### PR TITLE
feat(ingest):Remove event outcome signals from Sentry.

### PR DESCRIPTION
**Pull request by RaduW**
Remove event outcome signals in preparation to moving the outcome consumer to getsentry.

### CODE REVIEW

**Comment by jan-auer** [comment]
Since this outcomes consumer is now dead, can we remove it completely from the code base?

**Comment by untitaker** [comment]
@jan-auer this pr hasn't been created yet but we can remove it here

**Comment by RaduW** [comment]
I left the outcome consumer together with the fixed unit tests because I assumed it will be copied (and probably modified) into getsentry so I wanted to have a usable base that works without signals.

**Comment by untitaker** [comment]
Gonna create a replacing PR in a minute. We are now in a position to remove the consumer entirely.

**Pull request closed without merging**
