### PR TITLE
adding back in Alert Rule feature receiver

### PR DESCRIPTION
**Pull request by ehfeng**
Adding back a single, UI-triggered receiver to test whether the receiver processing works correctly at low load.

#nochanges

### CODE REVIEW

**Comment by dcramer** [comment]
The problem is almost certainly the event processed trigger

**Comment by ehfeng** [comment]
I agree, but given the downside of being wrong, I'm ok with being overly cautious here. And if it takes another week to redo the event_processed signal, I'd rather be collecting the UI metrics in the meantime.

**Review by mattrobenolt — APPROVED** [review]
I think we can be a little more generous here and add back any of the events triggered from the UI, but it's your call. I'm comfortable with any that aren't related to the processing pipeline.

**Comment by ehfeng** [comment]
Ok, adding in the other UI triggers then.

**Pull request merged**
