### PR TITLE
Testing charts demos

### PR DESCRIPTION
**Pull request by ayesha-omarali**
demos for highcharts, echarts, and chart.js (not for merging)
Titles link to storybook demo.

## All of them: 
- are responsive
- have tooltips
- have clear documentation & are maintained. 
- compatible with older browsers

### [Highcharts](https://storybook.getsentry.net/branches/testing-charts-demos/index.html?selectedKind=Discover%3A%20High%20Charts&selectedStory=default&full=0&down=1&left=1&panelRight=0&downPanel=storybooks%2Fstorybook-addon-knobs)
- Does everything you need or want
- compatibility 
- _cons_: 
  + A little bit of a learning curve
  + $$ 

### [Echarts](https://storybook.getsentry.net/branches/testing-charts-demos/index.html?selectedKind=Discover%3A%20Echarts&selectedStory=default&full=0&down=1&left=1&panelRight=0&downPanel=storybooks%2Fstorybook-addon-knobs): 
- Does almost everything
- All in JS
- Made to handle big data
- _cons_: 
  + Chinese company, so possible language barrier in support (they still have english docs)
  + Can be a bit confusing with color/design. 

### [chart.js](https://storybook.getsentry.net/branches/testing-charts-demos/index.html?selectedKind=Discover%3A%20Chart.JS&selectedStory=default&full=0&down=1&left=1&panelRight=0&downPanel=storybooks%2Fstorybook-addon-knobs)
- most popular of all the js charting libraries
- Nice animations on load
- More simple/clean style 
- _cons_: 
  + Canvas based and shares the same issues as non-vector formats
  + Limited features, only 6 graphs. 

 
Useful resource from [Hackernoon](https://hackernoon.com/9-best-javascript-charting-libraries-46e7f4dc34e6): 
image

### CODE REVIEW

**Comment by dcramer** [comment]
It might be worthwhile to do a quick evaluation of perf as well -- if nothing else than total dependency filesize

**Comment by dcramer** [comment]
@ayesha-omarali does echarts support zoom?

**Comment by ckj** [comment]
@dcramer I was curious about that too. It appears they do, and the interaction seems a little slicker than highcharts: https://ecomfe.github.io/echarts-examples/public/editor.html?c=grid-multiple

Also echart's dl to png button seems like it could come in handy:

**Comment by dcramer** [comment]
@ckj that seems to be scrolling less so than zooming

I do think echarts seems to be the most promising free option so ultimately I think we should answer: is the performance acceptable?

**Comment by billyvg** [comment]
I believe Baidu uses echarts, so I'm not too concerned about perf being a problem, bundle sizes shouldn't be a huge concern either since the charts should be lazy loaded. My concern would be around any potential support issues that come up and if language barriers would become a problem.

@ayesha-omarali can you check the bundle sizes for these? I would use `webpack-bundle-analyzer`

**Comment by ayesha-omarali** [comment]
@dcramer The only free charting library that has a nice zoom I've found is [react timesries charts](https://software.es.net/react-timeseries-charts/#/example/ddoshttps://software.es.net/react-timeseries-charts/#/example/ddos). 

Echarts is also arguably one of the most powerful charting libraries from my research. 

@billyvg on it!

**Comment by lynnagara** [comment]
echarts looks good, +1 on writing our own wrapper for it

**Pull request closed without merging**
