### PR TITLE
ci: Add Python vulnerability scanner

### PR DESCRIPTION
**Pull request by mattrobenolt**

### CODE REVIEW

**Comment by getsentry-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Changes to build requirements</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by mattrobenolt** [comment]
@dcramer do you have any thoughts on how this is implemented? This works by using https://pyup.io/safety/ which has a database for insecure packages https://github.com/pyupio/safety-db.

I chose not to use the actual CI integration they provide so it doesn't need access to repositories. This works just by calling `safety check` during the test runs, like a linter. This works by scanning all dependencies within the active virtualenv.

The downside is we don't get granular output in the GitHub report. If this is a big deal, I can try to figure out how to make the CI thing work.

**Comment by mattrobenolt** [comment]
Also, this is currently failing because of the issues I mentioned, so we'll want to flag this behind `|| true` or address them, while still dumping out the report without actually failing, so we can address the few issues by either ignoring them if they're not applicable, or patching.

**Comment by dcramer** [comment]
What is this waiting on?

**Review by mitsuhiko — APPROVED** [review]

**Pull request merged**
