### PR TITLE
feat(scim): add flags to team model

### PR DESCRIPTION
**Pull request by cathteng**
Folks will be able to provision teams using SCIM. These idp-provisioned teams will need to store a flag indicating them as such so that users added to that team via SCIM cannot leave and new users cannot be added from within Sentry.

Removed the migration test `test_0311_backfill_slack_settings.py` since it was breaking and those specific tests aren't useful once the migration has been merged.

### CODE REVIEW

**Review by wedamija — COMMENTED** [review]
Is it worth using a bool here? bitfields are painful to query on, the main benefits are:
 - storage savings: Probably not a lot of upside here since team isn't a large table
 - ease of adding new booleans: If you think you will add a lot of new bools to this table then it saves having to make a db migration for each column.

**Comment by markstory** [comment]
I would also recommend avoiding bitfields whenever possible. They are a pain to debug, query and update.

**Comment by cathyteng17** [comment]
@wedamija i removed the bitfield in favor of a bool

**Review by wedamija — APPROVED** [review]
lgtm. Just noting that we removed the migration test since it was breaking and those specific tests aren't useful once the migration has been merged.

**Pull request merged**
