### PR TITLE
fix(async-csv) Revert master to unblock production pipeline

### PR DESCRIPTION
**Pull request by leeandher**
I merged a branch that passed CI locally, but seems to be failing getsentry build pipeline. This PR should undo it.

### CODE REVIEW

**Comment by mattrobenolt** [comment]
Reverting migrations is not good. What's the reason for this?

**Comment by scefali** [comment]
@mattrobenolt This PR is causing getsentry tests to fail in Travis. I don't think the migrations would have run because the deploys were failing, correct?

**Comment by mattrobenolt** [comment]
Is it too hard to roll forward? Anyone locally could have pulled and run migrations in the meantime. on-premise builds, etc.

**Comment by scefali** [comment]
@mattrobenolt We aren't sure about the root cause yet. What about changing this PR to not include reverting the migration?

**Comment by mattrobenolt** [comment]
That's your calls to make. I'm not sure how good of an idea that is. For the future, usually we try to decouple migrations from the rest of the feature for multiple reasons, this being one of them.

**Comment by scefali** [comment]
@mattrobenolt Yea, 100% agree about decoupling migrations.

**Comment by scefali** [comment]
@leeandher Let's just make a PR to remove the tests you added and go from there.

**Pull request closed without merging**
