### PR TITLE
feat(alerts): add new tsdb functions for new condition

### PR DESCRIPTION
**Pull request by JoshFerge**
new TSDB function that allows for conditions to be passed to the uniq count function. will be used in the coming PR https://github.com/getsentry/team-issues/issues/40. This will only be used in that case, so my tests which cover the feature will cover this function, which is just a simple passthrough to the snuba `get_data` function.

### CODE REVIEW

**Review by snigdhas — APPROVED** [review]

**Review by wedamija — COMMENTED** [review]
This could probably do with some tests

**Comment by JoshFerge** [comment]
> This could probably do with some tests

given its only going to be used in one place, and given the simple nature of the logic, i felt fine not having any for this subsection of the feature. let me know if you disagree.

**Comment by JoshFerge** [comment]
additionally, as far as i know, TSDB is an abstraction we're looking to deprecate in any case? so i don't think future use of this is likely

**Comment by JoshFerge** [comment]
will add some quick tests and a comment on my next PR. thanks @wedamija

**Comment by wedamija** [comment]
> additionally, as far as i know, TSDB is an abstraction we're looking to deprecate in any case? so i don't think future use of this is likely

I think the only way it's deprecated is that we don't really want to expand it. But I don't know of any plans or need to kill the whole thing any time soon.

**Pull request merged**
