### PR TITLE
feat(javascript): Do not fail on missing filename for in_app detection

### PR DESCRIPTION
**Pull request by mitsuhiko**
This resolves a failure where the in_app detection fails if the sourcemap
does not contain a filename for a frame.

Fixes SENTRY-3XQ

### CODE REVIEW

**Review by alex-hofsteede — APPROVED** [review]
+ test?

**Comment by mitsuhiko** [comment]
@alex-hofsteede will put one in a separate PR. It's quite annoying to manufacture one but this seems to affect a fair number of users.

**Comment by mitsuhiko** [comment]
was less work than i thought because I could just null out the filenames to trigger this.

**Comment by getsentry-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Pull request merged**
