### PR TITLE
Revert "Revert "ref: replace deprecated index_together with indexes (#63776)""

### PR DESCRIPTION
**Pull request by asottile-sentry**
This reverts commit e24ccd3eb6213aa0910a69d1dbe7c4f70a32fff5.

I have applied the "dangerous" migration that was missing previously in singletenants causing the failure

### CODE REVIEW

**Review by armenzg — APPROVED** [review]

**Review by wedamija — APPROVED** [review]
This seems ok to me, index renames should be safe.

Could you elaborate on the problem you saw previously?

**Comment by asottile-sentry** [comment]
> This seems ok to me, index renames should be safe.
> 
> Could you elaborate on the problem you saw previously?

there's a comment in the linked PR

**Comment by wedamija** [comment]
> > This seems ok to me, index renames should be safe.
> > Could you elaborate on the problem you saw previously?
> 
> there's a comment in the linked PR

So an unapplied index in single tenant that we attempted to rename?

**Comment by asottile-sentry** [comment]
> > > This seems ok to me, index renames should be safe.
> > > Could you elaborate on the problem you saw previously?
> > 
> > 
> > there's a comment in the linked PR
> 
> So an unapplied index in single tenant that we attempted to rename?

yep yep

**Comment by asottile-sentry** [comment]
another one :/

```
ValueError: Found wrong number (0) of indexes for sentry_incidenttrigger(alert_rule_trigger_id, incident_id).
```

**Pull request merged**
