### PR TITLE
No longer unquote on release files.  This partially fixes #2280.

### LINKED ISSUE #2280: Release Endpoints Version Field Encoding
Currently due to a bug we require clients to multi encode incoming data in the version field.  The decoding happens in these places:

* first level decode in the webserver which decodes for the routing
* second decode is directly in the project endpoint

This means a client needs to double encode the data to get to what the code originally expects.

The original unquoting was done as an attempt to get slashes through the system but unfortunatley they cannot be carried in url path components.  A `%2f` gets resolved to `/` early on to support matching on paths and there is little we can do about that.  Some servers support passing through unquoted bytes but only if no high level matching has been performed.  However even in that case the django routing system requires unquoted paths to support matching which again would kill the slash.

Proposals:

* send the data into a query string, there all bytes survive
* figure out which wsgi servers we support and try to see if we can get to raw bytes for all of them, then build a reconciliation system to get to the raw bytes
* do greedy matching where we allow slashes to appear as part of the parameter.  eg: `/foo/<bar>` where `bar` can contain slashes itself.

### PR DESCRIPTION
**Pull request by mitsuhiko**
This just removes the bad unquotes.  I will add protection for
slashes not to appear in versions for the other files separately.

### CODE REVIEW

**Comment by mattrobenolt** [comment]
@mitsuhiko Wanna add a test for this? Since I assume this is a thing that we'll easily break again at some point.

**Comment by mitsuhiko** [comment]
@mattrobenolt could, but this basically means this endpoint is no longer special. eg: we no longer do anything with the version parameter that we do not do anywhere else. The value incoming is already unquoted, unquoting again just is never the right thing.

**Comment by mattrobenolt** [comment]
@mitsuhiko Can we merge this?

**Comment by mitsuhiko** [comment]
Yes! I thought we already did.

**Pull request merged**
