### PR TITLE
Use urllib2 as it correctly handles working with proxies

### PR DESCRIPTION
**Pull request by drcapulet**

### CODE REVIEW

**Comment by dcramer** [comment]
@mitsuhiko can we use sentry.http here?

**Comment by mattrobenolt** [comment]
We can't in the current state of affairs since this gets run from within `setup.py` without dependencies installed. So it's very likely that this would fail during say, an `sdist` run.

**Comment by mattrobenolt** [comment]
I don't think there's more we can do here, and urllib2 seems reasonable to me.

Thanks. :cake:

**Comment by mitsuhiko** [comment]
Yeah, urllib2 is probably the best we can do for now. +1 on this.

**Pull request merged**
