### PR TITLE
ref(codeowners) - Processing team got renamed

### PR DESCRIPTION
**Pull request by armenzg**

### CODE REVIEW

**Review by Swatinem — APPROVED** [review]

**Comment by IanWoodard** [comment]
Broke sentry ci: https://github.com/getsentry/sentry/actions/runs/8084434650/job/22089716402

**Comment by armenzg** [comment]
@IanWoodard how did it not fail in the PR?

**Comment by IanWoodard** [comment]
> @IanWoodard how did it not fail in the PR?

Because it was a backend test that failed and this PR didn't run any backend tests. We should probably update the path filter to include CODEOWNERS since it can cause a backend test to fail.

**Comment by armenzg** [comment]
> > @IanWoodard how did it not fail in the PR?
> 
> Because it was a backend test that failed and this PR didn't run any backend tests. We should probably update the path filter to include CODEOWNERS since it can cause a backend test to fail.

Maybe we should remove that test or fix it.

**Pull request merged**
