### PR TITLE
chore(CI): increase matrix count for backend-tests

### PR DESCRIPTION
**Pull request by corps**
As hybrid cloud work progresses, we need to run increasing number of tests in both the current deployment mode of SaaS and the future deployment modes of Control and Region silos.  To help alleviate the resulting increased build times, we increase the amount of backend instances running tests, spreading out the workload across more concurrent builds.

### CODE REVIEW

**Comment by mattgauntseo-sentry** [comment]
Adding @asottile-sentry as he looked at backend build times before and may know more on good / bad practice here.

**Review by asottile-sentry — APPROVED** [review]
the trade off here is decreased stability vs. faster build times -- the more parallel workers the more subject we are to random flakiness

**Review by dashed — APPROVED** [review]

**Comment by corps** [comment]
@asottile-sentry To that point, I'm willing to help tackle flakey tests as they are identifier -- what is the ideal feed back loop / workflow for doing so?  Like, is there a dashboard where we track test level instability over time?

**Comment by asottile-sentry** [comment]
> @asottile-sentry To that point, I'm willing to help tackle flakey tests as they are identifier -- what is the ideal feed back loop / workflow for doing so? Like, is there a dashboard where we track test level instability over time?

it's less the flaky tests but more that github actions infrastructure is flaky -- the more parallel job startups we run the more likely one will fail and therefore fail the whole commit

**Comment by corps** [comment]
Roger.

**Pull request closed without merging**
