### PR TITLE
fix(devserver): delete after stopping containers

### PR DESCRIPTION
**Pull request by joshuarli**
Currently, devserver will only start and stop containers on demand. But it doesn't delete. And just reuses the stopped container.

So if you `sentry devservices up` to upgrade say, Relay, and there is a stopped relay container, it will be reused. The new relay image won't be used to rebuild it.

There is also the relatively longstanding bug that very visibly blocks this PR: for some reason, things are called twice. As you can see, the first proxy removal succeeded, and of course the second fails. @untitaker is anything immediately obvious to you on why this is firing twice?

```
17:56:43 server  | SIGINT/SIGQUIT received...killing workers...
17:56:43 relay   | Stopping relay
17:56:43 proxy   | Stopping proxy
17:56:44 proxy   | Removing proxy
17:56:44 proxy   | Stopping proxy
17:56:44 proxy   | Error in atexit._run_exitfuncs:
17:56:44 proxy   | Traceback (most recent call last):
17:56:44 proxy   |   File "/Users/joshua.li/.local/share/pyenv/versions/2.7.16/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
17:56:44 proxy   |     func(*targs, **kargs)
17:56:44 proxy   |   File "/Users/joshua.li/dev/sentry/sentry/src/sentry/runner/commands/devservices.py", line 87, in exit_handler
17:56:44 proxy   |     container.stop()
-- snip --
17:56:44 proxy   | docker.errors.NotFound: 404 Client Error: Not Found ("No such container: cbff5757db85b1b011035e815cd2ccebe5d5d00967d9b79f8132201c2bf2fcef")
```

### CODE REVIEW

**Review by dashed — APPROVED** [review]

**Comment by untitaker** [comment]
Line 93-95 are registering the callback multiple times. I am not sure which of the events are overlapping in practice but I've made it a habit to keep this function idempotent.

I would rather see that `devservices up` would delete the stopped container if there is a newer image.

**Comment by joshuarli** [comment]
> I would rather see that devservices up would delete the stopped container if there is a newer image.

That's definitely a better solution, I'll look into it when I have some time. Gonna merge this to patch, though.

**Comment by joshuarli** [comment]
Oh, I see. @untitaker how do you feel about just removing the `atexit` handler? In 99.99% of cases people will stop devserver with SIGINT.

**Comment by untitaker** [comment]
That's prob fine

**Pull request merged**
