### PR TITLE
types(breadcrumb): update crumb

### PR DESCRIPTION
**Pull request by JonasBa**
Update breadcrumb type (this should also make type guards slightly nicer to use)

### CODE REVIEW

**Comment by JonasBa** [comment]
@priscilawebdev Something I noticed. Eof we have a `isBreadCrumbTypeDefault` type guard that asserts a breadcrumb is "default", this is the implementation.
```js
export function isBreadcrumbTypeDefault(
  breadcrumb: Crumb
): breadcrumb is Extract<Crumb, BreadcrumbTypeDefault> {
  return ![BreadcrumbType.HTTP, BreadcrumbType.NAVIGATION].includes(breadcrumb.type);
}
```
If you look above in the file however, you can see that we have more breadcrumbs defined -> `BreadcrumbTypeSystem`, `BreadcrumbTypeSession`, `BreadcrumbTypeNavigation`, `BreadcrumbTypeHTTP` and `BreadcrumbTypeDefault`, but the type guard only checks for HTTP and NAVIGATION meaning that Session and System would be marked as "default". Is this intended behavior or did we just forget to update the guard? If it's intended, we should throw in a comment there to explain why.

Similarly, the RawCrumb type is a union type of only `BreadcrumbTypeNavigation`, `BreadcrumbTypeHTTP` and `BreadcrumbTypeDefault`, should we add the `BreadcrumbTypeSession` and `BreadcrumbTypeSystem` here?

**Review by priscilawebdev — APPROVED** [review]

**Comment by priscilawebdev** [comment]
@JonasBa thanks for the heads up. Hmm I have worked on the breadcrumbs some years ago and I don't quite remember but I think it was intentional. I will add this to my todo list and can take a look when I have time

**Comment by JonasBa** [comment]
Perfect, thanks for the review. I wanted to make sure because at a quick glance it looks like we added breadcrumbs, but forgot to update the type guard 😅

**Comment by priscilawebdev** [comment]
@JonasBa sorry for a status update after ages 🙈 

Today I worked again on the breadcrumbs to fix an issue as you can see in the Pull Request https://github.com/getsentry/sentry/pull/41055 and after checking the `isBreadcrumbTypeDefault` function I think it makes sense to update it to be like the following:

```
export function isBreadcrumbTypeDefault(
  breadcrumb: Crumb
): breadcrumb is Extract<Crumb, BreadcrumbTypeDefault> {
  if (breadcrumb.type === BreadcrumbType.DEFAULT) {
    return true;
  }
  return !Object.values(BreadcrumbType).includes(breadcrumb.type);
}
```

but I noticed that updating this function breaks some unit tests and as I'm not very familiar with them I didn't feel confident to update it. Do you think you can take a look?

**Comment by JonasBa** [comment]
> @JonasBa sorry for a status update after ages 🙈
> 
> Today I worked again on the breadcrumbs to fix an issue as you can see in the Pull Request #41055 and after checking the `isBreadcrumbTypeDefault` function I think it makes sense to update it to be like the following:
> 
> ```
> export function isBreadcrumbTypeDefault(
>   breadcrumb: Crumb
> ): breadcrumb is Extract<Crumb, BreadcrumbTypeDefault> {
>   if (breadcrumb.type === BreadcrumbType.DEFAULT) {
>     return true;
>   }
>   return !Object.values(BreadcrumbType).includes(breadcrumb.type);
> }
> ```
> 
> but I noticed that updating this function breaks some unit tests and as I'm not very familiar with them I didn't feel confident to update it. Do you think you can take a look into it? it seems that you worked on them

I think it makes sense that it fails (the type guard before was not checking for all types of breadcrumbs, so some of them fall through). I think we need to look at it on a case by case basis to determine if it is the correct behavior

**Pull request merged**
