### PR TITLE
chore(api): Unpublish ProjectUserReportsEndpoint

### PR DESCRIPTION
**Pull request by iamrajjoshi**
The API is deprecated and Feedback team wants to unpublish it from the api docs. cc @aliu39

### CODE REVIEW

**Review by aliu39 — APPROVED** [review]

**Review by schew2381 — APPROVED** [review]
heads up that you also need to delete the old tests in apidocs

**Review by aliu39 — APPROVED** [review]
Fixes https://github.com/getsentry/sentry-docs/issues/10643

**Comment by idosun** [comment]
Hey folks, this API is still referenced in all the SDK docs for user feedback 

image

**Comment by iamrajjoshi** [comment]
> Hey folks, this API is still referenced in all the SDK docs for user feedback
> 
> image

cc @aliu39

**Pull request merged**
