### PR TITLE
fix(export): Fix broken export command after Django upgrades

### PR DESCRIPTION
**Pull request by BYK**
A few things this command relied on got deprecated and removed so it stopped working after these. This patch makes it work again. We should probably add tests around this to prevent further breakage.

### CODE REVIEW

**Comment by joshuarli** [comment]
Looks good, although you forgot to remove `from django.db.models import get_apps`.

@wedamija Do you think adding test coverage for this would be a blocker for imminent Django 1.10 upgrade? Briefly looking at the output from this command, it looks like tests would have to be regenerated pretty frequently... although maybe simply running it and seeing that it doesn't fail would be sufficient (for now)?

**Comment by BYK** [comment]
>Looks good, although you forgot to remove from django.db.models import get_apps.

lol

**Review by joshuarli — APPROVED** [review]

**Comment by wedamija** [comment]
> Looks good, although you forgot to remove `from django.db.models import get_apps`.
> 
> @wedamija Do you think adding test coverage for this would be a blocker for imminent Django 1.10 upgrade? Briefly looking at the output from this command, it looks like tests would have to be regenerated pretty frequently... although maybe simply running it and seeing that it doesn't fail would be sufficient (for now)?

@joshuarli Probably not worth blocking 1.10. I think we just need to have a simple test that runs the code and makes sure it doesn't error, because verifying the db output is probably unnecessary.

**Pull request merged**
