### PR TITLE
fix(tests): Fix symbolicator tests

### PR DESCRIPTION
**Pull request by wedamija**
Fixes a number of issues with the symbolicator integration test suite:

- Updates to `nightly` tags, which was missed in https://github.com/getsentry/sentry/pull/21368.
- Updates unreal test snapshots for https://github.com/getsentry/relay/pull/828.
- Removes abandoned snapshot files from the native test suite.

### CODE REVIEW

**Comment by jan-auer** [comment]
@wedamija I'm updating this PR and its description, thank you!

**Comment by jan-auer** [comment]
Of course `rg ':latest'` skips hidden files, not only ignored ones :/

**Comment by jan-auer** [comment]
Snuba integration tests are still failing with:

```
ImportError: No module named amqp
```

This failure existed on master prior to the symbolicator test failures. @BYK could this have to do with https://github.com/getsentry/sentry/pull/21390?

**Comment by BYK** [comment]
>@BYK could this have to do with #21390?

Quite possibly, but that indicates an issue with our dependency declarations. That error and this line indicates that `amqp` should never have been declared as optional: https://github.com/celery/kombu/blob/92b8c32717191e420bf30734247b7a3b2ef1af0f/requirements/default.txt#L2

**Review by untitaker — APPROVED** [review]

**Review by billyvg — APPROVED** [review]

**Comment by untitaker** [comment]
We need s&s to fix snuba tests

**Comment by billyvg** [comment]
@wedamija I'm gonna go ahead and merge this to unblock us

**Pull request merged**
