### PR TITLE
Google is deprecating OpenID logins starting April 20th, 2015.  Move to OAuth2 based logins.

### PR DESCRIPTION
**Pull request by rogerhu**
Changes that must be made:
1. Create a project at: https://console.developers.google.com
2. Select the project.
3. Navigate to `APIs & auth` -> `Credentials`.
4. Create a new Client ID.
5. Get the client ID and client secret and specify as `GOOGLE_OAUTH2_CLIENT_ID` and `GOOGLE_OAUTH2_CLIENT_SECRET`.
6. Add to authorized redirect URI's:

https://[sentry.yourdomain.com]/account/settings/social/complete/google-oauth2/

### CODE REVIEW

**Comment by dcramer** [comment]
So not looking forward to dealing with this. Thanks for putting this together, though!

**Comment by rogerhu** [comment]
Fortunately it was pretty painless besides cleaning out users with dup emails in our system.  I think that if a user had a username/password login and authenticated via OpenID, those accounts were not being linked.  Moving to a 3rd auth option would break Sentry logins.  We fixed the issue by cleaning out those username/password-based accounts.

**Comment by rogerhu** [comment]
Made one more push..https://github.com/rogerhu/sentry/commit/48ad2bbdc6800b31a8c9e8f127ed246ad47fcec1 turns off django-social-auth  from readjusting the session duration to be the 1-hour token that Google grants.  If you decide to upgrade this package just want to mention that this setting might likely to be different..

**Comment by rogerhu** [comment]
Reminder: 11 days until OpenID goes away!

**Comment by dcramer** [comment]
Of point, we decided we're probably going to completely kill social auth.

A number of reasons, but one being it conflicts with SSO (its too confusing to users).

I'm still trying to figure out what our story is for OSS/on premise. We may decide to open source our google SSO implementation, but that is still up in the air.

**Comment by dcramer** [comment]
We've removed Google so I'm going to close this out.

**Comment by streeter** [comment]
@dcramer, have you guys decided what you're doing with a Google SSO plugin? We use it with our install, so can't upgrade for now.

**Comment by dcramer** [comment]
@streeter right now we're keeping it closed source. If we decide to change that it still won't happen for a little while. It's *likely* it will happen, its just unclear how big of a deal it'll be at this time and we haven't fully finished the SSO backend.

**Comment by pivotal-casebook** [comment]
@dcramer We're still running the 6.3 version of Sentry and are having problems authenticating with Google now.  We're trying to determine the most expedient way to get our authentication working again. Is the better path to upgrade to 7.X and try rogerhu's steps above?  Or is it possible to get the new Google OAuth2 working with 6.3?  If the latter, do you have any pointers (we've tried but haven't been able to get it working).

**Comment by dcramer** [comment]
@pivotal-casebook in theory you just need to swap out the AUTH PROVIDERS settings so it loads the correct django-social-auth backend (vs the openid one). I think it'd be as simple as saying

AUTH_PROVIDERS['google_oauth2'] = AUTH_PROVIDERS.pop('google')

Though I don't guarantee that actually is correct/works. It'll also require all accounts to re-auth/etc

**Pull request closed without merging**
