### PR TITLE
feta(perf-views) Add an onboarding state for performance views

### PR DESCRIPTION
**Pull request by markstory**
Expose the has_transactions flag on projects to conditionally display an onboarding state for performance views. The icon is temporary until we get more polished assets from creative.

The getting started state has some copy paste from releases v2 but I'll clean that up separately.
Screen Shot 2020-05-22 at 10 33 45 AM

### CODE REVIEW

**Review by wmak — COMMENTED** [review]
Could we remove the charts or prevent them from loading? In my local env I still see a call to `events-stats`

**Comment by dashed** [comment]
@markstory I think @doralchan preferred the empty state to be full page.

**Comment by markstory** [comment]
@dashed Ok I'll find out and adapt from there.

**Comment by markstory** [comment]
@dashed Update based on Dora's feedback to hide all the content and controls during onboarding.

**Review by dashed — APPROVED** [review]

**Pull request merged**
