### PR TITLE
[auth] bind user context immediately on login

### PR DESCRIPTION
**Pull request by dcramer**

### CODE REVIEW

**Comment by tkaemming** [comment]
I'm a little confused — since the call to `django.contrib.auth.login` (or `_login` here) sets `request.user`, shouldn't that be picked up in the [`DjangoClient`](https://github.com/getsentry/raven-python/blob/a1f59164990b624dd895f0b60d3e342c9ba6060a/raven/contrib/django/client.py#L142) and sent as the user data when `capture` is called?

**Comment by dcramer** [comment]
@tkaemming yeah seemingly it should actually -- maybe we dont need this change (though I didn't confirm if our User model conforms to that interface)

**Comment by tkaemming** [comment]
Yeah — I was a little confused how it wouldn't be picked up, and if it was something we had to explicitly bind ourselves it seems like it might have made more sense to do it in `raven-python` via the `user_logged_in` signal.

**Comment by dcramer** [comment]
Its possible that the case im assuming happened, didnt actually happen. Will close this since it should be irrelevant.

**Pull request closed without merging**
