### PR TITLE
Add support for Safari Pinned Tabs

### LINKED ISSUE #3865: Support Safari Pinned Tabs
https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/pinnedTabs/pinnedTabs.html

If you pin a tab, right now, it will just put the letter of your organization as the pin "icon"

### PR DESCRIPTION
**Pull request by michaelhelmick**
Fixes #3865

aug-04-2016 15-47-18

I couldn't find a reference to the "red" used for the Sentry avatar and such, so I took the color from the Github avatar.

Also, I used the SVG given in the branding page which is why the icon looks a little small.

screenshot 2016-08-04 15 58 05
screenshot 2016-08-04 15 58 11

If you could provide a SVG stripped of whitespace, I'd be happy to swap it out.

---

This change is [Reviewable](https://reviewable.io/reviews/getsentry/sentry/3866)

### CODE REVIEW

**Comment by mattrobenolt** [comment]
Hi @michaelhelmick.

@ckj this seems fine to me?

The only feedback I'd have would be to minify the svg, but I can do that after merging.

**Comment by michaelhelmick** [comment]
Up to you. If you have a preferred library to minify it, I can do it on my end or you can do it after merge.

**Comment by ckj** [comment]
@michaelhelmick neat! 👍  on my end.

**Comment by mattrobenolt** [comment]
thx homie 🍦

**Pull request merged**
