### PR TITLE
fix(ui): Use link for "Take me to the issue stream"

### PR DESCRIPTION
**Pull request by evanpurkhiser**

### CODE REVIEW

**Comment by malwilley** [comment]
Doesn't this change the visual? Do we want that?

**Comment by evanpurkhiser** [comment]
I mean, it's not a button, it's using `priority="link"` so

**Comment by malwilley** [comment]
> I mean, it's not a button, it's using `priority="link"` so it should be similar I think right?

I'm seeing `priority="primary"`? https://github.com/getsentry/sentry/pull/42861/files#diff-a3429f8c012d38d51f272eb050c97fc28fa6b1e503771747a35fc56919a62cd0L78

**Comment by evanpurkhiser** [comment]
oops hahaha, you're right 🤪

**Pull request closed without merging**
