### PR TITLE
ci(relocation): run tests in monolith-db mode

### PR DESCRIPTION
**Pull request by ghost**
Run relocation tests in monolith-db mode. I've asserted that this will be removed soon, to be combined with the "main" test suite, to fall in line with recent improvements.

### CODE REVIEW

**Comment by azaslavsky** [comment]
> This will become unnecessary in the near future (Nov 11-ish?) as relocation code moves to not use whole-database transactions.

This isn't correct - relocation code running on self-hosted will still use a single atomic transaction across the entire monolithic DB, and will continue to do so indefinitely. That means we'd like to be able to maintain test coverage for that path indefinitely as well. Hopefully this is still okay?

**Comment by bukzor-sentryio** [comment]
> > This will become unnecessary in the near future (Nov 11-ish?) as relocation code moves to not use whole-database transactions.
> 
> This isn't correct - relocation code running on self-hosted will still use a single atomic transaction across the entire monolithic DB, and will continue to do so indefinitely. That means we'd like to be able to maintain test coverage for that path indefinitely as well. Hopefully this is still okay?

We still want to get of this separate special-case test suite, to fall in line with recent improvements, somehow. I've got the method wrong though.

**Comment by azaslavsky** [comment]
I think the current plan is to leave self-hosted on a monolithic DB for the foreseeable future, so the change is unlikely to come from the deprecation of the monolith codepath that this PR is meant to test. Unless you were referring to a different method of testing besides creating a new CI generator in the Makefile?

**Comment by bukzor-sentryio** [comment]
> Unless you were referring to a different method of testing besides creating a new CI generator in the Makefile?

Yes, exactly. The thought is to run these as a subprocessed pytest. Or something.

**Review by azaslavsky — APPROVED** [review]
LGTM, thank you for adding this! :)

**Pull request merged**
