### PR TITLE
feat(perf): Improve permissions and auditing on options endpoint

### PR DESCRIPTION
**Pull request by k-fish**
Makes modifying system options via /manage require 'options.admin'
permission, which can be added via /_admin. Also adds a simple audit log
on changes to options through this endpoint.

This is some prerequisite work since we will be adding quite a few options 
for the upcoming performance issues project.

Screen Shot 2022-08-31 at 3 40 47 PM

### CODE REVIEW

**Review by dcramer — APPROVED** [review]
lgtm solid improvement

**Comment by mitsuhiko** [comment]
@k-fish Does this not break the settings page for on-prem? Pretty sure we are not handing out the new permission to self-hosted superusers.

**Comment by k-fish** [comment]
@mitsuhiko I thought the SENTRY_PERMISSIONS was part of the default set, how do we get it into the defaults for self-hosted super users?

**Comment by k-fish** [comment]
I was checking how they were used and saw superadmin had them appended https://github.com/getsentry/sentry/blob/f93f333790c61c7134a7b1a9e80a318509cc31c3/src/sentry/models/userrole.py#L64

**Pull request merged**
