### PR TITLE
fix(py3): Correct some divisions that should be integer

### PR DESCRIPTION
**Pull request by evanpurkhiser**

### CODE REVIEW

**Review by BYK — APPROVED** [review]

**Comment by BYK** [comment]
Shall we do `from __future__ import divison` at places to start checking for this? -- https://docs.python.org/2.7/library/__future__.html

**Comment by EvanPurkhiser** [comment]
I'm also OK just being explicit about using double `//`

**Comment by EvanPurkhiser** [comment]
Ah you're saying import it AND use `//` right

**Comment by BYK** [comment]
@EvanPurkhiser 
>Ah you're saying import it AND use `//` right

Yup :)

**Pull request merged**
