### PR TITLE
Handle long request paths better

### PR DESCRIPTION
**Pull request by ckj**
**Before:**

screen shot 2016-06-16 at 1 09 46 pm

**After:**

screen shot 2016-06-16 at 1 06 32 pm

/cc @getsentry/ui

### CODE REVIEW

**Comment by benvinegar** [comment]
👍

**Comment by mattrobenolt** [comment]
Could we put the full url in the `title` or something so on hover you can see it?

**Comment by ckj** [comment]
@mattrobenolt good idea. added

**Comment by dcramer** [comment]
You can use the shiny new ``<Truncate>`` tag ;)

**Comment by ckj** [comment]
Cool, now this uses `<Truncate>` and is left trimmed (which is way better for urls).

**Comment by skyrpex** [comment]
Woah, that was so fast! Thanks!

**Pull request merged**
