### PR TITLE
feat(ui): Use markdown to show app detail overview

### PR DESCRIPTION
**Pull request by scefali**
This PR enables the use of markdown text in the app detail overview. Example:

Screen Shot 2019-06-20 at 1 46 32 PM

### CODE REVIEW

**Review by mattrobenolt — COMMENTED** [review]
This is preventing XSS and other maliciously rendered tags, right? Since this is all user generate content, we need to make sure we don't allow everything Markdown allows.

**Comment by scefali** [comment]
@mattrobenolt Good question. I am using the marked import from `/app/utils/marked.jsx` which has sanitize=true by default. That should prevent malicious tags and XSS, correct?

**Comment by mattrobenolt** [comment]
I dunno, I'm asking so someone can investigate. :)

My concern is that markdown allows fully embedding HTML. So I feel like ideally we'd want to not allow that at all if we can? People can embed images from sources we don't trust with normal markdown, etc. You can embed `<h1>` tags, `<input>` tags, etc. I know these are all currently issues because they can happen in comments.

So I'm asking if we can explicitly acknowledge these things and either accept that people can do it and it'll be fine, or figure out how to restrict to a subset of things we find acceptable.

As a good example, GitHub's markdown rendering here restricts which elements it'll render. You can't render a `<form>` or something.

**Comment by scefali** [comment]
@mattrobenolt I did a quick test to see what happens when you try to embed HTML in this input. When you have `sanitize=false`, you do see the HTML elements rendered:

Screen Shot 2019-06-21 at 9 51 43 AM

However, when you set`sanitize=true`, the HTML just gets rendered as text:

Screen Shot 2019-06-21 at 9 51 16 AM

So I don't think there is any way you could inject malicious code as long as you sanitize the inputs which is what I am doing.

**Comment by mattrobenolt** [comment]
Cool, thanks for explaining.

**Comment by scefali** [comment]
@mattrobenolt BTW, I think there is an easy way to prevent the HTML elements from being rendered in comments if we want to fix that. I see in some places in the code base we are importing `marked` directly from the package which is not sanitizing by default instead of the one we have in `app/utils/marked` which has `sanitize=true`. Not sure if this is by design.

**Comment by mattrobenolt** [comment]
We should look at them immediately because our stuff prevents a whole class of XSS, and if we’re not going through our modifications, we have security issues.

**Review by MeredithAnya — APPROVED** [review]

**Pull request merged**
