### PR TITLE
fix(relay): Disable projects with crashing get_project_config

### PR DESCRIPTION
**Pull request by untitaker**
We've had one incident related to double-pickling where the entire batch
was failed even though it didn't have to fail. We'd have preferred just
losing events for one project.

### CODE REVIEW

**Review by tonyo — APPROVED** [review]
Sanity checking: relay will gracefully handle the missing config in the returned batched response, right?

**Comment by untitaker** [comment]
There's no missing config because we already have written to the key at the beginning of this for-loop. We're using the same codepath as with missing projects.

**Comment by tonyo** [comment]
@untitaker Ah, you're right, but:
```
configs[str(project_id)] = {"disabled": True}
```
Doesn't relay do something more... aggressive in this case, e.g. negative caching?

**Comment by untitaker** [comment]
afaik the value for this is `cache.miss_expiry` which is set to 1 minute

**Comment by jan-auer** [comment]
> afaik the value for this is `cache.miss_expiry` which is set to 1 minute

That is correct. 

Just to be clear: This means Relay will now _drop events_ instead of buffering them until the project state comes back. This goes against initial design principles. Ideally, we would respond with a backoff response.

**Comment by untitaker** [comment]
@jan-auer I think we can revert/tweak this PR once the buffering works well, right now we know it doesn't behave too well with response times. Also we may want to consider buffering events per-project and enforcing limits per-project.

**Comment by untitaker** [comment]
should change this such that it actually ends up buffering instead of dropping in relay. got word from anton that we can probably buffer for single projects just fine

**Pull request closed without merging**
