### PR TITLE
test(backup): Remove @targets decorator, improve assert msg

### PR DESCRIPTION
**Pull request by azaslavsky**
Retries https://github.com/getsentry/sentry/pull/61719.

### CODE REVIEW

**Review by hubertdeng123 — APPROVED** [review]

**Comment by azaslavsky** [comment]
@GabeVillalobos any thoughts on whether I should be concerned about the first error (`OutboxFlushError`)? Should I use a burst runner or similar to avoid it and make sure everything gets flushed?

**Comment by GabeVillalobos** [comment]
> @GabeVillalobos any thoughts on whether I should be concerned about the first error (`OutboxFlushError`)? Should I use a burst runner or similar to avoid it and make sure everything gets flushed?

@azaslavsky It depends, have we root caused the connection failure behind it? Are we just flooding the system with RPCs or was there some sort of partial outage?

**Comment by azaslavsky** [comment]
Afaict I don't think the test itself is failing? Or at least, I've never seen it when running locally or when running presubmit CI. I think this has been happening for a while, but this (mechanical) refactor that touched this particular test caused it to be surfaced now. May be wrong about that though - not 100% sure how `sentry-io` bot works, or what kind of errors it reports (does it only report errors from tests that were touched by this PR? Can it report errors that would otherwise cause the test to pass?).

Mostly I'm just wondering if it's an easy fix - doesn't seem to be causing too much trouble atm.

**Comment by GabeVillalobos** [comment]
@azaslavsky Ohhh it's a test failure! Sorry, I thought it was an error in one of our deployments. Yeah this seems like a transient error. We can revisit the test if we find it continues to be flaky.

**Pull request merged**
