### PR TITLE
ref(api): Remove old unused saved search and saved search user default rows (SEN-711)

### PR DESCRIPTION
**Pull request by wedamija**
Now that we've moved off of Sentry 9 we no longer support these types of saved searches. This is
just a data migration to clean up the unused data, will follow up with code changes after.

I've confirmed that these types of searches are no longer being accessed at the project level, via
Datadog.

This also removes the receiver that auto creates default searches for a project. This should go live before we run the data migration.

### CODE REVIEW

**Comment by markstory** [comment]
If the receiver needs to be dropped before the migration is applied should that be done in a separate pull request that is merged first?

**Comment by wedamija** [comment]
> If the receiver needs to be dropped before the migration is applied should that be done in a separate pull request that is merged first?

It's not super important because I'm just going to ask ops to run after deploy, but I can split up if you think it makes more sense.

**Comment by markstory** [comment]
Just noticed the migration `is_dangerous`.

**Review by markstory — APPROVED** [review]

**Comment by BYK** [comment]
RIP south migrations. I hope we don't have these things lingering around still.

**Pull request closed without merging**
