### PR TITLE
Sort releases by creation date when available

### PR DESCRIPTION
**Pull request by dcramer**
@getsentry/infrastructure

---

This change is [Reviewable](https://reviewable.io/reviews/getsentry/sentry/3942)

### CODE REVIEW

**Comment by mattrobenolt** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/sentry/api/paginator.py, line 200 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/3942#-KPEqjev1nZ0cRiSUrzq:-KPEqjev1nZ0cRiSUrzr:b-23fcg) ([raw file](https://github.com/getsentry/sentry/blob/315608865dd8545f41753e712042433925339947/src/sentry/api/paginator.py#L200)):*
> ```Python
>         results = list(queryset[offset:stop])
>         if cursor.value != limit:
>             results = results[::-1][:limit + 1][::-1]
> ```

Why are you reversing twice on this list?

The same thing can be achieved by just `results[-(limit+1):]`

Also, it's not clear to me why you're trying to keep the last "limit". Wouldn't you want the first results?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3942)*

**Comment by dcramer** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/sentry/api/paginator.py, line 200 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/3942#-KPEqjev1nZ0cRiSUrzq:-KPEtZbR8ZjmEypUMd8b:b-fw427f) ([raw file](https://github.com/getsentry/sentry/blob/315608865dd8545f41753e712042433925339947/src/sentry/api/paginator.py#L200)):*
<details><summary><i>Previously, mattrobenolt (Matt Robenolt) wrote…</i></summary>
> Why are you reversing twice on this list?
> 
> The same thing can be achieved by just `results[-(limit+1):]`
> 
> Also, it's not clear to me why you're trying to keep the last "limit". Wouldn't you want the first results?
</details>
The paginator returns extra results to know "are there more".

The reason its reversing the list is (im pretty sure) laziness

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3942)*

**Comment by mattrobenolt** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/sentry/api/paginator.py, line 200 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/3942#-KPEqjev1nZ0cRiSUrzq:-KPEtqfxE-c_zitmww23:bytx1ff) ([raw file](https://github.com/getsentry/sentry/blob/315608865dd8545f41753e712042433925339947/src/sentry/api/paginator.py#L200)):*
No, I understand what it's doing. I just don't understand why you're trimming off the "right" side.

```python
>>> [1,2,3,4,5,6][::-1][:2+1][::-1]
[4, 5, 6]
```

Wouldn't you want the first 3 results instead of the last 3 given a limit of 2.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3942)*

**Comment by dcramer** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/sentry/api/paginator.py, line 200 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/3942#-KPEqjev1nZ0cRiSUrzq:-KPEvUkypWKDcVx04GiP:bkr9if8) ([raw file](https://github.com/getsentry/sentry/blob/315608865dd8545f41753e712042433925339947/src/sentry/api/paginator.py#L200)):*
<details><summary><i>Previously, mattrobenolt (Matt Robenolt) wrote…</i></summary>
> No, I understand what it's doing. I just don't understand why you're trimming off the "right" side.
> 
> ```python
> >>> [1,2,3,4,5,6][::-1][:2+1][::-1]
> [4, 5, 6]
> ```
> 
> Wouldn't you want the first 3 results instead of the last 3 given a limit of 2.
</details>
IIRC it's always sorted in a specific order, thus we always trim from one side. I don't touch this code much, so I'd suggest skimming through it to get an idea what it needs. It's a fairly complex bit of a logic though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3942)*

**Comment by mattrobenolt** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/sentry/api/paginator.py, line 200 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/3942#-KPEqjev1nZ0cRiSUrzq:-KPEwtsfDchZHFxM90ao:bojeqrz) ([raw file](https://github.com/getsentry/sentry/blob/315608865dd8545f41753e712042433925339947/src/sentry/api/paginator.py#L200)):*
<details><summary><i>Previously, dcramer (David Cramer) wrote…</i></summary>
> IIRC it's always sorted in a specific order, thus we always trim from one side. I don't touch this code much, so I'd suggest skimming through it to get an idea what it needs. It's a fairly complex bit of a logic though.
</details>
wfm, then just change so it's not flipping twice since doing the negative slice yields the same results.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3942)*

**Comment by filipnavara** [comment]
After the last change to use COALSCE at database level it's not necessary to introduce CompositeOffsetPaginator, is it?

**Comment by mattrobenolt** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/sentry/api/paginator.py, line 176 \[r2\]](https://reviewable.io:443/reviews/getsentry/sentry/3942#-KPF04vjx__caSyNIijG:-KPF04vkn4Guhr5_W_cS:b-t94mm) ([raw file](https://github.com/getsentry/sentry/blob/a27fc5748afd0d164d2dd19ad79e545383f3c118/src/sentry/api/paginator.py#L176)):*
> ```Python
> 
> 
> class CompositeOffsetPaginator(BasePaginator):
> ```

This isn't even needed now that you're using `COALESCE`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3942)*

**Pull request merged**
