### PR TITLE
fix(settings) Move project settings to new paths

### PR DESCRIPTION
**Pull request by markstory**
Add an additional `projects` segment to the settings routes to allow them to be conflict free with organization settings. This allows organizations that have an `integrations` project to once again access their settings.

I've stuck with the `/settings` prefix as it keeps all the settings routes together. I felt that having some settings under `/organizations` and other under `/settings` would be harder to remember, and harder to navigate via direct URL entry.

I haven't added aliases for the old settings, but am open to doing that if people feel there are likely browser bookmarks out in the wild.

Fixes ISSUE-277

### CODE REVIEW

**Comment by markstory** [comment]
I've also checked getsentry for project settings URLs and didn't find any.

**Comment by EvanPurkhiser** [comment]
Didn't we originally have something like this @billyvg and we decided to remove the `projects` portion of the URL?

**Review by lynnagara — APPROVED** [review]
👍 this is great!

**Comment by billyvg** [comment]
> Didn't we originally have something like this @billyvg and we decided to remove the `projects` portion of the URL?

Yeah we're re-adding it because there's been conflicts.

**Comment by lynnagara** [comment]
What are we going to do about stuff like this https://github.com/getsentry/sentry/blob/master/src/sentry/web/urls.py#L493? Why do we have that and are these redirects still gonna work?

**Pull request merged**
