### PR TITLE
test(ui): Ignore test file coverage

### PR DESCRIPTION
**Pull request by scttcper**
We want to know how much of our actual components are covered not tests

### CODE REVIEW

**Comment by scttcper** [comment]
i think this is doing what i want, to not send data at all for coverage files
image

**Comment by evanpurkhiser** [comment]
I think there was some reason we wanted to include the tests as well. Maybe @billyvg remembers.

**Comment by billyvg** [comment]
I don't remember, it may have been just experimenting with codecov. Do test files even produce a coverage file? It could have been trying to track unrun tests?

**Comment by scttcper** [comment]
@billyvg it seems to create the files, but codecov doesn't report any coverage for those files

**Review by armenzg — APPROVED** [review]
We do not generate coverage for the tests itself.

**Pull request merged**
