### PR TITLE
chore: disable membership settings for developer plans

### PR DESCRIPTION
**Pull request by ameliahsu**
since developer plans can only have 1 member, we want to disable membership settings for organizations on a developer plan. we can do this using a new `component:organization-membership-settings` hook (see https://github.com/getsentry/getsentry/pull/15697 for full context)

Screenshot 2024-11-12 at 10 51 42 AM

### CODE REVIEW

**Review by evanpurkhiser — COMMENTED** [review]
This belongs in getsentry no?

**Comment by evanpurkhiser** [comment]
Tooltip also feels like the wrong choice here. This should be an alert banner no?

**Comment by sentaur-athena** [comment]
@evanpurkhiser what's missing in the context here is that every single setting option in this picture have that tooltip. I agree with you that it can be handled better but I don't think it's beyond the scope of this PR.

**Comment by scttcper** [comment]
@sentaur-athena we don't put billing/plan related content in this repo currently

**Review by scttcper — APPROVED** [review]

**Pull request merged**
