### PR TITLE
feat(workflow): Add environment selector to Metric Alert Rule editor

### PR DESCRIPTION
**Pull request by billyvg**
This adds an environment selector to the Metric Alert Rule editor.

### CODE REVIEW

**Review by iProgramStuff — COMMENTED** [review]
This looks fine, but what is the plan for using this environment field? I see it's passed in alert rule API, but alert rule models and serializers don't have an environment field.

**Comment by iProgramStuff** [comment]
Backend support coming in this PR:
https://github.com/getsentry/sentry/pull/16621

**Review by markstory — APPROVED** [review]
Looks good to me.

**Comment by billyvg** [comment]
@iProgramStuff I'm going to merge this in ahead of the backend since alerts are feature flagged anyway

**Pull request merged**
