### PR TITLE
ref: remove common name exports

### PR DESCRIPTION
**Pull request by JonasBa**
Trying to cleanup some low-hanging fruit around exports namespace - these values seem like they could just be inlined. If you feel like these provides good value to you I'm totally fine leaving as is btw.

### CODE REVIEW

**Review by ryan953 — APPROVED** [review]
I'd have gone with `1_000_000` instead of the sci-notation, or exponents esp for the million and billion values. Exponents seem popular though, maybe they were added earlier before babel supported that new number format.

I did notice other related code in sentry, and also getsentry has similar, also in a generically  named file, so no wonder people can't find and re-use
https://github.com/getsentry/getsentry/blob/ae8c569ada6695f04605e4c1e986c752ea5505c1/static/getsentry/gsApp/constants.tsx#L8-L14

Seems like a this is a spot change, i'd prefer a more wholistic vision of for this formatting/units code.

Approved because it achieves the goal of 3 exports removed.

**Comment by JonasBa** [comment]
@ryan953 I am in favor of not having shared consts for things like these. They are easy to inline and make reading and debugging the code more straightforward.

**Comment by ryan953** [comment]
megabytes vs mebibytes is a distinction that not all folks might know or appreciate, which is why i kinda put that into a separate bucket from a straight up Million. Depends on context too right.

But I agree that it's just as easy to read or copy+paste the digits, it's very straight forward this way.

**Comment by JonasBa** [comment]
> megabytes vs mebibytes is a distinction that not all folks might know or appreciate, which is why i kinda put that into a separate bucket from a straight up Million. Depends on context too right.
> 
> But I agree that it's just as easy to read or copy+paste the digits, it's very straight forward this way.

Yes, exactly, so for example even if you were to reuse a value like this, you still need to look it up and see if it's what you want, which is more work than just inlining it in the first place.

**Comment by JonasBa** [comment]
I realize I should probably take a step back here - my original issue is that I didn't want the value exported, but I also inlined it, which eod is a preference and isn't really a valid argument, folks can dry up the var however they like and it's not up to me to decide this as the main issue is just with polluting the exports namespace. I will revert the inline change, but preserve the removal of exports.

**Comment by scttcper** [comment]
const enum would inline it

**Pull request merged**
