### PR TITLE
fix(integrations) Replace vsts logo with azure devops

### PR DESCRIPTION
**Pull request by markstory**
Preview of the new file is [here](https://github.com/getsentry/sentry/blob/b8f11f33dcd12b1896216d02d809d0bde9dceb96/src/sentry/static/sentry/app/icons/icon-vsts.svg)

Fixes APP-710

### CODE REVIEW

**Review by lauryndbrown — COMMENTED** [review]
Hmm... Mark because this is just an svg file it doesn't give anyone a good sense of what's changed. Can you take a screenshot of an area in the UI where this shows up, so that @saragilford can give her thoughts?

**Comment by benvinegar** [comment]
Rich diff is here: https://github.com/getsentry/sentry/pull/10392/files?short_path=e7f706f#diff-e7f706f2328aaf915f08548bd468b279

A screenshot would be nice, but I think we can move forward given that the shape of the images is pretty similar and can't really cause any harm.

**Comment by markstory** [comment]
screen shot 2018-11-01 at 4 55 36 pm

**Review by lauryndbrown — APPROVED** [review]
Thanks! Looks great

**Pull request merged**
