### PR TITLE
Add a quiet flag to the clean up task

### LINKED ISSUE #2794: Cleanup task shows progress bar on stderr
This makes silencing the cleanup task for cron consumption dangerous, because I would have to ignore real errors too.
For sentry 7 I posted a similar issue in the past, #1798 so you might have a Déjà vu
I didn't reopen that other issue, because this time it is probably caused by something else.

### PR DESCRIPTION
**Pull request by do3cc**
This would fix #2794
This is an alternative implementation. The other implementation
is in #2795

### CODE REVIEW

**Comment by do3cc** [comment]
While I wanted to write here why there are no tests, I realized that I was wrong. I will add tests, but not today.

**Comment by do3cc** [comment]
I was not sure if it would be better to write an echo method behaving differently wether the quiet flag was there or not. I decided against it. This way has many ifs but feels cleaner to me. But I'll happily change it if you disagree.

**Comment by dcramer** [comment]
tbh I think this is a good approach to the alternative solution. We can do something more heavy handed if its really needed, but if this solves the concerns then :+1:

(also no need for tests as this is a trivial change)

Thanks!

**Comment by mattrobenolt** [comment]
@do3cc sorry, I didn't get to look at this before it was merged, but I changed it from `--quiet` to `--silent` since we already have a precedent for `--silent` on a number of other commands, so stick with uniformity. :)

See: 281a5ae7ce5e5255666a58d6bb65de4ff7b28d1e

**Comment by do3cc** [comment]
I am sorry, I didn't check for similar flags before

**Pull request merged**
