### PR TITLE
feat(react): Fix select2 css in Custom Resolution Modal

### PR DESCRIPTION
**Pull request by billyvg**
* Fix css in Custom Resolution Modal

Prod:
image
PR:
image

### CODE REVIEW

**Comment by dcramer** [comment]
The data bit is invalid here right (In your description)?

**Review by dcramer — APPROVED** [review]

**Comment by billyvg** [comment]
right, `data` is only invalid if the field we're using is a `<select>`. in `<Select2TextField>` and the autocomplete one it's fine because the select2 field is an `<input>`

**Comment by dcramer** [comment]
@billyvg sorry I meant I didn't see any relevant changes to that point here

**Comment by billyvg** [comment]
Ah, woops, thanks

**Comment by billyvg** [comment]
Oh that's because you fixed that last week

**Pull request merged**
