### PR TITLE
fix(integrations): Add pagination to slack API calls

### LINKED ISSUE #10056: New global Slack integration only pulls back 1000 channels when finding the channel ID
## Important Details

How are you running Sentry?

* [X] On-Premise docker [Version 9.0.0]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

I was attempting to add in Slack integration using the new global integration. I tried to add one of our channels, but it kept saying it "does not exist or has not been granted access"

After poking around for a while, I realized that we were only getting back 1000 channels, and that there is token-based pagination happening per https://api.slack.com/methods/channels.list

## Steps to Reproduce

1. Integrate with a Slack instance with > 1000 channels
2. Attempt to add an alert to a channel that is after the first 1000 channels added
3. See it fail

### What you expected to happen

I would expect it to paginate until all channels are returned

### Possible Solution

I'm working right now on implementing basic pagination to get this working for us in the short term. I will update this task if I get something put together.

### PR DESCRIPTION
**Pull request by viteksafronov**
Split requests to chunks of 1000 entities. Fixes GH-10056
Unlike this PR https://github.com/getsentry/sentry/pull/14848 it still uses the legacy API

### CODE REVIEW

**Comment by PaarthB** [comment]
@viteksafronov There are no reviewers for this. So how will this get approved?

**Comment by PaarthB** [comment]
@EvanPurkhiser @mattrobenolt Could you look into this MR

**Review by PaarthB — APPROVED** [review]

**Review by evanpurkhiser — APPROVED** [review]
This looks good to me. @mnoble could I get your eyes on this real quick for sanity, and I think we can merge this in.

Thank you very much @viteksafronov for the PR!

**Comment by mnoble** [comment]
Looks good to me. 👍

**Comment by PaarthB** [comment]
Will it be possible to merge this without all the tests passing?

**Comment by PaarthB** [comment]
@mattrobenolt @EvanPurkhiser with this fix, is this going to be observed when we run sentry on-premise on docker? I thought minor fixes like these are achieved by default from Dockerfile as they pull source from master in the image. But I still don’t see this in the image building.

**Comment by mattrobenolt** [comment]
No, you'll have to wait for the next release which is probably still a bit away.

**Comment by mattrobenolt** [comment]
In theory, if you're running already the sentry 10 branch of onpremise and bleeding edge stuff there, I'm not even sure if it's fully working yet, but if you happen to be running that branch, you could build master image here, and run that and it'd be fine. But I'm not fully sure the state of all that right now.

**Comment by potter7050** [comment]
Hello, @mattrobenolt . I wonder if this PR has also been applied to Sentry on-premise 9.1.2.

**Comment by mattrobenolt** [comment]
It doesn’t appear that way.

**Comment by potter7050** [comment]
Thank you for your answer. Do you know when it will be applied to Sentry on-premise? Does this apply to Sentry v10?

**Comment by mattrobenolt** [comment]
Yeah, it’ll be in 10 for sure. It’s also in any of the 10 betas now if you wanna try that out.

**Pull request merged**
