### PR TITLE
chore: Remove idx and babel-plugin-idx

### PR DESCRIPTION
**Pull request by lynnagara**

### CODE REVIEW

**Review by billyvg — COMMENTED** [review]
I would vote to leave this as is until optional chaining proposal moves into stage3 (maybe 4).

One small benefit is that the babel plugin transpiles it down to avoid the function call (real world performance will be negligible in our codebase)

Your call @MaxBittker 

(also getsentry might be using this?)

**Comment by lynnagara** [comment]
It's not exported to getsentry, but getsentry does use this package as well. Where possible I would like to avoid simply adding external libraries (in this case 2 extra dependencies) unless we are getting real value out of them.

**Comment by MaxBittker** [comment]
in general, i'd rather have a library dependency than a compilation-time operation
(much less risk of awful hard to debug weirdness)

(This has burned me in the past with the lodash babel plugin 😬)

Because the performance isn't important here, I'm in favor of pulling this out... and I think we'd all prefer to replace it with the tc39 version, which is making progress, but slowly.

I think the lodash api is kinda nice here in the meantime.

The main risk is if this breaks some edge case and we don't notice. Because idx is used in only* 15 places across 7 files, I'm happy to help manually verify the behavior and i'm sure any follow ups won't be too painful to fix. 

*(can I still say only for 15?) 

I don't think this is a huge win or anything but I appreciate it and I'm +1 on it.

**Comment by markstory** [comment]
Is this something we're still interested in pursuing or can it be closed because it can no longer be merged?

**Comment by lynnagara** [comment]
I'm still in favour of this, but we don't have any agreement on it

**Comment by billyvg** [comment]
I think if we agree that we'd prefer to use the TC39 optional chaining syntax, then we should just wait to switch to that. Otherwise we're introducing changes that have marginal benefits, that will eventually be changed again. I think having some stability here would be better.

**Pull request closed without merging**
