### PR TITLE
refs: Upgrade python-u2flib-server to >= 5.0.0 < 6.0.0 (SEN-209)

### PR DESCRIPTION
**Pull request by wedamija**
This updates us to the latest `python-u2flib-server`. This introduces a new response format that the
js u2f library doesn't know how to parse, so I've massaged the data so that it can still support
the responses. I'm not sure why it doesn't understand the new response format, it might be that the native support in chrome just supports the FIDO 1.0 format. Either way, the data returned from the backend should support either.

Testing notes:
u2f device registered in Chrome 4.0.0, logged in successfully in Chrome 4.0.0, 5.0.0
u2f device registered in Chrome 5.0.0, logged in successfully in Chrome 4.0.0, 5.0.0.

### CODE REVIEW

**Review by markstory — COMMENTED** [review]
Looks ok to me, but I'm not very well versed in this part of the application. Cc @mitsuhiko @maheskett

**Comment by mitsuhiko** [comment]
Would it not make sense to upgrade the client library first and then to update the server?

**Comment by billyvg** [comment]
Our JS lib is at the latest version: https://github.com/grantila/u2f-api https://github.com/getsentry/sentry/blob/master/package.json#L90

**Comment by wedamija** [comment]
Yeah, I can't find a js client library that is newer than this. Not sure whether the current one even supports FIDO 1.1, I'll investigate more in a little while.

**Comment by wedamija** [comment]
After some investigation it looks like the js library uses Chrome's built in FIDO functionality, so hopefully this upgrade will actualy resolve the issues we're seeing. I'm not sure why it uses the FIDO 1.0 format, but we're returning both so we should work either way.

**Comment by wedamija** [comment]
@mitsuhiko Any objections to merging this?

**Comment by mitsuhiko** [comment]
No objections.

**Review by markstory — APPROVED** [review]

**Review by billyvg — APPROVED** [review]

**Pull request merged**
