### PR TITLE
ref(integrations): Move methods to Managers

### PR DESCRIPTION
**Pull request by mgaeta**
Refactor model methods for `GroupLink` and `ExternalIssue` and put them in Manager classes.

### CODE REVIEW

**Review by markstory — APPROVED** [review]
Migration seems good as it is only state changes.

**Review by wedamija — COMMENTED** [review]
This looks good to me, although we'll need to regenerate the migration to fix the conflicts

**Comment by wedamija** [comment]
> I think this is blocked by `check migration / check migration`. Do you know how to satisfy it?

It's because the state in the migration doesn't match the state on the models - probably caused by adding `db_constraint=False` to the models but not the migration.

**Comment by mgaeta** [comment]
@wedamija It worked!

**Pull request merged**
