### PR TITLE
fix: errors being sent in as dict

### PR DESCRIPTION
**Pull request by alex-hofsteede**
Plus a regression test

fixes: SENTRY-5A1

### CODE REVIEW

**Review by mattrobenolt — COMMENTED** [review]
In what case does this happen? What’s an example of the data that’s not a list, because we’re changing the behavior to clobbering it. This seems like a value we shouldn’t allow the SDK to send, so in theory, this is only being mutated ourselves internally.

**Comment by alex-hofsteede** [comment]
Not 100% sure. but looks like raven-node, and only on 2 distinct projects and appears to be an empty dict in those cases. The value would get clobbered by the schema validation anyway, so there's no world in which it survives and is useful later on.

**Comment by alex-hofsteede** [comment]
@mattrobenolt and we have been clobbering user-supplied errors since https://github.com/getsentry/sentry/commit/c892b6fb

**Comment by mattrobenolt** [comment]
Yeah, so given that, why don't we continue that behavior? It seems that we've regressed in some way that is allowing what the SDK to set pass through. So I'd argue that this fix is not really the right approach. I'd rather we just explicitly set it to `[]` and not even attempt to accept any passed in data.

**Comment by alex-hofsteede** [comment]
Yep, good point, I think I had thought that we might end up going through multiple runs of validation and accumulating errors in that list. The post-save behavior of events is still a little bit of a mystery to me, but as long as they don't go through the load/normalize/save cycle again (and we want to keep the original errors) then we can just reset them to `[]`

Have changed the commit.

**Comment by alex-hofsteede** [comment]
@mattrobenolt lmk if you are cool with this now

**Review by mattrobenolt — APPROVED** [review]
Yup, this is better. Thanks. :)

**Pull request merged**
