### PR TITLE
perf: move sentry/shared_integrations to orjson

### PR DESCRIPTION
**Pull request by anonrig**
Splitting the changes from https://github.com/getsentry/sentry/pull/71185 into multiple pull-requests as a recommendation from @fpacifici (ref: https://github.com/getsentry/sentry/pull/71185#issuecomment-2125854962).

This pull-request only changes `json` usages in `src/sentry/shared_integrations` folder.

### CODE REVIEW

**Comment by sentaur-athena** [comment]
Can you please add tests for the changes? Or point me to them if they're in another PR?

**Comment by anonrig** [comment]
> Can you please add tests for the changes? Or point me to them if they're in another PR? Want to make sure they have data so we're not testing empty like the other webhook test 🤦‍♀️

There is no risk in introducing `orjson.loads`. The only place that would need test is probably https://github.com/getsentry/sentry/pull/71648/files#diff-3da5973d25f3e7bc8377be87584b8d897c360ef30c5b6d03cce72c72236f1e04R336. Any suggestions on an example test?

**Comment by sentaur-athena** [comment]
I would assume tests for `shared_integrations/client/base` live somewhere in  `tests/sentry/shared_integrations/client/test_base.py`. They are very simple tests and don't include the special edge cases we have with json.dumps like timestamp, UUID etc. You can add your tests there.

**Comment by anonrig** [comment]
cc @sentaur-athena @getsentry/ecosystem appreciate it if you could review.

**Pull request closed without merging**
