### PR TITLE
feat(discover): Add empty state to result table when no results

### PR DESCRIPTION
**Pull request by lynnagara**
screen shot 2018-11-28 at 3 05 22 pm

### CODE REVIEW

**Review by billyvg — COMMENTED** [review]
Can we use `EmptyStateWarning` since that's what a lot of current views use?

**Comment by lynnagara** [comment]
I'd rather stick to this design

**Comment by billyvg** [comment]
It's fine if you want to stick with design, but can you move it into the `EmptyStateWarning` and throw it behind a prop. That way we have a consistent component that handles the "you have no data" message. It'll also make it easier in the future to switch to the discover design (or a completely new design) for all components.

**Comment by Chrissy** [comment]
I've always thought our standard `emptyStateWarning` looked a bit _horsey_ as they say, so I like the idea of trying out an alternate size like this.

Because this is very similar to `emptyStateWarning`, it might be worth folding this into that component via  a `small` modifier, but we could also just add an `inline` prop to `EmptyMessage` too. I'm fine with whatever is simpler, but I do think it would be nice to make this a bit more reusable.

**Review by billyvg — APPROVED** [review]
Would be great in the future to investigate making the "small" version the default (thoughts @Chrissy?)

**Comment by Chrissy** [comment]
yes! as long as it doesn't make a bunch of stuff look weird.

**Pull request merged**
