### PR TITLE
fix: Fix attribute error when deleting emails

### PR DESCRIPTION
**Pull request by wedamija**
We just missed a guard here

Fixes SENTRY-NBA

### CODE REVIEW

**Review by mattrobenolt — APPROVED** [review]

**Comment by mattrobenolt** [comment]
`.first()` strikes again.

**Review by iProgramStuff — APPROVED** [review]

**Comment by iProgramStuff** [comment]
> `.first()` strikes again.

Hehe.

Maybe we could also remove the `.first()` if you're feeling ambitious?

**Comment by wedamija** [comment]
I don't really think the first is a problem here

**Comment by mattrobenolt** [comment]
I've highly considered making it raise an exception in dev/tests, and work in production so we could emphasize not using it. It's really a misunderstood thing and the cause of lots of bugs and unintended behaviors.

**Comment by mattrobenolt** [comment]
> I don't really think the first is a problem here

It's part of it. On top of it generating a worse query which I'm sure is unintended, it also isn't clearly obvious that it could be None. Unlike an exception you need to handle.

**Pull request merged**
