### PR TITLE
chore(ui): Remove searchbar flag for alerts team

### PR DESCRIPTION
**Pull request by schew2381**
Removing the `search-query-builder-alerts` flag from FE

### CODE REVIEW

**Comment by malwilley** [comment]
Thanks for doing this! Looks like there is a failing test though which will need to be updated.

The act warning can be fixed by adding async expressions like `await screen.findBy*(...)` instead of doing just `screen.getBy*()`.

**Comment by schew2381** [comment]
> Thanks for doing this! Looks like there is a failing test though which will need to be updated.
> 
> The act warning can be fixed by adding async expressions like `await screen.findBy*(...)` instead of doing just `screen.getBy*()`.

@malwilley I've switched to `await screen.findBy*(...)` but it still seems to be having that act failure. Would you have any ideas? 🤔

**Comment by malwilley** [comment]
@schew2381 pushed up a commit - the fake timers were the issue here and didn't seem to be necessary so I just went ahead and removed them. Not quite sure why it wasn't working together, but don't think it's worth digging into much more 🤷

**Comment by schew2381** [comment]
> @schew2381 pushed up a commit - the fake timers were the issue here and didn't seem to be necessary so I just went ahead and removed them. Not quite sure why it wasn't working together, but don't think it's worth digging into much more 🤷

ok sick thanks

**Review by mifu67 — APPROVED** [review]

**Pull request merged**
