### PR TITLE
feat(sidebar): Reorder sidebar items (APP-999)

### PR DESCRIPTION
**Pull request by lynnagara**
Order events directly below issues. Hide Projects when sentry10 is
active.

### CODE REVIEW

**Review by billyvg — APPROVED** [review]
Are we intending to replace `Projects` with `Dashboard`? If we, should we update the dashboard icon to use the same projects icon?

**Comment by lynnagara** [comment]
I'm not aware of icons changing again,  we're just hiding "Projects" for sentry10 users here

**Comment by billyvg** [comment]
I just took a random icon (health) for Dashboards, I think it'd make more sense to use the Projects icon if we're gonna hide it for the sentry 10 flag

**Comment by lynnagara** [comment]
Oh i see, i thought it was specced out in the design. I think it's fitting so will leave it for now (the projects one implies a list which doesn't seem that correct). The design team can tackle this later if they want.

**Pull request merged**
