### PR TITLE
feat(ci/codecov): Upload coverage data even if some tests fail

### PR DESCRIPTION
**Pull request by armenzg**
When a test fails, we do not upload any coverage data for that job since the step would be skipped. This would cause commits on `master` to loose substantial coverage score since a large portion of all tests would not submit coverage data. This would cause PRs based on such commits to have a large increases in coverage, thus, making coverage results show a very large number of impacted files.

This would also affects PRs regardless of what happens on `master` since few tests failing on the PR would also show a very larger number of impacted files, thus, making navigating the codecov results harder.

Uploading coverage data even if some tests fail will reduce the number of impacted files to mostly the tests that actually failed.

It may also help with the `frontend` diff target check not to be triggered for backend PRs (most of them have this check fail):
image

### CODE REVIEW

**Comment by armenzg** [comment]
I have #43445 in order to test out if it would work.

For instance, this [job failed](https://github.com/getsentry/sentry/actions/runs/3961274704/jobs/6786506871) some tests but it managed to upload the artifacts.
image

**Comment by armenzg** [comment]
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsif

**Review by ghost — APPROVED** [review]
Concept is sound. I'm not sure about the implementation.

**Comment by armenzg** [comment]
We're going to try #43600 as the fix.

**Pull request merged**
