### PR TITLE
ref(select-control): Add noMenu prop + minor focus cleanup

### PR DESCRIPTION
**Pull request by evanpurkhiser**

### CODE REVIEW

**Review by billyvg — COMMENTED** [review]
The multiline/multi select diffs are off :(

**Comment by EvanPurkhiser** [comment]
> The multiline/multi select diffs are off :(

I'm confused, what's the issue?

**Comment by billyvg** [comment]
look at the percy diffs, the down arrow is not vertically aligned with the clear button

**Comment by EvanPurkhiser** [comment]
So it actually doesn't look like that in chrome it seems: 
image

**Comment by billyvg** [comment]
Firefox though: image
 vs 
image

**Comment by EvanPurkhiser** [comment]
image

I can't seem to recreate this in Firefox. This select will go away soon enough, I have a nearly working react-select-v2 version of our control, which will require a bit more work to get all of them converted. But it doesn't use table alignment properties.

**Review by billyvg — APPROVED** [review]

**Pull request merged**
