### PR TITLE
build: Allow people to use volta instead of notion

### PR DESCRIPTION
**Pull request by untitaker**
Just duplicate this for now, and remove `toolchain` later

### CODE REVIEW

**Comment by untitaker** [comment]
@mitsuhiko https://github.com/volta-cli/volta/issues/432 will take a while, meanwhile I don't see the big deal in duplicating this.

**Comment by mitsuhiko** [comment]
We also need to add volta instead of notion to the makefile

**Comment by untitaker** [comment]
@mitsuhiko can you re-review?

**Review by mitsuhiko — APPROVED** [review]
lgtm, we need the same in getsentry though.

**Pull request merged**
