### PR TITLE
ref(devserver): Overhaul interplay between kafka consumers and --workers

### PR DESCRIPTION
**Pull request by untitaker**
Some of our kafka consumers implicitly started when --workers was not
provided, and some of them started even though kafka itself was disabled
in sentry.conf.py. This causes great confusion because in the case of
getsentry outcomes consumer, we started a consumer without ensuring kafka
was running.

This new setup removes a ton of duplicated sanity-checks around kafka,
and replaces it with one flow:

* --workers is required to start ANY Kafka consumer (breaking change)
* --ingest requires --workers, because without --workers there's no
  ingest consumer (breaking change)
* Relay is not started without --workers (plain devserver literally only
  starts webpack and uwsgi no matter what) (also breaking change)
* Random product feature flags append to kafka_consumers list
* If that list ends up being non-empty but we find no kafka/zookeeper
  containers, we tell the user to fix it (use kafka eventstream or
  SENTRY_USE_RELAY)

### CODE REVIEW

**Comment by untitaker** [comment]
tagging some random teams that I think deal most with kafka consumers in sentry

**Comment by markstory** [comment]
> --ingest requires --workers, because without --workers there's no
ingest consumer (breaking change)

Should this be implicit? Having just `--ingest` isn't that useful as you'll be able to accept events but not have them show up anywhere. We could have 

* `--ingest` enables celery workers, kafka consumer + relay. Gives you a functioning ingestion pipeline locally.
* `--workers` runs celery workers and kafka consumers. Not all of the consumers will be doing work but that's ok.

**Comment by untitaker** [comment]
> Should this be implicit? Having just --ingest isn't that useful as you'll be able to accept events but not have them show up anywhere. We could have

this PR makes devserver explicitly reject --ingest without --workers. would you prefer it to implicitly enable --workers?

**Comment by markstory** [comment]
> would you prefer it to implicitly enable --workers?

Yeah, Instead of having to write out both options, `--ingest` starts the processes that `--workers` would as well as the rest of the ingestion pipeline.

**Comment by untitaker** [comment]
Done!

**Review by markstory — APPROVED** [review]
Looks good to me.

**Pull request merged**
