### PR TITLE
feat(icons): Introduce Sentry Pride icon  🌈

### PR DESCRIPTION
**Pull request by priscilawebdev**
**Preview:**

image

image

### CODE REVIEW

**Review by matejminar — APPROVED** [review]

**Review by cleptric — CHANGES_REQUESTED** [review]
This has to go into getsentry instead.

**Comment by priscilawebdev** [comment]
no no @cleptric ... we put it here and the logic to display will be in getsentry 😉

**Comment by priscilawebdev** [comment]
my auto merge ...merged the other PR here without approvals :( but I think its fine to merge all these changes together

**Comment by cleptric** [comment]
Your other PR has this branch as its target, so we're good.

**Comment by priscilawebdev** [comment]
since we want to the logo to be in getsentry, I am closing this PR

**Pull request closed without merging**
