### PR TITLE
feat(jest): enable profiling tests

### PR DESCRIPTION
**Pull request by JonasBa**
Enable profiling in jest

### CODE REVIEW

**Comment by JonasBa** [comment]
This seems much better now with eager logging and most test runs seem to have almost no overhead. That said, in some cases like https://github.com/getsentry/sentry/actions/runs/3285415456/jobs/5428080614, a run takes a few minutes longer to complete and times out.. Our test balancer seems to always have one test run that takes a lot longer than the rest (~15min compared to 10-12 on the other 3)

**Comment by JonasBa** [comment]
@AbhiPrasad this still occasionally runs very slowly and sometimes times out. I am not entirely sure why some tests sometimes just run very slowly, but I suspect this could be related to actions runners or infra. In any case, one thing I would like to do is try and optimize some http params like enabling [keepalive](https://github.com/getsentry/sentry-javascript/issues/2555) for node transport and possibly disabling gzip to save CPU resources. 

One though I had was to maybe also create a separate worker where we can dispatch envelopes and send them as fire/forget. Since this is in CI env, it would not be terrible if we sometimes dropped some profiles (small risk as the worker would get terminated as the entire suite finishes so anything in flight would be at risk). 

I opened a quick draft PR for the worker idea [here](https://github.com/getsentry/jest-sentry-environment/pull/16), lmk what you think.

**Comment by JonasBa** [comment]
This has now been running pretty consistently in the 10-15min range (as all of our current test runs). I have been manually re-running it and it has never timed out in the last 10 runs.

**Review by Zylphrex — APPROVED** [review]
:shipit:

**Comment by JonasBa** [comment]
image

**Pull request merged**
