### PR TITLE
fix: remove last references to AUTOCOMMIT

### PR DESCRIPTION
**Pull request by wilmardo**
Followup of #16816

Removes last references to autocommit :)

### CODE REVIEW

**Comment by mattrobenolt** [comment]
Why though? This is still a valid option. 

https://docs.djangoproject.com/en/1.11/ref/settings/#std:setting-DATABASE-AUTOCOMMIT

**Comment by wilmardo** [comment]
> Django 1.6 already defaults to True for this and in Django 1.8, which
is what the latest Sentry uses, the option is removed and causes a DB
connection error so dropping it to fix git builds.
See https://stackoverflow.com/a/29444039/90297.

Quote from https://github.com/getsentry/onpremise/pull/195

**Comment by mattrobenolt** [comment]
That’s referring to it being nested inside of `OPTIONS`. It does default to True, but for important things, we like to be explicit in case this default decided to change. But this hasn’t been removed at all.

**Comment by wilmardo** [comment]
Ah got it, thanks for the explanation! 

Sorry for the noise :)

**Pull request closed without merging**
