### PR TITLE
fix(msteams): Update identity database to allow for longer MS Teams user IDs

### PR DESCRIPTION
**Pull request by KKaempen**
This is necessary to make identity linking for Teams work.

### CODE REVIEW

**Review by wedamija — COMMENTED** [review]
Since the sql generation task is broken:
```
ALTER TABLE "sentry_identity" ALTER COLUMN "external_id" TYPE varchar(256) USING "external_id"::varchar(256);
```

I think this is actually dangerous. From what I understand, when postgres alters a column's max length it will have to rewrite the entire table.

@mattrobenolt This table is 200k rows. We should probably run this offline, correct?

It might also make sense to just switch to `TextField` since we're rewriting the table anyway. Then we don't need to worry about this again in the future.

**Comment by mattrobenolt** [comment]
> It might also make sense to just switch to TextField since we're rewriting the table anyway. Then we don't need to worry about this again in the future.

This. The migration to TextField actually doesn't require a rewrite since it's loosening the constraint and removing it.

I added fields explicitly for doing this though:

```python
from sentry.db.models.fields import CharField
```

This would get you a CharField that has a constraint validated in Python, but is backed by a `text` column in the database rather than `varchar(n)`.

I'd still say we should run offline to make sure since these operations happen rarely and always scare me.

**Comment by scefali** [comment]
@wedamija Kieran updated the model/migration with the text column like you suggested with `is_dangerous=True`

**Review by wedamija — APPROVED** [review]
LGTM

Remember that if you want to enforce a length in Python then you can use the field matt suggested: `from sentry.db.models.fields import CharField`.

**Comment by scefali** [comment]
This is the SQL I see now:
```
ALTER TABLE "sentry_identity" ALTER COLUMN "external_id" TYPE text USING "external_id"::text;
```

**Pull request merged**
