### PR TITLE
ref(plugins): move new_sentry_plugins into sentry_plugins

### PR DESCRIPTION
**Pull request by scefali**
Also change "sentry.new_apps" to "sentry_apps".

### CODE REVIEW

**Review by joshuarli — APPROVED** [review]
lgtm!

**Review by wedamija — APPROVED** [review]

**Comment by EvanPurkhiser** [comment]
Have we been able to remove the webpack dependency?

**Comment by joelr** [comment]
Any reason why we can't see PagerDuty under the list of integrations available?

**Comment by scefali** [comment]
@joelr Where are you looking? If you go to the legacy plugin page, it should show up:
Screen Shot 2019-11-27 at 9 39 57 AM

**Comment by joelr** [comment]
Ah got it thanks, I was looking under org settings/integrations rather the projects, thanks again!

**Comment by scefali** [comment]
@joelr No worries. Just so you know, we have PagerDuty integration coming out soon on the integrations page! Keep your eyes open for that in the next few months. It will be much better than the current PagerDuty plugin that we currently have.

**Comment by joelr** [comment]
great, thanks for the info

**Comment by Nuru** [comment]
@scefali Did the new PagerDuty integration come out? How do I install it in the open source/on premises 9.1.2 version of Sentry? I don't see it under Organization Settings > Integrations or in the release notes.

**Comment by scefali** [comment]
@Nuru We added it towards the end of 2019 so it probably only appears in Sentry 10.0+. Also, you'd need to set up your own PagerDuty app in PD. I don't know if we have any docs on this for on-prem folks. Honestly, it's probably easier to use the old PD plugin if you're on-prem.

**Comment by Nuru** [comment]
@scefali Unfortunately, the old version of the PagerDuty plug-in no longer works. https://github.com/getsentry/sentry-plugins/issues/356 

So at this point I am unable to create an effective integration between Sentry 9.1.2 and PagerDuty in any way.

**Comment by scefali** [comment]
@Nuru I see. I think you just need to upgrade to Sentry 10 if you want PagerDuty to work.

**Pull request merged**
