### PR TITLE
Js translations

### PR DESCRIPTION
**Pull request by mitsuhiko**
Work in progress translations.  All of views is missing so far.

### CODE REVIEW

**Comment by mitsuhiko** [comment]
Do not merge. I made this for travis :)

**Comment by mitsuhiko** [comment]
I think I have most of the views translated.  There is one area I left out: `stream/actions.jsx` and `stream/actionLink.jsx` primarily because the way `ActionLink` works makes translations really hard.

@dcramer are you fine changing up the UI messages slightly to aid translations?  Primarily we are currently constructing sentences out of little bits and pieces which does not work in all languages the same.

**Comment by mitsuhiko** [comment]
I think that should be all now.

**Comment by dcramer** [comment]
We should audit the rest of action link as merge is now broken like resolve used to be:

https://www.dropbox.com/s/vofsqnubyhxr4fw/Screenshot%202015-11-26%2020.43.44.png?dl=0

**Comment by mitsuhiko** [comment]
I think I caught all now. But I will do another check. I think it was only the confirmation dialogs that behaved like this.

**Pull request merged**
