### PR TITLE
Add stats for blacklisted events

### PR DESCRIPTION
**Pull request by mattrobenolt**
Last part for GH-2023

image

/cc @dcramer @benvinegar

### CODE REVIEW

**Comment by dcramer** [comment]
With the legend can we change it to:

- Accepted
- Dropped (Rate Limit)
- Dropped (Blacklist)

**Comment by mattrobenolt** [comment]
The legend on the graph? Or the legend on the table below?

**Comment by mattrobenolt** [comment]
To clarify, we'd be taking up too much horizontal space in the `<table>`. :/

**Comment by dcramer** [comment]
Maybe all legends, but the table below ideally we could have like

```
  Dropped           Dropped
(Rate Limit)       (Blacklist)
```

**Comment by mattrobenolt** [comment]
Ah, ok, lemme try and make that work.

**Comment by mattrobenolt** [comment]
@dcramer 
image

?

**Comment by dcramer** [comment]
lgtm

**Pull request merged**
