### PR TITLE
Migrations Considered Harmful: Week 4

### PR DESCRIPTION
**Pull request by wedamija**
Note: This migration won't be merged. Please don't review or comment on this if you're not participating
in MCH.

Welcome to Week 4 of Migrations Considered Harmful. The goal of MCH is to have a member on each
team who can confidently review migrations, and hopefully have fewer outages related to them.

Each week I'll put up a pr with a migration, you look at it and prepare (but don't submit) your
review. Then at the same time each week everyone can submit their reviews, and we can discuss in
our weekly meeting.

Our fourth migration is adding a new category column to the `Group` table.
Is there anything wrong with this migration? If so:

What problems will it cause?
Why does this migration cause problems?
How should we fix it?
Feel free to link to docs if there are things that already explain how to improve the migration.

Ignore any conflicts on migrations_lockfile.txt.

### CODE REVIEW

**Review by RyanSkonnord — COMMENTED** [review]
Needs `is_dangerous = True` because `Group` is a highly active table (and, as the comment says, initializing to null does not help).

The implied meaning of a `category` field suggests that we want the model attribute to be an `IntEnum` rather than a `PositiveSmallIntegerField`, so that the meaning of each number is self-documenting. In that case, it would likely be better to have a default value than a nullable category -- meaning we'd want to backfill the new default value in a two-step migration.

**Review by JoshFerge — COMMENTED** [review]
- let's mark `is_dangerous=True`. this is a v. large table (my count(*) on redash timed out so i don't know exactly how big)
- from the postgres docs, "Adding a CHECK or NOT NULL constraint requires scanning the table to verify that existing rows meet the constraint, but does not require a table rewrite."
    - i'm not sure if this would happen with a newly created column, but it could make this migration very long running if so.
- i think we'd want this to run in a transaction and set `atomic=True`, but confidence level medium on that

**Comment by alxu-sentry** [comment]
> * let's mark `is_dangerous=True`. this is a v. large table (my count(*) on redash timed out so i don't know exactly how big)

on postgres, `select count(*) from table` requires reading the entire table so will take a long time. you can get an estimate of the table size by running `explain select * from table;`.

regarding the migration itself, aside from whether this should be an enum, i ran this benchmark using postgres 9.6 in docker on my mac:

```
test_db=# SELECT generate_series(1,100000000) AS id INTO test_table;
SELECT 100000000
Time: 26597.531 ms
test_db=# alter table test_table ADD COLUMN "category" smallint NULL;
ALTER TABLE
Time: 1.121 ms
test_db=# drop table test_table;
DROP TABLE
Time: 641.696 ms
test_db=# SELECT generate_series(1,100000000) AS id INTO test_table;
SELECT 100000000
Time: 27898.123 ms
test_db=# alter table test_table ADD COLUMN "category" smallint NULL default 5;
ALTER TABLE
Time: 43893.414 ms
test_db=# drop table test_table;
DROP TABLE
Time: 1382.146 ms
test_db=# SELECT generate_series(1,100000000) AS id INTO test_table;
SELECT 100000000
Time: 27568.851 ms
test_db=# alter table test_table ADD COLUMN "category" smallint NULL CHECK ("category" >= 0);
ALTER TABLE
Time: 9587.715 ms
```

based on this benchmark, i concluded that while the ddl in this migration doesn't rewrite the whole table, it does scan the whole table. i also checked `select * from pg_locks` while running the third column add and it seemed to be taking several ExclusiveLocks and a AccessExclusiveLock. for a smaller table, i think it might be ok to mark the migration `is_dangerous` and run it at a later time, but i don't think we can r/w block this table for what could be many minutes.

could we instead add the column, then add a `NOT VALID` constraint? it seems based on https://code.djangoproject.com/ticket/31653 that this is not currently supported, but we could use raw sql instead. since we control all writers to this table, we can simply enforce ourselves that we don't write to this new column before adding the constraint.

**Comment by iProgramStuff** [comment]
Just going to throw out the suggestion that we look towards adding a second model, GroupCategory to track this relationship because our Group table is really hot

**Pull request closed without merging**
