### PR TITLE
feat(mobile): frame metrics react native

### PR DESCRIPTION
**Pull request by bruno-garcia**
RN has been sending slow and frozen frames with accurate data

### CODE REVIEW

**Comment by bruno-garcia** [comment]
Oh I missed some stuff, wait up

**Comment by bruno-garcia** [comment]
pretty much ended up as a revert from: https://github.com/getsentry/sentry/commit/7b69a0a09644137c4b2523b5e2a2abe4876c5b5a

**Comment by dashed** [comment]
@bruno-garcia 👀  https://github.com/getsentry/sentry/pull/32815

**Comment by bruno-garcia** [comment]
oof, anyway VS Code can't stop itself but to reformat the whole file. I'll get back to powerpoint

**Pull request closed without merging**
