### PR TITLE
chore: Remove unused SSO components

### PR DESCRIPTION
**Pull request by markstory**
Remove the OrganizationAuthProvider component and related tests. This component has been commented out since March 2018. Removing this code will help reduce bundle sizes and test duration.

### CODE REVIEW

**Comment by EvanPurkhiser** [comment]
Shouldn’t dead code elimination stop this from being included in the bundle?

I’m good with removing this, I just don’t want to forget that it’s here, since this really does need to be migrated from Django.

**Comment by markstory** [comment]
> I’m good with removing this, I just don’t want to forget that it’s here, since this really does need to be migrated from Django.

Is the existing code 'done'? I agree it should get moved over to react but if the current code isn't finished or working keeping it around doesn't have much value.

**Comment by EvanPurkhiser** [comment]
It's not done, but it might server as a decent reference for when we do finish it up.

How about a TODO comment with reference to the commit this is removed in?

**Comment by billyvg** [comment]
I would say that a code comment is not the proper place for a larger task like this. We should open a ticket in JIRA and link to this PR imo.

**Comment by markstory** [comment]
@billyvg I created https://getsentry.atlassian.net/browse/APP-958 with a reference to this pull request so that future us has some reference.

**Review by billyvg — APPROVED** [review]

**Pull request merged**
