### PR TITLE
bug(replays): Guard against hydrating invalid attachments

### PR DESCRIPTION
**Pull request by ryan953**
Fixes https://github.com/getsentry/team-replay/issues/93

### CODE REVIEW

**Review by billyvg — APPROVED** [review]
Wonder if we should be more explicit in checking the data contents rather than relying on an exception being thrown due to invalid data.

**Comment by ryan953** [comment]
> Wonder if we should be more explicit in checking the data contents rather than relying on an exception being thrown due to invalid data.

@billyvg it's a speed tradeoff. @mydea was saying in chat that we might not need to check each item. maybe the middle ground is ErrorBoundary around each item when we render the lists in the details page? (breadcrumb list, console list, etc etc)

**Comment by billyvg** [comment]
I'm good with this solution fwiw

**Comment by ryan953** [comment]
@billyvg tests were showing that i didn't even throw on the 'invalid date' case, which was the goal.

I've added `invariant` to throw, and `isValidDate` to make the assertion.

**Review by billyvg — APPROVED** [review]

**Pull request merged**
