### PR TITLE
feat(auth): Support migration of auth identity id value

### PR DESCRIPTION
**Pull request by evanpurkhiser**
Supports fixing our choice of identifier for google auth.

### CODE REVIEW

**Comment by dcramer** [comment]
For context, this will let us migrate to Google's internal IDs, which we mistakenly didn't use when building SSO.

**Comment by getsentry-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Changes require @getsentry/security sign-off</td>
    </tr>
  </tbody>
</table>

### Security concerns found

- src/sentry/auth/helper.py
- src/sentry/auth/provider.py


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by EvanPurkhiser** [comment]
And here's the associated Google Auth change: https://github.com/getsentry/sentry-auth-google/pull/20

**Review by dcramer — APPROVED** [review]
would we be able to add a test for this behavior?

**Comment by EvanPurkhiser** [comment]
@dcramer yes added tests.

**Comment by EvanPurkhiser** [comment]
@dcramer wanted to get your eyes on the tests real quick for a re-approve before merging.

**Review by dcramer — APPROVED** [review]

**Pull request merged**
