### PR TITLE
fix(integrations): Fix migration file

### PR DESCRIPTION
**Pull request by mgaeta**
Copy enum definitions from the models directory and into the migrations that use them.

It's better to have copies of enums inside the migration. This allows us to change or remove the enums without breaking past migrations.

### CODE REVIEW

**Comment by mgaeta** [comment]
@getsentry/owners-migrations Is this a valid way/reason to modify an older migration?

**Review by ceorourke — COMMENTED** [review]
looks good but I'll leave it to Dan / migration people to approve since I'm not sure this won't blow things up

**Review by markstory — APPROVED** [review]
Looks good to me. Migrations shouldn't be importing application objects that could change often. :+1:

**Comment by mgaeta** [comment]
@getsentry/github-admins Can you merge this for me?

**Comment by billyvg** [comment]
Should this be happening? https://github.com/getsentry/sentry/pull/24507/checks?check_run_id=2133396663#step:8:28

**Comment by scefali** [comment]
@mgaeta I'm curious how you tested this PR to verify there isn't a mistake with one of enums being copied. Did you reset your DB and run the migrations from scratch?

**Comment by wedamija** [comment]
> @getsentry/github-admins Can you merge this for me?

We don't want to force merge this. Next time someone generates a migration the extra junk would just be included in their migration

**Comment by BYK** [comment]
@scefali 
>@mgaeta I'm curious how you tested this PR to verify there isn't a mistake with one of enums being copied. Did you reset your DB and run the migrations from scratch?

This is being tested by the GCB check on each PR.

**Comment by mgaeta** [comment]
I think I got around the problem with imports. Everything seems fine as long as the enums are available at the scope imported by the migration. For example, I'm moving `NotificationSettingTypes` to `sentry/notifications/types.py` but still importing the enum in `sentry/models/notificationsetting.py`. When the migration does: 
```
import sentry.models.notificationsetting
```` 
`sentry.models.notificationsetting.NotificationScopeType` just works.

**Pull request closed without merging**
