### PR TITLE
feat(ui): Added issue stream link into project settings page

### PR DESCRIPTION
**Pull request by matejminar**
image

This PR adds an Issues Stream link of the given project into the project's general settings page.

This has been a major pain point for some of our staff - they lacked the ability to quickly jump to the respective issues stream from the project's settings page.

### CODE REVIEW

**Comment by matejminar** [comment]
Does it make sense to place it there? 

Do we need to do any changes to make it clear, that it is a link to the project's issues stream and not a button to settings of issues stream?

**Comment by billyvg** [comment]
I think our navigation (with regards to "selected" project) needs a look-over in general, but this feels a bit out of place to me. Why is it only displayed in the project settings? I would expect to just hit the sidebar to go back to the issues stream (I realize this is not how it works today). @doralchan any thoughts here?

**Comment by matejminar** [comment]
Does anyone have a better solution for navigating from the project's settings to issues stream? Maybe we can make the button less dominant, or place it somewhere where it is not that much in your face.

Or maybe just a simple change of wording would do, perhaps different icon:
Screenshot 2020-03-06 at 14 28 52
This is just an example, I know that this icon is mostly used for external links...

Or what if we **hide the button behind isSuperUser** or some other flag  - we don't pollute the UI for customers that won't use this for sure and we solve the problem for our staff that jumps between many projects a day.

**Comment by doralchan** [comment]
@matejminar This link doesn't quite make sense in Project Settings considering Issues is not the focus here. This may be more correlated with Issue Owners but I'd resist putting it in a general project setting. 

Note: I believe everyone will agree with me when I say this but Settings is garbage and needs an audit.

**Review by doralchan — CHANGES_REQUESTED** [review]
What was the original problem that made you want to add it in settings?

**Comment by matejminar** [comment]
@doralchan Some folks in Vienna office context switch between project's settings and project's issues stream many times a day (on multiple different orgs and projects).
For example when debugging something.

Currently, there is no easy way to jump from the project's settings to the issues stream of that project.
They need to click on Issues in a sidebar, then scroll through sometimes dozens of projects in global selection header to filter down the stream.
This is very painful if you do it many times a day.

That was the motivation.

I agree that the button is misplaced there - hence my first comment in this PR.

We can either do this:
> Or what if we hide the button behind isSuperUser or some other flag - we don't pollute the UI for customers that won't use this for sure and we solve the problem for our staff that jumps between many projects/orgs a day.

or do we have any additional ideas on how to help them without spending too much time?

**Comment by billyvg** [comment]
I think superuser only might be fine

**Comment by doralchan** [comment]
Screen Shot 2020-03-17 at 4 13 07 PM

Maybe one of things we can do is move the button to Issue Owners and rename that to Issue Settings to encompass more topics.

**Review by doralchan — APPROVED** [review]

**Comment by matejminar** [comment]
Final verdict after discussions: We are placing the button into Issue owners, without renaming. Thanks to everyone involved!

**Pull request merged**
