### PR TITLE
feat(accounts): add hook for custom delete account modal

### PR DESCRIPTION
**Pull request by scefali**
We want to let getsentry set a custom modal for closing an account

### CODE REVIEW

**Review by priscilawebdev — COMMENTED** [review]
the code looks good but it's not clear to me why we are doing this... it looks like we just moved the `close account` confirm modal code to a separate component

**Review by markstory — APPROVED** [review]

**Comment by scefali** [comment]
@priscilawebdev It's related to a promotion we want to run, want custom content in the modal to dissuade folks from shutting down their account.

**Comment by priscilawebdev** [comment]
I see..but the modal doesn't yet have custom content...will this be added in a follow-up?

**Comment by scefali** [comment]
@priscilawebdev well yes, that modal wouldn't exist in Sentry, that's why we are making a hook. Yes, it's going to be added as follow-up in getsentry. Not sure on the exact design yet, but no matter what we need this hook to show custom content.

**Pull request merged**
