### PR TITLE
Add password confirmation when enabling or disabling 2fa

### LINKED ISSUE #3919: MFA configuration should require password confirmation
If you manage to hijack a users session you can prevent the user from logging in by enabling MFA on their account. This means it'd be fairly complex for the user to reclaim the account, as it'd have to go through an administrator. Due to this, we should require password confirmation when enabling or disabling MFA.

### PR DESCRIPTION
**Pull request by kjlundsgaard**
Fixes #3919 
@getsentry/infrastructure 

image
image

---

This change is [Reviewable](https://reviewable.io/reviews/getsentry/sentry/4068)

### CODE REVIEW

**Comment by dcramer** [comment]
Do we currently not requiring 2fa to remove 2fa? I think password confirmation is good, but if you already have their password (in which you can brute force it via some of these pages), the standard is generally to require verification through a secondary mechanism in order to remove that mechanism.

That said, this is still a good addition either way especially on the side of adding a new authenticator.

I would suggest we also add rate limiting, and can probably re-use the auth.rate-limit settings for this and arguably anything that does password verification:

```
        limit = options.get('auth.user-rate-limit')
        if not limit:
            return False

        username = self.cleaned_data.get('username')
        if not username:
            return False

        return ratelimiter.is_limited(
            u'auth:username:{}'.format(username),
            limit,
        )
```

---

Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/4068#-:-KR09kzlNLlEtbMNmzcb:b-ebbwfm)*

**Comment by benvinegar** [comment]
Reviewed 1 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/4068)*

**Comment by dcramer** [comment]
Reviewed 1 of 4 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/4068)*

**Comment by benvinegar** [comment]
:shipit:

**Comment by benvinegar** [comment]
@dcramer – as a followup, GitHub lets you remove 2FA without verifying your second factor beforehand.

I think the thinking is – if you got access to the account, you had to use 2FA to begin with. Or you got access to the computer physically.

**Pull request merged**
