### PR TITLE
ci: Do not mark tests with backend label

### PR DESCRIPTION
**Pull request by mattgauntseo-sentry**
I don't think this will affect any workflows or behaviors but I could be missing some configuration.

[DEVINFRA-86]

[DEVINFRA-86]: https://getsentry.atlassian.net/browse/DEVINFRA-86?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by asottile-sentry** [comment]
I think the problem is more subtle than that -- because `backend` includes `**/*.py` anything in `tests/**/*.py` will also match and become `backend

what probably needs to happen is to have the file filters differentiate the deployable parts and the test-only parts and use that knowledge to apply the frontend/backend labels (since we still want backend tests to run if backend tests change, etc.)

**Review by evanpurkhiser — COMMENTED** [review]
Doesn’t this actually _add_ tests to the backend filter?

**Comment by evanpurkhiser** [comment]
Yeah this probably just needs to become fine grained for both running tests and for labeling

**Comment by mattgauntseo-sentry** [comment]
For some reason I read the filters as exclusions, sorry.

This is not going to be the quick fix I was hoping for

**Pull request closed without merging**
