### PR TITLE
fix(snuba): Control how results are nested.

### PR DESCRIPTION
**Pull request by alex-hofsteede**

### CODE REVIEW

**Comment by alex-hofsteede** [comment]
@bretthoerner is this something like what you would want for search stuff?

**Comment by bretthoerner** [comment]
Yeah, I'd use it if it bubbled up to Sentry utils.

**Review by bretthoerner — APPROVED** [review]
Forgot to approve.

**Comment by alex-hofsteede** [comment]
@bretthoerner  did you end up needing this at all? I kinda forgot about it

**Comment by bretthoerner** [comment]
Eh it's fine, I only unroll it one place so far so it may be more confusing to readers to have it? Up to you, really.

**Comment by alex-hofsteede** [comment]
Will just leave it out for now, can bring it back if needed.

**Pull request closed without merging**
