### PR TITLE
Add release metadata per issue

### PR DESCRIPTION
**Pull request by dcramer**
This adds the GroupRelease schema which keeps track of the given [release+environment] combinations available for the group, as well as some basic statistics regarding them.

@getsentry/infrastructure

---

This change is [Reviewable](https://reviewable.io/reviews/getsentry/sentry/3697)

### CODE REVIEW

**Comment by dcramer** [comment]
We'll follow up to utilize this data for the frequency chart so its entirely based on environment.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3697#-:-KMV6xC5CtVObK3gT3Ns:-1633227016)*

**Comment by mitsuhiko** [comment]
Do you want to merge this in the current form?

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3697#-:-KMa8VIjQKC4mZGMtwWO:1295782142)*

**Comment by dcramer** [comment]
@mitsuhiko do you think theres something missing? I'd like to get this in in current form unless there's a clear flaw, as it starts collecting the data.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3697#-:-KMa9nXOrL7nLeNPiHp2:-453331232)*

**Comment by dcramer** [comment]
Actually this needs added to the cleanup tasks first

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3697#-:-KMaBR4HU_D4npWmSbmn:-970763533)*

**Comment by dcramer** [comment]
Fixed

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3697#-:-KMaHmdSE_E47HfLfkhI:-497468049)*

**Comment by mitsuhiko** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3697)*

**Pull request merged**
