### PR TITLE
fix(accounts): Prevent Referer leak on password reset page

### LINKED ISSUE #11907: Prevent Referer leaking on password reset page
Right now when you get a password reset link, the page you end up on contains the reset token in the url.

Doing this causes a problem in which any page redirected to after this, and _especially_ any third party assets being loaded leak this reset token via the `Referer` header on the request.

While this isn't specifically a problem since the only things we embed are trusted vendors, in the case of SaaS, it's better to just avoid it.

My proposal is to keep the same url, but this endpoint does the following:

* Accepts the request, and puts the token either into the browser session or browser's cookie.
* Redirect away from this url, to a generic password reset form page.
* This new password reset form page then takes the values from your session or cookie.

Doing this mitigates any ability for leaking data through any Referer header in the future.

I am open to other proposals, but this is the best that comes to my mind.

### PR DESCRIPTION
**Pull request by bsr3000**
Add `Referrer-Policy` header with `strict-origin-when-cross-origin` value to responses on views with password reset hash.

Requests to third-party services on password reset page won't contain path with `hash` in referrer header

Fixes #11907

### CODE REVIEW

**Comment by mattrobenolt** [comment]
I still think I’d prefer to put the hash in a session instead of relying on modern browser behavior here personally. I haven’t looked into how widespread this support is. But I feel it’s better to avoid it if we can.

**Comment by dashed** [comment]
@bsr3000 sorry for taking a while to get back to you. Would you be able to rebase this pull-request against `master`?

**Comment by bsr3000** [comment]
@dashed Yes I can, but only tomorrow in the evening, if it can wait )

**Comment by dashed** [comment]
@bsr3000 thanks! 👍 

There's definitely no urgency on this PR. Take all the time you need.

**Comment by mattrobenolt** [comment]
From what I’m seeing this doesn’t work on IE or Safari on iOS. I personally access Sentry via Safari on iOS a nontrivial amount of times.

**Comment by bsr3000** [comment]
@mattrobenolt Support of this header looks good,  I don't think many users use Sentry on IE, here is the link to mdn docs https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy

**Comment by bsr3000** [comment]
@mattrobenolt yeah you are right about safari on ios,  didn't notice that

**Comment by mattrobenolt** [comment]
I literally have someone in my inbox complaining about this who uses IE and sent a video showing this behavior in IE. While I don’t fully agree on the severity, I just think I’d prefer to fix it in a better way by not even having the hash in the url. That solves a larger class of issues too that stem from this behavior.

**Comment by bsr3000** [comment]
@mattrobenolt found some info about IE and iOS Safari, maybe using user agent info we can switch value of this header: 
https://caniuse.com/#feat=referrer-policy

Looks like they work with an old spec of this header

**Review by BYK — APPROVED** [review]
The support for this header is much better now (97%) and I think this can be used in addition to what @mattrobenolt suggested.

Objections? /ping @dashed @markstory

**Pull request merged**
