### PR TITLE
fix(cdc): Create index concurrently in migration

### LINKED ISSUE #27125: Upgrade from 21.6.1 to 21.6.2 migration error, relation already exists
### Environment

self-hosted (`onpremise` deployment)

### Version

21.6.1 upgrade to 21.6.1

### Steps to Reproduce

1. git fetch tags/21.6.2
2. ./install.sh

### Expected Result

Migration to succeed.

### Actual Result

```
django.db.utils.ProgrammingError: ProgrammingError('relation "sentry_groupedmessage_project_id_id_515aaa7e_uniq" already exists\n',)
SQL: ALTER TABLE "sentry_groupedmessage" ADD CONSTRAINT "sentry_groupedmessage_project_id_id_515aaa7e_uniq" UNIQUE ("project_id", "id")
```

### PR DESCRIPTION
**Pull request by nikhars**
Change the migration so that the unique index on groupedmessage is
created concurrently.

This is a followup on this discussion https://github.com/getsentry/sentry/pull/27064#discussion_r663157625

Fixes #27125.

### CODE REVIEW

**Review by wedamija — APPROVED** [review]

**Comment by bobvandevijver** [comment]
Just to ask the question here: when upgrading to 21.6.2 (so with the current migration), I get the following error:

```
django.db.utils.ProgrammingError: ProgrammingError('relation "sentry_groupedmessage_project_id_id_515aaa7e_uniq" already exists\n',)
SQL: ALTER TABLE "sentry_groupedmessage" ADD CONSTRAINT "sentry_groupedmessage_project_id_id_515aaa7e_uniq" UNIQUE ("project_id", "id")
```

Would that be solved with this change?

**Comment by pataar** [comment]
> Just to ask the question here: when upgrading to 21.6.2 (so with the current migration), I get the following error:
> 
> ```
> django.db.utils.ProgrammingError: ProgrammingError('relation "sentry_groupedmessage_project_id_id_515aaa7e_uniq" already exists\n',)
> SQL: ALTER TABLE "sentry_groupedmessage" ADD CONSTRAINT "sentry_groupedmessage_project_id_id_515aaa7e_uniq" UNIQUE ("project_id", "id")
> ```
> 
> Would that be solved with this change?
> 
> Edit:
> After dropping the conflicting constraint, I get the following one, which was actually the first one that went wrong.
> 
> ```
> django.db.utils.ProgrammingError: ProgrammingError('index "sentry_groupasignee_project_id_group_id_fbf4364e_uniq" for table "sentry_groupasignee" does not exist\n',)
> SQL:
>             ALTER TABLE sentry_groupasignee REPLICA IDENTITY USING INDEX
>             sentry_groupasignee_project_id_group_id_fbf4364e_uniq
> ```

I have the same issue. I think this PR will fix it.

**Comment by nikhars** [comment]
> Just to ask the question here: when upgrading to 21.6.2 (so with the current migration), I get the following error:
> 
> ```
> django.db.utils.ProgrammingError: ProgrammingError('relation "sentry_groupedmessage_project_id_id_515aaa7e_uniq" already exists\n',)
> SQL: ALTER TABLE "sentry_groupedmessage" ADD CONSTRAINT "sentry_groupedmessage_project_id_id_515aaa7e_uniq" UNIQUE ("project_id", "id")
> ```
> 
> Would that be solved with this change?
> 
> Edit:
> After dropping the conflicting constraint, I get the following one, which was actually the first one that went wrong.
> 
> ```
> django.db.utils.ProgrammingError: ProgrammingError('index "sentry_groupasignee_project_id_group_id_fbf4364e_uniq" for table "sentry_groupasignee" does not exist\n',)
> SQL:
>             ALTER TABLE sentry_groupasignee REPLICA IDENTITY USING INDEX
>             sentry_groupasignee_project_id_group_id_fbf4364e_uniq
> ```

@bobvandevijver - You should have the index setup already from these lines https://github.com/getsentry/sentry/blob/master/src/sentry/migrations/0001_squashed_0200_release_indices.py#L5418-L5421

You can add the index on groupassignee by running the following command
CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS "sentry_groupasignee_project_id_group_id_fbf4364e_uniq" ON "sentry_groupasignee" (project_id, group_id)

**Comment by bobvandevijver** [comment]
@nikhars The migration you mention is not executed before the one in this MR though...

```
Running migrations:
  Applying sentry.0198_add_project_transaction_threshold... OK
  Applying sentry.0199_release_semver... OK
  Applying sentry.0200_release_indices... OK
  Applying sentry.0201_semver_package... OK
  Applying sentry.0202_org_slug_upper_idx... OK
  Applying sentry.0203_groupedmessage_status_index... OK
  Applying sentry.0204_use_project_team_for_team_key_transactions... OK
  Applying sentry.0205_semver_backfill... OK
  Applying sentry.0206_organization_require_email_verification_flag... OK
  Applying sentry.0207_release_adoption... OK
  Applying sentry.0208_add_team_scope... OK
  Applying sentry.0209_avatar_remove_file_fk... OK
  Applying sentry.0210_backfill_project_transaction_thresholds... OK
  Applying sentry.0211_add_artifact_count... OK
  Applying sentry.0212_appconnectbuilds... OK
  Applying sentry.0213_rule_project_status_owner_index... OK
  Applying sentry.0214_activity_project_type_datetime_idx... OK
  Applying sentry.0215_fix_state... OK
  Applying sentry.0216_cdc_setup_replication_index...Traceback (most recent call last):
```

**Comment by bobvandevijver** [comment]
It seems that 21.6.3 did indeed fix the migration issue.

**Comment by pataar** [comment]
Yes, can confirm this as well

**Pull request merged**
