### PR TITLE
feat(perf): Add feature flag for performance on-boarding checklist

### PR DESCRIPTION
**Pull request by dashed**
This feature flag will gate the UI portion of the Performance on-boarding checklist.

### CODE REVIEW

**Comment by udameli** [comment]
should https://github.com/getsentry/sentry/blob/master/src/sentry/conf/server.py be updated as well?

**Comment by dashed** [comment]
@udameli done 👍

**Review by 0Calories — APPROVED** [review]

**Review by udameli — APPROVED** [review]
🌟

**Review by priscilawebdev — APPROVED** [review]
one more for good luck :)

**Pull request merged**
