### PR TITLE
Fail to render event_details when there's more than one UserReport for an event id

### PR DESCRIPTION
**Pull request by mattrobenolt**
Fixes SENTRY-16W

@getsentry/infrastructure

### CODE REVIEW

**Comment by JTCunning** [comment]
LGTM

**Comment by mattrobenolt** [comment]
@ckj brought up a good point. Why were there two UserReports here in the first place. There should only ever be one.

**Comment by dcramer** [comment]
null unique constraint?






On Thu, Apr 28, 2016 at 3:11 PM -0700, "Matt Robenolt" <notifications@github.com> wrote:












@ckj brought up a good point. Why were there two UserReports here in the first place. There should only ever be one.

**Comment by mattrobenolt** [comment]
> null unique constraint?

Why a null? We can do a UNIQUE on `(project_id, event_id)` here without an issue. I wasn't sure if this was an oversight or an explicit reason to be done this way.

Turns out, a user was poking around with the client and explicitly did this. So I don't think we need to be overly defensive here, but it did break the app then to view the event details page. So we should either reject the input, override an existing entry with `create_or_update`, or just ignore multiple records and choose the latest (what I proposed here before I fully understood what was going on).

**Comment by dcramer** [comment]
lgtm

**Comment by mattrobenolt** [comment]
@dcramer Just updated this to use a UNIQUE constraint instead, and the API now updates an existing one if found, rather than just erroring out all over the place.

**Comment by mitsuhiko** [comment]
@mattrobenolt we should merge this. there are already so many migration PRs pending and cooking and this one is basically already signed off.

**Comment by mattrobenolt** [comment]
Yeah, gonna rebase, recreate migration, and merge this now.

**Pull request merged**
