### PR TITLE
WIP: Component styleguide using Storybook

### PR DESCRIPTION
**Pull request by billyvg**
Continuing work of #5521 in a new branch.

Uses [storybook](https://github.com/storybooks/storybook) instead of writing own styleguide

TODOS before merging:
* [X] Acceptance test (Percy) needs to capture the styleguide properly
* [X] Investigate if it's possible to omit `style-loader!` from LESS imports
~~Component examples should be documented _with the component_, either in an `__examples__` "hidden" folder or something else~~
~~Those examples should be automatically found by a Webpack configuration; we shouldn't have to manually import / render them~~
~~Make newly introduced JS dependencies (e.g. `react-syntax-highlighter`) devDependencies instead, ensure styleguide is only accessible when Sentry is run with `DEBUG=True`~~

### CODE REVIEW

**Comment by getsentry-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by getsentry-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Changes to build requirements</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by billyvg** [comment]
I think webpack config has the highest potential to break things, nearly everything else is pretty isolated.

**Comment by billyvg** [comment]
I'm splitting up this PR into multiple PRs.

**Pull request closed without merging**
