### PR TITLE
`npm install` with `--production` to avoid `devDependencies`

### PR DESCRIPTION
**Pull request by mattrobenolt**
@getsentry/javascript

### CODE REVIEW

**Comment by benvinegar** [comment]
👍

**Comment by benvinegar** [comment]
Actually, scratch that – we have a few dependencies erroneously listed in `devDependencies` when they should be in `dependencies`. I can push a commit to this branch.

**Comment by mattrobenolt** [comment]
Going to hold off on this util @benvinegar audits to make sure we can get away with just `dependencies` and nothing relies on `devDependencies` for production builds.

**Comment by mattrobenolt** [comment]
Going to test this out today before blindly merging.

**Comment by mattrobenolt** [comment]
:cookie:

**Pull request merged**
