### PR TITLE
upgrade(redis-py): Upgrade redis-py to 3.4.1

### PR DESCRIPTION
**Pull request by BYK**
Came by this error on the forums: https://forum.sentry.io/t/worker-error-unable-to-incr-internal-metric/13098?u=byk and then found andymccurdy/redis-py#1138 which got fixed in version 3.4.0. This patch upgrades it to `3.4.1` which has a fix for a regression introduced in `3.4.0`. No breaking changes.

### CODE REVIEW

**Comment by BYK** [comment]
Ughh, this is `rb` being overly strict. @wedamija do you have control over that package to loosen the `redis` requirement a bit?

**Comment by wedamija** [comment]
> Ughh, this is `rb` being overly strict. @wedamija do you have control over that package to loosen the `redis` requirement a bit?

We own `rb`, so we can just change it as needed. You can make a pr here: https://github.com/getsentry/rb/

Did you review the changes in 3.4.x? Bumping redis isn't necessarily trivial

**Review by wedamija — APPROVED** [review]
Changes look safe, assuming ci passed after we update `rb`

**Comment by billyvg** [comment]
@BYK The `js build and lint` is failing due to unrelated reasons, I'll have a fix for it shortly - this PR is good to merge

**Review by joshuarli — APPROVED** [review]
Sorry, late to seeing this. All looks good to me, thanks for doing this. I had this redis upgrade planned to do soon.

**Pull request merged**
