### PR TITLE
fix: Use json encoding in trim() when we have reached max depth.

### PR DESCRIPTION
**Pull request by alex-hofsteede**
When we reach the max depth (3) of a nested dictionary, we serialize
the remaining levels (and potentially truncate the resulting string if
it is too long). This change just uses json.dumps() instead of repr() so
that the resulting string doesn't contain python-specific junk like
`u'foo'`.

Related issue: https://github.com/getsentry/sentry/issues/5303

### CODE REVIEW

**Review by evanpurkhiser — APPROVED** [review]

**Comment by mitsuhiko** [comment]
Damn I was too slow

**Comment by mitsuhiko** [comment]
screen shot 2017-12-14 at 00 23 36

**Comment by alex-hofsteede** [comment]
@mitsuhiko sure, I can add that. What's the reasoning, just for better readability?

**Comment by mitsuhiko** [comment]
Mostly just because the escaping that json adds makes not too much sense for stuff outside the basic plane. eg:

```
>>> print json.dumps(u'💩')
"\ud83d\udca9"
```

**Pull request merged**
