### PR TITLE
ref(login): Translate session expired warning message

### PR DESCRIPTION
**Pull request by floels**
The goal of this PR is to fix a `TODO` comment in `sentry/src/constants.py` asking to translate the warning message for session expiration.

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Comment by floels** [comment]
Hi @chadwhitacre,

I opened this PR a couple of days ago and I'm not sure how to get reviews. Should I mention a particular team in a comment?

**Comment by chadwhitacre** [comment]
Thanks for the ping, @floels! Sorry this fell through the cracks. Hrm ... 🤔

Our normal routing and triage process doesn't cover PRs (goes to show how many more issues than PRs we get 😅). I've filed https://github.com/getsentry/team-ospo/issues/113 to expand to PRs.

Lgtm but let's see what @getsentry/app-frontend thinks.

**Review by markstory — APPROVED** [review]

**Comment by chadwhitacre** [comment]
Thanks for the contribution, @floels! :)

**Comment by floels** [comment]
Thanks @chadwhitacre for the help 🙏

**Pull request merged**
