### PR TITLE
fix ListField to raise validation error when values are None fixes SENTRY-3CJ

### PR DESCRIPTION
**Pull request by macqueen**
#nochanges 

https://sentry.io/sentry/sentry/issues/274048764/

### CODE REVIEW

**Comment by mattrobenolt** [comment]
Are there any cases where we expect this to work with the current behavior? I'm asking basically if we should instead introduce a new type that explicitly doesn't allow nulls.

**Comment by mattrobenolt** [comment]
Yeah, looking at this, it seems like this validation should happen within `ReleaseHeadCommitSerializer` to reject None values.

This validations hould happen as a part of `ListField.child`'s validation.

**Comment by macqueen** [comment]
@mattrobenolt i was originally going to do that, but it should also be the case for `CommitSerializer`, and from what i could tell, every other use case of `ListField` where a child was specified (should `sensitiveFields`, `safeFields`, `redirectUris`, `allowedOrigins` and `checksums` really allow null?) what about at least doing something like adding `allow_null=True`? to me, specifying a child serializer suggests you expect the nested item to be something other than null so we should probably support it in the `ListSerializer`

**Comment by macqueen** [comment]
also https://sentry.io/sentry/sentry/issues/275168843/

**Comment by mattrobenolt** [comment]
I'd call this `allow_null` since it's a serializer with input being JSON. But that's a minor nit.

Do we have tests for the actual `ListField` that we can add? I'd rather not be testing behavior of the ListField _through_ another serializer's implementation. That means if we drop say, `ReleaseSerializerWithProjects` at some point, we'll lose test coverage of this behavior.

**Review by mattrobenolt — APPROVED** [review]

**Pull request merged**
