### PR TITLE
ref(replay): replace some replay `ObjectInspector` references

### PR DESCRIPTION
**Pull request by michellewzhang**
relates to https://github.com/getsentry/sentry/issues/70042

replaces some instances of `ObjectInspector` in replay details with the issues `StructuredEventData` -- namely, instances on the network tab.

|  after `StructuredEventData` |  before `ObjectInspector`|
| ------------- | ------------- |
| SCR-20240710-odxm | SCR-20240710-oebz |
| SCR-20240710-oktd | SCR-20240710-olfl |

### CODE REVIEW

**Comment by aliu39** [comment]
where are other references?

**Comment by michellewzhang** [comment]
> where are other references?

SCR-20240710-oogf

**Review by aliu39 — APPROVED** [review]

**Review by billyvg — APPROVED** [review]
Ugh don't love that this component doesn't quote the strings -- this means that copy/pasting isn't guaranteed to have valid JSON.

image

**Comment by michellewzhang** [comment]
> Ugh don't love that this component doesn't quote the strings -- this means that copy/pasting isn't guaranteed to have valid JSON.
> 
> image

yeah, it looks like we can customize how we render only certain types of data types :( object keys for example, but not object values

https://github.com/getsentry/sentry/blob/1d8bcf330d7ea91be04df91579f958d9a46627e1/static/app/components/structuredEventData/index.tsx#L21-L30

**Pull request merged**
