### PR TITLE
fix(org-tokens): Add org token url to python

### PR DESCRIPTION
**Pull request by mydea**
Adding this new page here as well - I hope that helps to make redirects without an org work...?

### CODE REVIEW

**Comment by mydea** [comment]
No, TBH I don't even know what that does exactly 😅

**Review by markstory — COMMENTED** [review]
It would be good to verify that this will fix the redirect issue you're having with auth-tokens routes. You should be able to do that locally using getsentry+sentry together.

**Comment by iambriccardo** [comment]
> No, TBH I don't even know what that does exactly 😅

Glad that I asked, lol. Let me know if you need any help to locally set it up!

**Comment by mydea** [comment]
So after a bit of a struggle, I managed to set it up locally. However, it seems to always redirect me to `http://sentry-3n.dev.getsentry.net:8000/settings/organization/`, from `http://dev.getsentry.net:8000/settings/auth-tokens'`. but this also happens for e.g. `http://dev.getsentry.net:8000/settings/members/` or literally anything after `/settings/` for me 😓

**Comment by mydea** [comment]
So I _think_ we can still merge this because it _improved_ this (previously you'd get to the issues page, which I think is the fallback or something like this), but it doesn't fix the thing we set out to fix, which is exactly the problem that we do not know the org in the docs, so we can't include it in the URL sadly 😬 

What we want (but is a different thing then to this PR) is to have _a_ URL we can put in docs that will send users to the org token page of their org 🤔  To clarify the problem, if you're e.g. here in the docs:
image

We want to show a URL to users that they can go to. But if the user is not logged in, we don't know an org, so can't include that in the URL 😢

**Review by markstory — APPROVED** [review]

**Pull request merged**
