### PR TITLE
chore: Test react v17rc

### PR DESCRIPTION
**Pull request by matejminar**
#test-getsentry

### CODE REVIEW

**Comment by matejminar** [comment]
Looks like there is some sort of a problem with mounting in tests, but I didn't have time to study it into greater detail.

**Comment by billyvg** [comment]
Looks like https://github.com/getsentry/sentry/blob/0edc7c15a268106c2f293ef0730e86cf971b6a5d/src/sentry/static/sentry/app/stores/tooltipStore.tsx#L21 is a culprit cc @k-fish

**Comment by billyvg** [comment]
Our jest tests will be blocked by https://github.com/enzymejs/enzyme/issues/2429

**Comment by k-fish** [comment]
@billyvg damn, thought I'd have more than a few weeks before using internals bit me 😄. If we merge in https://github.com/getsentry/sentry/pull/20825 I think we should be fine on either side of the upgrade (if I'm reading the changes correctly).

**Pull request closed without merging**
