### PR TITLE
fix(awslambda): Fix bug when manually adding handler without adding the env variables

### PR DESCRIPTION
**Pull request by ahmedetefy**
This PR fixes https://getsentry.atlassian.net/browse/GRW-70

Changes:
- Added a check that also checks if env `SENTRY_INITIAL_HANDLER` is set and if not classifies as an disabled lambda function

### CODE REVIEW

**Comment by armenzg** [comment]
👋🏻 😄

**Comment by ahmedetefy** [comment]
oops was hoping no one would notice! might have gone nuts trying to rebase xD

**Comment by armenzg** [comment]
Since I joined Sentry, I've been trying to use Draft PRs until I'm sure things pass and the diff looks good since I know that normal PRs will summon the code owners! :)

**Comment by ahmedetefy** [comment]
Yeah will keep that in mind! Thanks :)

**Pull request closed without merging**
