### PR TITLE
Upgrade to React 15.2.1 [try 2] (#3689)

### PR DESCRIPTION
**Pull request by benvinegar**
This change is [Reviewable](https://reviewable.io/reviews/getsentry/sentry/3734)

### CODE REVIEW

**Comment by benvinegar** [comment]
Current status is that the acceptance tests on Travis CI really do not like this branch. They pass 100% locally on OS X, but on Travis CI (Ubuntu), the acceptance tests can't seem to connect to WebDriver/PhantomJS – even on pages that don't load any JavaScript/React at all (i.e. mail debug views).

Currently out of ideas.

**Comment by benvinegar** [comment]
@fotinakis – @dcramer suggested I reach out. Ever seen this (^) before?

**Comment by fotinakis** [comment]
@benvinegar unfortunately I haven't seen that, my experience with Selenium is usually through a Ruby wrapper library and I have very little knowledge of the python webdrivers. This looks like what is happening: http://stackoverflow.com/a/27530824/128597

**Comment by benvinegar** [comment]
> This looks like what is happening: http://stackoverflow.com/a/27530824/128597

Yep, found that link, but the issue here is that Selenium isn't even starting once. Seems like it might be Travis related, because it magically cleaned up by itself.

**Pull request merged**
