### PR TITLE
feat(plugins): Add discord webhook plugin

### PR DESCRIPTION
**Pull request by ryantam626**
Add discord webhook plugin that uses the vanilla webhook[1].

While the discord slack-compatible webhook[2] and Sentry legacy plugin work together in principle, it is not possible to utilise the `custom_message` field to trigger mentions in Discord, since Discord show the entire message in a single embed including the `custom_message` field content, whereby any scheme of mention is disabled (@here, @everyone, <@userid>, @<#channelid>).

With the vanilla webhook, we can preserve the embed in a similar format and add the `custom_message` field content as part of a normal message (as opposed to being part of the embed), whereby all scheme of mention works.

This commit is almost a one-to-one translation of the legacy Slack plugin, colours are translated from hex to decimal with https://www.spycolor.com/, field names have changed to adapt to using the vanilla webhook. Further functionality such as thread creation, customisable embed colour, user interaction with buttons, etc. are out of scope in this PR.

[1] - https://discord.com/developers/docs/resources/webhook#execute-webhook
[2] - https://discord.com/developers/docs/resources/webhook#execute-slackcompatible-webhook

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Comment by ryantam626** [comment]
> rotating_light **Warning:** This pull request contains Frontend and Backend changes!
> 
> It's discouraged to make changes to Sentry's Frontend and Backend in a single pull request. The Frontend and Backend are **not** atomically deployed. If the changes are interdependent of each other, they **must** be separated into two pull requests and be made forward or backwards compatible, such that the Backend or Frontend can be safely deployed independently.
> 
> Have questions? Please ask in the [`#discuss-dev-infra` channel](https://app.slack.com/client/T024ZCV9U/CTJL7358X).

Oops. Let me know if I should split this out.

FWIW, I first implemented changes for backend, it gracefully filled in the missing logo `</>` as expected. And I suspect having an svg in the frontend would have too big of a side effect? i.e. I think the release order doesn't matter here.

**Comment by ryantam626** [comment]
Just some screenshot to showcase the mentioning system works as expected.
image
image

**Comment by brianthi** [comment]
Hi @ryantam626, thanks for all the efforts to create this PR. The good news is that we've started working on a native integration for Discord. The plan is to have it generally available around August/September this year. Having said that, we wouldn't want to keep two integrations around for the same service, so unfortunately I'll need to close this PR. 

Keep track of this [Github Issue](https://github.com/getsentry/sentry/issues/10925), as we'll likely post an update there looking for early access testers. We'll be more than happy to have you be part of that group if that's something you're interested in.

**Comment by chadwhitacre** [comment]
> The good news is that we've started working on a native integration for Discord.

Whoa!!!! TIL 😳 Awesome! 😁 👍 💃

**Pull request closed without merging**
