### PR TITLE
ref(ui) Replace icon-arrow-down with IconChevron

### PR DESCRIPTION
**Pull request by markstory**
Replace another font-icon with new SVG icons.

### CODE REVIEW

**Review by billyvg — APPROVED** [review]
sad snapshots

**Comment by markstory** [comment]
@billyvg Do you think the 1px shift to the left should be fixed?

**Comment by billyvg** [comment]
@markstory ah was referring to the jest snapshots - I think the shift to me is a slight improvement, but might be worth double checking with a designer

**Comment by priscilawebdev** [comment]
I would add 1px to the left here 
image

**Comment by priscilawebdev** [comment]
it seems to me that here the arrow is not centered

image

**Pull request merged**
