### PR TITLE
Add server-side filters

### PR DESCRIPTION
**Pull request by dcramer**
This will allow users to configure a project to automatically filter out (blacklist) events submitted in certain situations.

@getsentry/infrastructure 

This change is [Reviewable](https://reviewable.io/reviews/getsentry/sentry/3702)

### CODE REVIEW

**Comment by dcramer** [comment]
This is obviously not done, but I'd be curious on what people think? All that is left is to implement which filters we want to provide.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3702#-:-KMWDO8q_eiEIJSbcRHp:-437832456)*

**Comment by mitsuhiko** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/sentry/web/api.py, line 328 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/3702#-KMa87pihKrgEB0y7oa9:-KMa87pihKrgEB0y7oaA:-1046069954) ([raw file](https://github.com/getsentry/sentry/blob/a5f5048447f71363ea3851d37a477aec73257e76/src/sentry/web/api.py#L328)):*
> ```Python
>             ])
> 
>         content_encoding = request.META.get('HTTP_CONTENT_ENCODING', '')
> ```

why did you kill all of this? seems unrelated to the rest of the code and we actually depend on this in the python sdk i think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3702)*

**Comment by mitsuhiko** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/sentry/web/api.py, line 328 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/3702#-KMa87pihKrgEB0y7oa9:-KMa8jE6pRQpNXoFy13Z:46617446) ([raw file](https://github.com/getsentry/sentry/blob/a5f5048447f71363ea3851d37a477aec73257e76/src/sentry/web/api.py#L328)):*
<details><summary><i>Previously, mitsuhiko (Armin Ronacher) wrote…</i></summary>
> why did you kill all of this? seems unrelated to the rest of the code and we actually depend on this in the python sdk i think.
</details>
Oh nevermind. We pull the header in elsewhere still.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3702)*

**Comment by mitsuhiko** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3702)*

**Comment by tkaemming** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/sentry/web/api.py, line 299 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/3702#-KN4c2bseeqlZOKLew51:-KN4c2bseeqlZOKLew52:-835028383) ([raw file](https://github.com/getsentry/sentry/blob/d495f32566fb9a9ff4d520cad2335fa45be59927/src/sentry/web/api.py#L299)):*
> ```Python
>         )
> 
>         if not is_valid_ip(remote_addr, project):
> ```

It seems like it might make sense to move the IP check here to a filter for consistency.

---

*[src/sentry/web/api.py, line 309 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/3702#-KN4dSAbVTYKS5YOFcZa:-KN4dSAbVTYKS5YOFcZb:-1362829424) ([raw file](https://github.com/getsentry/sentry/blob/d495f32566fb9a9ff4d520cad2335fa45be59927/src/sentry/web/api.py#L309)):*
> ```Python
>             raise APIForbidden('Blacklisted IP address: %s' % (remote_addr,))
> 
>         if helper.should_filter(data, project):
> ```

A little surprised to see this happen before rate limiting is applied.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3702)*

**Comment by dcramer** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/sentry/web/api.py, line 309 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/3702#-KN4dSAbVTYKS5YOFcZa:-KN4eBxUXolvaA3zxtWp:-1177891174) ([raw file](https://github.com/getsentry/sentry/blob/d495f32566fb9a9ff4d520cad2335fa45be59927/src/sentry/web/api.py#L309)):*
<details><summary><i>Previously, tkaemming (ted kaemming) wrote…</i></summary>
> A little surprised to see this happen before rate limiting is applied.
</details>
thats intentional -- the feature is designed so that we (for now) bear the brunt of the cost, and allow them to discard various things (prescribed options) before rate limiting. If it were after rate limiting it wouldn't be overly useful, as it wouldn't save them anything.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3702)*

**Comment by dcramer** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/sentry/web/api.py, line 299 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/3702#-KN4c2bseeqlZOKLew51:-KNIRsAP1bS2SGpbp3_8:-499146009) ([raw file](https://github.com/getsentry/sentry/blob/d495f32566fb9a9ff4d520cad2335fa45be59927/src/sentry/web/api.py#L299)):*
<details><summary><i>Previously, tkaemming (ted kaemming) wrote…</i></summary>
> It seems like it might make sense to move the IP check here to a filter for consistency.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3702)*

**Comment by tkaemming** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/sentry/coreapi.py, line 800 \[r3\]](https://reviewable.io:443/reviews/getsentry/sentry/3702#-KNnOdub5uMDkfgjLh-Q:-KNnOdub5uMDkfgjLh-R:421528092) ([raw file](https://github.com/getsentry/sentry/blob/b62f9cf00b868e54350758a9ec4583c11b31adad/src/sentry/coreapi.py#L800)):*
> ```Python
>         del self._data[name]
> 
>     def __contains__(self, name):
> ```

Out of curiosity, was there a reason you chose to implement this directly rather than use the mixin method from `MutableMapping`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3702)*

**Comment by dcramer** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/sentry/coreapi.py, line 800 \[r3\]](https://reviewable.io:443/reviews/getsentry/sentry/3702#-KNnOdub5uMDkfgjLh-Q:-KNwoc4E2-v-08s3p_1M:151656084) ([raw file](https://github.com/getsentry/sentry/blob/b62f9cf00b868e54350758a9ec4583c11b31adad/src/sentry/coreapi.py#L800)):*
<details><summary><i>Previously, tkaemming (ted kaemming) wrote…</i></summary>
> Out of curiosity, was there a reason you chose to implement this directly rather than use the mixin method from `MutableMapping`?
</details>
I'm not sure if I had a reason or not. In theory my implementation is faster, but I imagine I just didn't think that __contains__ was available.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3702)*

**Comment by dcramer** [comment]
Gonna merge this in so we can finish this feature

**Comment by dcramer** [comment]
I think this needs a fresh look as I had to go in and change a bunch of CSP code as well

**Pull request merged**
