### PR TITLE
fix(tooltips-safari): Update css in the switch button fixing tooltips not closing on safari - [TET-601]

### PR DESCRIPTION
**Pull request by priscilawebdev**
**Before:**

https://user-images.githubusercontent.com/29228205/208652163-247b6905-f380-40a2-8af2-51620aea8f1a.mov

**After:**

https://user-images.githubusercontent.com/29228205/208652038-7b3db18c-60b5-483b-a685-b99e31e9e0e7.mov

### CODE REVIEW

**Comment by evanpurkhiser** [comment]
do we set aria-disabled?

**Review by evanpurkhiser — CHANGES_REQUESTED** [review]
Gonna take a look at this in a couple hours if that’s ok. I’d like to check something

**Comment by priscilawebdev** [comment]
the issue happens if with `aria-disabled`

**Comment by evanpurkhiser** [comment]
With this change how are tests able to check if a switch is disabled?

How did we fix this on disabled buttons?

**Comment by priscilawebdev** [comment]
We discussed this issue offline and concluded that this must be a bug in safari because the `onPointerLeave` event does not fire as expected, causing the tooltip not to be removed.

Other folks like @scttcper  tried to solve this problem in the past too and mentioned that this, although seems simple, is not straightforward.

The conclusion is that we will replace the `button` element used in the `Switch` component with some other element, to try to solve the problem.

As we talked, I am handing over this issue to the @getsentry/core-ui team

**Pull request closed without merging**
