### PR TITLE
ci: Push docker images to dockerhub from github action for e2e tests

### PR DESCRIPTION
**Pull request by emmatyping**
This should push images to dockerhub with a `-tmp` tag while we make sure this workflow works. In a couple of days this will become the default for pushing images for self-hosted to DockerHub.

### CODE REVIEW

**Review by joshuarli — CHANGES_REQUESTED** [review]
Can you move your `Push built docker image` step into here? So that we have an explicit step for it rather than it being mashed under `Run Sentry self-hosted e2e CI`. It'd also be more obvious that the explicit step's skipped if it isn't on the master/main branch.

**Comment by ethanhs** [comment]
> Can you move your Push built docker image step into here? 

I'd like to keep that consistent as well, so that we can keep tagging and pushing to dockerhub consistent as well. Looking at relay/snuba/sentry there were several different ways that images were getting tagged.

**Comment by joshuarli** [comment]
> > Can you move your Push built docker image step into here?
> 
> I'd like to keep that centralized/consistent as well, so that we can keep tagging and pushing to dockerhub consistent as well. Looking at relay/snuba/sentry there were several different ways that images were getting tagged.

Snuba and relay have cloudbuild.yaml for tagging and pushing images. If you want to be consistent in that stuff to tag+push images also exist inside the source repo, then you should follow my recommendation. I don't see how your approach keeps things consistent.

**Comment by ethanhs** [comment]
> Snuba and relay have cloudbuild.yaml for tagging and pushing images
> I don't see how your approach keeps things consistent.

We are planning on removing testing and image pushing from cloudbuild.yml/GCB across Sentry/Relay/Snuba and replacing it with a centralized Github Action (the one referenced here). That is the plan to make everything consistent. More context is in [the issue about centralizing e2e CI/image pushing](https://github.com/getsentry/self-hosted/issues/1756). Perhaps renaming the job would make it clearer that it also pushes images?

**Comment by joshuarli** [comment]
> > Snuba and relay have cloudbuild.yaml for tagging and pushing images
> > I don't see how your approach keeps things consistent.
> 
> We are planning on removing testing and image pushing from cloudbuild.yml/GCB across Sentry/Relay/Snuba and replacing it with a centralized Github Action (the one referenced here). That is the plan to make everything consistent. More context is in [the issue about centralizing e2e CI/image pushing](https://github.com/getsentry/self-hosted/issues/1756). Perhaps renaming the job would make it clearer that it also pushes images?

Oh cool, that's the context I was missing - thanks!

Yeah, if you could rename it at some point, that would make me feel better.

**Review by joshuarli — APPROVED** [review]

**Review by chadwhitacre — APPROVED** [review]

**Review by hubertdeng123 — APPROVED** [review]

**Pull request merged**
