### PR TITLE
fix(perf): Fix HTTP widget documentation link

### LINKED ISSUE #65071: "Add integrations" link on Performance Page leads to nonexistent docs page for golang backend
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to the `Performance` tab in the left-hand main navigation
2. Choose `Backend` in the sub-navigation on the Performance page
3. Choose a Golang project
4. On the "Slow HTTP Ops", if it is empty, you should see the message:
> No transactions with HTTP spans found, you may need to [add integrations](https://docs.sentry.io/platforms/go/configuration/integrations).

image

5. Click on "add integrations"

### Expected Result

The user is redirected to the integrations section of the Golang SDK docs

### Actual Result

The user is redirected to a Page Not Found docs page (because https://github.com/getsentry/sentry-docs/issues/6229 has not been done):
image

### Product Area

Performance

### Link

_No response_

### DSN

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by gggritso**
Fixes #65071

Directs users with no HTTP span to the "Set Up Performance" page rather than the "Integrations" page which doesn't even exist for a lot of platforms.

Maybe the widget copy is a little awkward?

**e.g.,**
Screenshot 2024-02-28 at 3 29 21 PM

### CODE REVIEW

**Comment by vivianyentran** [comment]
Thoughts on this adjustment so that it's more actionable but still links to the performance setup?

"No transactions with HTTP spans found. You may need to add integrations to your [performance monitoring setup ](url)to instrument spans."

**Comment by gggritso** [comment]
@vivianyentran I like that! What do you think about "to capture spans" instead of "to instrument spans"? I think we usually say that spans are "captured", and instrumentation is "added" to a codebase or application

**Comment by vivianyentran** [comment]
Good suggestion! "Capture spans" definitely makes more sense in this case!

**Comment by gggritso** [comment]
@vivianyentran done 👍🏻

**Review by vivianyentran — APPROVED** [review]
copy LGTM! 👍

**Pull request merged**
