### PR TITLE
simplify formatBytes func

### PR DESCRIPTION
**Pull request by hustcc**
set `units` complete array, use `while` replace of `do ... while`. [Here](https://github.com/hustcc/filesize.js/blob/master/src/filesize.js#L49-L52).

---

This change is [Reviewable](https://reviewable.io/reviews/getsentry/sentry/4206)

### CODE REVIEW

**Comment by hustcc** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/4206)*

**Comment by hustcc** [comment]
Why I can do the `Reviewable` process ?

Nice tool ^_^.

**Comment by benvinegar** [comment]
Stylistically, we chose to show KB rather than B, even if its a decimal.

**Comment by hustcc** [comment]
You means when the file is 750 B, it  should be 0.75 KB ? But 

```js
if (bytes < thresh) {
        return bytes + ' B';
}
```
the origin code will return bytes when lt 1024.

This pr do not modify the input / output, just simplify the code.

**Comment by benvinegar** [comment]
Ah. Well, if you could supply a test verifying this, I'd be glad to merge.

**Comment by hustcc** [comment]
So how to add testcases ? I can't find some demos in `tests` dir.

**Comment by hustcc** [comment]
is testcase [here](https://github.com/hustcc/filesize.js) ok?

**Pull request closed without merging**
