### PR TITLE
perf(perf-issues): apply hasAny on the group_ids column instead of arrayJoining and filter

### PR DESCRIPTION
**Pull request by barkbarkimashark**
Possible query optimization to do some filtering on the column before arrayJoining and filtering.

Before query:
```
SELECT (arrayJoin((group_ids AS _snuba_group_ids)) AS _snuba_group_id), _snuba_group_id, (count() AS _snuba_times_seen), (min((finish_ts AS _snuba_timestamp)) AS _snuba_first_seen), (max(_snuba_timestamp) AS _snuba_last_seen), (ifNull(uniq((user AS `_snuba_tags[sentry:user]`)), 0) AS _snuba_count)
  FROM transactions_local
 WHERE greaterOrEquals((finish_ts AS _snuba_finish_ts), toDateTime('2022-09-15T18:52:01', 'Universal'))
   AND less(_snuba_finish_ts, toDateTime('2022-09-16T18:52:01', 'Universal'))
   AND in((project_id AS _snuba_project_id), tuple(1))
   AND in(_snuba_project_id, tuple(1))
   AND in(_snuba_group_id, tuple(3571022555))
   AND in((environment AS _snuba_environment), tuple('prod'))
 GROUP BY _snuba_group_id
 LIMIT 1000
OFFSET 0
```

after:
```
SELECT (arrayJoin((group_ids AS _snuba_group_ids)) AS _snuba_group_id), _snuba_group_id, (count() AS _snuba_times_seen), (min((finish_ts AS _snuba_timestamp)) AS _snuba_first_seen), (max(_snuba_timestamp) AS _snuba_last_seen), (ifNull(uniq((user AS `_snuba_tags[sentry:user]`)), 0) AS _snuba_count)
  FROM transactions_local
 WHERE greaterOrEquals((finish_ts AS _snuba_finish_ts), toDateTime('2022-11-11T21:07:23', 'Universal'))
   AND less(_snuba_finish_ts, toDateTime('2022-11-11T23:07:23', 'Universal'))
   AND in((project_id AS _snuba_project_id), tuple(4550919112556546))
   AND equals(hasAny(_snuba_group_ids, [1]), 1)
   AND in(_snuba_project_id, tuple(4550919112556546))
   AND in((environment AS _snuba_environment), tuple('morally primary rooster'))
 GROUP BY _snuba_group_id
 LIMIT 1000
OFFSET 0
```

### CODE REVIEW

**Review by wedamija — COMMENTED** [review]
I thought we tried something like this before? Probably worth having sns run these in prod to see if there's any improvement

**Comment by barkbarkimashark** [comment]
> I thought we tried something like this before? Probably worth having sns run these in prod to see if there's any improvement

Yeah, we ran an analysis but I think the analysis might've been flawed. Instead of pre-filtering rows with `has(group_ids, <group_ids>`, it looks like we ended up arrayJoining first and then filtering.

At least that's what I can gather from discussing with SNS team and looking at the first attempt optimization query:
```
SELECT (arrayJoin((group_ids AS _snuba_group_ids)) AS _snuba_group_id), _snuba_group_id, (count() AS _snuba_times_seen), (min((finish_ts AS _snuba_timestamp)) AS _snuba_first_seen), (max(_snuba_timestamp) AS _snuba_last_seen), (ifNull(uniq((user AS `_snuba_tags[sentry:user]`)), 0) AS _snuba_count)
  FROM transactions_local
 WHERE greaterOrEquals((finish_ts AS _snuba_finish_ts), toDateTime('2022-09-15T18:52:01', 'Universal'))
   AND less(_snuba_finish_ts, toDateTime('2022-09-16T18:52:01', 'Universal'))
   AND in((project_id AS _snuba_project_id), tuple(1))
   AND equals(hasAny(_snuba_group_ids, [3571022555]), 1)
   AND in(_snuba_project_id, tuple(1))
   AND in(_snuba_group_id, tuple(3571022555))
   AND in((environment AS _snuba_environment), tuple('prod'))
 GROUP BY _snuba_group_id
 LIMIT 1000
OFFSET 0
```

It's not obvious from the above query whether clickhouse would prune the rows by the `hasAny` before doing an arrayJoin, or would it just do the arrayJoin and ignore the `equals(hasAny(_snuba_group_ids, [3571022555]), 1)` expression. Will run another analysis with these changes and see if that makes a difference.

**Comment by evanh** [comment]
Did a couple tests, and the `hasAny` is better. Clickhouse moves it to the PREWHERE clause.

```[Debug] InterpreterSelectQuery: MergeTreeWhereOptimizer: condition "(hasAny(group_ids AS _snuba_group_ids, [1]) = 1) AND ((environment AS _snuba_environment) IN tuple('morally primary rooster'))" moved to PREWHERE```

**Comment by barkbarkimashark** [comment]
> Did a couple tests, and the `hasAny` is better. Clickhouse moves it to the PREWHERE clause.
> 
> `[Debug] InterpreterSelectQuery: MergeTreeWhereOptimizer: condition "(hasAny(group_ids AS _snuba_group_ids, [1]) = 1) AND ((environment AS _snuba_environment) IN tuple('morally primary rooster'))" moved to PREWHERE`

Sweet, thanks @evanh!

**Review by wedamija — APPROVED** [review]
Nice fix, let's use performance to see how much this improves our load times on the issue list.

Could we also make this change in the issue search code? (Actually I guess it won't help much since we don't have specific group ids to work with all the time)

**Pull request merged**
