### PR TITLE
Vertically center group items

### LINKED ISSUE #5986: Incorrect spacing on issue list items without a description
image

Note the spacing of the graph in the last item as well as the spacing of the `SENTRY-3XA` text.

### PR DESCRIPTION
**Pull request by evanpurkhiser**
Fixes GH-5986

Before: 
image

After:
image

As well as

Before: 
image

After: 
image

### CODE REVIEW

**Review by ckj — APPROVED** [review]
LGTM 🤘

**Comment by EvanPurkhiser** [comment]
Sat down with @ckj and fixed up a couple other items related to this. Ready for final review.

**Comment by getsentry-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by ckj** [comment]
Looks good 💅

**Pull request merged**
