### PR TITLE
fix(ui) Fix overflow on organization dashboard card

### PR DESCRIPTION
**Pull request by markstory**
Hide overflow text on project cards. Due to the dom structure ellipsis isn't entirely visible.

### Before

screen shot 2018-09-21 at 5 16 25 pm

### After

screen shot 2018-09-21 at 4 48 57 pm

### CODE REVIEW

**Comment by EvanPurkhiser** [comment]
Can we add a bit more margin to the right?

**Comment by markstory** [comment]
@EvanPurkhiser Added '1' spacer to the left side.

**Comment by markstory** [comment]
New After
screen shot 2018-09-25 at 12 07 55 pm

**Review by billyvg — APPROVED** [review]
It would be nice to have ellipsis, but this is better than the overflow. Would tooltips be too intrusive here?

**Comment by Chrissy** [comment]
@mark did you look at https://css-tricks.com/flexbox-truncated-text/

The trick with these is you need a non-flexed div as a parent.

**Comment by markstory** [comment]
@Chrissy I didn't see that. I'll see if I can adapt that to our components.

**Comment by markstory** [comment]
@Chrissy I was able to get it to work. Thanks for the link 🙇

**Comment by Chrissy** [comment]
@markstory NICE!! now we shall party in the temple of ellipsis.

**Pull request merged**
