### PR TITLE
feat(migration): Correctly mark existing savedsearch visibility

### PR DESCRIPTION
**Pull request by evanpurkhiser**
This is a follow up to GH-40874.

Now that we have a visibility column we need to set proper defaults for the existing rows.

Pinned searches get `Visibility.OWNER_PINNED`, all others get `Visibility.ORGANIZATION`

I **do NOT have this marked as dangerous**, since I am expecting to run this __after__ we've finished running GH-40753. At which point we'll only have ~20,580 rows to mutate.

### CODE REVIEW

**Comment by evanpurkhiser** [comment]
I'm aware this is missing the migration_lock.txt as well. I'll add it in once dependencies are merged.

**Review by wedamija — APPROVED** [review]

**Review by wedamija — COMMENTED** [review]
The table should be tiny at this point right? So no need for is_dangerous?

**Comment by evanpurkhiser** [comment]
> The table should be tiny at this point right? So no need for is_dangerous?

Yeah, about 20k rows now

**Comment by evanpurkhiser** [comment]
This should be green right around when the script for removing all the old saved search entires is done 🎉

**Pull request merged**
