### PR TITLE
Make sure we encode this version so we don't generate bad API calls

### PR DESCRIPTION
**Pull request by mattrobenolt**
Fixes https://app.getsentry.com/sentry/javascript/issues/111470981/

### CODE REVIEW

**Comment by dcramer** [comment]
I'm fairly sure we had talked about making this change before and didn't because it's incorrect.

@mitsuhiko do you recall?

**Comment by mattrobenolt** [comment]
Well, right now, the problem is we generate an API call that looks like, `/releases/#my version/` for someone, and it causes the API to call a different endpoint since it gets treated as a fragment.

**Comment by mattrobenolt** [comment]
This is also basically related to 6f445eaa GH-2618

**Comment by mattrobenolt** [comment]
@dcramer @mitsuhiko I'm not sure why we wouldn't want to merge this. If it's incorrect, I have no idea why and I'm apparently missing something.

**Pull request merged**
