### PR TITLE
fix(model): use textfield instead of varchar for filenames 

### LINKED ISSUE #36409: API request failed (400 HTTP error): Error about patch_set in commit "Ensure this field has no more than 255 characters."
### Environment

- Ubuntu 20.04.4 LTS
- Sentry SaaS (sentry.io)
- @sentry/cli@1.74.4
- @sentry/webpack-plugin: 1.18.8

### Steps to Reproduce

1. Renamed lot a files with long path (exceed 255 chars)
2. Commit it
3. Run command `sentry-cli releases set-commits repo@5.140.1 --auto --ignore-missing --ignore-empty`

### Expected Result

New Sentry release deployed

### Actual Result

```
error: API request failed

caused by: sentry reported an error: request failure (http status: 400)

Object({"commits": Object({"patch_set": Object({"path": Array([String("Ensure this field has no more than 255 characters.")])})})})

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.

Please attach the full debug log to all bug reports.
```

### PR DESCRIPTION
**Pull request by barkbarkimashark**
Customer reporting an issue where they were submitting commits with filepaths longer than 255 chars. > 255 chars seems high for a file path but its being used.

Other option is we just increase the varchar max_length limit.

### CODE REVIEW

**Comment by dashed** [comment]
@barkbarkimashark you need to generate migration file for this.

**Comment by wedamija** [comment]
> > @barkbarkimashark you need to generate migration file for this.
> 
> Gonna use this as a template:
> 
> https://github.com/getsentry/sentry/blob/f24cfb32705f84ae7df1759d04a89ac1c72ea269/src/sentry/migrations/0280_extend_commit_author_email_length.py#L8

You just need to generate it automatically: https://develop.sentry.dev/database-migrations/#produce-sql-for-a-migration

**Comment by barkbarkimashark** [comment]
> > > @barkbarkimashark you need to generate migration file for this.
> > 
> > 
> > Gonna use this as a template:
> > https://github.com/getsentry/sentry/blob/f24cfb32705f84ae7df1759d04a89ac1c72ea269/src/sentry/migrations/0280_extend_commit_author_email_length.py#L8
> 
> You just need to generate it automatically: https://develop.sentry.dev/database-migrations/#generate-migrations

Yeah, what I meant was the operation.

**Comment by wedamija** [comment]
> > > > @barkbarkimashark you need to generate migration file for this.
> > > 
> > > 
> > > Gonna use this as a template:
> > > https://github.com/getsentry/sentry/blob/f24cfb32705f84ae7df1759d04a89ac1c72ea269/src/sentry/migrations/0280_extend_commit_author_email_length.py#L8
> > 
> > 
> > You just need to generate it automatically: https://develop.sentry.dev/database-migrations/#generate-migrations
> 
> Yeah, what I meant was the operation.

The operation should be automatically produced by that command. For most changes model changes, you shouldn't really need to customize the migration at all.

**Comment by barkbarkimashark** [comment]
> > > > > @barkbarkimashark you need to generate migration file for this.
> > > > 
> > > > 
> > > > Gonna use this as a template:
> > > > https://github.com/getsentry/sentry/blob/f24cfb32705f84ae7df1759d04a89ac1c72ea269/src/sentry/migrations/0280_extend_commit_author_email_length.py#L8
> > > 
> > > 
> > > You just need to generate it automatically: https://develop.sentry.dev/database-migrations/#generate-migrations
> > 
> > 
> > Yeah, what I meant was the operation.
> 
> The operation should be automatically produced by that command. For most changes model changes, you shouldn't really need to customize the migration at all.

Ahhh, interesting ... 

I was using the `--empty` arg and filling in the `operations` array with custom AlterField. Just tried it without the empty flag and it does in fact create the exact same migration as my custom one. Nice. Didn't know that.

**Comment by wedamija** [comment]
> > > > > > @barkbarkimashark you need to generate migration file for this.
> > > > > 
> > > > > 
> > > > > Gonna use this as a template:
> > > > > https://github.com/getsentry/sentry/blob/f24cfb32705f84ae7df1759d04a89ac1c72ea269/src/sentry/migrations/0280_extend_commit_author_email_length.py#L8
> > > > 
> > > > 
> > > > You just need to generate it automatically: https://develop.sentry.dev/database-migrations/#generate-migrations
> > > 
> > > 
> > > Yeah, what I meant was the operation.
> > 
> > 
> > The operation should be automatically produced by that command. For most changes model changes, you shouldn't really need to customize the migration at all.
> 
> Ahhh, interesting ...
> 
> I was using the `--empty` arg and filling in the `operations` array with custom AlterField. Just tried it without the empty flag and it does in fact create the exact same migration as my custom one. Nice. Didn't know that.

Yeah, `--empty` is really just for data migrations

**Review by wedamija — APPROVED** [review]
This looks good to me. This table is 3b rows large, so we need to be a bit cautious here. 

Since we're just changing the type from char -> text, postgres doesn't need to rewrite the table. However, there's a chance we might struggle to acquire a lock since I assume there's a high write volume to this table.

We have a statement and lock acquisition timeout on our migrations now, so worst case here should be that the migration might fail to run due to not being able to acquire the lock. So lets do the following:

- Let me know when you're merging this so that I can keep an eye on the deploy
- Make a pr that switches this migration from `is_dangerous=False` to `True`. Then if we fail to run the migration as part of the deploy, we can merge that and have ops run it manually.

**Pull request merged**
