### PR TITLE
Link to the source of the webhook plugin

### PR DESCRIPTION
**Pull request by kaspergrubbe**
It took me a while to find the source for this plugin. I think the link shouldn't point to the main repo, but instead point to the actual source code.

### CODE REVIEW

**Review by markstory — APPROVED** [review]

**Review by dashed — APPROVED** [review]
Looks good to me

**Comment by kaspergrubbe** [comment]
I'm not sure I'm the reason Travis is failing, but please let me know if I need to do something.

**Comment by dashed** [comment]
@kaspergrubbe It's not you; it's a known flakey test. I've restarted the travis job.

**Comment by kaspergrubbe** [comment]
@dashed Great, thanks :) I can see that it is all green now.

**Comment by dashed** [comment]
@kaspergrubbe awesome thanks! 👍

**Pull request merged**
