### PR TITLE
logging: add transaction_id to group deletions

### PR DESCRIPTION
**Pull request by mattrobenolt**

### CODE REVIEW

**Comment by markstory** [comment]
Is this something we're still interested in pursuing or can it be closed because it can no longer be merged?

**Review by JTCunning — COMMENTED** [review]
🍪 
let's do it

**Comment by markstory** [comment]
@JTCunning Do you want to get this across the line, or should I take it?

**Comment by markstory** [comment]
@JTCunning I've rebased these changes, only one of the calls was still missing a transactionid. Once CI is happy with this I'll get these changes shipped.

**Review by markstory — APPROVED** [review]

**Pull request merged**
