### PR TITLE
build(webpack): Remove `lodash-webpack-plugin`

### PR DESCRIPTION
**Pull request by billyvg**
Undoes the work in introduced in https://github.com/getsentry/sentry/pull/5616. 

This plugin adds around 40-50 seconds to webpack build times and has caused confusion (see https://github.com/getsentry/sentry/pull/13834).

| -- | With Plugin | Without Plugin | Difference | lodash-es | lodash-es + react-mentions |
| -- | ----------- | -------------- | ---------- | --------- | - |
| app.js | 739051 | 739120 | 0% | | |
| app.js.gzip | 184017 | 184040 | 0% | | 186949 |
| vendor.js | 2076311 | 2090876 | +0.7% | 2089352 |
| vendor.js.gizp | 375718 | 380446 | + 1.2% | 380630 | 380476 |
| build time (w/ stats) | 316s | 466s | + 47% | |
| build time (env=prod) | 335s | 198s | n/a | |

Currently, there is no sizable difference between `lodash-es` and `lodash` -- we should revisit this in the future.

### CODE REVIEW

**Review by evanpurkhiser — APPROVED** [review]
Love this

**Comment by scefali** [comment]
@billyvg do we have an ES lint rule to prevent folks from importing the full lodash library?

**Comment by billyvg** [comment]
@scefali ya it's linked https://github.com/getsentry/eslint-config-sentry/pull/46

**Review by scefali — APPROVED** [review]

**Review by dashed — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
