### PR TITLE
remove small screen zoom because it was breaking captcha on mobile

### LINKED ISSUE #2875: Captcha on Sign-In Broken on Phones
Users who are shown the captcha on sign-in report issues with it working on mobile view.

### PR DESCRIPTION
**Pull request by macqueen**
fixes #2875 

@getsentry/ui

### CODE REVIEW

**Comment by mattrobenolt** [comment]
@macqueen Do we not need that for other pages? Or are we trying to just remove the zoom from the login page?

tbh I barely have any idea what this is doing, just making sure you're intending for it to be applied to every page.

**Comment by macqueen** [comment]
@mattrobenolt i figured @ckj could comment on how important the zoom is. my thought was that it doesn't change that much and could be breaking other things, so might as well get rid of it. but yes, if we have a reason to keep it, just removing zoom for login page is an option.

**Comment by ckj** [comment]
@macqueen Nice catch! How about we just remove zoom from auth pages? I think there's an `.auth` body class we can hook on to in `layout.less`.

We're kind of relying on the zoom stuff to get things to fit better on smaller screens. I think eventually we'll remove it in favor of another approach, but that's further down the road.

**Comment by ckj** [comment]
Sorry didn't see this notification. Looks great, +1.

**Pull request merged**
