### PR TITLE
feat(platforms): Add serverless to the list

### PR DESCRIPTION
**Pull request by evanpurkhiser**
Adds a new category to the platform picker

image

### CODE REVIEW

**Review by leedongwei — APPROVED** [review]
There's a spelling mistake in the PR title

**Review by ajjindal — APPROVED** [review]
lgtm

**Comment by ajjindal** [comment]
@EvanPurkhiser changes look good to me. Looks like there are a few conflicts though.

**Review by priscilawebdev — DISMISSED** [review]

**Comment by priscilawebdev** [comment]
Could you please check the screenshots? this one doesn't looks good:

image

**Comment by EvanPurkhiser** [comment]
Good catch @priscilawebdev, we'll have to do something about that

**Pull request merged**
