### PR TITLE
Add buildNumber to Event

### LINKED ISSUE #4773: Build Number for Cocoa Events
We currently do not send the build number with our events see:
https://github.com/getsentry/sentry-swift/issues/112

I've added an event property `buildNumber`
https://github.com/getsentry/sentry-swift/pull/113

Talked to @mitsuhiko about it because technically the build belongs to a release but I am not sure how it plays with the current release system.
It would be sufficient if we dynamically create an `event.tag` with `Build:${buildNumber}` to show the user the build.

### PR DESCRIPTION
**Pull request by HazAT**
Fixes #4773

### CODE REVIEW

**Comment by HazAT** [comment]
Should we add the build number also to the version number if we create a release?
https://github.com/getsentry/sentry-swift/issues/112#issuecomment-273550948

e.g.: `1.0 (1337)`

Which should result in separate release versions ...

**Comment by HazAT** [comment]
@dcramer @mattrobenolt @tkaemming https://github.com/getsentry/sentry/issues/4773
Can we merge this or do you have any other suggestions?

**Comment by dcramer** [comment]
My general opinion is we should avoid adding more top level attributes unless they make sense for all platforms. I think this kind of information could be useful, however, and maybe the better approach would be to support a more complex release attribute.

e.g. release=1 or release={'version': 1, 'build': 5}

**Comment by HazAT** [comment]
Ok ... then lets just do this ...
I just send this string from the client ... the server accepts this without any issues:
screenshot 2017-01-25 16 20 34
And we can drop this PR

**Comment by dcramer** [comment]
@HazAT sounds good. If we do indeed decide we want more metadata about a release we can take the approach I mentioned in the future.

**Pull request closed without merging**
