### PR TITLE
fix(codeowners): Transfer reprocessing to native team

### PR DESCRIPTION
**Pull request by untitaker**

### CODE REVIEW

**Review by jjbayer — APPROVED** [review]
Approved, as long as the native team approves.

**Comment by relaxolotl** [comment]
Just leaving a message so it's clear that I'm not deliberately ignoring this: I'm currently a little hesitant to approve of this handover yet as the native team hasn't spent much time at all in reprocessing. It feels too early right now, basically.

I do think this is very useful in at least publicly declaring that there is an intent to hand over this part of sentry to native though. What are everybody's thoughts on potentially sharing ownership of reprocessing and getting them involved in reviews as a preliminary step before fully handing it off to native?

**Comment by untitaker** [comment]
i restored the deleted lines such that both teams get assigned

**Review by relaxolotl — APPROVED** [review]
thanks greatly for the change! approving on the condition that i'd appreciate it if we could double check to make sure that the new rules marks both teams as co-owners as opposed to just applying the rule lowest in the list, e.g. they're not overwriting the ingest rule with the native rule

**Review by billyvg — APPROVED** [review]

**Comment by untitaker** [comment]
> i'd appreciate it if we could double check to make sure that the new rules marks both teams as co-owners as opposed to just applying the rule lowest in the list

I have 60% confidence that both teams will be assigned but I think we can just wait and see once the next PR comes in

**Comment by untitaker** [comment]
No clue how to interpret this, but I tend to lean towards "will assign both" https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-syntax

**Comment by relaxolotl** [comment]
> No clue how to interpret this, but I tend to lean towards "will assign both"

i think the second sentence here is what really gives me pause about this interpretation:
```
# Order is important; the last matching pattern takes the most
# precedence. When someone opens a pull request that only
# modifies JS files, only @js-owner and not the global
# owner(s) will be requested for a review.
```

note that it says the **last** matching pattern and not the most **specific** pattern, but perhaps i'm being too nitpicky about the wording. this shouldn't be too difficult to test, though.

**Pull request merged**
