### PR TITLE
chore(integrations): integration installation metrics

### PR DESCRIPTION
**Pull request by cathteng**
Adds overall integration installation metrics. This will compare how many times people initiate installing an integration vs how many times they actually complete the installation.

The pipeline is initialized
https://github.com/getsentry/sentry/blob/920ca20d7419a66324a85d30195e6f9a2dd573cb/src/sentry/integrations/web/organization_integration_setup.py#L54

And finish_pipeline is the last step
https://github.com/getsentry/sentry/blob/920ca20d7419a66324a85d30195e6f9a2dd573cb/src/sentry/pipeline/base.py#L179-L180

It would be useful to capture more granular metrics (but perhaps not report them as SLOs) for steps in the installation pipeline for each integration where errors can arise.

### CODE REVIEW

**Comment by cathteng** [comment]
i realize this basically tracks how many times people just click "Add Installation" but we don't have a way of knowing whether they actually intended to install for real 🤷‍♀️

**Comment by ameliahsu** [comment]
Is this different from just looking at frontend metrics that we're already logging?

**Comment by cathteng** [comment]
@ameliahsu do frontend metrics capture that the installation was actually installed?

**Comment by ameliahsu** [comment]
@cathteng We log installation start and complete [here](https://github.com/getsentry/sentry/blob/master/static/app/utils/analytics/integrations/index.ts#L99-L100)

**Comment by cathteng** [comment]
to follow up, we need to emit these metrics from the backend because the SLO reporting is done through DD

**Review by Christinarlong — APPROVED** [review]
love observavility <3

**Review by GabeVillalobos — APPROVED** [review]

**Pull request merged**
