### PR TITLE
fix(schemas): Allow anything but \r or \n in logger names 

### PR DESCRIPTION
**Pull request by bretthoerner**
This is a fix for a specific user support ticket. Their logger has a name like `foo.bar.[/api].[web]`.

As @alex-hofsteede pointed out the regex was used before the schema system and so nothing has really changed except that we now show the user an error and so more people are noticing/asking.

I'm putting up a PR because it's easy, but open to discussion here.

There are some options I see:

1. Tell the customer we only want to support more basic logger names, and they need to change them on their end.
2. Continue adding characters like this as users complain.
3. Open up the regex more, like say `[^\r\n]` or something.

As for 1, I'm not sure why we'd care and want to restrict users. But maybe this is an environment name fiasco waiting to happen? Probably @dcramer or someone knows better why the regex was/is the way it was/is.

### CODE REVIEW

**Comment by alex-hofsteede** [comment]
Unless the characters are actually dangerous for some part of the stack, I'd lean towards option 3. As far as I know, the current regex doesn't really prevent people from putting other kinds of meaningless logger names in there anyway, ie it's basically a freeform field.

**Comment by bretthoerner** [comment]
Ya, forgot to say in the original that I am generally +1 on 3 as well.

**Comment by tkaemming** [comment]
Another vote for #3 here, I can't think of anywhere it'd have any adverse consequences but I'm also not confident enough in that since it was sort of a weird choice to begin with to hit approve

**Comment by alex-hofsteede** [comment]
eea5a3e2 is where the sanitizing was added. cc @mattrobenolt

**Review by mattrobenolt — APPROVED** [review]
Yeah, looking at my original PR, I think I erronously applied it to the logger name itself, which is the value of a key. Impressed though that it made it this long before anyone cared.

:cookie:

**Comment by bretthoerner** [comment]
Discussed offline, commenting here just to be clear, Matt is OK with expanding it to be more open.

**Pull request merged**
