### PR TITLE
Adding support for new incident activity item

### PR DESCRIPTION
**Pull request by iProgramStuff**
We now write two activity items when an incident is created. 
They are 1: when the incident started and 2: when the incident was detected.

The backend adds support for this in #19358 and this adds the frontend support.

Before:
Screen Shot 2020-06-18 at 8 00 27 AM

After:
Screen Shot 2020-06-18 at 8 02 23 AM

Looking for some feedback on the copy here from @adhiraj & others.

### CODE REVIEW

**Comment by wedamija** [comment]
Concept looks good to me, I'll wait to merge my pr until this is ready

**Comment by adhiraj** [comment]
How about "Trigger conditions were met" and "Alert was created" (alert name not necessary since it's already there in big letters in the heading)

**Comment by adhiraj** [comment]
Can we also merge the first "alert status changed to X" with "alert was created" as "Alert was created with status X". 3 activities just when an alert start feels like too many since nothing interesting is actually happening

**Comment by iProgramStuff** [comment]
Closing because this was brought into Dan's PR and merged with that instead. #19358

**Pull request closed without merging**
