### PR TITLE
feat(ui): Add release hovercard to recent activity

### PR DESCRIPTION
**Pull request by evanpurkhiser**
screen shot 2018-03-29 at 17 07 36

### CODE REVIEW

**Comment by MaxBittker** [comment]
literally nicer than github's now
image

**Comment by MaxBittker** [comment]
oh wait, `deploys` might need a background color or a stroke so the line doesn't bleed through

**Comment by EvanPurkhiser** [comment]
good catch, that was close, hard to say how many subscribers we could have lost from that one.

**Review by MaxBittker — APPROVED** [review]
this seems good to me! thanks evan.
can't wait to hover.

**Pull request merged**
