### PR TITLE
build(eslint): refactor rules to external package

### PR DESCRIPTION
**Pull request by billyvg**
Refactor rules into [eslint-config-sentry](https://github.com/getsentry/eslint-config-sentry) so that we can re-use rules easily

Required for #6045

### CODE REVIEW

**Comment by getsentry-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Changes to build requirements</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Review by MaxBittker — APPROVED** [review]
really nice to refactor these and get stuff out of the repo! this will work transparently with things like editor plugins, correct?

**Comment by billyvg** [comment]
@MaxBittker yeah, it'll work w/ editor plugins (provided npm dependency is met)

**Comment by jan-auer** [comment]
Ideally, we'd have a package `eslint-config-sentry-base` that only exports `es6` + `base` rules and doesn't require `eslint-plugin-react` as peer dependency. We have a couple of node-based projects, like [github-grooming-bot](https://github.com/getsentry/github-grooming-bot) where this would come in handy. See [airbnb/javascript](https://github.com/airbnb/javascript/tree/master/packages) for reference.

Secondly, shouldn't we also add rules for [eslint-plugin-jsx-a11y](https://github.com/evcohen/eslint-plugin-jsx-a11y)? We can get some inspiration [here](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/rules/react-a11y.js).

**Comment by benvinegar** [comment]
@jan-auer makes some good points about peer dependencies.

What if we used a monorepo for all rules, but published multiple plugins using Lerna?

**Comment by billyvg** [comment]
Yeah I'll do that this weekend

**Pull request merged**
