### PR TITLE
ref(lodash): Only import used lodash functions

### PR DESCRIPTION
**Pull request by lynnagara**
Prevents unused lodash library code from being bundled

### CODE REVIEW

**Comment by billyvg** [comment]
We have a webpack plug-in that takes care of this

**Comment by EvanPurkhiser** [comment]
I'm :+1: on this as long as bundle size isn't largely different in a negative way.

**Comment by billyvg** [comment]
> I'm 👍 on this as long as bundle size isn't largely different in a negative way.

If bundle sizes are comparable, why change what we have? This is more prone to regressions.

If it's a matter of style then we should have an eslint rule attached.

**Comment by EvanPurkhiser** [comment]
Yeah for me it's a matter of style. I agree about an eslint rule.

> This is more prone to regressions

Why do you say this?

**Comment by billyvg** [comment]
> Yeah for me it's a matter of style. I agree about an eslint rule.
> 
> > This is more prone to regressions
> 
> Why do you say this?

Build size regressions, esp with no lint rules because it's easy for someone to import lodash.

**Pull request closed without merging**
