### PR TITLE
bug(replays): Hard-code the statsPeriod for the table on Transactions>Replay tab

### LINKED ISSUE #43342: Replays inaccurate counts
originally reported by jasmin in slack:

Hey team 
I see [this issue is closed](https://github.com/getsentry/sentry/issues/42818). However, I still notice significant discrepancies between Replay Count and number of replay events in the table on the Txn Summary page on pretty much any random transaction group I click. Is there some outstanding work I’m missing? Is this completely unavoidable rn?
Examples:
50+ Count vs. 7 in table --> [https://sentry.io/organizations/sentry/performance/summary/replays/?project=11276[…]&transaction=%2Forganizations%2F%3AorgId%2Fdiscover%2Fresults%2F](https://sentry.io/organizations/sentry/performance/summary/replays/?project=11276&query=transaction.op%3Apageload&statsPeriod=24h&transaction=%2Forganizations%2F%3AorgId%2Fdiscover%2Fresults%2F)
50+ Count vs. 5 in table --> [https://sentry.io/organizations/sentry/performance/summary/replays/?project=11276[…]tion=%2Forganizations%2F%3AorgId%2Fperformance%2F%3AeventSlug%2F](https://sentry.io/organizations/sentry/performance/summary/replays/?project=11276&query=transaction.op%3Apageload&statsPeriod=24h&transaction=%2Forganizations%2F%3AorgId%2Fperformance%2F%3AeventSlug%2F)
50+ Count vs. 0 in the table --> [https://sentry.io/organizations/sentry/performance/summary/replays/?project=11276[…]tatsPeriod=24h&transaction=%2Fonboarding%2F%3AorgId%2F%3Astep%2F](https://sentry.io/organizations/sentry/performance/summary/replays/?project=11276&query=transaction.op%3Apageload&statsPeriod=24h&transaction=%2Fonboarding%2F%3AorgId%2F%3Astep%2F)

### PR DESCRIPTION
**Pull request by ryan953**
Refactor the Transaction Summary> Replay table.

The refactor made it easy to rip out some old 'transaction searching' code, where we got some percentiles, and conditionally loaded tx span data depending on filters that we found in the url. None of that really made sense to be because there weren't any good buttons/dropdowns on the page to change those things. And even if there were: this page is nominally about Replays, not Transaction events; so it doesn't make sense imo to search for transaction events on this page anyway.

Now we've got the multi-layered fetch implemented in, what I think is as straight-forward a way as possible. 
1. We first have to create an EventView using the transaction `<PageLayout>` component, this evenView tells us how to fetch the list of eventIds related to this transaction.
2. Then we can pass that into our hook, which will load event data
3. From the event data we extract a list of replayIds and fetch those
4. Once we have replay records, we combine them with the events from step 2 and can render the table!

Fixes #43342

### CODE REVIEW

**Review by JoshFerge — APPROVED** [review]

**Review by JoshFerge — APPROVED** [review]
should we just disable pagination for now given that its p. broken?

**Comment by ryan953** [comment]
> should we just disable pagination for now given that its p. broken?

@JoshFerge pagination is alive, it works the same as on issues page.

**Comment by JoshFerge** [comment]
> > should we just disable pagination for now given that its p. broken?
> 
> @JoshFerge pagination is alive, it works the same as on issues page.

referring to https://github.com/getsentry/replay-backend/issues/244 and issue ben originally reported

**Comment by ryan953** [comment]
> > > should we just disable pagination for now given that its p. broken?

> > @JoshFerge pagination is alive, it works the same as on issues page.

> referring to https://github.com/getsentry/replay-backend/issues/244 and issue ben originally reported

pagination and sorting is removed/disabled

**Review by JoshFerge — APPROVED** [review]

**Pull request merged**
