### PR TITLE
Error embed style tweaks

### PR DESCRIPTION
**Pull request by ckj**
screen shot 2016-04-20 at 5 32 43 pm

screen shot 2016-04-20 at 5 33 17 pm

### CODE REVIEW

**Comment by ckj** [comment]
oops, cc @getsentry/ui

**Comment by macqueen** [comment]
👍

**Comment by ckj** [comment]
Added the logo:

screen shot 2016-04-20 at 5 56 09 pm

**Comment by benvinegar** [comment]
💯

**Pull request merged**
