### PR TITLE
feat(metrics) Track response codes for integrations

### PR DESCRIPTION
**Pull request by markstory**
By tracking response codes for integrations requests we can narrow pinpoint problematic integration providers and their outages. We'll get a diverse set of host values from on-premise integrations and atlassian cloud as jira-cloud is hostname based.

Refs APP-823

### CODE REVIEW

**Comment by mitsuhiko** [comment]
Would it not make more sense to issue separate metrics per status code?

**Comment by markstory** [comment]
I was hoping to use datadog's ability to easily graph all the tags for a metric to visualize what integrations were doing. If I had separate metrics per status code graphing trickier as I'd have to know all the status codes ahead of time.

**Comment by mitsuhiko** [comment]
It's just inconsistent from how we track the other status codes. That's why i asked.

**Review by lauryndbrown — APPROVED** [review]
Well... I don't see anything wrong with the code. So ... I'm approving it.

**Pull request merged**
