### PR TITLE
fix: Allow empty loggers

### PR DESCRIPTION
**Pull request by alex-hofsteede**

### CODE REVIEW

**Review by mattrobenolt — COMMENTED** [review]
What's the use case for allowing this? I'm guessing we allowed it before, but should we continue allowing it? I assume this isn't very useful in the UI?

**Comment by bretthoerner** [comment]
To me it just seems weird to show the user an error if they send `''` and then set it to the default value, which is `''`.

I don't know the full context for this coming up (it came up for other fields) but seemed like an easy edge case to fix here?

**Review by bretthoerner — APPROVED** [review]

**Comment by alex-hofsteede** [comment]
I think mostly because the default is the empty string, so in some sense the default for a field should match the schema. And it sounds like existing SDK's send it in as the empty string sometimes and we don't want to show validation errors.

I'm not sure why the default is the empty string and not just deleting values when they are bad though, but that's carried over from previous code.

**Comment by mattrobenolt** [comment]
Yeah, I think that's find and agree on this change to make it match existing behavior. Unclear though what this means for UX and it seems like a thing we should just stop allowing in the future?

**Comment by alex-hofsteede** [comment]
Yeah I assume these empty logger strings are also added to search indexes and stuff, which seems not that useful.

**Pull request merged**
