### PR TITLE
style(yaml): Apply prettier to .github/*

### PR DESCRIPTION
**Pull request by evanpurkhiser**
Runs `prettier -w .github/*/**`

### CODE REVIEW

**Review by asottile-sentry — COMMENTED** [review]
this should be automated otherwise it will regress and isn't all that useful

also I notice the freezing tool's output is incompatible with this

**Comment by evanpurkhiser** [comment]
> also I notice the freezing tool's output is incompatible with this

Is that a tool we control?

**Comment by evanpurkhiser** [comment]
> this should be automated otherwise it will regress and isn't all that useful

I agree, it's just annoying for me right now that my editor keeps making these changes haha

**Comment by asottile-sentry** [comment]
> > also I notice the freezing tool's output is incompatible with this
> 
> Is that a tool we control?

yep it lives in `tools`

**Comment by evanpurkhiser** [comment]
Will deal with it later

**Pull request closed without merging**
