### PR TITLE
feat(event-search): Added a test to show sorting aggregates work.

### PR DESCRIPTION
**Pull request by lauryndbrown**

### CODE REVIEW

**Comment by lauryndbrown** [comment]
Just double checking that no weirdness happens when sorting via aggregates. Let me know @lynnagara if you wanted me to focus on returning the whole table from the api endpoint sorted or if you were working on it. I assumed you were focusing on the csp/errors view and had that covered. Let me know if not.

**Comment by lauryndbrown** [comment]
Hmm noticed https://github.com/getsentry/sentry/pull/13453. I can hold off on any further building of thing here until that lands.

**Comment by lynnagara** [comment]
Yeah, Mark suggested removing the aggregates option from the client to simplify the API a bit and only support a small list of predefined aggregates, which I think might be a better way to go

**Comment by lauryndbrown** [comment]
No problem. I'll close this pr for now. :)

**Pull request closed without merging**
