### PR TITLE
feat(stream): Expose merge as top level action

### PR DESCRIPTION
**Pull request by dcramer**

### CODE REVIEW

**Comment by dcramer** [comment]
screen shot 2018-03-06 at 3 01 35 pm

**Review by billyvg — APPROVED** [review]
Looks out of place w/o an icon

**Comment by dcramer** [comment]
@billyvg agreed -- probably a good follow up after 9 gets out the door

**Comment by ckj** [comment]
Cool. I have an idea for a simple merge icon. I'll follow up with it in its own PR.

**Review by ckj — APPROVED** [review]
LGTM

**Pull request merged**
