### PR TITLE
feat(readme): Adding Logo

### PR DESCRIPTION
**Pull request by ehfeng**
I saw Bootstrap's [README](https://github.com/twbs/bootstrap), thought it looked nice. Thoughts?

[See here](https://github.com/getsentry/sentry/tree/pretty-readme) for preview.

### CODE REVIEW

**Comment by MaxBittker** [comment]
would be nice if the screenshots were all the same height

**Comment by MaxBittker** [comment]
imo this is improvement, but it's also a good opportunity to remove "Sentry is a server"

**Comment by ehfeng** [comment]
@MaxBittker took a stab.

**Comment by MaxBittker** [comment]
my subjective nits are drop the whats sentry heading all together, and/or use this as the first sentence:
Sentry is an application that helps you monitor and fix crashes in real time.

**Comment by ehfeng** [comment]
I see where you're coming from—it's an odd structure for the README. I
don't like "...is an *application*", as I'd prefer "tool", but also, that's
a nit.

I'm going to wait on @cameronmcfee or @rsomething to chime in here for
language/copy. My main opinions are adding the centered logo and the
screenshots in the README, which feels better to me.

**Review by ckj — APPROVED** [review]
👍

**Pull request merged**
