### PR TITLE
Add sentry-android to the Official Sentry SDKs

### PR DESCRIPTION
**Pull request by marandaneto**

### CODE REVIEW

**Review by matejminar — APPROVED** [review]

**Comment by srinu91** [comment]
hji amna

**Comment by srinu91** [comment]
hsdjhdsghfjkdghf

**Review by bruno-garcia — APPROVED** [review]
👍 keeping in mind we'll be moving that codebase into the sentry-java repository eventually

**Comment by bruno-garcia** [comment]
Closing because we merged repos

**Comment by BYK** [comment]
Closed as the repos are now merged.

**Pull request closed without merging**
