### PR TITLE
ref(js): Remove unused constant

### PR DESCRIPTION
**Pull request by evanpurkhiser**

### CODE REVIEW

**Review by davidenwang — APPROVED** [review]
good stuff

**Review by priscilawebdev — APPROVED** [review]
I think you will have to merge master for the error goes away..but it looks good

**Review by dashed — CHANGES_REQUESTED** [review]
This is used tho 🤔

**Comment by mrbaguvix** [comment]
@EvanPurkhiser checks don't pass.

**Comment by EvanPurkhiser** [comment]
Nah I removed it, just need to rebase

**Review by dashed — APPROVED** [review]

**Pull request merged**
