### PR TITLE
frontend(gravatar): use sha256 instead of md5

### PR DESCRIPTION
**Pull request by mdtro**
Gravatar supports profile and image lookups via sha256. MD5 shows up as a security finding in most scanning tools. This will remove one less finding.

### CODE REVIEW

**Review by billyvg — APPROVED** [review]

**Review by scttcper — APPROVED** [review]
this looks good, but it makes me think we could use the browser built in one and toss crypto-js - see example https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest#basic_example

it is only available in https, but i think we've got a few dependencies on https now

**Comment by markstory** [comment]
> it is only available in https, but i think we've got a few dependencies on https now

Does self-hosted default to HTTPs?

**Comment by scttcper** [comment]
@markstory 🤷 but i think they'd have a bad experience with any of our click to copy buttons as well

**Comment by scttcper** [comment]
Maybe non-https people don't get gravatar

**Comment by markstory** [comment]
> Maybe non-https people don't get gravatar, not a huge loss

That's fair. I would hope most self-hosters are able to get SSL wired up.

**Comment by aldy505** [comment]
> > it is only available in https, but i think we've got a few dependencies on https now
> 
> 
> 
> Does self-hosted default to HTTPs?

@markstory Nope. But at least it's documented here https://develop.sentry.dev/self-hosted/reverse-proxy

The recommended setup for self-hosted would be a terminated TLS in front of the whole self-hosted compose project. So I don't think there's a possible way to check whether we're HTTPS or not.

**Review by oioki — APPROVED** [review]

**Comment by mdtro** [comment]
I've opted to merge this as is for now to move away from MD5. I'll add removing crypto-js to the backlog for now.

**Pull request merged**
