### PR TITLE
ref: Delete unused styles from less files

### PR DESCRIPTION
**Pull request by lynnagara**
I'm 85% sure all of this isn't used. Let's see what Percy says.

### CODE REVIEW

**Review by markstory — COMMENTED** [review]
:clap: You might want to double check the dropdown in onboarding, I don't think percy goes there.

**Comment by lynnagara** [comment]
@markstory I checked the onboarding flow and I don't think there's a dropdown in there anymore (except the above mentioned new project flow ones) hence the deleted `.dropdown-menu` styles. It seems to have been part of this originally https://github.com/getsentry/sentry/commit/19a69045d16b1e6d77d679c4c11ec3019595cee7#diff-235c79450faf1117e0db7e2595961538R59

**Comment by lynnagara** [comment]
Double checked the removed styles, and Percy doesn't report any unexpected diffs. I think this is pretty safe.

**Comment by billyvg** [comment]
Have you grepped `getsentry` as well?

**Comment by lynnagara** [comment]
@billyvg I just double checked getsentry - I think the blankslate icon might be used so I added it back

**Comment by lynnagara** [comment]
@billyvg @markstory Can we merge this?

**Review by billyvg — APPROVED** [review]

**Pull request merged**
