### PR TITLE
feat(2fa): Added a resend code link to sms 2fa page

### PR DESCRIPTION
**Pull request by lauryndbrown**
Add a link to the sms two-factor authentication page to resend code for the case the user does not have their phone immediately handy before the time limit is up.

### CODE REVIEW

**Comment by lauryndbrown** [comment]
screen shot 2018-01-05 at 5 17 48 pm

**Comment by benvinegar** [comment]
Is there a way to do this without inline JavaScript? Like, could we just link to `href=""` (I can't remember if that works or not) or even do a `<form>` post?

Reason I ask is that, for security reasons (see: CSP), we may come back and eliminate all inline JavaScript code.

**Comment by mattrobenolt** [comment]
Oh. Derp. Not sure why I didn’t think of that. Yeah, we can just use a link to “” should be fine to trigger a refresh.

**Comment by lauryndbrown** [comment]
@mattrobenolt and @benvinegar so my concern with href="" is that it will resort to cached information from the browser and not generate a new code. Is there a way to do that without letting it used saved data?

**Comment by mattrobenolt** [comment]
I don’t think our cache-control headers would allow that to actually happen. If we think this might actually happen for some reason, we could easily just use a cache busting token. Like, append a random querystring value.

**Comment by lauryndbrown** [comment]
Ah! Ok. Gotcha. Sounds like this will work just fine then.

**Comment by benvinegar** [comment]
Aside: just GET-ing a page triggers an SMS?

**Comment by mattrobenolt** [comment]
Yeah, when this page is loaded, we send the SMS. This is current behavior, but we can address changing it somehow later if we want.

**Comment by benvinegar** [comment]
Let's address afterwards. I'd expect a `<form>` POST to trigger the SMS followed by a redirect to this view (so people can't accidentally refresh). Clicking "resend" should initiate the POST/redirect flow again.

**Comment by lauryndbrown** [comment]
@mattrobenolt is this ok to merge or are there more changes needed?

**Review by mattrobenolt — APPROVED** [review]
:tada:

**Pull request merged**
