### PR TITLE
fix(integrations) Ensure group links are created on pull request update

### PR DESCRIPTION
**Pull request by markstory**
Previously group links were not created when pull requests were updated. This meant that you had to get it right the first time and any updates made to a pull requests' description/title would not reset group links.

I've reorganized GitHub & GitHub Enterprise payload fixtures around so they are less confusing and closer to the code they are for.

Fixes APP-671

### CODE REVIEW

**Comment by lauryndbrown** [comment]
Looks like the tests are missing the file you removed.

**Comment by markstory** [comment]
Stale pyc files burn me once again :cry:

**Comment by lauryndbrown** [comment]
Are commits similar in any way? I can understand though why PR's would be particularly vulnerable. Just curious. I doubt people edit commits that much.

**Review by lauryndbrown — APPROVED** [review]
Mark it looks good. This is a good catch. Not sure what's happening with the tests though.

**Comment by markstory** [comment]
We don't modify Commit objects in either of GitHub or GitLab so update() sneaking by the post_save signal is not a problem.

**Pull request merged**
