### PR TITLE
feat(onboarding): Add auto/manual switch to Android docs

### LINKED ISSUE #51792: Android Project Creation Enhancements
### Background
The onboarding during project creation today is not a dynamic experience which is easy for a user to best understand what options they have to integrate Sentry into their Android application. Considering which major product features they may want to turn on (Performance and/or Profiling) and which tools associated with their development lifecycle they can use to best integrate Sentry. (Gradle, Kotlin, ProGuard & DexGuard). To in the end have their Android application setup to be able to send errors, performance, profiles, and other contextual data around their application with each new build and release (source context) to provide readable stack traces which can be linked to their source code.

### Proposal
There is an initiative to continue work in moving onbaording which re-uses our sentry-docs to the sentry repo in React code. There we can provide customer with a more custom experience, with toggles and other UI features to reduce clutter and make the experience adapt to the users needs.

- toggles for performance and profiling
- radials for different build tool plugins

**Related:**

https://github.com/getsentry/sentry/issues/48144

### PR DESCRIPTION
**Pull request by romtsn**
Closes #51792
Adds a switch to change between Auto and Manual installation steps (Manual is still relevant for Windows users)

## Manual

image

## Auto

image

### CODE REVIEW

**Review by ArthurKnaus — APPROVED** [review]
Looks good 👍 
One questions:
Shouldn't we tell the user somewhere that they have to use the manual method on Windows?
E.g. use the OS name for the toggle instead of Auto / Manual
wdyt?

**Comment by HazAT** [comment]
@ArthurKnaus I think the user can decide.
We could auto-switch if we are on windows, that would be cool.

```javascript
let userAgent = window.navigator.userAgent;
if (userAgent.indexOf("Win") != -1) os = "Windows";
```

**Comment by romtsn** [comment]
@ArthurKnaus yep, I thought about the same, but Mac users can still prefer the manual mode, so if we rename the labels it wouldn't be as clear.

I did what Daniel suggested - basically switching to the Manual mode by default if we detected Windows in https://github.com/getsentry/sentry/pull/57155/commits/45a3516ae41c2307d7f7371bdefea6c6a7a8e3b2, let me know if that makes sense. Thanks

**Comment by ArthurKnaus** [comment]
@romtsn LGTM 👍

**Pull request merged**
