### PR TITLE
Everybody Loves Rust

### PR DESCRIPTION
**Pull request by smeubank**
It's never good to argue with a rust developer

### CODE REVIEW

**Review by iambriccardo — APPROVED** [review]
Ship it 🚢

**Review by vgrozdanic — APPROVED** [review]
Why not.

**Comment by TheBoatyMcBoatFace** [comment]
The Rustaceans thank you 🦀 ❤️

**Comment by kraemahz** [comment]
It's not in alphabetical order 😢

**Review by priscilawebdev — APPROVED** [review]

**Comment by TheBoatyMcBoatFace** [comment]
No merge???? I spun up a new project the other day and, alas, rust hate is running strong at sentry.

**Pull request closed without merging**
