### PR TITLE
fix: Handle tagstore model moves in buffer processing

### PR DESCRIPTION
**Pull request by bretthoerner**
Longer term this will be part of a 'registry' system but this will
prevent short term bugs.

### CODE REVIEW

**Review by mattrobenolt — CHANGES_REQUESTED** [review]
I'd say attempt the import first, catch `ImportError`, then lookup in `MODEL_MOVES`.

So like:

```python
try:
    model = import_string(values['m'])
except ImportError:
    try:
        model_name = MODEL_MOVES[values['m']]
    except KeyError:
        raise ImportError(values['m'])
    model = import_string(model_name)
```

Then our hot path doesn't even have to touch MODEL_MOVES.

**Comment by bretthoerner** [comment]
Actually, moving this into `imports.py`, sec.

**Review by mattrobenolt — APPROVED** [review]
:thinking: ok, this is better.

**Comment by bretthoerner** [comment]
I moved it up the stack where I think it belongs.

I can do the `try/except` thing but er, isn't ever field access in Python a dict lookup? Is this really a performance thing at all?

**Pull request merged**
