### PR TITLE
feat(apis): Track API owners

### PR DESCRIPTION
**Pull request by sentaur-athena**
Adding a field to Endpoint class to track the engineering team owning it. Also creating experimental folder to keep track of what endpoints are not documented but will be soon. Will add one for private too but didn't have a good example now.

### CODE REVIEW

**Comment by sentaur-athena** [comment]
@leedongwei I didn't change the API route as we discussed because I noticed we have all these nice test utils for api/0/ routes that then I have to rewrite. This is good enough to build both
1. Lint rule to make people add owner
2. Bot to track what teams have many experimental APIs
Let me know what you think. I'll do the same for getsentry

**Review by JoshFerge — COMMENTED** [review]
makes sense to me. a few thoughts:

- how will this play with CODEOWNERS?
- what did we end up deciding to do with "UI endpoints", i.e. endpoints that are used in the UI, and IMO don't make sense to make publically available? 

> Also creating experimental folder to keep track of what endpoints are not documented but will be soon

will this be in this PR, or is this a separate effort?

**Comment by sentaur-athena** [comment]
@JoshFerge 

> how will this play with CODEOWNERS?

I didn't use it because it doesn't seem maintained at all. It only includes a few endpoints. But definitely a good point not to introduce new owners set. Do you have any thoughts on enforcing update to code owners automatically? I can look into it.

> what did we end up deciding to do with "UI endpoints", i.e. endpoints that are used in the UI, and IMO don't make sense to make publically available?

Creating private folder is about that. So basically api/endpoints/private/enterprise/SomeEndPointOwnedByEnterpriseThatIsUsedByUI.py


> will this be in this PR, or is this a separate effort?

In this PR I moved an experimental endpoint enterprise has as an example. I don't plan to fix all the existing ones myself but the goal is to build something that moving forward we know how to track them. Eventually we can do an audit. I was thinking moving everything to experimental for the team that owns it for example and nudge all teams periodically (with a bot or something) that they have too many experimentals. They have to move either to private or publish.

**Comment by JoshFerge** [comment]
> I didn't use it because it doesn't seem maintained at all. It only includes a few endpoints. But definitely a good point not to introduce new owners set. Do you have any thoughts on enforcing update to code owners automatically? I can look into it.

It's definitely maintained, just the vast majority of endpoints are unowned. Yes, we already did this when I was on the team. `owners-api` will fallback for all new endpoints created, and when I was managing, I would request changes on all new endpoints to have codeowners. to properly enforce, we should organize our endpoints into folders.

>Creating private folder is about that. So basically api/endpoints/private/enterprise/SomeEndPointOwnedByEnterpriseThatIsUsedByUI.py

why do that instead of a property on the endpoint? seems like it would make finding what you need harder by having it in the folder structure.


> In this PR I moved an experimental endpoint enterprise has as an example. I don't plan to fix all the existing ones myself but the goal is to build something that moving forward we know how to track them. Eventually we can do an audit.

Did you see https://docs.google.com/spreadsheets/d/11afZ8Ve7isA53GxN__hKWBILCWa_LvzVbd9RoDlDKko/edit#gid=0 ?

**Comment by sentaur-athena** [comment]
I'm writing down more options to see which one is more feasible. For now I'll hold on merging this.

**Comment by sentaur-athena** [comment]
@JoshFerge how did you generate  https://docs.google.com/spreadsheets/d/11afZ8Ve7isA53GxN__hKWBILCWa_LvzVbd9RoDlDKko/edit#gid=0 ?

**Comment by JoshFerge** [comment]
https://github.com/getsentry/sentry/pull/51104/files Similar to this PR, but i looked at the file that each endpoint class was in, and used something like https://github.com/sbdchd/codeowners to print the codeowner for each endpoint into a CSV. I then marked which ones were public, not public, and pulled data from bigquery to join in to look at usage.

**Comment by sentaur-athena** [comment]
closing in favor of https://github.com/getsentry/sentry/pull/54876

**Pull request closed without merging**
