### PR TITLE
Improve new stack rendering

### PR DESCRIPTION
**Pull request by dcramer**
- Add lineno back to 'title'
- Darken borders on cells
- Collapse trailing whitespace in Template/Stacktrace interfaces

/cc @getsentry/ui

### CODE REVIEW

**Comment by dcramer** [comment]
screenshot 2016-06-17 14 52 27

**Comment by dcramer** [comment]
screenshot 2016-06-17 15 05 59

**Comment by dcramer** [comment]
screenshot 2016-06-17 15 07 49

**Comment by benvinegar** [comment]
> Collapse trailing whitespace in Template/Stacktrace interfaces

Sweet.

**Pull request merged**
