### PR TITLE
Make breadcrumb UI way smaller

### PR DESCRIPTION
**Pull request by ckj**
#### Condenses this:

screen shot 2016-04-11 at 4 19 28 pm
#### Into this:

screen shot 2016-04-11 at 5 02 07 pm

cc @getsentry/ui

### CODE REVIEW

**Comment by ckj** [comment]
Doh, just found the `hideIfEmpty` prop. Gonna use this instead of the ternary stuff.

**Comment by mitsuhiko** [comment]
Not a huge fan that POST or the UI event type moved away from the table. Maybe for the HTTP request the table could go and instead of url = X it shuold show `POST http://URL/here`?

The "Click" thing might look less confusing if it was "Click UI Event" or something.

**Comment by ckj** [comment]
> Maybe for the HTTP request the table could go and instead of url = X it shuold show POST http://URL/here?

Yeah, I think that's a great idea. Same could be done with the UI stuff, too. Let me give it a try.

**Comment by dcramer** [comment]
I think we need to push left those aligned nodes too. No reason to try and horizontally align things when we can do grids based on event type

**Comment by ckj** [comment]
> I think we need to push left those aligned nodes too. No reason to try and horizontally align things when we can do grids based on event type

@dcramer care to clarify? what needs pushed left?

**Comment by dcramer** [comment]
@ckj each individual crumb has huge whitespace between the key/value. We can make that whitespace per crumb, so its less wasted. You dont really need to horizontally scan them all the same way as they are different data anyways. This means that we could have multiple columns in some situations without sacrificing it in others (e.g. where URL is a longer field).

**Comment by ckj** [comment]
@dcramer Gotcha. I width:auto'd these cells and I dunno, my brain def prefers/expects these to be lined up:

screen shot 2016-04-11 at 4 47 06 pm

Thoughts? Maybe we manually set these at a smaller max-width since the key strings are all typically not that long?

**Comment by dcramer** [comment]
:+1: on the change in general. I think we can toy with having grid based elements per-crumb type later. My main concern right now is the large gap between label/content to ensure they can line up

**Comment by ckj** [comment]
Yeah, I feel you. I played with a few layout variants, but they weren't really helping condense the footprint which was the main goal of this PR. For now I reduced the width of the key column so that there's less whitespace until we can find a better solution. 

I updated the after screenshot in the original comment to reflect all the new changes based on the feedback here. Will :ship: shortly.

**Pull request merged**
