### PR TITLE
ref: upgrade boto* packages to fix conflicts

### PR DESCRIPTION
**Pull request by asottile-sentry**
while attempting to upgrade `selenium` the first issue hit is a conflict between botocore<->urllib3<->selenium

### CODE REVIEW

**Review by joshuarli — COMMENTED** [review]
For urllib3 1.26 which is needed for selenium 4 and would be nice in general, see [here](https://github.com/getsentry/sentry/pull/30824#issue-1087121659) and [here](https://github.com/getsentry/sentry/pull/30824#issuecomment-1063270760) for some prior writing.

As for testing boto upgrades, it unfortunately currently involves a manual process that @getsentry/ecosystem should know how to do: https://github.com/getsentry/sentry/pull/28693

I wouldn't worry about going through the pain of testing avatar uploading, it's more than likely it will just work and it's very minor breakage if it does.

**Comment by AniketDas-Tekky** [comment]
@asottile-sentry Do you know why ecosystem was tagged in this PR?

**Comment by asottile-sentry** [comment]
> @asottile-sentry Do you know why ecosystem was tagged in this PR?

yep!  I believe that's due to ownership of sqs and lambda integrations -- see https://github.com/getsentry/sentry/pull/28693

**Comment by leeandher** [comment]
Sorry for the wait, testing AWS locally is a bit of a pain. Was able to validate the branch locally, looks good from the SQS and Lambda side of things.

**Review by leeandher — APPROVED** [review]

**Pull request merged**
