### PR TITLE
feat(saved-search): Move components around per the new design

### PR DESCRIPTION
**Pull request by lynnagara**
Also removes some css/bootstrap usage and replaces with styled
components.

### CODE REVIEW

**Review by billyvg — COMMENTED** [review]
We should add a snapshot with `org-saved-searches` and `recent-searches` enabled. Search bar also seems a bit too small

**Comment by Chrissy** [comment]
just a heads up it looks like these structural changes will also affect users without the feature flag. This isn't a big deal until it gets to the helper menu thingy:

image
you can also see it in the percy snapshots.

**Review by Chrissy — CHANGES_REQUESTED** [review]
we should increase the width of the search box for users who don't have the feature flag (or maybe both?) before we release this.

**Comment by lynnagara** [comment]
Yeah, just saw that in the Percy diff, will try to find a solution

**Comment by lynnagara** [comment]
@Chrissy Can you take another look?

**Review by Chrissy — APPROVED** [review]

**Pull request merged**
