### PR TITLE
ref(ui): Widen breadcrumbs category by 12px to support event.transaction

### PR DESCRIPTION
**Pull request by kamilogorek**
Related SDK change: https://github.com/getsentry/sentry-javascript/pull/2450

Before:
image

After:
image

### CODE REVIEW

**Review by matejminar — APPROVED** [review]
Looks good to me 👍

**Review by HazAT — DISMISSED** [review]
This is probably not related here (or it might be)
But can we change the red warning sign to something less aggressive for transactions?
I feel like this should be shown like this, a transaction is never an error.

**Comment by matejminar** [comment]
Would you be OK with using one of these?
image

Or should we design a new one specific for transactions?

**Comment by HazAT** [comment]
Hmm not sure if we need a new icon but this one maybe?
image

**Review by matejminar — APPROVED** [review]

**Pull request merged**
