### PR TITLE
chore: upgrade+pin pip in ci, disable pep517 where applicable

### PR DESCRIPTION
**Pull request by joshuarli**

### CODE REVIEW

**Review by dashed — APPROVED** [review]
I'm not familiar with the implications of the `--disable-pip-version-check` flag.

But overall it looks good to me 👍

**Comment by joshuarli** [comment]
> Don't periodically check PyPI to determine whether a new version of pip is available for download.

It's just an annoyance (and without it, makes things marginally faster), we're aware of new pip versions and what we're pinned to.

**Comment by joshuarli** [comment]
Mmm. Well, I lied a bit. Looks like we still use pip 9 in CI.

**Comment by dashed** [comment]
Ah interesting.

Yea I saw the travis lint failure.

**Comment by joshuarli** [comment]
Bumping pip in CI necessitates broadening the scope of the pr - see title change.

**Review by mattrobenolt — APPROVED** [review]

**Pull request merged**
