### PR TITLE
webpack should not fail with 0 retcode

### PR DESCRIPTION
**Pull request by barbuza**

### CODE REVIEW

**Comment by dcramer** [comment]
@barbuza we specify --bail in all invocations at the moment -- were you seeing somewhere this isn't true?

(I'm not opposed to changing the default though I'm not sure how that translates with --watch)

**Comment by barbuza** [comment]
**Makefile**

```
build-js-po:
	mkdir -p build
	SENTRY_EXTRACT_TRANSLATIONS=1 ./node_modules/.bin/webpack
```

```
test-js:
	@echo "--> Running JavaScript tests"
	@${NPM_ROOT}/.bin/webpack
	@npm run test
	@echo ""
```

**Comment by dcramer** [comment]
@benvinegar will leave this to you -- as long as this doesnt break --watch I think it's sane (and then we can kill --bail in setup.py and ``SENTRY_WATCHERS``)

**Comment by benvinegar** [comment]
I added `bail: true`, and while webpack does bail at the first error it encounters, the status code is still 0.

@barbuza – did you have different results?

**Comment by benvinegar** [comment]
The issue here is that webpack 1.x doesn't return 0 on failure period ... and this looks to be fixed in 2.0, according to a bunch of comments I've read:

https://github.com/gatsbyjs/gatsby/issues/58

**Comment by dcramer** [comment]
i believe webpack --bail returns the exit code? i swear we tested and that was true

**Comment by benvinegar** [comment]
Weird, okay, now it works fine for me ... or I was doing it wrong before.

Personally, I think this should be specified on the command line anyways, not fixed in the config. If I'm doing development, I don't want it to bail on the first error – I want it to report all errors.

I'm going to propose closing and just fixing the missing `--bail` from the Makefile.

@dcramer – cool?

**Comment by dcramer** [comment]
no objections from me, as long as sdist/etc dont quietly build on failures

**Comment by mattrobenolt** [comment]
Is there anything for us to do here? I could have sworn if webpack failed in any of our build stuff, it errored.

**Comment by dcramer** [comment]
--bail deals with this as does new webpack versions

**Pull request closed without merging**
