### PR TITLE
Capture Exception ID for Last Event

### PR DESCRIPTION
**Pull request by BenLiyanage**
I'm looking to capture and store the last exception id for the event fired so I can associate it with some internal logging that we do.  In this PR I am attempting to do that.

FYI--the contributing page link is broken so I'm not sure how I'm supposed to do this.

### CODE REVIEW

**Comment by mattrobenolt** [comment]
@BenLiyanage What are you trying to accomplish here? I feel like we should do this over in `raven-python` instead since most of our behavior just derives from that.

It seems that we only support `last_event_id` for Flask at the moment. We extend from the `DjangoClient`, so in theory, we could just add support there most likely, then we'd magically get it here.

> FYI--the contributing page link is broken so I'm not sure how I'm supposed to do this.

Which link is broken? I'll fix it up.

**Comment by dcramer** [comment]
Sorry meant to comment. This was submitted based on a support convo, just incorrectly to the wrong repo. We want to provide this functionality in raven-python, we just dont yet today.

**Comment by mattrobenolt** [comment]
Link fixed. :)

**Comment by BenLiyanage** [comment]
@mattrobenolt is that a different repo?  Or a differnt part of the code base?  BTW I saw your talk the other day at yelp--it was pretty informative.  It inspired me to get our app error logging more tightly bound here...

**Comment by mattrobenolt** [comment]
@BenLiyanage Yeah, in this case, it was in the same repo, it was just our `CONTRIBUTING.md`.

**Comment by dcramer** [comment]
https://github.com/getsentry/raven-python/pull/914

**Pull request closed without merging**
