### PR TITLE
feat(onboarding): Remove release commits broadcast modal

### PR DESCRIPTION
**Pull request by lynnagara**
This is no longer a new feature, nor does it make sense to display as
the first thing a new user sees in Sentry

### CODE REVIEW

**Review by billyvg — COMMENTED** [review]
Would it make more sense to keep BroadcastModal around for future broadcasts and just remove the Releases announcement?

**Comment by lynnagara** [comment]
In general I think we should avoid keeping around code that isn't being used, and there is no current plan to replace this. I don't think this piece of code is particularly hard to recreate / we have git history for that, and the added complexity of keeping this around > the cost of potentially recreating it.

**Review by billyvg — APPROVED** [review]
Can we confirm that this is good to remove (and that we don't have any upcoming features we want to announce through this UI) /cc @eurica @benvinegar @saragilford

**Comment by lynnagara** [comment]
@eurica I believe it's shown once to new users upon account creation

**Comment by eurica** [comment]
Well let's get rid of the message for sure.

Sounds like it triggers if you sent your first event more than 2 days ago -- does that codepath sounds useful to us @adhiraj ?

**Comment by adhiraj** [comment]
@eurica that path is easy to recreate. @lynnagara do you wanna remove the styles too?

**Comment by lynnagara** [comment]
Good point, and the gif can go as well I guess

**Review by billyvg — APPROVED** [review]

**Pull request merged**
