### PR TITLE
Delete Sentry

### PR DESCRIPTION
**Pull request by silent1mezzo**

### CODE REVIEW

**Comment by leedongwei** [comment]
Wow. You nearly deleted the entire company @silent1mezzo 

Good save.

**Comment by maxiuyuan** [comment]
🥳

**Review by scefali — COMMENTED** [review]
LGTM...oh wait ;)

**Comment by silent1mezzo** [comment]
Sigh...Sorry ya'll

**Comment by JTCunning** [comment]
When will this feature be implemented?

**Comment by wedamija** [comment]
Good job, all bugs confirmed fixed

**Comment by evanh** [comment]
Congrats on getting Sentry to be 100% typed!

**Comment by armenzg** [comment]
image

**Comment by dashed** [comment]
This change makes Sentry run blazingly fast.

**Comment by lucas-zimerman** [comment]
Too bad, silent1mezzo almost got the chance of being the Top 1 Contributors, ordering by Deletions.

**Pull request closed without merging**
