### PR TITLE
refs(alert_rules): Stop writing to unused incident fields. Modify data model to prepare for removing unused fields

### PR DESCRIPTION
**Pull request by wedamija**
This refactors the `Incident` model to make `aggregation` and `query` nullable, removes the `groups`
relations and disables the constraints on `IncidentGroup`. We don't use any of these fields any
more, so may as well remove.

We also make `alert_rule` not null, since we will always have an alert rule available now. The data
migration will remove any incidents without alert rules - these are all test rows and are fine to
remove.

All tables involved are small, and so it's fine to do these operations as part of the migration.

Depends on https://github.com/getsentry/sentry/pull/18847

### CODE REVIEW

**Comment by markstory** [comment]
> This refactors the Incident model to make aggregation and query nullable, removes the groups

Will incidents be dropping their query text and aggregation in the future? It seems like that information would be redundant as incidents have alert rules too.

**Comment by wedamija** [comment]
Forgot to include ddl:
```
--
-- MIGRATION NOW PERFORMS OPERATION THAT CANNOT BE WRITTEN AS SQL:
-- Raw Python operation
--
--
-- Remove field groups from incident
--
--
-- Alter field aggregation on incident
--
ALTER TABLE "sentry_incident" ALTER COLUMN "aggregation" DROP NOT NULL;
--
-- Alter field alert_rule on incident
--
SET CONSTRAINTS "sentry_incident_alert_rule_id_2f44ba42_fk_sentry_alertrule_id" IMMEDIATE; ALTER TABLE "sentry_incident" DROP CONSTRAINT "sentry_incident_alert_rule_id_2f44ba42_fk_sentry_alertrule_id";
ALTER TABLE "sentry_incident" ALTER COLUMN "alert_rule_id" SET NOT NULL;
ALTER TABLE "sentry_incident" ADD CONSTRAINT "sentry_incident_alert_rule_id_2f44ba42_fk_sentry_alertrule_id" FOREIGN KEY ("alert_rule_id") REFERENCES "sentry_alertrule" ("id") DEFERRABLE INITIALLY DEFERRED;
--
-- Alter field query on incident
--
ALTER TABLE "sentry_incident" ALTER COLUMN "query" DROP NOT NULL;
--
-- Alter field incident on incidentgroup
--
```

**Comment by wedamija** [comment]
> > This refactors the Incident model to make aggregation and query nullable, removes the groups
> 
> Will incidents be dropping their query text and aggregation in the future? It seems like that information would be redundant as incidents have alert rules too.

@markstory yeah, those will be removed. Making them nullable is the first step so that we can remove them.

**Review by markstory — APPROVED** [review]
Migration looks good to me. The tables involved are all small ones.

**Review by evanpurkhiser — APPROVED** [review]
lots of good cleanup here

**Pull request merged**
