### PR TITLE
Update email templates to support event type display.

### LINKED ISSUE #3600: Rendered digest email message body contains unformatted group title.
The [email body is rendered using `Group.message_short`](https://github.com/getsentry/sentry/blob/2b4bab5fa2bee5d918f12df2ec0f3cc6d3664c1a/src/sentry/templates/sentry/emails/digests/body.html#L36) which [does not fall back to a formatted message](https://github.com/getsentry/sentry/blob/2b4bab5fa2bee5d918f12df2ec0f3cc6d3664c1a/src/sentry/models/group.py#L391) like [`Event.message_short` does](https://github.com/getsentry/sentry/blob/2b4bab5fa2bee5d918f12df2ec0f3cc6d3664c1a/src/sentry/models/event.py#L107), which results in the message being rendered with placeholders intact, like so:
screenshot 2016-06-27 15 41 01

This references GH-3456 which is related to this issue (but didn't introduce it.)

### PR DESCRIPTION
**Pull request by tkaemming**
This causes the digest templates to render differently based on the `group.data.type` attribute.

This fixes GH-3600, where group titles were rendering with unformatted messages, as well as brings the row for each group closer to parity with the web UI (for better or for worse.)

This is somewhat derived from the implementation details in GH-3456, which I'm assuming are correct for groups as well.

---

This change is [Reviewable](https://reviewable.io/reviews/getsentry/sentry/3621)

### CODE REVIEW

**Comment by tkaemming** [comment]
I'm going to go ahead and update the rest of the email templates to use the same template partial for rendering groups for consistency, this will also allow us to fix GH-3666.

**Comment by tkaemming** [comment]
OK @ckj, I think this is done now if you'd like to sign off.

Here is a screenshot of the rendered digest: screenshot 2016-07-13 16 34 53

The remainder of the emails affected should be able to be reviewed in Percy. (I also have a pull request to add this to digests for future work over at GH-3719.)

**Comment by ckj** [comment]
Reviewed 1 of 2 files at r4, 2 of 2 files at r8, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3621)*

**Comment by tkaemming** [comment]
*[src/sentry/templates/sentry/emails/email-styles.html, line 359 \[r9\]](https://reviewable.io:443/reviews/getsentry/sentry/3621#-KMaj2CaBSskBxgqAyrX:-KMaj2Cbh7TMjJiF3k2t:-272736227) ([raw file](https://github.com/getsentry/sentry/blob/716a67414aabcb91593005e9a4c8d374e57ee609/src/sentry/templates/sentry/emails/email-styles.html#L359)):*
> ```HTML
>   .event-type h3 {
>       line-height: 24px;
>       margin: 0;
> ```

Oops, fixed this tab width here: 7614d958d1f6751e819649f489e1446a2a12a1ca

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3621)*

**Pull request merged**
