### PR TITLE
Add raw toggle for additional data section

### LINKED ISSUE #5689: Add "raw" toggle to extra data (or any rich rendered field)
We need to be able to provide users an easy way to copy/paste values that appear in the `extra` interface (and other rich rendered fields). It might need to be per-field.

Example of when this is difficult:

As commented on the forums: https://forum.sentry.io/t/extra-data-in-raw-format/1873

### PR DESCRIPTION
**Pull request by kjlundsgaard**
Allow toggle so that additional data can be accessed in its raw format. Fixes #5689

What it looks like (updated):
toggle_raw

### CODE REVIEW

**Comment by getsentry-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Review by benvinegar — CHANGES_REQUESTED** [review]
* Let's have the keys remain as part of the UI (don't collapse the entire thing into a JSON string)
* Can we move the toggle to the top right (like Original/Minified for stack traces)?

**Comment by sabrehagen** [comment]
We're only a single lint error away from getting this in 👏

**Review by macqueen — APPROVED** [review]
seems like it could be good to write a basic test, but otherwise 👍

**Review by benvinegar — APPROVED** [review]

**Pull request merged**
