### PR TITLE
chore: Update Performance code owners

### PR DESCRIPTION
**Pull request by gggritso**
- Assign D&D code to Performance
- Assign Starfish to Performance
- Remove redundant assignment

### CODE REVIEW

**Review by AbhiPrasad — APPROVED** [review]
Unified Theory of Ownership 🫡

**Comment by asottile-sentry** [comment]
broke a test again -- cc @IanWoodard @sentaur-athena

```
FAILED tests/sentry/api/test_api_owners.py::APIOwnersTestCase::test_api_owner_owns_api - AssertionError: assert 'discover-n-dashboards' in {'alerts-notifications', 'crons', 'data', 'ecosystem', 'enterprise', 'feedback-backend', ...}
 +  where 'discover-n-dashboards' = <ApiOwner.DISCOVER_N_DASHBOARDS: 'discover-n-dashboards'>.value
 +  and   {'alerts-notifications', 'crons', 'data', 'ecosystem', 'enterprise', 'feedback-backend', ...} = <tests.sentry.api.test_api_owners.APIOwnersTestCase testMethod=test_api_owner_owns_api>.teams
```

**Comment by sentaur-athena** [comment]
For example in this case discover-n-dashvoard is removed from codeowners leaving a ton apis orphaned. If we can have a test on changes of codeowners it would be great.

**Comment by gggritso** [comment]
I'll update the owners of DND endpoints to Performance

**Comment by gggritso** [comment]
@sentaur-athena any idea why this test didn't fail on the PR before merging?

**Comment by sentaur-athena** [comment]
@gggritso it's what I'm suggesting in my above comment. codeowner changes currently don't trigger backend tests at all. If you were to update API owner to something that doesn't exist in codeowners the test would visibly fail.

**Comment by gggritso** [comment]
Roger, thanks!

**Comment by asottile-sentry** [comment]
ideally codeowners changes shouldn't impact tests at all.  the fact that they can kinda breaks my plan to make codeowners-only changes auto-approved :(

**Comment by sentaur-athena** [comment]
That's a good idea. We need API owners to be synced with codeowners and that's also something as important. We will fall back to the era where api quality didn't matter at all again. So let's work together on a solution that would work for both. Feel free to dm me or add your proposal to API TSC.

**Comment by asottile-sentry** [comment]
I think it might be on you to come up with something appropriate here since you introduced this failure mode and you understand the domain better :( -- why do we have both in the first place?

**Pull request merged**
