### PR TITLE
perf(indexer): Throttle Sentry logging for dropped cardinality errors

### PR DESCRIPTION
**Pull request by lynnagara**
We are getting way too many dropped messages due to high cardinality, throttle logging of these to Sentry

### CODE REVIEW

**Review by untitaker — APPROVED** [review]

**Comment by untitaker** [comment]
I am not entirely sure about this fwiw. we started logging this error because we wanted attribution to orgs for which we lost data. we should notify ingest that the error isn't accurate anymore, they tend to use this error for investigation (or used to)

cc @getsentry/ingest

**Comment by lynnagara** [comment]
@untitaker it hasn't been all that accurate for a long time due to the sample rate. there is a statsd metric with the actual number also emitted.

**Comment by lynnagara** [comment]
Sorry, I just realised the metric is missing too. Will fix tomorrow.

**Comment by untitaker** [comment]
how about we just revert this PR?

**Pull request merged**
