### PR TITLE
filters/browser_extensions: Filter out errors caused by "global code"

### LINKED ISSUE #5267: Ignore cross-origin SecurityError caused by broken browser autofill on iOS
We are currently seeing a lot of `SecurityErrors` being reported that are originating from the autofill function of Chrome for iOS.

The exception message usually reads something like:
> Blocked a frame with origin "https://www.foo.bar" from accessing a frame with origin "https://4606765.fls.doubleclick.net". Protocols, domains, and ports must match.

This seems to be caused by the injected browser code trying to access forms in an `<iframe>` with a different origin.

related links:

- http://stackoverflow.com/a/43469069/1478093
- https://bugs.chromium.org/p/chromium/issues/detail?id=590375

<p>
<details>
 <summary>Example <code>sentry.interfaces.Exception</code> content</summary>
<br>

```json
{
  "sentry.interfaces.Exception": {
    "exc_omitted": null,
    "values": [
      {
        "stacktrace": {
          "has_system_frames": false,
          "frames": [
            {
              "function": "global code",
              "abs_path": "https://www.foo.bar/",
              "module": "<unknown module>",
              "filename": "/",
              "post_context": [
                "<html>",
                "  <head>",
                "    <meta charset=\"utf-8\">",
                "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">",
                ""
              ],
              "colno": 98,
              "in_app": false,
              "context_line": "<!DOCTYPE html>",
              "lineno": 1
            },
            {
              "function": "extractForms",
              "abs_path": "https://www.foo.bar/",
              "pre_context": [
                "  <head>",
                "    <meta charset=\"utf-8\">",
                "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">",
                "",
                ""
              ],
              "module": "<unknown module>",
              "filename": "/",
              "post_context": [
                "",
                "",
                "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">",
                "    <meta name=\"HandheldFriendly\" content=\"True\"/>",
                "    <meta name=\"MobileOptimized\" content=\"320\"/>"
              ],
              "colno": 381,
              "in_app": false,
              "context_line": "    <title>Foo Bar</title>",
              "lineno": 8
            },
            {
              "function": "extractNewForms",
              "abs_path": "https://www.foo.bar/",
              "pre_context": [
                "    <title>Foo Bar</title>",
                "",
                "",
                "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">",
                "    <meta name=\"HandheldFriendly\" content=\"True\"/>"
              ],
              "module": "<unknown module>",
              "filename": "/",
              "post_context": [
                "    <meta http-equiv=\"cleartype\" content=\"on\"/>",
                "",
                "    <link rel=\"shortcut icon\" href=\"/external_assets/favicons/favicon.ico\" id=\"favicon\" />",
                "    <link rel=\"apple-touch-icon-precomposed\" sizes=\"57x57\"   href=\"/external_assets/favicons/apple-touch-icon-57x57-precomposed.png\" />",
                "    <link rel=\"apple-touch-icon-precomposed\" sizes=\"72x72\"   href=\"/external_assets/favicons/apple-touch-icon-72x72-precomposed.png\" />"
              ],
              "colno": 37,
              "in_app": false,
              "context_line": "    <meta name=\"MobileOptimized\" content=\"320\"/>",
              "lineno": 13
            },
            {
              "function": "g",
              "abs_path": "https://www.foo.bar/",
              "pre_context": [
                "<html>",
                "  <head>",
                "    <meta charset=\"utf-8\">",
                "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">",
                ""
              ],
              "module": "<unknown module>",
              "filename": "/",
              "post_context": [
                "    <title>Foo Bar</title>",
                "",
                "",
                "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">",
                "    <meta name=\"HandheldFriendly\" content=\"True\"/>"
              ],
              "colno": 323,
              "in_app": false,
              "context_line": "",
              "lineno": 7
            },
            {
              "function": "g",
              "abs_path": "https://www.foo.bar/",
              "pre_context": [
                "<!DOCTYPE html>",
                "<html>",
                "  <head>",
                "    <meta charset=\"utf-8\">"
              ],
              "module": "<unknown module>",
              "filename": "/",
              "post_context": [
                "",
                "",
                "    <title>Foo Bar</title>",
                "",
                ""
              ],
              "colno": 190,
              "in_app": false,
              "context_line": "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">",
              "lineno": 5
            }
          ],
          "frames_omitted": null
        },
        "mechanism": null,
        "type": "SecurityError",
        "module": null,
        "thread_id": null,
        "value": "Blocked a frame with origin \"https://www.foo.bar\" from accessing a frame with origin \"https://4606765.fls.doubleclick.net\". Protocols, domains, and ports must match.",
        "raw_stacktrace": null
      }
    ]
  }
}
```

</details>
</p>

I would like to propose adding this kind of exception to the [`BrowserExtensionsFilter`](https://github.com/getsentry/sentry/blob/ec9d13f8e3f812023bc664c9fda8c0ac1a118507/src/sentry/filters/browser_extensions.py). I can try to add the filtering code myself, but I would need some guidance on how you would like me to filter for this kind of exception (e.g. filter everything where first frame has `function: 'global code'`?)

### PR DESCRIPTION
**Pull request by Turbo87**
Resolves #5267

### CODE REVIEW

**Comment by mattrobenolt** [comment]
@benvinegar Do you know if this is reasonable? I don't know enough here to know if there are legit cases for this that we wouldn't want to filter out.

**Comment by benvinegar** [comment]
Definitely not enough information. What is this stopping? `global code` is something Safari spits out, and really just speaks to the scope of your code (e.g. `window` scope), which could be perfectly legitimate code afaik.

**Comment by Turbo87** [comment]
@benvinegar have you seen https://github.com/getsentry/sentry/issues/5267? please let me know what other information you need.

**Comment by benvinegar** [comment]
So one thing to know: Chrome for iOS is actually just a Safari Webview, which is why I identified this `global code` pattern as coming from Safari.

I suspect reason for this error / stack trace is that the autofill code is _likely_ implemented as a Safari extension (e.g. not part of the core WebView), and it has a bug.

To me, the only way to reliably detect this error is to look for `extractForms` etc in the stack, AND consider the user agent. But I'm not sure the processor code is set up just yet to do that.

In the meantime, I strongly recommend just having your own `shouldSendCallback` in Raven.js that rejects these errors.

**Comment by Turbo87** [comment]
> Aside: I suspect reason for this error / stack trace is that the autofill code is likely implemented as a Safari extension (e.g. not part of the core WebView), and it has a bug.

yes (https://bugs.chromium.org/p/chromium/issues/detail?id=590375), at least one bug...

> To me, the only way to reliably detect this error is to look for extractForms etc in the stack, AND consider the user agent. But I'm not sure the processor code is set up just yet to do that.

I'll see if I can find the time to revise the PR and check for those things instead.

> So one thing to know: Chrome for iOS is actually just a Safari Webview, which is why I identified this global code pattern as coming from Safari. It can/does appear in other stack traces, and so it 100% cannot be used (alone).

I thought that `global code` would indicate that the error originated in something injected into the WebView which seemed like it would always be a browser extension of some sort, even if that means the Chrome Mobile "browser extension" on top of the WebView component.

**Pull request closed without merging**
