### PR TITLE
fix(sessions): Fix metrics querybuilder

### PR DESCRIPTION
**Pull request by lynnagara**
not sure why this had sessions as the dataset, sessions doesn't exist anymore

### CODE REVIEW

**Review by iambriccardo — APPROVED** [review]
Good catch, this is not impacting the product though since the dataset won't be used because this code is not querying anything. The high coupling of query builders with parsing logic makes it quite hard to use exclusively the parsing logic.

**Comment by lynnagara** [comment]
@iambriccardo Do you have advice on how to resolve the `AttributeError: 'ReleaseHealthQueryBuilder' object has no attribute 'use_on_demand'` issue in the failing tests... Is that supposed to be defined on on that class?

**Comment by iambriccardo** [comment]
> @iambriccardo Do you have advice on how to resolve the `AttributeError: 'ReleaseHealthQueryBuilder' object has no attribute 'use_on_demand'` issue in the failing tests... Is it supposed to be defined on on that class?

I will check this out.

**Comment by iambriccardo** [comment]
I have tried several solutions to fix this problem but due to how intertwined the parsing logic is with the `Sessions` dataset configuration, our best bet is to temporarily keep this like it they are right now and in the future we will switch to the new `metrics/query` endpoint which has a completely new way of parsing queries.

**Pull request closed without merging**
