### PR TITLE
build(ci): Separate webpack from acceptance test runner

### PR DESCRIPTION
**Pull request by billyvg**
This creates a new webpack job that prepares our frontend assets for acceptance tests. The acceptance test runners will wait until this is completed before running.

### CODE REVIEW

**Comment by billyvg** [comment]
Yikes (although webpack is using `mode=production`, it could be faster w/o it).

image


The upload takes quite a bit because it does not batch the upload (see https://github.com/actions/upload-artifact/issues/69)

Also, all acceptance tests are blocked until webpack finishes - ideally the acceptance tests would initialize and wait for the webpack job to finish. Maybe this could be done if we polled the API until `webpack` job is finished?

**Comment by billyvg** [comment]
We could use something like https://github.com/marketplace/actions/wait-on-check to wait for the webpack job

**Comment by billyvg** [comment]
image

After changing away from `mode=production`
image

**Comment by armenzg** [comment]
> Yikes (although webpack is using `mode=production`, it could be faster w/o it).
> 
> image
> 
> The upload takes quite a bit because it does not batch the upload (see [actions/upload-artifact#69](https://github.com/actions/upload-artifact/issues/69))
> 
> Also, all acceptance tests are blocked until webpack finishes - ideally the acceptance tests would initialize and wait for the webpack job to finish. Maybe this could be done if we polled the API until `webpack` job is finished?

I think you could work around this by first compressing it (tar -cJf dist.tar.xz static/dist) and then uploading a single file.

**Pull request closed without merging**
