### PR TITLE
feat(pagerduty): Make the sentry issue link text more explicit

### PR DESCRIPTION
**Pull request by davidshepherd7**
This text appears hidden away near the bottom of the pagerduty page and positioned in a way that makes 
it unclear that the link is provided by sentry rather than pagerduty. Since it's probably the most important 
thing on the page, we should make it clearer.

Here's an example: https://imgur.com/a/8ESNJpw

### CODE REVIEW

**Review by silent1mezzo — APPROVED** [review]
👍 Thanks for the contribution! Just going to confirm with the Ecosystem team.

**Comment by MeredithAnya** [comment]
Hey @davidshepherd7, thanks for opening this PR ! 

So this will only change it for the PagerDuty plugin (installed on the project level), not our PagerDuty integration (installed on the organization level). I can't tell from the image which one you are using, but the equivalent code for the PagerDuty integration lives [here](https://github.com/getsentry/sentry/blob/master/src/sentry/integrations/pagerduty/client.py#L56). Even if you are just using the plugin, I think it would be good to update the integration as well. 

That change plus updating the broken test(s) and I think you're good to go.

**Comment by davidshepherd7** [comment]
@MeredithAnya Hi, sorry for the slow response! I've made those changes and I think the tests have passed (the failed ones are not fixable by me right?).

**Comment by MeredithAnya** [comment]
@davidshepherd7 So I think the visual snapshot test doesn't currently work on forked versions of Sentry, and since it's required I'm going to have to wait on merging until we can get that sorted. Hopefully in the next week or so! 

Feel free to ping me if this isn't merged by end of next week!

**Comment by BYK** [comment]
Went ahead and overruled the requirement as this looks safe and @MeredithAnya already gave a 👍🏻 .

Thanks a lot @davidshepherd7!

**Pull request merged**
