### PR TITLE
chore: Update selenium to 4.0.0

### PR DESCRIPTION
**Pull request by dashed**
Unable to run pytest locally since `selenium` v3 contains SyntaxErrors that python 3.8 doesn't like.

### CODE REVIEW

**Review by joshuarli — APPROVED** [review]

**Review by wedamija — APPROVED** [review]

**Comment by joshuarli** [comment]
urllib3 isn't trivial to upgrade, and selenium v4 has some api changes that we might need to adapt to. We need to make it easier to patch local dependencies because upgrading a bunch of stuff just for a one line change is often not justifiable. For now: https://github.com/getsentry/sentry/pull/29887

**Comment by dashed** [comment]
@joshuarli 🌮

**Comment by armenzg** [comment]
Should we close this?

**Review by armenzg — CHANGES_REQUESTED** [review]
This requires addressing the concerns Josh raised.

**Comment by joshuarli** [comment]
Closing due to age, reopen in the future.

**Comment by dashed** [comment]
@joshuarli thanks future Josh.

**Pull request closed without merging**
