### PR TITLE
Fix atomic with block in run_deletion task

### PR DESCRIPTION
**Pull request by jarus**

### CODE REVIEW

**Review by mattrobenolt — APPROVED** [review]
How uhh, did we not hit this?

**Comment by mattrobenolt** [comment]
Thanks! 🍕

**Comment by JTCunning** [comment]
This is golden. Thanks @jarus!

**Comment by jarus** [comment]
I assume there is no test with a deletion object which isn't in_progress already. I just hit it by triggering a manual deletion from CLI.

**Pull request merged**
