### PR TITLE
chore: Fix typo errywhere -> everywhere

### PR DESCRIPTION
**Pull request by iAziz786**

### CODE REVIEW

**Comment by mattrobenolt** [comment]
I'm pretty sure I misspelled this intentionally for comedic value.

Was added in https://github.com/getsentry/sentry/commit/4505e9fe44cabd078596dff80c89358c507db166

**Comment by iAziz786** [comment]
Oh, I thought it was a typo. 😅

**Review by dashed — APPROVED** [review]

**Comment by iAziz786** [comment]
Should I close this or anyone wants to merge it?

**Comment by mattrobenolt** [comment]
I don't have a strong opinion. I was just pointing out that I did it intentionally for my own entertainment 4 years ago.

If someone feels strongly to merge, go for it.

**Comment by iAziz786** [comment]
> I don't have a strong opinion. I was just pointing out that I did it intentionally for my own entertainment 4 years ago.

Let's merge it then.

**Comment by untitaker** [comment]
Merged this because this would've tripped me up back when I started to learn english.

**Pull request merged**
