### PR TITLE
chore(logo-upload): Migrate SentryApp table to include popularity column

### PR DESCRIPTION
**Pull request by leeandher**
See [API-2249](https://getsentry.atlassian.net/browse/API-2249)

This PR will add the popularity column to the SentryApp table with a type of PositiveSmallInteger. The default value is 1 since that will be the lowest ranking when compared to the current hardcoded values.

### CODE REVIEW

**Comment by leeandher** [comment]
i dont know if the GH bot edits its first message but i changed the migration, here is the new sql

```sql
BEGIN;
--
-- Custom state/database change combination
--
ALTER TABLE "sentry_sentryapp" ADD COLUMN "popularity" smallint NULL CHECK ("popularity" >= 0);
COMMIT;
```

**Comment by leeandher** [comment]
gh bot is smart

**Review by wedamija — APPROVED** [review]
looks good to me, thanks for updating the docs!

How will popularity be used? Any chance we will overflow a small int at some point?

**Comment by ceorourke** [comment]
@wedamija popularity is currently housed here https://github.com/getsentry/sentry/blob/master/static/app/views/organizationIntegrations/constants.tsx#L37 and will be replaced - the highest rn is 50 for slack and all published sentryapps are 9 so we're good

**Pull request merged**
