### PR TITLE
chore(eslint): Upgrade to v7

### PR DESCRIPTION
**Pull request by billyvg**
[Migration to 6.0.0](https://eslint.org/docs/user-guide/migrating-to-6.0.0)
[Migration to 7.0.0](https://eslint.org/docs/user-guide/migrating-to-7.0.0)

### CODE REVIEW

**Comment by EvanPurkhiser** [comment]
Looks like this was 100% fine.

Anything blocking this @billyvg ?

**Comment by billyvg** [comment]
@EvanPurkhiser No, I'll resolve + open PR on gs

**Comment by billyvg** [comment]
@EvanPurkhiser https://travis-ci.org/github/getsentry/sentry/jobs/705868093#L409 👀

**Review by BYK — APPROVED** [review]
Let's roll! 🧻

**Comment by billyvg** [comment]
Closing this as I don't have time to get this working

**Pull request closed without merging**
