### PR TITLE
(fix) Fix issue_page.viewed analytics event

### PR DESCRIPTION
**Pull request by adhiraj**
Seems to have broken in https://github.com/getsentry/sentry/pull/11422 with Sentry 10 changes.

Tried putting it in various places like componentDidMount or onGroupChange, but they either don't have the data yet, or are called multiple times. Putting it right after the API call seems to come closest to logging it once.

### CODE REVIEW

**Comment by adhiraj** [comment]
@lynnagara where is https://github.com/getsentry/sentry/blob/master/src/sentry/static/sentry/app/views/groupDetails/project/index.jsx#L38 being used? there still seem to be some calls to that component, though much fewer than historically

**Comment by lynnagara** [comment]
It's a lot less than historically since it's currently only tracked for users in the Sentry 9 flow.

For users in Sentry 10, it might be cleaner to add the analytics in this file instead - https://github.com/getsentry/sentry/blob/master/src/sentry/static/sentry/app/views/groupDetails/organization/index.jsx. The org and group ID should already be there when this component is mounted. Putting it in the success callback here will result it being called too many times when you toggle environment, etc.

**Comment by lynnagara** [comment]
Ah, unfortunately we remove project from all of the URLs so it's not as easy as before

**Review by lynnagara — APPROVED** [review]

**Comment by lynnagara** [comment]
nit: When you do squash and merge, can you make the commit prefix `fix:` vs `(fix)`, ref: https://docs.sentry.io/development/contribute/contributing/#commit-guidelines

**Pull request merged**
