### PR TITLE
feat(upgrade): Default to superuser for first user 

### LINKED ISSUE #80: Should tell if user needs to be superuser
Step (4) of the [README](https://hub.docker.com/_/sentry/) should tell if if the user needs to be superuser or not. Specially the question asked by Django is:

```
Should this user be a superuser? [y/N]:
```

Note that it default to **No**

### PR DESCRIPTION
**Pull request by BYK**
Creates the initial user as super user as this causes confusion for self-hosted versions and is 100% what the user wants and needs.

Fixes getsentry/docker-sentry#80

### CODE REVIEW

**Comment by untitaker** [comment]
Can we change the default here as well: https://github.com/getsentry/sentry/blob/ea576b8ab6744655d5d3bd07490913ef5802c000/src/sentry/runner/commands/createuser.py#L46

**Comment by dashed** [comment]
@BYK There's a `y/N` command prompt that shows up asking to make the first user a superuser. Unsure if this affects that.

**Comment by dashed** [comment]
Looks like @untitaker beat me to it 😄

**Comment by untitaker** [comment]
Yeah actually I think the prompt will still appear. Not sure how click works.

**Comment by BYK** [comment]
I've manually tested this flow and the prompt does not appear once you pass the value. The prompt is triggered by us only when nothing is passed: https://github.com/getsentry/sentry/blob/f365c0b8f356fc131b45dc091530674785701a56/src/sentry/runner/commands/createuser.py#L59-L60

Re, default value: we should definitely not change that as it will completely skip the prompt and create every user as a super user. We don't want that :)

**Review by untitaker — APPROVED** [review]

**Comment by BYK** [comment]
This branch accidentally had the contents of #13704 too which is also now approved.

**Pull request merged**
