### PR TITLE
default to release overview page for early adopters

### PR DESCRIPTION
**Pull request by macqueen**
isActive logic got somewhat gross, but couldn't think of a better way to deal with that

cc @ckj

### CODE REVIEW

**Comment by benvinegar** [comment]
Hmm. This is definitely not great. But ... the alternative is to re-write all URLs to "releases" through some kind of helper than changes the URL slug according to current org features, which also feels clunky.

If the performance impact feels low, since very few people visit these pages, we might be able to get away with it.

**Comment by macqueen** [comment]
@benvinegar yeah, also this is only going to be necessary until we move it from early adopters --> everyone so i'm hesitant to do something that is going to be a lot more work.

**Comment by benvinegar** [comment]
If you feel the user experience is fine / the lag is not really noticeable, then go for it ... but maybe comment that this is not ideal and we need to remove once we switch

**Review by benvinegar — APPROVED** [review]

**Comment by macqueen** [comment]
@benvinegar going to deploy to staging and see how slow it is

**Pull request merged**
