### PR TITLE
Allow models to be available read-only by server mode

### PR DESCRIPTION
**Pull request by RyanSkonnord**
Follows #34981.

Add a read-only mode for the `available_on` decorator. Requires more in-depth modification of the affected model's manager object.

### CODE REVIEW

**Comment by RyanSkonnord** [comment]
A major limitation of the current solution is that it only cares about the server mode at the time the decorator is evaluated, i.e., when the class is imported. This should work fine for prod and dev servers, but means that `settings_override` inside a unit test won't do anything.

But I have an idea for this, which I'm working on presently. In short: instead of conditionally overriding methods to always throw an exception, always override the methods to conditionally throw an exception. I'll probably make an analogous change to the endpoint decorator.

**Comment by markstory** [comment]
> This should work fine for prod and dev servers, but means that settings_override inside a unit test won't do anything.

We could run control/customer silo tests as a separate test run and annotate tests with pytest markers.

**Comment by RyanSkonnord** [comment]
> A major limitation of the current solution is that it only cares about the server mode at the time the decorator is evaluated, i.e., when the class is imported. ... But I have an idea for this, which I'm working on presently.

I think I've got this solved, and it motivated a big enough refactoring that I broke it out into another review: #35809

**Comment by RyanSkonnord** [comment]
Folded into https://github.com/getsentry/sentry/pull/35994

**Pull request closed without merging**
