### PR TITLE
feat(native): Support gzipped chunk uploads

### PR DESCRIPTION
**Pull request by jan-auer**
Server side support for gzipped chunk uploads. See https://github.com/getsentry/sentry-cli/pull/315

### CODE REVIEW

**Review by mitsuhiko — APPROVED** [review]
Not a huge fan of this gzipchunk but I can't come up with anything better that gives us the size ahead of time. We could let the client send it if we cared.

**Comment by mitsuhiko** [comment]
Actually can we make compression a list? Otherwise we lock ourselves to gzip forever.

**Review by mitsuhiko — CHANGES_REQUESTED** [review]
See last comment.

**Comment by jan-auer** [comment]
@mitsuhiko Updated

**Review by mitsuhiko — APPROVED** [review]

**Pull request merged**
