### PR TITLE
Install phantomjs to support selenium (refs GH-3423)

### PR DESCRIPTION
**Pull request by dcramer**
@fotinakis let me know if this works

### CODE REVIEW

**Comment by fotinakis** [comment]
I think @mattrobenolt's comments about where npm versions store dependencies different still might make trouble for relying on a transitive dependency like this.

**Comment by dcramer** [comment]
@fotinakis i get a socket timeout running selenium tests (not sure if related) but no errors on npm 2 with clean empty node_modules. I'm install npm 3 to confirm no issues there either.

**Comment by dcramer** [comment]
https://github.com/karma-runner/karma-phantomjs-launcher/pull/123/files we likely need this to fix npm3

**Comment by dcramer** [comment]
We should probably just rm -rf the dep and put the code in our test suite:

https://github.com/karma-runner/karma-phantomjs-launcher/blob/master/index.js

**Comment by dcramer** [comment]
FYI feel free to take over this PR if anyone wants to finish resolving this. I think our best approach is to vendor the plugin since there's no released solution and any release has to go through Google's CLA process.

**Comment by fotinakis** [comment]
@dcramer You can close this PR, I've cherry-picked the commit into #3497 and will finish it out there. I think I'm going to have to end up just putting a conditional.

**Pull request closed without merging**
