### PR TITLE
Fix: bower dependencies during build

### PR DESCRIPTION
**Pull request by beeftornado**
Suggested fix for https://github.com/getsentry/sentry/issues/1384

Installs bower dependencies during build phase.

### CODE REVIEW

**Comment by dcramer** [comment]
Hrm bower should be getting installed (and called) via npm install:

```
  "scripts": {
    "postinstall": "bower install",
```

**Comment by beeftornado** [comment]
^^ This is indeed true and I stand corrected. There is no defect here besides user error. My install was owned by root, "just because", and bower's errors were silenced by setup,py's `npm install --quiet` command and so I did not realize bower was even being run. Bower does not install any packages as `root`. (See https://github.com/bower/bower/issues/498). Re-running the clean install as a regular user does work as expected. I'm fine with the script as-is, but if another dummy comes along and thinks the same thing, it could be useful to have the same "safeguard" as bower and either a) warn if user is root, or b) fatally exit if root, or c) add the flag to bower install that allows root installs anyway.

**Comment by dcramer** [comment]
I might be ok with the flag that allows root, since I've had to do this in the past with bower. It's not really a great practice, but people are going to do waht they're going to do.

**Comment by beeftornado** [comment]
It's an easy task, but I know context switching is expensive so I am offering up the addition of the flag.

**Comment by dcramer** [comment]
@beeftornado  if you want to do it I'll pull it in

FWIW in our redesign we've removed bower as a dependency due to random problems (like this one)

**Pull request merged**
