### PR TITLE
chore(replay): remove refs to GA'd HE flag

### PR DESCRIPTION
**Pull request by aliu39**

### CODE REVIEW

**Comment by michellewzhang** [comment]
should probably split up backend and frontend changed into separate PRs

**Comment by aliu39** [comment]
oops, true!

**Comment by aliu39** [comment]
Actually, I don't think these changes are interdependent in any way. Do you think it's ok to merge them in one?

**Comment by michellewzhang** [comment]
> Actually, I don't think these changes are interdependent in any way. Do you think it's ok to merge them in one?

frontend + backend deploy at diff times, so you don't want to risk it - we should generally always rm FE ff references first, then the BE ones

**Review by michellewzhang — APPROVED** [review]

**Pull request merged**
