### PR TITLE
Fix lambda expressions for Python 3

### LINKED ISSUE #6030: Python 3 functions and lambdas cannot take explicit tuple param
The following lines in Sentry can not be ported to Python 3 in their current form...

flake8 testing of https://github.com/getsentry/sentry on Python 3.6.3

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./src/sentry/api/endpoints/group_similar_issues.py:21:20: E999 SyntaxError: invalid syntax
            lambda (group_id, scores): group_id != group.id,
                   ^

./src/sentry/api/serializers/models/group.py:78:36: E999 SyntaxError: invalid syntax
                            lambda (project, groups): groups if not options.get(
                                   ^

./src/sentry/digests/backends/redis.py:231:24: E999 SyntaxError: invalid syntax
                lambda (key, value, timestamp): Record(
                       ^

./src/sentry/rules/conditions/event_frequency.py:32:65: E999 SyntaxError: invalid syntax
                      ) in sorted(intervals.items(), key=lambda (key, (label, duration)): duration)
                                                                ^

./src/sentry/similarity/features.py:19:16: E999 SyntaxError: invalid syntax
        lambda (in_app, frames): list(frames),
               ^

./src/sentry/tasks/reports.py:700:26: E999 SyntaxError: invalid syntax
        lambda interval, (project, report): report is not None,
                         ^

./src/sentry/utils/iterators.py:21:20: E999 SyntaxError: invalid syntax
            lambda (i, iterator): advance(i, iterator),
                   ^

./tests/sentry/similarity/test_signatures.py:25:24: E999 SyntaxError: invalid syntax
                lambda (l, r): l == r,
                       ^

8     E999 SyntaxError: invalid syntax
```

### PR DESCRIPTION
**Pull request by cclauss**
Fixes #6030  In Python 3, __lambda (a, b):__ is a syntax error while __lambda a, b:__ is valid Python.  However, as noted in the comments below, these two formulation are not syntactically equivalent.  The first takes a single iterable with at least two values while the second takes two discrete values.

In this PR, `lambda (a, b):` is rewritten as `lambda a__b:`(note double the underscore).  Then in the _body_ of the lambda `a` is rewritten as `a__b[0]` and `b` is rewritten as `a__b[1]`.  It is a bit verbose but works in both Python 2 and Python 3.

@mattrobenolt @tkaemming @dcramer Please review these changes based on the comments in #6030 

If these are the correct changes then for the first time we can create an Abstract Syntax Tree for all Python files in this repo in both Python 2 and Python 3 without finding syntax errors or undefined names.
* python2 -m flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
* python3 -m flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics

### CODE REVIEW

**Review by tkaemming — CHANGES_REQUESTED** [review]
`lambda a, b:` and `lambda (a, b):` are not syntactically equivalent — the first takes two arguments, the second takes one argument (a sequence that has two items.)

**Comment by cclauss** [comment]
@tkaemming Thanks.  A bit of hacking at the REPL makes this clear to me now.

What would be an appropriate alternative.  There is the extra complication of __lambda (a (b, c)):__ that is used in a few places.

**Comment by dcramer** [comment]
@cclauss i think you'd have to just say 'arg' or something, and then do arg[0], arg[1], etc.

**Comment by getsentry-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by cclauss** [comment]
@tkaemming @dcramer Are these changes in line with expectations?

**Review by tkaemming — APPROVED** [review]
I think we'll want to rewrite many of these at some point to named function for readability's sake but this should work as expected now.

Thanks!

**Pull request merged**
