### PR TITLE
feat(symbolication): Add symbolication status to project details (NATIVE-209)

### PR DESCRIPTION
**Pull request by flub**
This adds a field in the project details which exposes the health of
the project's symbolication processing.  The aim is to let the UI show
warnings on the project if we are experiencing processing problems.

Currently returns dummy data, but a followup will change this to read
from 3 sentry options and compute the correct value from those.

NATIVE-209

---

Adding dynamic status information to the project details endpoint is perhaps a little weird, since currently it is entirely controlled via serialisers.  The other option would be to create a new project endpoint to return the status (e.g. `/{org_slug}/{proj_slug/health` or `/{org_slug}/{proj_slug}/status`), but the downside is that the UI now needs to query a new endpoint everywhere it needs to show this and project details is already needed in all those places.

### CODE REVIEW

**Review by loewenheim — APPROVED** [review]

**Review by relaxolotl — APPROVED** [review]
I assume this is change is being made primarily to unblock @priscilawebdev on the front end work? If not then the diff seems a little too bare-bones to be meaningful, but that's assuming the earlier statement is false.

**Comment by priscilawebdev** [comment]
if we decide to add a new endpoint to look for the project health, I would vote for `/{org_slug} / {proj_slug / health`. I think since we plan to display the alert elsewhere in the app where we don't fetch project details data, it makes sense to create it

**Review by priscilawebdev — APPROVED** [review]

**Comment by flub** [comment]
> I assume this is change is being made primarily to unblock @priscilawebdev on the front end work? If not then the diff seems a little too bare-bones to be meaningful, but that's assuming the earlier statement is false.

Yes, there is another task to make it reflect reality later

**Comment by flub** [comment]
> if we decide to add a new endpoint to return the project status, I would vote for `/{org_slug}/{proj_slug/health`. I think since we plan to display the alert elsewhere in the app where we don't fetch project details data, it makes sense to create it

@priscilawebdev Wait, you're saying you now have to start calling project details in new places?  That kind of invalidates the motivation to add it to project details...  and results in much more work on the backend than really required for the other places.  So I'll change this to be on `/{org_slug}/{proj_slug/health`

**Comment by priscilawebdev** [comment]
Sorry @flub, my explanation was not very clear... I meant that if we want to display these alerts elsewhere in the future, it would make sense to have this extra endpoint, but for now, we don't need it

**Comment by flub** [comment]
We had some short discussion and concluded to leave it as is, maybe later it can be merged into a more general notifications endpoint but designing such an endpoint is out of scope for now since we don't know all the requirements yet.

**Pull request merged**
