### PR TITLE
ref(ui) Convert icon-circle-exclamation to SVG components.

### PR DESCRIPTION
**Pull request by markstory**
This icon either represents a warning or a flag depending on the context. The bulk of the conversions were to flag as warning is intended to be used for 'leaning towards bad but not there yet', which doesn't fit with empty states and 'tips' in the application.

EmptyMessage components should have xl icons, as they previously set the icon size to 32px. To accommodate HeroIcon, I've had to introduce a new xxl icon size.

### CODE REVIEW

**Comment by priscilawebdev** [comment]
@markstory I am not sure about displaying a flag in the empty state component...maybe you could ask the design team to create a better icon..like for example an island? 🤷‍♀️

**Comment by priscilawebdev** [comment]
in this case, I think the iconSearch would fit better

image

. Please shouldn't the icon color be gray?

**Review by priscilawebdev — APPROVED** [review]
Good job 👏

**Comment by priscilawebdev** [comment]
maybe the icon below could be slightly bigger? but it's up to you 🙃

image

**Review by k-fish — APPROVED** [review]

**Pull request merged**
