### PR TITLE
feat(span-tree): Instrument toggle interactions on span tree

### PR DESCRIPTION
**Pull request by 0Calories**
In lieu of the generic interaction transactions that is WIP on the JS SDK, we can add some custom instrumentation to the span tree!

This introduces a new custom transaction called `ui.SpanTreeToggle`, which will be triggered when either a subtree or autogroup is collapsed / expanded. These interactions are some of the most expensive operations on the span tree, since they cause the entire tree to re-render. Instrumenting them may give us a bigger picture of what its performance looks like

I've also wrapped the SpanBar component with our react profiler, so we can see their lifecycle spans within this transaction and others.

Another thing, I've removed the `CustomerProfiler` HoC from the SpanTree, since I already have wrapped it using `withProfiler`.

### CODE REVIEW

**Review by gggritso — COMMENTED** [review]
This makes sense, but do the `startInteraction` calls not need a corresponding `finishInteraction` call?

**Comment by 0Calories** [comment]
@gggritso Hmm actually good point, I was relying on the default idle timeout [here](https://github.com/getsentry/sentry/blob/455dc75f2c3d2b5f811dcfe4d66236fbca613042/static/app/utils/performanceForSentry.tsx#L12) but on second thought, that default might be too big. I think I'll pass in a timeout value of 10 seconds, since I don't want to manually end the transaction

**Comment by 0Calories** [comment]
@gggritso Do you have any ideas on ending the transaction when the components finish re-rendering rather than a set timeout? That would be ideal but I'm not sure how to go about doing it 🤔

**Comment by gggritso** [comment]
I don't have any other major ideas other than waiting for browser idle, like the SDK itself does. Unsure if that'll make anything better in this case!

**Review by gggritso — APPROVED** [review]

**Comment by 0Calories** [comment]
Perfect, thanks! Yeah the browser idle probably won't make much of a difference here, I can probably tweak the timeout on this interaction too if necessary in the future

**Pull request merged**
