### PR TITLE
perf(starfish): improve rendering performance

### PR DESCRIPTION
**Pull request by anonrig**
This PR improves the rendering performance of the "performanceScoreRing" component. 

Previously:
- On each hover, the component was re-rendering and re-creating the "RingBar" and "RingBackground" components causing a slight lag and a drop in FPS. Memoizing the `rings` array makes sure that we don't re-create each background and bar components, unless we change it depending on React component lifecycles.
- Each component appended to this list didn't include any `key` attribute. This means that, on each re-rendering, React didn't know which item in this array got changed, causing the whole list to be re-rendered. React was even helping us towards fixing this issue: `Warning: Each child in a list should have a unique "key" prop.`
- We were creating `textNode` component whether or not `text` attribute is defined, but only using it if it was not `undefined`. Performance wise it is important to not create a component/variable unless we're going to use it. This PR makes sure that we only create it, if the value is not undefined.
- Even though, text has a type of ReactNode, we were calling `.toString()` method on an object/class/component. This resulted in `[object Object]` for the key value of the `Text` component key. Since, we are passing a ReactNode, there's no need of this hack.

### CODE REVIEW

**Review by ryan953 — APPROVED** [review]
Get that `useMemo` action!

**Review by k-fish — COMMENTED** [review]
👍 to the textNode, key etc. changes

Not blocking, but for the memo though can you attach a profile / devtool screenshot of the slow time or whatever you were using to determine this had performance impact, like a before vs. after. Mostly for posterity, just showing the rationale, since we generally don't want to sprinkle in `useMemo` unless it has a meaningful perf impact.

**Comment by k-fish** [comment]
The root of the problem here actually passing `x,y` which are captured from the mouse position, those could just be a css var, poke the ref or something else that didn't cause rerenders of the child in the first place.

**Comment by JonasBa** [comment]
+1 to @k-fish's point here, even thought the changes here seem sound. We shouldn't be storing mouse positions in state and instead just directly mutate the ref's style attribute in order to bypass react

**Pull request merged**
