### PR TITLE
fix(snuba) Percent conditions don't need to be consistent

### PR DESCRIPTION
**Pull request by evanh**
Being consistent doesn't help with sessions since it doesn't go through the same
processing pipeline as transactions and errors. The post processor automatically
makes all queries consistent, so this needs to be explicitly set to False here. This
does degrade performance though since consistent queries are sent to the write
nodes which have less processing power.

### CODE REVIEW

**Comment by evanh** [comment]
FYI workflow is not a codeowner for this file.

**Review by wedamija — COMMENTED** [review]
I thought that @fpacifici recently disabled consistent for these workers?

**Comment by fpacifici** [comment]
Not exactly:
I disabled a percentage only for metric alerts (that are not related with that worker). I never touched post process.  That was enough to keep the issue under control.
Also metric alerts as well are back in a 100% consistent state.

**Comment by wedamija** [comment]
Ok, makes sense. I'm wondering if we should just disable consistent for all of these types of alerts, since they're all fairly expensive and run off of `post_process_group`

**Review by wedamija — APPROVED** [review]

**Comment by fpacifici** [comment]
I am planning to run some stress tests soon to see how much headroom we have. It does not seem to be concerning as of now. The spikiness of metric alerts was largely to blame for the issues we had recently. In terms of sustained load I think we should be fine for a while

**Review by wedamija — APPROVED** [review]

**Pull request merged**
