### PR TITLE
feat(discover): Add slide in animation for Edit Query panel

### PR DESCRIPTION
**Pull request by lynnagara**

### CODE REVIEW

**Comment by lynnagara** [comment]
Not sure the best way to make slide out work with styled components, any ideas?

**Comment by lynnagara** [comment]
Should probably change this to use react-transition-group

**Review by ckj — APPROVED** [review]
not sure react-transition-group is needed here as this works/looks great

**Comment by lynnagara** [comment]
Ok, will leave it at this then

**Pull request merged**
