### PR TITLE
Allow up/down arrow key navigation of project search menu

### LINKED ISSUE #3617: add ability to navigate project search menu with up/down arrow keys
screenshot 2016-06-30 10 36 18

### PR DESCRIPTION
**Pull request by kjlundsgaard**
Fixes #3617  
@getsentry/ui

---

This change is [Reviewable](https://reviewable.io/reviews/getsentry/sentry/3944)

### CODE REVIEW

**Comment by macqueen** [comment]
could you add a screenshot of the highlighted menu item?

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/sentry/static/sentry/app/components/projectHeader/projectSelector.jsx, line 63 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/3944#-KPFG5lB_0Id9wgHZmPZ:-KPFG5lCJ8FkdUgnnQRV:b-n2q31l) ([raw file](https://github.com/getsentry/sentry/blob/7ab07cb97af83795876d9ff71fbb013e54d37a31/src/sentry/static/sentry/app/components/projectHeader/projectSelector.jsx#L63)):*
> ```JSX
>     node.hide().show(0);
>     if (prevState.filter !== this.state.filter) {
>       this.setProjectState();
> ```

since (i think) this is the only place you're doing this, you can probably just do `this.setState(this.getProjectState())` inline here and get rid of the extra method

---

*[src/sentry/static/sentry/app/components/projectHeader/projectSelector.jsx, line 289 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/3944#-KPFFsuaWZ3zFuwYuaXP:-KPFFsuaWZ3zFuwYuaXQ:b5b8wpj) ([raw file](https://github.com/getsentry/sentry/blob/7ab07cb97af83795876d9ff71fbb013e54d37a31/src/sentry/static/sentry/app/components/projectHeader/projectSelector.jsx#L289)):*
> ```JSX
> 
>   render() {
>     let org = this.props.organization;    
> ```

are there extra spaces after the semicolon here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3944#-:-KPFFZyGx73GSuT_sL8Q:b2mmtsp)*

**Comment by ckj** [comment]
Nice! I changed the background over to work off our @blue variable (found in `palette.less`) to make it a little easier on us when we update our color scheme.

Loving these 💅  pushes. Also, +1 for moar keyboard shortcuts.

**Comment by kjlundsgaard** [comment]
image

**Comment by kjlundsgaard** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/sentry/static/sentry/app/components/projectHeader/projectSelector.jsx, line 63 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/3944#-KPFG5lB_0Id9wgHZmPZ:-KPJRyA8WBKLkM-a7OEX:b-ti8mko) ([raw file](https://github.com/getsentry/sentry/blob/7ab07cb97af83795876d9ff71fbb013e54d37a31/src/sentry/static/sentry/app/components/projectHeader/projectSelector.jsx#L63)):*
<details><summary><i>Previously, macqueen (Jess MacQueen) wrote…</i></summary>
> since (i think) this is the only place you're doing this, you can probably just do `this.setState(this.getProjectState())` inline here and get rid of the extra method
</details>
returns an error - changing to use setState whenever filter is changed or dropdown is closed

---

*[src/sentry/static/sentry/app/components/projectHeader/projectSelector.jsx, line 289 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/3944#-KPFFsuaWZ3zFuwYuaXP:-KPFK-NGSiQBs21f9rAG:b-3yjlm3) ([raw file](https://github.com/getsentry/sentry/blob/7ab07cb97af83795876d9ff71fbb013e54d37a31/src/sentry/static/sentry/app/components/projectHeader/projectSelector.jsx#L289)):*
<details><summary><i>Previously, macqueen (Jess MacQueen) wrote…</i></summary>
> are there extra spaces after the semicolon here?
</details>
yep - removing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3944)*

**Comment by macqueen** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/sentry/static/sentry/app/components/projectHeader/projectSelector.jsx, line 98 \[r3\]](https://reviewable.io:443/reviews/getsentry/sentry/3944#-KPJxCuCpqkQZoS64XMW:-KPJxCuD5SJwDA9XhQtK:bwckpwp) ([raw file](https://github.com/getsentry/sentry/blob/b5f3377608e557835d01c37fa88445610428a8b3/src/sentry/static/sentry/app/components/projectHeader/projectSelector.jsx#L98)):*
> ```JSX
>   close() {
>     this.setState({
>       filter: '', 
> ```

trailing space here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3944)*

**Comment by macqueen** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3944)*

**Pull request merged**
