### PR TITLE
perf(assigneeselector): lazy compute assignees

### PR DESCRIPTION
**Pull request by JonasBa**
The Assignee selector precomputes the dropdown list before it needs it, meaning we are precomputing a very large list for large orgs which impacts loading UX. For example in sentry's use case, we are precomputing roughly 200*n where n is the number of assignee selectors the page is rendering.

### CODE REVIEW

**Comment by JonasBa** [comment]
Note that some of the jank has now moved to the click interaction with the dropdown selector.

**Comment by scttcper** [comment]
maybe some of the tests needs findBy?

**Comment by scttcper** [comment]
seems to work well

**Comment by JonasBa** [comment]
Yeah, I'm checking the tests now :)

**Review by scttcper — APPROVED** [review]

**Pull request merged**
