### PR TITLE
Spelling owners sentry dev

### PR DESCRIPTION
**Pull request by jsoref**
This is split from #35947

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Review by evanpurkhiser — APPROVED** [review]
Thank you!!

**Comment by jsoref** [comment]
@evanpurkhiser do I need to do something?

**Comment by jsoref** [comment]
@evanpurkhiser ? 😦

**Comment by evanpurkhiser** [comment]
oh no! Let me get this in for you :-)

**Comment by evanpurkhiser** [comment]
Ah, it looks like all of the comments that you cleaned up are actually out of date and have been removed 😅

Sorry we weren't able to get this in earlier

**Comment by jsoref** [comment]
actually, typos are still present, they've just moved a bit...

**Pull request closed without merging**
