### PR TITLE
feat(project-creation): Link to issue stream after dsn

### PR DESCRIPTION
**Pull request by MaxBittker**
before:
image
after:
image

### CODE REVIEW

**Comment by MaxBittker** [comment]
tagged matt as a reviewer because you asked for this feature

**Comment by EvanPurkhiser** [comment]
Could use some design review from @ckj

**Comment by MaxBittker** [comment]
shhhh  @EvanPurkhiser

**Comment by mattrobenolt** [comment]
Yeah. I mean, I assume this code is fine, but it looks real gross.

**Comment by MaxBittker** [comment]
i'll take another pass on it

**Comment by MaxBittker** [comment]
image

**Comment by MaxBittker** [comment]
screenshot 2017-10-24 14 50 02

**Review by evanpurkhiser — APPROVED** [review]
I still think small might look nicer, but this is good 👍

**Pull request merged**
