### PR TITLE
fix(weekly_reports): resolve the issue of duplicate weekly report emails being sent as much as possible.

### LINKED ISSUE #45470: The weekly reports mail is sent repeatedly 16 times, once every minute
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

23.1.1

### Steps to Reproduce

1、Run `Sentry cron` and `Sentry worker` services
2、`Sentry worker` has three instances

### Expected Result

Receive only one weekly newsletter per week

### Actual Result

Receive 16 Sentry weekly emails every Monday ，Received at one minute intervals，All users within the organization received 16 weekly report emails equally.

image

@Neo-Zhixing  Hi
I suspect it has something to do with this pr, https://github.com/getsentry/sentry/pull/39911, but it is not reproduced in my local development environment and the problem only exists in our production environment. What is the possible cause? Can you give any useful information? Thank you very much!

### PR DESCRIPTION
**Pull request by klboke**
Fix  #45470

@scefali  Hi, Maybe you could help take a look at this issue?
Because the prepare_organization_report method has a retry mechanism.
https://github.com/getsentry/sentry/blob/4919d0befef420c5cdf3f6510652d44398aaef72/src/sentry/tasks/weekly_reports.py#L145-L153

- Then, the prepare_organization_report method is not idempotent. When there are too many subscribers to the Sentry weekly report, such as 300 people, it is likely to fail and trigger retries, resulting in some people receiving multiple weekly report emails. 
- Changing email sending to asynchronous can further reduce the possibility of repeated sending of weekly reports.

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Comment by armenzg** [comment]
@klboke did this fix the issue for you? Should there be some tests that go with this change?

**Comment by klboke** [comment]
@armenzg Hi.

- Yes, I made a similar adjustment in our production environment by changing the default setting of sending weekly report emails to only manually subscribed users. This greatly reduced the number of emails sent and resolved the issue of duplicate emails. Therefore, I believe that this problem is related to the number and time of email sending.
- Do you have any suggestions on how to write test cases? I have tried to reproduce this issue in my local development environment, but it is not easy to reproduce. The problem only occurs when the worker sends an email normally and then is forcibly restarted. Of course, this may be related to my technology stack. I have a limited understanding of Python and I am a Java developer.

**Comment by armenzg** [comment]
> @armenzg Hi.
> 
>     * Yes, I made a similar adjustment in our production environment by changing the default setting of sending weekly report emails to only manually subscribed users. This greatly reduced the number of emails sent and resolved the issue of duplicate emails. Therefore, I believe that this problem is related to the number and time of email sending.
> 
>     * Do you have any suggestions on how to write test cases? I have tried to reproduce this issue in my local development environment, but it is not easy to reproduce. The problem only occurs when the worker sends an email normally and then is forcibly restarted. Of course, this may be related to my technology stack. I have a limited understanding of Python and I am a Java developer.

I am not as familiar with this codebase. I will let others chime in first.

**Comment by armenzg** [comment]
Hi @klboke there's no need to merge the `master` branch since it clears all the CI runs and one of us has to trigger it all again.

/gcbrun

**Review by armenzg — APPROVED** [review]
From looking at the code, this may actually perform better.

Let's see.

**Pull request merged**
