### PR TITLE
feat(docs) Add a docker based api docs builder

### PR DESCRIPTION
**Pull request by markstory**
Add a docker container that will allow us to build API docs in a docker host. The generated tar file will be uploaded to GCS where it can be consumed and integrated into the sentry-docs project.

Docs can be built with

```sh
docker run --rm -v $(pwd):/usr/src sentry:apidocs make build-api-docs
```

Refs #9643

### CODE REVIEW

**Review by mattrobenolt — COMMENTED** [review]
Hmm, so I was more thinking that this wouldn't live within the sentry repo. My thinking was that the Dockerfile itself would just download `master` of sentry to do the build. That way the build is entirely self contained and doesn't rely on `sentry` to be cloned.

It'd probably make more sense to put this into the docs repo, or it's own separate repo just for this.

My plan was that we create this Dockerfile, we build it once, then we push it to the registry, then we just run the image we've pushed.

Lemme know if this doesn't make sense or you think I'm talking crazy.

**Comment by markstory** [comment]
> It'd probably make more sense to put this into the docs repo, or it's own separate repo just for this.

Ok I can move this to sentry-docs and have it download `master`. If it is going to be in the docs repo, do we need to stash files in GCS? The markdown files could be moved into place as part of the script that 'syncs the api docs'.

**Comment by mattrobenolt** [comment]
> If it is going to be in the docs repo, do we need to stash files in GCS?

This strictly depends on how we plan on deploying this. If we run it as a cron, the intention was that the cron would always just to a Google Storage bucket, and this would be entirely disconnected from the docs repo.

The alternative is we sync, and commit the changes automatically, then push back into the repo. We can do that if we can fully automate that with a bot, then yeah, we can skip the middleman.

**Comment by markstory** [comment]
@mattrobenolt I'll find out how cameron would like to pull in the api docs.

**Comment by mattrobenolt** [comment]
Yeah, if it's self contained, someone can just manually run it too weekly or wahtever and commit it. I guess similar to how we sync job postings.

**Comment by markstory** [comment]
@mattrobenolt I'm willing to do that for a while. If it becomes a hassle we can publish content to GCS and pull that content in on deploy.

**Comment by markstory** [comment]
Closing as I'll open another pull request on sentry-docs.

**Pull request closed without merging**
