### PR TITLE
fix(replay): Show a basic error when replays cannot be loaded

### PR DESCRIPTION
**Pull request by ryan953**
There are some examples where a replay transaction doesn't have any attachments, so there are no rrweb events to display. 

Previously there was no guard, so the page would crash with an error like this:
Screen Shot 2022-04-12 at 10 47 58 AM

Now we have a simple error message with Retry button:

Screen Shot 2022-04-12 at 10 50 04 AM

And when the transaction itself cannot be found or loaded we still get the usual 404 message:
Screen Shot 2022-04-12 at 10 35 32 AM

### CODE REVIEW

**Comment by ryan953** [comment]
Current dependencies on/for this PR:
* master
  * **PR #33549** <a href="https://app.graphite.dev/github/pr/getsentry/sentry/33549" target="_blank">Graphite</a>  (this PR)

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/getsentry/sentry/33549?utm_source=stack-comment).

**Comment by billyvg** [comment]
@ryan953 do you know why the second case would occur? If it shows up in the list, why would it 404 for details?

**Review by billyvg — APPROVED** [review]
This is good for now -- in an ideal world, how should we handle these events w/ no replays? Display this error and maybe explain why this would happen (e.g. ad blockers)? Have the backend not list these at all?

**Comment by ryan953** [comment]
> ryan953 do you know why the second case would occur? If it shows up in the list, why would it 404 for details?

The rootReplay is what we see on the list page, and that is being loaded on the details page (we can see the Tags in the right sidebar are from that root object). The issue with the examples I have is that there are no attachments on that rootReplay object, and there should be something. 

So inside `useReplayEvent` we're doing some fetching in parallel:
```
const [event, rrwebEvents, replayEvents] = await Promise.all([
  fetchEvent(),
  fetchRRWebEvents(),
  fetchReplayEvents(),
]);
```
and in this case `event` is not null, but `rrwebEvents` is an empty array :(

**Pull request merged**
