### PR TITLE
add kaspersky lab to browser extension filters

### PR DESCRIPTION
**Pull request by MaxBittker**
@benvinegar this should match, correct?
screenshot 2017-02-21 16 56 04

### CODE REVIEW

**Review by benvinegar — CHANGES_REQUESTED** [review]
> this should match, correct?

Beats me, add a test :)

**Review by benvinegar — CHANGES_REQUESTED** [review]
Add a test with a full Kaspersky URL

**Comment by MaxBittker** [comment]
worried that this regex could be slow on malicious input or just because it's in a hot path

**Comment by PikachuEXE** [comment]
1 failed in Travis :(

**Comment by MaxBittker** [comment]
PikachuEXE it was just a transient failure -.-

**Comment by PikachuEXE** [comment]
@MaxBittker 
How do I know XD

**Comment by MaxBittker** [comment]
@PikachuEXE :P i was just embarrassed the test suite does that is all

**Review by benvinegar — APPROVED** [review]

**Review by benvinegar — CHANGES_REQUESTED** [review]
Scratch that.

**Comment by MaxBittker** [comment]
@benvinegar the problem was that EXTENSION_EXC_VALUES used search and EXTENSION_EXC_SOURCES used match, which only matches the beginning of the string

**Comment by MaxBittker** [comment]
I also want to bring up the fact that `     r'^chrome(?:-extension)?:\/\/',` might be causing problems for people running raven-js on chrome extensions

**Comment by MaxBittker** [comment]
@benvinegar testing this locally, I think we can merge it

**Review by benvinegar — APPROVED** [review]

**Pull request merged**
