### PR TITLE
fix(metrics): Handle a case when parsed_mri is None

### PR DESCRIPTION
**Pull request by udameli**
As it was reported by sentry, there are instances when `parsed_mri` is `None` so reading its properties like `namespace` fails. This PR adds an extra condition to check for that. While we're looking into why `parsed_mri` is evaluated to None, this is a stopgap solution.

Fixes SENTRY-VDC

### CODE REVIEW

**Comment by ahmedetefy** [comment]
Can you please add a test case for this?

**Comment by udameli** [comment]
> Can you please add a test case for this?

I tried writing a test but the challenge is that I don't know what's causing `parsed_mri` to be evaluated to None and I can't reproduce that in the test. I wrote a test but it's going to fail because it doesn't create that None `parsed_mri`. Any ideas how I can enforce a broken custom metric here?

**Comment by wmak** [comment]
@ahmedetefy based on the issue in production, the MRI being parsed looks to be a timestamp so this might also be a bug with `_get_metrics_for_entity` returning invalid ids?

@udameli you can use the python mock library to have `parse_mri` return `None` regardless of the actual metrics so we can test this, feel free to reach out if you have more qs on that

**Comment by udameli** [comment]
> @udameli you can use the python mock library to have `parse_mri` return `None` regardless of the actual metrics so we can test this, feel free to reach out if you have more qs on that

I took a stab at it 👍

**Review by wmak — APPROVED** [review]
lgtm

**Pull request merged**
