### PR TITLE
docs(ui): Add simpler `Next Steps` section in `Flutter` getting started docs

### PR DESCRIPTION
**Pull request by denrase**
Relates to https://github.com/getsentry/sentry-dart/issues/1585

### CODE REVIEW

**Review by ArthurKnaus — APPROVED** [review]
🙌

**Comment by denrase** [comment]
@ArthurKnaus Thank you for the review. Anything else to do here to get this merged?

**Comment by ArthurKnaus** [comment]
Hey @denrase thx again for the contribution and sorry for the delay. It seems there are unrelated linting issues in our master that prevent merging your fork (as it also has those).  Rest assured that I will take care of it in the following weeks.

**Comment by ArthurKnaus** [comment]
@denrase thx again for your contribution. There was still a linting error in your changes.
I fixed it and will merge it.

**Comment by denrase** [comment]
@ArthurKnaus Sorry about that and thank you for looking into this! 🙇

**Pull request merged**
