### PR TITLE
ref(alerts): Update UI

### PR DESCRIPTION
**Pull request by vuluongj20**
**Before ——**
Screenshot 2024-03-13 at 5 22 24 PM
Screenshot 2024-03-13 at 5 23 22 PM

**After ——**
Screenshot 2024-03-13 at 5 22 43 PM
Screenshot 2024-03-13 at 5 23 08 PM

**After, in context ——**
Screenshot 2024-03-13 at 5 24 03 PM

### CODE REVIEW

**Comment by vuluongj20** [comment]
In dark mode:

**Before ——**
Screenshot 2024-03-13 at 5 27 54 PM

**After ——**
Screenshot 2024-03-13 at 5 27 35 PM

**Comment by vuluongj20** [comment]
@getsentry/open-source

**Review by scttcper — APPROVED** [review]
looks like renaming iconColor might take more effort

**Comment by vuluongj20** [comment]
yea was wondering what's going on

**Pull request merged**
