### PR TITLE
ref(appstore-connect): Remove setup steps asking for iTunes credentials [NATIVE-294]

### PR DESCRIPTION
**Pull request by relaxolotl**
This goes the full mile and removes the endpoints, backend code, and all front end code related to the steps that ask for iTunes credentials during the App Store Connect integration setup.

The new setup flow looks like so:

### Existing integration
Screenshot 2021-10-29 at 5 48 44 PM
Screenshot 2021-10-29 at 5 48 51 PM

### New integration
Screenshot 2021-10-29 at 5 50 41 PM
Screenshot 2021-10-29 at 5 51 14 PM

What this does not cover is the actual removal of iTunes credentials from symbol sources. That will come in a separate PR. This does start redacting and erasing those credentials if users are creating or updating their integrations.

related: https://github.com/getsentry/sentry/issues/29531

### CODE REVIEW

**Review by Swatinem — APPROVED** [review]
❤️ I always love to see code being removed ;-)

**Comment by Swatinem** [comment]
Curious to know what https://github.com/ai/size-limit actually measures, since I would expect all the removed code to show up there.

**Comment by priscilawebdev** [comment]
Thanks for doing this @relaxolotl <3 

Some feedback:

I noticed that when updating an existing app store connect repo, the saved app is not selected by default... initialData gets a different appId than the saved one

**Review by priscilawebdev — APPROVED** [review]
tested locally and it looks good to me

**Comment by relaxolotl** [comment]
i think there are concerns about how to deploy this and the impact of this change's deployment. i'll try to get that sorted out tomorrow so that i can merge this without exploding something i haven't taken into account

**Review by flub — APPROVED** [review]
🚀

**Pull request merged**
