### PR TITLE
fix(discover): Removes failing add to dashboard test

### PR DESCRIPTION
**Pull request by edwardgou-sentry**
Removes a failing add to dashboard test. Recreating this test in RTL in another PR

### CODE REVIEW

**Review by priscilawebdev — APPROVED** [review]

**Comment by priscilawebdev** [comment]
@narsaynorath it seems that @edwardgou-sentry is also having tests issues

**Comment by edwardgou-sentry** [comment]
@narsaynorath @priscilawebdev  This test seems to be failing and blocking merge to master at the moment. I'm working on rewriting this test in RTL which will hopefully fix the failure, but this pr is to remove for now to unblock everyone else.

**Review by shruthilayaj — COMMENTED** [review]
Is it jest timeouts?

**Comment by edwardgou-sentry** [comment]
> @edwardgou-sentry I'm afraid writing the test in RTL won't solve the issue. We ran into the same problem last week with RTL tests and had to revert a PR

👍  thanks for the heads up, lets take this on slack to see if we can figure out a solution. will ping you

**Comment by shruthilayaj** [comment]
cc: @JonasBa here's a consistent jest timeout

**Pull request merged**
