### PR TITLE
feat(project-selector): settings link

### PR DESCRIPTION
**Pull request by Chrissy**
bookmark-new

### CODE REVIEW

**Review by lynnagara — CHANGES_REQUESTED** [review]
Spacing is missing in the verison where the project is not bookmarked, otherwise looks good

**Comment by Chrissy** [comment]
@lynnagara 🙏

**Comment by Chrissy** [comment]
alrighty @lynnagara this is better now. thanks for catching that!

**Comment by Chrissy** [comment]
alrighty I think this is *finally* bug free otherwise I'm moving to Montana

**Review by lynnagara — APPROVED** [review]
Looks good, thanks

**Pull request merged**
