### PR TITLE
Show progressbar on stdout

### PR DESCRIPTION
**Pull request by do3cc**
Please be aware this changes the behavior of the progress bar in every invocation.
#2794

### CODE REVIEW

**Comment by do3cc** [comment]
I want to make all tests pass.
I cannot run the local tests.
make test fails with 
```
py.test tests || exit 1
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/do3cc/.dev/sentry_code/lib/python2.7/site-packages/_pytest/main.py", line 80, in wrap_session
INTERNALERROR>     config.do_configure()
INTERNALERROR>   File "/Users/do3cc/.dev/sentry_code/lib/python2.7/site-packages/_pytest/config.py", line 618, in do_configure
INTERNALERROR>     self.hook.pytest_configure(config=self)
INTERNALERROR>   File "/Users/do3cc/.dev/sentry_code/lib/python2.7/site-packages/_pytest/core.py", line 413, in __call__
INTERNALERROR>     return self._docall(methods, kwargs)
INTERNALERROR>   File "/Users/do3cc/.dev/sentry_code/lib/python2.7/site-packages/_pytest/core.py", line 424, in _docall
INTERNALERROR>     res = mc.execute()
INTERNALERROR>   File "/Users/do3cc/.dev/sentry_code/lib/python2.7/site-packages/_pytest/core.py", line 315, in execute
INTERNALERROR>     res = method(**kwargs)
INTERNALERROR>   File "/Users/do3cc/dev/sentry_code/src/sentry/utils/pytest.py", line 124, in pytest_configure
INTERNALERROR>     client.flushdb()
INTERNALERROR>   File "/Users/do3cc/.dev/sentry_code/lib/python2.7/site-packages/redis/client.py", line 652, in flushdb
INTERNALERROR>     return self.execute_command('FLUSHDB')
INTERNALERROR>   File "/Users/do3cc/.dev/sentry_code/lib/python2.7/site-packages/rb/clients.py", line 432, in execute_command
INTERNALERROR>     buf = self._get_command_buffer(host_id, args[0])
INTERNALERROR>   File "/Users/do3cc/.dev/sentry_code/lib/python2.7/site-packages/rb/clients.py", line 322, in _get_command_buffer
INTERNALERROR>     buf = CommandBuffer(host_id, connection, self.auto_batch)
INTERNALERROR>   File "/Users/do3cc/.dev/sentry_code/lib/python2.7/site-packages/rb/clients.py", line 130, in __init__
INTERNALERROR>     connection.connect()
INTERNALERROR>   File "/Users/do3cc/.dev/sentry_code/lib/python2.7/site-packages/redis/connection.py", line 442, in connect
INTERNALERROR>     raise ConnectionError(self._error_message(e))
INTERNALERROR> ConnectionError: Error 61 connecting to localhost:6379. Connection refused.
make: *** [test-python] Error 1
```
Apparently I need to run some local services for the tests to run.
I guess you are reusing Dockerfile.dev somehow?
What is the right way to run the tests locally?

**Comment by dcramer** [comment]
It sounds like Redis isn't running. We definitely dont use Docker in tests, so its likely it wont work there.

**Comment by do3cc** [comment]
This helped, thanks @dcramer

**Comment by do3cc** [comment]
I've added a test case that at least executes the code in question, but:

1. It does not test for stdout vs stderr, that is currently impossible
2. I have no idea what I am doing in the test, because I don't really know django. So please look carefully at the test.

**Comment by mattrobenolt** [comment]
@do3cc awesome! Before I dig in more, can you remove the CHANGES entry? At least because it's in the wrong place. :) It was added under 8.2.1 which was already released.

**Comment by do3cc** [comment]
Sorry, I am used to projects where the latest first chapter of CHANGES is for yet unreleased packages :-)

**Comment by do3cc** [comment]
Hi, what is missing for a merge?

**Comment by mattrobenolt** [comment]
I'm ok with this, but I don't have a strong opinion. If it solves problems for you, I'm +1.

/cc @dcramer @mitsuhiko @tkaemming ?

If nobody objects, I'll merge.

**Comment by tkaemming** [comment]
I don't have a strong opinion here. Since this is used for migrations, cleanup, and repair tasks, it should probably be consistent with wherever those are dumping logs or status information. I don't know what that is off the top of my head.

I'm a little curious what the rationale behind this change is, though…?

**Comment by mattrobenolt** [comment]
@tkaemming See: https://github.com/getsentry/sentry/issues/2794 :)

**Comment by tkaemming** [comment]
Oops, missed that.

No strong opinion here, but seems like it might make more sense just to add an option to disable the progress bar for this case.

**Comment by do3cc** [comment]
I can write an alternative pr with a --quiet option

**Pull request closed without merging**
