### PR TITLE
Breadcrumbs filter

### LINKED ISSUE #3270: Add filter to breadcrumbs
Simple search box (instant search) that filters the list of breadcrumbs. Should search on category, level, message, data. Can go in the header probably.

### PR DESCRIPTION
**Pull request by kjlundsgaard**
Fixes #3270
@getsentry/ui

---

This change is [Reviewable](https://reviewable.io/reviews/getsentry/sentry/3920)

### CODE REVIEW

**Comment by ckj** [comment]
@kjlundsgaard nice! any chance you can post a screenshot here?

**Comment by dcramer** [comment]
percy has screenshots, duh

**Comment by dcramer** [comment]
(though percy says its broken with the search icon)

**Comment by ckj** [comment]
@kjlundsgaard ah, yeah for some reason Firefox doesn't like the positioning. I'm gonna push something real quick that should fix it.

**Comment by kjlundsgaard** [comment]
@ckj thanks! I'm also going to set collapse to true when the search is cleared

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3920#-:-KOvz6ccM5BdcJfx4CcH:b-8zpaal)*

**Comment by ckj** [comment]
@kjlundsgaard Can we get an empty state for when there are no results found? If you can wire up the logic, I can style it up quickly

**Comment by ckj** [comment]
@kjlundsgaard Pushed up some minor tweaks to the empty state. I'm 👍 x 💯. Love how fast this came together.

**Comment by benvinegar** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

*[src/sentry/static/sentry/app/components/events/interfaces/breadcrumbs.jsx, line 136 \[r5\]](https://reviewable.io:443/reviews/getsentry/sentry/3920#-KOxD5HC6rse9MaTE955:-KOxD5HC6rse9MaTE956:b2ttmzw) ([raw file](https://github.com/getsentry/sentry/blob/4e9b00bdbb2745d80ea2ba63c344793c19cf6461/src/sentry/static/sentry/app/components/events/interfaces/breadcrumbs.jsx#L136)):*
> ```JSX
>               (category.toLowerCase().indexOf(queryValue) !== -1) ||
>               (level.toLowerCase().indexOf(queryValue) !== -1);
>     });
> ```

I'd re-write this like this (took a few tries):

```javascript
return crumbs.filter(item => {
  // return true if any of category, message, or level contain queryValue
  return !!['category', 'message', 'level'].find(prop => {
    let propValue = (item[prop] || '').toLowerCase();
    return propValue.includes(queryValue);
  });
});
```

It's a little trickier to understand up front, but it has quite a few less lines/statements. It uses a couple new ES6 tricks:

* `Array.prototype.find`
* `String.prototype.includes`

---

*[src/sentry/static/sentry/app/components/events/interfaces/breadcrumbs.jsx, line 150 \[r5\]](https://reviewable.io:443/reviews/getsentry/sentry/3920#-KOxHsxjpRiXHGUyCkfd:-KOxHsxjpRiXHGUyCkfe:b-yaafnb) ([raw file](https://github.com/getsentry/sentry/blob/4e9b00bdbb2745d80ea2ba63c344793c19cf6461/src/sentry/static/sentry/app/components/events/interfaces/breadcrumbs.jsx#L150)):*
> ```JSX
>       <div className="breadcrumb-filter">
>         <input type="text" className="search-input form-control"
>           placeholder={'Search breadcrumbs...'}
> ```

We should probably mark these as translatable:

```javascript
import {t} from '../locale'; // or wherever it is

...

{t('Search breadcrumbs...')}
```

---

*[src/sentry/static/sentry/app/components/events/interfaces/breadcrumbs.jsx, line 195 \[r5\]](https://reviewable.io:443/reviews/getsentry/sentry/3920#-KOxJu6MEuHFRO8yrOR0:-KOxJu6MEuHFRO8yrOR1:bj53ac0) ([raw file](https://github.com/getsentry/sentry/blob/4e9b00bdbb2745d80ea2ba63c344793c19cf6461/src/sentry/static/sentry/app/components/events/interfaces/breadcrumbs.jsx#L195)):*
> ```JSX
>     if (queryValue) {
>       filtered = this.filterCrumbs(filtered, queryValue);
>     }
> ```

I'd call `toLowerCase` after the `if` statement. It's a little safer (if `queryValue` is not a string this breaks), plus you can use this neato ES6 [destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) declaration:

```javascript
let {queryValue} = this.state;
let filtered = queryValue
  ? this.filterCrumbs(all, queryValue.toLowerCase())
  : all;
```

---

*[tests/js/spec/components/events/interfaces/breadcrumbComponents/breadcrumbs.spec.jsx, line 7 \[r5\]](https://reviewable.io:443/reviews/getsentry/sentry/3920#-KOxL9XlrM1baXRlE9h5:-KOxL9Xm7aVlM6rxxDxe:b9nu5u7) ([raw file](https://github.com/getsentry/sentry/blob/4e9b00bdbb2745d80ea2ba63c344793c19cf6461/tests/js/spec/components/events/interfaces/breadcrumbComponents/breadcrumbs.spec.jsx#L7)):*
> ```JSX
> 
> describe('BreadcrumbsInterface', function() {
>   const PROPS =  {
> ```

Extra space here.

---

*[tests/js/spec/components/events/interfaces/breadcrumbComponents/breadcrumbs.spec.jsx, line 68 \[r5\]](https://reviewable.io:443/reviews/getsentry/sentry/3920#-KOxLJE81sPQ3RguRkN5:-KOxLJE81sPQ3RguRkN6:b-iqi2qd) ([raw file](https://github.com/getsentry/sentry/blob/4e9b00bdbb2745d80ea2ba63c344793c19cf6461/tests/js/spec/components/events/interfaces/breadcrumbComponents/breadcrumbs.spec.jsx#L68)):*
> ```JSX
>       wrapper.setState({queryValue: 'sup'});
>       expect(wrapper.find(Breadcrumb)).to.have.length(10);
>       wrapper.setState({queryValue: 'sup', collapsed: false});
> ```

Woot, Enzyme!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3920)*

**Comment by benvinegar** [comment]
Reviewed 1 of 3 files at r1, 1 of 2 files at r5.
Review status: 2 of 3 files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3920)*

**Comment by kjlundsgaard** [comment]
Review status: 2 of 3 files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

*[src/sentry/static/sentry/app/components/events/interfaces/breadcrumbs.jsx, line 150 \[r5\]](https://reviewable.io:443/reviews/getsentry/sentry/3920#-KOxHsxjpRiXHGUyCkfd:-KOzlhZRXhjdODNp3jkV:b-iggp1p) ([raw file](https://github.com/getsentry/sentry/blob/4e9b00bdbb2745d80ea2ba63c344793c19cf6461/src/sentry/static/sentry/app/components/events/interfaces/breadcrumbs.jsx#L150)):*
<details><summary><i>Previously, benvinegar (Ben Vinegar) wrote…</i></summary>
> We should probably mark these as translatable:
> 
> ```javascript
> import {t} from '../locale'; // or wherever it is
> 
> ...
> 
> {t('Search breadcrumbs...')}
> ```
</details>
Should I also do this for 
```javascript
{'Sorry, no breadcrumbs match your search query.'}
```
So that it becomes
```javascript
{t('Sorry, no breadcrumbs match your search query.')}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3920)*

**Comment by benvinegar** [comment]
Review status: 2 of 3 files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

*[src/sentry/static/sentry/app/components/events/interfaces/breadcrumbs.jsx, line 150 \[r5\]](https://reviewable.io:443/reviews/getsentry/sentry/3920#-KOxHsxjpRiXHGUyCkfd:-KOzqdkR9TEYIoLyMLOm:bb77uci) ([raw file](https://github.com/getsentry/sentry/blob/4e9b00bdbb2745d80ea2ba63c344793c19cf6461/src/sentry/static/sentry/app/components/events/interfaces/breadcrumbs.jsx#L150)):*
<details><summary><i>Previously, kjlundsgaard (Katie Lundsgaard) wrote…</i></summary>
> Should I also do this for 
> ```javascript
> {'Sorry, no breadcrumbs match your search query.'}
> ```
> So that it becomes
> ```javascript
> {t('Sorry, no breadcrumbs match your search query.')}
> ```
</details>
Yep!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3920)*

**Comment by benvinegar** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3920)*

**Pull request merged**
