### PR TITLE
add api rewrite URL too

### PR DESCRIPTION
**Pull request by arthurzenika**

### CODE REVIEW

**Comment by mattrobenolt** [comment]
Hmmmmmm, I'd be more in favor here of removing all of this. These instructions are pretty wrong at this point and we won't work with a subpath, I'm 99% sure. And nobody is working to fix it.

**Comment by arthurlogilab** [comment]
Fair enough, we ended up giving up on getting sentry to work in a subpath.

**Comment by mattrobenolt** [comment]
Yeah,  definitely do not officially support this method. I thought out docs mentioned that. I'll see if we're ok just removing these instructions, since I think they're lacking and inaccurate at best, and haven't been looked at in years.

**Comment by arthurlogilab** [comment]
yep, you can get the django part partly working, but the react part is impossible unless changing the code is allowed. Maybe replace that documentation with a FAQ and links to the tickets that need work on this issue... 

I think leaving historical hacks with a big red warning saying "this will not work with version X of sentry" can prevent some folks from trying out recipes they find in various places on the internet (stackoverflow, but also issues on github, etc.). In these kinds of setups if feels like you're almost there at every step.

Also, clarifying where the "Root URL -  The root web address which is used to communicate with the Sentry backend." fits in to all this, would be helpful. This Root URL mislead us to think that this problem was now solved in sentry.

**Comment by dcramer** [comment]
Do our docs suggest we support a subpath? We've always stated that it only works on a root path and we recommend using a domain/subdomain.

**Comment by mattrobenolt** [comment]
Nah, we explicitly say the opposite: https://docs.sentry.io/server/nginx/#hosting-sentry-at-a-subpath

But, to me, why do we even have these instructions at all, if we're flat out saying they likely don't work? I feel like we should just remove them, and if we decide to attempt to make this work again, it likely wouldn't require these hacks anyways.

**Comment by dcramer** [comment]
@mattrobenolt agreed -- it was probably a community contribution and we should just remove it

**Comment by mattrobenolt** [comment]
Cool. Will do that instead of this. Sorry for the confusion @arthurlogilab.

Out of curiosity, what is your reasoning for wanting to do this? Acquiring a sub domain and managing that, even getting a TLS certificate for it, these days is super trivial. So not sure if many of the reasons for wanting to support a subpath are even applicable anymore.

**Comment by arthurlogilab** [comment]
@mattrobenolt there are still environments out there where corporate administration makes it *really* hard to obtain domains, certificates, etc. (in this example, the existing domain took 4 months to obtain). I understand (and frequently work with) environments where a domain and associated TLS is a click away, please don't forget the diversity of the tech world that surrounds you (and again, I understand that you cannot focus on this, open source, etc.).

**Pull request closed without merging**
