### PR TITLE
feat(sdk_crash_detection): Add option to ignore exception mechanism type

### PR DESCRIPTION
**Pull request by krystofwoldrich**
This PR adds a new option to SDK Crash Detector which allow excluding selected mechanism types.

This PR adds mechanism type `console` to be excluded for the RN SDK. 

Mechanism type `console` could in theory contain some actual SDK crashes, should user choose to use the `captureConsoleIntegration` and would log the error/crash caused by the SDK.

But we are not able to identify these cases. We could mitigate this by excluding SyntheticExceptions, but this is more generic than excluding `console` thus potentially leads to even more missed crashes.

---

<details><summary>Details about capturing synthetic exceptions should we choose that</summary>
<p>

We can't use ignore function name because SyntheticExceptions are created directly in the SDK code without wrapper function.
- https://github.com/getsentry/sentry-javascript/blob/dafd51054d8b2ab2030fa0b16ad0fd70493b6e08/packages/utils/src/eventbuilder.ts#L117
- https://github.com/getsentry/sentry-javascript/blob/dafd51054d8b2ab2030fa0b16ad0fd70493b6e08/packages/utils/src/eventbuilder.ts#L125

Secondly the top frame is popped in the SDK, to remove the `captureException` from from the stack.
- `stripSentryFramesAndReverse` https://github.com/getsentry/sentry-javascript/blob/dafd51054d8b2ab2030fa0b16ad0fd70493b6e08/packages/utils/src/stacktrace.ts#L80
- `captureException` https://github.com/getsentry/sentry-javascript/blob/dafd51054d8b2ab2030fa0b16ad0fd70493b6e08/packages/core/src/scope.ts#L540
- `captureMessage` https://github.com/getsentry/sentry-javascript/blob/dafd51054d8b2ab2030fa0b16ad0fd70493b6e08/packages/core/src/scope.ts#L513

</p>
</details> 

---

This fix should significantly reduce (maybe completely stop) false reports of https://sentry.sentry.io/issues/5695469611

### CODE REVIEW

**Review by philipphofmann — COMMENTED** [review]
Some SDK crashes might actually have synthetic true. I would rather make this specific per platform. You know for sure that's the case on RN, so I think we should add a flag `report_synthetic_errors` similar to `report_fatal_errors`, set it to `true` per default and only set it to `false` for RN. https://github.com/getsentry/sentry/blob/998ed0e3a90405d6eda9cd2eb845321766bf4ee3/src/sentry/utils/sdk_crashes/sdk_crash_detection_config.py#L49

I would add some of explanation you added in the PR description to the RN config explaining why you want to set this field to false, so we don't have to go back to the PR and find out, but instead have the info directly in the code.

**Comment by krystofwoldrich** [comment]
I'm not opposed to adding this an a SDK crash detection option, but just to capture the complete picture, what would be the example of SDK crash with synthetic `true`?

**Comment by philipphofmann** [comment]
@krystofwoldrich, I would rather overreport and have some false positives than underreport and not see SDK crashes in Sentry. If an SDK detects it gets plenty of wrong crashes with synthetic true as on RN, it can always disable it.

**Review by philipphofmann — COMMENTED** [review]
Looking great. Please add some tests.

**Review by philipphofmann — APPROVED** [review]
LGTM, but the tests are failing.

**Comment by krystofwoldrich** [comment]
Based on error messages, the failed tests seems unrelated.

**Pull request merged**
