### PR TITLE
ref: Dont evaluate oauth params at runtime for Slack

### PR DESCRIPTION
**Pull request by dcramer**

### CODE REVIEW

**Comment by getsentry-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Changes require @getsentry/security sign-off</td>
    </tr>
  </tbody>
</table>

### Security concerns found

- src/sentry/integrations/oauth.py


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by dcramer** [comment]
Given options load from a network service, it makes sense that we shouldn't evaluate them at runtime. (it also throws random errors/etc elsewhere, and may be the cause of https://github.com/getsentry/sentry-plugins/pull/254#issuecomment-333670764)

**Comment by dcramer** [comment]
Might be a similar concern with the analytics backends @mattrobenolt

**Comment by mattrobenolt** [comment]
> Might be a similar concern with the analytics backends @mattrobenolt

Nah, that's chill.

**Comment by dcramer** [comment]
shipping this as its breaking the build rn

**Pull request merged**
