### PR TITLE
ref(ui): Remove crufty global exports

### PR DESCRIPTION
**Pull request by evanpurkhiser**
These are from a time when getsentry could not import sentry modules
itself and we needed to explicitly export things from sentry, which we
would do here.

 - Removes window globals that are NOT used in sentry-plugins OR in
   django HTML templates

 - Removes many `SentryApp` exports that are not used in sentry-plugins
   OR django HTML templates.

 - Comments existing items to describe where they are used

### CODE REVIEW

**Review by markstory — COMMENTED** [review]
Looks good. Do you think the acceptance tests give enough coverage on this kind of change? Should this be checked on staging before merging?

**Comment by billyvg** [comment]
Have you tested on getsentry?

**Comment by EvanPurkhiser** [comment]
> Have you tested on getsentry?

Yup, getsentry actually doesn't use any of this

**Comment by EvanPurkhiser** [comment]
> Looks good. Do you think the acceptance tests give enough coverage on this kind of change? Should this be checked on staging before merging?

Yes I think so. The plugin JS code is also super minimal.

The only case where we may break something here is if 3rd party plugins were using any of these exports.

**Review by billyvg — APPROVED** [review]

**Pull request merged**
