### PR TITLE
Replace rewrite statement in nginx sample

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by mattrobenolt** [comment]
So this changes behavior from the version we have.

What’s the goal here?

**Comment by J0WI** [comment]
The goal is to get rid of expensive `rewrite` and `if` statements in the config.
There are also `303`, `307` and `308`, but I think `301` is what you want here, isn't it?

**Comment by mattrobenolt** [comment]
We do want a 301, but I think "expensive" is relative here. I don't think it's worth changing the logic though.

What we'd want is to only redirect on a GET since a POST can't be redirected. I know you can with the `307` and `308` in theory, but our SDKs wouldn't respect this and would just fail instead.

**Comment by J0WI** [comment]
Does your SDK respect RFC 7231/6.4.2?

**Comment by mattrobenolt** [comment]
If it is a GET request, yes, but not for POST since you can't redirect a POST with a 301/302.

**Comment by J0WI** [comment]
Can we use the example provided here somehow?
https://www.nginx.com/resources/wiki/start/topics/depth/ifisevil/

**Comment by mattrobenolt** [comment]
No. If you read, the use of if isn’t to be avoided. They are pointing out that `if` doesn’t work as you’d always expect in a normal programming language because nginx config files are declarative. How we’re using is literally in the documentation you just linked to saying:

> There are cases where you simply cannot avoid using an if, for example, if you need to test a variable which has no equivalent directive.

The only change we can make here without changing behavior is to change the `rewrite` to a `return`, but there’s not really a strong reason to change it.

I’m going to close this out since there’s not anything here worth changing. Performance of `return` vs `rewrite` here is not anything yiu should be concerned about, and the `if` usage here isn’t unsafe.

**Pull request closed without merging**
