### PR TITLE
fix(team-roles): Padding matters

### PR DESCRIPTION
**Pull request by leedongwei**
Adjust padding to the right of the action button on PanelHeader.

### Before
Screen Shot 2022-06-07 at 10 16 00 PM

### After
Screen Shot 2022-06-07 at 10 15 46 PM

### CODE REVIEW

**Review by nhsiehgit — APPROVED** [review]

**Comment by leedongwei** [comment]
Github: "Nice 1-line change, let's make sure the entire company is aware of it."

**Review by billyvg — APPROVED** [review]
Great work @leedongwei

**Review by dashed — APPROVED** [review]
wow you're coding?!

**Review by jennmueng — APPROVED** [review]
perfectly aligned

**Review by priscilawebdev — APPROVED** [review]
Great PR Title!

**Review by evanpurkhiser — APPROVED** [review]

**Pull request merged**
