### PR TITLE
fix: Allow empty stacktraces

### PR DESCRIPTION
**Pull request by untitaker**
Also fix some unrelated null issues

This reverts commit 2b9fb52ed9b3f87577bdcf8a11008f7baa98cc3e.

fix SENTRY-89B
fix JAVASCRIPT-4M4
fix SENTRY-89C

#sync-getsentry

### CODE REVIEW

**Comment by untitaker** [comment]
I verified locally that the "there was 1 error" is because of a too old timestamp.

**Comment by mitsuhiko** [comment]
Looks good but there are some failures still.

**Comment by mitsuhiko** [comment]
lgtm. Did we check against incoming data from kafka?

**Comment by untitaker** [comment]
ah, need ot check

**Review by jan-auer — APPROVED** [review]

**Comment by untitaker** [comment]
kafka looks good

**Comment by mitsuhiko** [comment]
Cool. Let's get it out in the morning then.

**Pull request merged**
