### PR TITLE
fix(metric-alerts): Omit query when redirecting to metric alert creation

### PR DESCRIPTION
**Pull request by gggritso**
Closes PERF-1973. In short, we don't want people to create metric alerts that fall down to indexed events. Since the "Create Alert" button takes an `eventView`, it might have an event view that uses indexed events. We don't want to help people create this, so we're just going to omit the query when redirecting.

### CODE REVIEW

**Review by k-fish — COMMENTED** [review]
Code-wise this is fine, I think product-wise it's not a great flow to have conditions dropped when moving towards an alert since it's not consistent visually and is prob not an expected flow, we also need to remove the hybrid banner on the metrics alert page.

Can you do a gif or a couple screenshots of creating an alert with this flow (with a query being removed)?

**Comment by gggritso** [comment]
@k-fish definitely! Right now, the flow is already a little busted. You can see that the form chooses the wrong dataset, and doesn't properly fill in the details:

https://user-images.githubusercontent.com/989898/218196616-6d56b3d7-e35a-4248-9a28-30d1f4221e56.mov

Here's with the change, where it also drops the query:

https://user-images.githubusercontent.com/989898/218196645-88ec4908-4d88-42a9-95fe-55f97c4c4094.mov

I don't really love it either to be honest. I'd prefer to fix this flow, keep the query, and highlight the ineligible fields in red 🤔

**Review by scttcper — APPROVED** [review]
create alert button probably needs a refresh

**Comment by gggritso** [comment]
Closing this! We won't strip things. We'll continue highlighting incompatible things in red, and I'll go around and fix the "Create Alert" buttons if any are busted (some are busted)

**Pull request closed without merging**
