### PR TITLE
Show culprit as a subtitle even for events of type "default"

### PR DESCRIPTION
**Pull request by mdamien**
When I was sending message via `.captureMessage(...` and adding a culprit in the data, it wouldn't show as a subtitle.

Also de-duplicate because the code for `getTitle` :+1: 

cc @benvinegar @mitsuhiko @dcramer

### CODE REVIEW

**Comment by benvinegar** [comment]
Are we guaranteed to always have a culprit?

**Comment by mdamien** [comment]
No, by default there is no culprit (`culprit == ''`) when you use `.captureMessage(..`. I took this into account by re-using the exact same structure than before (using a simple span without margin) if there is no subtitle/culprit to show

**Comment by benvinegar** [comment]
Oh, oops – I totally missed the `else` block (I'm bad at programming).

Okay, looks pretty cool. Let me just poke at it and I think we can merge it pretty soon.

**Comment by dcramer** [comment]
@getsentry/ui

**Comment by dcramer** [comment]
-1

I'm not against adding 'culprit' back in somewhere, but this changes all events to once again look identical, and one of our goals here was to be able to specialize events so that things were easier to comprehend.

**Comment by dcramer** [comment]
I'm going to toy with UI here and see what it looks like getting culprit into subinfo

**Comment by dcramer** [comment]
Might be eating my own words here, as it's possible I was forgetting which code path was which here.

**Comment by dcramer** [comment]
This was merged (with some tweaks) so that culprit is available as the subtext on default events.

**Pull request closed without merging**
