### PR TITLE
Add platform specific time-to-process for cocoa/javascript

### PR DESCRIPTION
**Pull request by dcramer**
This change is [Reviewable](https://reviewable.io/reviews/getsentry/sentry/4166)

### CODE REVIEW

**Comment by mattrobenolt** [comment]
Couldn't we use platform as a tag here instead? Seems that be better.

**Comment by dcramer** [comment]
There is no platform tag.

**Comment by mattrobenolt** [comment]
Sorry, to be more specific:

```python
if platform in ('cocoa', 'javascript'):
    metrics.timing('events.time-to-process', ttp, tags={'platform': platform})
else:
    metrics.timing('events.time-to-process', ttp, tags={'platform': 'other'})
```

Would make it a bit easier to deal with.

**Comment by mattrobenolt** [comment]
Or I guess `instance=...` I'm not sure the different tbh.

**Comment by mattrobenolt** [comment]
I guess `instance` just sets a tag labeled `instance`. But for the statsd backend, it ends up being used for the key name. So seems more suitable than a `platform` tag.

**Review by mattrobenolt — APPROVED** [review]
:+1:

**Pull request merged**
