### PR TITLE
django 1.9 SQL audit

### PR DESCRIPTION
**Pull request by joshuarli**
This is `py3/django-sql-checker` but starting off with neater git history because I got annoyed at myself. rebases >>>>> merges.

**EDIT:** This is now much more correct than the old branch, which was lying about test function names because we only logged sql at the test case class level. Also, because it's using a pytest fixture we get new suspect SQL on, for example, `tests/sentry/api/endpoints/test_shared_group_details.py` which is using APITestCase, a class we didn't add the sql stuff to originally.

It's based on https://github.com/getsentry/sentry/pull/15399 since we need to be on Django 1.9 in order to see querysets that were translated to literal `= (SELECT`, meaning it's potentially not what we want since it would have been implicitly converted to `IN` in 1.8.

### CODE REVIEW

**Comment by joshuarli** [comment]
er, the 2nd "add back snuba tests that i accidentally removed" should be "pytest fail traceback doesn't have test path, so print it", but not really worth force pushing over with an amend

**Comment by joshuarli** [comment]
Rebasing against latest https://github.com/getsentry/sentry/pull/15399.

**Comment by joshuarli** [comment]
Nice, so with dan's fixes ported over, ci for aac1cce looks good (the remaining suspect SQLs are false positives).

Just need to finish SQL audit for getsentry now, taking into consideration all connections as well so we can test billing SQL.

**Comment by wedamija** [comment]
Closing this since we've fixed all the broken queries on master. There are some false positives here that we can ignore.

**Pull request closed without merging**
