### PR TITLE
feat(eventDetails): link to release from event release tag

### PR DESCRIPTION
**Pull request by MaxBittker**
image

^this icon is the ( i ) info now

i click this all the time when debugging people's sourcemaps and it annoys me that it doesn't go to the release. 
(the blue text still makes a search, but now there's a nice way to go to the release details)

### CODE REVIEW

**Comment by lynnagara** [comment]
Probably more to do with the hovercard component itself rather than your changes but I've just noticed that the text is not contained within the container, and the avatars are not spaced evenly.

screen shot 2018-03-28 at 2 54 13 pm

**Comment by MaxBittker** [comment]
uhoh

**Comment by EvanPurkhiser** [comment]
I'll fix these things. I can take this over @MaxBittker

**Comment by EvanPurkhiser** [comment]
@lynnagara I fixed avatar spacing here https://github.com/getsentry/sentry/pull/7823/files#diff-e7a042b6f307277fa8be0f5e5c9a5610L161

**Review by billyvg — APPROVED** [review]
design nit: icon seems a bit too dark/bold compared to the text around it, I think it could use a bit more left pad?

**Comment by MaxBittker** [comment]
good point, fixing

**Pull request merged**
