### PR TITLE
fix(de-canadification): colour to color

### PR DESCRIPTION
**Pull request by doralchan**
🇨🇦   to  🇺🇸

### CODE REVIEW

**Review by dashed — DISMISSED** [review]
I reject this.

**Review by silent1mezzo — APPROVED** [review]
I don't like this but I accept this.

**Review by dashed — APPROVED** [review]
🇨🇦 🇨🇦 🇨🇦 🇨🇦

**Review by Zylphrex — APPROVED** [review]
I disapprove of this, but I will reluctantly approve

**Pull request merged**
