### PR TITLE
chore: Update logo for dark or light theme

### PR DESCRIPTION
**Pull request by mattjohnsonpint**
GitHub allow you to [set a theme](https://github.com/settings/appearance), which come in both dark and light flavors.  

Sentry's black logo looks horrible on a dark theme, and "pixels matter".  This is the current state, on a dark theme:

image
 
This PR changes the logo to use the purple Sentry logo, which is readable on both white and black backgrounds.

image
image

Note: The first draft of this PR used a media query to select either the white logo for a dark theme, or a dark logo for a light theme. However, it was pointed out to me that some repos render their readme files on package manager sites, and most of those don't change their background correctly for OS theme. Thus switching to a white logo when the OS was set to dark mode would give a white-on-white invisible logo.  Since this readme is published to PyPi [here](https://pypi.org/project/sentry/), it makes sense to use the purple logo.

### CODE REVIEW

**Comment by mattjohnsonpint** [comment]
Some discussion on this https://github.com/getsentry/sentry-electron/pull/479 - apparently this approach doesn't work best due to how other package registries render the readme.  Going to try another approach.

**Comment by mwarkentin** [comment]
Went down a bit of a rabbit hole on this one previously: https://github.com/getsentry/sentry/pull/33799

**Review by taylangocmen — APPROVED** [review]
Thanks

**Comment by mwarkentin** [comment]
@mattjohnsonpint Looks like there's a new way to support both light/dark mode now: https://github.blog/changelog/2022-05-19-specify-theme-context-for-images-in-markdown-beta/

Not sure if that would be handled better by downstream repositories or not.

**Comment by mattjohnsonpint** [comment]
@mwarkentin  - That was the approach used in [my first draft](https://github.com/getsentry/sentry/pull/34229/commits/28322f7d7a1825a8d111c6b804b7803fac5caf19).  It works great when the readme is rendered on GitHub.  Unfortunately, most readme files also make their way to package managers and software repositories (PyPi, NPM, Packagist, NuGet, etc.) and very few of those sites render their own background according to the user's theme preferences.  For example, [this project's readme on PyPi](https://pypi.org/project/sentry/)) is always rendered on a white background, regardless of theme settings.  If you happen to set your OS for dark theme, then the Sentry logo would render as white by picking up the theme preference, and it would be invisible on the white background.

Hence, why I updated this PR to just use the purple logo.

**Pull request merged**
