### PR TITLE
chore: Remove acceptance tests with no interactions

### PR DESCRIPTION
**Pull request by markstory**
These tests were primarily used to collect screenshots and have no meaningful interactions with the application. Since we aren't comparing screenshots in a way that is meaningful anymore these tests only add entropy to our build status and increase CI time. If we feel these tests are still valuable perhaps they can be updated to do more than just take pictures that are never viewed.

### CODE REVIEW

**Review by priscilawebdev — APPROVED** [review]
imo it makes sense

**Comment by malwilley** [comment]
@markstory  FYI you _can_ still run these with the `Trigger: Visual Snapshot` label, which I have found helpful in some situations. [Here's a PR](https://github.com/getsentry/sentry/pull/46476#discussion_r1151271548) where I added that and it helped find a regression.

Just wanted to add a voice from someone who does find value in these snapshots still.

**Comment by priscilawebdev** [comment]
@malwilley I understand your point but I think that many folks won't even remember that we can manually trigger the visual snapshots.

Regarding the snapshots you are talking about, they are not present in this PR, example https://github.com/getsentry/sentry/blob/903346f48a30b1dca0c1862a2b4e1e612786bcf3/tests/acceptance/test_issue_details.py#L185-L218

but in any case, I don't think we need an acceptance test for them but only Jest + RTL

**Comment by markstory** [comment]
> FYI you can still run these with the Trigger: Visual Snapshot label, which I have found helpful in some situations. 

:+1: I'm good with keeping the tests around if folks are still getting value out of them and using the results they can create.

**Comment by malwilley** [comment]
I was just pointing out that there is some amount of value left in these tests -  that value may or may not be outweighed by how much longer the acceptance tests take to run, so I don't want to block this if most people want them gone.

Perhaps a separate discussion, but IMO these acceptance tests do have value if we add some simple checks for the loaded content on the page. I don't think there are any CI checks right now that will block a build when some pages break completely (i.e. someone changes an endpoint URL and now the replays list page doesn't load).

**Comment by armenzg** [comment]
Would any checks on `master` fail?

**Pull request closed without merging**
