### PR TITLE
Update docs to reflect changes in email settings

### PR DESCRIPTION
**Pull request by mattrobenolt**
See GH-2799

Changes proposed in this pull request:
- Updating docs to reflect reality.

@getsentry/infrastructure

### CODE REVIEW

**Comment by tkaemming** [comment]
:+1: 

Should this also mention the setup wizard?

**Comment by mattrobenolt** [comment]
> Should this also mention the setup wizard?

I just realized that we also have docs under config.rst, which mentions setup wizard. I'm going to add stuff there as well.

**Comment by mattrobenolt** [comment]
@ted wanna take another quick looksie? I added a bunch.

**Comment by tkaemming** [comment]
This generally makes sense, although I do wonder how many people will blow right past the install wizard bit and just copy/paste into the configuration file anyway.

:+1:

**Comment by mattrobenolt** [comment]
> although I do wonder how many people will blow right past the install wizard bit and just copy/paste into the configuration file anyway.

The `config.yml` template already spits out these exact same values commented out. So we'll see!

**Pull request merged**
