### PR TITLE
Implement react-native + electron filename parsing on server

### PR DESCRIPTION
**Pull request by dcramer**
@getsentry/javascript

---

This change is [Reviewable](https://reviewable.io/reviews/getsentry/sentry/4090)

### CODE REVIEW

**Comment by dcramer** [comment]
I'm envisioning a world where we combine rules + inbound data filters and just create a ton of built-in behavior (like this) that could be opt-in/opt-out.

Until then, I dont think this will break anything. Thoughts?

**Comment by dcramer** [comment]
I need a few Electron examples to confirm, but if its all *.app/Contents/ we can alternatively match that.

**Comment by benvinegar** [comment]
We should hold off on this until we know what offline app paths look like on Android, Windows, etc.

**Comment by dcramer** [comment]
idk how i completely butchered this branch, but will fix

**Review by arusakov — APPROVED** [review]
Looks good! Thank you for Electron support.

**Comment by dcramer** [comment]
just a note, need to fix the regexp here yet, but I think we should get this finished up as it greatly simplifies some experiences.

**Comment by dcramer** [comment]
@mattrobenolt would you mind taking ownership of this and getting it in?

**Pull request closed without merging**
