### PR TITLE
chore(react): Bump react & react-dom to version 16.14.0

### PR DESCRIPTION
**Pull request by priscilawebdev**
Bump react & react-dom to version 16.14.0

We are currently experiencing the same error reported here https://github.com/facebook/react/issues/20031 and we will have to wait for a solution

### CODE REVIEW

**Comment by billyvg** [comment]
@priscilawebdev We can still upgrade to 16.14, we just can't rely on JSX being in context w/o importing React

**Comment by priscilawebdev** [comment]
@billyvg you are right...everything works out of the box (if we don't remove the React import)

**Review by markstory — APPROVED** [review]
This is a good first step. We can revisit the import drop when there is a solution for key in prop spreading.

**Review by billyvg — APPROVED** [review]

**Comment by morlay** [comment]
Waiting for https://github.com/emotion-js/emotion/pull/1970 merged, when to switch to `jsx-runtime`.

or putting `key` prop before `{...spread}`

**Comment by priscilawebdev** [comment]
Thanks for the heads-up @morlay :) I prefer to wait until the PR [emotion-js/emotion#1970](https://github.com/emotion-js/emotion/pull/1970)  is merged

**Pull request merged**
