### PR TITLE
fix(dashboard): Renaming Issue widget fields

### PR DESCRIPTION
**Pull request by edwardgou-sentry**
**Renamed** 
- count to events
- lifetimeCount to lifetimeEvents
- userCount to users
- lifetimeUserCount to lifetimeUsers

**Added a `fieldHeaderMap` prop to `SimpleTableChart` to allow custom column headers**

~~todo: pr to update already saved fields to use new names~~
**Associated PR for `0268_rename_issue_widget_query_fields` migration to map saved issue fields to renamed value: https://github.com/getsentry/sentry/pull/31352**

image
image

### CODE REVIEW

**Comment by edwardgou-sentry** [comment]
Drafting for now, need to make some more changes to headers

**Comment by edwardgou-sentry** [comment]
cc @jas-kas

**Comment by edwardgou-sentry** [comment]
Moved migration to this pr: https://github.com/getsentry/sentry/pull/31352

**Review by wedamija — COMMENTED** [review]
Is this code backwards compatible? As in, will this code work ok if the migration hasn't run yet? Or will the existing code work if the migration is run before this deploys?

**Comment by edwardgou-sentry** [comment]
> Is this code backwards compatible? As in, will this code work ok if the migration hasn't run yet? Or will the existing code work if the migration is run before this deploys?

Updated to temporarily allow backwards compatibility with old field names. We'll create a PR to undo this after running the migration and confirming no issues!

**Review by narsaynorath — APPROVED** [review]
Looks good to me. I tested its backward compatibility and the table shows the same without the migration and looks as expected when making new widgets.

One thing I noticed is that old issue widgets have their count, lifetimeCount, userCount, and lifetimeUserCount fields as `tag`s but I feel like this is fine if the migration gets applied shortly after.

Screen Shot 2022-01-25 at 4 03 33 PM

**Pull request merged**
