### PR TITLE
Use Travis's Trusty environment.

### PR DESCRIPTION
**Pull request by JTCunning**

### CODE REVIEW

**Comment by getsentry-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Changes to build requirements</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Review by mitsuhiko — APPROVED** [review]
what can go wrong

**Comment by benvinegar** [comment]
This job fails: https://travis-ci.org/getsentry/sentry/jobs/258336869

**Comment by markstory** [comment]
This was done in 24bba58060c

**Pull request closed without merging**
