### PR TITLE
feat(ui): Use new Org General Settings form

### PR DESCRIPTION
**Pull request by billyvg**
Use new organization general settings form in old org settings shell

### CODE REVIEW

**Comment by getsentry-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by MaxBittker** [comment]
image

is this overlap of the indicators a problem?

**Comment by MaxBittker** [comment]
this is cool, and im pleasantly surprised it works so cleanly as a drop-in. will be a lot more traffic than we've been giving the form internally though, so lets be watchful if we ship this.

**Review by MaxBittker — APPROVED** [review]
🆕

**Comment by billyvg** [comment]
Not concerned about overlap, I will double check behavior though (I want to make sure switch should switch back to "off")

**Pull request merged**
