### PR TITLE
ref(metrics-indexer): Change bulk_record, record signatures

### PR DESCRIPTION
**Pull request by MeredithAnya**
**context**
We are changing the implementation of metric indexer. This is due to the change to the schema that was added in https://github.com/getsentry/sentry/pull/32540. The new schema was the first step. The rest of the steps are outlined below.

**Steps**
1. Add a new indexer schema - added in https://github.com/getsentry/sentry/pull/32540
2. Add new indexer interface - going to be added in https://github.com/getsentry/sentry/pull/32780
3. Update the current implementation to match the new signatures:
    1. Update `bulk_record` and `record` signatures since `bulk_record` is only in the indexer, and `record` is only used in tests. 
    2. Update `resolve` and `reverse_resolve`
4. Switch the implementation

It should be fine to do step 2 and 3 in parallel since adding the new signatures shouldn't change the functionality of the indexer. We won't use the `org_id` until we switch to the new implementation.

### CODE REVIEW

**Review by onewland — APPROVED** [review]
Seems fine to me, but is it that much clearer splitting the functional change from the interface change?

**Comment by MeredithAnya** [comment]
> Seems fine to me, but is it that much clearer splitting the functional change from the interface change?

My hope was that it was easier to review since this is a lot of files but relatively small changes.

**Comment by fpacifici** [comment]
One question: I do not see any change to the product here. Is the product code not using the indexer to resolve ints to strings?  @jjbayer 
I think it is important for the product code not to depend on the index postgres model directly otherwise we would not be able to move away from a postgres backed storage for the indexer

**Comment by MeredithAnya** [comment]
> One question: I do not see any change to the product here. Is the product code not using the indexer to resolve ints to strings? @jjbayer I think it is important for the product code not to depend on the index postgres model directly otherwise we would not be able to move away from a postgres backed storage for the indexer

I did not include `resolve` here. I mention that in the description, and @wmak 
 is helping with the `resolve` method https://github.com/getsentry/sentry/pull/32825.

**Comment by untitaker** [comment]
>I think it is important for the product code not to depend on the index postgres model directly otherwise we would not be able to move away from a postgres backed storage for the indexer

fwiw we are exclusively using the functions that you have exposed via the service abstraction, we should be fine.

**Review by untitaker — APPROVED** [review]

**Pull request merged**
