### PR TITLE
test(js): Refactor to use `sentry-test` alias and  `mountWithTheme`

### PR DESCRIPTION
**Pull request by billyvg**
Refactor to use a `mountWithTheme` wrapper for `enzyme.mount`. This is needed to upgrade to emotion@10.

### CODE REVIEW

**Comment by EvanPurkhiser** [comment]
Can we remove a lot of the router context stuff then too?

**Comment by billyvg** [comment]
@EvanPurkhiser What stuff specifically? I'd rather not add more changes in this PR as it's going to be a pain to keep up to date with master

**Comment by dashed** [comment]
I agree with @billyvg. Let's have the router context stuff in a separate PR.

**Comment by EvanPurkhiser** [comment]
Like the `routerContext` parameters. But agreed, lets just move forward with this as is once tests are passing.

Let me know when this is good and I can give the +1

**Comment by billyvg** [comment]
@EvanPurkhiser Are you suggesting removing the use of routerContext params completely? Or moving them into `mount/mountWithTheme`? 

It's ready to go, just bumped getsentry to track this commit for gs tests.

Also added an eslint rule to ensure no usage of `enzyme` directly: https://github.com/getsentry/eslint-config-sentry/pull/32

And docs https://github.com/getsentry/frontend-handbook/pull/3

**Comment by EvanPurkhiser** [comment]
> Are you suggesting removing the use of routerContext params completely

Do we need them if we're now doing this? Maybe I'm misunderstanding exactly what this PR does for us.

**Review by evanpurkhiser — APPROVED** [review]

**Comment by billyvg** [comment]
@EvanPurkhiser `routerContext()` also initializes some things like organization, router, location, etc, that a lot of our components expect to be in context. The emotion theming related ones have been removed: https://github.com/getsentry/sentry/pull/15062/files#diff-aa34cb9acf9a36938078d3c80d01a25aL199

**Comment by EvanPurkhiser** [comment]
I see now. Okay, sounds good.

**Pull request merged**
