### PR TITLE
feat: Add sort by users in issue stream

### LINKED ISSUE #2874: Possible to sort by User?
Hi,

in Sentry i can sort by First Seen, Frequency, etc. but i cannot sort by user. 
I know, detecting unique users can be hard, but the numbers are there already, when i can sort by user it would give me at least some hint how many people are affected. 
A bug that happened for 10k users once is in my view more important than a bug that a happened 10k times for two user :)

PS: keep up the great work, sentry is great!

### PR DESCRIPTION
**Pull request by scttcper**
closes #2874
https://app.asana.com/0/1143846759074121/1173934306766147/f

Adds "Users" to the sort by option in issues stream. Issues are sorted by user totals in the current date range, however it may be confusing because the user column shows total lifetime users impacted. This confusion is somewhat addressed via a tooltip in #18832

image

### CODE REVIEW

**Review by wedamija — APPROVED** [review]
Looks good!

**Comment by benvinegar** [comment]
Whoa. Is this real life? 😇

**Review by markstory — APPROVED** [review]

**Comment by chocnut** [comment]
Woah thanks!

**Comment by psabharwal123** [comment]
thanks! @slohmes when will this reach https://aws.amazon.com/marketplace/pp/B07JJDVVNJ?ref_=srh_res_product_title ?

**Pull request merged**
