### PR TITLE
fix: Remove unnecessary onClick handler from ShortId component

### PR DESCRIPTION
**Pull request by dashed**
This was causing hard reloads for when you click on the the `Issue` field cells in Discover.

Screen Shot 2020-09-10 at 1 25 26 PM

### CODE REVIEW

**Review by billyvg — APPROVED** [review]
I wonder if there are other places where this happens?

IMO this logic shouldn't belong in the shortId component, the comment says it's for the stream... shouldn't the stream add an `onClick` to control the click behavior? I'm unsure of the scope of this change though so...

**Comment by dashed** [comment]
@billyvg Not that I know of. This behaviour was around for 5 years. 

I can follow it up with another PR to clean other places.

**Comment by billyvg** [comment]
Yeah I think the onClick here is just unnecessary, and I can see a similar issue popup in future features that need `ShortId` within a `<Link>`

**Comment by dashed** [comment]
@billyvg Okay. I'll just delete it.

**Comment by billyvg** [comment]
@dashed https://github.com/getsentry/sentry/blob/34bcb41539b486fee352c07fdbbeaea2fd12c33c/src/sentry/static/sentry/app/components/eventOrGroupExtraDetails.jsx#L55 we'll need a click handler here to stop propagation

**Comment by dashed** [comment]
@billyvg Oh I see. This should be addressed in https://github.com/getsentry/sentry/pull/20713/commits/84ff6f8a4417097cc4dda42ccae0ca9886ae2fec

**Review by billyvg — APPROVED** [review]
thanks for cleaning this up! You will have prevented many future bugs with this.

**Pull request merged**
