### PR TITLE
new Platformpicker in project install 

### PR DESCRIPTION
**Pull request by MaxBittker**
This uses the new platfompicker component in project install. 

Had to move styles to a more general purpose selector and not show 'other' outside of onboarding.
screenshot 2017-08-07 17 48 18
screenshot 2017-08-07 17 47 28

### CODE REVIEW

**Comment by getsentry-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by MaxBittker** [comment]
i hope percy catches this so i don't have to take screeshots :P

**Review by ehfeng — CHANGES_REQUESTED** [review]
Searching "JavaScript" only returns JS and React: no Vue, Ember, etc. The same with "Python": no Tornado, Bottle, etc.

Other than that, looks good!

**Comment by MaxBittker** [comment]
@eric I'm fixing this in my next branch, it's because of behavior the tabs

**Comment by denamwangi** [comment]
Hey @eric were you searching "JavaScript" or "javascsript" - if it's not lowercase I get no results. I hadn't realized earlier that it was case sensitive. I know we were waiting on changing up the tabs behavior but can we add case insensitivity to the filter?

**Comment by eric** [comment]
🙅🏼‍♂️ Wrong Eric.

**Comment by mattrobenolt** [comment]
lol

**Comment by ehfeng** [comment]
@eric come work at sentry so we can actually tag you.

**Review by ehfeng — APPROVED** [review]

**Comment by denamwangi** [comment]
Oopsies! Sorry @eric

**Review by denamwangi — CHANGES_REQUESTED** [review]
Let's make platformpicker case insensitive

**Comment by MaxBittker** [comment]
good catch @denamwangi - I fixed the case sensitivity and the tab behavior.

**Review by denamwangi — APPROVED** [review]

**Comment by denamwangi** [comment]
lgtm :boom:

**Pull request merged**
