### PR TITLE
ref(ts): Convert errorItem to typescript

### PR DESCRIPTION
**Pull request by k-fish**

### CODE REVIEW

**Review by scttcper — APPROVED** [review]
could update props/state to use destructuring but this also looks good as is

**Comment by scttcper** [comment]
Also unrelated but i does moment.utc do anything when diffing two times?

```js
duration(moment.utc(data.server_time).diff(moment.utc(data.sdk_time)))
```

**Review by leedongwei — APPROVED** [review]

**Comment by leedongwei** [comment]
Not sure if we could simplify `moment.utc(data.server_time).diff(moment.utc(data.sdk_time))` to `moment(data.server_time).diff(data.sdk_time)`.

You'll probably need to test if `sdk_time` is a date string with an odd format. This is out of scope for TS conversion so it's up to you.

**Review by priscilawebdev — APPROVED** [review]

**Comment by k-fish** [comment]
@leedongwei my plan of attack for converting typescript files has been to try to make the changes as non-functional as possible for now and just do the typing. We can always come to the these files after we're done to fix them up, or next time someone actually needs to use it, as they'll have more context into how it's used then I will doing just the conversion.

**Pull request merged**
