### PR TITLE
ref(search): Make Cursor.__repr__ less ... weird

### PR DESCRIPTION
**Pull request by tkaemming**
```
<<class 'sentry.utils.cursors.Cursor'>: value=1526667588000 offset=0 is_prev=0>
```

lol

### CODE REVIEW

**Review by mattrobenolt — APPROVED** [review]
Great job @tkaemming. Fantastic. 🎉

**Comment by tkaemming** [comment]
Thanks everyone, really happy to contribute

**Comment by JTCunning** [comment]
I love free open source software.

**Comment by tkaemming** [comment]
My only regret is that this didn't make Sentry 9

**Comment by JTCunning** [comment]
We still have time, Ted. I'll put a good word in with the boss.

**Comment by JoshuaRLi** [comment]
cool, and nice

**Pull request merged**
