### PR TITLE
Adding 'verbose' flag to command 'sentry init'

### PR DESCRIPTION
**Pull request by joedborg**
... to make it easier to script setting Sentry up.

### CODE REVIEW

**Comment by mattrobenolt** [comment]
Just curious, but why woudl this help? Seems this is going to give you some garbled output since they'll just be effectively concatenated together. You could just as well do `sentry init && cat /etc/sentry/config.yml /etc/sentry/sentry.conf.py` which would yield the same output, or am I missing something?

**Comment by mattrobenolt** [comment]
Oh, I also misread. You're just echoing out the file paths. Definitely not sure then why this helps. :)

**Comment by joedborg** [comment]
Hey @mattrobenolt.  It's so any deployment scripts know where the files have gone.  I know you could do `sentry init /some/path/`, but if you're happy with the default location (which varies depending on how you deploy), you can use this store these locations in a variable for later reference.

**Comment by mattrobenolt** [comment]
Yeah, as someone who does this, I don't understand the use case. So this will simply print back out the file locations, nothing more. But thes values are derived based on what you're passing in already to `sentry init`. So it's like, `sentry init $path`, then you haev `$path/config.yml` and `$path/sentry.conf.py` instead of needing to parse stdout. I'd also not like to maintain that this output would expect to be machine readable. Typically verbose output is for humans.

**Comment by joedborg** [comment]
As someone who also has done this across many different methods, it'd be nice to to have to worry about setting up a `$path` where these end up, rather letting Sentry chose its relative places using `discover_configs()` and run from there.

I'm more than happy to change the flag name - or even the output format, say JSON, but this isn't something that's consistent with any of Sentry's runners.

**Comment by mattrobenolt** [comment]
What if we introduced a different argument that literally explicitly spit back this information?

So maybe like, `sentry init $path --info` which doesn't create the files, but it just spits back these two locations. Then you'd do something like `sentry init $path && sentry init $path --info` or whatever makes sense.

Sorry if my concerns aren't translating well. I'd just don't want to potentially interleave other random "verbose" output with somethign you expect to be machine readable. If there's verbose flag, I can very easily see changing output to say like, "> writing file to /etc/sentry/config.yml" for example.

**Comment by joedborg** [comment]
Yeah, as I say, if the name of the flag is not consistent with either Sentry or your expectations, then I'll happily change it, I just couldn't find any other runners that do something like this.

Doing something like `--file` is fine, but my case isn't
`sentry init $path --info` (it's clear that you'd just cat $path and the two conf file names (assuming these will never change; which, to my knowledge, isn't the case as the .py will be going one day)
...it's...
`sentry init --info`
...to know what `discover_configs()` has resolved.

Again, in terms of output format, tell me whatever Sentry's or your standard is and I'll adjust the PR accordingly, it's not something I'm confined to.

**Comment by mattrobenolt** [comment]
> sentry init --info
> ...to know what discover_configs() has resolved.

Yup, I think we're on the same page here.

Actually, how about this:

We already have `sentry config <command>`. What if we just add `sentry config discover` here? To do what you're asking. Then as precedent, we have the `sentry files info <id>` take a `--format` flag to specify how you want it returned. I think format would be overkill since it's simply newline separated.

This feels a bit better to me and less hacky. Thoughts?

**Comment by joedborg** [comment]
Sounds good to me.  I'll code it up and make a new PR.

**Pull request closed without merging**
