### PR TITLE
fix(style): justify-content: center dropdown-actor-title

### PR DESCRIPTION
**Pull request by MaxBittker**
per lyn

### CODE REVIEW

**Comment by lynnagara** [comment]
💯

**Comment by MaxBittker** [comment]
lets see what you've got, percy

**Comment by lynnagara** [comment]
Looks a lot better! Can't say the same for german though, perhaps we should fix the case where text is longer than the button as well (this is sadly common...)

**Review by ckj — APPROVED** [review]
LGTM

**Pull request merged**
