### PR TITLE
Add logging for notifications (refs GH-2918)

### PR DESCRIPTION
**Pull request by dcramer**
@getsentry/infrastructure

### CODE REVIEW

**Comment by mitsuhiko** [comment]
I can't tell from the issue why we do this. I guess it's good to merge, but probably would make sense to also emit the org id?

**Comment by dcramer** [comment]
@mitsuhiko we wanted to log when notifications were sent (email, slack) so we could audit it. I'd prefer we come up with a stronger standard log format, but that's a bigger convo. Def agree we can add organization here.

**Comment by mattrobenolt** [comment]
@dcramer Wanna get this pulled in before I cut 8.3?

**Comment by dcramer** [comment]
Nope

**Pull request merged**
