### PR TITLE
feat(apidocs): type team serializer response

### PR DESCRIPTION
**Pull request by JoshFerge**
- types the Team serializer function with a TypedDict
- replaces TODOs with types added
- creates a `types.py` file for common types

We start to run into circular import issues so the `TYPE_CHECKING` variable is used. as an interesting aside, `from __future__ import annotations` is required for this to work with TypedDicts from what I see. perhaps something with their syntax.

EDIT: my above comment is true regardless of typeddict, without `__future__` you'd have to use a string literal instead

### CODE REVIEW

**Comment by JoshFerge** [comment]
the first api-docs test failure on the first commit brings up an interesting point. our API docs are generated in a normal interpreter, so types imported under TYPE_CHECKING will not exist. these types are not used in doc-gen, so this is fine for now. I will brainstorm solutions, if adding fancy logic to our type parser fails, defining the types in a separate file will do.

**Review by evanh — APPROVED** [review]
That API Doc error is interesting. The exception is thrown in the typing module, so I don't understand why TYPE_CHECKING would be false.

**Comment by untitaker** [comment]
I wonder whether a separate `API_DOCS_TYPE_CHECKING` flag could solve this without flipping all  of docs generation upside down and without making circular imports (outside of apidocs) impossible.

**Comment by JoshFerge** [comment]
> That API Doc error is interesting. The exception is thrown in the typing module, so I don't understand why TYPE_CHECKING would be false.

The API docs are generated in a python runtime environment, so TYPE_CHECKING is false in this case. The reason the error is in the type checking module is because we use the `typing.get_origin` as part of our parsing logic. (see `src/sentry/apidocs/spectacular_ports.py`).

**Comment by JoshFerge** [comment]
@untitaker @evanh see https://github.com/getsentry/sentry/pull/31958 for my proposed solution.

**Pull request merged**
