### PR TITLE
deps(ui): Upgrade jest, jest-junit

### PR DESCRIPTION
**Pull request by scttcper**
Jest is working towards releasing v28 so this puts us on the latest version of 27

### CODE REVIEW

**Review by priscilawebdev — APPROVED** [review]

**Review by matejminar — APPROVED** [review]

**Comment by JonasBa** [comment]
@scttcper we should run a quick benchmark of the test suites before merging this. The reason is that lots of people have been saying that there seems to have been slight regressions in v27. If those are sufficiently large for our project, we should maybe reconsider merging (altho looks like all of our tests pass, so maybe there's no impact)

**Comment by scttcper** [comment]
@JonasBa we're already on v27. Do the comments say it's the later versions or any version

**Comment by scttcper** [comment]
@JonasBa looks within the normal range https://sentry.io/organizations/sentry/discover/results/?display=top5&environment=ci&field=title&field=avg%28transaction.duration%29&name=All+Events&project=4857230&query=transaction.op%3A%22jest+test+suite%22++transaction.duration%3A%3C2min+branch%3Arefs%2Fheads%2Fmaster&sort=-avg_transaction_duration&statsPeriod=7d&widths=-1&widths=-1

**Comment by JonasBa** [comment]
@scttcper oh my bad. I looked at the @types/jest diff which was still on 26...

**Pull request merged**
