### PR TITLE
fix(crons): Fix single escaping and make FQN consistent

### PR DESCRIPTION
**Pull request by shaedrich**
* A slash has to be escaped with another slash to not be mistaking for escaping itself
* Some functions and classes from the SDK used FQN, some only the function/class name

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Comment by shaedrich** [comment]
@evanpurkhiser bumping this as well

**Review by evanpurkhiser — APPROVED** [review]

**Comment by evanpurkhiser** [comment]
Thank you for tihs as well!

**Comment by shaedrich** [comment]
My pleasure!

**Comment by shaedrich** [comment]
@evanpurkhiser Approved and closed&mdash;you sure?

**Comment by evanpurkhiser** [comment]
damn, this bot is annoying haha.

**Comment by evanpurkhiser** [comment]
Let me see if something was failing PR checks

**Comment by shaedrich** [comment]
> damn, this bot is annoying haha.

and I thought, I was the only one thinking this 😅

**Pull request merged**
