### PR TITLE
fix(discover) - Change condition to tag when incompatible

### PR DESCRIPTION
**Pull request by wmak**
- When a query includes "event.type=transaction" certain other
  conditions become incompatible since the transaction table doesn't
  have those fields (eg. `stack.stack_level` or `error.handled`)
- In these situations change those fields to be tags so that snuba can
  handle it. Most of the time this will result in nothing.

### CODE REVIEW

**Comment by lynnagara** [comment]
I don't quite follow why we would want to convert stack traces and error frames into tags. Why not just omit them from the query.

1) That doesn't seem like what the user is intending if they use one of these fields
2) The format is different, which seems like it would confuse end users - string vs array
3) Won't it potentially make these queries a lot slower since the tags have to be unpacked for no reason? (maybe not with the flattened tags but we're still potentially reading the entire tags column for now reason)

**Comment by wmak** [comment]
Hmm, good points @lynnagara but I think omitting might be more confusing since they'll get "inaccurate" results. I think since we know that combining the two will always result in nothing, it'll be better to just exit early.

**Comment by markstory** [comment]
> I don't quite follow why we would want to convert stack traces and error frames into tags. Why not just omit them from the query.

We wanted to stay within the discover model of if a column doesn't exist it is treated as a tag. Given that the `event.type` condition makes a dataset selection causing a variety of fields to be treated as tags.

**Comment by lynnagara** [comment]
Early exit / skipping the query and then returning either error or empty result set seems good to me. (Querying on a tag that we don't expect to return anything seems like a too roundabout way of generate an empty result.)

**Comment by lynnagara** [comment]
Do we need a generic approach to handling these cases? There are many other potentially invalid combinations along these same lines. For example: a stack trace on a CSP event, an issue ID on a transaction, or a trace ID on an error, the list goes on...

**Comment by markstory** [comment]
> Do we need a generic approach to handling these cases?

I think we should explore that. A stack trace on a CSP event isn't quite the same unless we plan on separating storage for CSP events. Looking at the storage table selection and rejecting queries based on impossible conditions could be something that the discover dataset does. We could evolve that logic if/or when joins are added too.

**Comment by wmak** [comment]
@lynnagara @markstory Would it make sense to do this separately depending on whether its a column or condition?
ie. Turn incompatible columns into tags, so we still show results but with the incompatible column resulting in empty strings?

**Comment by markstory** [comment]
> ie. Turn incompatible columns into tags, so we still show results but with the incompatible column resulting in empty strings?

Yes. Unknown columns in the select field have to be treated as tags. If it is a known column that is incompatible with the current table I think selecting a static `''` or `null` is a reasonable.

**Comment by wmak** [comment]
Closing this PR, will be building a more generic solution instead.

**Pull request closed without merging**
