### PR TITLE
fix(starfish): Use max and min from series data instead of page filter for accurate max and min

### PR DESCRIPTION
**Pull request by edwardgou-sentry**
Use max and min from series data instead of page filter for accurate max and min. This fixes an issue where the x axis max and min doesn't match series data (especially after trimming) and also fixes the x axis getting further out of sync with page filter over time. Also removes `start`, `end`, and `statsPeriod` props from starfish chart and use page filter inside the component instead.

### CODE REVIEW

**Comment by DominikB2014** [comment]
I'm not sure about this approach in the scenario where I explicitly select a certain time range, especially if I have a specific time in mind. (I think its good if we're just thinking of stats period). 
I would expect data for the exact range selected (from pagefilters), to be the exact data i'm seeing, if there's no data available then i'd rather know that then the data just getting cut off and not knowing why.

There's another bug i'm seeing when testing this, which is not related to your PR to worth noting.
If I select 7AM to 10AM, then the data cuts off at 9AM, meaning im missing 1/3 of the data i'm requesting.
image.

If I select 7AM-11AM, then it will cut off at 10AM, so clearly the data is available for 10AM.

Lmk if you have any thoughts on this or if I'm missing something here!

**Comment by edwardgou-sentry** [comment]
> I'm not sure about this approach in the scenario where I explicitly select a certain time range, especially if I have a specific time in mind. (I think its good if we're just thinking of stats period). I would expect data for the exact range selected (from pagefilters), to be the exact data i'm seeing, if there's no data available then i'd rather know that then the data just getting cut off and not knowing why.
> 
> There's another bug i'm seeing when testing this, which is not related to your PR to worth noting. If I select 7AM to 10AM, then the data cuts off at 9AM, meaning im missing 1/3 of the data i'm requesting. image.
> 
> If I select 7AM-11AM, then it will cut off at 10AM, so clearly the data is available for 10AM.
> 
> Lmk if you have any thoughts on this or if I'm missing something here!

Hey Dom, thanks for the review! So the reason I think we can probably base the start and end time off the series data is because `events-stats` requests should always return the full range of data requested including zerofill. This data should match the timerange selected by the user exactly. 

For the issue where you're seeing missing data, I think I've figured out why this is happening. So there is trimming logic in place for relative time queries in the `Chart` component. But it looks like the `Chart` component is being used with hardcoded `statsPeriod`, `start`, and `end` values in a lot of places in starfish, which is causing the trimming logic to not work correctly. I'm going to spend some time cleaning up these instances and probably just get rid of the `statsPeriod`, `start`, and `end` props entirely since I don't think we actually need them passed in. We can probably just use the page filter hook if needed.

I'll work on this today and let you know when I have an update!

**Comment by DominikB2014** [comment]
> I'll work on this today and let you know when I have an update!

@edwardgou-sentry Perfect, thanks for looking into that!

**Comment by edwardgou-sentry** [comment]
Hey @DominikB2014 , updated the pr. You should be able to see that the data should not be getting cut off anymore when you select a specific absolute time range. The only time we trim the last interval is when a relative time range is selected, because the last datapoint is always incomplete. I removed the `statsPeriod`, `start`, and `end` props since they were being provided hardcoded values and I could just pull the pagefilter from within the component anyways.

**Review by DominikB2014 — APPROVED** [review]
@edwardgou-sentry It lgtm! But I think there might be something weird going on backend wise, the last data point seems to differ. By that I mean

if I select 7AM - 10AM, then at 10AM there are 141 queries/s
image

If I select 7AM - 11AM, then at 10AM there are 7500 queries/s 
image

It seems a bit odd, but I believe this is a BE issue, frontend lgtm!

**Comment by edwardgou-sentry** [comment]
@DominikB2014 Thanks for the review! Interesting observation, I just checked this and found the backend returning the same thing too. I'll check the backlog to see if we have a ticket for this!

**Pull request merged**
