### PR TITLE
ref(py3): Use integer division in metric alert time window calc

### PR DESCRIPTION
**Pull request by evanpurkhiser**

### CODE REVIEW

**Review by joshuarli — APPROVED** [review]
I wanna say, I feel like it'd be safe to mass-convert `/` to `//` only if operands are strictly integers. It should be easy to add an ast-based check for that in sentry-flake8.

There's also `from __future__ import division` but it's really heavy-handed (affects `__div__`) and you'd need to still manually audit any `/` with integer operands because the result will be float.

**Comment by EvanPurkhiser** [comment]
How would you tell if a variable is strictly an integer?

**Comment by EvanPurkhiser** [comment]
Oh you're saying for constant divisions? `10 / 5`

**Comment by joshuarli** [comment]
> Oh you're saying for constant divisions? `10 / 5`

Yeah.

**Review by BYK — APPROVED** [review]

**Pull request merged**
