### PR TITLE
improved tooltips (especially in unknown user case)

### PR DESCRIPTION
**Pull request by MaxBittker**
screenshot 2017-04-03 14 49 11
screenshot 2017-04-03 14 49 16

### CODE REVIEW

**Review by dcramer — DISMISSED** [review]
theres no newlines, this is still ugly af

**Comment by MaxBittker** [comment]
screenshot 2017-04-03 17 44 25
screenshot 2017-04-03 17 44 22

**Comment by MaxBittker** [comment]
also limits to 7 commits for now

**Review by ckj — APPROVED** [review]
Much better 😉

**Pull request merged**
