### PR TITLE
chore(SDK's): Update various SDK versions/urls

### PR DESCRIPTION
**Pull request by lobsterkatie**
... so that the UI will correctly report when the SDK used to capture an event is out of date.

NB: This is not comprehensive, because it's a band-aid on the real problem, which is that ideally these would get updated automatically. Working on that in a separate PR. (Will update this PR with a link to it once it's up.)

@HazAT I notice JS isn't in here. Is that on purpose, or should I add it while I'm here?

[UPDATE: There are a few others missing, too. Worth adding them?]

### CODE REVIEW

**Comment by HazAT** [comment]
@lobsterkatie Would be awesome if you could add it.
Also, we could think of using the release registry for the version numbers + SDKs so we don't have to update it manually anymore.
Basically this todo:
https://github.com/getsentry/sentry/pull/13225/files#diff-fd5d9dbc87e18a510a3520831899b63eL1485

Wouldn't be that hard to do, let me know what you think.

**Review by HazAT — APPROVED** [review]

**Comment by lobsterkatie** [comment]
Yeah, would be great to not have to do it manually. I don't know much about the release registry, but if you can point me in the right direction, I can give it a shot.

We do have one problem to solve in the meantime, though: the format of SDK names has changed, or at least diversified. Everything used to be `raven-language` or `sentry-language`, possibly followed by a more specific identifier: `raven-language:something` or `sentry-language:something` (the example given in the relevant docstring is `raven-java:logback`). But now there's `sentry.javascript.browser` and friends, which don't fit the pattern.

So, not going to do it in this PR (which I'll hang onto until the above is fixed), but our logic around "do we show the _hey, yo, your SDK is out of date!_ message?" will need to get smarter, to be able to handle both versions of SDK names. Once that's done, I can add javascript (and any other missing ones) here, and then let's talk about the release registry.

Sound okay?

**Comment by HazAT** [comment]
@lobsterkatie Good catch!
We will fix the rust identifier.

I would merge this for now and go with the pragmatic approach. 
We can hop on a quick call next week so I can guide you in the right direction regarding using the release registry.

**Comment by HazAT** [comment]
🎉

**Pull request merged**
