### PR TITLE
Suggest assignees

### PR DESCRIPTION
**Pull request by kjlundsgaard**
Initial implementation of suggested assignees - just the front-end design
screen shot 2017-01-12 at 4 52 15 pm

@ckj @benvinegar @getsentry/product

### CODE REVIEW

**Comment by benvinegar** [comment]
Can we get that `SUGGESTED` bar to line up with the border above it?

**Comment by benvinegar** [comment]
Let's hang onto this until we get further with changes to the issue details page.

**Comment by MaxBittker** [comment]
wait this actually looks better than the placeholder UI we have now

**Comment by MaxBittker** [comment]
it's slightly different because this version doesn't show that there's someone suggested until you click it though

**Pull request closed without merging**
