### PR TITLE
chore(various): Minor adjustments

### PR DESCRIPTION
**Pull request by evanpurkhiser**
- Don't try and be smart about tooltip container display mode proptype,
   there are more values than on the ones list.

 - Noramlzie comment in types

### CODE REVIEW

**Review by billyvg — APPROVED** [review]
The PR title is a bit vague, can we be a bit more specific?

**Comment by EvanPurkhiser** [comment]
I'll split. I just got a little lazy

**Comment by EvanPurkhiser** [comment]
Actually will just merge with a better type

**Comment by EvanPurkhiser** [comment]
https://github.com/getsentry/sentry/pull/17631 and https://github.com/getsentry/sentry/pull/17632

**Pull request closed without merging**
