### PR TITLE
test(gha): Use pytest-github-actions-annotate-failures

### PR DESCRIPTION
**Pull request by evanpurkhiser**

### CODE REVIEW

**Review by BYK — APPROVED** [review]
Let's do this 👀

**Review by billyvg — APPROVED** [review]

**Comment by joshuarli** [comment]
What's wrong with what we currently have @EvanPurkhiser?

**Comment by EvanPurkhiser** [comment]
I was just testing something, which is why I didn’t assign anyone :)

It is better than the error matcher we currently use, instead of each line of a failed test turning into a single annotation, the whole block of error text becomes a single annotation

**Comment by EvanPurkhiser** [comment]
Actually this looks goo now.

**Comment by BYK** [comment]
Murge at will @EvanPurkhiser

**Pull request merged**
