### PR TITLE
Update conftest.py

### PR DESCRIPTION
**Pull request by afraz-khan**
remove white spaces for readability.

### CODE REVIEW

**Comment by joshuarli** [comment]
Unfortunately, this isn't the way the `black` formatter wants imports. Thanks for the pull request!

**Comment by frenck** [comment]
It looks like this user is running for a Hacktoberfest t-shirt by creating a bunch of useless PRs on several repositories on this new GitHub account.

My advice would be to add the `invalid` tag as well. Hacktoberfest processes the `invalid` tag by invalidating the contribution the user has made and won't count toward Hacktoberfest.

More information about this:

https://hacktoberfest.digitalocean.com/details#spam

The other PR's:
https://github.com/django/django/pull/11864/files
https://github.com/getsentry/sentry/pull/14908/files
https://github.com/wagtail/wagtail/pull/5598/files
https://github.com/fabric/fabric/pull/2020/files
https://github.com/home-assistant/home-assistant/pull/27124/files

**Comment by joshuarli** [comment]
@frenck Thanks! I definitely noticed the spam, but didn't know it was for Hacktoberfest. Thanks for bringing this to my attention.

**Comment by frenck** [comment]
No problem @joshuarli!

**Pull request closed without merging**
