### PR TITLE
fix: metrics.timer typo

### PR DESCRIPTION
**Pull request by 0o001**
### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Review by armenzg — APPROVED** [review]
Thank you very much!

**Comment by 0o001** [comment]
Anyone?

**Comment by 0o001** [comment]
@armenzg

**Comment by armenzg** [comment]
My apologies. I don't know why I did not merge it right away. I've set the auto-merge so I don't forget.

Thanks @0o001 for the ping and your patience!

**Pull request closed without merging**
