### PR TITLE
feat(SessionSerializer): Deprecate transitional serializer

### PR DESCRIPTION
**Pull request by maxiuyuan**
In our effort to get rid of pickled objects in our session, we had the transitional serializer that slowly converted all pickle to json objects in our session. Looking at our[ dashboard ](https://app.datadoghq.com/dashboard/ax8-c4b-rxd/login--signup?from_ts=1646519011590&to_ts=1649111011590&live=true) we are no longer reading pickle objects so we can safely use the json serializer 

#sync-getsentry

### CODE REVIEW

**Review by nhsiehgit — APPROVED** [review]

**Review by JoshFerge — CHANGES_REQUESTED** [review]
I don't think thats the correct module for JSON serializing of session. Additionally, JSON is now the default, so you can simply remove that setting IMO.

https://docs.djangoproject.com/en/2.2/ref/settings/#std:setting-SESSION_SERIALIZER

**Comment by maxiuyuan** [comment]
> I don't think thats the correct module for JSON serializing of session. Additionally, JSON is now the default, so you can simply remove that setting IMO.
> 
> https://docs.djangoproject.com/en/2.2/ref/settings/#std:setting-SESSION_SERIALIZER

i see, removing it will default to the Json serializer. I wonder if they created this module so they can import the Pickle and Json serializer in the same place. It looks like the Json serializer from`django.contrib.sessions.serializers.JSONSerializer` is set to the one from `django.core.signing.JSONSerializer` https://github.com/django/django/blob/main/django/contrib/sessions/serializers.py

**Comment by JoshFerge** [comment]
> > I don't think thats the correct module for JSON serializing of session. Additionally, JSON is now the default, so you can simply remove that setting IMO.
> > https://docs.djangoproject.com/en/2.2/ref/settings/#std:setting-SESSION_SERIALIZER
> 
> i see, removing it will default to the Json serializer. I wonder if they created this module so they can import the Pickle and Json serializer in the same place. It looks like the Json serializer from`django.contrib.sessions.serializers.JSONSerializer` is set to the one from `django.core.signing.JSONSerializer` https://github.com/django/django/blob/main/django/contrib/sessions/serializers.py

makes sense. thanks for changing!

**Review by JoshFerge — APPROVED** [review]
looks good! only other consideration would be to let self hosted team know to add a note about this change in the upcoming release. what do you think are considerations for a self-hosted user deploying this change?

**Comment by maxiuyuan** [comment]
> looks good! only other consideration would be to let self hosted team know to add a note about this change in the upcoming release. what do you think are considerations for a self-hosted user deploying this change?

A consideration i can think of is that the self-host user might have pickle objects in the session still. with these changes, if they have something not json serializable would cause a lot of errors for the user

**Comment by JoshFerge** [comment]
> > looks good! only other consideration would be to let self hosted team know to add a note about this change in the upcoming release. what do you think are considerations for a self-hosted user deploying this change?
> 
> A consideration i can think of is that the self-host user might have pickle objects in the session still. with these changes, if they have something not json serializable would cause a lot of errors for the user

What happens in this case after the error? do we think this is an acceptable user experience?

**Comment by maxiuyuan** [comment]
> > > looks good! only other consideration would be to let self hosted team know to add a note about this change in the upcoming release. what do you think are considerations for a self-hosted user deploying this change?
> > 
> > 
> > A consideration i can think of is that the self-host user might have pickle objects in the session still. with these changes, if they have something not json serializable would cause a lot of errors for the user
> 
> What happens in this case after the error? do we think this is an acceptable user experience?

it wouldn't an acceptable user experience if they are greeted by the error. I'll talk to the self-hosted team about this before i merge. Would Chad would be the person to contact?

**Comment by JoshFerge** [comment]
> > > > looks good! only other consideration would be to let self hosted team know to add a note about this change in the upcoming release. what do you think are considerations for a self-hosted user deploying this change?
> > > 
> > > 
> > > A consideration i can think of is that the self-host user might have pickle objects in the session still. with these changes, if they have something not json serializable would cause a lot of errors for the user
> > 
> > 
> > What happens in this case after the error? do we think this is an acceptable user experience?
> 
> it wouldn't an acceptable user experience if they are greeted by the error. I'll talk to the self-hosted team about this before i merge. Would Chad would be the person to contact?

I would say that for self hosted users, an experience like that, in where the user simply has to re-log in to fix the error once, is acceptable, especially since this upgrade helps with security, it is a fine tradeoff. I think its just something to note for the release this goes out. And yes, chad would be the right person to loop in.

**Pull request merged**
