### PR TITLE
Fix ``bad-chained-comparison`` in ``api/endpoints/project_details.py``

### PR DESCRIPTION
**Pull request by Pierre-Sassoulas**
This seems to be a genuine error detected by the new pylint check in https://github.com/PyCQA/pylint/pull/7990.

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Review by JoshFerge — APPROVED** [review]

**Comment by Pierre-Sassoulas** [comment]
This is still a bug, but I don't know what's wrong with the continuous integration.

**Review by dashed — APPROVED** [review]

**Pull request merged**
