### PR TITLE
fix(dashboard): Change Dashboard to use Discover feature flag [APP-1095]

### PR DESCRIPTION
**Pull request by billyvg**
Changes sidebar order too

image

### CODE REVIEW

**Comment by billyvg** [comment]
Hmm we may want this to be behind `sentry10` and `discover`

**Comment by lynnagara** [comment]
@billyvg Yeah, let's do sentry10 + discover

**Comment by ckj** [comment]
Is Discover separated from Projects in the old nav on purpose? https://percy.io/getsentry/sentry/builds/1414350

**Comment by billyvg** [comment]
@ckj 	was following https://getsentry.atlassian.net/browse/APP-1095

**Review by ckj — APPROVED** [review]

**Comment by markstory** [comment]
Is dashboards ready for customers to see? Customers will be getting sentry10 soon, and some already have discover. Should there be another flag used until discover is ready for customers.

**Comment by billyvg** [comment]
> Is dashboards ready for customers to see? Customers will be getting sentry10 soon, and some already have discover. Should there be another flag used until discover is ready for customers.

Yeah it's ready

**Pull request merged**
