### PR TITLE
clean up plugin settings list ui

### PR DESCRIPTION
**Pull request by macqueen**
Putting this up to get initial feedback. The main changes are:
- Issue tracking and notification integrations get their own sections under the integrations header
- Gets rid of the view where users could edit multiple integrations at once. It seemed confusing to have two different views to do the exact same thing and unlikely that people ever actually are trying to edit their JIRA and Github settings at the same time.

Other things we could do:
- Add a customer service tab for JSD and Zendesk integrations
- Add product icons for integrations (with @ckj's help)

Does this seem better? Worse? Any other suggestions? @getsentry/product 
### before:

screenshot 2016-10-21 14 04 46

screenshot 2016-10-21 14 06 08
### after:

screenshot 2016-10-21 13 52 44

screenshot 2016-10-21 13 52 21

screenshot 2016-10-21 13 52 03

(The All Integrations tab looks the same)

### CODE REVIEW

**Comment by macqueen** [comment]
updated screenshot:

screenshot 2016-11-16 13 10 10

**Review by benvinegar — COMMENTED** [review]
I'm not super comfortable with the plugin code so I'd prefer if someone like @mattrobenolt or @dcramer signed off.

The JavaScript looks fine. And from a product perspective, this feels like a huge improvement.

If I had any suggestions, they'd be:
- Move "All Integrations" to the bottom of the list (and maybe just use "All")
- It would be nice if we could incorporate "Chat" into the "Notifications" title – we should make it super clear where to find Slack/Hipchat/etc since they're the most popular integrations

**Comment by macqueen** [comment]
ok this is back to being at a place where I could use some more UI help / feedback. I made the list a grid:

screenshot 2016-12-07 16 58 07

when you click on an icon, it will either take you to the configuration page (if plugin is configurable) or submits a form (with your confirmation) to enable/disable the plugin (if the plugin is not configurable -- so most of the build in ones)

I also added links to the notification plugins back to the alerts page:

screenshot 2016-12-07 17 08 12

@ckj / @dcramer thoughts?

**Comment by dcramer** [comment]
damn one year ago

gonna close this out since this will all change now

**Pull request closed without merging**
