### PR TITLE
fix(crons): Make check-in status enum case match scenario

### PR DESCRIPTION
**Pull request by shaedrich**
When "job has completed successfully", status should be "ok" instead of "inProgress"

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Comment by shaedrich** [comment]
Well, it's not my fault, it's stale 🤷🏻

**Comment by shaedrich** [comment]
Are you sure you want to close PR just because you can't look at it in time?

**Comment by evanpurkhiser** [comment]
Sorry this didn't get routed correctly. Taking a look!

**Comment by shaedrich** [comment]
Thanks a lot!

**Review by evanpurkhiser — APPROVED** [review]

**Comment by evanpurkhiser** [comment]
Thanks for fixing this!

**Comment by shaedrich** [comment]
You're welcome!

**Pull request merged**
