### PR TITLE
add details link to shared issue

### PR DESCRIPTION
**Pull request by scotchka**
https://github.com/getsentry/sentry/issues/4936

### CODE REVIEW

**Comment by scotchka** [comment]
need to add test

**Comment by mattrobenolt** [comment]
Mind attaching a screenshot since this is a visual change?

**Comment by scotchka** [comment]
Logged In:

screen shot 2017-03-19 at 2 16 59 pm

Not Logged In:

screen shot 2017-03-19 at 2 27 41 pm

**Review by MaxBittker — APPROVED** [review]
looks good to me 💯 thanks Henry!

**Pull request merged**
