### PR TITLE
fix(ui): Remove useless tooltip

### PR DESCRIPTION
**Pull request by evanpurkhiser**

### CODE REVIEW

**Review by matejminar — APPROVED** [review]

**Review by priscilawebdev — APPROVED** [review]
Perhaps you could have replaced it with the label prop, helping our app to become more accessible 😉

**Comment by benvinegar** [comment]
> Perhaps you could have replaced it with the label prop, helping our app to become more accessible 😉

What if we made this some kind of lint rule? "At least one accessible prop must be specified", something like that.

**Comment by priscilawebdev** [comment]
@benvinegar Good idea! I'll check if we can do that 😉

**Comment by EvanPurkhiser** [comment]
I think what would be great is if we could have it check if the children is text, and use that as the accessible label value :)

Though, I would be pretty surprised if screen readers couldn't already correctly read the buttons text?

**Comment by matejminar** [comment]
@EvanPurkhiser  I think we are already doing that

https://github.com/getsentry/sentry/blob/653303294e38ae7b6f4fd009ab9dd1d9befba82a/src/sentry/static/sentry/app/components/button.tsx#L81-L85

**Comment by EvanPurkhiser** [comment]
Nice :) I thought we were, but didn't want to say without checking first!

**Comment by priscilawebdev** [comment]
good catch @matejminar

**Pull request merged**
