### PR TITLE
feat(react): Add loader to <Button>

### PR DESCRIPTION
**Pull request by billyvg**
View https://percy.io/getsentry/sentry-storybook/builds/350375 for component diff

### CODE REVIEW

**Comment by getsentry-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by MaxBittker** [comment]
i think the slight shift up looks a little worse in the organization header, but it's not a big deal.

**Comment by MaxBittker** [comment]
also, ideally the button wouldn't get horizontally larger when the spinner started, which might mean it would need a "canbebusy" flag or you could observe whether busy was actually falser or completely undefined? that might be confusing behavior either way, not worth blocking this PR probably

**Review by MaxBittker — APPROVED** [review]
lgtm, but the vertical alignment change and the growing shrinking behavior should probably be revisited if they manifest a lot in-app

**Comment by billyvg** [comment]
@MaxBittker 

* replaced spinning indicator with a simple opacity change for "busy" state
* added support for tooltips with `title` prop
* refactored props so we're not redeclaring the same ones

**Pull request merged**
