### PR TITLE
test: add required testing on Python 3.8.12

### PR DESCRIPTION
**Pull request by joshuarli**
This shouldn't be merged until we're ready to attempt the initial full deploy, which could break beyond what we can ensure in tests.

Since this introduces a lot of additional CI I'm trying to keep the window of enforcing 3.8 tests passing in addition to 3.6 to just 3.8 tests at a minimum. The ideal situation is we merge this, deploy 3.8 to great success, then remove all of 3.6. But if the 3.8 deploy doesn't go well, we should keep enforcing 3.6 + 3.8 tests passing.

Note, visual snapshotting is disabled on 3.8, and when we make the switch to it I'll enable it in the PR and don't think there'll be any differences.

Gonna need to change repo settings again for these new check titles. And again when 3.6 is removed.

### CODE REVIEW

**Comment by joshuarli** [comment]
Hmm, can't reproduce charcuterie tests: `collecting ... collected 1 item / 1 deselected`

It collects for me locally.

**Comment by joshuarli** [comment]
Ok, great success now.

**Comment by armenzg** [comment]
> Gonna need to change repo settings again for these new check titles. And again when 3.6 is removed.

Ideally, one day we won't need to do this. We could use this API to determine the current set of required checks.
https://docs.github.com/en/rest/reference/repos#get-status-checks-protection

**Review by armenzg — APPROVED** [review]
lgtm.

Thanks for your diligent comments throughout about the matrix total.

Ideally, we could find a trick to calculate it. Maybe we can do something in bash and then set it as a variable. I have not thought through if it would work.

**Review by billyvg — APPROVED** [review]

**Pull request merged**
