### PR TITLE
fix(hybridcloud) Don't capture valid notification queries as errors

### PR DESCRIPTION
**Pull request by markstory**
Remove the assert that was trying enforce user/team conditions. The logic used in deletions removes all notifications for a project which is valid query.

Fixes SENTRY-11C0

### CODE REVIEW

**Comment by corps** [comment]
Interesting, what's the context?

**Comment by markstory** [comment]
> Interesting, what's the context?

Project deletions cascade into notification settings. This will be problematic in the future because those records are in different silos, but those queries are still reasonable to run until we address deletions in siloed mode.

**Review by corps — APPROVED** [review]

**Comment by vbro** [comment]
> The logic used in deletions removes all notifications for a project which is valid query.

Is this new logic? Or perhaps it used to make 2 calls, one to delete all the user notifications for the project and another to delete team notifications for the project?

**Review by vbro — APPROVED** [review]
LGTM, with comment

**Comment by markstory** [comment]
This assert is newish. I added it in https://github.com/getsentry/sentry/commit/01b3fa7b08e09f48f1d8158982160e71d1403766 . I was fixing a cross silo joined load during audit log saving. I failed to anticipate that `actor_key` would also be null due to mistakes elsewhere or just missing test coverage.

**Pull request merged**
