### PR TITLE
fix(replays): Fix console hovering to the exact time

### LINKED ISSUE #36014: Bug: Fix Console so that hovering over rows highlights the timestamp in the other components, currently this works when hovering the timestamp
If you hover over a timestamp in the Console component then the `currentHoverTime` is set and the rest of the page lights up 

Example Replay:
https://dev.getsentry.net:7999/organizations/sentry-emerging-tech/replays/ben-test:cd7824017b744d3b88473be9c2f72ebc/#console

Image

Hovered putting the cursor to the left of the timestamp doesn't have the same effect. It should.

Also it looks like the hovered time is wrong, it's probably using `less-than` somewhere, and it should be `less-than-equal`.

### PR DESCRIPTION
**Pull request by jesus4497**
Before when you hovered on a timestamp (for example a breadcrumb one), it would highlight the closest console message relative to that timestamp, which is not the correct behavior - changed it to highlight the console message only when the timestamp is exact to that of the console. Closes #36014 

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Comment by ryan953** [comment]
> timestamp is exact

The odds of it being the exact timestamp seem really really small to me. These are measured in miliseconds.

Can we instead make it highlight the row where the timestamp is <= currentTimestamp

something like:

```javascript
const beforeHoverCrumbs = crumbs.filter(crumb => crumbs.time <= currentHoverTime);
const lastCrumb = findCrumbWithHighestTimestamp(beforeHoverCrumbs)
...
isActive={crumb === lastCrumb}
```

getPrevBreadcrumb() is supposed to be doing something like this, with the `allowExact` param. Seems it's not working.

**Comment by jesus4497** [comment]
> > timestamp is exact
> 
> The odds of it being the exact timestamp seem really really small to me. These are measured in miliseconds.
> 
> Can we instead make it highlight the row where the timestamp is <= currentTimestamp
> 
> something like:
> 
> ```js
> const beforeHoverCrumbs = crumbs.filter(crumb => crumbs.time <= currentHoverTime);
> const lastCrumb = findCrumbWithHighestTimestamp(beforeHoverCrumbs)
> ...
> isActive={crumb === lastCrumb}
> ```
> 
> getPrevBreadcrumb() is supposed to be doing something like this, with the `allowExact` param. Seems it's not working.

Correct me if I'm wrong! But won't this cause this behavior: 

Screen Shot 2022-08-17 at 10 48 25 AM


Where we are hovering over a focus at 3:25 and it's highlighting the first console message which is at 0:01

**Comment by ryan953** [comment]
> Where we are hovering over a focus at 3:25 and it's highlighting the first console message which is at 0:01

I think that's ok. 

In this example if you hover the Timeline at 3:20
- then the breadcrumb at 0:36 will light up
- so some console message should also highlight, it's going to be a 0:01

if we used the "only exact" logic then hovering over either the Timeline or breadcrumbs would never (really close to never) trigger a highlight in the Console section. The only time anything in Console would be highlighted is when your mouse is inside that section, which is only half the benefit.

**Comment by jesus4497** [comment]
**Update:** We had an internal conversation and decided to change the "exact logic" to work with seconds instead of milliseconds, so the highlighting won't be that confusing to the user and allowing us to highlight more easily these events

**Comment by danecando** [comment]
I hadn't read this conversation before I talked to Jesus about it but that made sense to me. The hover highlight is meant to bring focus to things happening at that particular time in the replay. Milliseconds are too exact but if I'm highlighting a crumb or certain time anything happening on the same second or at least relatively close to it is particularly interesting. I think highlighting something at a timestamp just because it was the last or most recent one isn't very helpful in that context especially if it's time is not close with the timestamp being hovered.

**Pull request closed without merging**
