### PR TITLE
Migrations Considered Harmful: Week 1

### PR DESCRIPTION
**Pull request by wedamija**
Note: This migration won't be merged. Please don't review or comment on this if you're not participating 
in MCH.

Welcome to Week 1 of Migrations Considered Harmful. The goal of MCH is to have a member on each
team who can confidently review migrations, and hopefully have fewer outages related to them.

Each week I'll put up a pr with a migration, you look at it and prepare (but don't submit) your
review. Then at the same time each week everyone can submit their reviews, and we can discuss in
our weekly meeting.

Our first migration is removing a column from the incidents table. Is there anything wrong with this 
migration? If so:
- What problems will it cause?
- Why does this migration cause problems?
- How should we fix it?

Feel free to link to docs if there are things that already explain how to improve the migration.

### CODE REVIEW

**Review by iProgramStuff — COMMENTED** [review]
re: `is_dangerous`: It might be safer to mark this as dangerous and have ops manually run it but I think this should be okay.

re: `atomic`: This is a fairly low volume table (and only ~700k rows), so grabbing an exclusive lock should be easy enough, meaning atomic can be kept True (?). I also think adding a column is more expensive than deleting one, but not sure.

The generated SQL looks fine to me, so I don't think we need to manually write it to get rid of anything janky that was automatically generated.

You have some failing code that is relying on this field, you could consider removing all Django references to it and apply a state migration before applying a database migration to be safer...but I don't think we need to do that here.

There is a conflict in the migrations_lockfile.txt. This probably means someone merged a migration before you and you'll need to produce a new migration to fix this (I usually just edit the migration file name, its dependency file name, and change the lockfile manually)

**Review by JoshFerge — COMMENTED** [review]
Looks low risk, parameters on migration look good, generated SQL also looks good. Do see that we are referring to this field in other places, would need to remove those references before merging and running this migration.

**Comment by mgaeta** [comment]
Which dependent object do you intend to remove with the `CASCADE` option? If none, then remove this option. Otherwise this might remove an important and needed index.

@getsentry/owners-migrations How many rows can we alter in a migration before we'd need scheduled downtime? If 700k is above that threshold then `is_dangerous` should be set to True.

**Review by wmak — COMMENTED** [review]
Should be marked is_dangerous, incidents is a fairly large table but on top of that because of the `CASCADE` on the drop column, I think we're going to drop rows in other tables that have a dependency here, which might be an unexpected side effect?

**Pull request closed without merging**
