### PR TITLE
chore(api): Make `List Issues to be Resolved in a Particular Release` Endpoint Experimental

### PR DESCRIPTION
**Pull request by isabellaenriquez**
https://docs.sentry.io/api/releases/list-issues-to-be-resolved-in-a-particular-release/ should not be public. The endpoint file has publish status to private but these (incomplete) docs come from the old documentation system with JSON. This PR removes the outdated documentation to line up with the status in the endpoint file.

### CODE REVIEW

**Review by JoshFerge — APPROVED** [review]

**Comment by sentaur-athena** [comment]
I don't think this is the right move here. The endpoint is probably marked as private by mistake if it was already public. Let me take a closer look.

**Comment by sentaur-athena** [comment]
How broken are the docs now? Can we migrate it to the endpoint and mark it as public instead? It doesn't seem like a particularly sentry specific endpoint to me so I don't see the reason behind being private.

**Comment by isabellaenriquez** [comment]
@sentaur-athena I believe this was made private pretty recently (https://github.com/getsentry/sentry/pull/62954). The JSON documentation was also missing information, as pointed out by Dhrumil (see the 200 response at https://docs.sentry.io/api/releases/list-issues-to-be-resolved-in-a-particular-release/).

**Comment by sentaur-athena** [comment]
I saw that. I still think it shouldn't be private. To unblock you can you please remove the doc and mark the API as `experimental`. I'll follow up with @scefali when he's back.

**Review by sentaur-athena — APPROVED** [review]

**Pull request merged**
