### PR TITLE
feat(tags): Add protected tags to API to prevent deletion

### PR DESCRIPTION
**Pull request by tkaemming**

### CODE REVIEW

**Comment by tkaemming** [comment]
This is for GH-6987 (cc @lynnagara)

**Comment by tkaemming** [comment]
We're going to use tag data for sorting when environment filters are enabled, so we don't want to allow this data to be deleted.

**Review by mattrobenolt — APPROVED** [review]
This sounds like a good thing.

Maybe also `release`? It feels like there are many tags we shouldn't allow deletion.

**Review by evanpurkhiser — APPROVED** [review]
🛡

**Comment by getsentry-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Pull request merged**
