### PR TITLE
Invert report arrows

### PR DESCRIPTION
**Pull request by ckj**
% changed indicators now make more sense

screen shot 2016-08-11 at 5 31 13 pm

@getsentry/ui @tkaemming

---

This change is [Reviewable](https://reviewable.io/reviews/getsentry/sentry/3925)

### CODE REVIEW

**Comment by benvinegar** [comment]
Whoa shouldn't these be the other way around?

**Comment by benvinegar** [comment]
I hope obvious troll is obvious :)

**Comment by ckj** [comment]
> I hope obvious troll is obvious :)

Not obvious because of the back and forth we've had on these IRL... 

Gonna 🚢

**Comment by dcramer** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3925)*

**Pull request merged**
