### PR TITLE
Add Team: Crons label

### PR DESCRIPTION
**Pull request by hubertdeng123**
~Removing core-ui and frontend labels~

Add Team: Crons label

### CODE REVIEW

**Review by asottile-sentry — APPROVED** [review]

**Comment by chadwhitacre** [comment]
Are the labels empty currently? We should reroute all open tickets before landing this.

**Comment by evanpurkhiser** [comment]
unfortunate people are editing these manually 😢

**Comment by evanpurkhiser** [comment]
Oh wait this is actually removing them, nvm yeah what chad said

**Review by chadwhitacre — CHANGES_REQUESTED** [review]
Reroute open tickets first.

**Comment by hubertdeng123** [comment]
Currently rerouting tickets as we speak

**Comment by chadwhitacre** [comment]
We have https://github.com/getsentry/team-ospo/issues/60 for a bigger cleanup, this is quick fixes because we have a lot of tickets to triage piled up on these old labels (particularly core-ui).

**Review by emmatyping — APPROVED** [review]

**Comment by chadwhitacre** [comment]
FYI decided to keep Core UI.

not-dead-yet

**Comment by chadwhitacre** [comment]
We still have 10 open Frontend issues. Since those are all triaged (yes?) and the main reason for this PR was to deal with Core UI which we're now leaving, want to drop the Frontend removal and now make this just about adding Crons? 😅

**Comment by hubertdeng123** [comment]
Yes, we can deal with frontend and core ui some other time if needed

**Review by chadwhitacre — APPROVED** [review]

**Pull request merged**
