### PR TITLE
license: Switch to Apache 2.0

### LINKED ISSUE #5698: Switch license to Apache 2
Let's do it.

### PR DESCRIPTION
**Pull request by dcramer**
Fixes GH-5698

### CODE REVIEW

**Comment by getsentry-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Do not modify the License</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Review by mattrobenolt — APPROVED** [review]
IANAL

Also, does this affect any of our License comment headers in source code?

**Comment by mattrobenolt** [comment]
> Do not modify the License

Lol

**Comment by dcramer** [comment]
@mattrobenolt it does, putting discussion in attached ticket

**Comment by mattrobenolt** [comment]
We definitely reference BSD in source code. 

Also https://github.com/getsentry/sentry/blob/master/setup.py#L207

**Pull request closed without merging**
