### PR TITLE
feat: Added basic span handling in store

### PR DESCRIPTION
**Pull request by mitsuhiko**
This is not really useful as it stands, I think we need to rethink this a bit
but it's good enough for now I belive.

This depends on https://github.com/getsentry/semaphore/pull/179

### CODE REVIEW

**Comment by mitsuhiko** [comment]
I hacked this together to make session store work but I'm not sure this makes any sense for a longer term solution.

**Comment by mitsuhiko** [comment]
@alex-hofsteede There is a dummy function that gets invoked now doing nothing.

**Comment by HazAT** [comment]
@mitsuhiko The rust normalization strips away spans.
```
{u'_meta': {u'spans': {u'': {u'err': [u'invalid_attribute']}}}, ...
```

**Comment by mitsuhiko** [comment]
@HazAT any chance you are running an old version of semaphore? Spans were added a while back: https://github.com/getsentry/semaphore/commit/aa3b92b48755bd178f28e472ca79f87249c6f631

**Comment by HazAT** [comment]
@mitsuhiko I just ran `make develop` on this branch.
It's probably because I don't have `semaphore` installed with editable or something.

**Comment by mitsuhiko** [comment]
I think that might be because this branch is outdated in comparison to master. Merge master in, make develop and that should fix it (i hope).

**Comment by HazAT** [comment]
That fixed it, rebased master and force pushed.

**Comment by alex-hofsteede** [comment]
@mitsuhiko I'm going to take this over and see if I can get the events sent into eventstream/kafka.

**Pull request closed without merging**
