### PR TITLE
fix(replays): Remove dashes from issues/trace requests

### LINKED ISSUE #38001: Bug: Errors are not correctly showing up on the Details header and Issues tab
See https://sentry.io/organizations/sentry/replays/javascript:bb62563b-2e9f-474a-b907-f981603057a2/?t_main=console (there should be 3 errors associated with it, Index page displays countErrors correctly).

### PR DESCRIPTION
**Pull request by ryan953**
Show data in Issues and Traces tabs again:
Screen Shot 2022-08-18 at 10 12 31 AM
Screen Shot 2022-08-18 at 10 12 38 AM

Fixes #[#38002](https://github.com/getsentry/sentry/issues/38002)

### CODE REVIEW

**Comment by JoshFerge** [comment]
where do dashes in the replay_id happen in the first place?

**Comment by ryan953** [comment]
> where do dashes in the replay_id happen in the first place?

I think it comes from here: https://github.com/getsentry/sentry-replay/blob/main/src/session/Session.ts#L74

**Comment by JoshFerge** [comment]
@ryan953 i believe dashes don't make it into the backend

**Review by JoshFerge — APPROVED** [review]

**Comment by JoshFerge** [comment]
will look into adjusting on replay index

**Comment by ryan953** [comment]
closing this. It's a better fix to reformat the uuids before including them in the api responses. It shouldn't send formatted replayId's to the front-end.

**Pull request closed without merging**
