### PR TITLE
from six.moves import reduce() and xrange() for Python 3

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by mitsuhiko** [comment]
Might as well use range for this. Generally though this should go into a compat module.

**Comment by cclauss** [comment]
Are the [tests failing](https://travis-ci.org/getsentry/sentry/builds/266615170?utm_source=github_status&utm_medium=notification) because of these changes?  If so, what fixes do you suggest?  I am having a hard time making sense of the Travis output.

**Comment by dcramer** [comment]
I'm guessing that our linters weren't catching these? (Granted not sure if flake8 let's you do actual import namespace checks)

**Comment by getsentry-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by cclauss** [comment]
Ready for (careful) review.  Much discussion is on #6030

**Pull request closed without merging**
