### PR TITLE
Add simulator to device info

### PR DESCRIPTION
**Pull request by mitsuhiko**
This change is [Reviewable](https://reviewable.io/reviews/getsentry/sentry/3723)

### CODE REVIEW

**Comment by dcramer** [comment]
One thought, would it be better to do X (Simulator) rather than just X Simulator

---

Reviewed 3 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3723#-:-KMefSj84SRW_spQ1C8n:-235810639)*

**Comment by mitsuhiko** [comment]
@dcramer the device family reported by ios is "iPhone Simulator" and not "iPhone (Simulator)" so I figured we should try to match it.

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3723#-:-KMeiOEB62MDRAVb0J0f:-1965347980)*

**Comment by mitsuhiko** [comment]
That said, i have no idea if that makes sense for Android :)

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3723#-:-KMeiWxb0aGsrnHthoWq:1592220212)*

**Comment by dcramer** [comment]
I'm still +1on getting this change in

**Comment by dcramer** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3723)*

**Comment by mitsuhiko** [comment]
I'm going to revisit this PR now. I'm still not super happy with some of the effects it has.

**Pull request closed without merging**
