### PR TITLE
fix(projects): Allow subject prefix to be blank

### PR DESCRIPTION
**Pull request by wmak**
- This allows the field to be emptied again
    - currently the field starts empty, but if you enter text and empty
      it again the field will error.

### CODE REVIEW

**Comment by EvanPurkhiser** [comment]
Would be nice for the `fix` in the commit to have some scope, maybe `projects`?

**Comment by dashed** [comment]
@wmak which JIRA/asana ticket does this fix refer to? Want to see the context for this fix.

**Comment by wmak** [comment]
@dashed https://getsentry.atlassian.net/browse/ISSUE-629 and 👍  I'll update the commit to include `projects`

**Comment by dashed** [comment]
@wmak gotcha thanks 👍 Makes sense. 


Any chance we can have a test case for this in https://github.com/getsentry/sentry/blob/master/tests/sentry/api/endpoints/test_project_details.py (unsure if this is the right file 👀 ) ?

**Review by dashed — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
