### PR TITLE
feat(performance): Add top events to the metrics datasets

### PR DESCRIPTION
**Pull request by wmak**
- This allows topEvents to be used for both the metrics dataset and the metricsEnhanced dataset
- This does not use the metrics layer since that's currently being reworked

### CODE REVIEW

**Review by shruthilayaj — APPROVED** [review]
the pyproject.toml file changes look accidental? but otherwise lgtm

**Comment by wmak** [comment]
@shruthilayaj I think its intentional based on this CI action: https://github.com/getsentry/sentry/pull/57371/commits/a47fc3c934f37e1ce9dd4c76fc62dcb81a2cd997

**Comment by asottile-sentry** [comment]
> @shruthilayaj I think its intentional based on this CI action: [a47fc3c](https://github.com/getsentry/sentry/commit/a47fc3c934f37e1ce9dd4c76fc62dcb81a2cd997)

yeah this PR was based on an old master and fixed a single file so the diff looks a little bit weird

**Comment by wmak** [comment]
@asottile-sentry woops, should I not have merged?

**Comment by asottile-sentry** [comment]
nope you were fine!  if you look at the merge commit it made it only touched the one line for the file you fixed \o/

**Pull request merged**
