### PR TITLE
feat(rules): suspect commits and issue owner rules support for mobile languages

### PR DESCRIPTION
**Pull request by barkbarkimashark**
This PR adds support for the following:

|                    | kotlin | swift | react-native | flutter |
|--------------------|--------|-------|--------------|---------|
| suspect commits    |    ✓   |   ✓   |       ✓      |    ✓    |
| issue/code owners  |    ✓   |   ✓   |       ✓      |    ✓    |
| stacktrace linking |    ⨯   |   ⨯   |       ⨯      |    ⨯    |

Please note, the contents of this PR have already been reviewed - I held off on merging to master to keep everything in sync.

### CODE REVIEW

**Comment by barkbarkimashark** [comment]
Would it make sense to release this internally first before putting it out in the wild? I have no reason to believe this functionality has any major risks to our customers though - just a thought.

**Review by wedamija — APPROVED** [review]
Looks good to me. Let's deploy this some tomorrow when you'll be around to monitor it. Also let's make sure this gets deployed individually, so that it's easy to roll back if there are any issues. So basically:
 - hit deploy in freight
 - merge
 - hit deploy again after 30s so that your deploy is isolated

**Review by wedamija — COMMENTED** [review]
fwiw I think that it might be better merging these things piecemeal for the next project - makes it easier to isolate any individual issues that could come up

**Comment by barkbarkimashark** [comment]
> fwiw I think that it might be better merging these things piecemeal for the next project - makes it easier to isolate any individual issues that could come up

Yeah, will do. I realize it doesn't make sense to hold off on the merging until everything is finished.

**Pull request merged**
