### PR TITLE
feat(sdk): update to latest

### PR DESCRIPTION
**Pull request by DominikB2014**
Update to latest SDK, the motivation is to fix incorrect sizes in the resource module such as
image

Due to an SDK bug.

### CODE REVIEW

**Comment by AbhiPrasad** [comment]
@0Calories are we good to move off the alpha?

**Comment by 0Calories** [comment]
@AbhiPrasad I got enough data for the experiment for now so it's fine to switch off, thanks for checking in!

**Review by AbhiPrasad — APPROVED** [review]

**Comment by billyvg** [comment]
https://github.com/getsentry/sentry/pull/60876 will fix this

**Comment by DominikB2014** [comment]
> #60876 will fix this

@billyvg looks like we're updating the SDK there too, i'll drop this PR in favour of that one.
Thank you!

**Pull request closed without merging**
