### PR TITLE
fix(webpack): set cross origin loading to anonymous

### PR DESCRIPTION
**Pull request by JonasBa**
From https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin
```
anonymous
Request uses CORS headers and credentials flag is set to 'same-origin'. There is no exchange of user credentials via cookies, client-side SSL certificates or HTTP authentication, unless destination is the same origin.
```

Tldr, I was debugging this when trying to see why frames from our CDN bundle are omitted from profiles and I think it is because they are not treated as same-origin (we are currently not passing crossorigin=anonymous(

From https://wicg.github.io/js-self-profiling/
```
11.2 Cross-origin execution
Cross-origin execution contexts should not be observable by the API through the realm check in the [take a sample](https://wicg.github.io/js-self-profiling/#dfn-take-a-sample) algorithm. Cross-origin iframes and other execution contexts that share an [agent](https://tc39.es/ecma262/multipage/#agent) with a profiler will therefore not have their execution observable through this API.
```

### CODE REVIEW

**Review by billyvg — APPROVED** [review]
Will there be any unexpected side effects from this?

**Comment by JonasBa** [comment]
@billyvg I am not sure, I am tempted to say no since we dont need credentials to be sent to cdn chunks (and we are not sending them now anyways). That said, my knowledge around this is not great so I would like to first deploy to staging and test it out

**Review by mdtro — APPROVED** [review]

**Comment by JonasBa** [comment]
This has been open for a while, but I just manually tested by loading a file from a cdn using crossOrigin=anonynmous and running the profiler confirmed the frames get correctly picked up by the profiler whereas they were omitted before

**Comment by billyvg** [comment]
:shipit:

**Pull request merged**
