### PR TITLE
feat(ui): More padding fixes for Group "extras"

### PR DESCRIPTION
**Pull request by billyvg**
e.g. Annotations, loggers, etc

image
image
image

image
(old):
image

### CODE REVIEW

**Comment by markstory** [comment]
Locally all my issues have a 0 comments icon showing. Is that intentional, or should the comment count only show when it is > 0?

**Comment by billyvg** [comment]
@markstory oops forgot to push some changes

**Comment by billyvg** [comment]
@markstory 	also looks like firefox needs that `translateY` :/

**Comment by billyvg** [comment]
This is what it looks like on my firefox:
image

**Review by markstory — APPROVED** [review]

**Pull request merged**
