### PR TITLE
ref(dynamic-sampling): Update Health Check copy

### PR DESCRIPTION
**Pull request by ale-cota**
Updated Health Checks priority name and helper text

### CODE REVIEW

**Comment by priscilawebdev** [comment]
@ale-cota you will have to update the unit tests too otherwise you can't merge the PR https://github.com/getsentry/sentry/blob/68f3e3678a3893d41a48a7b9a9519a76c3755af0/static/app/views/settings/project/dynamicSampling/dynamicSampling.spec.tsx#L77

**Comment by priscilawebdev** [comment]
I took the liberty of updating the title of your pull request too...hope you don't mind

**Comment by ale-cota** [comment]
Thanks, @priscilawebdev! I guess that's where my skills end 🙈 @matejminar would you be able to update the unit tests, please? 🙏 Thank you!

**Review by matejminar — APPROVED** [review]
Looks good to me.

**Review by priscilawebdev — APPROVED** [review]
LGTM

**Pull request merged**
