### PR TITLE
Set max workers to encourage jest to use 2 cores

### PR DESCRIPTION
**Pull request by mattgauntseo-sentry**
From: https://dev.to/ddoice/fix-slow-tests-with-jest-in-github-actions-5h00

Unsure if --runInBand is necessary, so would be good to confirm.

If tests this reduced run time by 2 ~ 4mins

### Run 1

0: 8m 32s
1: 7m 21s
2: 6m 34s
3: 6m 29s

### Run 2

0: 6m 59s
1: 8m 54s
2: 5m 9s
3: 6m 35s

### Run 3

0: 7m 53s
1: 6m 57s
2: 5m 34s
3: 6m 32s

### Run 4

0: 10m 29s
1: 6m 47s
2: 7m 52s
3: 6m 28s

You can compare this to commits on the default branch, but rounding down each run for the last 4 runs and the average duration is:

0: 13m 30s
1: 12m 15s
2: 8m 45s
3: 14m 0 s

With this change, rounding up each run, the avg is:

0: 8m 45s
1: 8m 45s
2: 6m 45s
3: 7m 0 s

### CODE REVIEW

**Comment by scttcper** [comment]
Do workers have 2cpus? Would it make sense to use --maxWorkers=100% if that changes

**Comment by mattgauntseo-sentry** [comment]
At the moment the GitHub hosted runners have 2 cores according to this: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

My understanding of [dev.to/ddoice/fix-slow-tests-with-jest-in-github-actions-5h00](https://dev.to/ddoice/fix-slow-tests-with-jest-in-github-actions-5h00) is that max workers of 100% will actually be 1 core, but I'll set it to 100% and see the affect.

**Comment by mattgauntseo-sentry** [comment]
0: 9m 17s
1: 6m 13s
2: 5m 38s
3: 6m 22s

So similar times as `maxWorkers=2`, so definitely preferable.

**Review by evanpurkhiser — APPROVED** [review]
I'm so about it

**Review by scttcper — APPROVED** [review]

**Pull request merged**
