### PR TITLE
Add Crystal icon to the .context-item

### LINKED ISSUE #16443: Crystal language icon
## Summary

Would you mind adding [Crystal](https://crystal-lang.org) icon within the section below?

image

SVG icon is available at https://crystal-lang.org/assets/media/crystal_icon.svg

I can post a PR if needed, just wanted to know beforehand would you be willing to accept it.

## Motivation

Would be a nice touch for Crystal-based users.

### PR DESCRIPTION
**Pull request by Sija**
image

Fixes #16443

### CODE REVIEW

**Comment by dashed** [comment]
@Sija thanks! Someone will take a look at it.

**Comment by Sija** [comment]
@dashed Sweet, thank you!

**Comment by dashed** [comment]
@matejminar Dora will sign off on the icon.

**Comment by matejminar** [comment]
Cool. In terms of code - it looks good to me 👍

**Review by doralchan — APPROVED** [review]

**Review by matejminar — APPROVED** [review]

**Pull request merged**
