### PR TITLE
feat: Expect-Staple and Expect-CT support

### PR DESCRIPTION
**Pull request by alex-hofsteede**
Refactored the CSP endpoint and helpers to allow for support of HPKP violation reports. Added schema validation and filtering logic to make it easier to add more interface schemas in future.

Requires some more tests.

### CODE REVIEW

**Comment by getsentry-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Review by mattrobenolt — COMMENTED** [review]
This is a big change, so just letting you know I'm looking at it and will get back to you. :)

**Comment by graingert** [comment]
@alex-hofsteede any chance of doing Expect-Staple at the same time?

**Comment by alex-hofsteede** [comment]
Yeah, Expct-Staple is next on the list.

**Review by mattrobenolt — CHANGES_REQUESTED** [review]
All of this looks fine. The only missing piece is the UI to display these.

Would really like to address the urls though before approving. But code seems good otherwise..

**Comment by alex-hofsteede** [comment]
@mattrobenolt so this  can go out?

**Review by mattrobenolt — APPROVED** [review]
:tada: looks great, let's make sure we coordinate a change for the new endpoint with ops.

cc @JTCunning 

We'll need a location block for `/api/<project>/security/` that's identical to the current `/api/<project>/csp-report/`

( this can happen after this gets shipped since it's not really used yet )

**Comment by leonelwilliams** [comment]
I'm a bit late to the party (sorry) but it looks like the expect-staple header isn't something that's implemented by UAs and may never ship? See https://twitter.com/estark37/status/949336829349707776 for information (and a note on the preload version of expect-staple)

As an aside: HPKP may also be on the [chopping block](https://groups.google.com/a/chromium.org/d/msg/blink-dev/he9tr7p3rZ8/eNMwKPmUBAAJ) but still exists for now.

**Pull request merged**
