### PR TITLE
feat(replay): Refetch the viewed-by data after an update to it

### PR DESCRIPTION
**Pull request by ryan953**
This follows https://github.com/getsentry/sentry/pull/69232 which removed some optimistic updated that would cause crazy re-rendering. Instead we'll just invalidate (and re-fetch if needed) the `/viewed-by/` endpoint data.

This is related to the viewed-by replay project:
https://github.com/getsentry/team-replay/issues/19
https://github.com/getsentry/sentry/issues/64924

### CODE REVIEW

**Review by billyvg — APPROVED** [review]
Would this refetch on the same page view? Ie if I visit replay details for first time would my avatar be in the viewed by? Or would it just invalidate for the next page view?

**Comment by ryan953** [comment]
> Would this refetch on the same page view? Ie if I visit replay details for first time would my avatar be in the viewed by? Or would it just invalidate for the next page view?

Fixed it so it'll refetch on the same pageview. This makes it so your own icon will pop into place after you view a replay for the first time.

**Comment by billyvg** [comment]
> > Would this refetch on the same page view? Ie if I visit replay details for first time would my avatar be in the viewed by? Or would it just invalidate for the next page view?
> 
> Fixed it so it'll refetch on the same pageview. This makes it so your own icon will pop into place after you view a replay for the first time.

@ryan953 FWIW this differs from issue details where we *never* see ourselves in the view by list (which I guess makes sense on the details page since you'll always have viewed it).

**Comment by ryan953** [comment]
> > > Would this refetch on the same page view? Ie if I visit replay details for first time would my avatar be in the viewed by? Or would it just invalidate for the next page view?
> > 
> > 
> > Fixed it so it'll refetch on the same pageview. This makes it so your own icon will pop into place after you view a replay for the first time.
> 
> @ryan953 FWIW this differs from issue details where we _never_ see ourselves in the view by list (which I guess makes sense on the details page since you'll always have viewed it).

that's true. the issues page uses a component the filters out the current user from the list.  I'd go for that, but i remember we also got feedback that the empty state on Replay Details look funny, and i think it's often the case that a replay hasn't been seen by anyone yet, so it might be more important to solve that too.

**Pull request merged**
