### PR TITLE
Added new read-only member role

### PR DESCRIPTION
**Pull request by jgriffith23**
Addresses issue #4956, "New read-only member role."

When a read-only member attempts to take one of the following actions on an event, their actions do not occur, and they receive the corresponding responses:

- Resolve an event: remains on event page and receives message, "Unable to update events. Please try again."
- Delete an event: is taken through the delete flow and back to the event list, but receives message, "Unable to delete events. Please try again.
- Assign event to a member: remains on event page and receives message, "Unable to change assignee. Please try again."
- Remove artifacts associated with an event: remains on artifact list page and receives message, "Unable to remove artifacts. Please try again."

Read-only members also cannot see the "Project Settings" button from the project page. They can, however, access the "Client Keys (DSN)" page via direct link. Whether they should be able to access those keys is a bit of a philosophical question.

### CODE REVIEW

**Comment by mattrobenolt** [comment]
@dcramer this seems fine to me. Any objections?

**Comment by markstory** [comment]
Thanks for taking the time to put this together, but I don't feel that having the UI appear to work but do nothing is inline with the type of experience we want to provide.

**Comment by alexandrul** [comment]
@markstory so a read-only role will be available out-of-the-box in sentry?

**Comment by markstory** [comment]
@alexandrul Not in the short term. This pull request would have added an incomplete implementation that would create unpleasant experiences for users in that role, as the app would appear sufficiently broken.

**Comment by alexandrul** [comment]
Until that distant future, my choice is to apply this patch manually after each sentry upgrade, since it is very useful for my use case.

The sensible choice would be to merge this PR and put a warning next to this new role in the settings area. After all, if this new role is not used for any users, there will be no UI issues, correct?

**Comment by markstory** [comment]
We will have to disagree on what is sensible then. Thankfully you have the source code and can customize it to your taste.

**Comment by mattrobenolt** [comment]
@alexandrul you don’t need to apply a patch anywhere against Sentey source code. You could just define `SENTRY_ROLES` in your `~/.sentry/sentry.conf.py` and override it entirely. This is 100% what I’d recommend doing instead of patching our source code. This is a configurable variable for a reason, so you have the ability to extend or define your own roles.

**Comment by alexandrul** [comment]
@markstory fully agree with you on this. In my defense, 8.22 has a nice warning for the User Feedback functionality: `Psst! This feature is still a work-in-progress. Thanks for being an early adopter!`. This was setting my expectation that a similar warning could have been also used for this PR. That being said, I respect your decision.

@mattrobenolt thank you very much for the info, I will follow your advice. The current approach was fine with me because I have to check for changes in the builtin roles anyway.

**Comment by caleb15** [comment]
@markstory I can understand that you don't want extra support requests from users that may not understand that they have the read-only role assigned, but giving everyone full access is a security concern that outweighs the cost of a few extra support requests. Customers of sentry that do not have a self-hosted version like myself are not able to patch sentry to get around this issue.

If the PR is merged and support requests become a problem maybe a banner could be added letting the user know they are in read-only mode?

**Comment by dcramer** [comment]
@caleb15 can you please articulate the security concern?

Read access to data for most organizations is just as severe as write access, and if you have employment agreements with folks, that should suffice for your security given _any_ access.

**Comment by caleb15** [comment]
A person with a write role could delete and discard exceptions so they don't become visible or falsely resolve them. It's not a big security concern I admit, I would be more worried about someone accidentally fiddling around with sentry than doing it maliciously.

**Comment by st-sloth** [comment]
Read access is hardly as severe as write access. Say, we need our large support team to have view access to events and maybe write access to comments but their workflow will NEVER include resolving or god forbid deleting issues. And it doesn't really matter whether someone does it maliciously or accidentally, the problem is that they are able to do it and it will happen one way or another.
Thankfully, Sentry access is based on scopes and, in theory, it seems that it would be possible to even create custom roles from the settings. But just read-only member role would already be an extremely welcome addition.

**Comment by dcramer** [comment]
You're right it is technically possible to create a read-only role via the configuration, but the UI is going to behave poorly around it today.

At some point we will expose more advance permissions (it's an ongoing internal conversations), but this has very rarely come up, which is why it's not been pushed up higher in the priority chain.

**Pull request closed without merging**
