### PR TITLE
ref(indexer): backfill use_case_id

### PR DESCRIPTION
**Pull request by MeredithAnya**
**context**
The perf indexer is being transitioned to being the pipeline for generic metrics, and so we've added a `use_case_id` to differentiate between the different use cases this pipeline will support. When this column was created the default was `performance`, however, the `use_case_id` should actually be aligned with the relay namespacing. In relay, the namespace is `transactions` (for performance metrics). 

Currently the performance metrics (`transactions`) is the only use case, and we've haven't merged any code yet that actually uses this attribute to query by (since there is only the one use case). However, this table is still on the ingest path, so it is very high traffic. It is also queried by the product as well when looking up the strings from the indexed values. 

linked OPS ticket: https://getsentry.atlassian.net/browse/OPS-3345

### CODE REVIEW

**Review by wedamija — COMMENTED** [review]
Should we also be changing the default on the model first? Otherwise new rows will continue writing the wrong value

**Comment by MeredithAnya** [comment]
> Should we also be changing the default on the model first? Otherwise new rows will continue writing the wrong value

Oh yeah so forgot to link this but there is a PR that I want to wait for that is going to start writing the correct `transactions` use case:  https://github.com/getsentry/sentry/pull/47284

**Comment by MeredithAnya** [comment]
> > > Should we also be changing the default on the model first? Otherwise new rows will continue writing the wrong value
> > 
> > 
> > Oh yeah so forgot to link this but there is a PR that I want to wait for that is going to start writing the correct `transactions` use case: #47284
> 
> Ok, it's fine if you want to wait, but if `performance` is never correct then it might make sense to change the default anyway? Other than that, this migration looks good to me.

We've starting writing the correct values and should no longer need the default so I've just added a pr to remove it all together: =https://github.com/getsentry/sentry/pull/48972

**Comment by ayirr7** [comment]
We're writing the correct values in, and the default has been removed by a migration.

**Review by wedamija — APPROVED** [review]

**Pull request merged**
