### PR TITLE
Updated Slack integration logo

### PR DESCRIPTION
**Pull request by Roach**
Updated the Slack logo :)

### CODE REVIEW

**Comment by mattrobenolt** [comment]
@EvanPurkhiser is the change in dimensions a problem?

**Comment by Roach** [comment]
@mattrobenolt fixed the dimensions - thanks for calling that out

**Comment by mattrobenolt** [comment]
It seems that your latest commit is still 124x124. Not 400x400. 🤔

**Comment by mattrobenolt** [comment]
image
🤔

**Comment by Roach** [comment]
Apparently our asset downloader doesn't actually resize the default - fixing now...

**Review by MeredithAnya — APPROVED** [review]

**Pull request merged**
