### PR TITLE
DO NOT REVIEW

### PR DESCRIPTION
**Pull request by scefali**

### CODE REVIEW

**Review by dashed — COMMENTED** [review]
This is not a review.

**Comment by scefali** [comment]
@dashed so meta

**Comment by mattrobenolt** [comment]
What’s happening here?

**Comment by scefali** [comment]
@mattrobenolt Just creating a PR so I can copy over some of the changes into a different branch.

**Comment by mattrobenolt** [comment]
What?

**Comment by scefali** [comment]
@mattrobenolt I want to put the UI changes into a different PR that can be reviewed independently. Is there a better way to do this that I am missing?

**Comment by mattrobenolt** [comment]
Cherry pick commits into a different branch? I’m not sure what you’re doing. Or how a PR helps you achieve what you’re trying to do.

**Comment by scefali** [comment]
@mattrobenolt It helps because I can see exactly what files I have changed and then makes it easy to copy the changes to my local environment. Maybe other people do this differently but it works for me.

**Comment by tkaemming** [comment]
https://github.com/getsentry/sentry/compare/master...feat/new_trello_plugin

**Comment by scefali** [comment]
@tkaemming good point, I can just press compare without actually opening it. Thanks!

**Comment by mattrobenolt** [comment]
Also `git diff`.

**Pull request closed without merging**
