### PR TITLE
ref(ui): Fix wrapping on Truncate component

### PR DESCRIPTION
**Pull request by evanpurkhiser**
Soemtimes the ... would wrap to the next line, we don't want that for this component

### CODE REVIEW

**Comment by EvanPurkhiser** [comment]
Now that I think about it maybe we do?

**Comment by priscilawebdev** [comment]
should we check this issue?

**Before:**

image


**After:**

image

**Comment by EvanPurkhiser** [comment]
I think I'll change this to a prop

**Comment by EvanPurkhiser** [comment]
Okay going to deal with this in the future

**Pull request closed without merging**
