### PR TITLE
ref: upgrade grpcio to a version which is built for 3.10

### PR DESCRIPTION
**Pull request by asottile-sentry**

### CODE REVIEW

**Review by joshuarli — APPROVED** [review]

**Review by joshuarli — COMMENTED** [review]
Probably best to hold off on this until Freight can do canary.

**Comment by mwarkentin** [comment]
@joshuarli any idea when that's planned? Google Support is suggesting we upgrade grpcio to attempt to resolve the 500 RST_STREAM errors we've been seeing.

**Comment by untitaker** [comment]
this is technically part of an incident resolution process so if canary deployments are the problem here, I would suggest working with ops to manually deploy one of the save_event workers. I believe that's worth the effort.

**Comment by asottile-sentry** [comment]
canary: not soon enough, if we need manual verification we should approach that route manually (staging / flipping one host) -- though personally I'm not concerned about this upgrade (grpcio is usually fairly stable, and we've already moved past the problematic version) so I'm also not opposed to just sending this out in a deploy on its own

**Comment by joshuarli** [comment]
> @joshuarli any idea when that's planned? Google Support is suggesting we upgrade grpcio to attempt to resolve the 500 RST_STREAM errors we've been seeing.

Oh, well, that changes things, let's do this asap!

**Comment by joshuarli** [comment]
> this is technically part of an incident resolution process so if canary deployments are the problem here, I would suggest working with ops to manually deploy one of the save_event workers. I believe that's worth the effort.

The issue before was in postprocess: https://github.com/getsentry/sentry/pull/23454

But yeah, it wouldn't be much effort for me to do a manual canary.

**Comment by joshuarli** [comment]
Gonna do an s4s deploy for 84711fbd6263a3d2987f08bc7df2c4d0f450b062, don't merge until successful.

**Comment by joshuarli** [comment]
OK, looks great in s4s, this can ship.

**Pull request merged**
