### PR TITLE
fix(component): set shouldBlurOnClose to false so it can open on mobile views.

### LINKED ISSUE #34320: The <CompactSelect> component doesn't open a flyout when rendering in the Chrome Mobile Emulator
Repro: 

1. Visit: https://storybook.sentry.dev/?path=/story/components-forms-fields--compact-select-field
   - Notice you can open the select field and see some options
3. In devtools enable mobile emulation
   - Screen Shot 2022-05-06 at 10 17 14 PM
   - Notice the flyout no longer appears when you click the field.

### PR DESCRIPTION
**Pull request by Danondso**
Closes #34320

Here's a pic of the behavior in prod: 
Screen Shot 2022-05-06 at 1 50 17 PM

Here's my branch with the fix.
image

----

By submitting this pull request, I confirm that Sentry can use, modify, copy, and redistribute this contribution, under Sentry's choice of terms.

### CODE REVIEW

**Comment by billyvg** [comment]
Does this affect how it closes?

**Comment by Danondso** [comment]
> Does this affect how it closes?

On the Discover screen I tried opening it and clicking off, clicking the button after opening to close, and selecting an option. Everything had parity with prod that I could tell.

**Comment by ryan953** [comment]
I don't think this is sufficient.

The proposed fix boils down to "don't use `shouldCloseOnBlur` because the behavior is not correct in a mobile context".
This is insufficient because someone is still empowered to write `<CompactSelect shouldCloseOnBlur />` and have a broken mobile experience. If the real fix is to tell people "never use shouldCloseOnBlur" then we should be removing the prop. That seems like too much though; could we ignore the prop in mobile?

Ignoring the prop in mobile feels like a potential fallback, there's some research I'd read first.
- It looks like `shouldCloseOnBlur` is getting fed into https://react-spectrum.adobe.com/react-aria/useOverlay.html. So I wonder if there are some community notes or workarounds?
- Is there an existing bug, or can we file one against Adobe. It would be ok to wait for a fix and then update our package.json later.

**Review by ryan953 — CHANGES_REQUESTED** [review]
I don't think this is sufficient.

The proposed fix boils down to "don't use `shouldCloseOnBlur` because the behavior is not correct in a mobile context".
This is insufficient because someone is still empowered to write `<CompactSelect shouldCloseOnBlur />` and have a broken mobile experience. If the real fix is to tell Sentry contributors "never use shouldCloseOnBlur" then we should be removing the prop. That seems like too much though; could we ignore the prop in mobile?

Ignoring the prop in mobile feels like a potential fallback, there's some research I'd read first.
- It looks like `shouldCloseOnBlur` is getting fed into https://react-spectrum.adobe.com/react-aria/useOverlay.html. So I wonder if there are some community notes or workarounds?
- Is there an existing bug, or can we file one against Adobe. It would be ok to wait for a fix and then update our package.json later.

**Comment by Danondso** [comment]
@ryan953 I did some looking around on react and found [this issue](https://github.com/adobe/react-spectrum/issues/816) that's essentially the same behavior, a blur event fires right after opening. There's claims of a fix but there's no direct version number pointing to it but there's a [PR](https://github.com/adobe/react-spectrum/pull/2175). I'm curious if a dependency upgrade will fix it and I can go down that path if we're okay with bumping the react-aria version up to 3.15. 

For the sake of time I'm going to get a codesandbox link up that duplicates the problem and create an issue. In the meantime I'll adjust the PR to ignore the prop on mobile. My plan is to check isMobile() since leveraging a media query check gave me really mixed results.

**Comment by Danondso** [comment]
Closing this so the Core UI team can delve into instead of me

**Pull request closed without merging**
