### PR TITLE
feat: Prevent environment tag delete button from being shown

### PR DESCRIPTION
**Pull request by lynnagara**
Just hiding this in the UI for now if the tag key is `environment`!

@tkaemming Not sure if you'd prefer to add a `canDelete` prop to the tags endpoint instead, which I guess would be a bit nicer

screen shot 2018-01-19 at 1 51 26 pm

### CODE REVIEW

**Comment by tkaemming** [comment]
I was planning on adding a list of tags that are protected from deletion so I think it does make sense to pass that down as a `canDelete` attribute. I'll do that tomorrow and follow up here.

**Comment by tkaemming** [comment]
I just landed GH-6998, feel free to rebase and update at update this at your convenience

**Comment by lynnagara** [comment]
@tkaemming Updated

**Review by tkaemming — APPROVED** [review]
👍

**Comment by lynnagara** [comment]
Updated with new design

**Comment by getsentry-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Review by billyvg — APPROVED** [review]

**Pull request merged**
