### PR TITLE
bug(replays): Check for valid node prior to processing click event

### PR DESCRIPTION
**Pull request by cmanallen**
Fixes: https://sentry.sentry.io/issues/4047163153/?project=1&referrer=assigned_activity-slack
Related: https://github.com/getsentry/sentry/issues/45524

### CODE REVIEW

**Review by JoshFerge — COMMENTED** [review]
I don't think DOM elements are required to have ids or tagNames -- could we instead just empty string these?

cc @getsentry/replay-sdk

**Comment by cmanallen** [comment]
@JoshFerge "id" in this context refers to the RRWeb ID.  On the second part, what is the case where the tag name could be empty?

**Comment by billyvg** [comment]
> also, i'm looking at this code again, is `10` a long enough limit for class?

it's true 10 seems a bit low since this is how you write CSS these days (only partially exaggerated):

image

**Comment by cmanallen** [comment]
> which one is the rrweb id vs the id of the html?

Added docstring to that function which attempts to explain the difference.  I also simplified the conditional.  The structure of the node body will obey the node schema or it will not exist at all.  A simple existence check is sufficient.

> also, i'm looking at this code again, is 10 a long enough limit for class?

> 10 seems a bit low 

@billyvg @JoshFerge Unfortunately this limit needs to stay as low as possible while still retaining utility as a search term.  If a list of 10 classes does not give utility then we should not ingest them at all.  Its not practical to index 25, 50, 100 classes for each click.  Especially given our data structure.  If in the future we manage to simplify our data-model (or introduce a specialized UI for DOM search) then this can be revisited and we can make accommodations for these large class lists.

> i'm thinking maybe it's text content?

Text content can be empty string for sure.

**Comment by JoshFerge** [comment]
> > which one is the rrweb id vs the id of the html?
> 
> Added docstring to that function which attempts to explain the difference. I also simplified the conditional. The structure of the node body will obey the node schema or it will not exist at all. A simple existence check is sufficient.
> 
> > also, i'm looking at this code again, is 10 a long enough limit for class?
> 
> > 10 seems a bit low
> 
> @billyvg @JoshFerge Unfortunately this limit needs to stay as low as possible while still retaining utility as a search term. If a list of 10 classes does not give utility then we should not ingest them at all. Its not practical to index 25, 50, 100 classes for each click. Especially given our data-structure and query-patterns. If in the future we manage to simplify our data model (or introduce a specialized UI for DOM search) then this can be revisited and we can make accommodations for these large class lists.
> 
> > i'm thinking maybe it's text content?
> 
> Text content can be empty string for sure.

are class names just an array? i feel like in sentry for tags we can ingest quite large arrays with each event, and we can always add a B-tree index for them to speed up searches. 

We could also consider filtering out tachyon type classnames (the ones where people use classNames instead of css) from being indexed @billyvg wdyt about that?

**Review by JoshFerge — APPROVED** [review]

**Comment by billyvg** [comment]
I was half trolling there -- I suspect class names will not be an ideal way for some customers (including us!) to query. Most of our class names are compiled, so not useful -- likewise for the screenshot I posted (tailwindcss). imo let's stick to this for now and see how it goes, probably push people towards other types of queries like id, data-testid, aria-label

**Comment by cmanallen** [comment]
> are class names just an array?

Yeah just an array.

> i feel like in sentry for tags we can ingest quite large arrays with each event

We should get data on this and see how large those arrays are before acting.  cc @bmckerry 

For each segment there can be a maximum of 20 clicks.  Whatever value we define as our class list max, the upper bound per segment will be 20x.  The index page is then: 10 segments per replay (avg) * 20 click events * `m` classes * every replay in a 14 day time window.  The numbers get large fast.

> we can always add a B-tree index for them to speed up searches.

We're querying over the aggregation so the index is not used.

**Pull request merged**
