### PR TITLE
Improve Clojure rollups by collapsing anonymous module names.

### PR DESCRIPTION
**Pull request by bretthoerner**
#5607 

Uh, @mattrobenolt you self-assigned this one, idk if you want to review for me? :)

I tried my damnest to use just one regex, but had no luck. So it's two regexs and each has to be called in turn.

1. We need to substitute a well known group, either by number (`\1`) or name (`foo`)
2. You can't have multiple groups with the same name (`(?P<name>...)`)
3. Number based groups don't work, (`(?:(thing1)|(thing2))`, `\1` is always `thing1`, even if `thing2` is the first match)

### CODE REVIEW

**Comment by bretthoerner** [comment]
Forgot to say I verified this local with an actual Clojure client. Adding a unit test now.

**Comment by mattrobenolt** [comment]
Can you write a couple test cases for this? Should be trivial, and from me reading this, this seems to be doing not what you'd want exactly. But a test would confirm that. :)

**Comment by bretthoerner** [comment]
Added. 😬

**Comment by bretthoerner** [comment]
The failure is Travis bullshit, btw.

**Review by dcramer — APPROVED** [review]

**Pull request merged**
