### PR TITLE
Jane Doe changed to Orville Wright

### PR DESCRIPTION
**Pull request by bartoszhernas**
Hi, 

I've recently integrated "Feedback form" on our React frontend. It shows iframe to report the feedback with the placeholder "Jane Doe".

Then my CEO who is native UK speaker said that the placeholder sounds really morbid as Jane Doe is mostly used to refer to unknown corpses. #somethingNewLearnedEveryDay

I was asked to change it to something else, but it is not JS configurable, hence the pull request.

Maybe you have other name proposition like "Amelia Earhart" or "Boaty McBoatface" ?

### CODE REVIEW

**Comment by bartoszhernas** [comment]
Screenshot 2019-11-08 15 39 33

**Comment by dashed** [comment]
@bartoszhernas thanks. I'm going to tag @BYK who can make a decision on this.

**Comment by mattrobenolt** [comment]
I'm +1 for Boaty McBoatface though.

Regardless of us making this change, we can't edit the files under `src/sentry/locale/*` since those are all auto generated from Transifex.

Do you mind backing out those changes, and that'll make this much smaller of a PR, then someone more responsible can decide if we wanna make this change or not. :) fwiw I do agree that Jane/John Doe has some potentially negative connotations and we can likely do better.

If we wanted to be fancier, I've seen some software that has a set of say, Nobel Prize winners, and names are generated from that at random, similar to your suggestion of Orville Wright or Amelia Earhart.

**Comment by billyvg** [comment]
+1 Boaty McBoatface

**Review by BYK — CHANGES_REQUESTED** [review]
Let's revert those `.po` file changes and proceed with one of the following:

- Joe Bloggs
- Jane Bloggs
- Fred Bloggs
- Joe Q. Public

Resources:
1. https://en.wikipedia.org/wiki/John_Q._Public
2. https://en.wikipedia.org/wiki/Joe_Bloggs

**Comment by BYK** [comment]
Also, definitely not "Boaty McBoatface" 😁 May be "Jane/Joe Bughunter"?

**Comment by bartoszhernas** [comment]
I've went with `Jane Bloggs`, so the last name is the only change in the end. I reverted translation changes, and now I will just make sure all tests pass. 

Thank you :)

**Review by BYK — APPROVED** [review]
Looks pretty good to me, thanks a lot!

Note to @getsentry/app - we should probably make this a constant?

**Review by dashed — APPROVED** [review]
Looks good to me 👍 

@bartoszhernas thanks!

**Pull request merged**
