### PR TITLE
ref(stores): Make ProjectsStore useLegacyStore compatible

### PR DESCRIPTION
**Pull request by evanpurkhiser**

### CODE REVIEW

**Review by matejminar — APPROVED** [review]
lgtm

**Comment by davidhollin** [comment]
> >  

LGTM 

Actually, nit, but consider providing a brief description here so we know what this change actually does

**Comment by evanpurkhiser** [comment]
@matejminar could I get another review actually.

I ended up removing the `withProjectsSpecified` HoC since it was only used in the `GlobalSelectionHeader` and wasn't really doing anything interesting.

it also made fixing tests a bit easier

**Review by matejminar — APPROVED** [review]
Tested locally, looks good.

**Pull request merged**
