### PR TITLE
fix(dev-env): Pull x86 image for snuba

### PR DESCRIPTION
**Pull request by Zylphrex**
This was trying to pull the ARM image which has not been built since getsentry/snuba#5365. To pull the x86 image, we have to explicitly specify the platform otherwise it'll try to pull the latest ARM image which doesn't exist and silently continues using the previously pulled ARM image.

### CODE REVIEW

**Review by untitaker — APPROVED** [review]

**Comment by joshuarli** [comment]
silently? i fatal with:

```
docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.43/images/ghcr.io/getsentry/snuba:latest/json: Not Found ("No such image: ghcr.io/getsentry/snuba:latest")
```

but yeah we can't pull on apple silicon anymore - lemme see if i can get emulation working

**Comment by Zylphrex** [comment]
> silently? i fatal with:
> 
> ```
> docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.43/images/ghcr.io/getsentry/snuba:latest/json: Not Found ("No such image: ghcr.io/getsentry/snuba:latest")
> ```
> 
> but yeah we can't pull on apple silicon anymore - lemme see if i can get emulation working

I think it's only silent if you have an older ARM image with the `latest` tag on it. Once I deleted my existing image, it started giving the same error.

**Comment by untitaker** [comment]
for what it's worth, the kind of image snuba pushes nowadays should be the same situation as relay, plainly x86.

but there was a time where it was a multiarch image containing arm64 as well. sometime in the past week we stopped publishing the multiarch image, and now this is broken.

**Review by joshuarli — DISMISSED** [review]
blocking this for now - i think this is because tony's using colima 0.6.7 while we have 0.6.2 as a known good version

also instead of specifying arch we should just use `ghcr.io/getsentry/snuba:amd64-latest`
- never mind, apparently its out of date?

**Comment by joshuarli** [comment]
committed some fixes

also people on colima != 0.6.2 are still gonna fail this so not relevant, this is a required fix generally

**Review by evanpurkhiser — APPROVED** [review]

**Pull request merged**
