### PR TITLE
ref(IntegrationDirectory): Increase threshold sensitivity for fuzzy search

### PR DESCRIPTION
**Pull request by NisanthanNanthakumar**
## Objective
Updates the integration search filtering so it matches typos better. 

## UI
Screen Shot 2020-03-23 at 9 20 33 PM
Screen Shot 2020-03-23 at 9 22 02 PM

## Test Plan
Typed common typos into search bar and checked for displayed results. I referred to this Amplitude chart about common search typos without results: [https://analytics.amplitude.com/sentry/chart/tc5r423](https://analytics.amplitude.com/sentry/chart/tc5r423)

### CODE REVIEW

**Review by leeandher — APPROVED** [review]
Probably ping ~~jonesphillip or scefali~~ to test some of the common 'no-result' searches, but if you've done that already it looks good to me

**Review by leeandher — COMMENTED** [review]
Woops clicked Approve when I meant comment, just check with them first

**Comment by leeandher** [comment]
Lol nvm, you already did that, i missed the bottom part with your Test Plan --> LGTM

**Comment by scefali** [comment]
@NisanthanNanthakumar Just to check, if you type in `jiraa` does it work?

**Comment by NisanthanNanthakumar** [comment]
> @NisanthanNanthakumar Just to check, if you type in `jiraa` does it work?

@scefali Yes, I took screenshots of the common misspellings and put it in the UI section of the PR.  `jiraa` is the first picture.

**Comment by scefali** [comment]
@NisanthanNanthakumar My apologies! I should have looked more carefully at the screenshots :)

**Pull request merged**
