### PR TITLE
fix(discoverv2) Check projects in facet map for accessibility

### PR DESCRIPTION
**Pull request by evanh**
Make sure that the user has access to all the projects that the facet map wants
to show.

### CODE REVIEW

**Comment by dashed** [comment]
@evanh can you please add a test case for this?

**Review by markstory — APPROVED** [review]
Looks good if we have a test.

**Review by markstory — APPROVED** [review]
:clap::clap::clap::clap::clap::clap::clap::clap::clap::clap:

**Review by dashed — APPROVED** [review]
Nice 👍

**Pull request merged**
