### PR TITLE
 Ignore GeneratedMethodAccessor suffix

### LINKED ISSUE #13304: Stack traces not grouping because of jdk.internal.reflect.GeneratedMethodAccessor
## Important Details

How are you running Sentry?

* [x] On-Premise docker [Version 9.0.0]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

Stack traces that should be grouped together, aren't, and the major difference I can see is that they have a stack trace element with the class `jdk.internal.reflect.GeneratedMethodAccessor{effectively random number}`. This class moved from `sun.reflect` to `jdk.internal.reflect` so the fix made in #11145 / e4c6600  doesn't help users of JDK11 (possibly earlier, too). 

## Steps to Reproduce

1. Use JDK 11 with some code that uses 
2. Capture an exception that uses Method#invoke somewhere in its call stack. 
3. The captured stack trace will have something like this in it: 

```    
    at jdk.internal.reflect.GeneratedMethodAccessor261.invoke
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:566)
 ```

### What you expected to happen

Ignore the trailing number from the generated method accessor when calculating the grouping for the stacktrace.

### PR DESCRIPTION
**Pull request by thyming**
Fixes #13304

### CODE REVIEW

**Comment by markstory** [comment]
cc @mitsuhiko

**Comment by mitsuhiko** [comment]
lgtm. I will add some tests to ensure this does not regress.

**Comment by thyming** [comment]
Thanks for the help with the tests 😄 wasn't immediately obvious how to do that correctly. I'll fixup the commit style as I see you all use a specific format.

**Comment by mitsuhiko** [comment]
@thyming not necessary, we squash merge anyways and i will fix it up.

**Review by mitsuhiko — APPROVED** [review]

**Comment by mitsuhiko** [comment]
Thanks a bunch :)

**Pull request merged**
