### PR TITLE
chore(ts): Convert _some_ bootstrap files

### PR DESCRIPTION
**Pull request by evanpurkhiser**
This is a followup to https://github.com/getsentry/sentry/pull/17836. I didn't convert quite as many bootstrap type things. Let's make sure cloudbuild passes, which is a good indication if getsentry will be able to be deployed as well.

### CODE REVIEW

**Review by BYK — CHANGES_REQUESTED** [review]
Still failing but not due to a memory issue. Now that I think about it, exit code 2 is usually some error, not due to memory anyway. Here's the error I salvaged:

Okay found it:

```
ERROR in /usr/src/sentry/src/sentry/static/sentry/app/utils/statics-setup.tsx
ERROR in /usr/src/sentry/src/sentry/static/sentry/app/utils/statics-setup.tsx(14,3):
TS2304: Cannot find name '__webpack_public_path__'.
```

**Review by BYK — APPROVED** [review]

**Review by dashed — APPROVED** [review]
Looks good to me 👍

**Comment by EvanPurkhiser** [comment]
Oops, accidentally overwrite byks changes here 😬

**Comment by BYK** [comment]
>Oops, accidentally overwrite byks changes here 😬

As long as you keep the builds green, I am okay becoming redundant :)

**Comment by EvanPurkhiser** [comment]
Why won't these tests run 😿

**Comment by BYK** [comment]
[API IS DOWN](https://www.traviscistatus.com/incidents/wfwd9y5x4k0p)

**Pull request merged**
