### PR TITLE
feat(plugins): move Freight into sentry

### PR DESCRIPTION
**Pull request by scefali**
Must be merged with: https://github.com/getsentry/getsentry/pull/3354

### CODE REVIEW

**Comment by mattrobenolt** [comment]
Do we wanna vendor this one? I don't particularly care, but I don't think we should vendor straight up every single plugin.

We do still have a plugin system that works. I think what we vendor should be considered core support.

**Comment by scefali** [comment]
@mattrobenolt Just talked to @wedamija about this. We want to vendorize all of the plugins so we know when they break when people make changes to them. Also, if we are going to move the bulk of plugins I think we should just move all of them for consistency unless we are planning on getting rid of that plugin.

**Comment by dcramer** [comment]
fwiw we still need to support plugins APIs, so you'll still have to deal w/ all of that anyways

**Comment by wedamija** [comment]
> fwiw we still need to support plugins APIs, so you'll still have to deal w/ all of that anyways

Yeah, the main benefit is that everything is in one place and so it's easier to keep everything in sync.

**Review by wedamija — APPROVED** [review]
Since we're adding this into `sentry.plugins`, I assume this needs to be coordinated with either removing the entrypoint from the original repo, or removing the dependency from `requirements_plugins.txt` in getsentry (depending on which path we choose)?

**Comment by joshuarli** [comment]
> Since we're adding this into `sentry.plugins`, I assume this needs to be coordinated with either removing the entrypoint from the original repo, or removing the dependency from `requirements_plugins.txt` in getsentry (depending on which path we choose)?

Why not both?

**Comment by wedamija** [comment]
> > Since we're adding this into `sentry.plugins`, I assume this needs to be coordinated with either removing the entrypoint from the original repo, or removing the dependency from `requirements_plugins.txt` in getsentry (depending on which path we choose)?
> 
> Why not both? Going forward we wouldn't be maintaining the individual repos.

@dcramer brought up a good point that people install off of master for these repos, so we're potentially breaking old sentry installs that use these plugins.

**Pull request merged**
