### PR TITLE
chore(deps): bump openapi-examples-validator

### PR DESCRIPTION
**Pull request by mdtro**
Bumps openapi-examples-validator to resolve dependabot alert.

### CODE REVIEW

**Review by JoshFerge — COMMENTED** [review]
doesn't a package.json file have to be updated too?

**Comment by mdtro** [comment]
> doesn't a package.json file have to be updated too?

Woops! Thank you!

**Comment by mdtro** [comment]
Appears we might be running in to this issue: https://github.com/codekie/openapi-examples-validator/issues/178 where our schema was incorrectly passing the checks. That the bug is fixed in `openapi-examples-validator` version 4.7.0.

**Comment by JoshFerge** [comment]
@mdtro is there a flag that we can add on to make the validator pass for now? don't have time to go through and fix all these at the moment, but could add the flag then create a github issue for it.

**Comment by mdtro** [comment]
> @mdtro is there a flag that we can add on to make the validator pass for now? don't have time to go through and fix all these at the moment, but could add the flag then create a github issue for it.

@JoshFerge I believe it would just be done by removing the `--no-additional-properties` flag in the test action, but that has other implications.

**Pull request closed without merging**
