### PR TITLE
ref(ui) Shuffle components around to make adding new graphs easier.

### PR DESCRIPTION
**Pull request by markstory**
Move a few components around in performance views and remove cross view imports. This should help make adding more charts to performance views a tiny bit easier.

### CODE REVIEW

**Review by billyvg — APPROVED** [review]
LGTM - not in love with the filepath of `app/utils/discover/styles` but this is a step in the right direction to move all of these related styles to one location.

**Comment by markstory** [comment]
> not in love with the filepath of app/utils/discover/styles

Agreed. I don't love this path either. Would something in `app/styles` work?

**Comment by billyvg** [comment]
> > not in love with the filepath of app/utils/discover/styles
> 
> Agreed. I don't love this path either. Would something in `app/styles` work?

Yeah I think `app/styles` makes more sense. Does `discover` still apply? it seems like we need a higher level name to capture these different views, but maybe `discover` is that name

**Comment by markstory** [comment]
> Does discover still apply? it seems like we need a higher level name to capture these different views, but maybe discover is that name.

The components I moved are less related to discover and more to the 66/33% layout that we use there. I don't have a clever name for that layout yet, but can move these components to that module when we do have a name for it.

**Pull request merged**
