### PR TITLE
feat(api): switch to prefixed strings for auth tokens and client secrets

### PR DESCRIPTION
**Pull request by greysteil**
Currently, Sentry uses `uuid4().hex + uuid4().hex` to generate its auth tokens and application client secrets. This PR switches to prefixed strings generated with [`secrets.token_urlsafe`](https://docs.python.org/3/library/secrets.html#generating-tokens). Both strings remain 64 characters long.

There are a couple of benefits to this approach:
* More entropy, since the new strings encode ~40 bytes of randomness (the old ones had ~30)
* Easier to detect with regex scanning (and would be a perfect candidate for [GitHub secret scanning](https://docs.github.com/en/developers/overview/secret-scanning), which is part of my day job)
    * Note that the existing strings can already be detected with regex scanning, since they use UUID4. I don't think there's a security through obscurity argument here - the following pattern will pick the existing tokens up relatively accurately, but with some false positives (e.g., Sentry client IDs):
        ```
        /[a-f0-9]{12}4[a-f0-9]{3}[89aAbB][a-f0-9]{27}4[a-f0-9]{3}[89aAbB][a-f0-9]{15}/
        ```

Note: I've replaced `-` and `_` characters in the output of `secrets.token_urlsafe`. This slightly reduces the entropy of the output strings, but is more aesthetically pleasing and removes the (minorly) irritating problem that `-` characters act as word boundaries. A more robust implementation would be to use `secrets.token_bytes` and write the logic to encode that as base62, rather than base64. If the small loss in entropy is important to you (note: still a gain on the current setup) let me know.

### CODE REVIEW

**Comment by markstory** [comment]
Adding ecosystem team as they are the caretakers of the integration platform.

**Comment by greysteil** [comment]
Thanks @markstory @BYK.

I've also got data on how big an immediate effect updating a token pattern has on the ability to detect leaked tokens (a big part of my motivation for this PR). After we updated our [token pattern at GitHub](https://github.blog/2021-04-05-behind-githubs-new-authentication-token-formats/) we saw an immediate change in the format of the leaked tokens we were detecting. It turns out, tokens are most likely to be leaked immediately after they've been created. Which makes sense when you think about it - that's the moment they're being "handled" the most.

114217138-c86f8400-9935-11eb-9c20-5932a5a95b3c

I'm pretty confident in the changes in this PR, but I should note that I don't write much Python!

**Comment by greysteil** [comment]
Anything more I can do on this? I noticed linting was still failing - sorry about that, I don't write a lot of Python 😬. It's fixed now (by filtering the files sent to `isort` even in PRs - the alternative was to sort the imports in the `0001_initial` migration, but I figured that would add noise to this PR).

**Comment by manuzope** [comment]
Thanks for the PR, @greysteil! The intent of it makes sense to me. We do plan on reviewing this but its lower priority amongst other things right now. We don't have a timeline on when we'll be able to review this, but we will ping you when we do get to it.

**Comment by greysteil** [comment]
Hey @manuzope, any update on when you and the team will be able to review this?

**Comment by manuzope** [comment]
Hi @greysteil, none yet but this is in our backlog. We don't have a timeline on when we'll be able to get to this unfortunately.

**Comment by greysteil** [comment]
I'm going to close this, as it's been six months and it doesn't look like your team is going to be able to review contributions like this. I know what that's like and don't want it to be sitting around going stale and/or making y'all feel bad! :octocat:

**Pull request closed without merging**
