### PR TITLE
fix(ui): Render context data as context data

### PR DESCRIPTION
**Pull request by jan-auer**
https://gist.github.com/drunkcod/7ceacb97930a118452aea44f4b7e5e22

### CODE REVIEW

**Comment by jan-auer** [comment]
The user context had it already for some reason, but it's also not using `<ContextBlock />`.

**Review by mitsuhiko — APPROVED** [review]

**Comment by jan-auer** [comment]
Percy, where are you?

**Comment by jan-auer** [comment]
Hold, `<KeyValueList>` doesn't render the `<DeviceName>` component.

**Comment by billyvg** [comment]
Hmm why do we have two different font colors (black vs blue)?

**Comment by jan-auer** [comment]
@billyvg I suppose because strings are rendered blue in the context mode but everything is black in the non-context mode. 

Just realizing that this is causing an ugly mix in the device context, not sure what’s the best fix atm.

**Review by billyvg — APPROVED** [review]
I think the inconsistent colors are not great, but being able to render context data would make this a net win, imo. Thoughts on merging and then followup to see if we can be more consistent in the other contexts?

**Comment by jan-auer** [comment]
👍 Once we touch contexts again we should revisit this.

**Pull request merged**
