### PR TITLE
feat(replays): Add virtualization to DOM Events

### PR DESCRIPTION
**Pull request by jesus4497**
Related to #37549.

### Changes
- Added virtualization to DOM events with `react-virtualize`.

### Note: 
Seems like the problem about the lagginess is not related to the number of rows but rather the playback of the replay as @billyvg mentioned before. Even after having a virtualized list the tab keeps lagging and this might be due to the works its doing collecting all the DOM nodes by running the whole replay in the background.

https://user-images.githubusercontent.com/39612839/188505406-a4833f56-127e-4a61-ade8-4c426facdd6d.mp4

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Review by NisanthanNanthakumar — COMMENTED** [review]
@jesus4497 I think you can use React Profiler to see if this change has a material impact in improving the lagginess

**Review by billyvg — COMMENTED** [review]
It looks pretty good -- the only problem I see is that when you scroll the horizonal scrollbars always show up and then later disappear.

**Comment by jesus4497** [comment]
> It looks pretty good -- the only problem I see is that when you scroll the horizonal scrollbars always show up and then later disappear.

Hey @billyvg! which horizontal scrollbars? 🤔

**Comment by jesus4497** [comment]
> It looks pretty good -- the only problem I see is that when you scroll the horizonal scrollbars always show up and then later disappear.

Hey @billyvg! lets do follow up PR about this issue later - It's taking more time that it should to debug

**Review by billyvg — APPROVED** [review]

**Pull request merged**
