### PR TITLE
Add uniqueness constraints to FlatFileIndex(State)

### PR DESCRIPTION
**Pull request by Swatinem**
Both tables were truncated using https://github.com/getsentry/sentry/pull/54440, which has since been executed in https://getsentry.atlassian.net/browse/OPS-3745, and both tables are empty.

### CODE REVIEW

**Review by beezz — APPROVED** [review]

**Review by wedamija — CHANGES_REQUESTED** [review]
These will fail because there are duplicate rows on these columns in the table

```
select count(*), flat_file_index_id, artifact_bundle_id
from sentry_flatfileindexstate
group by flat_file_index_id, artifact_bundle_id
having count(*) > 1
```

```
select count(*), project_id, release_name, dist_name
from  sentry_artifactbundleflatfileindex
group by project_id, release_name, dist_name
having count(*) > 1
```

**Comment by Swatinem** [comment]
> These will fail because there are duplicate rows on these columns in the table

That’s why https://github.com/getsentry/sentry/pull/54440 was truncating both tables. By now that migration was executed in https://getsentry.atlassian.net/browse/OPS-3745, and both tables are empty.

**Comment by wedamija** [comment]
> > These will fail because there are duplicate rows on these columns in the table
> 
> That’s why #54440 was truncating both tables. By now that migration was executed in https://getsentry.atlassian.net/browse/OPS-3745, and both tables are empty.

Ok, generally a good thing to mention in your pr description

**Review by wedamija — APPROVED** [review]

**Comment by Swatinem** [comment]
> generally a good thing to mention in your pr description

yes, my bad. I split this PR out from https://github.com/getsentry/sentry/pull/54440 which originally had both the data migration and changes to the index in one.

**Pull request merged**
