### PR TITLE
feat(profiles): Deobfuscate Android with Symbolicator

### PR DESCRIPTION
**Pull request by phacops**
Deobfuscation on workers is proving to be a challenge since it needs a lot of resources. It's better to pool those resources and cache proguard files in Symbolicator and let it do the work.

Recently, the processing team added that capability and this will allow us to test it on profiles.

### CODE REVIEW

**Review by Swatinem — APPROVED** [review]
this looks simple enough. does it have proper tests though? since this is opt-in via the project-id Set, it might be a good idea to enable that in some of the tests.

**Review by loewenheim — APPROVED** [review]

**Comment by loewenheim** [comment]
I agree with @Swatinem about trying this in a test.

**Review by viglia — COMMENTED** [review]
@Swatinem @phacops , does Symbolicator know when to use the params mapping when lines are not available (in our case always)?

In the current implementation it's explicit:
`mapper = open_proguard_mapper(debug_file_path, initialize_param_mapping=True)`

Does symbolicator do that automatically if it sees there are no lines or does it simply end up not doing proper deobfuscation as it was before the `initialize_param_mapping` implementation?

**Comment by phacops** [comment]
Merged by accident.

**Comment by Swatinem** [comment]
I don’t think we have properly implemented the parameter mapping at all right now.

**Comment by viglia** [comment]
ok, then I think this should be delayed until then.

This would introduce a regression for customers that are sending in profiles with obfuscated frames.

It would also hinder proper working of `issue-detection`.

**Pull request merged**
