### PR TITLE
feat(ui): Display PII meta data in issue details

### PR DESCRIPTION
**Pull request by billyvg**
Show overlays for annotated sections in PII stripped or modified event data on the issue details screen. This PR is based on https://github.com/getsentry/sentry/pull/9928

## Example 

screenshot 2018-09-28 at 00 52 34

## Overview

This PR introduces a set of new components which must be used consistently throughout the event rendering tree:

 - `MetaProxy`: Proxy for an event object with meta data. As you traverse through the object, the proxy keeps state of the keys used so that it can access the associated meta data if present.
 - `withMeta`: Decorates an object with a proxy
 - `Annotated`: A getter for an object + property name that will wrap the data with an annotation if possible
 - `MetaData`: Class to fetch metadata from an object + key
 - `AnnotatedText`: A component that receives a value and meta data and renders all remarks and errors. If the meta data contains redacted chunks, they are rendered with a tooltip. This component can safely be rendered in a pre while preserving the original text format.

### CODE REVIEW

**Comment by billyvg** [comment]
@jan-auer Is there a way we can add some test data to `load-mocks` so we can test this in dev?

**Comment by jan-auer** [comment]
@billyvg I'll have to check that this has no unwanted side effects, but I think we should be good with adding one more PII stripping example JSON. I'll get one ready by tomorrow and add it to this PR

**Comment by jan-auer** [comment]
@billyvg my bad, we weren't saving meta data properly. a rebase before merging https://github.com/getsentry/sentry/pull/9912 added code that drops all meta data.

**Review by lynnagara — APPROVED** [review]
Looks good to me, thanks for adding the mocks 👍

**Review by jan-auer — APPROVED** [review]

**Pull request merged**
