### PR TITLE
tests(py): Reduce junk output in tests due to signal errors

### PR DESCRIPTION
**Pull request by evanpurkhiser**
This should reduce noise by not erroring, and instead just logging failure to get org owners

### CODE REVIEW

**Review by mattrobenolt — COMMENTED** [review]
This is definitely changing behavior for things that expect there to be an owner. And I haven't checked everywhere if returning None is acceptable in all the paths.

**Comment by EvanPurkhiser** [comment]
This is just used for these analytics recievers, which are all already returning None.

**Comment by markstory** [comment]
Could we add the owner to the tests that don't have one? Sounds like the tests are working on invalid states that could be masking other problems.

**Comment by EvanPurkhiser** [comment]
Okay will deal with this later, too much time investment trying to get this to work now.

**Pull request closed without merging**
