### PR TITLE
fix(ui): Update Rubik font file's vertical metrics

### PR DESCRIPTION
**Pull request by vuluongj20**
Standardize font display across browsers and operating systems. MacOS uses a different set of font metrics from Windows. In addition, while Chrome and Safari in MacOS use the MacOS metrics (`hhea`), Firefox in MacOS confoundingly uses the Windows metrics (`win`).

---

**In Chrome & Safari in MacOS**

Before & after:
 - Text - icon alignment
    Screen Shot 2022-01-05 at 3 37 20 PM
    Screen Shot 2022-01-05 at 3 36 55 PM

 - Text - text alignment (zoom in, and notice how in the first screenshot the baseline of the gray text is higher than that of the blue text)
    Screen Shot 2022-01-05 at 3 39 07 PM
    Screen Shot 2022-01-05 at 3 39 15 PM

---

**In Windows, and in Firefox in MacOS**

Before & after:
 - Text - box alignment: not much has changed, there's slightly more space below the text
    Screen Shot 2022-01-05 at 3 50 44 PM
    Screen Shot 2022-01-05 at 3 50 35 PM
 - Text display: descenders are no longer cut off
    Screen Shot 2022-01-05 at 3 52 55 PM
    Screen Shot 2022-01-05 at 3 53 35 PM
 - Buttons: there is now more even spacing, in the first screenshot, there's more space on top
    Screen Shot 2022-01-05 at 3 57 23 PM
    Screen Shot 2022-01-05 at 3 57 53 PM

### CODE REVIEW

**Comment by evanpurkhiser** [comment]
This is seriously good work.

How can we make sure we don't regress this somehow, is there any type of 'source file' for these fonts we can check in or anything like that?

Basically the fact that this is fixed is tribal knowledge, maybe even a README.md in this folder could be good?

**Comment by evanpurkhiser** [comment]
Also these files got WAY bigger. Can we fix that?

Presumably a bunch of metadata snuck in.

**Comment by vuluongj20** [comment]
@evanpurkhiser Good points! Minimized the files (without losing crucial features & settings), and added a README file.

**Review by evanpurkhiser — APPROVED** [review]
wow that file size reduction!

**Pull request merged**
