### PR TITLE
feat: add and fix bitfield tests on Django 1.9, 1.10, bring back Exact lookup support and refactor lookup style

### PR DESCRIPTION
**Pull request by joshuarli**
We've had bitfield tests, but ci never actually ran them. Moving them into sentry tests so I don't have to add another make target and travis job.

Turns out they were broken on master - this fixes them for at least Django 1.9. I also removed compat code for < 1.8.

Actually, tests also pass on Django 1.10 - it looks like cramer vendored bitfield code that supported 1.10 (we've got a custom Creator for to_python, and a custom Lookup to replace the deprecated get_prep_lookup, get_db_prep_lookup).

### CODE REVIEW

**Comment by joshuarli** [comment]
I don't quite understand what's going on here, but 261b5c0467e5e2a85f60f8d3ad5f667fc50caa92 appears to fix the non-bitfield tests that were failing.

Alternatively, going back to subclassing Lookup instead of Exact (upstream has Exact) fixes our tests, but breaks bitfield tests (a873884301a9847ef44a32158c909c0751bae9fc).

From https://github.com/getsentry/sentry/pull/7771:

    Remove support for doing .filter(flags=Bit()) -- This was easier than fixing compatibility, and is obscure anyways.

So this is what I think happened:

- Cramer removed support for exact BitField lookups in https://github.com/getsentry/sentry/pull/7771, which necessitated changing the lookup style to use Django F.
  - At this point, bitfield tests that depended on exact support fail. But this goes unnoticed because we don't run them in ci.
- I noticed bitfield tests weren't running, and brought back Exact lookups to pass the bitfield test suite.
- I then noticed this broke our tests, and bringing back the lookups to = instead of F fixed them.

**Comment by joshuarli** [comment]
Also, after switching away from F lookups, I was able to undo this: https://github.com/getsentry/sentry/pull/7771/commits/aa371df7b78b868539a02e3eb4c693a7a07470e1#r208044293

Specifically `params.append(self.get_db_prep_lookup(self.rhs, connection)[1])` -> `params.extend(self.process_rhs(qn, connection)[1])`. The latter is in upstream bitfield, and this makes our vendored bitfield pretty much the same as upstream.

Before, it would `ProgrammingError("can't adapt type 'CombinedExpression'",)`.

Literally have no idea what's going on.

**Comment by joshuarli** [comment]
After this, we're pretty close to upstream code, with one notable exception:

`params.extend(self.process_rhs(qn, connection)[1])` (upstream has `params.append(self.get_db_prep_lookup(self.rhs, connection)[1])`)

Changing to that results in some `ProgrammingError("can't adapt type 'CombinedExpression'",)` in a few tests like `ResetOrganizationMember2faTest.test_org_owner_can_reset_member_2fa`.

**Comment by joshuarli** [comment]
`sentry django makemigrations` gives `No changes detected`.

**Review by wedamija — APPROVED** [review]
After a lot of back and forth this looks good 👍

**Pull request merged**
