### PR TITLE
ref(event_saved): Send event_saved signal in outcomes_consumer

### PR DESCRIPTION
**Pull request by nathan-heskia**
Moves the `event_saved` signal to the outcomes consumer. This will enable passing of event category as well as quantity to the signal handlers for billing in getsentry.

### CODE REVIEW

**Comment by nathan-heskia** [comment]
@jan-auer build on my fork wasn't succeeding, i moved to branching in the main repository.

**Comment by nathan-heskia** [comment]
why are the tests for outcomes consumer xfailing?

**Comment by nathan-heskia** [comment]
if they are being skipped, it is reducing the code coverage

**Review by tonyo — APPROVED** [review]
Let's... keep an eye on outcomes consumer graphs (on Relay dashboard) when this is going out 😅

**Review by untitaker — APPROVED** [review]
Right, that seems fine. I am not quite sure why we have teh intermediate step of still sending the signal in save_event and marking the signal as sent. How does that help with migration?

**Comment by untitaker** [comment]
@nathan-heskia we xfail all things kafka when kafka is not "set up". We are actively fixing that to at least run in CI: https://github.com/getsentry/sentry/pull/17133

for local testing you can use `SENTRY_KAFKA_HOSTS=localhost:9092` as envvar to make them not xfail

**Review by jan-auer — APPROVED** [review]

**Comment by jan-auer** [comment]
Outcomes consumer tests have been updated on master and now run as part of CI

**Pull request merged**
