### PR TITLE
chore(css): Remove Box/Flex from sentryAppDetailsModal

### PR DESCRIPTION
**Pull request by evanpurkhiser**

### CODE REVIEW

**Comment by billyvg** [comment]
@MeredithAnya @scefali Do we have percy snapshots for these modals?

**Comment by scefali** [comment]
@billyvg No. This component is now only used for a rare use case when someone installs from the external install link (aka not installing through the integrations page). Probably not worth lengthening acceptance tests for that case.

**Review by scefali — APPROVED** [review]

**Review by scefali — CHANGES_REQUESTED** [review]
shouldn't have approved...looks weird now

**Comment by scefali** [comment]
Before:

Screen Shot 2020-03-25 at 10 51 17 AM

Now:

Screen Shot 2020-03-25 at 10 51 13 AM

The logo should be next to the name.

**Comment by EvanPurkhiser** [comment]
Ah damn, thanks for testing.

**Comment by EvanPurkhiser** [comment]
Alright, got that fixed 
image

**Review by scefali — APPROVED** [review]

**Pull request merged**
