### PR TITLE
ref(externalIssueForm): Remove jQuery usage

### PR DESCRIPTION
**Pull request by BYK**

### CODE REVIEW

**Review by evanpurkhiser — APPROVED** [review]
Looks fine to me

Any concern with `fetch` usage @billyvg ?

**Comment by billyvg** [comment]
@EvanPurkhiser @BYK One thing I can think of is `ajaxCsrfSetup` is configured to be called before sending requests with `jQuery.ajaxSetup`

**Comment by BYK** [comment]
Since this is a `GET` request, the CSRF setup does not apply. That said, I think it'd be wise to create a request helper method that does this automatically instead of using `fetch` directly in the future.

I'll start working on that -- leaving up to your judgement to merge this before or wait until that patch @EvanPurkhiser

**Comment by billyvg** [comment]
> Since this is a `GET` request, the CSRF setup does not apply. That said, I think it'd be wise to create a request helper method that does this automatically instead of using `fetch` directly in the future.
> 
> I'll start working on that -- leaving up to your judgement to merge this before or wait until that patch @EvanPurkhiser

@BYK I'd probably rather just stick with using `fetch` directly for now and refactor as needed down the line.

**Comment by markstory** [comment]
Are we still supporting IE11? That browser doesn't support fetch() and I don't see a polyfill for it in babel.

**Comment by BYK** [comment]
>Are we still supporting IE11? That browser doesn't support fetch() and I don't see a polyfill for it in babel.

Checked with @benvinegar - we support it for SDKs but we don't support in on sentry.io so we should be fine.

**Pull request merged**
