### PR TITLE
feat(utils): Add method to correctly join and format lists of strings

### PR DESCRIPTION
**Pull request by lobsterkatie**
This is to support the _admin audit log.

### CODE REVIEW

**Comment by lobsterkatie** [comment]
Does codecov not run doctests??

https://codecov.io/gh/getsentry/sentry/compare/c96abc7716d8f753f019e4d35a22414c6c348e0f...d5243e0ef10287ab6aaf11edd77967f1d3df45eb/diff

**Comment by maheskett** [comment]
No, I don't think doctests are run at all. Our travis config runs [make test-python](https://github.com/getsentry/sentry/blob/master/Makefile#L178) (i.e. `py.test tests/integration tests/sentry`).

**Comment by lobsterkatie** [comment]
Anyway, I added tests in the tests file also. That was more me venting than anything else. PR should be good to go if you feel comfortable hitting approve.

**Comment by maheskett** [comment]
Also, what do you think about adding the case of an empty list?

**Review by maheskett — APPROVED** [review]

**Pull request merged**
