### PR TITLE
feat(ui): Form padding tweaks when stacked and not inline

### PR DESCRIPTION
**Pull request by billyvg**
Needs more space between form fields and less between label and help

Old:
image

New:
image

### CODE REVIEW

**Comment by Chrissy** [comment]
screenshots?

**Comment by billyvg** [comment]
@Chrissy added

**Comment by Chrissy** [comment]
dis much better

I'm not sure if you meant to do this, but it looks like the changes from https://github.com/getsentry/sentry/pull/13206 are included in this pull?

**Comment by billyvg** [comment]
Oops, updated

**Review by markstory — APPROVED** [review]

**Review by Chrissy — APPROVED** [review]

**Pull request merged**
