### PR TITLE
add verify_tls option for sourcemap scaping Fixes #4500

### LINKED ISSUE #4500: Handle optional TLS validation for external source fetching
Originally brought up here: https://github.com/getsentry/sentry/pull/4016

We should surface a new setting to require TLS validation when fetching external files. This option would be enabled by default (security first) with an option to disable. We need to make sure we then are able to surface this exact error inside the UI correct so a user can make the decision to disable on their own. To clarify, we shouldn't just blindly say, "Failed to fetch file.", we should strictly say, "Unable to validate TLS certificate when fetching file." or something akin to that.

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by mattrobenolt** [comment]
Awesome, I'm going to make sure I look through this this week.

I vaguely also remember you wanting to make sure that we surfaced this error in the UI when TLS verification failed. I'm assuming you'd still want to do that? Unclear at first glance if we'd be doing that already. If it's raised as a subclass of `RequestException` I think we would surface it. Otherwise, we won't.

**Comment by mattrobenolt** [comment]
Oh, it looks like it does! So it seems like this would magically work.

**Comment by mattrobenolt** [comment]
Cool, so confirmed, this will manifest itself in the UI as:

```
Unable to fetch resource: ...
```

With a `value` of `hostname 'xxx' doesn't match either of 'xxx, or yyy'`

Awesome, I'll just make sure the rest of this is good, and should be good to merge.

**Comment by graingert** [comment]
@mattrobenolt can you add the Security label to this?

**Comment by graingert** [comment]
> Awesome, I'll just make sure the rest of this is good, and should be good to merge.

any update on this?

**Comment by dcramer** [comment]
In general I'm ok with this. @mattrobenolt did you have any final thoughts?

(i didnt look at why tests are failing)

**Comment by graingert** [comment]
@dcramer tests are failing because https://github.com/getsentry/sentry/pull/4843

**Review by mattrobenolt — APPROVED** [review]

**Comment by mattrobenolt** [comment]
@graingert I rebased and got this fixed up so it can be merged now.

For reference: https://github.com/getsentry/sentry/pull/4795/commits/475b13e4d0d7cb270e1b082cd3e510ef6a2ebd65

The biggest problem is that the form field was never being added to the page to be rendered. :) Otherwise, I just renamed stuff.

**Pull request merged**
