### PR TITLE
chore(issue-priority): Register new option for issue priority flag

### PR DESCRIPTION
**Pull request by snigdhas**
Related to https://github.com/getsentry/sentry/issues/63653

### CODE REVIEW

**Comment by malwilley** [comment]
Do we need to register an option if we use `AutoRegisterOptionBackedRolloutFeatureHandler` here? https://github.com/getsentry/getsentry/blob/56b4741390cb53b27ce67fc4781e86ff56397b05/getsentry/features.py#L1188

**Comment by snigdhas** [comment]
I think we have to register it if we want to use `sentry-options-automator` to update the enabled projects, which I prefer since those PRs are faster & more reliable than getsentry. 

Not sure how to use `sentry-options-automator` with `AutoRegisterOptionBackedRolloutFeatureHandler` but open to trying!

**Comment by wedamija** [comment]
It will register an option, you just need to figure out the name for use with options automator

**Comment by snigdhas** [comment]
Sweet, closing this!

**Comment by snigdhas** [comment]
Reopening 🙈 

`AutoRegisterOptionBackedRolloutFeatureHandler` relies on `OptionBackedRolloutFeatureHandler` which expects an OrganizationFeature. We _could_ override `_check_for_batch` but that seems more likely to introduce a bug

**Review by armenzg — APPROVED** [review]

**Pull request merged**
