### PR TITLE
Fix BadHeaderError

### LINKED ISSUE #4742: BadHeaderError: Header values can't contain newlines (got 'attachment; filename="vendor.js.map\r\n\n             ...
https://sentry.io/sentry/sentry/issues/202980928/

```
BadHeaderError: Header values can't contain newlines (got 'attachment; filename="vendor.js.map\r\n\n                "')
(1 additional frame(s) were not displayed)
...
  File "sentry/api/base.py", line 86, in handle_exception
    return super(Endpoint, self).handle_exception(exc)
  File "sentry/api/base.py", line 180, in dispatch
    response = handler(request, *args, **kwargs)
  File "sentry/api/endpoints/release_file_details.py", line 123, in get
    return self.download(releasefile)
  File "sentry/api/endpoints/release_file_details.py", line 83, in download
    response['Content-Disposition'] = 'attachment; filename="%s"' % posixpath.basename(releasefile.name)

BadHeaderError: Header values can't contain newlines (got 'attachment; filename="vendor.js.map\r\n\n                "')
```

### PR DESCRIPTION
**Pull request by HazAT**
Fixes #4742

### CODE REVIEW

**Comment by mattrobenolt** [comment]
So technically, there's nothing that wouldn't prevent a newline character in the middle. This is only covering the ends.

**Review by mitsuhiko — CHANGES_REQUESTED** [review]
I would splitlines() and use first item. Note that the list can be empty. Reason is that newlines can be in the middle too

**Comment by HazAT** [comment]
Found here: http://stackoverflow.com/a/37001613/1139707

**Comment by mitsuhiko** [comment]
I would join on space instead of empty string so that files named "foo bar.js" don't become "foobar.js"

**Review by mitsuhiko — APPROVED** [review]

**Pull request merged**
