### PR TITLE
feat(workflow): Backfill ProjectTeam model

### PR DESCRIPTION
**Pull request by macqueen**
part 2/3, depends on https://github.com/getsentry/sentry/pull/6136

cc @getsentry/workflow

### CODE REVIEW

**Comment by getsentry-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR includes migrations</td>
    </tr>
  </tbody>
</table>

## Migration Checklist

- [ ] new columns need to be nullable (unless table is new)
- [ ] migration with any new index needs to be done concurrently
- [ ] data migrations should not be done inside a transaction
- [ ] before merging, check to make sure there aren't conflicting migration ids


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Review by dcramer — APPROVED** [review]
reminder to deploy part 1 before deploying part 2

**Comment by mattrobenolt** [comment]
We doing this? This is in my review queue even though it's been approved. :)

**Comment by macqueen** [comment]
@mattrobenolt i was gonna wait until part 3 (where we actually use the new fields) is closer to being done. i can kick you off as a reviewer

**Pull request merged**
