### PR TITLE
feat(ci): *TEMP* downgrade GHA runners for acceptance tests to 18.04

### PR DESCRIPTION
**Pull request by billyvg**
See https://github.com/dotnet/core/issues/7286

### CODE REVIEW

**Review by evanpurkhiser — APPROVED** [review]

**Comment by evanpurkhiser** [comment]
🙏

**Review by armenzg — APPROVED** [review]
The ancient past is less broken than the recent past :)
Thank you, Billy!

**Review by joshuarli — APPROVED** [review]
lmao

**Review by guihatano — APPROVED** [review]

**Review by joshuarli — APPROVED** [review]
#neverupgrade

**Pull request merged**
