### PR TITLE
fix(ui): Fix header stacking

### PR DESCRIPTION
**Pull request by lynnagara**
Global selection header needs to be below the sidebar for the org / user
menu to stack correctly

### CODE REVIEW

**Comment by lynnagara** [comment]
Fixes screen shot 2019-01-14 at 1 32 03 pm

**Review by billyvg — APPROVED** [review]
While you're in there can you also fix this? 😬

image

**Comment by billyvg** [comment]
Thanks!

**Comment by markstory** [comment]
Thank you for fixing this.

**Pull request merged**
