### PR TITLE
feat(dashboard): More condensed version of project card

### PR DESCRIPTION
**Pull request by lynnagara**
- [x] Reduce text size and better spacing of deploy details
- [x] Drop "Latest Deploys" heading
- [x] Move platform icon inline
- [x] Standardize release version format 

Fixes APP-261

### CODE REVIEW

**Comment by benvinegar** [comment]
Padding looks like it needs some love (taken from Percy):



@ckj could you maybe just shadow @lyn and make adjustments?

**Comment by ckj** [comment]
@lynnagara the `max-width:  100%;` that's set to the Platformicon img's is making them a little too small. Can you disable that, set their size to 22px, and give them a border radius of 3px? 

I'm a 👍 once that's touched up a little.

**Comment by ckj** [comment]
@lynnagara btw, can we use the release hovercard for these?

**Comment by lynnagara** [comment]
Do we really want to load all releases every time we load dashboard? (required for release hovercard)

**Review by ckj — APPROVED** [review]
LGTM 🤘

**Pull request merged**
