### PR TITLE
workflow: improve resolution by commit metadata

### PR DESCRIPTION
**Pull request by dcramer**
#nochanges

### CODE REVIEW

**Comment by dcramer** [comment]
This was semi broken in that it only would update things if the release was the same. We now treat it identical to the other behavior, that it transitions any resolution status when it happens.

**Comment by getsentry-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">You need to update CHANGES due to the size of this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Review by mattrobenolt — APPROVED** [review]
fine

**Comment by dcramer** [comment]
this has a bunch of random changes now as i changed the default verified state on the user's primary email fixture

**Pull request merged**
