### PR TITLE
ref: fix types for sentry.utils.snowflake

### PR DESCRIPTION
**Pull request by asottile-sentry**
a bit of a hack -- I originally tried removing the mixin but there are checks for it in the outbox code -- is there a better way to detect if a model is a snowflake model there rather than `isinstance` of this mixin?

### CODE REVIEW

**Comment by markstory** [comment]
> is there a better way to detect if a model is a snowflake model there rather than isinstance of this mixin?

We could check for the method that the mixin provides. I agree with your comments that this logic could be done as a module level function.

**Review by markstory — APPROVED** [review]

**Comment by asottile-sentry** [comment]
> > is there a better way to detect if a model is a snowflake model there rather than isinstance of this mixin?
> 
> We could check for the method that the mixin provides. I agree with your comments that this logic could be done as a module level function.

ah well my goal was to kill the mixin entirely since that's the part that can't be typed properly :S

**Comment by markstory** [comment]
> ah well my goal was to kill the mixin entirely since that's the part that can't be typed properly

Making the mixin into a module function is something I can take care of.

**Comment by asottile-sentry** [comment]
> > ah well my goal was to kill the mixin entirely since that's the part that can't be typed properly
> 
> Making the mixin into a module function is something I can take care of.

sweet -- will merge this and let you take care of that -- thanks!

**Pull request merged**
