### PR TITLE
feat(owners): Add suggested commit box to issue details

### PR DESCRIPTION
**Pull request by dcramer**
This also improves some heuristics around suggesting owners, leveraging filename over abs path when possible.

This is behind the 'organizations:suggested-commits' feature.

### CODE REVIEW

**Comment by dcramer** [comment]
screen shot 2018-02-26 at 5 38 53 pm

**Comment by dcramer** [comment]
we will overhaul design/etc later

**Comment by dcramer** [comment]
@getsentry/design for design specs, likely what this would do is:

1. show a list (one row per commit) of the most relevant likely commits
2. if one commit is > 70% confidence (we have no score atm), only show that one
3. if theres not a single match, show anything above 20%?
3. show an 'expand' button if there is anything hidden

Each row should include: subject (click to expand message), author, revision sha, and timesince

**Comment by dcramer** [comment]
(also i dont think this should take up as much vertical space as a normal box, so whatever we can do to shrink it similar to the muted/resolved box)

**Comment by getsentry-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by ckj** [comment]
@dcramer Shipping behind a switch for now works for me. @getsentry/design won't be able to give this much attention until after this sprint.

**Comment by dcramer** [comment]
As a followup I likely want to change the 'find relevant releases' query to work like:

- Find up to N releases in the last week. If its less than Y, search deeper up to one month ago.
- If the Y interval method doesn't return enough data, simply find the last N releases
- If neither of the above end up working well, let's drop release as a primary search mechanism and simply search for relevant commits ordered by -date_released with an N limit

**Review by macqueen — APPROVED** [review]

**Pull request merged**
