### PR TITLE
fix(files): Make file uploads actually concurrent

### PR DESCRIPTION
**Pull request by mitsuhiko**
Do not merge yet. I need to test that the concurrency actually works correctly.

### CODE REVIEW

**Review by dcramer — APPROVED** [review]
Do you actually have to use lambda? Otherwise the docs look like it works by passing the func and arts sequentially in arg list.

**Comment by mitsuhiko** [comment]
@dcramer the only reason I added the lambda is because the ted executor from sentry.utils.concurrent has a similar API but requires a lambda there:

https://github.com/getsentry/sentry/blob/824c03089907ad22a9282303a5eaca33989ce481/src/sentry/utils/concurrent.py#L200

**Comment by JTCunning** [comment]
Let's move forward with this.

**Comment by mitsuhiko** [comment]
I will fix this today or tomorrow.

**Comment by BYK** [comment]
Closing due to staleness and obsolescence.

**Pull request closed without merging**
