### PR TITLE
chore(hybrid-cloud): Removing user foreign keys from group / release models.

### PR DESCRIPTION
**Pull request by corps**
Next step in breaking production foreign keys

The file changes are large mostly due to the large number of tests that need to swap from using the relation to the column id.  Functionally it is largerly identical.

Some small changes were made around serialization now that the foreign key is broken.  Additional HC test annotations were added.

Notably, one of the foreign key columns was built without an index.  The index will be required for efficient querying to handle eventual consistency.  I broke the migration up into two parts: first part is a safe migration that does not add the migration, and the second is an unsafe migration that adds the necessary index.  will ask ops to run the unsafe migration by hand after deploy.

### CODE REVIEW

**Review by wedamija — CHANGES_REQUESTED** [review]
This is much too large around a high risk area of our product. Please split this into individual prs per model

**Comment by corps** [comment]
> This is much too large around a high risk area of our product. Please split this into individual prs per model

Hi @wedamija ,

I don't believe this represents a large risk for the product.  I've updated my comment to explain.  The vast majority of the changes are simply adjustments from a relation to an explicit column name (user => user_id).  So I believe the impact is not large.

It will be hard to break this work down much more.  Anytime one of these fks is broken, there will be a large range of especially tests in particular that need to have many individual lines changing their queries.

Would you be willing to help me either review this change or find a strategy that works?

**Comment by wedamija** [comment]
> > This is much too large around a high risk area of our product. Please split this into individual prs per model
> 
> Hi @wedamija ,
> 
> I don't believe this represents a large risk for the product. I've updated my comment to explain. The vast majority of the changes are simply adjustments from a relation to an explicit column name (user => user_id). So I believe the impact is not large.
> 
> It will be hard to break this work down much more. Anytime one of these fks is broken, there will be a large range of especially tests in particular that need to have many individual lines changing their queries.
> 
> Would you be willing to help me either review this change or find a strategy that works?

I guess I don't really understand the difficulty here. You went through each model individually I assume, and fixed all the queries for each model. Why not break those into separate prs, rather than one large pr?

I'm also concerned about modifying a lot of high volume tables in a single migration. Our migrations are relatively safe these days in terms of using a lock timeout, but I would prefer to isolate the changes.

**Comment by corps** [comment]
> > > This is much too large around a high risk area of our product. Please split this into individual prs per model
> > 
> > 
> > Hi @wedamija ,
> > I don't believe this represents a large risk for the product. I've updated my comment to explain. The vast majority of the changes are simply adjustments from a relation to an explicit column name (user => user_id). So I believe the impact is not large.
> > It will be hard to break this work down much more. Anytime one of these fks is broken, there will be a large range of especially tests in particular that need to have many individual lines changing their queries.
> > Would you be willing to help me either review this change or find a strategy that works?
> 
> I guess I don't really understand the difficulty here. You went through each model individually I assume, and fixed all the queries for each model. Why not break those into separate prs, rather than one large pr?
> 
> I'm also concerned about modifying a lot of high volume tables in a single migration. Our migrations are relatively safe these days in terms of using a lock timeout, but I would prefer to isolate the changes.

Sure.  I guess what I'm looking for is a better assessment of what "risk" is so I can make some decisions.  Breaking each foreign key, one at a time, seems untennable for hybrid cloud.   Here's a full list of all relations that must be broken: https://github.com/getsentry/sentry/blob/master/tests/sentry/db/test_silo_models.py#L88   

Breaking each, one at a time, will definitely incur significant overhead and review, when in reality we have a well understood general plan and readiness for dealing with potential failures.

For instance, I can confidentially defend that the migration sqls in question will have no database impact.  If you'd like to talk more about that specifically or come up with a plan for validating that, I'm all ears.  The one potential database impacting migration is adding the new index, which is marked unsafe, and is completely safe to run in the future (not dependent on deployment) as it only adds additional performance to the deletion job.

If there is something specific you are concerned about, I'm definitely down to chat and come up with a plan.  I'd hope we can reach a solution where we are able to roll forward several of these related changes confidentally rather than doing batches for every single model.  If there is a specific, model, or set of models, you'd rather be given special attention, that is reasonable.  I just want to have a discussion and a plan that works for sentry!

I have documented elsewhere our strategy [here](https://www.notion.so/sentry/Deletions-in-Hybrid-Cloud-eb0c167804a0415ca0a418ab2700cdff) and @markstory has provided additional summarization [here](https://www.notion.so/sentry/Cross-region-data-removal-tombstones-e9751b1c19fc4b368cc28e92d4e191f7).  I've done some legwork before these PRs to study the relations and what it will take to break them (including some of the application surface logic that has to change, for instance new service calls where application logic may require it).

**Comment by corps** [comment]
For instance, even if i do break this PR into 6 separate PRs, I beg the question: does that mean 6 separate deploys?

If the answer is not: what's the difference in risk between batching them together as an atomic operation?  They represent a related group of work to be reviewed and deployed and migrated.

If the answer is yes: I'm concerned about the continuous overhead of individually deploying 50 migrations that are, effectually, similar and well understood.

I'm looking for a path that helps hybrid cloud deliver safely, and also deliver efficiently.

**Comment by wedamija** [comment]
> > > > This is much too large around a high risk area of our product. Please split this into individual prs per model
> > > 
> > > 
> > > Hi @wedamija ,
> > > I don't believe this represents a large risk for the product. I've updated my comment to explain. The vast majority of the changes are simply adjustments from a relation to an explicit column name (user => user_id). So I believe the impact is not large.
> > > It will be hard to break this work down much more. Anytime one of these fks is broken, there will be a large range of especially tests in particular that need to have many individual lines changing their queries.
> > > Would you be willing to help me either review this change or find a strategy that works?
> > 
> > 
> > I guess I don't really understand the difficulty here. You went through each model individually I assume, and fixed all the queries for each model. Why not break those into separate prs, rather than one large pr?
> > I'm also concerned about modifying a lot of high volume tables in a single migration. Our migrations are relatively safe these days in terms of using a lock timeout, but I would prefer to isolate the changes.
> 
> Sure. I guess what I'm looking for is a better assessment of what "risk" is so I can make some decisions. Breaking each foreign key, one at a time, seems untennable for hybrid cloud. Here's a full list of all relations that must be broken: https://github.com/getsentry/sentry/blob/master/tests/sentry/db/test_silo_models.py#L88
> 
> Breaking each, one at a time, will definitely incur significant overhead and review, when in reality we have a well understood general plan and readiness for dealing with potential failures.
> 
> For instance, I can confidentially defend that the migration sqls in question will have no database impact. If you'd like to talk more about that specifically or come up with a plan for validating that, I'm all ears. The one potential database impacting migration is adding the new index, which is marked unsafe, and is completely safe to run in the future (not dependent on deployment) as it only adds additional performance to the deletion job.
> 
> If there is something specific you are concerned about, I'm definitely down to chat and come up with a plan. I'd hope we can reach a solution where we are able to roll forward several of these related changes confidentally rather than doing batches for every single model. If there is a specific, model, or set of models, you'd rather be given special attention, that is reasonable. I just want to have a discussion and a plan that works for sentry!
> 
> I have documented elsewhere our strategy [here](https://www.notion.so/sentry/Deletions-in-Hybrid-Cloud-eb0c167804a0415ca0a418ab2700cdff) and @markstory has provided additional summarization [here](https://www.notion.so/sentry/Cross-region-data-removal-tombstones-e9751b1c19fc4b368cc28e92d4e191f7). I've done some legwork before these PRs to study the relations and what it will take to break them (including some of the application surface logic that has to change, for instance new service calls where application logic may require it).



> For instance, even if i do break this PR into 6 separate PRs, I beg the question: does that mean 6 separate deploys?
> 
> If the answer is not: what's the difference in risk between batching them together as an atomic operation? They represent a related group of work to be reviewed and deployed and migrated.
> 
> If the answer is yes: I'm concerned about the continuous overhead of individually deploying 50 migrations that are, effectually, similar and well understood.
> 
> I'm looking for a path that helps hybrid cloud deliver safely, and also deliver efficiently.

Just answering these all together.

I don't think you need to have a separate migration for every model in the system. My concern here is that everything around `Group` is considered high risk. Many of the models you're touching here are touched as part of the ingestion pipeline, and almost all of them are part of our core product in general (ie errors).

The risk I see it has a few pieces:
1. This pr is much too large for me to review effectively. I'm one of the primary owners of this area of the codebase, and I prefer to be able to give a thorough review to changes like this. It's difficult to do so in a pr with so many changes to consider.
2. Even though the migrations are simple, there is some risk to them. Altering a table at all requires us to take out an exclusive lock on it. We've had situations in the past where we had a migration attempt to take out a lock, we were unable to acquire the lock for a long time (10+ seconds-minutes), and this caused other reads/writes to the table to queue up behind the lock and fail. This is mostly mitigated these days, since we now use a lock timeout for all of our DDL migrations, but making a lot of changes to these tables in one batch still makes me nervous.

Tbh, I think we could resolve this by:
 - Breaking the query changes up into 2-3 separate prs of 200-300 length each. The query changes don't require any changes to the models, and this will let me effectively review those changes in a constrained way.
 - Break the model changes/migrations into a small number of prs, so that risky tables are done separately. Tables I consider risky here in terms of migrations are `Release` and `GroupOwner`. So we could have a migration each for these, and one larger migration for the other tables. Then we'd deploy each of these migrations separately.

**Comment by wedamija** [comment]
Separately, I think there's something about `0356_add_groupseen_index.py` that is breaking our generate SQL job. Not sure if the job is just generally broken for some unrelated reason, or if it's something about the migrations. Could you take a look into that as well?

**Comment by corps** [comment]
> > > > > This is much too large around a high risk area of our product. Please split this into individual prs per model
> > > > 
> > > > 
> > > > Hi @wedamija ,
> > > > I don't believe this represents a large risk for the product. I've updated my comment to explain. The vast majority of the changes are simply adjustments from a relation to an explicit column name (user => user_id). So I believe the impact is not large.
> > > > It will be hard to break this work down much more. Anytime one of these fks is broken, there will be a large range of especially tests in particular that need to have many individual lines changing their queries.
> > > > Would you be willing to help me either review this change or find a strategy that works?
> > > 
> > > 
> > > I guess I don't really understand the difficulty here. You went through each model individually I assume, and fixed all the queries for each model. Why not break those into separate prs, rather than one large pr?
> > > I'm also concerned about modifying a lot of high volume tables in a single migration. Our migrations are relatively safe these days in terms of using a lock timeout, but I would prefer to isolate the changes.
> > 
> > 
> > Sure. I guess what I'm looking for is a better assessment of what "risk" is so I can make some decisions. Breaking each foreign key, one at a time, seems untennable for hybrid cloud. Here's a full list of all relations that must be broken: https://github.com/getsentry/sentry/blob/master/tests/sentry/db/test_silo_models.py#L88
> > Breaking each, one at a time, will definitely incur significant overhead and review, when in reality we have a well understood general plan and readiness for dealing with potential failures.
> > For instance, I can confidentially defend that the migration sqls in question will have no database impact. If you'd like to talk more about that specifically or come up with a plan for validating that, I'm all ears. The one potential database impacting migration is adding the new index, which is marked unsafe, and is completely safe to run in the future (not dependent on deployment) as it only adds additional performance to the deletion job.
> > If there is something specific you are concerned about, I'm definitely down to chat and come up with a plan. I'd hope we can reach a solution where we are able to roll forward several of these related changes confidentally rather than doing batches for every single model. If there is a specific, model, or set of models, you'd rather be given special attention, that is reasonable. I just want to have a discussion and a plan that works for sentry!
> > I have documented elsewhere our strategy [here](https://www.notion.so/sentry/Deletions-in-Hybrid-Cloud-eb0c167804a0415ca0a418ab2700cdff) and @markstory has provided additional summarization [here](https://www.notion.so/sentry/Cross-region-data-removal-tombstones-e9751b1c19fc4b368cc28e92d4e191f7). I've done some legwork before these PRs to study the relations and what it will take to break them (including some of the application surface logic that has to change, for instance new service calls where application logic may require it).
> 
> > For instance, even if i do break this PR into 6 separate PRs, I beg the question: does that mean 6 separate deploys?
> > If the answer is not: what's the difference in risk between batching them together as an atomic operation? They represent a related group of work to be reviewed and deployed and migrated.
> > If the answer is yes: I'm concerned about the continuous overhead of individually deploying 50 migrations that are, effectually, similar and well understood.
> > I'm looking for a path that helps hybrid cloud deliver safely, and also deliver efficiently.
> 
> Just answering these all together.
> 
> I don't think you need to have a separate migration for every model in the system. My concern here is that everything around `Group` is considered high risk. Many of the models you're touching here are touched as part of the ingestion pipeline, and almost all of them are part of our core product in general (ie errors).
> 
> The risk I see it has a few pieces:
> 
>     1. This pr is much too large for me to review effectively. I'm one of the primary owners of this area of the codebase, and I prefer to be able to give a thorough review to changes like this. It's difficult to do so in a pr with so many changes to consider.
> 
>     2. Even though the migrations are simple, there is some risk to them. Altering a table at all requires us to take out an exclusive lock on it. We've had situations in the past where we had a migration attempt to take out a lock, we were unable to acquire the lock for a long time (10+ seconds-minutes), and this caused other reads/writes to the table to queue up behind the lock and fail. This is mostly mitigated these days, since we now use a lock timeout for all of our DDL migrations, but making a lot of changes to these tables in one batch still makes me nervous.
> 
> 
> Tbh, I think we could resolve this by:
> 
>     * Breaking the query changes up into 2-3 separate prs of 200-300 length each. The query changes don't require any changes to the models, and this will let me effectively review those changes in a constrained way.
> 
>     * Break the model changes/migrations into a small number of prs, so that risky tables are done separately. Tables I consider risky here in terms of migrations are `Release` and `GroupOwner`. So we could have a migration each for these, and one larger migration for the other tables. Then we'd deploy each of these migrations separately.

That's fair, thank you for the detailed explanation.

  One, trick, unfortunately.  Although I can move the query changes over into a separate PR, I can't "remove" the relation without also forcing django to produce a migration.  So in other words, I can give you a PR that makes query changes independent on of the migration by extracting that here, but I may still end up needing to make further query changes on the final migration PR because there won't be any enforcement in tests that relations aren't used (say by other concurrent changes).  As long as that's reasonable, I can take this approach.

I also did notice that for some reason, the generate SQL in CI isn't working, which is interesting since it works locally and I am able to both run it and produce SQL.  I'll get that fixed so you can check the SQL.

Essentially, these DDL changes become `SET CONSTRAINTS "sentry_savedsearch_owner_id_b9547283_fk_auth_user_id" IMMEDIATE; ALTER TABLE "sentry_savedsearch" DROP CONSTRAINT "sentry_savedsearch_owner_id_b9547283_fk_auth_user_id";`.  Because this does involve dropping triggers (postgresql foreign keys are actually triggers in terms of implementation) it does require table level locks, but the operation itself is near instant (constant time anyways).

**Pull request closed without merging**
