### PR TITLE
ref(assets): replaced platform imgs with platformicons package

### PR DESCRIPTION
**Pull request by doralchan**
- Removing unused imgs

### CODE REVIEW

**Review by evanpurkhiser — APPROVED** [review]
YES

**Comment by billyvg** [comment]
Are we sure these aren't referenced outside of the Sentry app?

**Comment by doralchan** [comment]
@billyvg getsentry wasn't referencing anything in here, and neither was docs. Docs is using the platformicon package similar to sentry. I couldn't find anything in the static-sites repo. Is there a way to easily double-check repos without cloning them locally?

**Comment by billyvg** [comment]
@doralchan I think the closest is GitHub's code search -- although if there are any abstractions around loading these images, it probably won't appear. https://github.com/search?p=2&q=org%3Agetsentry+platforms&type=Code

It's *probably* unused, and if static-sites isn't using it 🚢

**Review by dashed — APPROVED** [review]

**Pull request merged**
