### PR TITLE
feat(replays): Add telemetry to recording consumer

### PR DESCRIPTION
**Pull request by cmanallen**
closes https://github.com/getsentry/replay-backend/issues/129

### CODE REVIEW

**Comment by cmanallen** [comment]
@JoshFerge I think these are good places to track.  I wasn't too sure about sampling so I left it off for now.  Also wasn't too sure about `op` naming for the spans.  I didn't include any sort of scoping prefix.  I assume the transaction scope is enough?

**Review by JoshFerge — APPROVED** [review]
nice!

**Comment by JoshFerge** [comment]
not sure how sampling works in this context. will have to see, but even 100% is fine for now at low scale. and yeah i think your naming is fine

**Comment by JoshFerge** [comment]
looks like we can do something similar to https://github.com/getsentry/sentry/blob/713cf827ae987a8bf7e65cb7b53bc591810ff832/src/sentry/ingest/ingest_consumer.py#L161 for sampling if we want.

**Review by JoshFerge — APPROVED** [review]

**Pull request merged**
