### PR TITLE
chore(django-3.2): Update django-rest-framework to 3.12.4

### PR DESCRIPTION
**Pull request by AniketDas-Tekky**
3.12.4 is a version that should be compatible with both django 2.2 and 3.2

[Changelogs](https://www.django-rest-framework.org/community/release-notes/#3124)

### CODE REVIEW

**Review by joshuarli — CHANGES_REQUESTED** [review]
Good to see DRF upgrade not break anything, it's certainly been easier than like, the 3.4.x upgrade.

Have you double checked / resynced `monkeypatch_drf_listfield_serializer_errors`?

Also, where are you getting that it's compatible with Django 2.2 + 3.2? Trove classifiers here https://pypi.org/project/djangorestframework/3.12.4/ state 2.2, 3.0, 3.1 - but I would checkout this version in their git and see if they had Django 3.2 running and passing in CI as a better source of truth.

    edit: confirmed 3.12.4 in slack

**Review by joshuarli — APPROVED** [review]
lgtm pending resync (if necessary) of `monkeypatch_drf_listfield_serializer_errors`

**Comment by AniketDas-Tekky** [comment]
So if all the tests are passing, isn’t that verification that `monkeypatch_drf_listfield_serialize_errors` works with 3.12.4?

**Comment by joshuarli** [comment]
> So if all the tests are passing, isn’t that verification that `monkeypatch_drf_listfield_serialize_errors` works with 3.12.4?

No, it just means it hasn't broken our tests.

By resync (if necessary) I mean you should read the portion of upstream code that we're monkeypatching over and seeing if anything changed. And if so, it would be best to update. Otherwise you're holding onto this one piece of code from 3.8.x which you would have otherwise updated along with the 3.12 upgrade.

Of course, we want to keep this part:

```
        # Begin code retained from < drf 3.8.x.
        return [self.child.run_validation(item) for item in data]
        # End code retained from < drf 3.8.x.
```

But if that `to_internal_value` changes, you should mirror those changes.

**Comment by AniketDas-Tekky** [comment]
@joshuarli Took a look at the 3.12 code compared to 3.8 and confirmed that there were no changes between the two versions

**Review by joshuarli — APPROVED** [review]

**Pull request merged**
