### PR TITLE
ref(py3): Decode IngestConsumerWorker msgpack messages

### PR DESCRIPTION
**Pull request by evanpurkhiser**
This sets `raw=False` the same way we did in 3cfd20f2ca for the grouping config messages between relay.

### I am opening this PR more for feedback than I am suggesting it is totally the correct thing.

I have my time split on a different project right now, so can't completely dedicate myself to verifying this.  However, someone who works more closely on relay may be able to.

### CODE REVIEW

**Review by jan-auer — COMMENTED** [review]
I'm pretty sure we want actual strings in the msgpack decoded to `str`. Note that these specific messages also contain *explicit* binary data, which already decodes to `bytes`. I'm not aware of any problems with unpacking those messages at the moment, what is the trigger for this change? 

Unfortunately, I don't fully see the extent of this change. Deferring to @mitsuhiko who may know more about that.

**Comment by BYK** [comment]
>I'm pretty sure we want actual strings in the msgpack decoded to str. Note that these specific messages also contain explicit binary data, which already decodes to bytes. I'm not aware of any problems with unpacking those messages at the moment, what is the trigger for this change?

This is related to the Python 3 migration where all strings are `bytes` in PY2 whereas in PY3, strings need to be unicode (decoded bytes).

**Comment by EvanPurkhiser** [comment]
> I'm not aware of any problems with unpacking those messages at the moment, what is the trigger for this change?

This is explicitly for python 3, which represents both strings and bytes. In it's current form, decoding as raw produces byte string keys, which breaks indexing into the returned message. I would also suspect that there are real strings in the msgpack that should produce unicode string objects.

**Comment by EvanPurkhiser** [comment]
> which already decodes to bytes

Also fwiw there is no `byte` type in python 2. Maybe in python 3 it will correctly decode as bytes though? I'll verify

**Comment by EvanPurkhiser** [comment]
```py
>>> data = msgpack.packb({'test': b'hello'})
>>> msgpack.unpackb(data, raw=False)
{'test': 'hello'}
>>> msgpack.unpackb(data)
{b'test': b'hello'}
```

**Comment by jan-auer** [comment]
I just took a quick look into Relay's integration tests running Python 3, and we use `raw=False` there, too, and manually decode. However, I do not have high confidence that what we're doing there has been investigated carefully.

@EvanPurkhiser I think we will just have to update `msgpack`. With `python 3.8.5` and `msgpack==1.0.0`, I get:

```py
>>> msgpack.unpackb(msgpack.packb({'b': b'b', 'u': u'u', 's': 's'}))
{'b': b'b', 'u': 'u', 's': 's'}
>>> msgpack.unpackb(msgpack.packb({'b': b'b', 'u': u'u', 's': 's'}), raw=False)
{'b': b'b', 'u': 'u', 's': 's'}
>>> msgpack.unpackb(msgpack.packb({'b': b'b', 'u': u'u', 's': 's'}), raw=True)
{b'b': b'b', b'u': b'u', b's': b's'}
```

Note how `raw=False` is now the default.

**Comment by untitaker** [comment]
msgpack 1.0 has only partial Python 2 support. We could use a diff version specifically for Python 3.

**Comment by EvanPurkhiser** [comment]
Created a new PR that upgrades msgpack and notes why doing so works.

**Pull request closed without merging**
