### PR TITLE
Added a quick way to disable the releasefile memcache for js assets

### PR DESCRIPTION
**Pull request by mitsuhiko**

### CODE REVIEW

**Comment by mitsuhiko** [comment]
This intentionally still uses the cache to store negatives.

**Review by mattrobenolt — CHANGES_REQUESTED** [review]
This will just cause a bottleneck elsewhere right now, so we can't do this.

**Comment by markstory** [comment]
Is this something we're still interested in pursuing or can it be closed?

**Comment by mitsuhiko** [comment]
This is no longer relevant. Thanks for cleaning this up.

**Pull request closed without merging**
