### PR TITLE
fix(router): Async Component works without the location prop passed

### LINKED ISSUE #7245: Install Wizard Broken
Something changed in our routing that seems to have stopped passing params/location to child components. We should revert that change, as there is not enough test coverage to ensure we haven't broken other things.

```
$ git diff
diff --git a/src/sentry/static/sentry/app/views/app.jsx b/src/sentry/static/sentry/app/views/app.jsx
index 6f6c8e7d2..842815a8b 100644
--- a/src/sentry/static/sentry/app/views/app.jsx
+++ b/src/sentry/static/sentry/app/views/app.jsx
@@ -131,7 +131,11 @@ const App = createReactClass({
       return (
         <div>
           <Indicators className="indicators-container" />
-          <InstallWizard onConfigured={this.onConfigured} />
+          <InstallWizard
+            onConfigured={this.onConfigured}
+            location={this.props.location}
+            params={this.props.params}
+          />
         </div>
       );
     }
```

### PR DESCRIPTION
**Pull request by lynnagara**
`this.props.location` isn't passed down to child components. Probably changed in React Router 3.

Fixes #7245

### CODE REVIEW

**Comment by lynnagara** [comment]
We can probably pull it off context

**Comment by billyvg** [comment]
Not sure why those tests are failing, they seem unrelated? Also why not use `withRouter`?

**Comment by lynnagara** [comment]
you mean exporting wrapping the whole AsyncComponent in withRouter?

**Comment by billyvg** [comment]
Yeah

**Comment by lynnagara** [comment]
Because other components extend AsyncComponent and that wouldn't work anymore

**Comment by billyvg** [comment]
Ah right

**Review by billyvg — APPROVED** [review]

**Pull request merged**
