### PR TITLE
Sticky Actions Scroll fix

### PR DESCRIPTION
**Pull request by nimishsinghal**
On scrolling, if advance search option is open make header of full width #4924

### CODE REVIEW

**Comment by nimishsinghal** [comment]
Initially I made sticky actions bar full width, now I have disappeared it. Please review and suggest changes if any. If it looks good, will squash the commits and write new commit message.

**Comment by ckj** [comment]
@nimishsinghal Out of curiosity, what was wrong with your first solution? We would prefer to show it if we can.

**Comment by nimishsinghal** [comment]
@sksembhi suggested that removing it on scroll would be a better option that making it full width. It was looking neater by removing it on scrolling.

**Comment by ckj** [comment]
@nimishsinghal Sorry, I missed that. There has been a miscommunication here in the office between @sksembhi and I (which was totally my fault). We actually need the stream actions bar to be shown when the advanced search panel is active.

Can you update your PR to have something along the lines of:

```
.show-sidebar .sticky .stream-actions {
    border-right: 1px solid @trim;
    margin-right: 0;
    padding-right: 10px;
}
```

Once that's in place I will approve this PR and merge.

**Comment by nimishsinghal** [comment]
Thanks @ckj, for reviewing and correcting me. I have made the required changes. Please let me know if anything else is needed.
Also should I squash them to make a single commit?

**Comment by ckj** [comment]
@nimishsinghal No, no thank you. Sorry for the back and forth on our end. Approving now.

**Review by ckj — APPROVED** [review]
👍

**Comment by sksembhi** [comment]
apologies for the miscommunication!

**Comment by nimishsinghal** [comment]
@sksembhi @ckj Please do not apologize. I appreciate the effort you both took in taking out time and guiding me.

If it is okay, I am just curious why the Travis CI build is failing for above PR?

**Comment by JTCunning** [comment]
Danger is my favorite problematic warning system.

**Pull request merged**
