### PR TITLE
ci: only run pre-commit on changed files

### PR DESCRIPTION
**Pull request by joshuarli**
Currently, it takes like, several minutes. Most of this is black and flake8 running on all files.

Admittedly I was being lazy when I first implemented this, but turns out, it's pretty easy.

Only concern I have is that the output of `$(git diff --diff-filter=d --name-only master)` might exceed Linux's limits (`getconf ARG_MAX` - max # bytes of args + environ for exec()). It's usually ~2 MiB though.

If this looks good I'll mirror it to getsentry.

### CODE REVIEW

**Comment by joshuarli** [comment]
@BYK looks like it works - check out https://travis-ci.org/github/getsentry/sentry/jobs/694809636

**Comment by joshuarli** [comment]
Lol it now takes 2 minutes. As opposed to 5 min 30. Really kicking myself here.

**Review by BYK — APPROVED** [review]
>Only concern I have is that the output of $(git diff --diff-filter=d --name-only master) might exceed Linux's limits (getconf ARG_MAX - max # bytes of args + environ for exec()). It's usually ~2 MiB though.

We should probably add this as a comment above the line.

GJ 👏

**Comment by joshuarli** [comment]
I am just realizing now that this noops on master branch builds, obviously because there wouldn't be any files changed compared to itself.

I think this is fine, because you need to pass CI to merge into master anyway. So a good optimization would be to completely omit the pre-commit part of the step if we're building master. (Could split out the dependency scanning job.)

**Pull request merged**
