### PR TITLE
fix(app-platform): don't send issue_ignored webhook for issue unresolved action

### PR DESCRIPTION
**Pull request by nolachen**
The code for sending `issue_ignored` webhooks was indented incorrectly so the `issue_ignored` webhooks were being sent when an issue was unresolved

### CODE REVIEW

**Comment by MeredithAnya** [comment]
I'm surprised we don't have a test that would have caught this but I guess it's just used for analytics?

**Comment by nolachen** [comment]
@MeredithAnya It's the code that sends `issue.ignored` webhooks so that's why those were getting sent when you manually go and unresolve an issue in the UI

**Comment by MeredithAnya** [comment]
@nolachen It looks like that code pre-dates the webhooks stuff we added, I think for this case we are just pigging back off that already being in place if that makes sense. Like it seems like this has been broken for a long time and have the webhook was just a way for us to uncover that haha

**Review by MeredithAnya — APPROVED** [review]

**Review by benvinegar — DISMISSED** [review]
Can we attach a test to this?

**Pull request merged**
