### PR TITLE
feat(gitlab): Add option to search for projects in subgroups

### PR DESCRIPTION
**Pull request by kinghuang**
Add an installation option to the GitLab global organization integration to include projects in subgroups of the GitLab group.

Sentry's current behaviour only allows GitLab projects that are immediate members of the group to be used. When the new “Include Subgroups” option is enabled, projects in all subgroups of the group can also be searched and added.

Contributes to #12774 and #14799. This does not handle projects across an entire GitLab instance (e.g., when self-hosted).

Screen Shot 2019-10-18 at 12 50 45 PM

### CODE REVIEW

**Review by markstory — COMMENTED** [review]
This looks pretty good. Did you need a hand with the tests?

**Comment by kinghuang** [comment]
I think I've got it. I'll push updates hopefully later today.

**Comment by markstory** [comment]
Should we keep this open if #15188 is also open?

**Comment by kinghuang** [comment]
@markstory Up to you. I consider it two different changes. This one adds subgroup search. The other adds whole instance support.

#15188 currently carries the commits from this because there's modifications to the changes introduced here. If this gets merged, it can get rebased.

**Review by markstory — APPROVED** [review]

**Comment by markstory** [comment]
Thank you 👍

**Pull request merged**
