### PR TITLE
chore(span): Track span origin for analytics

### PR DESCRIPTION
**Pull request by philipphofmann**
With https://github.com/getsentry/relay/pull/1984, Relay officially accepts a new property on the span called `origin`. The origin property indicates what precisely created the span. This PR sends origin for opening span details to investigate that data in Amplitude. The Amplitude event is [`Performance Views: Event Details span details opened`](https://data.amplitude.com/sentry/sentry.io/events/main/latest/Performance%20Views%3A%20Event%20Details%20span%20details%20opened?view=All&tab=DETAILS&propertyValidityFilter=All%2520Properties). For more information on trace origin, visit the [develop docs](https://develop.sentry.dev/sdk/performance/trace-origin/).

The draft PR shows what I roughly would like to achieve. Can someone help me and tell me what else I need to do to finish this PR? Do I also need to update some tests?

### CODE REVIEW

**Comment by philipphofmann** [comment]
Hey, @getsentry/performance, I would like a quick review on this one, please 😃 .

**Review by k-fish — APPROVED** [review]
👍

**Review by k-fish — APPROVED** [review]
👍

**Review by k-fish — APPROVED** [review]
👍

**Pull request merged**
