### PR TITLE
ref: upgrade to django 5.0

### PR DESCRIPTION
**Pull request by asottile-sentry**

### CODE REVIEW

**Review by wedamija — COMMENTED** [review]
Looks good to me, I just want to check that you verified that `Queryset.update` hasn't significantly changed, since we should update this if so https://github.com/getsentry/sentry/blob/c8a00d1cf64a349276060458ca51dab9e2538f3e/src/sentry/db/models/manager/base_query_set.py#L32-L74

**Comment by asottile-sentry** [comment]
> Looks good to me, I just want to check that you verified that `Queryset.update` hasn't significantly changed, since we should update this if so
> 
> https://github.com/getsentry/sentry/blob/c8a00d1cf64a349276060458ca51dab9e2538f3e/src/sentry/db/models/manager/base_query_set.py#L32-L74

I didn't, but it doesn't look like it has received any updates that we care about.  there's a proposal to make `returning` a thing but it hasn't been added yet

**Comment by wedamija** [comment]
> > Looks good to me, I just want to check that you verified that `Queryset.update` hasn't significantly changed, since we should update this if so
> > https://github.com/getsentry/sentry/blob/c8a00d1cf64a349276060458ca51dab9e2538f3e/src/sentry/db/models/manager/base_query_set.py#L32-L74
> 
> I didn't, but it doesn't look like it has received any updates that we care about. there's a proposal to make `returning` a thing but it hasn't been added yet

Yeah, that seems to have been hanging around for years so I'm not holding my breath on it happening any time soon!

**Comment by asottile-sentry** [comment]
> > > Looks good to me, I just want to check that you verified that `Queryset.update` hasn't significantly changed, since we should update this if so
> > > https://github.com/getsentry/sentry/blob/c8a00d1cf64a349276060458ca51dab9e2538f3e/src/sentry/db/models/manager/base_query_set.py#L32-L74
> > 
> > 
> > I didn't, but it doesn't look like it has received any updates that we care about. there's a proposal to make `returning` a thing but it hasn't been added yet
> 
> Yeah, that seems to have been hanging around for years so I'm not holding my breath on it happening any time soon!

🤞 yeahhhh -- though I've gotten to delete a lot of the hacky things we've got over time -- one day we'll have less of this stuff 😭

**Review by wedamija — APPROVED** [review]

**Review by joshuarli — APPROVED** [review]

**Pull request merged**
