### PR TITLE
I have rebased 15188

### PR DESCRIPTION
**Pull request by simPod**
I have rebased #15188. What can we do next to proceed?

### CODE REVIEW

**Comment by simPod** [comment]
Eeee

**Review by AniketDas-Tekky — COMMENTED** [review]
Test

**Comment by AniketDas-Tekky** [comment]
Test 2

**Comment by ceorourke** [comment]
Hi @simPod , sorry but we're having a strange issue where we can't leave review comments on specific lines. There are a few things from the old PR that we'd like to get cleaned up before merging this:

https://github.com/getsentry/sentry/blob/bf42249654592926754b24152747a85b06b07ce2/src/sentry/integrations/gitlab/integration.py#L372

I think trimming the trailing `/` got lost somewhere, can you change this line to:

`"domain_name": u"{}/{}".format(hostname, group.get("full_path", "")).rtrim("/"),`

From https://github.com/getsentry/sentry/pull/15188/files#r337079258 


https://github.com/getsentry/sentry/blob/bf42249654592926754b24152747a85b06b07ce2/src/sentry/integrations/gitlab/integration.py#L346

Are you sure this won't result in a `KeyError` if there is no group? https://github.com/getsentry/sentry/pull/15188/files#r418253429


https://github.com/getsentry/sentry/blob/bf42249654592926754b24152747a85b06b07ce2/src/sentry/integrations/gitlab/integration.py#L368

Can you change `instance` here to `_instance_`? It seems like this got lost in a rebase - https://github.com/getsentry/sentry/pull/15188/files#r337081078

**Comment by simPod** [comment]
@ceorourke the issue is because it was so long I forgot about this PR and deleted the repository. Will followup here https://github.com/getsentry/sentry/pull/31375

**Pull request closed without merging**
