### PR TITLE
feat(onboarding): migration to add `disable_member_invite` bit flag to hybrid cloud services

### PR DESCRIPTION
**Pull request by ameliahsu**
recently merged a [migration](https://github.com/getsentry/sentry/pull/76116) to add `disable_member_invite` to the organization bitflag and now need to add it to hybrid cloud services to sync

### CODE REVIEW

**Review by wedamija — COMMENTED** [review]
Migration lgtm

**Review by iamrajjoshi — APPROVED** [review]
lgtm

**Review by markstory — APPROVED** [review]
Looks good to me. We deploy regions first, so when control is deployed it will already be receiving the new flag field and upsert() will continue to behave correctly.

**Review by GabeVillalobos — APPROVED** [review]
Looks good! For future reference, it might be good to split migration changes from the implementation logic just to be safe.

**Pull request merged**
