### PR TITLE
ref(icon refactor): replace icon trash

### PR DESCRIPTION
**Pull request by doralchan**
**Before:**
Screen Shot 2020-04-09 at 11 12 03 AM

**After:**
Screen Shot 2020-04-08 at 8 56 23 PM

### CODE REVIEW

**Comment by billyvg** [comment]
@doralchan would it be better to name it by what it is rather than what it is intended to do?

**Review by billyvg — COMMENTED** [review]
Note there's a component in getsentry that relies on `icon-trash`

**Comment by doralchan** [comment]
@billyvg Yep https://github.com/getsentry/getsentry/pull/3755 Already removed it. I actually thought I'd name it similar to IconAdd, where its action rather than what it is (IconPlus). Was a bit worried people might consider it IconGarbage or IconTrash. IconDelete just seemed easier to remember

**Review by billyvg — APPROVED** [review]
LGTM

This might be worth a discussion after we've replaced all of the icons. I think it could get confusing because some icons are named after what they are and some are the action.

**Pull request merged**
