### PR TITLE
ref(replay): append DOM root inside hidden iframe in createHiddenPlayer

### PR DESCRIPTION
**Pull request by michellewzhang**
relates to performance issues described in https://github.com/getsentry/team-replay/issues/450

**context:**
we want to alleviate the amount of [layout thrashing](https://web.dev/articles/avoid-large-complex-layouts-and-layout-thrashing?utm_source=devtools#avoid-forced-synchronous-layouts) happening (purple gaps in pic below), which is causing performance slowdowns on the breadcrumbs tab and causing certain replays to crash. adding a hidden iframe means it won't affect the main DOM layout. we don't care how the DOM root/Replayer instance renders because in practice, we are just using it to generate the HTML to display in the breadcrumbs tab.

image
taken from the below image, from a crashed replay:
image

new iframe in the hierarchy:

SCR-20240716-mfqa

### CODE REVIEW

**Review by billyvg — APPROVED** [review]
can you double check that this works for the DOM Nodes chart in the Memory tab?

**Comment by c298lee** [comment]
how does the hidden iframe help alleviate layout thrashing?

**Comment by michellewzhang** [comment]
> how does the hidden iframe help alleviate layout thrashing?

i tried to explain that in the description

**Comment by c298lee** [comment]
> > how does the hidden iframe help alleviate layout thrashing?
> 
> i tried to explain that in the description

i am slow 😞 i get it now tyyy

**Comment by michellewzhang** [comment]
> > > how does the hidden iframe help alleviate layout thrashing?
> > 
> > 
> > i tried to explain that in the description
> 
> i am slow 😞 i get it now tyyy

@c298lee aw no worries !!

**Comment by michellewzhang** [comment]
> can you double check that this works for the DOM Nodes chart in the Memory tab?
SCR-20240716-mwjr

looks like we have 2 of these when on the memory tab, seems like expected behavior

**Pull request merged**
