### PR TITLE
fix(ui): Fix spacing on release event list

### PR DESCRIPTION
**Pull request by lynnagara**
Didn't have enough space in the variant where there's no checkbox

### CODE REVIEW

**Comment by lynnagara** [comment]
screen shot 2018-04-09 at 5 47 30 pm

**Review by billyvg — APPROVED** [review]

**Comment by MaxBittker** [comment]
shenk approved 👍

**Comment by shenk0786786** [comment]
I cannot see anywhere magisk app not showing NDK  box not showing anywhere plz check

**Comment by ckj** [comment]
@lynnagara good catch

**Pull request merged**
