### PR TITLE
fix(snuba): Use `tags[sentry:user]` for user distinct count models

### PR DESCRIPTION
**Pull request by tkaemming**

### CODE REVIEW

**Comment by alex-hofsteede** [comment]
wait, what is the difference between `user_id` and `sentry:user` again?

**Comment by alex-hofsteede** [comment]
If we are searching for the users by string, but the tsdb method gets passed user ids, then we also would have to add a translation in https://github.com/getsentry/sentry/blob/master/src/sentry/utils/snuba.py#L187

**Comment by bretthoerner** [comment]
`user_*` fields break out all of the fields in the actual User interface (email, username, id, ip).

`sentry:user` is the one value that the Sentry backend "chooses" for the user. I'm strugging to find it now, but it's basically an order of preference between one of those 4 fields.

**Comment by bretthoerner** [comment]
https://github.com/getsentry/sentry/blob/a7f8f17e1c54582e61304dfb6f897d49066ebd81/src/sentry/models/eventuser.py#L78-L90

**Comment by alex-hofsteede** [comment]
You can ignore my comment about the translations I think. As long as we are effectively just getting `uniq(tags[sentry:user])` and we aren't filtering for specific users by id.

**Comment by tkaemming** [comment]
Yeah, I don't think we're doing anything where the translations would be necessary (at least, they weren't before?)

**Review by alex-hofsteede — APPROVED** [review]
Looks good, I assume existing tests cover this fine.

**Pull request merged**
