### PR TITLE
fix(issues): Add project id to occurrence rate limit key

### PR DESCRIPTION
**Pull request by roggenkemper**
this pr adds the project id to the occurrence rate limit key, some fingerprints can be the same across projects and we don't want to rate limit across projects

### CODE REVIEW

**Review by wedamija — APPROVED** [review]
Probably not too likely to conflict, but worth being cautious

**Review by JoshFerge — APPROVED** [review]
💯

**Comment by JoshFerge** [comment]
> Probably not too likely to conflict, but worth being cautious

hehe 😅 https://github.com/getsentry/sentry/blob/30b553e8e4812b307b7e1492302bcd2ddaf58521/src/sentry/replays/usecases/ingest/issue_creation.py#L40

**Comment by wedamija** [comment]
> > Probably not too likely to conflict, but worth being cautious
> 
> hehe 😅 Screenshot 2024-10-24 at 2 08 43 PM

Lol, I always forget about this

**Pull request merged**
