### PR TITLE
upgrade eslint, upgrade eslint react, fix lints

### PR DESCRIPTION
**Pull request by MaxBittker**
eslint has had a lot of bugfixes and works better with newish things like pure components. this bumps those deps and does some housekeeping to match new rules that they enable.

### CODE REVIEW

**Comment by benvinegar** [comment]
@maxbittker – can you rebase w/ the Prettier changes (might want to wait for the Prettier 1.2.2 patch), then ping me again?

**Review by benvinegar — CHANGES_REQUESTED** [review]
Needs rebase.

**Comment by MaxBittker** [comment]
do you have suggestions for doing this rebase easily? it's messy.

**Comment by MaxBittker** [comment]
closing in favor of https://github.com/getsentry/sentry/pull/5288

**Pull request closed without merging**
