### PR TITLE
feat(ui-components): Add radio group rating - [TET-367]

### PR DESCRIPTION
**Pull request by priscilawebdev**
**What this PR does:**

- Add a new component called `RadioGroupRating` which will be used in the Sampling `FeatureFeedback` in the PR https://github.com/getsentry/sentry/pull/39144
- Export CSS styles from the button component which is now being reused in this new component
- Add the component to the [storybook](https://storybook-jxj2521l9.sentry.dev/) 
- Add unit test

**Preview:**

https://user-images.githubusercontent.com/29228205/191723364-7984ac2d-cfda-42b1-a259-b9131bd76f17.mov

### CODE REVIEW

**Comment by Jesse-Box** [comment]
If you're looking for design feedback @priscilawebdev I would suggest changing the styles for the button that is currently active, exactly how our button bar current functions.

**Comment by priscilawebdev** [comment]
https://user-images.githubusercontent.com/29228205/191924410-e06f1628-85ce-491b-9eae-fcec4612d1da.mov

**Comment by Jesse-Box** [comment]
🚢 it

**Review by matejminar — APPROVED** [review]
Approving so that we can use this in Dynamic Sampling.

If there's feedback from the Core UI team, we can apply/refactor it in a follow-up PR.

**Pull request merged**
