### PR TITLE
feat(ui): Remove Sentry Icon crumb in favor of global 'Back to x' link

### PR DESCRIPTION
**Pull request by ckj**
Removes the Sentry Icon breadcrumb in favor of a contextual 'Back to x' link.

It looks like:

screen shot 2018-02-20 at 5 53 10 pm

It feels like:

💖 

cc @benvinegar

### CODE REVIEW

**Comment by getsentry-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by MaxBittker** [comment]
very nice

**Review by billyvg — APPROVED** [review]
Looks great, definitely seems more obvious on how to leave settings. One comment is that it seems even more disconnected from sentry since there's no "branding" anywhere

**Comment by ckj** [comment]
> it seems even more disconnected from sentry since there's no "branding" anywhere

Agreed. Gonna try to address that before merging.

**Pull request merged**
