### PR TITLE
ref: better SENTRY_SCREENSHOT

### PR DESCRIPTION
**Pull request by joshuarli**
I had to generate some screenshots and view them locally, but the old behavior only snapped a portion of the page, without scrolling or anything.

We had code to capture the entire page under `VISUAL_SNAPSHOT_ENABLE`, so I moved `SENTRY_SCREENSHOT` there.

Also just in general some code improvements (dedenting, mkdirs).

### CODE REVIEW

**Review by billyvg — APPROVED** [review]

**Comment by joshuarli** [comment]
> Action required after 4m — 182 snapshots need review 

🤔

**Comment by joshuarli** [comment]
Well, still not entirely fixed which is strange.

One thing:

```

1 new snapshots

    acceptance-mobile/project-settings-mobile-menu.png
```

The only place mobile_only is used is:

```
tests/acceptance/test_project_general_settings.py
35:            self.browser.snapshot("project settings - mobile menu", mobile_only=True)
```

And the previous logic didn't actually produce a mobile snapshot if `mobile_only=True`, lol, so this PR fixes that too.

**Comment by joshuarli** [comment]
I wonder if it's just flaky; kicking again w/ empty commit.

**Comment by billyvg** [comment]
@joshuarli Hmm odd, I'm not sure what's going on with visual diff, but it looks like it's not picking up changes from some PRs, e.g. https://github.com/getsentry/sentry/pull/21378

**Comment by billyvg** [comment]
@joshuarli nm found the problem, https://github.com/getsentry/sentry/runs/1288550156?check_suite_focus=true#step:2:93

**Comment by joshuarli** [comment]
Still 16 snapshots... not immediately obvious how the code diff as it is now would result in those visual diffs.

**Comment by billyvg** [comment]
@joshuarli pretty sure it just needs a rebase w/ master

**Comment by joshuarli** [comment]
> @joshuarli pretty sure it just needs a rebase w/ master

I've merged a few times, but here's another roll of the dice.

**Comment by joshuarli** [comment]
🤔 117 changed snapshots now LOL

**Comment by joshuarli** [comment]
Fixed by https://github.com/getsentry/sentry/pull/21522. Thanks @billyvg

**Comment by joshuarli** [comment]
Merging - the backend tests are fixed by https://github.com/getsentry/sentry/pull/21545.

**Pull request merged**
