### PR TITLE
ref(processing-issues): Remove /processingissues/fix API endpoint and corresponding ProjectProcessingIssuesFixEndpoint

### PR DESCRIPTION
**Pull request by kamilogorek**
This feature has been broken for 5 years now due to incorrectly used sentry-cli command (`--uuid` instead of `--id` flag which was changed in https://github.com/getsentry/sentry-cli/commit/e8965f8c7d32c67af22b4a5bb267911a45371ee3).

We will remove it from the UI first, and corresponding API removal will follow.

UI change: https://github.com/getsentry/sentry/pull/46495

NOTE: We should wait for a few weeks before merging this. Set myself a reminder to do so.

### CODE REVIEW

**Review by wedamija — COMMENTED** [review]
This endpoint is getting a small amount of hits in saas, is that expected?

**Comment by mitsuhiko** [comment]
@wedamija probably because we hit it on the settings page? What it returns is broken so i don’t think anyone can actually use it.

**Comment by kamilogorek** [comment]
They can copy-paste the auto-fix snippet, which will cause the endpoint hit, but it will do nothing.
So those are probably just people that "try it out" to see if it fixes anything.

**Comment by kamilogorek** [comment]
> NOTE: We should wait for a few weeks before merging this. Set myself a reminder to do so.

A month has passed. Merging.

**Comment by kamilogorek** [comment]
cc @mitsuhiko

**Review by wedamija — APPROVED** [review]

**Pull request merged**
