### PR TITLE
meta(linting): Add flake8-logging

### PR DESCRIPTION
**Pull request by vartec**
Implements #60890 

Adding [flake8-logging](https://github.com/adamchainz/flake8-logging), principally to catch [_LOG003 `extra` key `'<key>'` clashes with LogRecord attribute_](https://github.com/adamchainz/flake8-logging#log003-extra-key-key-clashes-with-logrecord-attribute)

Related to: #60831

### CODE REVIEW

**Comment by vartec** [comment]
Depends on https://github.com/getsentry/sentry/pull/60850

**Comment by vartec** [comment]
Verified that it indeed catches the problem:

pre-commit catching `name` in extra

**Review by asottile-sentry — CHANGES_REQUESTED** [review]
we shouldn't add a plugin with most of its useful codes failing -- it'll perform very poorly

you also need to make getsentry pass as it uses the same set of tools

**Comment by vartec** [comment]
> we shouldn't add a plugin with most of its useful codes failing -- it'll perform very poorly

My idea is to get the tool in first, then iterate on getting rid of these style issues. The more immediate goal is to prevent production outages caused by logging (like the `KeyError "Attempt to overwrite 'name' in LogRecord"` we experienced yesterday). 

From site reliability perspective all the rules that help prevent production incidents are enabled 
([LOG003](https://github.com/adamchainz/flake8-logging#log003-extra-key-key-clashes-with-logrecord-attribute), [LOG012](https://github.com/adamchainz/flake8-logging#log012-formatting-error-n-style-placeholders-but-m-arguments), [LOG013](https://github.com/adamchainz/flake8-logging#log013-formatting-error-missingunreferenced-keys-keys)). 
 
Fixes for the stylistic checks would follow in separate PRs. 
 
> you also need to make getsentry pass as it uses the same set of tools

Good point, I'll validate that.

**Comment by asottile-sentry** [comment]
> > we shouldn't add a plugin with most of its useful codes failing -- it'll perform very poorly
> 
> My idea is to get the tool in first, then iterate on getting rid of these style issues. The more immediate goal is to prevent production outages caused by logging (like the `KeyError "Attempt to overwrite 'name' in LogRecord"` we experienced yesterday).
> 
> From site reliability perspective all the rules that help prevent production incidents are enabled ([LOG003](https://github.com/adamchainz/flake8-logging#log003-extra-key-key-clashes-with-logrecord-attribute), [LOG012](https://github.com/adamchainz/flake8-logging#log012-formatting-error-n-style-placeholders-but-m-arguments), [LOG013](https://github.com/adamchainz/flake8-logging#log013-formatting-error-missingunreferenced-keys-keys)).
> 
> Fixes for the stylistic checks would follow in separate PRs.
> 
> > you also need to make getsentry pass as it uses the same set of tools
> 
> Good point, I'll validate that.

please do the fixes first rather than adding a linter which will be noisy for developers and slow for CI -- they should all be pretty easy and uncontroversial -- perhaps even automatable

**Review by iker-barriocanal — APPROVED** [review]

**Comment by vartec** [comment]
@asottile-sentry  I've fixed all the flake8-logging issues in other PRs (already merged), so this is back to being a minimal PR just adding the plugin, and now it does _not_ ignore anything.

**Comment by asottile-sentry** [comment]
> @asottile-sentry I've fixed all the flake8-logging issues in other PRs (already merged), so this is back to being a minimal PR just adding the plugin, and now it does _not_ ignore anything.

were you able to get to the issues I pointed out in the `getsentry` PR?

**Review by asottile-sentry — APPROVED** [review]

**Pull request merged**
