### PR TITLE
feat(ui): Add 404 page for invalid orgs

### PR DESCRIPTION
**Pull request by billyvg**
Takes SVG from marketing 404s and ported to React (e.g. https://sentry.io/for/fdsafdsa/)

image

### CODE REVIEW

**Review by markstory — APPROVED** [review]

**Review by ckj — CHANGES_REQUESTED** [review]
This needs a home button of some kind -- maybe our logo at the top of the sidebar would be enough?

**Comment by cameronmcefee** [comment]
Does this load in a place where dark backgrounds aren't possible? It wasn't designed to be on a light background and looks kinda bad

**Comment by billyvg** [comment]
@ckj I have https://github.com/getsentry/sentry/pull/9846 that adds in the user dropdown menu.

**Comment by ckj** [comment]
> Does this load in a place where dark backgrounds aren't possible?

We don't have anything else in the app with this much contrast, so I thought the experience of a 404 _and_ the dark background might be overly jarring.

@billyvg did you try the dark bg?

**Comment by ckj** [comment]
> @ckj I have #9846 that adds in the user dropdown menu.

Nice, that should be enough then

**Comment by cameronmcefee** [comment]
Maybe we should make something designed for this purpose? Seems a bit square peg/round hole.

Also the fonts aren't loading in the app so you've got some nasty serifs on those buttons.

**Comment by billyvg** [comment]
The buttons are also serifed in the original? https://sentry.io/for/aowekrowae/

I agree, it'd be preferable to make something, but doesn't seem like it should be a priority. I have no problem closing up this PR if people are not happy with it.

**Comment by cameronmcefee** [comment]
> The buttons are also serifed in the original? https://sentry.io/for/aowekrowae/

Damn, I must be loading from local fonts. I guess that needs that needs to be resolved.

I guess I don't feel strongly enough to be a blocker, and I can't commit my personal time, so let's pretend I didn't drop in here.

**Comment by billyvg** [comment]
@ckj gonna defer to you to see what we want to do

**Comment by ckj** [comment]
@billyvg I'm thinking this could be more trouble than it's worth. I think i'd settle for #9846 with a nicer error message and better padding

**Pull request closed without merging**
