### PR TITLE
fix(ui): Do not display the dropdown clear button for the dropdown list of environments if it is empty

### PR DESCRIPTION
**Pull request by dashed**
Before:
Screen Shot 2019-06-21 at 4 14 14 PM

After:

Screen Shot 2019-06-21 at 4 14 37 PM

### CODE REVIEW

**Comment by billyvg** [comment]
The bug is deeper than the clear button... here's kind of a bandaid: https://github.com/getsentry/sentry/pull/13334

**Comment by dashed** [comment]
@billyvg ooo, I wasn't aware that there was work begun for SEN-661.

**Comment by billyvg** [comment]
Is this still needed since it's a bug if you have an environment value without any environments and should probably be fixed at its source.

**Comment by dashed** [comment]
I'll close this.

**Pull request closed without merging**
