### PR TITLE
fix: replace usage of global functions in Lua with locals

### PR DESCRIPTION
**Pull request by sigmaris**
Redis 6.2.7 and 7.0.0 include a [security fix](https://github.com/redis/redis/pull/10651) which forbids modifying Lua globals, including by defining new global functions. This causes e.g. the current `digests.lua` script to fail with an error: `redis.exceptions.ResponseError: Error running script (call to f_094f8735408af273da283389ad983f63977831e8): @user_script:11: user_script:11: Attempt to modify a readonly table`
To fix the issue, this PR replaces global function definitions with local functions.

----

By submitting this pull request, I confirm that Sentry can use, modify, copy, and redistribute this contribution, under Sentry's choice of terms.

### CODE REVIEW

**Review by jjbayer — COMMENTED** [review]
@sigmaris I understand the addition of the `local` keyword. Is renaming the functions (from `.` to `_`) also necessary? @getsentry/ecosystem might be a better reviewer because they own other digests-related source code: https://github.com/getsentry/sentry/blob/5bda44de64fb20500978dbefb552af6062629907/.github/CODEOWNERS#L215

**Comment by sigmaris** [comment]
> I understand the addition of the local keyword. Is renaming the functions (from . to _) also necessary? 

It seems like it is necessary; I tried just adding the `local` keyword and keeping the function names as they were, but Lua refuses to parse that - it complained that `.` wasn't an allowed character in the name. AFAIK this is a syntactic difference between global and local function definitions.

**Comment by sigmaris** [comment]
I pushed a new version which moves `table_ireduce` to be defined before it's used in `sum`.

**Comment by sigmaris** [comment]
Is there any action/changes required from me on this PR? I saw that the Google Cloud Build / self-hosted-github-pr-check (sentryio) check failed, but I can't seem to see any more details in Google about why it failed, so can't determine if anything needs changed on the PR.

**Comment by untitaker** [comment]
@chadwhitacre can you help out with this failing docker build?

**Comment by chadwhitacre** [comment]
Sorry, missed the notification on this. Rerunning to see if it's still failing ...

**Comment by chadwhitacre** [comment]
Still failing in CI.

I'm now running locally with https://github.com/getsentry/self-hosted/commit/6c88b78de6f15a19d8cf99e16d21517eed16461d and:

```diff
diff --git a/.env b/.env
index acb4ee8..19cf7d8 100644
--- a/.env
+++ b/.env
@@ -5,7 +5,7 @@ SENTRY_EVENT_RETENTION_DAYS=90
 SENTRY_BIND=9000
 # Set SENTRY_MAIL_HOST to a valid FQDN (host/domain name) to be able to send emails!
 # SENTRY_MAIL_HOST=example.com
-SENTRY_IMAGE=getsentry/sentry:nightly
+SENTRY_IMAGE=getsentry/sentry:c70d88c4f87e2e7d164ad4d32a92291ac9274a76
 SNUBA_IMAGE=getsentry/snuba:nightly
 RELAY_IMAGE=getsentry/relay:nightly
 SYMBOLICATOR_IMAGE=getsentry/symbolicator:nightly
```

I pulled that SHA from [the GCP build](https://console.cloud.google.com/cloud-build/builds/8e4f980d-2213-4aac-a987-07ebba3cc638;step=2?project=sentryio):

```
INFO[0033] Pushing image to us.gcr.io/sentryio/sentry:c70d88c4f87e2e7d164ad4d32a92291ac9274a76 
```

My expectation is that this will fail with the same 404 as I'm seeing in GCP:

```
Step #4 - "e2e-test": [32;1mweb_1                                       |[0m 13:20:05 [WARNING] django.request: Not Found: /api/0/projects/sentry/internal/events/83bf51e9886308294e17ce20825d2879/ (status_code=404 request=<WSGIRequest: GET '/api/0/projects/sentry/internal/events/83bf51e9886308294e17ce20825d2879/'>)
Finished Step #4 - "e2e-test"
ERROR
ERROR: build step 4 "gcr.io/sentryio/docker-compose" failed: step exited with non-zero status: 124
```

**Comment by chadwhitacre** [comment]
Oh right my local self-hosted env is [in the mud](https://github.com/getsentry/self-hosted/issues/914). 😞

@sigmaris Have you tested this patch against Redis 6.2.4? If not, could you? That's the version we pin to in self-hosted and presumably SaaS, whatever we come up with here should support that version if we want to get this across without waiting for SaaS to upgrade Redis.

**Comment by ilylia** [comment]
wait for this PR!

**Comment by jjbayer** [comment]
@sigmaris any update on this?

> @sigmaris Have you tested this patch against Redis 6.2.4? If not, could you? That's the version we [pin to in self-hosted](https://github.com/getsentry/self-hosted/blob/22.5.0/docker-compose.yml#L109) and presumably SaaS. Whatever we come up with here should support that version if we want to get this across without waiting for SaaS to upgrade Redis.

**Comment by sigmaris** [comment]
I have some time this week to work on this, I'll try testing it as part of self-hosted, using Redis 6.2.4 and running the `./integration-test.sh` in the self-hosted repository.

**Comment by sigmaris** [comment]
I've checked out the `self-hosted` repo and applied this patch:
```diff
diff --git a/.env b/.env
index acb4ee8..59cf80d 100644
--- a/.env
+++ b/.env
@@ -5,7 +5,7 @@ SENTRY_EVENT_RETENTION_DAYS=90
 SENTRY_BIND=9000
 # Set SENTRY_MAIL_HOST to a valid FQDN (host/domain name) to be able to send emails!
 # SENTRY_MAIL_HOST=example.com
-SENTRY_IMAGE=getsentry/sentry:nightly
+SENTRY_IMAGE=us.gcr.io/sentryio/sentry:7c57fe7b17f613fecc47a56c22fff3a20a958496
 SNUBA_IMAGE=getsentry/snuba:nightly
 RELAY_IMAGE=getsentry/relay:nightly
 SYMBOLICATOR_IMAGE=getsentry/symbolicator:nightly
```
i.e. use the Sentry image built from this branch, but otherwise use the regular images for other components including `redis:6.2.4-alpine`; I was able to successfully run the integration tests in `self-hosted` via `./integration-test.sh`, and looking in the UI I didn't see any problems, so compatibility seems OK with Redis 6.2.4.

**Review by jjbayer — APPROVED** [review]
Looks good to me. Would still be nice to get a review from @getsentry/ecosystem though.

**Review by leeandher — APPROVED** [review]
looks good to me 🚀  Thanks for taking a look at this!!

**Comment by untitaker** [comment]
ok, i'm gonna merge this since it was initially assigned to ingest

**Comment by untitaker** [comment]
thansk for the pr @sigmaris and sorry for the slow turnaround!

**Pull request merged**
