### PR TITLE
Don't redirect to login page for share page

### LINKED ISSUE #3395: Share page in some circumstances keeps reloading
In certain circumstances the event share page has been reported to reload constantly.

Example event from sentry's payment backend: https://app.getsentry.com/share/issue/312e313330383536353235/

### PR DESCRIPTION
**Pull request by benvinegar**
Fixes #3395 

Not pretty, but it works. I intend to follow-up and let you specify whether a route is anonymous inside the route declaration.

cc @getsentry/ui @mitsuhiko

### CODE REVIEW

**Comment by mitsuhiko** [comment]
Can we not just instead of doing this just not make the failing 401 requests? eg: system health.

**Comment by dcramer** [comment]
Id rather not duct tape API responses just to handle broken UI code

**Comment by mitsuhiko** [comment]
@dcramer does your comment imply not making the failing api calls?

**Comment by dcramer** [comment]
@mitsuhiko no -- the internal health is a normal API endpoint, we shouldnt special case it because the UI isn't built to handle it. The UI can just fail gracefully on a 401 there, rather than suggesting we actually need to auth.

**Comment by mitsuhiko** [comment]
@dcramer i'm more thinking along the lines of marking specific api requests as being fine if they are failing for permission errors. The health endpoint being one of them.

**Comment by mitsuhiko** [comment]
I just heavily dislike making share page specific code in our permission error handler. Too obscure.

**Comment by benvinegar** [comment]
I just wanted to get this patch out quick so that the bug is solved. Other solutions seem more involved. I will follow up.

**Comment by mitsuhiko** [comment]
@benvinegar let's just merge it then and leave a clear todo somewhere

**Comment by benvinegar** [comment]
Added a todo comment.

**Comment by mitsuhiko** [comment]
🍪

**Pull request merged**
