### PR TITLE
chore(ts): upgrade to typescript 4.2

### PR DESCRIPTION
**Pull request by alxu-sentry**
https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/
https://devblogs.microsoft.com/typescript/announcing-typescript-4-2/

a bunch of fixes for 4.1. no changes needed for 4.2, it comes "free".

### CODE REVIEW

**Review by markstory — APPROVED** [review]
Looks good to me.

**Comment by billyvg** [comment]
@getsentry/app-frontend Can someone help get this merged? We will also need a getsentry PR as well

**Review by evanpurkhiser — APPROVED** [review]
I think we can merge @scttcper wanna handle this one?

**Pull request merged**
