### PR TITLE
feat(minidump): Optionally add minidumps as event attachments

### PR DESCRIPTION
**Pull request by mitsuhiko**
This is the replacement for #9379

### CODE REVIEW

**Comment by mitsuhiko** [comment]
https://github.com/getsentry/sentry/pull/9380/commits/0728026cfba0070afc37f65f7f52cc2f941f8c71 fixes the earlier commit before the deploy that broke it: https://github.com/getsentry/sentry/pull/9379/commits/61e8c95baa0e4cd5a8889304481e886e659c0bba

I will add a basic test for this.

**Comment by mitsuhiko** [comment]
Added a test but also noticed that we should add a full minidump test so I will add that before we merge it. Makes me feel more confident.

**Comment by mitsuhiko** [comment]
Added more tests. If they pass I think this is good for deployment.

**Review by jan-auer — APPROVED** [review]
Thanks for adding such comprehensive tests. 👏

Optionally, we could also add one more test with enabled `organizations:event-attachments` but disabled `sentry:store_crash_reports` to see that minidumps do not get attached but all other files do.

**Comment by jan-auer** [comment]
Please disregard my above comment, I misread the test.

**Review by mattrobenolt — APPROVED** [review]
🍪

**Pull request merged**
