### PR TITLE
ref(grouping): Make `GroupingComponent` generic and add subclasses

### PR DESCRIPTION
**Pull request by lobsterkatie**
This adds a full taxonomy of `BaseGroupingCompontent` subclasses, partially just as a form of documentation (we create this deeply nested `variants` structure when grouping, and it's helpful to understand what kind of data is in each part), and partially so that it's easier to write helpers dealing with different kinds of components and not have to constantly be checking for the presence of this or that attribute.

Key changes:

- Make `BaseGroupingComponent` generic, so that subclasses can specify the types allowed in `values`.
- Allow `id` to be a class attribute (no longer require it to be passed to `__init__`), so that it can be specified in each subclass.
- Add overloads of `get_single_grouping_component`.
- Use a `TypeVar` to make `ReturnedVariants` covaraint. This is a bit of a hack, but fixing it will require a larger change than felt reasonable here. (Basically, we'll have to make everywhere it's used treat it as read-only.) I left a TODO.

### CODE REVIEW

**Comment by lobsterkatie** [comment]
@JoshFerge, to answer your questions from https://github.com/getsentry/sentry/pull/80503:

> can this be made abstract?

and 

> why would we ever pass in id if there are specific subclasses for each grouping component?

So right now, it creates one outer-most wrapper component corresponding to the variant after it's made the entire rest of the tree:

https://github.com/getsentry/sentry/blob/16f14bca196da243f667072880177abb1e000325/src/sentry/grouping/api.py#L294-L298

It's not 100% clear _why_, though, and I suspect things could be simplified here so that it doesn't. (In other words, instead of creating `variant -> this wrapper component -> real top-level component`, I suspect we could switch it to just doing `variant -> real top-level component`.) If we did that simplification, then the answers to your questions would be _yes, we could_ and _no reason_. As it stands I could make subclasses for those wrappers as well, in which case the answers would be the same, or I could wait and take a look at getting rid of the wrapper first. I don't have a strong feeling, do you?

**Comment by JoshFerge** [comment]
> @JoshFerge, to answer your questions from #80503:
> 
> > can this be made abstract?
> 
> and
> 
> > why would we ever pass in id if there are specific subclasses for each grouping component?
> 
> So right now, it creates one outer-most wrapper component corresponding to the variant after it's made the entire rest of the tree:
> 
> https://github.com/getsentry/sentry/blob/16f14bca196da243f667072880177abb1e000325/src/sentry/grouping/api.py#L294-L298
> 
> It's not 100% clear _why_, though, and I suspect things could be simplified here so that it doesn't. (In other words, instead of creating `variant -> this wrapper component -> real top-level component`, I suspect we could switch it to just doing `variant -> real top-level component`.) If we did that simplification, then the answers to your questions would be _yes, we could_ and _no reason_. As it stands I could make subclasses for those wrappers as well, in which case the answers would be the same, or I could wait and take a look at getting rid of the wrapper first. I don't have a strong feeling, do you?

The implementation in your PR allows for:
```
from sentry.grouping.component import LineNumberGroupingComponent
LineNumberGroupingComponent(id="somthing_else")
```

which feels quite strange to me. i would advocate for removing the ability to pass in `id`, as well as making `BaseGroupingComponent` an abstract class so that we can have a stronger relationship of `id` to the subclasses, and remove confusion about what future implementations should do to implement a new component type.

**Review by JoshFerge — APPROVED** [review]

**Comment by lobsterkatie** [comment]
> The implementation in your PR allows for:
> 
> ```
> from sentry.grouping.component import LineNumberGroupingComponent
> LineNumberGroupingComponent(id="somthing_else")
> ```
> 
> which feels quite strange to me.

That's fair. I'll add in the variant components and make it abstract, without the ability manually set the id.

**Comment by JoshFerge** [comment]
> > The implementation in your PR allows for:
> > ```
> > from sentry.grouping.component import LineNumberGroupingComponent
> > LineNumberGroupingComponent(id="somthing_else")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > which feels quite strange to me.
> 
> That's fair. I'll add in the variant components and make it abstract, without the ability manually set the id.

👍🏼 please feel free to do afterwards, don't want this comment to block the feature work

**Pull request merged**
