### PR TITLE
chore(hybridcloud) Move apigateway middleware

### PR DESCRIPTION
**Pull request by markstory**
Move the middleware class to be with the rest of the apigateway logic.

Refs HC-982

### CODE REVIEW

**Review by corps — APPROVED** [review]
Curious to see if our new grouping logic correctly groups api gateway errors after the package rename! @JoshFerge

**Comment by JoshFerge** [comment]
> Curious to see if our new grouping logic correctly groups api gateway errors after the package rename! @JoshFerge

bring it on!!

**Comment by JoshFerge** [comment]
also: have we considered marking some of the hybrid cloud files as non-in-app in our stacktrace rules?

**Comment by markstory** [comment]
> also: have we considered marking some of the hybrid cloud files as non-in-app in our stacktrace rules?

They are in-app to *me* though 😄

**Pull request merged**
