### PR TITLE
ref(workflow): Reducing rate limit from 10req/sec/ip to 5req/sec/ip

### PR DESCRIPTION
**Pull request by iProgramStuff**
This may not actually achieve anything and may need to be integrated with performance improvements (more collapse/expand support?) to prevent Snuba from being sent a "thundering herd [...] when someone tries to scrape all issues". But it shouldn't hurt.

This applies only to issue/group details.

Resolves WOR-579?

### CODE REVIEW

**Review by wedamija — APPROVED** [review]
Seems fine to me. 5/s is still a lot, but at least we're halving the number of requests.

**Comment by iProgramStuff** [comment]
I changed it to 1, will merge when CI finishes. Maybe 1 is low enough to be useful but not low enough to be annoying.

**Comment by wedamija** [comment]
> I changed it to 1, will merge when CI finishes. Maybe 1 is low enough to be useful but not low enough to be annoying.

I think 1 is a bit low. If the user refreshes the page quickly they might hit this... We could do something like 10/10 seconds, which averages out the same. That likely means we'd get bursts of 10 requests from people hammering our api though.

**Pull request merged**
