### PR TITLE
Relocate short id on issue detail

### PR DESCRIPTION
**Pull request by ckj**
Moves the short id to the right of the message/culprit area by shifting 'Seen by' to where the 'Share' action was and moving Share to the More... dropdown. Okay that's confusing, pics or it didn't happen:

screen shot 2016-05-13 at 2 47 36 pm

cc @getsentry/ui

### CODE REVIEW

**Comment by dcramer** [comment]
I like the visual for short ID over what we had before

I'm not a huge fan of hiding share under more so would prefer an alternative if we can come up with one.

**Comment by benvinegar** [comment]
Definitely +1 on moving callsign and de-prioritizing it.

We could make the "More" button not be a drop-down if there's just one item (I thought we did that already?).

**Comment by ckj** [comment]
> We could make the "More" button not be a drop-down if there's just one item (I thought we did that already?).

@benvinegar I removed that as a part of this, but now that I think about it that wasn't necessary. There's some complexity there, but I think i'll try to bring it back.

**Comment by EvanPurkhiser** [comment]
@ckj is this something that we can close out? Looks pretty darn old

> This is part of my attempt to reduce the number of open PRs we have.

**Comment by ckj** [comment]
Yep!

**Pull request closed without merging**
