### PR TITLE
ref(escalating-issues): Delete GroupForecast Table

### PR DESCRIPTION
**Pull request by jangjodi**
Step 3 of removing the GroupForecast table

See step 2: removing the GroupForecast model [here](https://github.com/getsentry/sentry/pull/47593)
See step 1: removing the foreign key constraint in the GroupForecast table [here](https://github.com/getsentry/sentry/pull/47578)

WOR-2966

### CODE REVIEW

**Review by lobsterkatie — APPROVED** [review]

**Review by wedamija — APPROVED** [review]
lgtm, please make sure that this isn't merged until https://github.com/getsentry/sentry/pull/47593 is merged + deployed

**Comment by barkbarkimashark** [comment]
You'll need to delete these tests to get tests to pass:
`tests/sentry/migrations/test_0417_backfill_groupedmessage_substatus.py`
`tests/sentry/migrations/test_0420_backfill_groupedmessage_ignored_substatus.py`

**Review by wedamija — APPROVED** [review]
That test failure should be unrelated... I'd try just rebasing on latest master

**Comment by barkbarkimashark** [comment]
> That test failure should be unrelated... I'd try just rebasing on latest master

Was referring to this test failure: https://github.com/getsentry/sentry/actions/runs/4747748622/jobs/8433063906

**Pull request merged**
