### PR TITLE
fix(settings): Breadcrumb dropdown showed the same organization

### PR DESCRIPTION
**Pull request by leedongwei**
Found a long-term fix for #19098

### CODE REVIEW

**Comment by leedongwei** [comment]
I reviewed all the usage of `IdBadge` and `OrganizationBadge` and those that wants organization to be displayed would pass the value in as a prop. `withOrganization` is not needed.

**Comment by billyvg** [comment]
Off the top of my head, the parts that could be affected by this change could be the sidebar on `/manage/` and maybe the account settings.

**Comment by leedongwei** [comment]
@billyvg Gotcha, I'll check through on `staging` before merging

**Comment by leedongwei** [comment]
I've looked around on staging. `/manage/` didn't use either of the badges. There's no change to settings page.

**Review by billyvg — APPROVED** [review]

**Comment by billyvg** [comment]
Thanks for checking those

**Review by dashed — APPROVED** [review]

**Pull request merged**
