### PR TITLE
Use random group generator for email previews.

### PR DESCRIPTION
**Pull request by tkaemming**
This uses the random group generator for generating content for email previews so that there is more  variation when developing. Specifically, this will generate different event types at random.

This is extracted from GH-3621, since I mainly just wanted to get a baseline for the visual tests, which use a seeded random number generator to ensure deterministic rendering.

---

This change is [Reviewable](https://reviewable.io/reviews/getsentry/sentry/3699)

### CODE REVIEW

**Comment by dcramer** [comment]
This will break percy as it causes inconsistent diffs

**Comment by tkaemming** [comment]
I'm not sure if you read the description or the code. Can you provide an example where that'd occur?

**Comment by dcramer** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3699#-:-KMVcbtyD63cnSJdUy-8:1417088721)*

**Comment by dcramer** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3699)*

**Pull request merged**
