### PR TITLE
Remove martini integration

### PR DESCRIPTION
**Pull request by ribice**
In lieu with https://github.com/getsentry/sentry-go/pull/861

### CODE REVIEW

**Comment by priscilawebdev** [comment]
nice! Thanks for keeping a lookout 👏🙂

**Review by priscilawebdev — DISMISSED** [review]

**Comment by priscilawebdev** [comment]
Let's remove 'go-martini' only in `static/app/data/platformPickerCategories.tsx`  and `static/app/components/onboarding/frameworkSuggestionModal.tsx`, so users can not create this project anymore

**Comment by ribice** [comment]
> Let's remove 'go-martini' only in `static/app/data/platformPickerCategories.tsx` and `static/app/components/onboarding/frameworkSuggestionModal.tsx`, so users can not create a project with this platform anymore

Should the text in `static/app/gettingStartedDocs/go/martini.tsx` remain?

**Comment by priscilawebdev** [comment]
@ribice Yes, so users with a Martini project that hasn't been set up yet can still view the instructions for sending events

**Comment by ribice** [comment]
@priscilawebdev Opened a new one https://github.com/getsentry/sentry/pull/76375

**Pull request closed without merging**
