### PR TITLE
Update all var tables to use new-style rendering

### PR DESCRIPTION
**Pull request by dcramer**
/cc @getsentry/ui @ckj

### CODE REVIEW

**Comment by dcramer** [comment]
screenshot 2016-06-17 14 00 13

**Comment by benvinegar** [comment]
I think the sample data looks pretty good in the screenshots above, but I have some live examples where values are some combination of large/not predictable and as a result you lose some significant document structure. The pages also become very, very white.

One example (this could also just be a problem that could be solved with better value rendering):

image

**Comment by dcramer** [comment]
@benvinegar thats actually unrelated to this change (the vars stuff is elsewhere). This was just changing all of the others, but I think we all agree the lack of structure for this in other places makes it much less useful so I'm going to close it out.

**Comment by ckj** [comment]
❤️

**Pull request closed without merging**
