### PR TITLE
feat(traces): Add definitions for span field search keys

### PR DESCRIPTION
**Pull request by 0Calories**
Adds definitions for span search fields. This affects mainly the search in the Traces page, but also several searchbars in Insights modules that allow for searching on spans.

Initially, I planned on referencing `SpanIndexedField` and `SpanMetricsField` when setting the definitions, but importing it results in a circular dependency due to the file they reside in also importing from `static/app/utils/fields/index.ts`. I decided to create a `TraceFields` enum instead which results in some code duplication, but the alternative is a massive and fairly messy refactor.

Related to https://github.com/getsentry/sentry/issues/74276

image

Side note; I noticed that most of these definitions are missing in our documentation, we should update them there as well once we've decided on adequate descriptions for these fields.

### CODE REVIEW

**Review by gggritso — COMMENTED** [review]
>  importing it results in a circular dependency

Ouch! If I'm reading this right, I think you can resolve the circular dependency by extracting `STARFISH_AGGREGATION_FIELDS` into its own file! That will eliminate the imports for 

```tsx
import type {AggregationOutputType} from 'sentry/utils/discover/fields';
import {DiscoverDatasets} from 'sentry/utils/discover/types';
import {FieldKind, FieldValueType} from 'sentry/utils/fields';
```

You can also delete `StarfishDatasetFields`, it's unused. That will remove the import for

```tsx
import {DiscoverDatasets} from 'sentry/utils/discover/types';
```

That should remove the circular dependency

**Comment by 0Calories** [comment]
Thanks for the suggestion @gggritso, that refactor was a lot cleaner

**Review by gggritso — APPROVED** [review]
Nice! Although, I have a nit. "i.e.," and "e.g.,"` are different! 

Correct:

>i.e. the tables involved in a `db` span or the host name in an `http` span'

Not correct, should be "e.g.,"

> i.e `http.client`, `middleware`
> i.e `cache`, `db`, `http`, etc.

See [Chicago Manual of Style](https://www.chicagomanualofstyle.org/qanda/data/faq/topics/Abbreviations/faq0047.html) for deets

**Review by Zylphrex — APPROVED** [review]
Nice! 🎉 This is a good start

**Comment by 0Calories** [comment]
@gggritso learned something new today, thanks! But this also made me realize we have a lot of field definitions (aside from the ones I added) that incorrectly use i.e. 😅

**Pull request merged**
