### PR TITLE
Add discard pending processing issues button

### PR DESCRIPTION
**Pull request by HazAT**
This adds functionality to discard pending events for reprocessing.
Under some circumstances it can occur that events will be forever stuck in reprocessing, we are still trying to figure out the conditions.
This PR adds a button so all pending issues with their events can be deleted.

sentry___internal

@ckj Probably need some feedback on UI

### CODE REVIEW

**Comment by getsentry-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by mitsuhiko** [comment]
Generally +1 on the button, but I think we should make this entire page look nicer :)

**Comment by HazAT** [comment]
This is the final form!
screenshot 2017-08-23 10 50 37

**Review by mitsuhiko — APPROVED** [review]

**Comment by dcramer** [comment]
Great improvement! I'd love to see this take on a dedicated page that isn't linked (unless there are relevant issues).

e.g. the stream (and similar) show a banner saying there are N processing issues, you click that and it goes to a dedicated page that has no standard nav

**Comment by mitsuhiko** [comment]
Yeah. I think we should move the reprocessing checkbox into general settings and then move this page to a dedicated popup. But that might need @ckj to make a general design for these dialogs. Won't be the last.

**Comment by HazAT** [comment]
I agree, this page is more like a status/internal issue collection, actually, just the small switch is the only setting here. 
We should probably think about having like a project status page, because right now the only way to display internal issues is with the banner on the top (which does not provide enough space).

**Pull request merged**
