### PR TITLE
chore(flag): for issue alerts targeting

### PR DESCRIPTION
**Pull request by jeffkwoh**
Feature docs: https://www.notion.so/sentry/Issue-Alert-Targeting-30805fa4d233467ab2edb3eb98fce25e

### CODE REVIEW

**Comment by dashed** [comment]
@jeffkwoh may need to add this flag to this list https://github.com/getsentry/sentry/blob/657322392fb3e343473c8e2f24c645462e8a10f8/src/sentry/features/__init__.py#L109-L117

**Comment by dashed** [comment]
@jeffkwoh I could be wrong about this. Can you confirm with your team?

**Review by wedamija — APPROVED** [review]
No need for snuba here afaict, we're just modifying who can be targeted by an issue alert, which doesn't require a snuba query.

**Comment by jeffkwoh** [comment]
Thanks @dashed  and @wedamija

**Pull request merged**
