### PR TITLE
ref(js): Load members when loading organization

### PR DESCRIPTION
**Pull request by evanpurkhiser**
This is more of an RFC.

Right now we basically don't load members unless components explicitly do it.

Places we load members right now

* Project context (used in project settings)
  https://github.com/getsentry/sentry/blob/274c1cdc395e80b2a90f05d24cf2335a9d5f5c54/static/app/views/projects/projectContext.tsx#L200

* Issue list overview 
  https://github.com/getsentry/sentry/blob/274c1cdc395e80b2a90f05d24cf2335a9d5f5c54/static/app/views/issueList/overview.tsx#L384-L388

* Group list (Like issue list, but used in other pages lol)
  https://github.com/getsentry/sentry/blob/274c1cdc395e80b2a90f05d24cf2335a9d5f5c54/static/app/components/issues/groupList.tsx#L126-L128

* Assigned to thing
  https://github.com/getsentry/sentry/blob/274c1cdc395e80b2a90f05d24cf2335a9d5f5c54/static/app/components/group/assignedTo.tsx#L185-L188

* Rule builder project provider thing
  https://github.com/getsentry/sentry/blob/274c1cdc395e80b2a90f05d24cf2335a9d5f5c54/static/app/views/alerts/builder/projectProvider.tsx#L45-L50

* Dashboards
  https://github.com/getsentry/sentry/blob/274c1cdc395e80b2a90f05d24cf2335a9d5f5c54/static/app/views/dashboards/dashboard.tsx#L178-L186

* Widget builder
  https://github.com/getsentry/sentry/blob/274c1cdc395e80b2a90f05d24cf2335a9d5f5c54/static/app/views/dashboards/widgetBuilder/widgetBuilder.tsx#L322-L324

* Metrics alert rule form builder
  https://github.com/getsentry/sentry/blob/274c1cdc395e80b2a90f05d24cf2335a9d5f5c54/static/app/views/alerts/rules/metric/triggers/form.tsx#L138-L142

* Metrics details
  https://github.com/getsentry/sentry/blob/274c1cdc395e80b2a90f05d24cf2335a9d5f5c54/static/app/views/alerts/rules/metric/details/index.tsx#L55

All these things should be able to be updated to use an upcoming `useMembers` thing I'm building, but even that will want to have things loaded early.

It doesn't have to be done like this though, maybe we can do it in the hook with useApiQuery instead.

### CODE REVIEW

**Comment by billyvg** [comment]
Isn't it better to load members on demand? We're already making a lot of API requests on page load.

**Comment by malwilley** [comment]
If we really _do_ want to fetch org members earlier, I don't think we want to do it in this function since this will block the page load (something that already takes too long).

I totally agree though that all the places you mention should be using a central cache of some sort instead of fetching results independently.  But I think that we should be trying to get to a place where we load projects/teams/members ahead on demand instead of on load since those entities are unbounded and can take a long time to load.

**Comment by evanpurkhiser** [comment]
Yeah I think I can move most of these over to using `useMembers` and have it use `useApiQuery` to deduplicate requests it's making, and then just use the API client for doing searches

**Comment by evanpurkhiser** [comment]
btw afaict this doesn't actually block page load

**Pull request closed without merging**
