### PR TITLE
chore: Bump moment to align moment requirements

### PR DESCRIPTION
**Pull request by evanpurkhiser**

### CODE REVIEW

**Review by billyvg — APPROVED** [review]

**Comment by EvanPurkhiser** [comment]
@billyvg Could you take a look at this again real quick? I had to explicitly configure the users timezones  in a couple tests otherwise it was defaulting to UTC time.

**Comment by billyvg** [comment]
That's odd that bumping moment would break these tests.... I wonder if is related to our configuration of the env var `TZ` in `scripts/test.js` 

anyway I think it'd be better if we set the timezone globally in `tests/js/setup.js` instead of on a per test basis

**Comment by EvanPurkhiser** [comment]
Ahh, I didn't know about the `TZ` variable. I'll test that. I spent some time looking through the moment.js change logs to try and understand what was causing breaking, but couldn't pin down the exact change.

**Comment by EvanPurkhiser** [comment]
Yeah the `process.env.TZ` variable is absolutely causing problems.

We actually already set the use's timezone to UTC in `tests/js/setup.js`, which is a sane default I think, so it probably makes sense for these timzezone specific tests to have the timezone changed individually on the test.

**Review by billyvg — APPROVED** [review]

**Comment by EvanPurkhiser** [comment]
I spent a while trying to remove the env.TZ stuff, but it was becoming really tricky 🤷‍♂️

We'll want to revisit at some point.

**Pull request merged**
