### PR TITLE
feat(workflow): Display issue short id in email alert

### LINKED ISSUE #6040: Display issue short id in email alert
I spoke with someone at RailsCamp who has started using the "Fixes SENTRY-" commit feature, but wanted a reference to the issue's short id in the email to make the workflow a bit smoother/less annoying.

### PR DESCRIPTION
**Pull request by nimishsinghal**
Fixes #6040

### CODE REVIEW

**Comment by MaxBittker** [comment]
awesome, thanks!
Only thing is that I'm not sure abound the ordering here, it should probably be the last item in the subject, after title. 
would you mind sharing screenshot of one of the emails?

**Comment by MaxBittker** [comment]
this wouldn't be enough to close #6040 (it's about having it in the email body where it's easier to copy), but it does address ted's concern and is a good standalone fix.

**Comment by nimishsinghal** [comment]
@MaxBittker thanks for reviewing, addressed your comments. Please check.

**Review by tkaemming — COMMENTED** [review]
I think the Python is fine. There are test failures that need to be addressed before this can be approved, however.

I wonder if it'd make sense to change the subject since the project is now displayed twice: once as part of the prefix with `get_full_name()` and again as the callsign part of the short ID.

Deferring to @ckj for any stylistic concerns.

**Comment by nimishsinghal** [comment]
@tkaemming addressed failing test cases.

**Comment by tkaemming** [comment]
Thanks! I'm going to bump this over to @ckj for any design feedback but otherwise the implementation looks good to me.

**Comment by holman** [comment]
Oh nice; I was the drive-by culprit from RailsCamp in #6040- didn't know this had been hashed out here (thanks @nimishsinghal!) Getting it in the email body would definitely make my life a little easier, since I do the copy+paste => commit message dance pretty often. :sparkles:

**Comment by MaxBittker** [comment]
agreed this is important! it just got stuck in the state of pretty good but not pretty enough to merge 😬 possibly we could pare it down to only the subject line for now and follow up with a better template.

**Comment by nimishsinghal** [comment]
Please let me know for any suggestions to improve the template.

**Comment by MaxBittker** [comment]
just to keep things moving, rebased and removed the body changes for now, since that's the part that needs more polish and the rest is good on its own IMO. 

IMO this is good to merge, the main question is the changed behavior with inbox group, and whether this is preferable.

**Comment by MaxBittker** [comment]
>Please let me know for any suggestions to improve the template.

Sorry, I don't have specific help here besides that it's an email that a lot of people see and it needs to be designed well (aka better than I can do, so I'd need to defer to @getsentry/design)

**Comment by MaxBittker** [comment]
for future reference, this is the commit I removed and could be cherry picked for a future PR.
https://github.com/getsentry/sentry/pull/6230/commits/648f7f4d33a3bd7baaa7b2f3c5786c796e66f156

**Comment by billyvg** [comment]
Thanks @nimishsinghal (and @MaxBittker), we briefly talked about this and think that it's a bit redundant to have project name AND short id, so let's replace project_name with short id completely.

I think we also need to update the default email template so that it reflects this too (i.e. in Project Settings -> Alerts)

**Comment by nimishsinghal** [comment]
@billyvg @MaxBittker should I push a new commit with the changes @billyvg suggested above?

**Comment by billyvg** [comment]
@nimishsinghal that would be great if you could!

**Comment by lauryndbrown** [comment]
Hello! @nimishsinghal Thanks for helping out! I noticed things stalled a bit, and I was fixing #6902 unifying email subjects. I'm working on a pull request #6992 that I think should address everything you were working on here. ^.^

**Comment by holman** [comment]
Yasssss thanks so much, this is great!

**Pull request closed without merging**
