### PR TITLE
Finished State LoadingIndicator

### PR DESCRIPTION
**Pull request by HazAT**
This adds a new state `finished` to the LoadingIndicator
This PR needs to be merged before: https://github.com/getsentry/sentry/pull/6523

my movie mp4

Better framerate version
https://www.dropbox.com/s/zz4dtersx12bwxe/loading.mov?dl=0

### CODE REVIEW

**Comment by HazAT** [comment]
@getsentry/design I've added a new state to the LoadingIndicator had to do some refactoring of the CSS but I checked so it looks the same. Also added it to the storybook/styleguide.
Please review just this and tell me if it's fine.

_Moved this from this #6523 to a seperate PR_

**Comment by getsentry-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by benvinegar** [comment]
@HazAT Damn, pretty cool.

**Review by ckj — APPROVED** [review]
Really cool, @HazAT ❤️

Note for @getsentry/design: we should update this to use an icon from the new set once it lands.

**Pull request merged**
