### PR TITLE
ref(sampling): Update to the latest sampling config version

### PR DESCRIPTION
**Pull request by jan-auer**
Relay has introduced an updated version for dynamic sampling rules. This
PR changes rule generation to emit this new version.

The changes in this version are:

1. Sampling config is now explicitly versioned through a `version`
   field. The version defaults to `1` if missing, which indicates to
   Relay that a legacy config is used.
2. Rules are declared in `rules`. For backwards compatibility, `rulesV2`
   is normalized by Relay.
3. Rule conditions can now use comparison operators (`>`, `>=`, `<`,
   `<=`) on strings.

As part of this update, we're removing `dynamicSamplingRules` from the
project details endpoint response. It has been unused and can instead be
queried using internal endpoints not exposed to the public product.

Requires https://github.com/getsentry/relay/pull/2721 
See also https://github.com/getsentry/getsentry/pull/12096

### CODE REVIEW

**Review by iambriccardo — APPROVED** [review]
LGTM, we should not forget to change the logic in admin that now fetches `sampling` instead of `dynamicSampling` from the project config.

**Comment by jan-auer** [comment]
There's been unrelated changes in librelay that changed the behavior of renormalization, now breaking tests. We're looking into this.

**Review by jjbayer — APPROVED** [review]
Looks like the performance score assertions need to be updated to include `optional`. Or we update relay with a `skip_serializing_if` attribute.

**Review by Dav1dde — APPROVED** [review]

**Comment by jan-auer** [comment]
@jjbayer I left a comment in our tracking issue for this:
https://github.com/getsentry/team-ingest/issues/158#issuecomment-1845371942

**Pull request merged**
