### PR TITLE
ref(migration): Remove deprecated savedsearch columns (state only)

### PR DESCRIPTION
**Pull request by evanpurkhiser**
Step 2 / 3 to remove the deprecated columns from this table

Requires GH-40755 to be deployed first.

### CODE REVIEW

**Review by wedamija — COMMENTED** [review]
lgtm, but looks like you have a few places that still rely on this field?

**Comment by evanpurkhiser** [comment]
> lgtm, but looks like you have a few places that still rely on this field?

Where do you see it?

I assume the tests are failing here actually because this PR isn't ontop of https://github.com/getsentry/sentry/pull/40755

**Comment by wedamija** [comment]
> > lgtm, but looks like you have a few places that still rely on this field?
> 
> Where do you see it?
> 
> I assume the tests are failing here actually because this PR isn't ontop of #40755

Right, it's probably just that it's not based on that, nm

**Comment by evanpurkhiser** [comment]
I'll get that one merged so we can see this pass 👍

**Review by wedamija — APPROVED** [review]

**Pull request merged**
