### PR TITLE
Use relative url for all assets

### LINKED ISSUE #2981: Template "absolute_asset_url" ignore HTTPS protocol
I turned on HTTPS in Nginx and [Sentry](https://docs.getsentry.com/on-premise/server/installation/#enabling-ssl), but browsers (Chromium, Firefox etc) show warning:

`Mixed Content: The page at 'https://example.com/sentry/' was loaded over HTTPS, but requested an insecure favicon 'http://example.com/_static/d896d9de2e6c63ebbbede072b88b7883857ccfbc/sentry/images/icons/apple-touch-icon.png'. This content should also be served over HTTPS.`

### PR DESCRIPTION
**Pull request by adipascu**
This will make loading of all assets more consistent.
As a side effect this will fix #2981

### CODE REVIEW

**Comment by mattrobenolt** [comment]
Sorry, but this will break lots of things. There are explicit reasons why certain urls are absolute and not relative.

**Comment by adi1133** [comment]
No problem, what are the reasons for keeping absolute paths ?

**Comment by mattrobenolt** [comment]
Most of the urls you changed for example, are used in email templates, and they just won't work otherwise. The others were favicons and other images for metadata.

**Comment by adi1133** [comment]
I stand corrected about the email templates. 

If you want I can post an update that only changes the favicons inside https://github.com/getsentry/sentry/blob/master/src/sentry/templates/sentry/layout.html

(this was my original intention with this PR)

**Comment by mattrobenolt** [comment]
I'd rather not. They work fine just as they are. I'm not sure the issue here.

**Comment by adi1133** [comment]
Ok. Cheers !

**Pull request closed without merging**
