### PR TITLE
warning: sort warnings to create consistency

### PR DESCRIPTION
**Pull request by dcramer**

### CODE REVIEW

**Review by tkaemming — CHANGES_REQUESTED** [review]
Looks like these aren't stable sorted:

```
In [1]: from sentry.utils.warnings import WarningSet                                                                                                                                                                                                                                                                                                                        

In [2]: w = WarningSet()

In [3]: w.add(Warning('foo'))

In [4]: w.add(Warning('bar'))                                                                                                                                                                                                                                                                                                                                               

In [5]: w.add(Warning('baz'))                                                                                                                                                                                                                                                                                                                                               

In [6]: list(w)
Out[6]: [Warning('baz'), Warning('foo'), Warning('bar')]

In [7]: sorted(list(w))
Out[7]: [Warning('foo'), Warning('bar'), Warning('baz')]

In [8]: w = WarningSet()

In [9]: w.add(Warning('foo'))

In [10]: w.add(Warning('bar'))

In [11]: w.add(Warning('baz'))

In [12]: sorted(list(w))
Out[12]: [Warning('bar'), Warning('foo'), Warning('baz')]
```

I'd probably change this to:

```
sorted(six.itervalues(self.__warnings), key=self.__get_key)
```

**Comment by dcramer** [comment]
damn.

**Comment by tkaemming** [comment]
I guess an `OrderedDict` would work too here (but might be overkill?)

**Comment by tkaemming** [comment]
This isn't required, the actual problem that existed here was fixed with GH-5686.

**Pull request closed without merging**
