### PR TITLE
ref: Cleanup after Source Map migration to Symbolicator

### PR DESCRIPTION
**Pull request by kamilogorek**
- removed helper functions used to choose processing pipeline should based on project option/sample rate
- removed test parametrization
- deprecated options used for feature testing
- cleaned up test assertions
- remove old js processor tests, as this code is deprecated

~(I haven't run tests locally, relying solely on the CI, so treat it as a draft for now 👀 )~

TODO:
- [x] Update and merge https://github.com/getsentry/sentry/pull/53420 once this is merged

### CODE REVIEW

**Review by loewenheim — APPROVED** [review]
You love to see it

**Review by Swatinem — COMMENTED** [review]
lgtm, lets pull in @beezz as this would immediately turn on js symbolication for single tenant. I’m not sure if the infrastructure for that is already in place?
Depending on that we should hold off with turning this on directly until ST it ready for it.

**Comment by kamilogorek** [comment]
Ping @beezz

**Comment by beezz** [comment]
> Ping @beezz

Pong. The infra is not in place yet.

**Pull request merged**
