### PR TITLE
feat(dev): add optional chaining proposal

### PR DESCRIPTION
**Pull request by jeffkwoh**
Addresses: https://github.com/getsentry/sentry/pull/16418#discussion_r366053674

### CODE REVIEW

**Comment by billyvg** [comment]
I would like to start using optional chaining, but wanted to bring it up in the TSC first. Proposal here: https://www.notion.so/sentry/321690a3061f43fe85f66df25435d883?v=daa97633c42242d4acc818b140afdd7f&p=575d56a576d6462c9162ffc8e87e4d3e

**Comment by jeffkwoh** [comment]
> I would like to start using optional chaining, but wanted to bring it up in the TSC first. Proposal here: https://www.notion.so/sentry/321690a3061f43fe85f66df25435d883?v=daa97633c42242d4acc818b140afdd7f&p=575d56a576d6462c9162ffc8e87e4d3e

Noted on this, will wait till after TSC before bumping this PR again

**Comment by jeffkwoh** [comment]
Optional chaining introduction approved: https://www.notion.so/sentry/Optional-Chaining-and-Null-Coalescing-575d56a576d6462c9162ffc8e87e4d3e

Added WIP, remove lodash/get throughout codebase

**Review by billyvg — APPROVED** [review]

**Comment by billyvg** [comment]
Also note we need to do this for getsentry

**Pull request merged**
