### PR TITLE
fix[api]: Remove Email Validation on commit author

### LINKED ISSUE #20085: Sentry API 400s with "Please enter a valid email address" when commit emails contain [square brackets]
## Important Details

**How are you running Sentry?**
-> Saas (sentry.io)

## Description

For one of our projects, we are unable to upload releases to Sentry's API via `sentry-cli` due to an email validation error. Sentry is failing to let some RFC2822 compliant email addresses through.

Specifically, our team uses Dependabot to update dependencies. We also use squash commits on GitHub. This results in commits having an email address like `27856297+dependabot-preview[bot]@users.noreply.github.com`. A validation is failing on these emails.

## Steps to Reproduce

1. Create a git repo that has a commit with author.email set to `27856297+dependabot-preview[bot]@users.noreply.github.com` (in particular, the square brackets `[bot]`). Note this is a RFC2822 valid email address (and also not really in our team's control).

2. Run e.g. `SENTRY_LOG_LEVEL=debug sentry-cli releases -o $ORGANIZATION set-commits --auto $CIRCLE_SHA1`

```
[... snip (sorry, these are private repos) ...]
  DEBUG   2020-07-29 18:27:34.311394218 +00:00 response status: 400
  DEBUG   2020-07-29 18:27:34.311418182 +00:00 body: {"commits":{"author_email":["Enter a valid email address."]}}
  DEBUG   2020-07-29 18:27:34.312391739 +00:00 error: running update nagger
error: API request failed
  caused by: sentry reported an error: request failure (http status: 400)
  Object({"commits": Object({"author_email": Array([String("Enter a valid email address.")])})})
  DEBUG   2020-07-29 18:27:34.313350041 +00:00 client close; no transport to shut down  (from sentry)
```

### What you expected to happen

Sentry's API should have accepted my commits with the quirky (but not invalid!) email addresses.

### Possible Solution

Unfortunately this one isn't going to be easy - I verified it's Django's `EmailValidator` that is causing this:

```
root@77f2244ff101:/# python3
Python 3.8.5 (default, Jul 22 2020, 12:28:11)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from django.core import validators
>>> validators.validate_email('good@gmail.com')
>>> validators.validate_email('12345+user@github.com')
>>> validators.validate_email('27856297+dependabot-preview[bot]@users.noreply.github.com')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/django/core/validators.py", line 197, in __call__
    raise ValidationError(self.message, code=self.code)
django.core.exceptions.ValidationError: <exception str() failed>
>>>
```

I don't have great ideas. Getting something fixed upstream isn't going to be quick or easy. 

Perhaps `sentry-cli` could be modified to clean up these email addresses before sending them to the API? (not the best, I know). 

From our perspective - sure we could re-write our Git repo history, but this will keep happening whenever we merge these Dependabot PRs.

### PR DESCRIPTION
**Pull request by silent1mezzo**
Github's Dependabot includes brackets `[]` in the email. This is technically an invalid email (see [rfc2822](https://tools.ietf.org/html/rfc2822)) but causes an error if someone is trying to attach commits to a release.

Screen Shot 2020-08-21 at 4 16 43 PM

This fixes https://github.com/getsentry/sentry/issues/20085 and https://github.com/getsentry/sentry-cli/issues/803

### CODE REVIEW

**Review by mattrobenolt — COMMENTED** [review]
What about the actual `EmailField` that exists on the model? I'm not sure if the serializer here would allow it to pass, but then fail on email validation when writing to the database.

I'm also going to continue to throw in a +1 to removing validation rather than loosening since I'm not sure how this could be "dangerous" or abused. So maybe if you have some clarification for that.

Worst case, we get values in here which aren't email addresses. Not sure what impact that'd have that'd be considered dangerous.

**Comment by silent1mezzo** [comment]
@mattrobenolt It allows it to go through because we don't actually run `full_clean` on the model side. We let the serializer clean the data and then run `get_or_create`.

My only concern is if someone throws in some sort of xss or sql injection into the field. I'm not confident in my ability to audit how this is used across the app to ensure we don't just render it. That's why it felt safer to loosen the validation vs remove it entirely.

**Comment by silent1mezzo** [comment]
@kamilogorek thoughts on this fix? I can remove validation entirely as per @mattrobenolt's suggestion.

**Comment by kamilogorek** [comment]
I don't see any sensible reason why we'd want to validate the email in the first place. I'm +1 for removing the validation entirely from the model.

**Comment by rspechenkin** [comment]
Hey, I just want to point out another similar issue that we're facing. We're using [versioned settings in TeamCity](https://www.jetbrains.com/help/teamcity/storing-project-settings-in-version-control.html#Synchronizing+Settings+with+VCS) and some commits have the email address like **username@Teamcity** and that also breaks the email validation. So it would be nice if you could remove this validation

**Comment by lewisblackwood** [comment]
👋  @silent1mezzo is there anything that can be done to get this merged? We use Dependabot and this validation stops us uploading automating releases with the Netlify Sentry build plugin.

**Review by mattrobenolt — APPROVED** [review]

**Comment by sikhlana** [comment]
Any update on this PR?

**Comment by silent1mezzo** [comment]
@rspechenkin @lewlewisblackwood @sikhlana this has been merged and deployed. You should be good to go now with dependabot and teamcity commits.

**Comment by sikhlana** [comment]
@silent1mezzo great! Just deployed the latest master to my on-premise solution.

**Pull request merged**
