### PR TITLE
fix(relay): Handle missing projects explicitly

### PR DESCRIPTION
**Pull request by untitaker**
Fix SENTRY-E5Y

I am not sure what exact race we're actually running into here. For now let's just collect metrics.

### CODE REVIEW

**Review by jan-auer — APPROVED** [review]
Rather than a metric, how about a Sentry issue? 

It could be that project deletion somehow triggers options updates, which then lead to this task being spawned.

**Comment by untitaker** [comment]
I want to get rid of the Sentry issue as this is just noise for onprem users who look through the internal project. I tried to repro the race locally but couldn't. Going through the events in our Sentry instance there seem to be a couple different update_reasons, and by aggregating them in statsd (or yeah, also in Sentry) we can figure out what's going on.

**Comment by jan-auer** [comment]
Makes sense. My fear is that this is a legitimate bug and it's too easy to miss or forget with a metric. As long as this stays on your radar, merge on.

**Comment by untitaker** [comment]
You're right. I'm going to close this and just add some sentry tags

**Pull request closed without merging**
