### PR TITLE
(chore) Use standalone proptypes

### PR DESCRIPTION
**Pull request by MaxBittker**
in preparation for react 16

### CODE REVIEW

**Comment by getsentry-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by MaxBittker** [comment]
interesting how this broke storybook!

**Comment by billyvg** [comment]
Wonder if this is related? https://github.com/storybooks/storybook/issues/1723

**Comment by MaxBittker** [comment]
off the cuff instinct is no, gonna investigate further. 
this issue seems more accurate but is supposedly fixed in 3.1.4 and we're on 3.2.0
https://github.com/storybooks/storybook/issues/954

**Comment by MaxBittker** [comment]
https://github.com/storybooks/storybook/pull/1725

this PR got merged that fixes the issue, gonna try running storybook from master lol

**Comment by MaxBittker** [comment]
upgrading storybook to ^3.2.0 fixed this - want me to pin a specific patch? this is safe to merge now I believe.

**Review by billyvg — APPROVED** [review]

**Pull request merged**
