### PR TITLE
Protect ourselves against broken plugin urls

### PR DESCRIPTION
**Pull request by mattrobenolt**
@getsentry/infrastructure @dcramer @macqueen 

This should prevent any mishap of a plugin returning garbage or raising an exception taking everything down.

---

This change is [Reviewable](https://reviewable.io/reviews/getsentry/sentry/4070)

### CODE REVIEW

**Comment by mattrobenolt** [comment]
I'll write tests for this in morning.

**Comment by tkaemming** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/sentry/plugins/base/project_api_urls.py, line 16 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/4070#-KQhPMgsZ0QLBgnzcyKg:-KQhPMgsZ0QLBgnzcyKh:bv3u8ab) ([raw file](https://github.com/getsentry/sentry/blob/b98bfad36e8b56c22c82b353b4330e0f396728b7/src/sentry/plugins/base/project_api_urls.py#L16)):*
> ```Python
> def is_valid_urls(urls):
>     if not urls:
>         return False
> ```

Why isn't an empty sequence of URLs considered valid?

---

*[src/sentry/plugins/base/project_api_urls.py, line 20 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/4070#-KQhPT0jELVWfDRhwQ-K:-KQhPT0jELVWfDRhwQ-L:bok8jwu) ([raw file](https://github.com/getsentry/sentry/blob/b98bfad36e8b56c22c82b353b4330e0f396728b7/src/sentry/plugins/base/project_api_urls.py#L20)):*
> ```Python
>     for u in urls:
>         if not isinstance(u, (RegexURLResolver, RegexURLPattern)):
>             return False
> ```

This doesn't provide much feedback about what values specifically are invalid — this seems like it could be annoying if you have a plugin with lots of URLs (or dynamically generated ones, etc.)

---

*[src/sentry/plugins/base/project_api_urls.py, line 32 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/4070#-KQhP6-9X217IqprN-8a:-KQhP6-9X217IqprN-8b:bp2vjmd) ([raw file](https://github.com/getsentry/sentry/blob/b98bfad36e8b56c22c82b353b4330e0f396728b7/src/sentry/plugins/base/project_api_urls.py#L32)):*
> ```Python
>             _plugin_project_urls = _plugin.get_project_urls()
>             assert is_valid_urls(_plugin_project_urls)
>         except Exception:
> ```

I'm guessing this is intentionally not limited to `AssertionError` to capture any exceptions thrown by `get_project_urls`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/4070)*

**Comment by tkaemming** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/4070)*

**Comment by mattrobenolt** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/sentry/plugins/base/project_api_urls.py, line 16 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/4070#-KQhPMgsZ0QLBgnzcyKg:-KQhXDr9-pR45nxU8Gns:b7ijok5) ([raw file](https://github.com/getsentry/sentry/blob/b98bfad36e8b56c22c82b353b4330e0f396728b7/src/sentry/plugins/base/project_api_urls.py#L16)):*
<details><summary><i>Previously, tkaemming (ted kaemming) wrote…</i></summary>
> Why isn't an empty sequence of URLs considered valid?
</details>
Oh, I guess I should remove this case now that it's logging it as an exception. So it should be valid. Will change.

---

*[src/sentry/plugins/base/project_api_urls.py, line 20 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/4070#-KQhPT0jELVWfDRhwQ-K:-KQhXS5cRGNnv_nyMjZ2:bjc97pc) ([raw file](https://github.com/getsentry/sentry/blob/b98bfad36e8b56c22c82b353b4330e0f396728b7/src/sentry/plugins/base/project_api_urls.py#L20)):*
<details><summary><i>Previously, tkaemming (ted kaemming) wrote…</i></summary>
> This doesn't provide much feedback about what values specifically are invalid — this seems like it could be annoying if you have a plugin with lots of URLs (or dynamically generated ones, etc.)
</details>
You mean in the case that you passed in garbage, it's not being informative about what the issue was? I can change this to raise an exception instead with more useful information instead of returning False.

---

*[src/sentry/plugins/base/project_api_urls.py, line 32 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/4070#-KQhP6-9X217IqprN-8a:-KQhXcdLoOADlvdEFaoB:b-n9nh4g) ([raw file](https://github.com/getsentry/sentry/blob/b98bfad36e8b56c22c82b353b4330e0f396728b7/src/sentry/plugins/base/project_api_urls.py#L32)):*
<details><summary><i>Previously, tkaemming (ted kaemming) wrote…</i></summary>
> I'm guessing this is intentionally not limited to `AssertionError` to capture any exceptions thrown by `get_project_urls`?
</details>
Yes. We need to swallow up everything here and continue up or it will break the entire application.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/4070)*

**Comment by tkaemming** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/sentry/plugins/base/project_api_urls.py, line 20 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/4070#-KQhPT0jELVWfDRhwQ-K:-KQh_DQOad0drgQD81xB:bm2i2vg) ([raw file](https://github.com/getsentry/sentry/blob/b98bfad36e8b56c22c82b353b4330e0f396728b7/src/sentry/plugins/base/project_api_urls.py#L20)):*
<details><summary><i>Previously, mattrobenolt (Matt Robenolt) wrote…</i></summary>
> You mean in the case that you passed in garbage, it's not being informative about what the issue was? I can change this to raise an exception instead with more useful information instead of returning False.
</details>
Yeah, or if only a subset of the URLs in the sequence are actually incorrect.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/4070)*

**Comment by mattrobenolt** [comment]
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---

*[src/sentry/plugins/base/project_api_urls.py, line 20 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/4070#-KQhPT0jELVWfDRhwQ-K:-KR0g4XPAfz6rSn8bMYI:b9u1me7) ([raw file](https://github.com/getsentry/sentry/blob/b98bfad36e8b56c22c82b353b4330e0f396728b7/src/sentry/plugins/base/project_api_urls.py#L20)):*
<details><summary><i>Previously, tkaemming (ted kaemming) wrote…</i></summary>
> Yeah, or if only a subset of the URLs in the sequence are actually incorrect.
</details>
Changed to raise an exception with more useful information.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/4070)*

**Comment by tkaemming** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/sentry/plugins/base/test.py, line 28 \[r2\]](https://reviewable.io:443/reviews/getsentry/sentry/4070#-KR0i8BBV5UIMGBKL8Hq:-KR0i8BCZjpNdtLDUmDG:bkgzhnl) ([raw file](https://github.com/getsentry/sentry/blob/6f041813f4d5a55a506e6ca9d2b507854b18dae0/tests/sentry/plugins/base/test.py#L28)):*
> ```Python
>     class BadPluginC(object):
>         def get_project_urls(self):
>             return None
> ```

`BadPluginA` and `BadPluginC` are not necessarily "bad" any more since they don't cause any errors.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/4070)*

**Comment by mattrobenolt** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[tests/sentry/plugins/base/test.py, line 28 \[r2\]](https://reviewable.io:443/reviews/getsentry/sentry/4070#-KR0i8BBV5UIMGBKL8Hq:-KR0jHBpnzhEJEbgo6iu:b968mj6) ([raw file](https://github.com/getsentry/sentry/blob/6f041813f4d5a55a506e6ca9d2b507854b18dae0/tests/sentry/plugins/base/test.py#L28)):*
<details><summary><i>Previously, tkaemming (ted kaemming) wrote…</i></summary>
> `BadPluginA` and `BadPluginC` are not necessarily "bad" any more since they don't cause any errors.
</details>
PluginA is bad since it raises an AssertionError, but C isn't "bad". It just adds no urls. :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/4070)*

**Pull request merged**
