### PR TITLE
fix(stream): Don't re-fetch data on project star

### LINKED ISSUE #7238: starring/unstarring a project results in stream view re-fetching data

### PR DESCRIPTION
**Pull request by MaxBittker**
fixes https://github.com/getsentry/sentry/issues/7238

### CODE REVIEW

**Review by benvinegar — COMMENTED** [review]
Could you help explain why removing this changes the behavior?

Are we sure this doesn't impact streaming (polling) in any way?

**Comment by MaxBittker** [comment]
https://github.com/getsentry/sentry/commit/0c98030d17a07f17ccf81f35457b089df8681389#diff-6c99060bedfae86add32892f76673815R131

this line was actually was added in a recent PR*, 
It's not safe to merge this without a better explanation/mental model of the ramifications.

I'm going to look into it later but putting this down for now

https://github.com/getsentry/sentry/commit/0c98030d17a07f17ccf81f35457b089df8681389#diff-6c99060bedfae86add32892f76673815R131

**Review by lynnagara — APPROVED** [review]
This makes sense to me, problem was since we set `this.lastRequest` to `null` it was always fetching

**Comment by lynnagara** [comment]
Also needed another fix for those with the environments flag

**Comment by MaxBittker** [comment]
lyn, do you remember what this line was added for? I don't want to remove a case that should fetch and make it now

**Comment by MaxBittker** [comment]
but I do want to merge this, because I believe it causes extra spinners on load even when the button isn't clicked

**Comment by lynnagara** [comment]
There was some condition (possibly on initial load) that wasn't fetching which I don't quite recall sorry :( But I've tested it a bit, and don't think that's an issue. I think this is a good fix, and we should merge it

**Comment by MaxBittker** [comment]
merging this because i tried it more locally and it's pretty bad in prod right now (the stream view will spin, render, spin, then render on a fresh load)

**Pull request merged**
