### PR TITLE
feat(gdpr): Change beacon statistics to use a radio boolean

### PR DESCRIPTION
**Pull request by dcramer**

### CODE REVIEW

**Comment by dcramer** [comment]
screen shot 2018-04-02 at 11 27 08 am

This doesnt handle the 'required' attribute yet, but realistically none of our fields handle it in a great way (most rely on the native browser component).

**Comment by dcramer** [comment]
(realized i didnt reload the page, but the text isnt 100% whats in the screenshot)

**Comment by dcramer** [comment]
Aside, the backend can at least enforce "you must pass true or false" for these boolean fields. I still dont know how we'd easily do it from a per-field level, since the <Form> itself doesnt control the <Field> components, and they dont share state in a reasonable way that <Form> knows about the field being required.

**Review by billyvg — APPROVED** [review]

**Comment by billyvg** [comment]
Once settings goes GA, we'll consolidate form fields (which in new settings has better support for required fields)

**Pull request merged**
