### PR TITLE
ref: Clean up categories to match docs

### PR DESCRIPTION
**Pull request by dcramer**
- electron -> javascript.electron
- cordova -> javascript.cordova
- csharp -> dotnet
- java.android -> android
- cocoa -> apple
- native.*

Some of these are transitional and will need removed when docs gets synchronized.

### CODE REVIEW

**Comment by dcramer** [comment]
Once the platform names are fully uniform (I think this might be the last major PR needed) I want to figure out how we can sync wizard + platforms (in docs) and then export the categoryList from docs itself.

**Review by billyvg — APPROVED** [review]
Tests are still failing but this looks fine.

Can you point me to where in docs these are synced from?

**Comment by dcramer** [comment]
Will fix tests - synced from https://docs.sentry.io/_platforms/_index.json

**Comment by dcramer** [comment]
y are these tests randomly failing

**Comment by bruno-garcia** [comment]
Yes! Please and thank you.

**Pull request merged**
