### PR TITLE
cleanup(replays): Flatten event iterator

### PR DESCRIPTION
**Pull request by cmanallen**
- Flattens the event iterator and moves unique processors to different functions.
- Removes unnecessary conditional evaluations.

### CODE REVIEW

**Review by JoshFerge — COMMENTED** [review]
could we keep the logging for click indexing in? could prove to be useful in near-future projects

**Comment by cmanallen** [comment]
@JoshFerge Yeah we can.  I removed it because I thought we weren't using it any more.

**Comment by cmanallen** [comment]
@JoshFerge Added click logging.

**Review by JoshFerge — APPROVED** [review]
is the title of the PR still accurate? is anything removed now? but looks good

**Pull request closed without merging**
