### PR TITLE
Don't render expand/collapse toggle when nothing to show

### LINKED ISSUE #2144: Handle case of single line of context
We shouldn't show expand/collapse if there's nothing to be done

### PR DESCRIPTION
**Pull request by mattrobenolt**
Fixes GH-2144

/cc @benvinegar Is this sensible?

### CODE REVIEW

**Comment by benvinegar** [comment]
I wouldn't have a `renderX` function return anything other than a React element. Not a big fan of having it render a tuple here, which is a departure from like 200+ `renderX` methods in our codebase.

Instead I'd make `hasContextSource`, `expandable`, etc prototype methods that you could query in both places.

**Comment by mattrobenolt** [comment]
You got it boss.

**Comment by mattrobenolt** [comment]
@benvinegar updated.

**Comment by mattrobenolt** [comment]
@benvinegar mind taking a peek at this again today plz?

**Comment by benvinegar** [comment]
🐳

**Pull request merged**
