### PR TITLE
fix(slack): Use team hash on status response

### PR DESCRIPTION
**Pull request by dcramer**

### CODE REVIEW

**Comment by dcramer** [comment]
Missed this one the first time around.

**Comment by dcramer** [comment]
Feels more confusing to me when we show #team everywhere in sentry except Slack

**Review by markstory — COMMENTED** [review]
Will slack convert the sentry team into a channel link if there is an overlapping team/channel name?

**Comment by EvanPurkhiser** [comment]
> Will slack convert the sentry team into a channel link if there is an overlapping team/channel name?

I'm not sure, I'd have to check.

**Comment by dcramer** [comment]
Can we just agree that we shouldn't be prioritizing how Slack treats things, and prioritize Sentry's experience for these? We always should be using #team in context of Sentry because with it out its not obvious what it means. It could just be a username.

**Review by evanpurkhiser — APPROVED** [review]

**Pull request merged**
