### PR TITLE
ref: Use docker for spotlight instead of webpack

### PR DESCRIPTION
**Pull request by HazAT**
Changing Spotlight to use Docker instead of Webpack

The motivation for this change:
Using webpack to spin off a child process caused issues in getsentry

`rm -f .webpack.meta && pytest tests --collect-only -qq`
```
$ pstree -w -p 82761
-+= 00001 root /sbin/launchd
 \-+= 00654 asottile /System/Applications/Utilities/Terminal.app/Contents/MacOS/Terminal
   \-+= 46942 root login -pf asottile
     \-+= 46943 asottile -bash
       \-+= 82761 asottile /Users/asottile/workspace/getsentry/.venv/bin/python /Users/asottile/workspace/getsentry/.venv/bin/pytest tests --collect-only -qq
         \-+- 82766 asottile yarn build-acceptance
           \-+- 82767 asottile node /Users/asottile/.volta/tools/image/yarn/1.22.5/bin/yarn.js build-acceptance
             \-+- 82778 asottile /Users/asottile/.volta/tools/image/node/20.11.0/bin/node /Users/asottile/.volta/tools/image/yarn/1.22.5/bin/yarn.js build
               \-+- 82779 asottile /Users/asottile/.volta/tools/image/node/20.11.0/bin/node /Users/asottile/.volta/tools/image/yarn/1.22.5/bin/yarn.js webpack
                 \-+- 82780 asottile webpack 
                   \-+- 82783 asottile /Users/asottile/.volta/tools/image/node/20.11.0/bin/node /Users/asottile/.volta/tools/image/yarn/1.22.5/bin/yarn.js run spotlight-sidecar
                     \--- 82784 asottile /Users/asottile/.volta/tools/image/node/20.11.0/bin/node /Users/asottile/workspace/getsentry/node_modules/.bin/spotlight-sidecar
```

so we are making it that people need to enable the sidecar locally and use our docker image instead.

Requires https://github.com/getsentry/getsentry/pull/12865

### CODE REVIEW

**Review by scttcper — APPROVED** [review]
looks good, should we remove the `spotlight-sidecar` package as well?

**Review by anonrig — APPROVED** [review]

**Comment by HazAT** [comment]
@scttcper where do you see a sidecar dep? this is child dep of Spotlight itself but we don't use it

Also, upgraded spotlight now 😬

**Review by anonrig — APPROVED** [review]

**Comment by scttcper** [comment]
i meant the `@spotlightjs/spotlight` package

**Comment by scttcper** [comment]
ignore me

**Review by anonrig — APPROVED** [review]

**Pull request merged**
