### PR TITLE
feat(devserver): Add option to run HTTP server in same process

### PR DESCRIPTION
**Pull request by RyanSkonnord**
Add a `--debug-server` option to the devserver command, replacing the
`--skip-daemons` option. If set, it forces the WSGI option and causes
the HTTP server to be run in a parallel thread of the devserver's
process, rather than as a daemon in its own process.

The motive is to keep an IDE debugger to attached to the HTTP server,
which can't be done as easily if it is in a new process that the IDE
doesn't know about. This replaces the solution that used the
`--skip-daemons` option, which regressed as of b97365ec.

This takes advantage of the `debug` parameter on
`SentryHTTPServer.__init__`, which previously was unused and ignored. It
is used in SentryHTTPServer to override the environmental UWSGI
settings, because the UWSGI server command is always executed at the OS
level, which also prevents a debugger from attaching.

### CODE REVIEW

**Review by untitaker — APPROVED** [review]
can we merge this option with `SENTRY_USE_UWSGI` setting?

**Comment by RyanSkonnord** [comment]
> can we merge this option with `SENTRY_USE_UWSGI` setting?

I don't know. That depends on whether we care about being able to having a non-UWSGI server executed via
```python
manager.add_process(`server`, `sentry run web`)
```
as opposed to
```python
threading.Thread(target=server.run).start()
```

Does that make a difference for anyone's workflow or environment?

(Anyone who really cared about doing `sentry run web` could just execute that command, but not without the `devserver` command attempting to do the same thing if you need to run it concurrently, which is the trouble that brought me to the `--skip-daemons` solution in the first place.)

**Comment by untitaker** [comment]
I only know of you and @RaduW using any of this. I think it would be good to minimize the amount of options exposed.

**Comment by jusigler** [comment]
@untitaker I use this too!

**Comment by RyanSkonnord** [comment]
Sorry for the lag; I've just gotten back from vacation.

@untitaker Since you've approved, I'll go ahead and get this merged. If you'd like to follow up with me about merging with the `SENTRY_USE_UWSGI` setting, I'd be happy to iterate on that again but could use some more detail. For now, I don't want to change the daemon behavior and surprise anyone who relies on the `SENTRY_USE_UWSGI` setting for other reasons.

**Pull request merged**
