### PR TITLE
fix(issue-detectors): Filter out None values from tags

### PR DESCRIPTION
**Pull request by narsaynorath**
Filters out None values from the tags array so we don't attempt to index None.

Fixes SENTRY-FOR-SENTRY-RZM

### CODE REVIEW

**Review by mjq-sentry — APPROVED** [review]
🚢

**Comment by lynnagara** [comment]
Can this be fixed at the source? A tag value of `None` seems like it's completely invalid to me

**Comment by narsaynorath** [comment]
@lynnagara For sure, this was just spotted and we decided to do a quick patch, but we recognize we'll have to find out why we're getting `None` values here as well. Thanks for calling that out!

**Comment by mjq-sentry** [comment]
@lynnagara For sure - that's next on the list! We wanted to stop the error from happening while we do that investigation though.

**Comment by mjq-sentry** [comment]
For future debugging - the four projects sending us `None` in `tags` are all using the `sentry.php` SDK, versions `3.3.7`, `3.14.0`, and `3.16.0`.

**Pull request merged**
