### PR TITLE
feat(growth) : Adds React Native events to Demo Mode 

### PR DESCRIPTION
**Pull request by roggenkemper**
This PR adds 2 React Native events to Demo Mode. Previously, there was a React Native organization created but it was not populated with events. 
Screen Shot 2021-06-22 at 10 43 50 AM

### CODE REVIEW

**Review by scefali — COMMENTED** [review]
Screen Shot 2021-06-22 at 1 25 11 PM

@roggenkemper can you update the URLs from localhost to `https://app.example.com`?

**Comment by scefali** [comment]
Screen Shot 2021-06-22 at 1 27 22 PM

@roggenkemper can you also fix the start time? This is the unhandled promise rejection.

**Comment by roggenkemper** [comment]
> Screen Shot 2021-06-22 at 1 27 22 PM
> 
> @roggenkemper can you also fix the start time? I think both events need this fixed.

yup! removed for both

**Comment by roggenkemper** [comment]
> Screen Shot 2021-06-22 at 1 25 11 PM
> 
> @roggenkemper can you update the URLs from localhost to `https://app.example.com`?

changed!

**Review by scefali — APPROVED** [review]

**Pull request merged**
