### PR TITLE
py3(drf): bump djangorestframework to 3.1.x

### PR DESCRIPTION
**Pull request by joshuarli**
Going to 3.1.3, the last in the 3.1.x series of DRF releases.

### CODE REVIEW

**Comment by joshuarli** [comment]
Looks like the only work that needed to be done was going to 3.1.0, the rest of 3.1.x were free.

**Review by wedamija — COMMENTED** [review]
I did an audit of the uses of `serializers.CharField`, most seem fine. I'm a little concerned with:
- `UserPasswordSerializer` in sentry/api/endpoints/user_password.py, since I'm not sure if whitespace characters are potentially valid here. Might be worth just disabling trimming here as well.
- `TotpRestSerializer` and the other serializers in sentry/api/endpoints/user_authenticator_enroll.py.
- `AuthVerifyValidator` in sentry/api/validators/auth.py

**Comment by joshuarli** [comment]
It definitely makes sense to trim whitespace by default, especially on those serializers. I'll just add a few test cases to define the behavior.

**Review by wedamija — APPROVED** [review]
lgtm, merge this at the same time as the  bump in sentry-plugins and getsentry

**Pull request merged**
