### PR TITLE
Remove unnecessary files

### PR DESCRIPTION
**Pull request by ibigbug**

### CODE REVIEW

**Comment by ibigbug** [comment]
Since we are using this for now ? https://github.com/getsentry/docker-sentry/tree/master/git

**Comment by mattrobenolt** [comment]
I haven't taken the time to look at this yet. But I be,I eve these have all been replaced by something else. Not just `docker-sentry`.

**Comment by ibigbug** [comment]
OK. Looking forward to the new packaging procesure :)

**Comment by EvanPurkhiser** [comment]
@mattrobenolt can this be merged?

**Review by mattrobenolt — APPROVED** [review]
🎉

**Pull request merged**
