### PR TITLE
feat: Add options to use Kafka for preprocess/process/event_save tasks

### PR DESCRIPTION
**Pull request by bretthoerner**
Try number 2 of #12159. There were `AttributeError`s causing SENTRY-9TF.

### CODE REVIEW

**Comment by bretthoerner** [comment]
@tkaemming Any opinions on how to test `run_post_process_forwarder`?

**Comment by bretthoerner** [comment]
Like I could split out the "create consumer" code and add a small unit for that, but it's not actually trying the bootstrap server or subscribing to the topic I'm looking up. I suppose we could add "setup Kafka in Travis" as a dependency of this PR. Love 🐍

**Comment by alex-hofsteede** [comment]
@bretthoerner is there a simple smoke test that we can put together (maybe mocks producing/consuming from kafka?) I guess we don't have to test everything, but just making sure that the post processor can start is probably a good safeguard

**Comment by bretthoerner** [comment]
@alex-hofsteede OK I just tried for like an hour but I think the only way to test this code is with a working Kafka broker, a producer, etc. I mocked the Kafka Consumer but then I have to deal with producing working messages from `poll` (which will poll as fast as possible) and the shutdown logics of 2 consumers on 2 threads and all kinds of other things. So yeah, I think testing the `post_process_forwarder` is blocked on a much more prod-like test environment.

In my attempts I at least verified that the `AttributeError` is gone.

**Review by alex-hofsteede — APPROVED** [review]
OK yeah, as discussed elsewhere, we do need end-to-end tests that make sure that a message gets all the way through our pipes in a test env, but doing that inside this PR is probably overkill.

:shipit:

**Pull request merged**
