### PR TITLE
fix(sentry-apps) Add an option to control the webhook timeout at runtime

### PR DESCRIPTION
**Pull request by fpacifici**
This PR registers an option to control the webhook timeout at runtime.

### CODE REVIEW

**Review by scefali — APPROVED** [review]

**Review by wedamija — APPROVED** [review]

**Review by scefali — COMMENTED** [review]
@fpacificiwe so I guess we need a second PR to use the setting?

**Comment by fpacifici** [comment]
@scefali https://github.com/getsentry/sentry/pull/53947

**Comment by scefali** [comment]
@fpacifici you linked to this PR lol

**Comment by fpacifici** [comment]
https://github.com/getsentry/sentry/pull/53948

**Pull request merged**
