### PR TITLE
fix(api): Correct handling of transaction name as culprit

### PR DESCRIPTION
**Pull request by dcramer**

### CODE REVIEW

**Comment by mitsuhiko** [comment]
We didn't get to updating the SDKs yet. We can merge it anyways but probably this means that transactions are not there for a while.

**Comment by mitsuhiko** [comment]
We're going to merge this soon now that the SDKs have the correct beahvior in. Setting a merge target for two weeks from now.

**Comment by untitaker** [comment]
@mitsuhiko that EOS bot permanently notifies me about this. Is there anything blocking this apart from CI?

**Comment by untitaker** [comment]
No clue what's going on in CI

**Comment by mitsuhiko** [comment]
@untitaker in the twisted way that is our entanglement docs broke sentry: https://github.com/getsentry/sentry-docs/pull/306

**Review by mitsuhiko — APPROVED** [review]

**Pull request merged**
