### PR TITLE
Reverse the order of logging handlers.

### PR DESCRIPTION
**Pull request by JTCunning**
Attempt to blindly fix SENTRY-117.

@mattrobenolt / @getsentry/platform

### CODE REVIEW

**Comment by mattrobenolt** [comment]
Can't we validate this behavior locally?

**Comment by JTCunning** [comment]
I was unable to validate the behavior over the past few days :(

**Comment by mattrobenolt** [comment]
I'm going to try and reproduce this tonight. I'd rather try and see it happen locally before just blindly shipping things and hoping they work. Because these don't happen that often anyways.

**Comment by mattrobenolt** [comment]
This is superseded by #4433

**Pull request closed without merging**
