### PR TITLE
feat(graphql): Add has_graphql_request analytics property to issue/event

### LINKED ISSUE #50231: Analytics to track the adoption of the GraphQL errors
### Problem Statement

After working on https://github.com/getsentry/sentry/issues/50230 we'd like to understand if this feature is actually being used and makes sense.

### Solution Brainstorm

Can we actually measure if this is signal vs noise? for example, analytics about if people are ignoring/silencing GraphQL client errors, etc.
Let's pair up on that to check what makes more sense to be tracked.

### Product Area

Issues

### PR DESCRIPTION
**Pull request by malwilley**
Closes https://github.com/getsentry/sentry/issues/50231

### CODE REVIEW

**Comment by marandaneto** [comment]
@malwilley is that tracking the number of viewed events with the graphql request in it?
So the analytics would be e.g. 10 out of 1000 events were graphql events?
This is a good step, but I'd like to go beyond that.

> Can we actually measure if this is signal vs noise? for example, analytics about if people are ignoring/silencing GraphQL client errors, etc.

So my goal would be to understand if this type of event is actually useful and not really only if they are opening it.
For example, I'd like to analyse something like that:

I've got 1000 graphql events, 900 of them were "resolved", 50 were archived, 50 were deleted, etc.
This probably has to be tracked on the Issues page and Issues details page.

@kahest or @scefali do you have more ideas?

**Comment by kahest** [comment]
> ...
> So my goal would be to understand if this type of event is actually useful and not really only if they are opening it. For example, I'd like to analyse something like that:
> 
> I've got 1000 graphql events, 900 of them were "resolved", 50 were archived, 50 were deleted, etc. This probably has to be tracked on the Issues page and Issues details page.
> 
> @kahest or @scefali do you have more ideas?

IMO that's great to start with. If we have similar analyses happening for other features (or issues in general), we can look into adapting them to just look at GraphQL events.

**Comment by malwilley** [comment]
@marandaneto @kahest With this added you will be able to track which graphql errors are being resolved, ignored, etc since this property will be attached to those events as well. We are doing similar analyses with the exception groups project. The one major disadvantage is that this only works for issues users are viewing and acting on from the issue details page. But AFAIK this is the best way we have of tracking this kind of event-level info since other places the user might be resolving/ignoring from won't have the event details to check if it's a graphql event or not.

LMK if I'm missing anything @scefali

**Review by scefali — APPROVED** [review]

**Comment by scefali** [comment]
It's easy enough to construct a funnel starting at viewing a graphql issue and resolving it. This analytics should be sufficient for that analysis.

**Comment by marandaneto** [comment]
Alright, thank you @malwilley and @scefali

**Pull request merged**
