### PR TITLE
Make some updates to `labels.yml`

### PR DESCRIPTION
**Pull request by chadwhitacre**
- Delete `Team: *` labels (we're [using `Product Area: *`](https://github.com/getsentry/team-ospo/issues/146) now)
- Add `www.` to Notion links so macOS cmd-click in Terminal works
- Delete `dependencies` ref: #51750
- Add `Platform: React Native` ¯\\\_(ツ)\_/¯
- Add `Trigger: Silo db` (from https://github.com/getsentry/sentry/pull/51774)

### CODE REVIEW

**Review by hubertdeng123 — APPROVED** [review]
so team labels are already deleted? this deletes them from labels.yml

**Comment by chadwhitacre** [comment]
> so team labels are already deleted? this deletes them from labels.yml

Yes! I deleted them manually as I went through the process of migrating the data to [this project board](https://github.com/orgs/getsentry/projects/108).

It looks like we've had some other labels sneak in in the meantime, so I'm going to go through those before merging.

**Comment by chadwhitacre** [comment]
I've manually created the `Trigger: Silo db` label and am bringing #51774 into this in order to unblock the Hybrid Cloud crew.

**Comment by chadwhitacre** [comment]
I manually deleted the `Product Area: SDKs - Native` label, which was added for [this issue](https://github.com/getsentry/sentry/issues/50518) (see comments inline). I'll follow separately to discuss how best to handle that case.

**Comment by chadwhitacre** [comment]
Also we are using `Platform: React-Native` (with a dash) in other repos. I'm working with the relevant folks to standardize on `Platform: React Native`.

**Pull request merged**
