### PR TITLE
fix(bdist): Docs not built in fresh bdist_wheel

### PR DESCRIPTION
**Pull request by atcase**
When building a fresh docker image with getsentry/docker-sentry, the integration-docs aren't copied over. This results in behaviour identical to #2664 'Docs not built' errors.

The docs and assets need to be built prior to the build command, so that they are copied over from src/ -> build/ in the subsequent build command.

### CODE REVIEW

**Comment by ibm5155** [comment]
This change sure was needed for me to perform many actions on sentry that were with errors.

**Review by BYK — APPROVED** [review]
~Definitely seems to be working. Can you explain why it works tho? :D~

Ignore my comment above, just read the final part of your message :D

Also, do we have any other places we need to fix this as I see `SentryDevelopCommand` following the same pattern/order?

**Comment by mattrobenolt** [comment]
This needs to be reverted for now and figure out what the issue is, but this definitely breaks an install that does:

```
$ pip install -e git+https://github.com/getsentry/sentry.git@{sha}#egg=sentry
```

We use this internally for some stuff, and it took a while to figure out why this broke.

The issue primarily is that now static assets that get compiled are not moved into the right folder and no static assets are able to be served. I didn't look into docs or anything like that.

**Comment by BYK** [comment]
>The issue primarily is that now static assets that get compiled are not moved into the right folder and no static assets are able to be served. I didn't look into docs or anything like that.

This was supposed to fix this exact problem. I think for some reason `sdist` and `develop` flows need different ordering :(

**Pull request merged**
