### PR TITLE
ref: Use SnubaEvent instead of Event in project_group_index

### PR DESCRIPTION
**Pull request by lynnagara**
Fixes flaky test_project_group_index tests

### CODE REVIEW

**Comment by fpacifici** [comment]
Context? Which is the flaky test ?

**Comment by lynnagara** [comment]
The 2 tests that are changed in this PR `test_lookup_by_event_id` and `test_lookup_by_event_with_matching_environment` seem pretty flaky starting today. The weird thing is I am not sure what would have changed in the last few hours since this seems to have started this morning that would affect this, but using SnubaEvent consistently everywhere will help.

**Comment by fpacifici** [comment]
Are they still flaky and what is the error message when they fail ?
If the issue was with loading partially from Snuba and partially from postgres, the tests would either always fail or always succeed, or would have to be fixed anyway because the snuba dataset may not be cleaned up properly.

**Comment by lynnagara** [comment]
Tests seem fine now, I don't recall the message anymore. I'm going to refactor these tests to use Snuba properly then.

**Review by markstory — APPROVED** [review]
Seems like a good incremental improvement removing a few uses of `create_event()`

**Pull request merged**
