### PR TITLE
feat(proj-config): Add task timeouts [INGEST-1365 INGEST-1324]

### PR DESCRIPTION
**Pull request by iker-barriocanal**
Add a 25m task timeout. There isn't a strong reasoning behind using that
number and it may be too high, but it should be high enough to not kill
tasks. We will monitor how long tasks take and adjust the number
accordingly.

I'm giving 5m more to the hard limit (`time_limit`) in case there are
exceptions to collect.

### CODE REVIEW

**Review by untitaker — APPROVED** [review]

**Review by jjbayer — APPROVED** [review]

**Review by flub — APPROVED** [review]

**Comment by flub** [comment]
Is this really this simple to add timeouts?  The task does a hugely different amount of work depending on how it is invoked: it can be invoked for a single public key or it can be invoked for an entire organisation with thousands of projects.

**Comment by flub** [comment]
How do we feel about this 2s grace time btw?  If for some reason we don't manage to run the finalisers we're not generating the configs for the next hour (that's the proposed TTL of the debounce keys)

**Comment by iker-barriocanal** [comment]
I think 2s should be long enough considering it only needs to delete a key from redis. How long do you think the grace period should be?

**Comment by flub** [comment]
So this task is only called still for the single project case, thus these timeouts should be just fine.

**Pull request merged**
