### PR TITLE
feat(ingest): Add metrics for `save_transaction_events`

### PR DESCRIPTION
**Pull request by 0Calories**
Looking for the best opportunities to improve the performance of `save_transaction_events`, add some metrics so we can see which parts of the task take the longest

### CODE REVIEW

**Review by JoshFerge — COMMENTED** [review]
why not use the sentry perf product? seems like these functions are already instrumented with tracing

**Review by JoshFerge — COMMENTED** [review]
matter of taste, but i prefer the `@metrics.wraps` decorator to having to use context managers everywhere

**Comment by lynnagara** [comment]
> why not use the sentry perf product? seems like these functions are already instrumented with tracing

sentry perf product is too heavily sampled and looking at traces does not tell us the average time we are spending on each function as a % of the total work the consumer is doing. fundamentally we need a metric not a trace.

**Comment by JoshFerge** [comment]
https://sentry.sentry.io/performance/summary/?project=1&query=&referrer=performance-transaction-summary&statsPeriod=24h&transaction=sentry.tasks.store.save_event_transaction&unselectedSeries=p100%28%29&unselectedSeries=avg%28%29

**Comment by JoshFerge** [comment]
we also already have profiling set up for this, is this not enough? https://sentry.sentry.io/performance/summary/profiles/?project=1&query=&statsPeriod=24h&transaction=sentry.tasks.store.save_event_transaction

**Review by lynnagara — APPROVED** [review]

**Comment by JoshFerge** [comment]
@lynnagara we have 2.7 million samples in the last day for this transaction. is that really not enough samples? https://sentry.sentry.io/discover/results/?dataset=transactions&field=count%28%29&name=sentry.tasks.store.save_event_transaction&project=1&query=event.type%3Atransaction%20transaction%3Asentry.tasks.store.save_event_transaction&queryDataset=transaction-like&sort=-count%28%29&statsPeriod=24h&yAxis=count%28%29

**Comment by lynnagara** [comment]
@JoshFerge fundamentally the primitive that we need is a metric not a profile or a trace, and sentry does not offer that. Now we can try and infer this by collecting and analysing heavily sampled profiles and traces which we have been doing for the last 2 weeks, but that is very roundabout way of answering the question we care about- how much time is each function taking relative to the others

**Comment by JoshFerge** [comment]
and @lynnagara in terms of average time per span, isn't this what you need exactly already? https://sentry.sentry.io/performance/summary/spans/?project=1&query=&statsPeriod=24h&transaction=sentry.tasks.store.save_event_transaction

i understand custom metrics are cheap, but why not try and use the telemetry we have already instead of adding more?

**Comment by 0Calories** [comment]
@JoshFerge on the topic of using `@metrics.wraps`, I agree that's cleaner but I saw some of these functions are called within `save_generic_events` but I want to isolate these metrics specifically for `save_transaction_events`

**Comment by lynnagara** [comment]
> and @lynnagara in terms of average time per span, isn't this what you need exactly already? https://sentry.sentry.io/performance/summary/spans/?project=1&query=&statsPeriod=24h&transaction=sentry.tasks.store.save_event_transaction
> 
> i understand custom metrics are cheap, but why not try and use the telemetry we have already instead of adding more?

the thought was to use the primitive that answers our question in the most straightforward way rather than bending over backward to use a product that is ours but isn't the right tool for the job

**Review by mjq — APPROVED** [review]

**Comment by JoshFerge** [comment]
> > and @lynnagara in terms of average time per span, isn't this what you need exactly already? https://sentry.sentry.io/performance/summary/spans/?project=1&query=&statsPeriod=24h&transaction=sentry.tasks.store.save_event_transaction
> > i understand custom metrics are cheap, but why not try and use the telemetry we have already instead of adding more?
> 
> the thought was to use the primitive that answers our question in the most straightforward way rather than bending over backward to use a product that is ours but isn't the right tool for the job

got it. i would encourage the team to take a look at the traces and profiles, as there's some useful data in there as well.

**Review by JoshFerge — APPROVED** [review]

**Comment by mjq** [comment]
@JoshFerge Thanks! FWIW we've been looking at the traces and profiles for a week+ (and adding more spans to to make the traces more meaningful) before deciding we needed this extra info.

**Comment by 0Calories** [comment]
@JoshFerge these are fair questions to be asking, but I've been using traces and profiles to look into this as well as in `ingest_consumer.process_event`, and struggling to find the answers we need. Our setup that determines where events come from (SaaS, S4S, ST), individual sampling rates on each region, and configuration has caused a lot of confusion or headaches.

I just want to see avg duration of each of these functions to get a clear picture of the best part of this task to improve first, and our existing instrumentation wasn't helping me there unfortunately.

Was checking out the profile summary page earlier too and noticed the sample rate is just too low: https://sentry.sentry.io/profiling/summary/sentry/?colorCoding=by%20system%20vs%20application%20frame&project=1&sorting=call%20order&statsPeriod=1h&tid=134175301000064&transaction=sentry.tasks.store.save_event_transaction&view=top%20down

**Pull request merged**
