### PR TITLE
tasks: split events queue into preprocess_event and save_event queues

### PR DESCRIPTION
**Pull request by mattrobenolt**
This will allow us to allocate workers dedicated for saves vs
preprocessing. Right now, tasks flow into and out of the same queue for
these two phases. This results in confusion when consuming a backlog
becasue as the rate of consuming increases, the rate on "events" also
increases, making it hard to diagnose the actual health of catching up
on a backlog without visibility into seeing how many jobs are in each
phase.

Also, for most events, non-{js,dsym}, preprocess_event is considerably
faster compared to save_event. This has an effect on our end-to-end
latency when we're near or at capacity since save_events aren't
otherwise taking priority to preprocess_events. This change will allow
us to allocate priorities and monitor more effectively the situation at
hand.

Lastly, there's a compatibility shim in place for end-users that may be
doing `run worker -Q events` that will fan out and actually subscribe to
all 3 (for now, will remove old 'events' in a follow up) to maintain
current and expected behavior. Likely htis only affects us and helps
during our transition.

@getsentry/platform

### CODE REVIEW

**Comment by mattrobenolt** [comment]
To add, I've also manually tested, since we don't really have an end-to-end test that would confirm this behavior still works since we're really only changing semantics at the queue server level.

**Comment by JTCunning** [comment]
This is a @bitprophet nitpick (Hi Jeff!), but the statement of `event.preprocess` already assumes that you are preprocessing events, therefore you should remove the `_event` bits from the name.

**Comment by mattrobenolt** [comment]
> the statement of event.preprocess already assumes that you are preprocessing events, therefore you should remove the _event bits from the name.

That's fair. tbh I literally didn't consider naming. I just took the name of the task and used that as a queue name. Previously, I've done where every single task had it's own queue by name, and we just named queues to match. I don't have a strong opinion either way. The way I have it seems to be more intuitive, albeit less "correct" since it's a bit redundant. To me, this leaves no ambiguity to what the queue is actually doing since it maps up directly to the task name.

**Review by JTCunning — APPROVED** [review]
Just like Burger King, you can have it your way. <3

**Review by dcramer — APPROVED** [review]

**Pull request merged**
