### PR TITLE
feat: Add consent prompt

### PR DESCRIPTION
**Pull request by dcramer**
This adds a the User.flags column with a single flag (``newsletter_consent_prompt``). That flag can be toggled on a row, and the UI will prompt the user to opt-in or out of the latest version of the newsletter consent.

### CODE REVIEW

**Comment by dcramer** [comment]
screen shot 2018-04-12 at 3 28 33 pm

https://github.com/getsentry/sentry/pull/8028

**Comment by dcramer** [comment]
This overhauls quite a bit of the backend code at this point. I scrapped 'newsletter' from the user emails endpoint and instead added a ``POST /users/me/subscriptions/`` handler which lets you do the default opt-in/out behavior.

**Comment by ckj** [comment]
@dcramer Do we need to have the [required] badge present on both the field label and the options? Otherwise, looks good 👍

**Review by mikeclarke — APPROVED** [review]
played around with this locally and it seems fine

**Pull request merged**
