### PR TITLE
Set project_id context for potentially problematic tasks

### PR DESCRIPTION
**Pull request by mattrobenolt**
Anywhere else you can think of?

### CODE REVIEW

**Comment by dcramer** [comment]
I'm not sure we instrument Celery correctly to clear context. Probably worthwhile to add it to instrumented_task at the very least.

**Comment by mattrobenolt** [comment]
Actually... will this be bad with Celery? I think I'll need to manaully clear the context, won't I?

**Comment by mattrobenolt** [comment]
Yeah, lemme add it into `instrumented_task`.

**Comment by dcramer** [comment]
:+1+

**Pull request merged**
