### PR TITLE
Fix bad address padding code for ios

### PR DESCRIPTION
**Pull request by mitsuhiko**
@getsentry/infrastructure

---

This change is [Reviewable](https://reviewable.io/reviews/getsentry/sentry/3907)

### CODE REVIEW

**Comment by dcramer** [comment]
Can we add some kind of test, since no one really knows what this is :)

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3907#-:-KOqoAbx1yeLYcoH3x5K:b97klde)*

**Comment by dcramer** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/sentry/lang/native/plugin.py, line 443 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/3907#-KOuvcKADpxG08hwNGOP:-KOuvcKADpxG08hwNGOQ:b3rp7d) ([raw file](https://github.com/getsentry/sentry/blob/35c6d2da3d701d395a528f4f66899fa41356ba35/src/sentry/lang/native/plugin.py#L443)):*
> ```Python
>     for frame in processed_frames:
>         for key in 'symbol_addr', 'instruction_addr':
>             frame[key] = '0x' + frame[key][2:].rjust(longest_addr - 2, '0')
> ```

re: add tests comment needs to be here i suppose for reviewable

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3907)*

**Comment by mitsuhiko** [comment]
Tests are there in case you did not see.

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3907#-:-KPW-l--LhP_lggnXtcc:b-qwnvxx)*

**Comment by mitsuhiko** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[src/sentry/lang/native/plugin.py, line 443 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/3907#-KOuvcKADpxG08hwNGOP:-KPW-pMaYInu6yisfEGU:b-896fix) ([raw file](https://github.com/getsentry/sentry/blob/35c6d2da3d701d395a528f4f66899fa41356ba35/src/sentry/lang/native/plugin.py#L443)):*
<details><summary><i>Previously, dcramer (David Cramer) wrote…</i></summary>
> re: add tests comment needs to be here i suppose for reviewable
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3907)*

**Comment by dcramer** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3907)*

**Pull request merged**
