### PR TITLE
ref(devserver): Default Relay to OFF

### PR DESCRIPTION
**Pull request by evanpurkhiser**

### CODE REVIEW

**Review by jan-auer — CHANGES_REQUESTED** [review]
What is the reason for this change? I'd strongly argue against that.

Turning Relay off means that event ingestion will not work much longer. We're removing the Python store endpoint any day now. All events reported also from the internal instance will no longer come in after that. 

If there are specific issues with the dev setup, please add them here and we can fix them individually.

**Comment by RaduW** [comment]
Please note that we will soon remove all Store endpoints from Sentry.

Once that is done, Relay will be the only way to get events in Sentry, therefore I think that disabling it by default is a bad idea. 

If there are problems or points of friction in using Relay in dev mode we (the ingest team) will do our best to fix them before we remove the Store endpoints from Sentry but we will eventually remove Store from Sentry.

Once again please let us know of any problems or general unpleasantness you encounter with Relay and we will do our best to sort them out.

**Comment by untitaker** [comment]
There has been the argument that most people don't actually ingest events. I would argue that we should not have defaults that leave sentry broken out of the box.

**Comment by untitaker** [comment]
What's the status on this, do we still want this?

**Comment by EvanPurkhiser** [comment]
I won't push to hard on this, I do agree we should dogfood, I just don't want this to become painful, so I'll try and bring up painpoints as I run into them.

Going to close now then.

**Pull request closed without merging**
