### PR TITLE
fix(api): Allow signed links to pass through SSO

### LINKED ISSUE #6044: Processing Issues shell script does not allow for organizations that require SSO
When trying to use the shell script, customer is getting back: `{"detail": "Must login via SSO"}`

### PR DESCRIPTION
**Pull request by HazAT**
Fixes GH-6044

### CODE REVIEW

**Comment by getsentry-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by mitsuhiko** [comment]
I think this is okay but I rather have someone else sign this off as well.

**Comment by mattrobenolt** [comment]
For my curiosity, why not use an API key? I may be missing some context here.

**Comment by mitsuhiko** [comment]
@mattrobenolt linksign is used for two pieces right now: unsub from email (which i guess is broken right now) and the generated dsym find script. The latter I suppose we could convert over to api keys somehow but there is no way to pass keys through the URL atm.

**Comment by HazAT** [comment]
@mitsuhiko @mattrobenolt mergeable?

**Review by mitsuhiko — APPROVED** [review]

**Pull request merged**
