### PR TITLE
ref: Add basic sentry instrumentation to metrics indexer

### PR DESCRIPTION
**Pull request by untitaker**
Instrument process_messages, which is a big chunk of synchronous
business logic that most easily fits into our transactions model.

Most of our operations are batched, and our batches are rather large, so
this should leave us with only a few txn per second at most.

### CODE REVIEW

**Comment by fpacifici** [comment]
Please run this through the QE environment ensuring Sentry is actually on. 
We do not know how bad this would be.

**Comment by lynnagara** [comment]
Isn't the batch size here only 50? https://github.com/getsentry/sentry/blob/a03e21a4fd6d06ace43dda9608315a861fe1fbe0/src/sentry/runner/commands/run.py#L613... If it's really 50, this might be sending too many transactions to Sentry.

**Comment by untitaker** [comment]
@lynnagara you are right. I'll just reduce the sample rate to 10% for now

**Comment by untitaker** [comment]
@fpacifici @lynnagara I tested it in QE env. The overhead on indexer performance is nonexistent even at 100% sample rate. That said, reducing to 10% is probably advisable anyway unless we're willing to fully trust DS to take care of this.

**Review by lynnagara — APPROVED** [review]

**Pull request merged**
