### PR TITLE
Add similarity indexing to `event_processed` signal receivers.

### PR DESCRIPTION
**Pull request by tkaemming**

### CODE REVIEW

**Comment by dcramer** [comment]
Do we need to add the default value of False to settings?

**Comment by tkaemming** [comment]
That should be covered [here](https://github.com/getsentry/sentry/blob/master/src/sentry/features/manager.py#L41-L42), right? (Or am I forgetting something?)

**Comment by dcramer** [comment]
Nope, nevermind.

**Review by JTCunning — APPROVED** [review]
https://www.youtube.com/watch?v=oTz93Y-qeq0

**Comment by tkaemming** [comment]
:metal:

**Pull request merged**
