### PR TITLE
ref(docs): Updating doc links

### PR DESCRIPTION
**Pull request by wmak**
- Docs is restructuring some URLs, updating links from sentry to these new onse

### CODE REVIEW

**Comment by ceorourke** [comment]
When do the new urls land? This looks fine, kinda surprised there aren't more 🤔

**Comment by wmak** [comment]
Going to land them at roughly the same time, here's the other PR for context https://github.com/getsentry/sentry-docs/pull/3892

docs can likely land first since most of them will handle redirects correctly

**Comment by ceorourke** [comment]
@wmak thanks for that, what about this bad boy: https://github.com/getsentry/sentry/blob/master/src/sentry/integrations/vsts/notify_action.py#L13

looks like it'll live under /product/integrations/source-code-mgmt/azure-devops

that was the only other one I found

**Comment by wmak** [comment]
ah @ceorourke that link was updated earlier in https://github.com/getsentry/sentry/pull/27438

**Review by ceorourke — APPROVED** [review]
oop look at me looking at outdated code

**Pull request merged**
