### PR TITLE
ref(editabletext): Apply design feedback

### PR DESCRIPTION
**Pull request by priscilawebdev**
**Before:**

image

hover:
image

**After:**

Default Mode

image

Edit Mode

image

Edit Hover Mode

image

Edit Active Mode

image

### CODE REVIEW

**Comment by markstory** [comment]
The visual differences for discover queries don't look ideal. Should the default state be more like the read state in dashboards?

**Comment by priscilawebdev** [comment]
@markstory sure. I think I missed that when I replaced `InlineInput` with `EditableText`. It should be fine now

**Comment by priscilawebdev** [comment]
@doralchan I have updated the code with the new design changes. Please let me know what you think 😉

**Comment by priscilawebdev** [comment]
@doralchan I've updated the code with the new changes. please let me know what you think 😉

new-changes

**Review by markstory — APPROVED** [review]
Looks good to me.

**Review by doralchan — APPROVED** [review]

**Pull request merged**
