### PR TITLE
feat(identity): Step 5 of removing org from IDP

### PR DESCRIPTION
**Pull request by adhiraj**
Drop organization_id column. I've seen `delete_column` used in other migrations, will this work?

### CODE REVIEW

**Review by mattrobenolt — CHANGES_REQUESTED** [review]
We can't do these in the same deploy. The column needs to be removed from the model definition before the migration. We can effectivley apply the migration at any point after we remove the column from the model in python since dropping the column is just cleanup.

**Comment by adhiraj** [comment]
Oh right because setting a default value is a django thing? Lemme update it.

**Comment by mattrobenolt** [comment]
It's not that, but what django does with all queries is like, `SELECT a, b, c, d FROM ...` and not like, `SELECT *`. So if you have a column in the model `organization_id`, Django will query `SELECT organization_id FROM ...` until it's removed from code.

What this means is that during deploy, it'll error as soon as the column is dropped, before the code has rolled out.

By removing the column from model first, makes Django think it doesn't exist so it stops fetching it.

**Comment by mattrobenolt** [comment]
Also, can we just move the whole migration to another PR? There's no point in doing what this migration is doing, and will just make it complicated trying to actually drop the column. If we just leave the migration as it was is fine, but we just put it in a separate PR.

**Comment by adhiraj** [comment]
I think we'll also have to alter db to remove not-null constraint on org_id?

**Comment by adhiraj** [comment]
Seems like we can merge this change into step 4 (https://github.com/getsentry/sentry/pull/8571) now, and remove non-null in that migration too. But happy to do it here too.

**Comment by adhiraj** [comment]
Actually if we need the null change it should happen after the code for step 4 goes out, so this is probably the right PR for it.

**Comment by mattrobenolt** [comment]
Hmm, good point. I'm sorta losing track of all of these here, but in isolation, your comment about not-null is correct. If we ship this change, things are going to start erroring since the column is flagged as "NOT NULL" and doesn't have a database level default value.

Granted, we can apply whatever changes we want manually, since it's unlikely this would be a real problem for on-premise since all of these are going to get applied right after one another and the race condition would just be non-existent.

**Review by mattrobenolt — APPROVED** [review]
:fire: 🍀

**Pull request merged**
