### PR TITLE
test(hc): Generate silo-mode tests at class level

### PR DESCRIPTION
**Pull request by RyanSkonnord**
Instead of adding siloed test methods within a class, generate a new siloed test case class. Previously, the setup and teardown methods were always run in monolith mode. This change ensures that the entire test run including setup runs in the proper mode.

Add the option to inject a set of Region objects at the decorator level, which overrides the global region map during setup.

Fix tests that now require stricter setup.

### CODE REVIEW

**Comment by RyanSkonnord** [comment]
> This change ensures that the entire test run including setup runs in the proper mode.

In other words, obeying the invariant condition articulated by @corps: "The invariant we want to move to is incredibly simple and forms the foundation of where we're going: all tests should either run entirely in monolith mode, or entirely in some combination of region and control modes.  A test that moves from region or control to monolith, or monolith to region or control, is invalid, cannot work, and represents a non existent system."

I expect the first commit to break some tests, which I believe is a sign of those tests spuriously relying on the `setUp` method being in monolith mode. This overlaps with some of the fixes in https://github.com/getsentry/sentry/pull/52768, and also should unblock fixing the still-broken tests there.

**Comment by corps** [comment]
Siiiick, will take a closer look.

**Review by corps — APPROVED** [review]

**Review by markstory — APPROVED** [review]
Nice work :clap:

**Comment by RyanSkonnord** [comment]
I believe I've fixed all test cases that required a simple `assume_test_silo_mode`. The other failures are:

- [x] `tests.sentry.hybrid_cloud.test_region.RegionResolutionTest`: Fixed in 72f9063
- [ ] `tests.sentry.incidents.action_handlers.test_msteams.MsTeamsActionHandlerTest`: Raises a `SiloLimit.AvailabilityError` that I believe exposes a legit bug in `create_alert_rule_trigger_action` when called with `type=ActionService.MSTEAMS`. If we don't want to block this PR while we fix it in another branch, I think it would be appropriate to downgrade `MsTeamsActionHandlerTest` to unstable.
- [ ] `tests.sentry.integrations.slack.webhooks.commands.test_help.SlackCommandsHelpTest`: Seems to be getting `"na.testserver"` from the default region data. Might be relying on the default monolith region for `url="http://testserver/extensions/slack/commands/"`? Either way, I'd prefer a fix that explicitly provides a `regions` parameter in `@control_silo_test(stable=True, regions=[...])` rather than asserting the default value.
- [ ] `tests.sentry.middleware.integrations.parsers.test_jira.JiraRequestParserTest`: Fails on `assert ControlOutbox.objects.count() == 0`. I'm not sure what that means yet.
- [ ] `tests.sentry.api.endpoints.test_accept_organization_invite.AcceptInviteTest`: Endpoint is returning 400.
- [ ] `tests.sentry.middleware.integrations.parsers.test_github.GithubRequestParserTest`: Fails on `assert ControlOutbox.objects.count() == 0`.

**Comment by corps** [comment]
@RyanSkonnord I think I know what the outbox errors are about, fixing them.

**Review by dashed — APPROVED** [review]
Thanks!

**Comment by RyanSkonnord** [comment]
Calling out [d02a1bd](https://github.com/getsentry/sentry/pull/53028/commits/d02a1bdc05092abf1a429bd64bbe5e0aad767ca8)... I only half understand what the problem was, but this seems to prevent issues with the outbox being in a state where where it tries to flush to `--monolith--` while in control mode. (Nothing related to the `RPC_SHARED_SECRET` value, which I manually checked was valid in both cases.)

I guess the multiple class-level decorators don't interact in the way I want. I hoped switching the order would fix the problem, but no dice. This makes me hesitate to adopt a solution that means we can't necessarily use other class-level decorators on tests as we normally would.

But, if no one objects, I think this is stable enough to go ahead. We can revisit the decorator-based implementation later if it does turn out to tie our hands too much.

**Comment by markstory** [comment]
> I guess the multiple class-level decorators don't interact in the way I want. I hoped switching the order would fix the problem, but no dice. This makes me hesitate to adopt a solution that means we can't necessarily use other class-level decorators on tests as we normally would.

I think that's an ok compromise. We don't use class decorators extensively.

**Pull request merged**
