### PR TITLE
fix(integrations): VSTS Use public alias rather than user id to get accounts.

### PR DESCRIPTION
**Pull request by lauryndbrown**
The `get_user_info` method overwrites the user id in the response with the user's descriptor. Thankfully, the public alias is also the user's uuid. I use public alias to get the user's uuid instead.

### CODE REVIEW

**Comment by lauryndbrown** [comment]
@mnoble no it's not descriptors and uuids are different. Descriptors are across microsoft applications where as the uuid is specific to vsts. The api I'm using to look up accounts only accepts uuids that's true for a lot of it.

**Comment by lauryndbrown** [comment]
@mnoble @adhiraj wrote the get_user_info method. Maybe it had a different usecase or something at the time?

**Comment by mnoble** [comment]
Can we update `get_user_info` and add something like:

```python
user['uuid'] = user['id']
```

before we overwrite that attribute and then use that? Feels more stable to me.

**Comment by adhiraj** [comment]
The reason for choosing descriptor is exactly what it says in the comment -- `The "id" field for the same user can be different for the same user in different places, so the "descriptor" is the best identifier for a user.`.

Change looks fine to me. How have we been making other API calls so far? Do they just need the token and not the ID?

**Review by mnoble — APPROVED** [review]

**Pull request merged**
