### PR TITLE
minor fix in brazilian transaction

### PR DESCRIPTION
**Pull request by AyrtonRicardo**

### CODE REVIEW

**Comment by mattrobenolt** [comment]
Hey @AyrtonRicardo, thanks for the contribution!

Unfortunately, all translations need to go through Transifex (https://www.transifex.com/getsentry/dashboard/all_resources/pt_BR/?project=sentry) it this change will get lost the next time we sync with them.

:(

If you'd like, you can submit the contribution over there, if not, we can apply it ourselves.

**Comment by mattrobenolt** [comment]
Sorry, that previous link was bad. :( It required you to be logged in.

This is the right one: https://www.transifex.com/getsentry/sentry/

**Comment by AyrtonRicardo** [comment]
Oh right. I made this modification on Transifex!

:) 
Thanks for accept me!

**Comment by mattrobenolt** [comment]
Yup, no problem. :) Thanks again!

**Pull request closed without merging**
