### PR TITLE
added data to release.version

### PR DESCRIPTION
**Pull request by JoseMoranUrena523**
Due to issue #41228, I added .data. to release.version to try to fix the error, since that is where the release version is showing when you add an app webhook to Heroku. I am doing this because deployhooks:http is deprecated and I want to try to fix it so I don't have to be using Zapier.

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Comment by JoseMoranUrena523** [comment]
I am just pushing more updates from the main branch to there.

**Comment by JoseMoranUrena523** [comment]
Ok

**Comment by JoseMoranUrena523** [comment]
Will it be merged

**Comment by armenzg** [comment]
> Will it be merged

Only when the Github checks pass and I approve the PR after I see them green.

**Comment by armenzg** [comment]
There are [test failures](https://github.com/getsentry/sentry/actions/runs/3596661090/jobs/6129893953) in `tests/sentry_plugins/heroku/test_plugin.py`; would you be able to look into fixing them?

**Comment by JoseMoranUrena523** [comment]
Weird, I don't understand what is wrong with this.

**Comment by JoseMoranUrena523** [comment]
Try now @armenzg

**Comment by armenzg** [comment]
Merging master won't fix it :/ It is a real test failure that needs work.

**Comment by JoseMoranUrena523** [comment]
No no, I fixed it on my repo.

On Tue, Dec 6, 2022 at 3:59 PM Armen Zambrano G.

**Comment by armenzg** [comment]
I don't see any test changes under https://github.com/getsentry/sentry/pull/41896/files

I will get the CI running just in case I'm missing something

**Comment by JoseMoranUrena523** [comment]
I can see edits

**Comment by armenzg** [comment]
I can only see code changes in here. Are you saying that you wrote tests for this? I may be misunderstanding
image

**Comment by JoseMoranUrena523** [comment]
That was the only update I did.

**Comment by JoseMoranUrena523** [comment]
Meow

**Pull request closed without merging**
