### PR TITLE
feat(access): Allow app tokens to assign roles based on their scopes

### PR DESCRIPTION
**Pull request by RyanSkonnord**
Proposed tweak to role-assignment policy to resolve https://getsentry.atlassian.net/browse/ER-1015 and https://getsentry.atlassian.net/browse/ISSUE-1357. See also https://github.com/getsentry/sentry/pull/33839.

Thanks to @scefali for the underlying idea.

### CODE REVIEW

**Review by scefali — COMMENTED** [review]
@RyanSkonnord looks good to me, just need some new tests

**Comment by RyanSkonnord** [comment]
just need some new tests

https://github.com/getsentry/sentry/pull/33853/commits/bf1aeaa18655e25045f7d210c3d37b28ecfa74e2 Anything else?

**Comment by RyanSkonnord** [comment]
Turns out this is an incomplete solution. It's only substituting for the check of which roles the request is authorized to promote to, effectively replicating the following lines by other means:

https://github.com/getsentry/sentry/blob/7f3b708e800b46a838eddbd4ccbe7bb69b90a00b/src/sentry/api/endpoints/organization_member/__init__.py#L50-L51

However, it fails to stop the request from demoting a member of a higher role, which is what these two lines are doing:

https://github.com/getsentry/sentry/blob/7f3b708e800b46a838eddbd4ccbe7bb69b90a00b/src/sentry/api/endpoints/organization_member/__init__.py#L47-L48

**Review by nhsiehgit — APPROVED** [review]

**Comment by RyanSkonnord** [comment]
Okay, so it's a little unclear what `get_allowed_roles` is doing. There's this check (with a recently added comment) that checks whether the targeted member has a higher role than the acting member and, if they do, completely blocks the operation.

https://github.com/getsentry/sentry/blob/101ce5f7aefcf4c1562788381623343bc96b0765/src/sentry/api/endpoints/organization_member/__init__.py#L48-L50

This is important to do, as indicated by the following unit test.

https://github.com/getsentry/sentry/blob/73bd578967fa96b3085ccbf79bae747672393ff7/tests/sentry/api/endpoints/test_organization_member_details.py#L364-L377

However, if we remove or mess with the check on lines 48-50, the test doesn't break. What gives? Well...

https://github.com/getsentry/sentry/blob/73bd578967fa96b3085ccbf79bae747672393ff7/src/sentry/api/endpoints/organization_member/details.py#L262-L267

This means that, in practice, `get_allowed_roles` doesn't define only the roles you're allowed to promote to, but also demote *from*. The target member's starting and ending roles must *both* be in the set. You would expect it's only checking the latter role from looking at the check on lines 48-50. I suspect that check is unnecessary in practice, as I'm currently investigating with #33935.

This is good news for the app token problem, because it means the original solution suffices. An app token wouldn't have permission to demote (for example) a manager unless it has all the same scopes as a manager, which I believe is okay under our security model.

**Comment by RyanSkonnord** [comment]
> I suspect that check is unnecessary in practice, as I'm currently investigating with https://github.com/getsentry/sentry/pull/33935.

As commented in #33935, amend "unnecessary in practice" to "logically unreachable". Shout out to @nhsiehgit for being right all along in https://github.com/getsentry/sentry/pull/33851#discussion_r857797121

Per my previous comment and the `test_internal_integration_cannot_lower_superior_role` case, this should now be safe to deliver pending review and approval.

**Review by nhsiehgit — APPROVED** [review]
double +1

**Review by maxiuyuan — APPROVED** [review]

**Comment by RyanSkonnord** [comment]
Closing this because the platform currently doesn't allow any way for app integration tokens to be given `alerts:*` scopes, which would be necessary for authorizing any member role changes (given the default configuration of roles). That means the proposed change would imply the existence of a user flow that isn't fully possible, as would the unit tests that set up a precondition that can't be created on an actual stack.

The solution is still most of the way there, and we have a few ideas (thanks again, @scefali!) about how to tweak it for practical use. I'll hang onto the branch and/or reopen this PR when we can commit to a fix.

**Pull request closed without merging**
