### PR TITLE
test: Make Discover test deterministic

### PR DESCRIPTION
**Pull request by lynnagara**
This test is flaky because the transaction is stored as a nullable string in
events and a non nullable string in transactions. Specifically, it happens
because `"a" > ""` but `"a" < NULL`.

Unfortunately we cannot fix this by rewriting `transaction` into `nullIf(transaction, '')` 
in Snuba since some tests in
https://github.com/getsentry/sentry/blob/master/tests/snuba/api/endpoints/test_organization_events_v2.py
will fail with that change and depend on the existing behaviour.
This is a workaround that avoids that issue by simply ensuring the same
`min()` is returned from both storages.

### CODE REVIEW

**Comment by wmak** [comment]
Hmm our version of `any` should be deterministic, this is cause we actually just call `min` instead. This is cause we limit the frontend `min` to numeric fields, but allow anything for the frontend `any` field.

**Comment by lynnagara** [comment]
@wmak Are you saying this is not a valid test and should be removed, since any() is never used? Or should I change any() to min() instead?

**Comment by wmak** [comment]
Sorry, no I'm saying that this test should already be deterministic because under the hood we're actually calling min alread:
https://github.com/getsentry/sentry/blob/master/src/sentry/api/event_search.py#L2244-L2250

**Comment by wmak** [comment]
>  The way it is written now definitely does not do the conversion and just sends any() along to Clickhouse

OH... uh It should, let me fix that instead

**Comment by lynnagara** [comment]
Sorry @wmak I was wrong earlier, it does do the conversion. Something else is causing a different min() when we switch the storage.

**Comment by lynnagara** [comment]
@wmak As discussed offline, updated this to limit results with type=transaction. My originally preferred solution involved making the change in Snuba to always translate `transaction` into `nullIf(transaction, '')`. However this causes other tests that depend on the current behaviour like https://github.com/getsentry/sentry/blob/master/tests/snuba/api/endpoints/test_organization_events_v2.py#L2870 to fail, so I've settled for this workaround instead.

**Review by wmak — APPROVED** [review]

**Pull request merged**
