### PR TITLE
Prevent one hit wonders on js cache

### PR DESCRIPTION
**Pull request by mitsuhiko**
Do not cache on first attempt to not cache one hit wonders

### CODE REVIEW

**Review by mattrobenolt — APPROVED** [review]
wcgw

**Comment by benvinegar** [comment]
@mitsuhiko – is this worth revisiting?

**Comment by mitsuhiko** [comment]
@benvinegar i think it's still worth exploring, maybe on a single worker to see what it does.

**Comment by markstory** [comment]
Is this something we're still interested in pursuing or can it be closed because it can no longer be merged?

**Pull request closed without merging**
