### PR TITLE
fix(sessions): Order results by timestamp and log error if snuba limit exceeded [ISSUE-1372]

### PR DESCRIPTION
**Pull request by jjbayer**
As described in https://getsentry.atlassian.net/browse/ISSUE-1372, gaps occur in sessions_v2 time series when the number of releases is large, for example:

```javascript
// Results for 8 days:
"series": {
        "sum(session)": [
            0,
            105,
            3653,
            77331,
            174854,
            179608,
            174777,
            61066
        ]
    }
    
// Results for the same end time, but ~30 days:
"series": {
        "sum(session)": [
            // ...
            0,
            0,
            3653,
            77331,
            174856,
            0,
            174814,
            0
        ]
    }
```

This seems to be caused by the fact that snuba applies a default limit of 1000:

https://github.com/getsentry/snuba/blob/69862db3ad224b48810ac1bb3001e4c446bf0aff/snuba/query/snql/parser.py#L908-L909

The sessions API queries these series without an orderBy constraint, so a random subset of entries default to zero.

This PR logs an error if this limit is actually reached. Furthermore, we add an order by clause to the snuba query, such that at least the most recent part of the time series is complete.

### CODE REVIEW

**Review by untitaker — APPROVED** [review]
have you checked locally if the error ends up becoming a sentry issue? that is not necessarily the case as our logging setup is quite arcane

**Review by Swatinem — APPROVED** [review]

**Comment by vladkluev** [comment]
If this query populates a UI, does the UI need 10k points of resolution? Returning that many rows from snuba will likely make a slower user experience since you're transferring so much data over the wire. Do we really need this many data points?

**Comment by onewland** [comment]
Can you explain 

> The sessions API queries these series without an orderBy constraint, so a random subset of entries default to zero.

with a little more detail? It does not make sense to me

**Comment by jjbayer** [comment]
> If this query populates a UI, does the UI need 10k points of resolution? Returning that many rows from snuba will likely make a slower user experience since you're transferring so much data over the wire. Do we really need this many data points?

@vladkluev I'm open to lowering this limit. In the linked issue the UI requested ~1700 data points (I'm not saying that's justified), so maybe we can set it to 3000 and just wait and see how often the error is logged?

**Comment by vladkluev** [comment]
My question is less about the specific limit and more about the retrieval of the data. How many user-perceivable datapoints does this chart actually have? I don't think it's anywhere close to 1000. Maybe 100? But if what is needed to power this chart is a 1700 point query, something tells me the query is incorrect. 

image

**Comment by jjbayer** [comment]
> Can you explain
> 
> > The sessions API queries these series without an orderBy constraint, so a random subset of entries default to zero.
> 
> with a little more detail? It doesn't make sense to me

@onewland the sessions API writes the snuba results into a fixed number of computed time slots. So if the number of rows returned from snuba is less than the number of time slots (multiplied by the number of time series), some time slots will remain "empty", that is, assume a value of 0.

**Comment by vladkluev** [comment]
> the sessions API writes the snuba results into a fixed number of computed time slots.

Can snuba just be queried with those computed time slots instead and do the aggregation on the snuba side? Then you won't need to be querying so many datapoints

**Comment by jjbayer** [comment]
> But if what is needed to power this chart is a 1700 point query, something tells me the query is incorrect.
Good point. I think the problem is that the org in question has a lot of releases, and this API does not offer functionality to only query releases that have been active recently. I'll look into that though.

**Comment by jjbayer** [comment]
> Can snuba just be queried with those computed time slots instead and do the aggregation on the snuba side?

@vladkluev The aggregation _is_ done on the snuba side. The high number of rows is a result of the high number of releases in this project: The request to this API endpoint translates to "Give me daily session counts for the last 30 days, grouped by release", which easily surpasses 1000 data points when there are a few dozen releases per month.

I did some digging and found that the UI actually only displays the top-50 releases, and discards the rest: https://github.com/getsentry/sentry/blob/6b29955072b4fbed6d8843ae193d65509e288f8f/static/app/views/releases/list/releasesAdoptionChart.tsx#L88-L97. It would of course be nice if we could apply this filter on the backend instead.

@jan-auer @Swatinem This is a problem that applies to both the sessions and the metrics API, maybe it's time we start thinking about mandatory pagination and optional orderBy for both of them. In the mean time, I think we should apply this PR (possibly with a lower limit) as a band aid.

**Comment by Swatinem** [comment]
I think it would be fair to think about this in a broader sense, yes.
Essentially we have `time_range * time_resolution * groupby_cardinality`. And in this case `groupby_cardinality` is just super large, because of the massive amounts of releases. Even larger if you group by both release, and env.
Figuring out the cardinality here is difficult I would say. And also figuring out if you really want to display that huge amount of data.

I think this is only a problem if you have multiple releases "active" at the same time. So for example for sentry itself, we expect the old release going to 0 once the next release is rolled out, so it won’t "use up" rows in the query result.

**Comment by untitaker** [comment]
>If this query populates a UI, does the UI need 10k points of resolution? Returning that many rows from snuba will likely make a slower user experience since you're transferring so much data over the wire. Do we really need this many data points?

That's a direct consequence of product requirements, which I think we will have to revisit, but that's where we are today. Currently the product just misbehaves, and there's no indication that 10k rows are too much to handle for it (downstream, unless 10k is already too much for Snuba)

**Comment by jjbayer** [comment]
> have you checked locally if the error ends up becoming a sentry issue? that is not necessarily the case as our logging setup is quite arcane

@untitaker yeah looks good:

Screen Shot 2022-01-21 at 13 22 28

**Comment by jjbayer** [comment]
I reverted the snuba limit back to 1000, so we can first analyze how often this problem occurs before we increase the limit. That means that this PR alone does not yet solve the customer issue, but with the order by, the results from the API will at least be correct for a part of the time range.

**Review by untitaker — APPROVED** [review]

**Pull request merged**
