### PR TITLE
feat(page-filters): Change time selector to dropdown from button bar

### PR DESCRIPTION
**Pull request by davidenwang**
I rewrote the component as a dropdown so the diff is not that helpful. Might just be easier to only look at the new code.

Also added new prop to the `TimeRangeSelector` to allow for custom summary text to be provided

Previously was:
image

Changing to look like:
image

### CODE REVIEW

**Comment by evanpurkhiser** [comment]
I wonder if we should be implementing this with @vuluongj20's new style dropdown look?

**Comment by davidenwang** [comment]
> I wonder if we should be implementing this with @vuluongj20's new style dropdown look?

I think we definitely can in the future, but right now these page filters are built as wrappers around the global selection header dropdowns. So we'd have to change those to use the V2 dropdowns. It might be easier to migrate off the global header fully first and then upgrade the dropdowns to the new V2 ones.

**Comment by vuluongj20** [comment]
> I wonder if we should be implementing this with @vuluongj20's new style dropdown look?

@evanpurkhiser Ideally, yes 😛 Right now I'm working on some layout changes to the search & filter area. After that, if we have enough time I'd want to update all three page filters to use [CompactSelect](https://github.com/getsentry/sentry/pull/31850).

**Comment by evanpurkhiser** [comment]
> > I wonder if we should be implementing this with @vuluongj20's new style dropdown look?
> 
> I think we definitely can in the future, but right now these page filters are built as wrappers around the global selection header dropdowns. So we'd have to change those to use the V2 dropdowns. It might be easier to migrate off the global header fully first and then upgrade the dropdowns to the new V2 ones.

oh yea, totally sounds good

**Review by evanpurkhiser — APPROVED** [review]
Looks good and clean to me

**Pull request merged**
