### PR TITLE
chore(ts): Consistent enum casing

### PR DESCRIPTION
**Pull request by evanpurkhiser**
All enums should be in pascal case

The following were the offenders

```
/Users/evan/Coding/sentry/static/app/components/onboarding/frameworkSuggestionModal.tsx
  27:13  error  Enum name `SUPPORTED_LANGUAGES` must match one of the following formats: PascalCase  @typescript-eslint/naming-convention

/Users/evan/Coding/sentry/static/app/types/stacktrace.tsx
  3:13  error  Enum name `STACK_VIEW` must match one of the following formats: PascalCase  @typescript-eslint/naming-convention
  9:13  error  Enum name `STACK_TYPE` must match one of the following formats: PascalCase  @typescript-eslint/naming-convention

/Users/evan/Coding/sentry/static/app/views/performance/data.tsx
  46:13  error  Enum name `PERFORMANCE_TERM` must match one of the following formats: PascalCase  @typescript-eslint/naming-convention

/Users/evan/Coding/sentry/static/app/views/performance/utils.tsx
  90:13  error  Enum name `PROJECT_PERFORMANCE_TYPE` must match one of the following formats: PascalCase  @typescript-eslint/naming-convention

/Users/evan/Coding/sentry/static/app/views/settings/projectSourceMaps/projectSourceMaps.tsx
  37:6  error  Enum name `SORT_BY` must match one of the following formats: PascalCase  @typescript-eslint/naming-convention
```

### CODE REVIEW

**Review by k-fish — COMMENTED** [review]
I kind of prefer constant-style naming, but I prefer consistency more so 👍

**Review by k-fish — APPROVED** [review]

**Comment by priscilawebdev** [comment]
hm do we have a guideline in our frontend handbook on this topic? I was not aware that ENUMS should be in pascal case

**Comment by evanpurkhiser** [comment]
95% of our enums were in PascalCase. I was planning to introduce a eslint rule so we don’t have to think about it

**Comment by priscilawebdev** [comment]
eslint rule sounds good :)

**Pull request merged**
