### PR TITLE
style(toolbar): update feature flag panel css

### PR DESCRIPTION
**Pull request by michellewzhang**
- relates to https://github.com/getsentry/sentry/issues/75636
- modify feature flag css according to the figma. main changes:
    - move "clear overrides" button from above search bar to the bottom of the "overrides" tab. 
    - Use x icon and "remove all" for the clear overrides button
    - make a "+ add flag" button in header
    - remove the gray "name value" header

before:
SCR-20240813-mmtm
SCR-20240813-mmul

after:

https://github.com/user-attachments/assets/acc7ede1-3f03-4999-969c-973ac410dd8c

### CODE REVIEW

**Comment by aliu39** [comment]
I know it's different from the figma but I like "+ Override" instead of "+ Add Flag" for the button.

Maybe the `+` icon could toggle to an up chevron `^` when the "Flag name to override" box is shown, to emphasize clicking again will hide the drop-down.

Nit: can disable + button when nothing is entered in the override box.

**Comment by aliu39** [comment]
A design idea: what if clicking the + Add flag button didn't make a drop-down, but instead replaced the regular search bar:
Screenshot 2024-08-14 at 11 55 59 PM

with a special override search bar, button, and toggle?
Screenshot 2024-08-14 at 11 56 13 PM

The override input would filter the FF list too (excuse the bad mock-up):
Screenshot 2024-08-14 at 11 56 54 PM
Screenshot 2024-08-14 at 11 57 08 PM

Clicking the button in the header would toggle the search bar back to normal.  
This lets me see the current status of the flag I'm about to override, and whether it exists. It also cleans up the panel.

**Review by aliu39 — APPROVED** [review]
Aside from the nit all my feedback was design ideas/potential follow-ups, we can merge this

**Comment by michellewzhang** [comment]
> what if clicking the + Add flag button didn't make a drop-down, but instead replaced the regular search bar with the override bar?

@aliu39 i like this idea! we should bring it up with @Jesse-Box and do in a followup if he agrees

especially this point: agree that it would be useful

> This lets me see the current status of the flag I'm about to override, and whether it exists.

**Comment by michellewzhang** [comment]
@aliu39 
added the chevron solution for now: 
https://github.com/user-attachments/assets/cf19eff0-1a36-4007-a0fb-b46b340065eb

**Pull request merged**
