### PR TITLE
chore: blacken take 2

### PR DESCRIPTION
**Pull request by joshuarli**
Got too scared to force push a large rebase to https://github.com/getsentry/sentry/pull/14263, so putting it on a new branch.

Currently testing with https://github.com/getsentry/getsentry/pull/3098.

### CODE REVIEW

**Comment by joshuarli** [comment]
This is looking pretty good, just have to wait for https://github.com/getsentry/getsentry/pull/3098 to pass. Then fix the small amount of merge conflicts in github's ui.

**Comment by joshuarli** [comment]
Oh, and `autopep8` has to be removed otherwise `sentry.lint` will conflict with `black` back-and-forth. https://github.com/getsentry/sentry/pull/14401

**Comment by joshuarli** [comment]
Rebased with

```
git fetch origin
git rebase -Xours origin/master
git status -s | grep DU | awk '{print $2}' | xargs git rm
git rebase --continue
pre-commit run -a
git add --all
git commit -m "re-black files overwritten by preferred rebase"
```

**Review by mattrobenolt — APPROVED** [review]

**Review by tkaemming — APPROVED** [review]
Yep, looks like Python

**Pull request merged**
