### PR TITLE
fix(integrations): use p-debounce for external issue linking

### PR DESCRIPTION
**Pull request by scefali**
Lodash's debounce doesn't work well with async functions as it will return a stale value even if it triggers the debounced function again. This is because `debounce` returns a function which just returns a value instead of a promise. This is causing a bug (https://getsentry.atlassian.net/browse/ISSUE-646).

The cleanest solution I found is to switch to a different library for debouncing (p-debounce). This debouncer returns a function that returns a promise. The debounced function calls get queued up until the user stops typing, makes the async request with the latest search term, and then returns that result. All function calls of `getOptions` wait on the single request to be finished then all return the same value.

 The other possible solution is to pass callbacks (see my other attempt: https://github.com/getsentry/sentry/pull/16215).

### CODE REVIEW

**Review by billyvg — COMMENTED** [review]
What does p denounce do that lodash doesn’t? There’s a bunch of different options for lodash denounce that we can utilize. I would prefer not to add a diff library for this if we don’t need to.

**Comment by scefali** [comment]
@billyvg I normally would agree with you about adding new libraries. The big difference between the lodash `debounce` and `pDebounce` is that `debounce` returns a value while `pDebounce` returns a promise. What this means for `debounce` is the following:
>  Subsequent calls to the debounced function return the result of the last func invocation.
What happens is that when you are typing, it will return the result of the last function invocation, wait until the debounce delay is over, then kick off the async request. It won't do anything with that result until you start typing again, whereupon it immediately returns that value. I've played around with the different options; none of them ensure that you don't return a stale value.

What `pDebounce` does is that instead of returning the result of the last function invocation, it waits until the debounce delay is finished, then calls the async function, then returns that result. It never returns an old value. All calls of `getOptions` that are being debounced all return at the same time with the same value (all calls were waiting on the debounced function to finish). Does that make sense?

**Comment by lynnagara** [comment]
I think having 2 ways of doing debouncing is confusing and should be avoided if at all possible

If lodash debounce no longer meets our requirements, we should probably agree on a future approach (and e.g. whether we want to codemod the rest of the codebase if we want this to replace lodash everywhere).

Otherwise, if the intent is for this library is being introduced for just this one spot why not just not use an async function? I don't think it's worth introducing a library for debouncing this one component.

**Comment by scefali** [comment]
@lynnagara good point. I will close this PR.

**Pull request closed without merging**
