### PR TITLE
ref(quick-start): Update polling logic

### PR DESCRIPTION
**Pull request by priscilawebdev**
closes https://github.com/getsentry/projects/issues/329

### CODE REVIEW

**Review by shellmayr — COMMENTED** [review]
Could the polling be activated only when the user opens the injected onboarding page? E.g. I never close my sidebar, would be a shame if this causes polling to happen despite me not needing it at all. I suppose this may be the same way for many users.

**Comment by priscilawebdev** [comment]
> Could the polling be activated only when the user opens the injected onboarding page? E.g. I never close my sidebar, would be a shame if this causes polling to happen despite me not needing it at all. I suppose this may be the same way for many users.

we still need it for the 'overall number', otherwise yes 
image

**Comment by shellmayr** [comment]
> > Could the polling be activated only when the user opens the injected onboarding page? E.g. I never close my sidebar, would be a shame if this causes polling to happen despite me not needing it at all. I suppose this may be the same way for many users.
> 
> we still need it for the 'overall number', otherwise yes image

Yeah, but do we need to update it if people don't even open it?

**Comment by priscilawebdev** [comment]
> Yeah, but do we need to update it if people don't even open it?

We display a red dot, indicating that tasks have been 'done' but they need to open the sidebar for them to be 'seen' (that's why) . We can probably update this flow but let's have this merged and discuss this again

**Comment by priscilawebdev** [comment]
@shellmayr I created this [task](https://github.com/getsentry/projects/issues/347) to revisit this flow

**Review by shellmayr — APPROVED** [review]

**Pull request merged**
