### PR TITLE
fix(ui): Avoid scrollbars on smaller screens

### PR DESCRIPTION
**Pull request by evanpurkhiser**

### CODE REVIEW

**Review by scefali — COMMENTED** [review]
@EvanPurkhiser doesn't seem like this did the trick for the pipeline views :(

**Comment by EvanPurkhiser** [comment]
It's probably because it's not body-sidebar 😢

**Comment by priscilawebdev** [comment]
oh ... scrollbars are annoying... 😬

**Comment by priscilawebdev** [comment]
Are you sure this works? I still can see them

**Comment by scefali** [comment]
Just pulled down and still not working :/

**Comment by EvanPurkhiser** [comment]
damn, I even tested this on the integration 🤔

**Comment by EvanPurkhiser** [comment]
At some point I'll get this in

**Comment by evanpurkhiser** [comment]
Deal with this later.

**Pull request closed without merging**
