### PR TITLE
feat(gdpr): Update subscribe text

### PR DESCRIPTION
**Pull request by dcramer**

### CODE REVIEW

**Comment by dcramer** [comment]
screen shot 2018-04-09 at 2 25 42 pm

**Comment by dcramer** [comment]
Handing this over to @mikeclarke

**Comment by dcramer** [comment]
@ckj @cameronmcefee we might want to consider just transitioning /signup/ fully into the app so itll be easier to maintain this language

**Comment by dcramer** [comment]
Probably should make sure we have a test that covers a mocked subscription backend since right now there's no failures with this change and I'd expect there to be.

**Comment by cameronmcefee** [comment]
I don't mind that, personally. It gives us one less semi-visible point of failure, and I don't think it would be terrible from a brand perspective

**Comment by dcramer** [comment]
I lessened the font size to 0.9em for the radio selections. 

This will have test coverage as part of #7867

**Review by mikeclarke — APPROVED** [review]

**Pull request merged**
