### PR TITLE
build(eslint): Upgrade sentry eslint config to 1.12.0

### PR DESCRIPTION
**Pull request by billyvg**
includes this rule only https://github.com/getsentry/eslint-config-sentry/commit/c7359131d1a1ba9fe19c5fb661c819ec62f24f81

### CODE REVIEW

**Comment by lynnagara** [comment]
Will we need to fix code that don't adhere to this rule before merging this? Can we also do this for getsentry?

**Comment by billyvg** [comment]
@lynnagara getsentry here https://github.com/getsentry/getsentry/pull/2887 -- does not require any code updates since the rule change is not necessarily stricter. 

What we can do as a followup is to clean out any one-off `no-unused-vars` but it'll have to be a manual process.

**Comment by lynnagara** [comment]
I see. An aside - I'd also be in favour of applying this to all args (not just after-used)

**Comment by billyvg** [comment]
Oh yeah you're right, it should be `all` since we ignore `_` now

**Review by markstory — APPROVED** [review]

**Pull request merged**
