### PR TITLE
fix(feedback): Lowercase event ID to align with normalization behavior

### PR DESCRIPTION
**Pull request by dcramer**

### CODE REVIEW

**Comment by dcramer** [comment]
A customer hit this as the iOS SDK was sending uppercase event_id, which then gets coerced to our standard lowercase UUID. This left the feedback objects dangling as they could never match an event.

**Review by mitsuhiko — APPROVED** [review]
looks good to me

**Comment by alex-hofsteede** [comment]
I think we should patch `EventManager.from_event_id` to use `lower()` as this is the common method now where all event lookups from the API should go through.

Solving it there will solve it for all our API

**Comment by dcramer** [comment]
@alex-hofsteede wont do that in this patch but agree that'd be a good followup. Do you think we need/should change anything on Snuba-side to be CI?

**Pull request merged**
