### PR TITLE
feat(issue-details): Add syntax highlighting to SQL code in breadcrumbs

### LINKED ISSUE #52929: Syntax highlighting for SQL queries in an issue
SQL queries can be shown in an issue in various locations: span evidence, span tree, and breadcrumbs. We've already done work to format these queries ([changelog entry here](https://changelog.getsentry.com/announcements/improved-sql-readability)), but we can go one step further and give them syntax highlighting as well.

Image

Image

### PR DESCRIPTION
**Pull request by 17hogeju**
Closes https://github.com/getsentry/sentry/issues/52929

Before:
Screenshot 2024-01-05 at 9 08 51 AM

After:
Screenshot 2024-01-05 at 9 08 16 AM

After with Highlighting:
Screenshot 2024-01-05 at 9 09 43 AM

NOTE: This PR does not include cases with annotated/filtered text:
Screenshot 2024-01-09 at 9 24 01 AM

### CODE REVIEW

**Review by malwilley — COMMENTED** [review]
A couple styling things I'm noticing:

- Font size should be 12px (I think the default is 13px for some reason)
- We don't want the bottom margin
- Inner padding should match the other breadcrumb items with gray background (looks like the default prism styling adds more than we need)
 
CleanShot 2024-01-04 at 11 03 51

**Comment by 17hogeju** [comment]
> * Font size should be 12px (I think the default is 13px for some reason)

We should probably update the other code blocks in the breadcrumbs too then. It looks like they also use size 13.

Screenshot 2024-01-04 at 11 29 35 AM

**Comment by malwilley** [comment]
@17hogeju  while testing I found one more thing that is missing. When the breadcrumb SQL is too long, we cut it off with `...` and show a tooltip. You can find an example here: https://sentry.sentry.io/issues/3899260560/events/b36f08142cce490fbd44a97338fdbd64/

CleanShot 2024-01-05 at 09 05 51@2x
CleanShot 2024-01-05 at 09 06 46@2x

**Comment by 17hogeju** [comment]
Screenshot 2024-01-08 at 1 12 52 PM

**Comment by 17hogeju** [comment]
After chatting, this PR will not address SQL formatting when there is annotated text present.

**Review by malwilley — APPROVED** [review]

**Pull request merged**
