### PR TITLE
ref(app-platform): App Platform Celery Queue

### PR DESCRIPTION
**Pull request by mnoble**
Adds a dedicated queue for App Platform tasks.

### CODE REVIEW

**Review by markstory — COMMENTED** [review]
:clap:

**Review by mattrobenolt — APPROVED** [review]
Let's just give @JTCunning and @getsentry/ops a heads up since this will be moving tasks out of a dedicated resource pool into a shared resource pool, until we want to allocate dedicated resources for these tasks. So it's really hard to tell if we need it now unless you can suggest usage. I'm guessing usage is very low though.

**Comment by mnoble** [comment]
@mattrobenolt @JTCunning so currently we enqueue a lot of jobs, but they don't really end up doing much. About ~1000/min tasks enqueued[1], each running for like 6ms on average[2].

[1] https://app.datadoghq.com/dash/960651/api-platform?screenId=960651&screenName=api-platform&from_ts=1544671800000&is_auto=false&live=true&page=0&tile_size=m&to_ts=1544758200000&fullscreen_widget=400507639

[2] https://app.datadoghq.com/dash/960651/api-platform?screenId=960651&screenName=api-platform&from_ts=1544671800000&is_auto=false&live=true&page=0&tile_size=m&to_ts=1544758200000&fullscreen_widget=776511096675652

**Comment by JTCunning** [comment]
This is all good.

We (ops) just need to deploy https://github.com/getsentry/ops/pull/1417 as a follow-up to make the queue federated, ensuring all tasks get picked up in a timely manner.

**Pull request merged**
