### PR TITLE
fix(integration): Treat single label domains as valid in jira server and bitbucket server

### LINKED ISSUE #17376: Integration URLs without '.'
## Summary
Currently Integrations require a '.' in the URL. When using a reverse proxy - the URL will not have a '.' character and so the valid URL fails validation

## Motivation

Currently integrations do not really work with a reverse proxy.

## Additional Context
image
Example above

### PR DESCRIPTION
**Pull request by dflss**
The Jira and Bitbucket server integrations are using a built-in Django URL validator. This means Jira and Bitbucket server can't be used without using a FQDN. This PR proposes to add a custom validator that inherits from Django URLValidator and allows to use single label domains as the URL.

Fixes #17376

### CODE REVIEW

**Comment by dflss** [comment]
@BYK Sorry to mention you personally but I've seen that you've been involved in this issue before - can you help with the workflow approvals?

**Comment by BYK** [comment]
Hi @dflss, sorry for the wait. I'll be reaching out to the team.

**Comment by dflss** [comment]
@BYK any news?

**Comment by BYK** [comment]
We are going to provide a review for this approach and get this landed soon. It is just lower priority among other things.

As much as we'd like to fix this issue, we need to make a distinction between self-hosted and SaaS as `SaaS` would never connect to TLDs and it would be an error to accept these values.

**Pull request closed without merging**
