### PR TITLE
add organization user issue search endpoint

### PR DESCRIPTION
**Pull request by macqueen**
also adds a `get_orgs` method on the user, which is helpful for the jira plugin

@dcramer

---

This change is [Reviewable](https://reviewable.io/reviews/getsentry/sentry/4086)

### CODE REVIEW

**Comment by dcramer** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/sentry/api/endpoints/organization_user_issues_search.py, line 21 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/4086#-KR0kARhQp0DhmxjhrIR:-KR0kARhQp0DhmxjhrIS:b2iblub) ([raw file](https://github.com/getsentry/sentry/blob/748f3941b7ae956b7343134dec0db1929a3eb4f5/src/sentry/api/endpoints/organization_user_issues_search.py#L21)):*
> ```Python
>         limit = request.GET.get('limit', 100)
> 
>         team_list = list(request.access.teams)
> ```

fyi this might have issues w/ people who are owners and have a lot of projects they're not a member of (but have access to) like HubSpot

---

*[src/sentry/api/endpoints/organization_user_issues_search.py, line 26 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/4086#-KR0karW-_2rs5tAhff-:-KR0karW-_2rs5tAhff0:b-9bchsa) ([raw file](https://github.com/getsentry/sentry/blob/748f3941b7ae956b7343134dec0db1929a3eb4f5/src/sentry/api/endpoints/organization_user_issues_search.py#L26)):*
> ```Python
>         )
> 
>         event_users = EventUser.objects.filter(email=email,
> ```

one concern in the future is that email is case sensitive in the current index (and because of user input and random behavior the input value might not be the same as whats stored)

We could improve that (if we care) by doing ``email__iexact=email`` and updating the index.

---

*[src/sentry/api/endpoints/organization_user_issues_search.py, line 27 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/4086#-KR0lbidQAOIGGSjKj6s:-KR0lbidQAOIGGSjKj6t:b-csw50j) ([raw file](https://github.com/getsentry/sentry/blob/748f3941b7ae956b7343134dec0db1929a3eb4f5/src/sentry/api/endpoints/organization_user_issues_search.py#L27)):*
> ```Python
> 
>         event_users = EventUser.objects.filter(email=email,
>                                                project_id__in=[p.id for p in projects])
> ```

lets add a limit here (e.g. 1k items)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/4086)*

**Comment by dcramer** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/sentry/api/endpoints/organization_user_issues_search.py, line 21 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/4086#-KR0kARhQp0DhmxjhrIR:-KR0m9K_N_rrMqWRtY_g:b-hv6u9i) ([raw file](https://github.com/getsentry/sentry/blob/748f3941b7ae956b7343134dec0db1929a3eb4f5/src/sentry/api/endpoints/organization_user_issues_search.py#L21)):*
<details><summary><i>Previously, dcramer (David Cramer) wrote…</i></summary>
> fyi this might have issues w/ people who are owners and have a lot of projects they're not a member of (but have access to) like HubSpot
</details>
yeah lets just make this a list of projects they have opted into

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/4086)*

**Comment by macqueen** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/sentry/api/endpoints/organization_user_issues_search.py, line 21 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/4086#-KR0kARhQp0DhmxjhrIR:-KR13bBooFqHKOom8jka:b-896fix) ([raw file](https://github.com/getsentry/sentry/blob/748f3941b7ae956b7343134dec0db1929a3eb4f5/src/sentry/api/endpoints/organization_user_issues_search.py#L21)):*
<details><summary><i>Previously, dcramer (David Cramer) wrote…</i></summary>
> yeah lets just make this a list of projects they have opted into
</details>
Done.

---

*[src/sentry/api/endpoints/organization_user_issues_search.py, line 27 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/4086#-KR0lbidQAOIGGSjKj6s:-KR13cUuUxqvrpOb5x7Y:b-896fix) ([raw file](https://github.com/getsentry/sentry/blob/748f3941b7ae956b7343134dec0db1929a3eb4f5/src/sentry/api/endpoints/organization_user_issues_search.py#L27)):*
<details><summary><i>Previously, dcramer (David Cramer) wrote…</i></summary>
> lets add a limit here (e.g. 1k items)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/4086)*

**Comment by dcramer** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/4086)*

**Pull request merged**
