### PR TITLE
fix(event ui): fixes JAVASCRIPT-2FR

### PR DESCRIPTION
**Pull request by MaxBittker**
this isn't a big impact bug ( curl command is broken in some weird cases ) and I'm not sure what the best solution is because they're a variety of weird object shapes, (not sure why inferredContentType isn't being set)

but opening this to maybe ship as a solution or maybe talk about a better solution, could write a test too

### CODE REVIEW

**Comment by EvanPurkhiser** [comment]
This is related to `multipart/form` data coming. Definitely down for a better solution, but need to think about it a bit.

**Comment by MaxBittker** [comment]
thoughts on merging this to improve the behavior in the meantime?

**Comment by EvanPurkhiser** [comment]
Could you also capture the `inferredContentType`. Then good to merge

**Comment by MaxBittker** [comment]
@EvanPurkhiser re-review?

**Review by evanpurkhiser — APPROVED** [review]

**Pull request merged**
