### PR TITLE
test(ci): Disable widget builder tests to pass CI

### PR DESCRIPTION
**Pull request by dashed**
In case https://github.com/getsentry/sentry/pull/32282 fails too

### CODE REVIEW

**Review by Zylphrex — APPROVED** [review]
🤞

**Comment by priscilawebdev** [comment]
Looks like the CI is still passing... are we still having issues with the frontend tests?

**Review by priscilawebdev — CHANGES_REQUESTED** [review]
please see my comment

**Comment by dashed** [comment]
> Looks like the CI is still passing... are we still having issues with the frontend tests?

@priscilawebdev No issues afaik. We created a bunch of pull requests on the same branch to see if it can pass without it being flaky. Going to close this.

**Pull request closed without merging**
