### PR TITLE
fix(analytics): Log when Google credentials can't be found

### PR DESCRIPTION
**Pull request by mattrobenolt**
This allows process to boot up if there are no credentials passed in

### CODE REVIEW

**Review by mitsuhiko — COMMENTED** [review]
Not that it matters much since we're light on threads but `cached_property` is not threadsafe.

**Comment by mattrobenolt** [comment]
Yeah, I think that's fine. I'm assuming the client itself is threadsafe or we'd have had issues with it already.

The problem this is solving, which I sorta left out, is that because this happens in `__init__` we're unable to build a production artifact without the python process having access to Google credentials. This breaks when we run `sentry django collectstatic` at build time.

The other alternative here is that I just `try..except` and then noop on the `record_event` side?

**Comment by mitsuhiko** [comment]
You could end up creating more than one client. Not sure if the client is stateful but then that would be an issue. Otherwise who cares.

To solve it you can put a mutex into the class and use that stupid double locking pattern in a custom property.

**Comment by mitsuhiko** [comment]
https://github.com/getsentry/rb/blob/51079a223c16a20efe13e9a6b7b7980fe0c8abb3/rb/cluster.py#L154-L173

**Comment by mattrobenolt** [comment]
Yeah, 1 client per thread, you mean? I'm not sure I care enough, but it's definitely a change in behavior.

I think I'll opt for just a try...except and logging it. Then noop in the record_event.

**Comment by mattrobenolt** [comment]
@mitsuhiko I just changed it to try except and log the error instead, which I think frankly makes more sense anyways.

**Review by mitsuhiko — APPROVED** [review]

**Pull request merged**
