### PR TITLE
fix(comments): error state border

### PR DESCRIPTION
**Pull request by Chrissy**
redbox-1
error-2

where's my bonus points @ckj

### CODE REVIEW

**Review by ckj — APPROVED** [review]
You get all the points 👈👇 👉 ☝️ 👆

**Comment by tkaemming** [comment]
whatcha gonna do with all those bonus points @Chrissy

**Comment by Chrissy** [comment]
save em' in my pointy bank.

**Comment by tkaemming** [comment]
dang what kind of rate of return you gettin on those points just sitting in the pointy bank

**Pull request merged**
