### PR TITLE
test(js): Add more fields to Group fixture

### PR DESCRIPTION
**Pull request by billyvg**
So that this more closely matches prod data

### CODE REVIEW

**Review by markstory — APPROVED** [review]

**Review by mitsuhiko — CHANGES_REQUESTED** [review]
can you also add `platform`?

**Comment by mitsuhiko** [comment]
To clarify why see this PR: https://github.com/getsentry/sentry/pull/12757

**Comment by billyvg** [comment]
@mitsuhiko is that going to be different than project platform?

**Comment by mitsuhiko** [comment]
@billyvg: yep. The group platform is the platform of the last event. The project platform is the icon flavour.

**Review by mitsuhiko — APPROVED** [review]

**Pull request merged**
