### PR TITLE
[security] prevent multiple auth payloads

### PR DESCRIPTION
**Pull request by dcramer**
@getsentry/security 

This change is [Reviewable](https://reviewable.io/reviews/getsentry/sentry/4219)

### CODE REVIEW

**Review by mattrobenolt — APPROVED** [review]
Do we maybe wanna log this too so we can see it happening if it does? Or at least metrics. Would be good to know if this is happening. Otherwise. This is simply going to return a 400 or whatever to the client silently.

**Comment by dcramer** [comment]
@mattrobenolt yeah i was thinking about that. I think this would get logged, but it wont have useful metadata. My one concern would be double logging. Thoughts on where these should go? /cc @JTCunning

**Comment by mattrobenolt** [comment]
@dcramer did we still see value in doing this since we "fixed" the original issue? Either way, we should merge or close this then.

**Comment by dcramer** [comment]
I think this is still valid. We can ignore the logging for now if we want.

**Comment by dcramer** [comment]
@mattrobenolt if you wanna land this before I'm back from vaca go ahead

**Review by JTCunning — APPROVED** [review]
I think that since `SuspiciousOperation`s already show up in logging that we're fine enough without adding any extra logging specific bits.

**Pull request merged**
