### PR TITLE
feat(profile-issues): Add profile category/type to search autocomplete

### LINKED ISSUE #44429: Add "issue.category:profile" autocomplete option in issue search
Currently, searching for `issue.category:profile` works as expected, but `profile` doesn't show up in the autocomplete results.

### PR DESCRIPTION
**Pull request by malwilley**
Closes https://github.com/getsentry/sentry/issues/44429

Simple change, just adds some profile issue values to the searchbar autocomplete.

CleanShot 2023-02-13 at 15 13 29

CleanShot 2023-02-13 at 15 13 16

### CODE REVIEW

**Comment by ceorourke** [comment]
Hmmm pretty low risk but profiling issues aren't out yet, should we wait to release this?

**Comment by malwilley** [comment]
> Hmmm pretty low risk but profiling issues aren't out yet, should we wait to release this?

@ceorourke I had the same thought, but we also did this for performance issues before they were ready and it was fine. The search works, just won't return any issues.

**Review by wedamija — COMMENTED** [review]
Could potentially put it behind the `organizations:issue-platform` feature flag?

**Comment by malwilley** [comment]
Required a tiny bit of modification, but now should be hidden behind the issue platform feature flag

**Review by wedamija — APPROVED** [review]
I don't know FE stuff too well, but this seems ok to me

**Pull request merged**
