### PR TITLE
ref(ui) RFC - Use new react JSX transform

### PR DESCRIPTION
**Pull request by markstory**
Now that we're on react 17 we can use the new JSX transform more easily. This applies the `react-codemod` to update/remove imports, as one huge chunk. It is very unlikely that this change will land as is. In order to ship, it can be broken up into a few pieces:

1. Add new babel plugins.
2. Relax eslint rules in our eslint-config.
3. Update smaller slices of the application with the codemod so that we're not dealing with 5K loc diffs.

Before doing that I wanted to gauge how receptive folks would be to this change as a whole.

See https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html for more details on how the new transform works.

### CODE REVIEW

**Comment by billyvg** [comment]
Ship it!

@priscilawebdev had attempted this awhile ago, I *think* most pre-reqs have been satisfied w/ the work @EvanPurkhiser has done (e.g. emotion 11), but maybe she can confirm

**Comment by priscilawebdev** [comment]
yes! I just tested this branch locally and everything seems to be fine! Thank you for doing this @markstory 🙏  Ship it!!!

**Review by priscilawebdev — APPROVED** [review]
Ship it!!

**Comment by markstory** [comment]
Closing this out as these changes will be shipped in smaller parts.

**Pull request closed without merging**
