### PR TITLE
ref(onboarding): Improve Flutter Getting Started Doc

### LINKED ISSUE #78452: Flutter: Simplify and improve onboarding docs

### LINKED ISSUE #78463: Flutter: Simplify and improve onboarding docs
Simplify and improve onboarding docs based on the learnings

### PR DESCRIPTION
**Pull request by priscilawebdev**
**Before**

image

image

**After**

Screenshot 2024-10-02 at 05 13 31
Screenshot 2024-10-02 at 05 14 41

Screenshot 2024-10-02 at 05 16 35

closes https://github.com/getsentry/sentry/issues/78452
closes https://github.com/getsentry/sentry/issues/78463

### CODE REVIEW

**Review by buenaflor — COMMENTED** [review]
nice!

I think we can also replace the tracing verification code with this:

```dart
import 'package:sentry/sentry.dart';

void execute() async {
  final transaction = Sentry.startTransaction('processOrderBatch()', 'task');

  try {
    await processOrderBatch(transaction);
  } catch (exception) {
    transaction.throwable = exception;
    transaction.status = const SpanStatus.internalError();
  } finally {
    await transaction.finish();
  }
}

Future<void> processOrderBatch(ISentrySpan span) async {
  // span operation: task, span description: operation
  final innerSpan = span.startChild('task', description: 'operation');

  try {
    // omitted code
  } catch (exception) {
    innerSpan.throwable = exception;
    innerSpan.status = const SpanStatus.notFound();
  } finally {
    await innerSpan.finish();
  }
}
```

maybe `execute()` should be called differently, up to you

**Review by buenaflor — COMMENTED** [review]
but looks good 👍

**Review by buenaflor — APPROVED** [review]
lgtm! 

maybe @kahest wants to take a quick peek

**Review by kahest — APPROVED** [review]
LGTM, thank you both! 🙏

**Pull request merged**
