### PR TITLE
feat(metrics_indexer) Add a gauge to track the amount of strings looked up per batch

### PR DESCRIPTION
**Pull request by fpacifici**
We do not have a metric on the number of strings we look up per batch. 
This metric would be useful to tune the batch size in a world with a lot more tags per messages.

Adding two of them, one in the consumer (before resolving all the hardcoded strings) and one in the postgres indexer, which only counts what we are trying to resolve from memecache/postgres.

### CODE REVIEW

**Review by evanh — APPROVED** [review]

**Comment by nikhars** [comment]
Will this give you a breakdown of lookups by tag keys and tag values? Does having that breakdown provide any additional insights?

**Comment by fpacifici** [comment]
> Will this give you a breakdown of lookups by tag keys and tag values?

I don't think we can afford that. Such a break down would be equivalent to a break down by project/org, so too high. Worse, it would depend on the cardinality of the tags provided by the customer. Thus that cardinality would impact the cost of recording metrics, without us having control on that.

**Comment by nikhars** [comment]
> > Will this give you a breakdown of lookups by tag keys and tag values?
> 
> I don't think we can afford that. Such a break down would be equivalent to a break down by project/org, so too high. Worse, it would depend on the cardinality of the tags provided by the customer. Thus that cardinality would impact the cost of recording metrics, without us having control on that.

I probably didn't make my point clear. Here's a second attempt. The indexer does lookups for tag keys and tag values. Should we have a metric for how many string to int lookups were done for tag keys? Similarly do we care about how many string to int lookups were done for tag values? So we don't need metric breakdown for individual tags but breakdown by the puspose of lookup.

**Comment by fpacifici** [comment]
Sorry I did not see your comment before merging. 
That would be possible. Not sure it will be that critical though. We know that the number of strings is largely dominated by values. As of now we do not even have custom tags. Tag keys are hardcoded, you do not even hit the cache for them. 
For the performance project we may have custom tags, still they will be dwarfed by the amount of values we need to resolve.

**Pull request merged**
