### PR TITLE
types.py: long was removed in Python 3

### PR DESCRIPTION
**Pull request by cclauss**
Detected via #14906

### CODE REVIEW

**Comment by cclauss** [comment]
__Access Denied__ when I attempt to view the Percy output and the Travis CI failure in Frontend is unclear to me.

**Comment by wedamija** [comment]
@joshuarli Did you have a fix for this in a separate pr?

**Comment by joshuarli** [comment]
I might have fixed it in my hackweek python3 branch, but that wasn't done in a 2.7-compatible manner.

**Review by wedamija — APPROVED** [review]
Thanks @cclauss, looks good

**Pull request merged**
