### PR TITLE
fix itunes url

### PR DESCRIPTION
**Pull request by wwwjfy**
use https instead of http, otherwise the status code would be 301

### CODE REVIEW

**Comment by mitsuhiko** [comment]
That is interesting. Is the URL enforcing HTTPS for you? It responds at unencrypted HTTP for me.

**Comment by mattrobenolt** [comment]
> It responds at unencrypted HTTP for me.

Same, I don't get a 301.

So I'd just suggest two things here:

* We probably should just do this over TLS unless there was a reason not to that I'm unaware of.
* Remove the "allow_redirects" since we explicitly don't want that.

**Comment by mitsuhiko** [comment]
There is no particular reason it's not using HTTPs but redirects are off intentionally. The main reason this is currently not using HTTPS is that we do an HTTP request on every dsym upload and I figured since there is no security concern here I doing it over HTTP cuts down on waiting time a bit.

**Comment by wwwjfy** [comment]
It returns 301 in China, while an HTTP request from a US server works fine.

```
curl -v 'http://itunes.apple.com/lookup/?bundleId=cn.12dong.mojigo'
*   Trying 111.161.121.27...
* TCP_NODELAY set
* Connected to itunes.apple.com (111.161.121.27) port 80 (#0)
> GET /lookup/?bundleId=cn.12dong.mojigo HTTP/1.1
> Host: itunes.apple.com
> User-Agent: curl/7.54.0
> Accept: */*
>
* HTTP 1.0, assume close after body
< HTTP/1.0 301 Moved Permanently
< Server: Cdn Cache Server V2.0
< Date: Wed, 03 May 2017 01:02:05 GMT
< Content-Length: 0
< Location: https://itunes.apple.com/lookup/?bundleId=cn.12dong.mojigo
<
```

I added `allow_redirects` just in case Apple changes it later, but we can update it manually anyway, so I 've removed it.

Is the concern of `allow_redirects` about security reasons?

**Review by mitsuhiko — APPROVED** [review]

**Pull request merged**
