### PR TITLE
fix(apm): Fix locale for inline errors on the span view

### PR DESCRIPTION
**Pull request by dashed**
Address this error:

Screen Shot 2020-04-22 at 7 10 33 PM

### CODE REVIEW

**Review by billyvg — APPROVED** [review]
Did linter not pick this up?

**Comment by dashed** [comment]
This is a runtime error. Is the linter capable of detecting this?

**Comment by billyvg** [comment]
Hmmm yeah, https://github.com/getsentry/eslint-config-sentry/blob/master/packages/eslint-plugin-sentry/lib/rules/no-digits-in-tn.js

**Comment by dashed** [comment]
@billyvg oh hmm... that never tripped for me.

**Comment by billyvg** [comment]
@matejminar any ideas?

**Pull request merged**
