### PR TITLE
Cache static files by default

### PR DESCRIPTION
**Pull request by mattrobenolt**
- Add in the `{version}` key to `STATIC_URL` by default so assets get a version.
- Make sure `/_static/` requests don't get a `Vary` header.
- Set a long lived `Cache-Control` header if we see a versioned request.
- Packages up static version with sdist for distribution.

### CODE REVIEW

**Comment by dcramer** [comment]
The issue with this change is it backwards incompatible if anyone setup nginx rules. We can do it but we should document the issue.

**Comment by mattrobenolt** [comment]
Oh, because people are serving the static files explicitly via nginx?

Our documentation doesn't explain this, so people would have to have done this on their own. At least I don't see it documented here: https://docs.getsentry.com/on-premise/server/nginx/

Unless there's somewhere else I'm missing.

**Comment by dcramer** [comment]
Yea it's not a default. I don't have stats on the number of people who have done it either. Might be just a handful. 






On Mon, Jan 4, 2016 at 8:40 PM -0800, "Matt Robenolt" <notifications@github.com> wrote:












Oh, because people are serving the static files explicitly via nginx?



Our documentation doesn't explain this, so people would have to have done this on their own. At least I don't see it documented here: https://docs.getsentry.com/on-premise/server/nginx/



Unless there's somewhere else I'm missing.

**Comment by mattrobenolt** [comment]
I'll add this then into the CHANGELOG for 8.0, since that's the only place this really seems relevant. Someone would had to have gone above and beyond our documentation.

Seem reasonable?

**Comment by dcramer** [comment]
Yep






On Mon, Jan 4, 2016 at 8:43 PM -0800, "Matt Robenolt" <notifications@github.com> wrote:












I'll add this then into the CHANGELOG for 8.0, since that's the only place this really seems relevant. Someone would had to have gone above and beyond our documentation.



Seem reasonable?

**Pull request merged**
