### PR TITLE
feat(ui): Add exact count in title for `<Count>`

### LINKED ISSUE #2101: Expose an exact error count in UI
Re: https://sentry.zendesk.com/agent/tickets/598

Not sure if we want to use a real tooltip or just a `title` attribute here, but it's probably worth exposing IMO.

Right now, we generalize at a very high level of "1.1M" without any way to see what the absolute number is.

### PR DESCRIPTION
**Pull request by infinityxxx**
Closes #2101

### CODE REVIEW

**Comment by infinityxxx** [comment]
@billyvg will you have time to review before hacktober ends? let me know if there is anything I can do.

**Comment by billyvg** [comment]
@infinityxxx yeah, there seems to be some lint errors, can you run eslint with --fix?

**Comment by infinityxxx** [comment]
@billyvg linter issue is fixed

**Comment by billyvg** [comment]
@infinityxxx Thanks!

Can you also rebase with latest `getsentry:master`? We just merged in a fix for our CI so that `Visual Snapshot` can run for forks.

**Review by billyvg — APPROVED** [review]
I think this should be ok, it takes a bit to pop-up:

image

Because `value` can be passed a string, the title does not always get formatted with `toLocaleString()` as a Number

**Comment by billyvg** [comment]
Thanks @infinityxxx!

**Pull request merged**
