### PR TITLE
Discover: Fix Capitalization in Sidebar

### PR DESCRIPTION
**Pull request by ayesha-omarali**
fixes: 
image

### CODE REVIEW

**Review by lynnagara — APPROVED** [review]

**Comment by benvinegar** [comment]
Our prior art here might be to capitalize both, e.g. what do we do for User Feedback?

**Comment by ayesha-omarali** [comment]
@benvinegar, @eurica wanted this casing. We use pretty mixed casing throughout the site. 
I think the most prominent are the "Select a project" and the header's "All Projects" and "All Events"

**Comment by eurica** [comment]
It's a tough one. On the page I see lower case winning over upper case

Upper cased:

- All Projects
- Line by Day
- Bar by Day

Lower cased:

- Last 14 days (although Absolute Date is capitalized)
- Assigned to me
- Bookmarked isses
- Recently viewed
- What's new
- Organization settings
- Switch organization
- User settings
- API keys
- Sign out

**Comment by lynnagara** [comment]
Yeah, we're pretty inconsistent. On the issue page (I think what Ben is referring to) upper case does win out. Fwiw I'm not a fan of title-style case when it's not actually a page title

**Comment by benvinegar** [comment]
Damn, I didn't realize we were all over the place. Welp ... _backs away slowly_

**Comment by ayesha-omarali** [comment]
Going to leave it as is (since it isn't a page title) unless anyone objects?

**Pull request merged**
