### PR TITLE
build(plugins): Include all files under sentry_plugins in the wheel

### LINKED ISSUE #18612: Template file for Teamwork plugin does not get inside docker image
## Important Details

How are you running Sentry?

On-Premise w/ Docker, version Sentry 10.1.0.dev06e9f429

## Description

Teamwork integration is missing the create_issue.html template file.

sentry_plugins/teamwork/templates/sentry_teamwork/create_issue.html is missing.

You can look inside the web docker image in /usr/local/lib/python2.7/site-packages/sentry_plugins/teamwork/ and the templates folder is missing.

## Steps to Reproduce

1. Enable integration with Teamwork
2. Try to create a new Teamwork task from a Sentry issue
3. Getting an error page

image

Log is showing this error: TemplateDoesNotExist: sentry_teamwork/create_issue.html (9 additional frame(s) were not displayed) ... File "sentry/web/frontend/group_plugin_action.py", line 25, in handle

### What you expected to happen

Manually copying the missing templates folder into the docker container fix the problem.
I'm getting the Create Teamwork Task page.

image

### Possible Solution

I don't know much about python packaging, something is excluding that packages/sentry_plugins/teamwork/templates/ folder when packaging the .whl file.

### PR DESCRIPTION
**Pull request by BYK**
Fixes #18612.

### CODE REVIEW

**Comment by BYK** [comment]
@mattrobenolt - shall we add other folders under `src` too? (such as `bitfield` etc.)

**Comment by mattrobenolt** [comment]
If there are files we need, yeah. I don't know.

**Comment by BYK** [comment]
Just verified that this fixes #18612:
```shell
root@166415a31c4a:/# ls /usr/local/lib/python3.6/site-packages/sentry_plugins/teamwork/templates/sentry_teamwork/
create_issue.html
```

**Comment by BYK** [comment]
>If there are files we need, yeah. I don't know.

Only some PO/MO files under social_auth. Will add that too.

**Review by untitaker — APPROVED** [review]

**Pull request merged**
