### PR TITLE
ref(sampling): Open uniform rule modal via url - [TET-430]

### PR DESCRIPTION
**Pull request by priscilawebdev**
**What this PR does:**

- Add the new route `/rules/:rule/` to the `routes.tsx` file. This will be used to open the UniformSampleRateModal according to the URL
- Update `serverSideSampling` component to open the modal if the url contains `/rules/new` or `/rules/:ruleId`

**Preview:**

https://user-images.githubusercontent.com/29228205/193546734-540a2a3b-2905-43d8-a748-a2767d6b8fc6.mov

### CODE REVIEW

**Review by matejminar — COMMENTED** [review]
> Note: now it doesn't open the already created rule (edit mode) via URL, but this can be done in a follow-up

That's a key functionality, if possible, let's try to fix that and only merge then 🙏

**Comment by priscilawebdev** [comment]
@matejminar I updated the code 😉

**Review by matejminar — APPROVED** [review]
Can we prevent the distribution/sdk-versions from reloading when opening/closing the modal?
https://user-images.githubusercontent.com/9060071/193597000-9dc6fa71-7642-4098-abc0-2736f3994bde.mp4

Looks like the visual snapshot did not open a modal - is that a flake or genuine concern?

Otherwise, lgtm.

**Comment by priscilawebdev** [comment]
@matejminar yes I was going to address this issue in a follow-up PR... In fact, what I need is to use the code that I had as an experiment in the PR https://github.com/getsentry/sentry/pull/39330

**Comment by priscilawebdev** [comment]
@matejminar about the snapshot, I am not sure why it was not loading everything, but it shouldn't open the modal. I have moved the `expect(container).toSnapshot();` to the bottom of the code, so lets see if it fixes the issue

**Comment by priscilawebdev** [comment]
@matejminar I am not sure why the visual snapshots are not loading everything, but about the Modal...it shouldn't be in the snapshot as we are performing this act before opening the modal 😉

**Comment by priscilawebdev** [comment]
> Can we prevent the distribution/sdk-versions from reloading when opening/closing the modal?

@matejminar I've addressed this issue in my last commit https://github.com/getsentry/sentry/pull/39508/commits/6fb62ed715f697c83aa2a53a00ef15c014a03d6b

**Pull request merged**
