### PR TITLE
ref: Swap Raven out for the new Python SDK

### PR DESCRIPTION
**Pull request by untitaker**
Deploying this is **blocked** on https://github.com/getsentry/getsentry/pull/2237

### CODE REVIEW

**Comment by mitsuhiko** [comment]
@mattrobenolt I really want to get this out sooner or later because dogfooding SDKs is important. I don't have too many concerns but I cannot 100% guarantee that we will hit all the same groups. I would love to see how this goes on a single worker and see if we get too many new groups that way.

**Comment by mattrobenolt** [comment]
I mean, the only way to really do that is to either coordinate with @JTCunning, or put all of this behind some switch, so we can toggle it on/off on a single server.

**Comment by untitaker** [comment]
I can write that switch but would like confirmation from @JTCunning that it's necessary for partial rollout

**Comment by JTCunning** [comment]
We don't need a switch. Matt was saying it's either choice. We can run a one-off. Just link me to the Freight staging deploy that has this commit included and I'll run a single worker on it.

**Comment by JTCunning** [comment]
We don't need a switch. Matt was saying it's either choice. We can run a one-off. Just link me to the Freight staging deploy that has this commit included and I'll run a single worker on it.

**Comment by untitaker** [comment]
I mean, whatever is easier to do on your side and doesn't block other's deploys too much. I'm fine with either.

**Comment by JTCunning** [comment]
If you want something to run for an hour or so, we can run a one-off. If you want more than thst, implement an environment variable switch. They are both minimal effort on my part and should not be taken into consideration.

**Review by mitsuhiko — APPROVED** [review]

**Pull request merged**
