### PR TITLE
feat(sampling): Remove user segment condition [TET-276]

### PR DESCRIPTION
**Pull request by matejminar**
We won't be supporting the user segment condition on day 1.

Requires https://github.com/getsentry/sentry/pull/37172

### CODE REVIEW

**Review by priscilawebdev — APPROVED** [review]
do we need to update the tests too?

**Comment by andriisoldatenko** [comment]
@matejminar what about:

`pt "SamplingInnerName.TRACE_USER_SEGMENT"`

```
./static/app/types/sampling.tsx
114:    | SamplingInnerName.TRACE_USER_SEGMENT;
```

**Comment by matejminar** [comment]
@priscilawebdev yep, I just had to separate the frontend and backend PR. I pushed the backend one and linked it in the desc.

@andriisoldatenko for some reason we are leaving all the old conditions there so I just kept it consistent. I agree that we should clean that type. We can tackle that in a follow-up PR.

**Comment by priscilawebdev** [comment]
@matejminar yes I think we can remove those types :)

**Pull request merged**
