### PR TITLE
ref(ui): Normalize import paths

### PR DESCRIPTION
**Pull request by evanpurkhiser**
Always use ./views over app/views

### CODE REVIEW

**Review by billyvg — COMMENTED** [review]
Is this an improvement? What if we were to refactor out e.g. org/project settings routes elsewhere?

**Comment by EvanPurkhiser** [comment]
I can do it the other way if we want, so that they are all absolute. It's just inconsistent right now is all.

**Comment by billyvg** [comment]
I think absolute would be better, thoughts?

**Comment by EvanPurkhiser** [comment]
Yeah I think I agree

**Review by billyvg — APPROVED** [review]

**Comment by EvanPurkhiser** [comment]
Oops, merged with the wrong message body. 🤷‍♂

**Pull request merged**
