### PR TITLE
feat(discover): Replace GSH with page filters

### PR DESCRIPTION
**Pull request by davidenwang**
Before:
Screen Shot 2022-04-12 at 2 59 34 PM

After:
image

### CODE REVIEW

**Comment by silent1mezzo** [comment]
The small query bar is going to be challenging. It already gets cramped and losing half the width isn't great.

**Review by silent1mezzo — CHANGES_REQUESTED** [review]
The small query bar is going to be challenging. It already gets cramped and losing half the width doesn't make that any easier. We're saying that these filters are as important as the discover query (maybe even more important since they're on the left).

**Comment by davidenwang** [comment]
> The small query bar is going to be challenging. It already gets cramped and losing half the width doesn't make that any easier. We're saying that these filters are as important as the discover query (maybe even more important since they're on the left).

mmm gotcha, I can go ahead and put the page filters on its own row in that case

**Review by evanpurkhiser — APPROVED** [review]

**Review by silent1mezzo — APPROVED** [review]
Looks good to test out 👍

**Pull request merged**
