### PR TITLE
fix: Don't try and truncate Nones

### PR DESCRIPTION
**Pull request by alex-hofsteede**
fixes SENTRY-3Q0

### CODE REVIEW

**Review by mattrobenolt — APPROVED** [review]
Not a huge deal, but seems like something really easy to unittest this truncatechars function if we're not already.

**Review by mitsuhiko — CHANGES_REQUESTED** [review]
Mind if we just do an explicit check for `None` at the start of the function instead?

**Comment by mitsuhiko** [comment]
(Reason for the None check is that it's not clear for the reader why there is an instance check on strings for a function that is supposed to be getting strings)

**Comment by alex-hofsteede** [comment]
@mitsuhiko sure.

There would still be one little edge case that will throw an en exception though, if `value` is a dict, it will pass the `len()` check but throw when you try and do `value[:x]` on it. I'm not sure of all the places this function is used and whether getting a dict is even a possibility?

**Comment by alex-hofsteede** [comment]
@mitsuhiko done

**Review by mitsuhiko — APPROVED** [review]

**Comment by mitsuhiko** [comment]
@alex-hofsteede in that case i'm perfectly happy with it blowing up for now. Longer term we can reject such things on a strong schema.

**Pull request merged**
