### PR TITLE
fix(ui): Shrink PanelTable header in project stats page

### PR DESCRIPTION
**Pull request by EricHasegawa**
Shrinks down the PanelTable header to be exactly 45px

### CODE REVIEW

**Review by cathteng — APPROVED** [review]
is this the correct PR title? also can you add a picture

**Comment by scttcper** [comment]
hmmm this is used in a lot of places

**Review by scttcper — CHANGES_REQUESTED** [review]
I would say to find another way to do this

**Comment by EricHasegawa** [comment]
> is this the correct PR title? also can you add a picture
My fault on the title - auto populated from a different change
Screenshot 2023-06-21 at 3 42 26 PM

**Review by scttcper — APPROVED** [review]
yee

**Pull request merged**
