### PR TITLE
feat(discover): Add visualization to query string

### PR DESCRIPTION
**Pull request by lynnagara**
Discover visualization type can be defined via the URL, visualization
name persists when switching Discover tabs.

### CODE REVIEW

**Comment by billyvg** [comment]
Query string keeps changing (I think when you navigate with browser history with `query` it sorts params alphabetically it looks like).

https://cl.ly/5d039d85644f/download/Screen%20Recording%202019-01-10%20at%2001.12%20PM.gif

**Comment by billyvg** [comment]
Looks like it's this? https://github.com/getsentry/sentry/blob/master/src/sentry/static/sentry/app/views/organizationDiscover/discover.jsx#L253

**Comment by lynnagara** [comment]
Yeah, i'm starting to think we should always sort so react router works properly

**Comment by billyvg** [comment]
Is there a reason not to use `query` instead of `search`?

**Comment by lynnagara** [comment]
Not that I know of, it's inconsistently used in discover right now. I did a quick fix but it might not be the best solution

**Comment by lynnagara** [comment]
Some of the formats used presently might not be very compatible with how `query` stringifies things

**Comment by billyvg** [comment]
The query string still causes some issues if it has parens (e.g. count aggregation)

**Comment by lynnagara** [comment]
Damn, tried to fix this by passing it through the original function again. Another option would be to switch everything to use `query` but in the interests of wanting to keep the URL unchanged just went with this

**Comment by lynnagara** [comment]
@billyvg How do you feel about merging this?

**Review by billyvg — APPROVED** [review]
@lynnagara 	The query string is still switching because of the parens, but since it's not any worse than what's currently on prod, I'd say it's still a net win if we merged.

**Pull request merged**
