### PR TITLE
build(github-actions): RIP github actions

### PR DESCRIPTION
**Pull request by billyvg**
👻

### CODE REVIEW

**Review by evanpurkhiser — APPROVED** [review]

**Comment by dashed** [comment]
⚰️

**Comment by dashed** [comment]
I don't even want to approve it because I don't want it to go.

**Comment by Smolevich** [comment]
Do you have plans on using GIthub Actions for this ci [plan](https://github.com/getsentry/sentry/blob/master/.travis.yml) in future? I can help and prepare PR

**Comment by untitaker** [comment]
@Smolevich no such plans. Main reason is pricing from what I know.

**Comment by untitaker** [comment]
@Smolevich No plans in the near future :)

**Pull request merged**
