### PR TITLE
ref(rate limits): Move settings out of sentry

### PR DESCRIPTION
**Pull request by ceorourke**
Move rate limit settings out of sentry and into getsentry so that on prem customers aren't affected by them. 

Requires https://github.com/getsentry/getsentry/pull/7350 to be merged first

#sync-getsentry

### CODE REVIEW

**Review by AniketDas-Tekky — COMMENTED** [review]
Add a test to make sure everything works if it is self hosted

**Review by AniketDas-Tekky — COMMENTED** [review]
LGTM. Try this on staging and then I'll approve

**Review by AniketDas-Tekky — APPROVED** [review]

**Comment by AniketDas-Tekky** [comment]
Approved for staging deploy, not for merge

**Comment by ceorourke** [comment]
I deployed this on staging and hit the `EventIdLookupEndpoint` in the browser to make sure it was still rate limited (it has a 1 request / 1 second limit):

Screen Shot 2022-04-21 at 4 17 23 PM

though I don't know why the script I had set up was consistently getting 401s :( this makes me feel good about deploying this change to production.

**Pull request merged**
