### PR TITLE
ref: better better SENTRY_SCREENSHOT

### PR DESCRIPTION
**Pull request by joshuarli**
Follow up to https://github.com/getsentry/sentry/pull/21484, just a dedent. Should have done this after noticing https://github.com/getsentry/sentry/pull/21484#issuecomment-714740083.

### CODE REVIEW

**Comment by billyvg** [comment]
Can we do this in a way that keeps desktop screenshots first? That way it will minimize the number of windows resizes we have to do

**Comment by joshuarli** [comment]
```
VISUAL_SNAPSHOT_ENABLE=1 pytest -s -k test_list tests/acceptance/test_organization_releases.py
...
mobile 1st: 0.6123337745666504
full 2nd: 0.7262599468231201
```

```
full 1st: 0.7364819049835205
mobile 2nd: 0.5933198928833008
```

No significant difference. Also I ran a few times to stabilize timings (cpu cache blah blah).

**Comment by joshuarli** [comment]
Could do more rigorous testing but I think that's reason enough.

**Comment by joshuarli** [comment]
Wait, same visual snapshot diff weirdness. 🤔

**Comment by billyvg** [comment]
@joshuarli :/ yeah that is probably due to the resizing -- doesn't seem to happen in prod though

**Comment by joshuarli** [comment]
Ehh, just going to close this one.

**Pull request closed without merging**
