### PR TITLE
feat(ci): Support skipping of jobs

### PR DESCRIPTION
**Pull request by armenzg**
Until now we have used skipping of steps in a job as a way of reducing CI usage when certain jobs should not be triggered depending on the files being touched.

Now that #33455 has been merged, we have some jobs that depend on all the backend/frontend required jobs. Once we make the frontend and backend jobs required checks, we can remove all the jobs they depend on, thus, we can now skip them.

This change will make the number of jobs executed on PRs or pushes on master variable since it depends on the files being touched.

### CODE REVIEW

**Comment by armenzg** [comment]
I'm getting the approval but I will not update the required checks and merge this until tomorrow.

**Review by billyvg — APPROVED** [review]
Can we wait until thurs/fri to change the required checks? It'll give folks a bit more time to get their PRs rebased or merged.

**Comment by armenzg** [comment]
> Can we wait until thurs/fri to change the required checks? It'll give folks a bit more time to get their PRs rebased or merged.

I will be away on Friday. Let's aim for Thursday.

**Comment by armenzg** [comment]
I will wait to land this on Tuesday.

**Pull request merged**
