### PR TITLE
ref: Disable flaky test_existing_group_different_category

### PR DESCRIPTION
**Pull request by armenzg**

### CODE REVIEW

**Review by leeandher — APPROVED** [review]

**Review by ceorourke — COMMENTED** [review]
Oh I think this is just because @gggritso removed the `PERFORMANCE_N_PLUS_ONE` `GroupType`. I think you can just swap that out on line 108 for `PERFORMANCE_N_PLUS_ONE_DB_QUERIES` and this shouldn't flake anymore.

**Comment by armenzg** [comment]
> Oh I think this is just because @gggritso removed the `PERFORMANCE_N_PLUS_ONE` `GroupType`. I think you can just swap that out on line 108 for `PERFORMANCE_N_PLUS_ONE_DB_QUERIES` and this shouldn't flake anymore.

Thanks @ceorourke !

It's the end of my day. I will leave it to others to handle.

**Comment by ceorourke** [comment]
> > Oh I think this is just because @gggritso removed the `PERFORMANCE_N_PLUS_ONE` `GroupType`. I think you can just swap that out on line 108 for `PERFORMANCE_N_PLUS_ONE_DB_QUERIES` and this shouldn't flake anymore.
> 
> Thanks @ceorourke !
> 
> It's the end of my day. I will leave it to others to handle.

No problem, I'll open a separate PR to handle it.

**Review by davidenwang — APPROVED** [review]

**Comment by gggritso** [comment]
Sorry and thank you! I think PR that added that test was opened before I started removing that detector, and merged after I got done removing it! I removed the constant in https://github.com/getsentry/sentry/pull/42226, and the test was added https://github.com/getsentry/sentry/pull/42183 so I think this one is less flaky than fully broken 😅

**Pull request merged**
