### PR TITLE
feat(replays): Warn on duplicate segment ingestion and remove attachment

### PR DESCRIPTION
**Pull request by cmanallen**
closes: https://github.com/getsentry/replay-backend/issues/256

### CODE REVIEW

**Review by bruno-garcia — APPROVED** [review]
We don't need to get alerted/act on each of these, and don't need the payload for a repro? 
Then LGTM

**Review by JoshFerge — COMMENTED** [review]
this won't send a sentry warning right? i'd be in favor of removing the sentry stuff and just logging it or using a metric instead -- since we aren't using that scope here anymore

**Comment by cmanallen** [comment]
@bruno-garcia Nah.  We did at one point but its outlived its useful life.  Duplicate payloads are expected.  It depends on the number.

**Review by JoshFerge — COMMENTED** [review]
@cmanallen thanks! could wee add the replay_id and project_id to the log so we can debug in future if needed? should be able to add in info dict in log

**Comment by cmanallen** [comment]
@JoshFerge Done.

**Review by JoshFerge — APPROVED** [review]

**Pull request merged**
