### PR TITLE
use a less literal translation

### PR DESCRIPTION
**Pull request by greg0ire**

### CODE REVIEW

**Comment by dcramer** [comment]
@greg0ire we use Transifex for localization (and don't have a good way in place to accept translations). If you want to setup an account there you can contribute to the French localization.

**Comment by greg0ire** [comment]
I just did. Can you accept me ?

**Comment by dcramer** [comment]
@greg0ire either someone beat me to it or I dont see the request

**Comment by greg0ire** [comment]
Looks like someone beat you to it :)

**Comment by greg0ire** [comment]
I made my change, but I am not sure if I need to commit or validate anything

**Comment by dcramer** [comment]
@greg0ire we auto accept generally on Transifex, so once you submit it you should be ok. We regularly update the locale (sync repo from transifex) so when that happens next it'll get in.

**Comment by greg0ire** [comment]
okay thanks!

**Pull request closed without merging**
