### PR TITLE
fix(issues): getsentry/self-hosted#1672 next button redirection

### PR DESCRIPTION
**Pull request by victorelec14**
the next button redirects you to a url that is wrong because a slash was missing in the url.

In the following lines of code it looks like it is well written.

Thanks

Related Issue: https://github.com/getsentry/self-hosted/issues/1672

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Review by armenzg — APPROVED** [review]
Thanks @victorelec14 !

Let me rebase and see if the checks pass then.

**Comment by victorelec14** [comment]
Activity to not automatically close the ticket :)

@ceorourke can be merged ?

**Comment by armenzg** [comment]
Let's say Yes and rectify later if need be.

**Pull request merged**
