### PR TITLE
build(stylelint): Upgrade to stylelint@10.1.0

### PR DESCRIPTION
**Pull request by billyvg**
This upgrades stylelint to the latest version ~and fix our stylelint to use the `css-in-js` syntax, allowing us to not need the explicit disabling of `no-duplicate-selectors`~

### CODE REVIEW

**Comment by billyvg** [comment]
Hmm I can't seem to get stylelint to fail.

**Comment by billyvg** [comment]
Seems like this is broken because of `babel.config.js`? /cc https://github.com/stylelint/stylelint/issues/4018

**Review by markstory — APPROVED** [review]
Looks good. We've added a few duplicate transitive dependencies around babel. It would be good to get those lined up if possible.

**Comment by billyvg** [comment]
> Looks good. We've added a few duplicate transitive dependencies around babel. It would be good to get those lined up if possible.

Will do

**Pull request merged**
