### PR TITLE
ref(hybrid-cloud): Extract actor constraints into a new migration

### PR DESCRIPTION
**Pull request by mikejihbe**
This will allow them to be run separately from the backfill and comply with Ops team constraints.

### CODE REVIEW

**Review by wedamija — APPROVED** [review]

**Comment by mikejihbe** [comment]
we should trash this changeset and replace it with 2 migrations, one with the backfill logic and another for adding the indexes/constraints in an idempotent fashion with handrolled sql

**Comment by corps** [comment]
Let me get this https://github.com/getsentry/sentry/pull/47096 in then I'll update this one.

**Comment by corps** [comment]
Fixes coming

**Comment by corps** [comment]
I'm closing this PR to take a slightly different approach in follow up PRs

**Pull request closed without merging**
