### PR TITLE
fix(profiling): add flutter and dart-flutter to profiling onboarding

### LINKED ISSUE #59198: Add Flutter profiling to onboarding
### Problem Statement

Based on https://github.com/getsentry/sentry/issues/54093, add Profiling to Flutter (currently in alpha and only available for iOS and macOS).

See:
* https://github.com/getsentry/sentry-dart/pull/1611
* https://github.com/getsentry/sentry-docs/pull/8363

### Solution Brainstorm

_No response_

### Product Area

Profiling

### PR DESCRIPTION
**Pull request by JonasBa**
Resolves: https://github.com/getsentry/sentry/issues/59198

### CODE REVIEW

**Comment by Zylphrex** [comment]
This will enable it for all flutter projects when we only support it for cocoa for now right?

**Comment by bruno-garcia** [comment]
> This will enable it for all flutter projects when we only support it for cocoa for now right?

It's still a single Flutter project for all OS's. Mac and iOS builds will generate profiles, the rest won't (could be Windows, Android and Web).

**Comment by bruno-garcia** [comment]
Wizard PR: https://github.com/getsentry/sentry-docs/pull/8446

**Comment by JonasBa** [comment]
@bruno-garcia this is now ready, just need a review!

**Review by bruno-garcia — APPROVED** [review]

**Comment by bruno-garcia** [comment]
@JonasBa RSLGTM!

**Pull request merged**
