### PR TITLE
feat(replay): Use `<ObjectInspector>` for breadcrumbs

### PR DESCRIPTION
**Pull request by billyvg**
Adds object inspection to Replay breadcrumbs.

Before:
image

After:
image

### CODE REVIEW

**Comment by Jesse-Box** [comment]
@billyvg how difficult would it be to wrap this object component in a styled box which matches the code block used for breadcrumb events like UI click?

It would be great to use Roboto Mono as well

**Comment by billyvg** [comment]
@Jesse-Box styling it is a bit annoying but not impossible, we basically need to define a theme for it:

image

**Comment by billyvg** [comment]
Updated font

**Comment by Jesse-Box** [comment]
> @Jesse-Box styling it is a bit annoying but not impossible, we basically need to define a theme for it:
> 
> image

oh, yeah, OK this will require some a bit more time. I'll write a separate ticket for this.

**Review by Jesse-Box — APPROVED** [review]

**Review by eliashussary — APPROVED** [review]

**Pull request merged**
