### PR TITLE
upgrade: force postcss-svgo to >=5.0.0

### PR DESCRIPTION
**Pull request by BYK**
This should resolve the security warning we keep getting on `is-svg`.

### CODE REVIEW

**Comment by EvanPurkhiser** [comment]
What package is holding it back?

**Comment by BYK** [comment]
@EvanPurkhiser this is what Dependabot says:

image

**Comment by BYK** [comment]
Gonna close this out and will just force `is-svg` instead as its breaking change is dropping node 6 support.

**Comment by BYK** [comment]
https://github.com/getsentry/sentry/pull/25295

**Pull request closed without merging**
