### PR TITLE
fix(stats): Allow org owner to see all teams in dropdown

### LINKED ISSUE #58774: Owners are not able to view stats for teams that they are not a part of
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Go to the `stats/issues` page as an owner.

By looking at the [code](https://github.com/getsentry/sentry/blob/7bb213df90a03a982865916fcad1e0dbc18e2d35/static/app/views/organizationStats/teamInsights/controls.tsx#L133), it seems to me that we are just checking whether the user is either a super user or returning the teams that they are only a part of

### Expected Result

As an organization owner, I would expect to be able to select and see the stats for ALL the teams within my org, even if I am not part of that team

### Actual Result

As an owner, I am only able to select teams I am a part of in the dropdown

### Product Area

Issues

### Link

https://demo.sentry.io/stats/issues/

### DSN

_No response_

### Version

_No response_

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1968) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by schew2381**
### Video w/ Before + After (fix is applied halfway through video)

https://github.com/getsentry/sentry/assets/67301797/0add80e4-054c-4d35-9cc7-ff1037276fa8

Closes https://github.com/getsentry/sentry/issues/58774

### CODE REVIEW

**Review by cathteng — APPROVED** [review]
should we also remove the team filter if the org has open membership? just a thought -- i'm also not sure if this is consistent elsewhere

**Comment by schew2381** [comment]
> should we also remove the team filter if the org has open membership? just a thought -- i'm also not sure if this is consistent elsewhere

Hmm on first thought I think if open membership was on, I'd still rather only be able to see my own teams for convenience

**Comment by cathteng** [comment]
@schew2381 yeah that's where i was going too

**Comment by DavidCain** [comment]
Thanks so much for this PR! Does still seem to have a bug for me.

I can make an effort to dig through the API calls & try to debug what's going on, but what I'm seeing as an org owner:
- All teams are available for selection in the "Team:" widget on `https://<subdomain>.sentry.io/stats/issues/`
- If you select any team but your own, the widget instead defaults to a team you're on
- The URL itself changes (to append `?team=<int-id>`), but no state changes occur

**Comment by schew2381** [comment]
@DavidCain 
Hey so sorry about the bug, I can't believe I didn't click into one of the teams when I was testing 🤦
I figured out the bug and will link another PR to this

**Pull request merged**
