### PR TITLE
Bust Symbolicator `list_files` cache on uploads

### PR DESCRIPTION
**Pull request by Swatinem**
By attaching a random querystring parameter to the Sentry internal source, this will cause a cache miss in Symbolicators `list_files` cache, thus fetching and discovering the uploaded debug file immediately.

This is very similar to `bump_reprocessing_revision`, except it has a TTL. Also the code for `bump_reprocessing_revision` is overly complex for reasons I don’t understand so I don’t want to touch that.

I tested this with a local symbolicator that has caching turned on, see this comment:
https://github.com/getsentry/sentry/blob/3eae8087c6096c80aa64240e43bed670b3dfb6c5/tests/symbolicator/test_minidump_full.py#L156-L160

### CODE REVIEW

**Comment by loewenheim** [comment]
Does the altered URL have any effect on how e.g. object candidates are displayed? Or in other words, is this URL visible to users anywhere?

**Comment by Swatinem** [comment]
> Does the altered URL have any effect on how e.g. object candidates are displayed? Or in other words, is this URL visible to users anywhere?

I double-checked, and the URL is never exposed to users, and also not used for caching of downloaded files, but just for caching of `list_files` requests.

Downloaded file caches and candidates are only using the `uri` which is pretty much a constructed string containing the `file_id`.

**Comment by loewenheim** [comment]
Nice. Then I would just like to request comments somewhere in the code explaining what this query parameter is for, so that we can still understand this in a few years 😅

**Review by loewenheim — APPROVED** [review]

**Comment by Swatinem** [comment]
Reverting because the PR hardcodes the `"default"` redis cluster which fails on deploys

**Pull request merged**
