### PR TITLE
ref(replays): accordion closes

### PR DESCRIPTION
**Pull request by michellewzhang**
Only applies for the button on left case, which is currently only being used by Replays. 

https://github.com/getsentry/sentry/assets/56095982/17c69745-350e-404e-a518-d07623c0faa1

Disabled button when panel is expanded for performance use case:

https://github.com/getsentry/sentry/assets/56095982/b18863bd-ab56-4c1a-ab67-9425e80382e5

### CODE REVIEW

**Review by roggenkemper — COMMENTED** [review]
do we also want to update it for the case where the button is on the right?

**Comment by michellewzhang** [comment]
> do we also want to update it for the case where the button is on the right?

that's up to performance, since it's their component

**Review by roggenkemper — COMMENTED** [review]
should we be updating the aria label to be collapse or smth like that when it is expanded

**Comment by ryan953** [comment]
This would be a good time to add the `disabled` prop to the button when it's already expanded, if it can't be closed again that is.

**Review by roggenkemper — APPROVED** [review]
lgtm but prob best to have someone on perf approve as well

**Review by ryan953 — APPROVED** [review]
Step by step.

I think we will be back to either add some config/composability, or change our replay design.

**Review by k-fish — APPROVED** [review]
Nice!

**Pull request merged**
