### PR TITLE
fix(py3): http_status passed to spans should be an int

### PR DESCRIPTION
**Pull request by evanpurkhiser**
This fixes a number of py3 tests due to str -> int comparison errors

### CODE REVIEW

**Comment by MeredithAnya** [comment]
@EvanPurkhiser sometimes the code isn't a number tho - in the cases where we don't actually get a http response code back

**Comment by EvanPurkhiser** [comment]
Damn, the sentry sdk does some integer comparison which just blows up. Maybe something we might have to fix in the sdk in that case

**Comment by MeredithAnya** [comment]
> Damn, the sentry sdk does some integer comparison which just blows up. Maybe something we might have to fix in the sdk in that case

hmm yeah so I think it's cause it's attempting to set the status as well. Maybe we should be setting the strings to the status ? since that's what the int comparison achieves anyway ?

**Comment by untitaker** [comment]
Don't call the method if the status is None. We can extend the api to allow for None but that's not how it is supposed to be used right now. It only accepts int

**Comment by MeredithAnya** [comment]
> Don't call the method if the status is None. We can extend the api to allow for None but that's not how it is supposed to be used right now. It only accepts int

Just to be clear - we aren't passing in None for the status, we are passing in a string, so for example "timeout". But yeah that's fair. 

@EvanPurkhiser I think the options we have are to have a try except on the ValueError, or to add another argument 'status' to method. in each case, if it's not a proper http response code, we can call `span.set_status()` instead of `span.set_http_status`

**Comment by untitaker** [comment]
Gotcha, if you're using status it has to match the enum documented here
https://develop.sentry.dev/sdk/event-payloads/types#typedef-SpanStatus

**Comment by EvanPurkhiser** [comment]
@MeredithAnya could you take a look at this again?

**Comment by tonyo** [comment]
JFYI
Just saw this in Github Action tests (https://github.com/getsentry/sentry/pull/20388/checks?check_run_id=1035530553):

```
...
  File "/home/runner/work/sentry/sentry/src/sentry/shared_integrations/client.py", line 277, in get_cached
    result = self.request("GET", path, *args, **kwargs)
  File "/home/runner/work/sentry/sentry/src/sentry/integrations/jira/client.py", line 117, in request
    return self._request(**request_spec)
  File "/home/runner/work/sentry/sentry/src/sentry/shared_integrations/client.py", line 239, in _request
    self.track_response_data("connection_error", span, e)
  File "/home/runner/work/sentry/sentry/src/sentry/shared_integrations/client.py", line 157, in track_response_data
    span.set_http_status(code)
  File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/site-packages/sentry_sdk/tracing.py", line 327, in set_http_status
    if http_status < 400:
TypeError: '<' not supported between instances of 'str' and 'int'
```

Seems to be related.

**Comment by MeredithAnya** [comment]
@EvanPurkhiser so we have `connection_error` and `timeout` that don't seem to be in the list here: https://develop.sentry.dev/sdk/event-payloads/types/#typedef-SpanStatus so we would have to change those. But what I said earlier still stands, we would need to do something like 

```python
try:
    status = int(code)
    span.set_http_status(status)
except ValueError:
    span.set_status(code)
```

**Comment by untitaker** [comment]
Can't we just set that status to `unknown` or something like that in case of `ValueError`?

**Comment by EvanPurkhiser** [comment]
@tonyo That is what this fixes :)

@MeredithAnya 

> But what I said earlier still stands, we would need to do something like

I think it's updated to your suggestion, I'm also fine to set it to unknown, or alternatively @untitaker is there an exception that is raised when setting a string status fails?

**Comment by untitaker** [comment]
if you set the status to an invalid one it should be discarded on the server.

**Comment by MeredithAnya** [comment]
you can set it to `unknown` if you want, to me it kind of defeats the point of being able to segment between the different kinds of transactions that failed (with no http code) but we should probs unblock this

**Review by MeredithAnya — APPROVED** [review]

**Pull request merged**
