### PR TITLE
feat(replay): Add search field for DOM click selector syntax

### PR DESCRIPTION
**Pull request by billyvg**
This adds a search field for DOM clicks using the CSS selector syntax.

### CODE REVIEW

**Review by cmanallen — APPROVED** [review]
I might have you update the description but I'm not sure how wordy it can be.  There's a lot of missing context I think just based on the complexity of what we're doing.  But otherwise looks good!

Edit: meant `ReplayClickFieldKey.CLICK_SELECTOR.desc`

**Comment by billyvg** [comment]
yeah just let me know what you want to change it to

**Comment by cmanallen** [comment]
@billyvg I think we should adapt my PR description here (as best we can): https://github.com/getsentry/sentry/pull/46701.

**Comment by billyvg** [comment]
We need a one liner and link out to docs, because there's a lot in there.

**Comment by cmanallen** [comment]
@billyvg I think the line is fine as is then.  The docs will cover the edges.

**Pull request merged**
