### PR TITLE
Chore/react/create component codemod (WIP)

### PR DESCRIPTION
**Pull request by MaxBittker**
result of adding the standalone create class shim and running this class codemod: https://github.com/reactjs/react-codemod

helps us get closer to react 16:
https://github.com/getsentry/sentry/issues/6495

### CODE REVIEW

**Comment by getsentry-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by billyvg** [comment]
I would prefer to wait until we're ready to upgrade before merging this in. Otherwise, we'll end up having to run it again when we upgrade (e.g. `rg React.PropTypes`)

**Comment by MaxBittker** [comment]
lol, good point

**Comment by MaxBittker** [comment]
i'll leave this open for now, and when the time comes we can revert the last commit, rebase, and rerun codemod.

**Comment by billyvg** [comment]
Since @lynnagara upgraded react, let's work on getting this merged in next @MaxBittker (whenever you get back). We'll also want to make sure people know to use `createClass` from the package and not React.

**Comment by MaxBittker** [comment]
awesome, thanks billy!

**Comment by MaxBittker** [comment]
closing in favor of https://github.com/getsentry/sentry/pull/6823

**Pull request closed without merging**
