### PR TITLE
fix(jira): revert change for persisting reporter

### PR DESCRIPTION
**Pull request by scefali**
This reverts https://github.com/getsentry/sentry/pull/21589 which is causing the following error:
`{"errorMessages":["Either the 'username' or the 'key' query parameters need to be provided"],"errors":{}}`

Sentry error here: https://sentry.io/share/issue/3532ee5963314ef9bc10d52c04420e42/

@saifelse  Feel free to make a follow-up PR that implements your original PR while handling this error.

Fixes SENTRY-JDS

### CODE REVIEW

**Review by MeredithAnya — APPROVED** [review]

**Comment by saifelse** [comment]
@scefali : oof, sorry!
Could you confirm if these errors are happening for JiraServer or JiraCloud?

My hunch is that it's JiraServer... as I only was able to manually test against JiraCloud 😅 .

Do y'all have a toy JiraServer that I could test against... otherwise, I can try downloading from https://www.atlassian.com/software/jira/download ... at the very least, I can error gracefully or just restrict support for JiraCloud.

**Comment by scefali** [comment]
> @scefali : oof, sorry!
> Could you confirm if these errors are happening for JiraServer or JiraCloud?
> 
> My hunch is that it's JiraServer... as I only was able to manually test against JiraCloud 😅 .
> 
> If so, do y'all have a toy JiraServer that I could test against... otherwise, I can try downloading from https://www.atlassian.com/software/jira/download ... at the very least, I can error gracefully or just restrict support for JiraCloud.

@saifelse Good intuition, it's only happening for Jira Server. We don't actually have a toy Jira Server that you can use (I just downloaded my own). I'll leave it up to you if you want to download it or just restrict it for Jira Cloud (though having it work for Jira Server would be great).

**Comment by saifelse** [comment]
I suspect the issue with JiraServer is that the correct parameter name will depend on what version of JiraServer the user is using... will do some digging to see if there is a sane way to support both without needing to add complexity.

> Ah figured it out. Some of our customers are using Jira Server and not Jira Cloud and thus are on previous versions that have the old behavior. I've handled the condition by querying serverInfo to see if the build date is before the 2020-04-15 which seems to be the one that introduced the breaking change.

from https://community.atlassian.com/t5/Jira-questions/API-breaking-change-bug-quot-The-accountId-query-parameter-needs/qaq-p/1350776

**Comment by saifelse** [comment]
Sign nvm, it seems just a dumb API decision: https://docs.atlassian.com/software/jira/docs/api/REST/8.13.1/#api/2/user-getUser `api/2/user` calls the parameter `username` for this endpoint, but `name` in the user response and /assignee endpoints.

**Pull request merged**
