### PR TITLE
feat(discover): Add panel to intro component

### PR DESCRIPTION
**Pull request by lynnagara**

### CODE REVIEW

**Review by billyvg — APPROVED** [review]
Can we add screenshots to the PR description for UI changes like this?

**Comment by lynnagara** [comment]
This adds the panel/border around the intro component
screen shot 2018-09-28 at 1 38 07 pm

**Comment by EvanPurkhiser** [comment]
Maybe just me, and @ckj could weigh in too, but I feel it actually looked better without the panel

**Comment by ckj** [comment]
@EvanPurkhiser yeah I agree it felt better without it. @lynnagara what was the thinking behind adding it?

**Comment by lynnagara** [comment]
@ckj I thought you've asked us to do this some time ago. Just got around to it.

**Comment by ckj** [comment]
@lynnagara Oh, okay! I think I meant around the results table itself, but we added it there already. I'm +1 for reverting this specific change if you agree it looked better before.

**Pull request merged**
