### PR TITLE
feat(ui): Add new sorting options to releases page

### PR DESCRIPTION
**Pull request by matejminar**
Adding 3 new sorting options to releases:
- By Build Number
- By Semantic Version
- By Date Adopted

Backend for this is still in progress. The visibility of these options is feature flagged.

This PR also introduces two new feature flags that can be reused on the backend if needed:
`organizations:semver` and `organizations:release-adoption-stage`

### CODE REVIEW

**Review by priscilawebdev — APPROVED** [review]
lgtm

**Comment by matejminar** [comment]
Adding 3 new sorting options to releases:

By Build Number
By Semantic Version
By Date Adopted
Backend for this is still in progress. The visibility of these options is feature flagged.

This PR also introduces two new feature flags that can be reused on the backend if needed:
organizations:semver and organizations:release-adoption-stage

**Comment by armenzg** [comment]
I've recently started trying to use Semantic Versioning for one of my services, however, I've noticed that Sentry does not show a valid semantic version.

This shows that it is valid semver:
https://jubianchi.github.io/semver-check/#/version/2021.8.20%2B142918.armenzg-semver.68fd0d2

[Here's the release](https://sentry.io/organizations/sentry/releases/2021.8.20%2B142918.armenzg-semver.68fd0d2/?project=5748916) and I was expecting to use the sorting feature, however, I'm told there's no semantic versioned releases.

**Comment by matejminar** [comment]
@armenzg Looking at your release, I can tell we do not parse it as a semantic version. 
Can you please add the package portion to your version?
More info can be found here: https://docs.sentry.io/platforms/javascript/configuration/releases/#bind-the-version

Btw, we do not actually follow SemVer exactly, it's more of a SentryVer (for example we support major.minor.patch.revision instead of just major.minor patch, etc).

**Comment by armenzg** [comment]
Someone ended up telling me that I need to specify `gitbot@` at the beginning.
Thanks for checking!

**Comment by matejminar** [comment]
Yes, that will act as a package and the parser should be therefore happy. 👍

**Pull request merged**
