### PR TITLE
Update labels - no more Unito for epics

### PR DESCRIPTION
**Pull request by chadwhitacre**
https://github.com/getsentry/team-ospo/issues/106

### CODE REVIEW

**Review by asottile-sentry — APPROVED** [review]

**Comment by chadwhitacre** [comment]
Might remove the label entirely if @brentc doesn't want it, but for now at least updating the doco. :)

**Comment by brentc** [comment]
Presently, I'm using it to separate out projects from tasks in order to support [this roadmap view](https://github.com/orgs/getsentry/projects/54/views/15) in our project board. That being said, we could do it via a project field instead, so it's not a huge loss for us if it goes away.

**Comment by brentc** [comment]
Wait... scratch that I'm already using a project field for that. Feel free to drop it.

**Pull request merged**
