### PR TITLE
Add number confirm modal dialog with code input

### PR DESCRIPTION
**Pull request by HazAT**
#nochanges

### CODE REVIEW

**Comment by mitsuhiko** [comment]
Fancy! We should use this for our 2fa flow too then.

**Comment by mitsuhiko** [comment]
(Does it support copy/paste?)

**Review by mitsuhiko — APPROVED** [review]

**Comment by HazAT** [comment]
No copy paste support yet ... also had to use a older version because of our react version.

**Comment by HazAT** [comment]
screen shot 2017-04-06 at 09 16 42

**Comment by 40818419** [comment]
https://github.com/40818419/react-code-input/issues/6

copy paste is now available, have fun guys!

**Pull request merged**
