### PR TITLE
Add action links for subscribe/unsubscribe.

### PR DESCRIPTION
**Pull request by tkaemming**
Buddy commit for GH-4471 to allow subscribing or unsubscribing to issues from the stream.

### CODE REVIEW

**Comment by benvinegar** [comment]
cc @ckj 

I think we should explore how we can add subscription status to the stream UI, for example, here:

image

**Comment by ckj** [comment]
@benvinegar Yeah, using "<icon-signal> Subscribed" somewhere on that line could work well. We do something similar for Ignored issues in the main line, but I think that would be too prominent for this.

**Comment by benvinegar** [comment]
@ckj – we're wondering if there's a lower visual-impact way of describing this. Because if you bulk resolve a bunch of issues, then they all pop up back again due to regressions - you'll see "subscribed" for all of them. Is there anything we can do, icon-wise?

**Comment by ckj** [comment]
@benvinegar Potentially, but I'm not sure [icon-signal] (the current icon) would be clear enough on its own. There's not a universal icon for "subscribe" other than maybe the RSS/feed icon, but I don't think that would be the right choice here. Unfortunately, that's the best answer I can provide without putting in some design time around this.

**Comment by tkaemming** [comment]
Also worth keeping in mind here that there are several possible states, though I'm not sure which make sense to try and articulate here:

- You've disabled workflow notifications for the project, and are subscribed to the issue. You receive workflow notifications.[1] This should be marked as subscribed.
- You've disabled workflow notifications for the project, and are unsubscribed from the issue. You don't receive workflow notifications. This should probably be marked as unsubscribed.
- You've disabled workflow notifications for the project, and are neither subscribed nor unsubscribed to/from the issue. You don't receive workflow notifications. Does this get marked as anything in particular?
- You've enabled workflow notifications for the project, and are subscribed to the issue. You receive workflow notifications. This should be marked as subscribed.
- You've enabled workflow notifications for the project, and are unsubscribed from the issue. You don't receive workflow notifications. This should be marked as.
- You've enabled workflow notifications for the project, and are neither subscribed nor unsubscribed to/from the issue. You *might* receive workflow notifications, depending on the value of the "Receive updates for all issues by default" setting. Does this get marked as subscribed? Something sort of like subscribed?

[1]: I'm pretty sure this works this way, but need to double check.

**Comment by tkaemming** [comment]
Talked over this one in person with @ckj and @benvinegar — we're going to display the signal icon in the stream view (next to where we show the comment icon/count) if you're explicitly subscribed to the issue. No special handling for the other states (soft subscribed, etc.)

**Comment by tkaemming** [comment]
🙈

**Comment by benvinegar** [comment]
Did we convince ourselves to pass on this?

**Comment by tkaemming** [comment]
Last we talked about it, we had decided on taking a wait-and-see approach if there continued to be more support issues we'd reevaluate.

It doesn't seem like there have been many support concerns around workflow notifications the past couple of weeks, so I went ahead and closed this out to avoid leaving it hanging indefinitely. I did intentionally leave the branch around in case we change our minds later and decide to reopen.

**Pull request closed without merging**
