### PR TITLE
Revert "Upgrade to React 15.2.1 [try 2] (#3689) (#3734)"

### PR DESCRIPTION
**Pull request by benvinegar**
This reverts commit 7fdcc5fd717b6691686504b1381711f52e541545.

Build is broken again so I'm reverting again.

I basically don't know what to do anymore. Before I merged, the acceptance test [was green](https://travis-ci.org/getsentry/sentry/builds/144891183). I even used the visual diffs created by Percy to fix some bugs. But after merging, [it went red](https://travis-ci.org/getsentry/sentry/builds/145403723) with the same `BadStatusLine` Selenium/Webdriver error.

cc @getsentry/team @fotinakis

---

This change is [Reviewable](https://reviewable.io/reviews/getsentry/sentry/3743)

### CODE REVIEW

**Comment by benvinegar** [comment]
[This thread](https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/6690) is the closest thing I've found on the web that seems to match this error – and Travis also runs Ubuntu.

**Comment by benvinegar** [comment]
Also the acceptance tests still pass if you re-run the original (now merged) branch: https://travis-ci.org/getsentry/sentry/jobs/144891187

**Comment by benvinegar** [comment]
Okay, I think I have something. If I start deleting caches and re-running tests, they start to fail.

I think that we have begun to download a new version of Selenium for which this bug is present (2.53.6 was introduced 2 weeks ago), and that I just conveniently was the first person to hit it when I introduced my React branch (with a new cache).

I'm going to experiment with pinning Selenium to previous versions and see if that helps things.

**Comment by fotinakis** [comment]
Nice @benvinegar! Yes, pinning Selenium versions is I think pretty common because the webdriver interface unfortunately sometimes breaks compatibility with browsers between versions of either. If you find a pattern that works and seems to fix the `BadStatusLine` error, can you let me know so I can add a recommendation to our python docs?

**Comment by benvinegar** [comment]
@fotinakis – So, that didn't work. I tried pinning the last 2 previous versions and nothing helped.

This is becoming a serious issue. If I have to choose between never upgrading my client side libs and running acceptance tests, I'm going to ditch the acceptance tests. Would really appreciate some help on this because I'm completely in the dark.

**Comment by benvinegar** [comment]
new pr open on #3747

**Pull request merged**
