### PR TITLE
feat(replays): Add alternative buffered I/O recording consumer implementation

### PR DESCRIPTION
**Pull request by cmanallen**
This change adds a new recording consumer type which batches I/O operations together.  Currently, the whole process from start to finish occurs in a threadpool.  CPU bound and I/O bound work run interleaved with one another.  This is a problem because it limits our ability to handle the I/O operations concurrently.  You end up with head of line blocking as one thread uses the CPU and another threads waits until it can start its I/O.

If we process the messages up-front we can be sure of two things:

1. We know the CPU bound portions of the message processor will run as fast as possible (no blocking I/O ever).
2. We know the I/O bound portions will _only_ contain I/O.  This means better utilization of those threads (and the ability to add more) because a thread is never waiting on a blocking CPU operation.

These two factors should hopefully lead to a large performance increase for the recording consumer.

### CODE REVIEW

**Comment by JoshFerge** [comment]
could you add a description of what the overall architecture of this change is and the performance improvements we'd expect to see?

**Comment by cmanallen** [comment]
@JoshFerge Updated.

**Comment by JoshFerge** [comment]
Thank you @cmanallen! That makes sense. Would it be possible to test this change with the load testing platform?

**Comment by cmanallen** [comment]
@JoshFerge Yeah! So if we merge this its a no-op.  And we can setup the QE platform to target the CLI entrypoint I set up.

**Review by JoshFerge — APPROVED** [review]
excited to try this!

**Pull request merged**
