### PR TITLE
perf(tests): change fixture init to be per class

### PR DESCRIPTION
**Pull request by JoshFerge**
seeing if this speeds up tests / even works.

### CODE REVIEW

**Comment by asottile-sentry** [comment]
this was attempted in #43471 but it only made ~5-10 seconds of meaningful improvement and the downsides are pretty high (shared state leaks between tests) so it was abandoned

**Comment by JoshFerge** [comment]
> this was attempted in #43471 but it only made ~5-10 seconds of meaningful improvement and the downsides are pretty high (shared state leaks between tests) so it was abandoned

it makes sense. if we could do a module or session based fixture with proper cleanups inbetween i think it would make a larger difference. need to dig a lot more to determine feasibility of that though

**Comment by JoshFerge** [comment]
> > > this was attempted in #43471 but it only made ~5-10 seconds of meaningful improvement and the downsides are pretty high (shared state leaks between tests) so it was abandoned
> > 
> > 
> > it makes sense. if we could do a module or session based fixture with proper cleanups inbetween i think it would make a larger difference. need to dig a lot more to determine feasibility of that though
> 
> that's what the linked PR attempts -- it's a ton of complexity for very little gain

from what I read in the PR it seems like it was attempted to make it a class based fixture. from what i understand a module or session based fixture would have a greater impact. according to our perf stats this fixture setup is by far the most time consuming fixture in our tests, so i think there is fruit to be had here

**Comment by asottile-sentry** [comment]
> > > > this was attempted in #43471 but it only made ~5-10 seconds of meaningful improvement and the downsides are pretty high (shared state leaks between tests) so it was abandoned
> > > 
> > > 
> > > it makes sense. if we could do a module or session based fixture with proper cleanups inbetween i think it would make a larger difference. need to dig a lot more to determine feasibility of that though
> > 
> > 
> > that's what the linked PR attempts -- it's a ton of complexity for very little gain
> 
> from what I read in the PR it seems like it was attempted to make it a class based fixture. from what i understand a module or session based fixture would have a greater impact. according to our perf stats this fixture setup is by far the most time consuming fixture in our tests, so i think there is fruit to be had here

acceptance is always going to be slow, and dominated by the tests themselves.  the perf data overly-skews the impact of this fixture because it's run so often but it's unlikely to make a significant impact overall

**Pull request closed without merging**
