### PR TITLE
add tombstones to load-mocks

### PR DESCRIPTION
**Pull request by macqueen**
cc @ckj

### CODE REVIEW

**Review by tkaemming — APPROVED** [review]
Didn't actually run it, but seems like it should work

**Comment by ckj** [comment]
🙏

**Comment by kjlundsgaard** [comment]
A separate issue than _creating_ tombstone mocks, but if you discard any events through the UI and then try to run `load-mocks`, you'll run into `raise HashDiscarded('Matches group tombstone %s' % h.group_tombstone_id)`

**Comment by macqueen** [comment]
@kjlundsgaard ok i can fix that separately

**Pull request merged**
