### PR TITLE
feat(browser-starfish): add use case for bundle analysis

### PR DESCRIPTION
**Pull request by DominikB2014**
After some discussion, we decided to go with generic metrics to keep track of bundle size.

This PR adds a new use cases for the bundle analysis project in order to create new generic metrics for it. 

The code for emiting the metrics will be in a future PR (in draft here https://github.com/getsentry/sentry/pull/65270)

### CODE REVIEW

**Comment by evanh** [comment]
> After some discussion, we decided to go with generic metrics to keep track of bundle size.

Are there some notes about this? From my understanding there will only be a single value emitted for each release, which is not really a great use case for metrics.

**Comment by DominikB2014** [comment]
> Are there some notes about this? From my understanding there will only be a single value emitted for each release, which is not really a great use case for metrics.

There will actually be multiple values emitted per release, we're good with using metrics because it gives us the flexibility we need to build out this feature.

**Review by edwardgou-sentry — APPROVED** [review]

**Comment by edwardgou-sentry** [comment]
> > After some discussion, we decided to go with generic metrics to keep track of bundle size.
> 
> Are there some notes about this? From my understanding there will only be a single value emitted for each release, which is not really a great use case for metrics.

I think @phacops can elaborate better, but as long as the product needs are met, it should be ok right? The use case here definitely won't exceed what generic metrics can support, but that shouldnt be a blocker

**Comment by evanh** [comment]
> I think @phacops can elaborate better, but as long as the product needs are met, it should be ok right? The use case here definitely won't fully use what generic metrics can support, but that shouldnt be a blocker

@edwardgou-sentry @DominikB2014

You are right, and I'm not trying to be a blocker. However storing small numbers of values per cardinality (in this case per release) is relatively expensive. The upside of metrics is that the cost remains constant as the number of values scales. So be aware that if the cost of this feature starts to go up, you might have to come up with a different solution anyway.

**Comment by DominikB2014** [comment]
> You are right, and I'm not trying to be a blocker. However storing small numbers of values per cardinality (in this case per release) is relatively expensive. The upside of metrics is that the cost remains constant as the number of values scales. So be aware that if the cost of this feature starts to go up, you might have to come up with a different solution anyway.

👍 that definitely makes sense, we'll be keep an eye on that, Thank you!

**Pull request merged**
