### PR TITLE
[alerts] enhance digest/alert emails

### PR DESCRIPTION
**Pull request by dcramer**
- add issue header to alert
- add transaction to issue headers
- update event rendering to reflect current UI

### CODE REVIEW

**Comment by dcramer** [comment]
screenshot 2017-02-04 12 14 21

**Comment by dcramer** [comment]
screenshot 2017-02-04 12 14 44

**Comment by dcramer** [comment]
We probably need to tighten up digests, but transactions are super important to understand issues so I want to get them in there.

**Comment by dcramer** [comment]
Lowered line-height to 22px (from 24px)

**Comment by ckj** [comment]
Sorry for taking so long to get to this. I'm seeing some overflow issues locally:
 
screen shot 2017-02-21 at 11 36 54 am

I'm going to see if I can quickly get some guards in against this so we can get this merged asap.

**Review by ckj — APPROVED** [review]
I'd like to make some legibility fixes on the error-level labels, but that's an issue for another PR. This looks good! 🚢🚢🚢

**Pull request merged**
