### PR TITLE
feat: Add API to identify available permissions

### PR DESCRIPTION
**Pull request by dcramer**
Will be utilized when building a configuration form in admin, and makes use of the currently unused configurable list of permissions.

### CODE REVIEW

**Comment by dcramer** [comment]
@wedamija found a use for it :)

**Review by markstory — APPROVED** [review]

**Comment by dcramer** [comment]
thought: if permisisons are superuser only, should this return empty list when user is missing is_superuser? my thoughts are: meh who cares

**Review by wedamija — APPROVED** [review]
It's probably not that big of a deal, but since this endpoint is intended for use only by superusers should we just restrict it and 403/404 if they don't have it?

**Comment by dcramer** [comment]
@wedamija if we do we will likely want to change that in quite a few places. I'm not opposed but also not concerneda bout risk

**Comment by dcramer** [comment]
Will revisit perms issue as a whole later

**Pull request merged**
