### PR TITLE
feat(org-events): add PreviewFeature message

### PR DESCRIPTION
**Pull request by Chrissy**
image

### CODE REVIEW

**Comment by billyvg** [comment]
So this component is only used in project security settings, should we make this an info alert instead of warn to be consistent with our other early adopter messages?

**Comment by Chrissy** [comment]
@billy yah that seems right. 

It's a little confusing that we have this component but also a bunch of similarly-functioning alert messages that don't use it. Is the hope that we will transition to this if we can build it out a bit? Or did I just use the wrong component?

**Comment by billyvg** [comment]
Yeah I think the hope is that we transition to this component (but I think building this into `app/components/acl/feature` would be even better /cc @EvanPurkhiser)

**Comment by Chrissy** [comment]
alright cool I'll build in a `role` type thing and switch to `info`

**Comment by ckj** [comment]
@Chrissy @billyvg we also have some branding around preview/branding with `icon-labs` that I'd like to make a thing

**Comment by ckj** [comment]
💥ty

**Comment by EvanPurkhiser** [comment]
Yeah I think it would definitely make sense to move this into the acl namespace. Maybe it can even replace the ComingSoon component

**Review by billyvg — APPROVED** [review]

**Pull request merged**
