### PR TITLE
Add link and shell script to upload missing dsyms

### PR DESCRIPTION
**Pull request by HazAT**
screen shot 2017-04-18 at 09 12 39

#nochanges

### CODE REVIEW

**Comment by mitsuhiko** [comment]
I wouldn't mind merging this. Just probably need to get some UI polish.

**Comment by mitsuhiko** [comment]
@ckj this is a leftover from hackweek. I would love to get this polished and actually into the product because it helps users that failed to configure their build steps which is not too unlikely. Do you think you could make a pass over the UI?

**Comment by mitsuhiko** [comment]
@HazAT I just realized that we did not actually ever solve the flow part about "this user does not have an API key". Probably need to do something about that.

**Review by ckj — APPROVED** [review]
Made a pass on UI and Language. It's in a good place, 👍 .

**Comment by ckj** [comment]
Updated screenshot:

screen shot 2017-04-19 at 3 38 05 pm

**Comment by HazAT** [comment]
:shipit:

**Pull request merged**
