### PR TITLE
chore(roles): remove OrgRoleInfo

### PR DESCRIPTION
**Pull request by cathteng**
`OrgRoleInfo` was supposed to be used in the case that a member was part of a team with an org role, so we could show where a member was getting their roles (complicated, I know).

This can be removed since we are removing all references to org roles for teams. I already remove the UI to be able to set an org role for a team in #64626.

For https://github.com/getsentry/team-core-product-foundations/issues/51

### CODE REVIEW

**Review by 17hogeju — COMMENTED** [review]
Will this need to be removed as well?
https://github.com/getsentry/sentry/blob/03ca9619c0715a21369bca330b0cb2094dc14a5c/static/app/data/forms/teamSettingsFields.tsx#L29-L54

**Comment by cathteng** [comment]
@17hogeju it's already removed on master https://github.com/getsentry/sentry/blob/master/static/app/data/forms/teamSettingsFields.tsx#L29-L54

**Comment by 17hogeju** [comment]
Is removing `orgRole` from Team also part of this PR?

**Comment by cathteng** [comment]
@17hogeju i'm trying to not remove like 1000 lines in a PR, so i will attempt clean up all references to `team.orgRole` (or at least break it up) before removing the field from the `Team` type

**Review by 17hogeju — APPROVED** [review]

**Pull request merged**
