### PR TITLE
fix(ui): Upgrade react mentions

### PR DESCRIPTION
**Pull request by scttcper**
Upgrades the [react-mentions](https://github.com/signavio/react-mentions) package. Pretty large version increase seems scary but it seems to work the same after a few changes.

size - now has treeshaking and no longer depends on lodash.
new 50kB - https://bundlephobia.com/result?p=react-mentions@4.0.1
old 110kB - https://bundlephobia.com/result?p=react-mentions@1.2.0

### CODE REVIEW

**Comment by billyvg** [comment]
Nice I have been waiting for this release... closes https://github.com/getsentry/sentry/pull/15579

**Review by billyvg — CHANGES_REQUESTED** [review]
The issue details activity textarea height is covering up the Post button

image

**Comment by scttcper** [comment]
That is a good catch 👍 I did not check the size of the hidden container 🤣

**Comment by scttcper** [comment]
We can remove `babel-runtime` for only `@babel/runtime` if we update react-virtualized after this

**Review by billyvg — APPROVED** [review]

**Pull request merged**
