### PR TITLE
fix(notifications): Unify Email Subjects

### LINKED ISSUE #6902: Unify Email Subjects
With the introduction of the User Feedback emails, we now have 2 (3?) subjects in emails. Historically we kept an oddly generated alert subject template and had never gotten around to changing it, but at this point there's better solutions we could do from an experience POV.

Let's use this opportunity to overhaul subjects for the following:

- Alerts
- Workflow
- Digests

The subject we're using in feedback emails is:

```
{SHORT_ID} - {TITLE}
```

Where ``SHORT_ID`` is ZEUS-F1, and ``TITLE`` is 'New Feedback from USER'

See also https://github.com/getsentry/sentry/pull/6230

### PR DESCRIPTION
**Pull request by lauryndbrown**
Added shortID to existing email subjects in Alerts, Workflow, and Digests.
FIXES: #6902

### CODE REVIEW

**Comment by getsentry-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Review by dcramer — APPROVED** [review]
🚀

**Comment by lauryndbrown** [comment]
@dcramer I noticed that the shortID parameter I added to the email templates shows up on the UI here https://percy.io/getsentry/sentry/builds/480409. So far, I haven't removed any parameters. I just added shortID. Would you want to keep the text about the project and just add shortid to that list? or remove it?

**Comment by billyvg** [comment]
I think what you have as is is perfect, `project` is redundant

**Comment by dcramer** [comment]
agree with @billyvg

**Pull request merged**
