### PR TITLE
feat(grouping): Exclude sentry-java sdk frames from group and inapp

### PR DESCRIPTION
**Pull request by romtsn**
This is necessary for the sentry-java sdk to not mess up grouping, because we'll start sending sdk frames for fatals from the next major version (relevant pr: https://github.com/getsentry/sentry-java/pull/3021)

Also changed `io.sentry` to `com.example` in `stacktrace-collapse-recursion` snapshot so it's not affected by this change

### CODE REVIEW

**Review by lobsterkatie — COMMENTED** [review]
So, if I understand correctly, this doesn't affect current issues, just ones which will come from the new version of the SDK. Is that right?

**Comment by romtsn** [comment]
> So, if I understand correctly, this doesn't affect current issues, just ones which will come from the new version of the SDK. Is that right?

yes, that's right!

**Comment by romtsn** [comment]
@lobsterkatie can we get this approved, or do you see any problems with that? :)

**Comment by kahest** [comment]
@lobsterkatie also just to be 100% sure - once this is merged, the new rule is applied immediately for new events, correct?

**Comment by lobsterkatie** [comment]
Yes, it will be applied immediately. But I checked out https://github.com/getsentry/sentry-java/pull/3021 and it seems like currently, no events have sentry frames, correct? If that's true, then this is fine to merge.

**Review by lobsterkatie — APPROVED** [review]
Yup! 🚢

**Pull request merged**
