### PR TITLE
ref(js): Improved naming of projects util search callback

### PR DESCRIPTION
**Pull request by evanpurkhiser**

### CODE REVIEW

**Review by billyvg — COMMENTED** [review]
Isn't this named appropriately since it's a callback that's being passed around?

**Comment by billyvg** [comment]
I would say it's a prop of the render function which is similar to if it were a prop of a component

**Comment by EvanPurkhiser** [comment]
> I would say it's a prop of the render function which is similar to if it were a prop of a component

I'm not sure that we can say a render function parameter is the same as a prop of a component. Isn't that the whole point of a render prop style component, is that it's a IoC. Which is why you can pass things that are functions down.

For example, you might pass the `onSearch` into a `onChange` of a input (if the parameters were more right). In which case, wouldn't it make more sense for it to be `handleSearch` so that it's

```tsx
<input onChange={handleSearch} />
```

Instead of 

```tsx
<input onChange={onSearch} />
```

which is a pattern we've tried to avoid right

**Comment by billyvg** [comment]
> I'm not sure that we can say a render function parameter is the same as a prop of a component. 
Not saying they are the same, just that they are similar (enough that we call them render props in our types).

In your example,

```
<input onChange={onSearch} />
```

Would make sense if `onSearch` is a prop of that component that is passed in by a parent component, where `handleSearch` handles the change event.

e.g.

```
function A() { const handleSearch = () => {}; return <B onSearch={handleSearch} /> }
function B({onSearch}) { return <input onChange={onSearch} />}
```

And yeah, because of the IoC w/ render fn, control resides inside of `<Projects>` which has the `handleSearch` method.

```
function A() { return <B>{({onSearch} => <input onChange={onSearch} />}</B> }
function B({children}) { const handleSearch = () => {}; return children({onSearch: handleSearch}) }
```

**Comment by EvanPurkhiser** [comment]
Yeah I see. I think I generally agree

**Pull request closed without merging**
