### PR TITLE
ref(gitlab): Handle IdentityNotValid in check_file

### PR DESCRIPTION
**Pull request by MeredithAnya**
Same problem as https://github.com/getsentry/sentry/pull/27765 but here we should just catch the error and return `None`.

FIXES SENTRY-NT9
(forreal this time)

### CODE REVIEW

**Comment by mgaeta** [comment]
Can we add a test to `sentry/tests/sentry/integrations/gitlab/test_client.py`?

**Review by ceorourke — APPROVED** [review]

**Comment by styfox** [comment]
Ghazi

**Comment by styfox** [comment]
>  @**

1. 

- 

**

**Comment by MeredithAnya** [comment]
> Can we add a test to `sentry/tests/sentry/integrations/gitlab/test_client.py`?

added it to `test_integration.py` instead because I think that made a bit more sense

**Pull request merged**
