### PR TITLE
[danger] improve security checks

### PR DESCRIPTION
**Pull request by dcramer**
- remove key from contents checks (matches too many things, like CACHE_KEY)
- exclude all test_*.py files
- remove accounts files (most of accounts is not related to security/authentication)

### CODE REVIEW

**Comment by dcramer** [comment]
i literally didn't test this, but will push up a dummy commit to see if it flags

**Comment by dcramer** [comment]
qa here https://github.com/getsentry/sentry/pull/4461

**Comment by dcramer** [comment]
also ``bundle exec danger local`` works now so confirmed things are sane

**Review by mattrobenolt — APPROVED** [review]
⚠️

**Pull request merged**
