### PR TITLE
ref(login): Add join request button to login

### PR DESCRIPTION
**Pull request by maheskett**
Screen Shot 2019-11-22 at 1 05 13 PM
Screen Shot 2019-11-22 at 1 04 58 PM

### CODE REVIEW

**Review by dashed — APPROVED** [review]
Looks good to me 👍

**Comment by billyvg** [comment]
The icon doesn't look centered - is it intentional to subdue the link a bit? It wasn't immediately obvious to me that it can be clicked.

**Comment by maheskett** [comment]
@billyvg Updated the icon. Does that look better? Yeah, it was intentional to subdue the link. Previous feedback was that the button (in description history) was too prominent cc @ckj

**Review by billyvg — APPROVED** [review]
👍

**Review by ckj — APPROVED** [review]

**Pull request merged**
