### PR TITLE
feat(mobile): extract device class context as tag

### PR DESCRIPTION
**Pull request by edwardgou-sentry**
Adds `device.class` to `context_to_tag_mapping` so that `device.class` context is also created as a tag when it exists.

### CODE REVIEW

**Review by narsaynorath — APPROVED** [review]

**Comment by jjbayer** [comment]
Requesting review from @getsentry/sns because I am not sure if we're still supposed to promote context values to tags, or rather create Snuba columns for them directly. See also this conversation: https://github.com/getsentry/sentry/pull/43591#discussion_r1086012851.

Although it makes sense IMO to make `device.class` a tag for consistency's sake, because `device.model` and `device.family` are also tags.

**Review by untitaker — CHANGES_REQUESTED** [review]
please do not do this, we should make it clear that this entire model of tag extraction is supposed to be deprecated. If you really need a tag, you can extract it in Relay (that's where most of the tag extraction went), and if not, it's better to promote the context data in snuba (`errors_processor.py` has very similar logic). It will be more efficient in every way.

**Comment by jjbayer** [comment]
> we should make it clear that this entire model of tag extraction is supposed to be deprecated. If you really need a tag, you can extract it in Relay (that's where most of the tag extraction went), and if not, it's better to promote the context data in snuba (`errors_processor.py` has very similar logic). It will be more efficient in every way.

@evanpurkhiser @wedamija reading the comment above, we might want to reinstate the note you discussed [here](https://github.com/getsentry/sentry/pull/43591#discussion_r1086012851), in one form or another.

**Comment by untitaker** [comment]
I am not sure why this note was removed, and judging by the comments we seem to want to explicitly have some data in `event.tags`, not just searchable in some way. Why is that the caes?

**Comment by wedamija** [comment]
> I am not sure why this note was removed, and judging by the comments we seem to want to explicitly have some data in `event.tags`, not just searchable in some way. Why is that the caes?

That note was never added. @evanpurkhiser was adding docs around context so we could understand it better, but when we investigated we found it wasn't true. Snuba does not actually perform any conversion of context -> tags. It does promote contexts -> columns, but we still rely on all of the code here that extracts tags from contexts: https://github.com/getsentry/sentry/blob/c8bbb69c609b5537d03f3da8c0aafda338e89293/src/sentry/interfaces/contexts.py#L142-L172

I can't speak to the relay part, if that's the preferred path then that's fine, but this context code is very much still in use at the moment.

**Comment by untitaker** [comment]
> Snuba does not actually perform any conversion of context -> tags. It does promote contexts -> columns,

People add things here because they want to make them searchable, so this makes no difference. However, Nar additionally wants those values to appear in the tags breakdown, so adding tags here or in Relay is their only solution atm.

If we extract some new fields into searchable discover fields and only some other things into auto-generated tags, the UI will be very inconsistent.

I don't think we have proper UX guidance as to what belongs in tags and what doesn't, but in the past S&S has been banging the drum of putting as little into tags as possible due to performance reasons.

**Comment by edwardgou-sentry** [comment]
Closing this for now since we should be creating the tag in relay instead

**Pull request closed without merging**
