### PR TITLE
Swap release-based stats into issue details

### PR DESCRIPTION
**Pull request by dcramer**
Replaces the stats graphs (which are pure event counts) with stacked bars based on the current release. This allows users to more easily identify if the issues are happening primarily on the current release, or on an older version.
- Adds project environments endpoint
- Adds issue environment details endpoint
- Environment selector on issue details will now represent only data for the given selection (for graphs, first seen, and last seen)
- Adds a 'default environment' option in project settings to choose the default value for the selector

@getsentry/api @getsentry/ui

---

This change is [Reviewable](https://reviewable.io/reviews/getsentry/sentry/3764)

### CODE REVIEW

**Comment by dcramer** [comment]
screenshot 2016-07-20 16 24 50

**Comment by dcramer** [comment]
#3652

**Comment by macqueen** [comment]
Reviewed 4 of 31 files at r1, 1 of 7 files at r2.
Review status: 5 of 32 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[src/sentry/static/sentry/app/components/group/sidebar.jsx, line 25 \[r3\]](https://reviewable.io:443/reviews/getsentry/sentry/3764#-KNDWF0a364eoyfJNkwt:-KNDWF0a364eoyfJNkwu:-246944297) ([raw file](https://github.com/getsentry/sentry/blob/9b9bcbef231dfdd6e64979bef216c7b3e7af7a75/src/sentry/static/sentry/app/components/group/sidebar.jsx#L25)):*
> ```JSX
>   ],
> 
>   // shouldComponentUpdate(nextProps, nextState) {
> ```

should this just be deleted? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3764)*

**Comment by mattrobenolt** [comment]
Review status: 5 of 32 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[src/sentry/api/endpoints/group_environment_details.py, line 25 \[r3\]](https://reviewable.io:443/reviews/getsentry/sentry/3764#-KNDi_7uyrK67WBzBkKK:-KNDi_7uyrK67WBzBkKL:175174279) ([raw file](https://github.com/getsentry/sentry/blob/9b9bcbef231dfdd6e64979bef216c7b3e7af7a75/src/sentry/api/endpoints/group_environment_details.py#L25)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>
>       try:
>             first_release = GroupRelease.objects.filter(
>                 group_id=group.id,
>                 environment=environment,
>             ).order_by('first_seen')[0]
>         except IndexError:
>             first_release = None
</details>

Can we simplify these to `.first()` calls?

```python
first_release = GroupRelease.objects.filter(
    group_id=group.id,
    environment=environment,
).order_by('first_seen').first()
```

---

*[src/sentry/api/serializers/models/project.py, line 46 \[r3\]](https://reviewable.io:443/reviews/getsentry/sentry/3764#-KNDjJpns3idZiKbyPku:-KNDjJpo3kg5JRVpGXJW:-2090306404) ([raw file](https://github.com/getsentry/sentry/blob/9b9bcbef231dfdd6e64979bef216c7b3e7af7a75/src/sentry/api/serializers/models/project.py#L46)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>
>         default_environments = {
>                 o.project_id: o.value
>                 for o in ProjectOption.objects.filter(
>                     key='sentry:default_environment',
>                     project__in=project_ids,
>                 )
>             }
</details>

```python
default_environments = dict(ProjectOption.objects.filter(key='sentry:default_envirnment', project__in=project_ids).values_list('project_id', 'value'))
```

Should be a bit more efficient.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3764)*

**Comment by tkaemming** [comment]
Reviewed 9 of 31 files at r1, 1 of 7 files at r2.
Review status: 15 of 32 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3764)*

**Comment by dcramer** [comment]
Review status: 15 of 32 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[src/sentry/api/serializers/models/project.py, line 46 \[r3\]](https://reviewable.io:443/reviews/getsentry/sentry/3764#-KNDjJpns3idZiKbyPku:-KNDmRiF0SYLQYevuOrJ:-746944638) ([raw file](https://github.com/getsentry/sentry/blob/9b9bcbef231dfdd6e64979bef216c7b3e7af7a75/src/sentry/api/serializers/models/project.py#L46)):*
<details><summary><i>Previously, mattrobenolt (Matt Robenolt) wrote…</i></summary>
> >         default_environments = {
> >                 o.project_id: o.value
> >                 for o in ProjectOption.objects.filter(
> >                     key='sentry:default_environment',
> >                     project__in=project_ids,
> >                 )
> >             }
> 
> ```python
> default_environments = dict(ProjectOption.objects.filter(key='sentry:default_envirnment', project__in=project_ids).values_list('project_id', 'value'))
> ```
> 
> Should be a bit more efficient.
</details>
I dont believe value() decodes things correctly (IIRC).

---

*[src/sentry/static/sentry/app/components/group/sidebar.jsx, line 25 \[r3\]](https://reviewable.io:443/reviews/getsentry/sentry/3764#-KNDWF0a364eoyfJNkwt:-KNDmVElqC0F2Jwi-cyc:1201932001) ([raw file](https://github.com/getsentry/sentry/blob/9b9bcbef231dfdd6e64979bef216c7b3e7af7a75/src/sentry/static/sentry/app/components/group/sidebar.jsx#L25)):*
<details><summary><i>Previously, macqueen (Jess MacQueen) wrote…</i></summary>
> should this just be deleted? 
</details>
Yeah I'll kill it. I was leaving it here since I was considering implementing it, but I dont think its reasonable to try since it breaks subcomponents.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3764)*

**Comment by mattrobenolt** [comment]
Review status: 15 of 32 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/sentry/api/serializers/models/project.py, line 46 \[r3\]](https://reviewable.io:443/reviews/getsentry/sentry/3764#-KNDjJpns3idZiKbyPku:-KNDmmx2a5v8IA9CtEsT:-1859676679) ([raw file](https://github.com/getsentry/sentry/blob/9b9bcbef231dfdd6e64979bef216c7b3e7af7a75/src/sentry/api/serializers/models/project.py#L46)):*
<details><summary><i>Previously, dcramer (David Cramer) wrote…</i></summary>
> I dont believe value() decodes things correctly (IIRC).
</details>
Ah, right. Since this `value` isn't exactly what's in the database. Nevermind.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3764)*

**Comment by dcramer** [comment]
Review status: 15 of 32 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[src/sentry/api/endpoints/group_environment_details.py, line 25 \[r3\]](https://reviewable.io:443/reviews/getsentry/sentry/3764#-KNDi_7uyrK67WBzBkKK:-KNDo9jhPbqFJ8M2w9CZ:-499146009) ([raw file](https://github.com/getsentry/sentry/blob/9b9bcbef231dfdd6e64979bef216c7b3e7af7a75/src/sentry/api/endpoints/group_environment_details.py#L25)):*
<details><summary><i>Previously, mattrobenolt (Matt Robenolt) wrote…</i></summary>
> >       try:
> >             first_release = GroupRelease.objects.filter(
> >                 group_id=group.id,
> >                 environment=environment,
> >             ).order_by('first_seen')[0]
> >         except IndexError:
> >             first_release = None
> 
> Can we simplify these to `.first()` calls?
> 
> ```python
> first_release = GroupRelease.objects.filter(
>     group_id=group.id,
>     environment=environment,
> ).order_by('first_seen').first()
> ```
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3764)*

**Comment by dcramer** [comment]
Review status: 15 of 32 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/sentry/static/sentry/app/components/group/sidebar.jsx, line 25 \[r3\]](https://reviewable.io:443/reviews/getsentry/sentry/3764#-KNDWF0a364eoyfJNkwt:-KNDpX4zjMTYU6BDhXJe:-499146009) ([raw file](https://github.com/getsentry/sentry/blob/9b9bcbef231dfdd6e64979bef216c7b3e7af7a75/src/sentry/static/sentry/app/components/group/sidebar.jsx#L25)):*
<details><summary><i>Previously, dcramer (David Cramer) wrote…</i></summary>
> Yeah I'll kill it. I was leaving it here since I was considering implementing it, but I dont think its reasonable to try since it breaks subcomponents.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3764)*

**Comment by mattrobenolt** [comment]
Reviewed 4 of 31 files at r1, 1 of 2 files at r4.
Review status: 20 of 32 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3764)*

**Pull request merged**
