### PR TITLE
fix(issues): Correct handling of tags with issue context

### PR DESCRIPTION
**Pull request by dcramer**

### CODE REVIEW

**Review by evanpurkhiser — APPROVED** [review]
🍪

**Comment by dcramer** [comment]
Found another minor issue and including a compat fix.

**Comment by dcramer** [comment]
I noticed that linking an issue doesnt seem to actually show the success message

**Comment by dcramer** [comment]
I also noticed that when an issue has an external issue ID associated it adds some bottom margin/padding to the header row /cc @EvanPurkhiser @ckj

**Review by evanpurkhiser — APPROVED** [review]
Took a look again, looks good.

**Comment by EvanPurkhiser** [comment]
Would be nice if there were any tests for this.

**Comment by dcramer** [comment]
@EvanPurkhiser i added one to the mail stuff

**Pull request merged**
