### PR TITLE
build(ci): Change `acceptance` workflow back to `pull_request`

### LINKED ISSUE #22432: GitHub Actions: Avoid using `pull_request_target`
GitHub Actions (GHA) does not expose repo secrets to PRs opened from a fork. This breaks for our custom and required workflows (e.g. Visual Snapshots). To workaround this we opted to use the workflow event: `pull_request_target` which allows forks access to secrets, with some limitations. The major one being that it only runs the workflow defined on the base branch (e.g. master).

This event also, by default, checks out the repo from the base PR branch (master). In our workflow, we need to check out the fork branch to test, but by doing so we expose ourselves to the user’s code which can pull out and reveal our secrets.

Our current “secrets” are pretty harmless at the moment: 1) visual snapshots API key, which only allows you to upload snapshots (but doesn't get passed to usercode), and 2) secret to verify webhook payload for webpack metrics. However, this will end up being overlooked in the future, and we should change this before it gets to that point.

The solution here is to 1) never use `pull_request_target` for workflows that requires you to checkout/run your repository's code and 2) use `workflow_run` instead.

I have a PR incoming that will address this issue, but wanted to create this issue so that it's documented.

### PR DESCRIPTION
**Pull request by billyvg**
Closes #22432

### CODE REVIEW

**Comment by billyvg** [comment]
Unfortunately, this is another workflow event that only uses the workflow from `master` branch -- you can see it working here:

- Uses `workflow_run`: https://github.com/billyvg/sentry/pull/51
https://github.com/billyvg/sentry/pull/51/checks?check_run_id=1494316314
- Uses `pull_request_target`: https://github.com/billyvg/sentry/pull/52
https://github.com/billyvg/sentry/pull/52/checks?check_run_id=1494640586

**Comment by billyvg** [comment]
This will probably break PRs as they will need to rebase so that the acceptance workflow runs.

**Review by joshuarli — APPROVED** [review]
What about `js-getsentry-dispatch.yml`?

**Comment by billyvg** [comment]
@joshuarli So the difference there is that 1) it does not depend on a workflow and 2) we do not check out and run downstream code (it checks out code from master, but we only use `file-filters.yml`). In the acceptance workflow we were checking out the fork's code and running it, allow the user to extract secrets that are used in that workflow.

**Comment by joshuarli** [comment]
> @joshuarli So the difference there is that 1) it does not depend on a workflow and 2) we do not check out and run downstream code (it checks out code from master, but we only use `file-filters.yml`). In the acceptance workflow we were checking out the fork's code and running it, allow the user to extract secrets that are used in that workflow.

Oh duh, that makes sense. Thanks.

**Pull request merged**
