### PR TITLE
Add lxml

### PR DESCRIPTION
**Pull request by davedash**
I had a few false starts doing pip install sentry, somewhere in the chain lxml got lost (probably a dependency of another library).

### CODE REVIEW

**Comment by mattrobenolt** [comment]
Hmm, this is coming from toronado. So it's a subdependency.

**Comment by mattrobenolt** [comment]
Specifically: https://github.com/disqus/toronado/blob/master/setup.py#L10

So not sure what happened for you to get into that state?

**Comment by davedash** [comment]
Yes, it is.  So the scenario is this:

1. run `pip install sentry[postgres]`
2. Have it fail because your missing `libxml2-dev` on ubuntu
3. re-run `pip install sentry[postgres]` and everything seems fine
4. run `sentry` and oops couldn't find `lxml`.

I'm a bit preplexed why step 3 wouldn't re-install tornado, but `pip` has some thorny edges.

**Comment by mattrobenolt** [comment]
Oh, so it's only the case when it failed to install libxml in the first place from missing dependency? Does declaring it explicitly in our setup.py actually rectify that?

**Comment by davedash** [comment]
Yes because it will check setup.py and explicitly  check for lxml.

**Comment by mattrobenolt** [comment]
Interesting. tbh, that seems like a thing that pip should handle, but this works for me in the meantime.

Thanks. :)

/cc @dstufft

**Comment by dstufft** [comment]
What version of pip ?  This should be somewhat fixed in pip 6

**Pull request merged**
