### PR TITLE
Use svg-sprite-loader

### PR DESCRIPTION
**Pull request by Chrissy**
This is tested and works on ie, chrome, and firefox. [svg-sprite-loader](https://github.com/kisenka/svg-sprite-loader) takes advantage of `use` to create an svg sprite that get's webpacked in without the transpiling you get with other loaders.

The setup is actually very simple and makes it much easier to export and import things between sketch and the app.

I included the [svgo loader](https://github.com/rpominov/svgo-loader/issues/6) as an added free bonus 🌈 🎁 🦄 

To keep things low-risk, this pull only changes two icons: `icon-copy` and `icon-refresh`, which are both used in `shareIssue.jsx` and are super easy to test. 

A follow-up pull will change the other 10 or so svg icons in the codebase.

### CODE REVIEW

**Comment by getsentry-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Review by dcramer — APPROVED** [review]
lgtm

if you break production though its on youuuuuu

**Comment by Chrissy** [comment]
@dcramer thanks lol. Did you catch the [inline svg component](https://github.com/getsentry/sentry/pull/6764/files)? Wanna make sure it didn't get lost in all the svg changes.

**Comment by Chrissy** [comment]
also to anyone who cares: i'm gonna finish changing over all these svgs in another pull to help simplify the process of releasing this thing

**Pull request merged**
