### PR TITLE
ref(icons): removing unused icons

### PR DESCRIPTION
**Pull request by doralchan**
Removed unused icons

### CODE REVIEW

**Comment by markstory** [comment]
Are the rookout and clubhouse icons used by those integrations?

**Comment by doralchan** [comment]
No - I think integrations are using the ones in the images/logos folder

**Comment by billyvg** [comment]
Did you check getsentry to see if these were used?

**Comment by doralchan** [comment]
Screen Shot 2020-02-07 at 11 21 36 AM
Screen Shot 2020-02-07 at 11 21 25 AM

Yep - integrations are using the logo images

**Comment by doralchan** [comment]
getsentry is only using icon-forward once and I'm in the process of updating that to icon-warning since it's an alert that notifies the user information is missing

**Review by ckj — APPROVED** [review]
💯

**Pull request merged**
