### PR TITLE
fix(ui): refactored styles into base.less

### PR DESCRIPTION
**Pull request by robinrendle**
## What 

In this PR I’m combining all the styles for HTML elements without classes + the normalize stuff. In the future this `base.less` file is where all our default HTML styles should go. `html`, `body`, heading styles, etc. 

## Why

Right now our styles are all over the place. Some live in Bootstrap, some are custom styles, others are written in Emotion. We also have a lot of custom styles that are completely unnecessary and lots of instances of people using `div`s when they should use HTML elements. But they don’t because those base styles are weird and unpredictable. So if we combine all our styles into one place and refactor them all we should be able to decrease how much CSS we write to do basic stuff like add headings to a page.

This is just the first step in that refactor process. Next thing to go is that `text.tsx` file.

### CODE REVIEW

**Comment by markstory** [comment]
Most of the changes look better. The changes to spacing of the MutedBox/EventErrors on the issue details page make the icons misaligned. The margins/positioning on those icons likely needs to be adjusted.

**Comment by robinrendle** [comment]
@markstory @billyvg fixed the BannerSummary component which should fix those icon issues.

**Comment by billyvg** [comment]
@robinrendle The header size for `acceptance/project-data-forwarding-settings.png` is off

**Comment by robinrendle** [comment]
@billyvg I’d say that’s a visual improvement — today it looks way too big and goofy.

**Comment by markstory** [comment]
`acceptance/list-organization-members.png` looks like the button is being stretched via flexbox. Same with `acceptance-mobile/list-organization-members.png`

**Comment by billyvg** [comment]
@robinrendle besides mark's comment I think everything else looks good? we will want to check first though

**Review by markstory — APPROVED** [review]
Visual diffs look good to me.

**Pull request merged**
