### PR TITLE
fix(integrations): Handle IntegrationErrors in commit task

### PR DESCRIPTION
**Pull request by macqueen**

### CODE REVIEW

**Comment by mnoble** [comment]
What's `IntegrationError` mean in this case?

**Comment by macqueen** [comment]
@mnoble  if something goes wrong with the external request that allows us to sync commits, an IntegrationError is raised, for example: https://sentry.io/sentry/sentry/issues/657878432/

Right now, the commit fetching failure emails are all defaulting to the generic `An internal system error occurred.` when they should provide users more detail because we're not handling the `IntegrationError`

**Review by mnoble — APPROVED** [review]
Looks good. Just curious if this is going to lead to spam.

**Comment by macqueen** [comment]
it shouldn't. now we're just spamming them with an unhelpful/incorrect message. this will make the message potentially actionable for them, which is what we want

**Pull request merged**
