### PR TITLE
Drop back to global CoC

### PR DESCRIPTION
**Pull request by chadwhitacre**
We don't need a separate CoC in this repo. By removing this we will fall back to [the global one in the .github repo](https://github.com/getsentry/.github/blob/main/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Review by hubertdeng123 — COMMENTED** [review]
Do we want to remove the CoC files in other repos too as well then?
https://github.com/search?q=org%3Agetsentry+CODE_OF_CONDUCT&type=code&p=1

**Comment by chadwhitacre** [comment]
I did do a search, the only one I found that wasn't in a fork was https://github.com/getsentry/eng-pipes/pull/472. Are there others I'm missing? Should we remove in forks as well?

**Review by asottile-sentry — APPROVED** [review]

**Comment by hubertdeng123** [comment]
@chadwhitacre found a few more:
- [sentry-ruby](https://github.com/getsentry/sentry-ruby/blob/525890073baf80f12ba48edc77af36753fde6c3f/sentry-ruby/CODE_OF_CONDUCT.md)
- [security-panther-analysis](https://github.com/getsentry/security-panther-analysis/blob/768a06f235e779b2d46aaf30042d40a94ccda25a/CODE_OF_CONDUCT.md) (it's private though)
- [cloud-run-typescript-template](https://github.com/getsentry/cloud-run-typescript-template) (not sure if still used?)

**Comment by chadwhitacre** [comment]
Let's move convo to https://github.com/getsentry/team-ospo/issues/149#issuecomment-1577521440 (new ticket).

**Pull request merged**
