### PR TITLE
Fix/slack message title limit

### PR DESCRIPTION
**Pull request by SamHausmann**

### CODE REVIEW

**Comment by EvanPurkhiser** [comment]
Have you tested this with longer titles @SamHausmann? I think I was under the impression there was a length limit to slack titles.

**Comment by SamHausmann** [comment]
@EvanPurkhiser the limit 97 characters as far as I can tell but this would at least double the amount we could see of our actual error messages. I could foresee a more fault tolerant implementation of this to be adding an option to not show the culprit context in the slack message but I don't have the bandwidth right now to do a PR for that and make sure that option is propagated to all the appropriate places. 

At least in this case the the truncation is left to Slack which I don't think we could override anyway.

**Comment by dashed** [comment]
@SamHausmann is there a reference indicating that the limit is 97 characters? My Google-fu seems to be failing me.

**Comment by SamHausmann** [comment]
@dashed I've reached out to Slack for confirmation

**Comment by EvanPurkhiser** [comment]
It's unfortunate that the culprit will likely be cutoff often in that case, since it's pretty often that group titles are going to be longer

**Comment by SamHausmann** [comment]
@EvanPurkhiser agreed. Our hope is we can potentially at least double the amount of the error message that we currently get. Slack responded with a request for screenshots but hasn't replied since so I'm going to bump.

**Review by evanpurkhiser — APPROVED** [review]

**Pull request merged**
