### PR TITLE
fix(user_options) Deprecate alert_email user option

### PR DESCRIPTION
**Pull request by evanh**
There is no place to update this option through the frontend, but there are
still a few users kicking around with this value set. We're going to send an
email to them, and then deploy this change to default to the primary email
address instead.

### CODE REVIEW

**Review by markstory — COMMENTED** [review]
Will there be a follow up migration to delete the options entirely?

**Comment by evanh** [comment]
Yes. I'll open a separate PR for that though.

**Review by markstory — APPROVED** [review]

**Comment by evanh** [comment]
@adhiraj This PR will be released on Feb 10. We're sending an email to communicate this change first.

**Comment by adhiraj** [comment]
quick update, this will go out jan 28

**Pull request merged**
