### PR TITLE
append trailing slashes in react router

### LINKED ISSUE #2028: Automatically redirect URLs without trailing slash
When a route doesnt match we'd like to redirect to the same URL with a trailing slash (or at least determine if there would be one that would match).

This is purely on the React side.

### PR DESCRIPTION
**Pull request by mattrobenolt**
I couldn't find a better way to do this, but version 1.0 supposedly supports this behavior.

fixes GH-2028

### CODE REVIEW

**Comment by benvinegar** [comment]
Did you try doing this programatically?

**Comment by mattrobenolt** [comment]
Got an example?

Ideally, I'd have a catch-all that did like:  `[^/]$` and rewrote it. But `react-router` doesn't handle real regular expressions.

**Comment by mattrobenolt** [comment]
Actually, lemme try this inside the `RouteNotFound` view.

**Comment by dcramer** [comment]
Ideally this would be a transition handler (or the NotFoundHandler if thats capable enough)

**Comment by benvinegar** [comment]
> Ideally, I'd have a catch-all that did like: [^/]$ and rewrote it. But react-router doesn't handle real regular expressions.

Sure, but I meant as an alternative to writing out each redirect manually, traversing the declared route elements, and for each route generating a corresponding redirect element (e.g. via `React.createElement`).

> RouteNotFound

Seems like a good idea.

**Pull request merged**
