### PR TITLE
build: Configure zeit for build previews

### PR DESCRIPTION
**Pull request by evanpurkhiser**
Prepares sentry to be deployed by zeit.

You can test this right now by just running `npx now` on your checkout of sentry

### CODE REVIEW

**Comment by markstory** [comment]
Would we be using this for pull request previews in place of netlify?

**Review by cameronmcefee — APPROVED** [review]

**Review by billyvg — APPROVED** [review]
\o/ thanks @EvanPurkhiser -- Is there a GitHub status check so that we can get the link to the preview build?

**Review by dashed — APPROVED** [review]
Looks like zeit to me 👍

**Comment by EvanPurkhiser** [comment]
> Would we be using this for pull request previews in place of netlify?

Yup

**Pull request merged**
