### PR TITLE
feat(ingest): Enable Relay in Sentry configuration

### PR DESCRIPTION
**Pull request by RaduW**
Enable Relay integration by default

### CODE REVIEW

**Review by jan-auer — APPROVED** [review]

**Comment by joshuarli** [comment]
@RaduW @jan-auer Just wondering, is there a plan to remove `SENTRY_USE_RELAY` soon (that would imply that the legacy code paths that relay replaces are all removed)?

**Comment by untitaker** [comment]
@joshuarli yes but no reliable ETA yet imo

**Comment by jan-auer** [comment]
We were going to remove python store soon after https://github.com/getsentry/onpremise/pull/421 is merged, which is in its final stages now. 

The flag `SENTRY_USE_RELAY` will probably stay, however, so that people can remove Relay from their dev setup, if they do not need to ingest events.

**Comment by joshuarli** [comment]
> The flag SENTRY_USE_RELAY will probably stay, however, so that people can remove Relay from their dev setup, if they do not need to ingest events.

Oh, this would be really good!

**Pull request merged**
