### PR TITLE
Add global asset version

### PR DESCRIPTION
**Pull request by dcramer**
This switches away from the individual file versions (due to it being very complex to clean them up) onto a global static versioning system.

### CODE REVIEW

**Comment by dcramer** [comment]
This probably isnt good enough. An alternative would be this:

- keep the default generated asset version in dev (the time())
- generate an asset version as part of build_static (or something) that just md5's every damn file in Sentry
- figure out how this is going to play nicely with getsentry (ideally the md5 goes onto the result of collectstatic)

**Comment by mattrobenolt** [comment]
> generate an asset version as part of build_static (or something) that just md5's every damn file in Sentry

I did this before by generating md5's of every file, then taking an md5 of that manifest to treat as the "asserts version".

> figure out how this is going to play nicely with getsentry (ideally the md5 goes onto the result of collectstatic)

This goes to what @benvinegar and I talked about the other day, I think. Is that ideally, our getsentry build system would compile sentry as a part, instead of these two separate builds.

But with that said, if we leave getsentry files un-versioned, do you think that's ok here?

**Comment by dcramer** [comment]
We can't not version getsentry's files (at least not easily) as it runs through the sentry toolchain

**Comment by mattrobenolt** [comment]
For posterity, this is how I've generated the master version in the past:

```
% md5sum $(find static -type f) | md5sum | awk '{print $1}'
```

Something like that, so it generates a checksum file of all files, then does an md5 of the checksum output.

**Pull request merged**
