### PR TITLE
fix(onboarding): Render the list of Go frameworks in create project UI and framework modal

### LINKED ISSUE #59017: Go project creation lacks some integrations
grafik

We should add

- https://docs.sentry.io/platforms/go/guides/gin/ (supports panic reporting & performance)
- https://docs.sentry.io/platforms/go/guides/echo/ (supports panic reporting)
- https://docs.sentry.io/platforms/go/guides/fasthttp/ (supports panic reporting)

### PR DESCRIPTION
**Pull request by natikgadzhi**
## Summary

This PR fixes a bug where the list of Go frameworks won't show up in the framework selection modal in the create project flow. Fixes #59017. /cc @cleptric 

The expected behavior is that the list of Go frameworks shows up in:
- Create project screen in "server" tab.
- The modal that shows up when you tap "create" when Go is selected as the language.

## Changes

Initially, in #47618 we've added the framework modal, and than in #53845 we've added Go to the list of languages for which the framework modal would show up. But the list of frameworks was just filtering the list of `createablePlatforms`. This PR adds go frameworks to that list. 

See the overview: https://www.loom.com/share/ed697055cff944dea0d268a6e0eecadd

## Review

This is my first pull request in Sentry, so be cautious. 
- Git pre-push hook was not happy: 
  ```
  fix end of files.........................................................Failed
  - hook id: end-of-file-fixer
  - exit code: 1
  - files were modified by this hook
  
  Fixing tests/symbolicator/fixtures/test.min.js
  ```

  Since I didn't touch the fixture, I pushed with `--no-verify`, but happy to redo. 

- I did not yet verify this locally. I'll try to setup my databases locally, or roll this commit SHA into a dockerized self-hosted version. The change is trivial, though. 

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Review by ArthurKnaus — APPROVED** [review]
Big thx for fixing that! 🎉

**Comment by smeubank** [comment]
thank you @natikgadzhi !

**Comment by natikgadzhi** [comment]
You're very welcome! Do you think you have a few more issues for me to work on? ;-) I've seen a few around Performance / tracing frontend, but curious about the backend pieces as well!

**Pull request merged**
