### PR TITLE
Initial Percy integration and acceptance tests.

### PR DESCRIPTION
**Pull request by fotinakis**
Integration with the new [python-percy-client](https://github.com/percy/python-percy-client) for visual regression tests.

Those in the `getsentry` org should be able to login to Percy and see this build:
https://percy.io/getsentry/sentry/builds/76523

Here are some examples though:
screen shot 2016-06-15 at 6 12 58 pm
screen shot 2016-06-15 at 6 13 17 pm
screen shot 2016-06-15 at 6 13 29 pm

I ended up having to do some fairly strong class-level initialization in order to re-use the Selenium browser object and to do the Percy initialization/finalization. There's a comment in there that eventually you could figure out a better strategy, probably a pytest plugin, if you end up writing tons of acceptance tests in Sentry and want to split them up across files.

Not done yet:
- You will need to set the `PERCY_TOKEN` and `PERCY_PROJECT` environment variables in your Travis CI config in order to enable Percy in CI.

### CODE REVIEW

**Comment by fotinakis** [comment]
Good to go here @dcramer ! Merge at will, or let me know if you'd like to change anything.

I realized we weren't calling `npm install` for the acceptance tests at all, so I added that to the makefile as well as cherry-picking your karma phantomjs loader commit and things work both locally and in CI.

Another note I realized: for security, Travis CI [does not expose ENV vars to PRs that come from forks](https://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables) (otherwise, random people could steal data from environment variables). Unfortunately, this means Percy will only run on PRs that you guys create in the repo, not from forks. I guess when you merge fork PRs into master and your master tests run, you'll be able to see the changes then.

**Comment by dcramer** [comment]
:+1:

Will clean up some things post-mege

**Comment by dcramer** [comment]
Locally I actually don't seem to have phantomjs binary based on the package.json changes (also unclear why I would). I'm investigating.

**Comment by dcramer** [comment]
```
npm WARN karma-phantomjs-launcher@1.0.0 requires a peer of phantomjs-prebuilt@>=1.9 but none was installed.
```

so same error -- im vendoring that library since no ones fixing it

**Comment by fotinakis** [comment]
That's just a warning, is there still a binary in `./node_modules/phantomjs-prebuilt/bin/phantomjs`? If so it might be fine to ignore.

**Pull request merged**
