### PR TITLE
chore(ts): Convert clippedBox

### PR DESCRIPTION
**Pull request by evanpurkhiser**
Also removes findDomNode

### CODE REVIEW

**Review by billyvg — COMMENTED** [review]
Seems to work but ts errors: https://storybook.getsentry.net/branches/evanpurkhiser-chorets-convert-clippedbox/index.html?path=/story/ui-clippedbox--default

**Comment by EvanPurkhiser** [comment]
Yeah I'll figure out what's going on here

**Comment by EvanPurkhiser** [comment]
Looks like there were a few bugs in usage of this. I fixed them, but we may now have some behavior that will change in the stack trace context values component because of the fix.

Lets see what percy says.

**Comment by billyvg** [comment]
Yeah this change in behavior does not seem great since it covers up a bit too much. Seems like it's not calculating the height correctly?

**Comment by EvanPurkhiser** [comment]
someone else converted :)

**Comment by priscilawebdev** [comment]
@EvanPurkhiser it was me 😁 sorry I didn't see this PR before.

**Pull request closed without merging**
