### PR TITLE
fix(monitors): Correct cache for monitors error creation

### PR DESCRIPTION
**Pull request by davidenwang**
For more than a year now we've been failing to fetch event data from the right cache in `preprocess_event` because it seems like we should be using the `event_processing_store` instead of `default_cache`.

### CODE REVIEW

**Review by wedamija — COMMENTED** [review]
This looks good to me. @untitaker old reprocessing uses this path as well, is that used at all?

**Review by jjbayer — COMMENTED** [review]
This change makes sense to me. Should we add a test though, that proves that data could not be fetched before?

**Comment by davidenwang** [comment]
> This change makes sense to me. Should we add a test though, that proves that data could not be fetched before?

hmm we could try to add a test but it might be rather difficult since it seems like this was working before in a local environment since the event processing and default cache are shared. Only in getsentry is there a configuration to use a different cache, though correct me if i'm wrong here.

**Comment by jjbayer** [comment]
> this was working before in a local environment since the event processing and default cache are shared

That's a good point. You could probably change `SENTRY_EVENT_PROCESSING_STORE` to a simple in-memory store for the scope of the test, but I'm not sure if it's worth the effort.

**Review by jjbayer — APPROVED** [review]

**Comment by davidenwang** [comment]
> > this was working before in a local environment since the event processing and default cache are shared
> 
> That's a good point. You could probably change `SENTRY_EVENT_PROCESSING_STORE` to a simple in-memory store for the scope of the test, but I'm not sure if it's worth the effort.

Sounds good gonna merge for now to unblock some monitors work. The test for this does seem a little unnecessary/cumbersome especially for this deprecated code path, but let me know if you would still want it I can try to do it in a follow up.

**Pull request merged**
