### PR TITLE
feat(replays): Make replayId a default column on Discover views

### LINKED ISSUE #39716: Discover: Default to showing the `replayId` in the discover table when replays are enabled
Currently in the Discover > All Events page users need to configure columns to see the replayId of an event, if that field is not empty.

We should show that column by default, if the replay ui feature is enabled, so that people can get quick access to the replay that an event is part of.

Image

See also #39713

### PR DESCRIPTION
**Pull request by danecando**
This PR makes the default fields used on the discover view include replayId and the replay link button if the feature is enabled.

### Changes
- Adds `replayId` to the `fields` array on `DEFAULT_EVENT_VIEW` if the replay feature is enabled

### Checks
The updated `results` component is only used in `/discover/*` pages. The replayId only gets added if there's not a saved query to display for the discover view

Closes #39716 

Screen Shot 2022-11-03 at 9 39 35 AM

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Review by edwardgou-sentry — APPROVED** [review]

**Review by narsaynorath — APPROVED** [review]
Looks good to me, but in testing we noticed some odd behaviour with applying an aggregate column after the fact. It's not related to this PR but figured we'd just raise it

https://user-images.githubusercontent.com/22846452/199759260-6e9fafbf-7662-4f45-8267-44c09578025d.mov

**Review by ryan953 — APPROVED** [review]

**Comment by ryan953** [comment]
> Looks good to me, but in testing we noticed some odd behaviour with applying an aggregate column after the fact. It's not related to this PR but figured we'd just raise it
> 
>  Screen.Recording.2022-11-03.at.11.06.51.AM.mov

@narsaynorath can you show the specific query/fields you've used here? and/or the url that the Replay button points towards?

**Comment by narsaynorath** [comment]
@ryan953 Yeah sure, I didn't have any particular query but for columns I used "replayId" and "count()". The resulting URL was `/organizations/sentry/replays/undefined:ffff931577fe4a148020b64590897750/?referrer=%2Forganizations%2F%3AorgId%2Fdiscover%2Fhomepage%2F` so it seems like the project slug was undefined and it looks like it's undefined anytime a function is being applied

**Comment by danecando** [comment]
Nice find thanks for reporting this. I created an issue for it here: https://github.com/getsentry/sentry/issues/40981 If you want to add any tags to it Ryan

**Pull request merged**
