### PR TITLE
feat(email): Map tags aliases to Snuba names in error email

### PR DESCRIPTION
**Pull request by lynnagara**
Correctly map the sentry:release, sentry:dist and sentry:user
properties.

Fixes APP-1094

### CODE REVIEW

**Comment by lynnagara** [comment]
Do we want this behavior everywhere this function is used?

**Comment by alex-hofsteede** [comment]
Can we be really careful here, I'm not sure if `get_tags()` is also used somewhere on the ingestion path, and translating these like this on the way in would cause a bunch of issues as snuba is expecting the payload to contain `sentry:release` etc. 

Also doesn't this already happen in serialization here: https://github.com/getsentry/sentry/blob/master/src/sentry/api/serializers/models/event.py#L94

**Comment by lynnagara** [comment]
Updated to just fix that one email, this might be the only place we actually want to change anything

**Review by markstory — APPROVED** [review]
Translating the tag keys only in the emails is safer than on the event methods :+1:

**Pull request merged**
