### PR TITLE
feat(assistant): Remove Assistant from Mobile

### PR DESCRIPTION
**Pull request by ehfeng**
Assistant isn't mobile optimized. Removing it with a media query for now.

### CODE REVIEW

**Review by Chrissy — APPROVED** [review]

**Comment by Chrissy** [comment]
we should probably create some breakpoints at some point but w/e for now

**Comment by ehfeng** [comment]
How so?

**Comment by Chrissy** [comment]
in theme we should do something like:

```mobile:

**Comment by Chrissy** [comment]
woops lol

**Comment by Chrissy** [comment]
in theme we should do something like:

```
unsupported: '360px',
smallHandheld: '900px',
handheld: '900px',
smallDesktop: '1200px'
//etc
```

but this is definitely within my realm of problems so don't worry about it haha.

**Pull request merged**
