### PR TITLE
feat(replays): Light HTMLCode highlighting theme

### PR DESCRIPTION
**Pull request by danecando**
### Changes
- Adds a new theme based on sentrys prism code highlighting theme to match more closely with new DOM Events mock up
- Loads light theme or dark theme based on user mode

Part of #37973 

Light Mode 
Screen Shot 2022-08-22 at 9 48 06 AM

Dark Mode

Screen Shot 2022-08-30 at 3 21 41 PM

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Comment by billyvg** [comment]
Does the theme update when we switch to dark mode?

**Comment by danecando** [comment]
> Does the theme update when we switch to dark mode?

I guess we could do something like this?
```
  useEffect(() => {
    if (ConfigStore.get('theme') === 'dark') {
      import('prism-sentry/index.css').then(() => {
        Prism.highlightElement(codeRef.current, false);
      });
    } else {
      import('sentry/styles/prism-sentry-light.css').then(() => {
        Prism.highlightElement(codeRef.current, false);
      });
    }
  }, []);
```

Webpack is not pleased with the dynamic imports though

**Comment by billyvg** [comment]
I think the dark bg > light bg for both light/dark modes (then again I'm a dark bg editor). Will leave it up @Jesse-Box or @ryan953

**Comment by Jesse-Box** [comment]
> I think the dark bg > light bg for both light/dark modes (then again I'm a dark bg editor). Will leave it up @Jesse-Box or @ryan953

So i realise now that sentry **intentionally** created a dark prism theme for a light themed page and my proposal runs **counter** to that decision. As much as it sucks, I think leaving the theme as it is today is the best solution we have until I can reach out to the design team to discuss this further.

**Comment by danecando** [comment]
Closing for now. See Jesse's comment for details

**Pull request closed without merging**
