### PR TITLE
feat(discover): Surface split decision through events-stats meta

### PR DESCRIPTION
**Pull request by narsaynorath**
Surfaces the split decision through the endpoint response meta for dashboard queries.

### CODE REVIEW

**Review by mjq — APPROVED** [review]

**Review by shruthilayaj — APPROVED** [review]
looks good, though should we also update the dataset it queries?
ie instead of `transactions_only_query = f"({query}) AND event.type:transaction"`, query the transaction dataset etc?

**Comment by narsaynorath** [comment]
@shruthilayaj I'll put up another PR for that! I was just keeping this for adding the meta value. Would you mind taking another quick glance? I had to fix a typing issue to handle top-events queries. My changes prior only handled one SnubaTS result.

**Comment by shruthilayaj** [comment]
@narsaynorath let's make sure the test cases cover both result types?

**Comment by narsaynorath** [comment]
@shruthilayaj thanks for calling that out. I put up the code change too quickly and assumed top events had the same access path. Turns out, `meta` might not exist so my code was incorrect. I've fixed it and added tests in the latest commit: 1769c52bfcbda9ad24ddebf58355a19d19006532

**Pull request merged**
