### PR TITLE
Remove phantomjs-prebuilt devDependency

### PR DESCRIPTION
**Pull request by mattrobenolt**
Until we figure out why this breaks our builds

@benvinegar

### CODE REVIEW

**Comment by benvinegar** [comment]
👍

**Comment by fotinakis** [comment]
Btw this now breaks the acceptance tests, since adding `phantomjs-prebuilt` to package.json was the way we decided to ensure that dev environments had phantomjs installed.

**Comment by mattrobenolt** [comment]
Yeah, of course. :) We need to figure out if/how we can get this back in without causing issues. 

From my understanding, the problem is because we try to install two different versions of Phantom now. This top level one, adpnd the one we use for our tests. And phantom wasn't happy about this.

**Comment by dcramer** [comment]
What is "the top level one"? Both Phantom is only used for tests. Can we not just use the same binary for both unit tests and the selenium tests?

**Comment by mattrobenolt** [comment]
This phatomjs-prebuilt was causing issues with the phantom we use as a subdependency for tests. These are also major version bumps, so I'm not sure if the Selenium tests can use the older version we already have installed for our JS test runner. I don't have enough context on this besides what @benvinegar told me. :)

**Comment by fotinakis** [comment]
It looks like we can probably transitively use `node_modules/phantomjs/lib/phantom/bin/phantomjs` instead of phantomjs-prebuilt. Will try that and let you know.

**Comment by mattrobenolt** [comment]
> It looks like we can probably transitively use node_modules/phantomjs/lib/phantom/bin/phantomjs instead of phantomjs-prebuilt.

I don't think it's safe to do that, especially between different versions of `npm`. Since `npm3` will lay files out differently on disk.

For example, my subdependency is at: `node_modules/karma-phantomjs-launcher/node_modules/phantomjs/bin/phantomjs`

**Comment by mattrobenolt** [comment]
With `npm@3.8.9`, I get:

```
$ ag -g bin/phantomjs node_modules
node_modules/phantomjs/bin/phantomjs
node_modules/phantomjs/lib/phantom/bin/phantomjs
```

And with `npm@2.15.6`, I get:

```
$ ag -g bin/phantomjs node_modules
node_modules/karma-phantomjs-launcher/node_modules/phantomjs/bin/phantomjs
node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom/bin/phantomjs
```

**Comment by fotinakis** [comment]
Makes sense—ok going to defer this until later, we can work around it for developing the addon just something we'll have to address for your acceptance tests later.

**Pull request merged**
