### PR TITLE
py38: Django 2.0

### PR DESCRIPTION
**Pull request by joshuarli**
Dependencies which will be separated into individual PRs:

- Trivial deprecation changes (done in various PRs)
- django-sudo porting (done https://github.com/getsentry/sentry/pull/26602, https://github.com/getsentry/sentry/pull/26646)
- port to new style middleware, since we can't use MIDDLEWARE_CLASSES in 2.0 anymore (https://github.com/getsentry/sentry/pull/26193 and https://github.com/getsentry/sentry/pull/26694)
- https://github.com/getsentry/sentry/pull/26980
- Plenty of getsentry things.

Other notable PRs discovered here:

- https://github.com/getsentry/sentry/pull/26696
- https://github.com/getsentry/sentry/pull/26745
- https://github.com/getsentry/sentry/pull/27326
- https://github.com/getsentry/sentry/pull/27382

Prerequisite testing:

- X-Django model pickling testing passed, see https://github.com/getsentry/sentry/tree/joshuarli/test-x-django-pickles
- `LAST_VERIFIED_DJANGO_VERSION` verification (done https://github.com/getsentry/sentry/pull/26644)
- X-Django event ingestion (just to be a little more thorough, locally + s4s rollout will test this)

More due dilligence:

- the great warnings saga https://github.com/getsentry/sentry/pull/26796

### CODE REVIEW

**Comment by joshuarli** [comment]
Ok, so at this point after rebasing atop my little middleware refactor, this `sentry.utils.retries.RetryException: <unprintable RetryException object>` is a result of django-sudo. All those tests pass with my WIP django-sudo changes.

So gonna finish updating django-sudo, then assuming most things look good here, get that and the middleware refactor merged, then gonna continue chipping away at this.

**Comment by joshuarli** [comment]
```
FAILED tests/sentry/incidents/endpoints/test_project_alert_rule_details.py::AlertRuleDetailsPutEndpointTest::test_no_owner
FAILED tests/sentry/incidents/endpoints/test_project_alert_rule_details.py::AlertRuleDetailsPutEndpointTest::test_simple
FAILED tests/sentry/integrations/jira_server/test_integration.py::JiraServerIntegrationTest::test_setup_create_webhook
FAILED tests/sentry/models/test_group.py::GroupTest::test_get_group_with_redirect
FAILED tests/sentry/models/test_group.py::GroupTest::test_get_group_with_redirect_from_qualified_short_id
FAILED tests/sentry/models/test_group.py::GroupTest::test_invalid_shared_id
FAILED tests/sentry/api/endpoints/test_group_current_release.py::GroupCurrentReleaseTest::test_current_release_has_group_on_all_envs
FAILED tests/sentry/api/endpoints/test_group_current_release.py::GroupCurrentReleaseTest::test_current_release_has_group_on_one_env
FAILED tests/sentry/api/endpoints/test_organization_details.py::OrganizationDetailsTest::test_with_projects
FAILED tests/sentry/data_export/processors/test_issues_by_tag.py::IssuesByTagProcessorTest::test_get_group
FAILED tests/sentry/integrations/jira_server/test_webhooks.py::JiraServerWebhookEndpointTest::test_post_update_assignee
FAILED tests/sentry/integrations/jira_server/test_webhooks.py::JiraServerWebhookEndpointTest::test_post_update_status
```

**Comment by joshuarli** [comment]
Hmm, the onion's being peeled back. More test fails now.

```
FAILED tests/sentry/api/bases/test_endpoint.py::EndpointTest::test_simple - T...
FAILED tests/sentry/api/bases/test_endpoint.py::EndpointTest::test_unicode_path
FAILED tests/sentry/api/endpoints/test_group_hashes_split.py::test_basic - As...
FAILED tests/sentry/incidents/test_models.py::IncidentClearSubscriptionCacheTest::test_deleted_subscription
FAILED tests/sentry/incidents/endpoints/test_project_alert_rule_details.py::AlertRuleDetailsPutEndpointTest::test_no_owner
FAILED tests/sentry/incidents/endpoints/test_project_alert_rule_details.py::AlertRuleDetailsPutEndpointTest::test_simple
FAILED tests/sentry/mail/test_adapter.py::MailAdapterNotifyTest::test_notify_with_suspect_commits
FAILED tests/sentry/models/test_group.py::GroupTest::test_first_last_release
FAILED tests/sentry/models/test_group.py::GroupTest::test_first_release_from_tag
FAILED tests/sentry/models/test_group.py::GroupTest::test_get_releases - Asse...
FAILED tests/sentry/api/endpoints/test_group_current_release.py::GroupCurrentReleaseTest::test_current_release_has_group_on_all_envs
FAILED tests/sentry/api/endpoints/test_group_current_release.py::GroupCurrentReleaseTest::test_current_release_has_group_on_one_env
FAILED tests/sentry/api/endpoints/test_group_first_last_release.py::GroupFirstLastTest::test_simple
FAILED tests/sentry/api/endpoints/test_organization_details.py::OrganizationDetailsTest::test_with_projects
FAILED tests/sentry/tasks/test_groupowner.py::TestGroupOwners::test_delete_old_entries
FAILED tests/sentry/tasks/test_groupowner.py::TestGroupOwners::test_no_matching_user
FAILED tests/sentry/tasks/test_groupowner.py::TestGroupOwners::test_simple - ...
FAILED tests/sentry/tasks/test_groupowner.py::TestGroupOwners::test_update_existing_entries
FAILED tests/sentry/utils/test_committers.py::GetEventFileCommitters::test_java_sdk_path_mangling
FAILED tests/sentry/utils/test_committers.py::GetEventFileCommitters::test_matching
FAILED tests/sentry/utils/test_committers.py::GetEventFileCommitters::test_matching_case_insensitive
FAILED tests/sentry/utils/test_committers.py::GetEventFileCommitters::test_no_commits
FAILED tests/sentry/utils/test_committers.py::GetEventFileCommitters::test_not_matching
```

**Comment by joshuarli** [comment]
🤔 50f6cfe is regression for at least `tests/sentry/tasks/test_groupowner.py::TestGroupOwners::test_update_existing_entries`

**Comment by joshuarli** [comment]
Ok so about 55b80785f0ae5fb7bbb82f43ca3bc21faf780ce8 which fixes a bunch of stuff:

Django 1.11, using a qs works for id=.

```
> /Users/josh/dev/sentry/src/sentry/models/group.py(496)__get_release()
-> if release_version is None:
(Pdb) GroupRelease.objects.filter(group_id=group_id, project_id=project_id).order_by(orderby).values("release_id")[:1]
<BaseQuerySet [{'release_id': 1}]>
(Pdb) qs = GroupRelease.objects.filter(group_id=group_id, project_id=project
_id).order_by(orderby).values("release_id")[:1]
(Pdb) Release.objects.get(id=qs)
<Release at 0x1133019e8: id=1, organization_id=2, version='v1337'>
```

Django 2.0, need the object otherwise it just fails.

```
(Pdb) qs
<BaseQuerySet [{'release_id': 1}]>
(Pdb) Release.objects.get(id=qs)
*** sentry.models.release.DoesNotExist: Release matching query does not exist.
```

**Comment by joshuarli** [comment]
lol another occurence of this for `tests/sentry/api/endpoints/test_group_current_release.py`, might want to audit all `[:1]` and slap `get()`s on them...

```
(Pdb) GroupRelease.objects.filter(
            group_id=group.id,
            release_id=release_envs[:1].get(),
        )
<BaseQuerySet [<GroupRelease at 0x115b127f0: id=60, group_id=14, release_id=10>, <GroupRelease at 0x115b12860: id=54, group_id=14, release_id=10>]>
(Pdb) GroupRelease.objects.filter(
            group_id=group.id,
            release_id=release_envs[:1],
        )
<BaseQuerySet []>
```

**Comment by joshuarli** [comment]
Hmm actually, I think these visual snapshots mean that #27382 isn't a complete workaround on Django 2.0...

**Comment by joshuarli** [comment]
Oh, it's this:

image

**Review by wedamija — APPROVED** [review]
lgtm, ready for canary

**Pull request merged**
