### PR TITLE
fix(replays): fix network alert formatting and make copy-pasteable

### LINKED ISSUE #50108: [Replay Details] Trim the query string, or scroll the alert content, when we tell people to allow a specific url for network req/resp body capture
Here's what the alert looks like inside the Network Req/Resp panel:

Image

We don't need all that query string in there do we? Lets trim it out.
Urls can be long though, so we could also make the copy+paste part a) actually copy+pastable b) scroll to the side, so the dynamic content is not multi lines.

### PR DESCRIPTION
**Pull request by michellewzhang**
Before:
SCR-20230802-ngth

After:

SCR-20230802-ocvp
SCR-20230802-oema

Fixes https://github.com/getsentry/sentry/issues/50108

### CODE REVIEW

**Review by billyvg — COMMENTED** [review]
How does this look if instead of scrolling, it wraps to next line? It may be difficult to tell that there is more text to scroll to.

Also the copy icon looks *slightly* off center (vertically) from the text, but I did not measure

**Comment by michellewzhang** [comment]
> How does this look if instead of scrolling, it wraps to next line? It may be difficult to tell that there is more text to scroll to.
> 
> Also the copy icon looks _slightly_ off center (vertically) from the text, but I did not measure

SCR-20230802-mgox
looks like this -- is this better?

**Comment by billyvg** [comment]
Hmm, another common pattern we use is using the [`text overflow`](https://storybook.sentry.dev/?path=/story/utilities-text-overflow--text-overflow) component/styling -- which of the three do you like best?

**Comment by michellewzhang** [comment]
> @michellewzhang Hmm, another common pattern we use is using the [`text overflow`](https://storybook.sentry.dev/?path=/story/utilities-text-overflow--text-overflow) component/styling -- which of the three do you like best?

I think I'm a fan of the scrollable (first iteration I did) -- even if you don't immediately see that there's more text to scroll to, the copy button copies the whole thing so user doesn't have to worry about missing part of the URL. Second option formatting is a bit wonky (something with the <code> tags padding is weird). @ryan953 thoughts?

**Comment by ryan953** [comment]
> copy button copies the whole thing so user doesn't have to worry about missing part of the URL

I agree with that.
Therefore I like the scrolling or TextOverflow options, whatever works.

**Comment by michellewzhang** [comment]
@billyvg consulted with @ryan953  and @jas-kas offline, and we decided on utilizing the `TextCopyInput` component, which automatically uses single-line scroll

**Review by billyvg — APPROVED** [review]
LGTM

**Pull request merged**
