### PR TITLE
fix(sentry): Base model has_changed method

### PR DESCRIPTION
**Pull request by mikellykels**
Fix base model has_changed method

cc @ehfeng

### CODE REVIEW

**Comment by mattrobenolt** [comment]
🤔 

What is this fixing? Does this just not work at all currently? How did we make it this far.

**Comment by mikellykels** [comment]
It wasn't working when trying to call it for the Organization model. I don't think it's actually being called anywhere in Sentry at the moment.

**Comment by ehfeng** [comment]
@mikellykels is right—it's not being used (except in one test tests/sentry/utils/models/tests.py).

**Comment by mattrobenolt** [comment]
Ah, well, then this seems like a great time to add a test to prove it's fixed! :)

**Comment by mikellykels** [comment]
Nevermind! Original code works and we aren't entirely sure why it wasn't working when I was trying to use it earlier 🤷‍♀️

**Pull request closed without merging**
