### PR TITLE
docs(replays): Add API documentation for the replay-counts endpoint

### PR DESCRIPTION
**Pull request by cmanallen**
Related: https://github.com/getsentry/team-replay/issues/353

### CODE REVIEW

**Review by billyvg — APPROVED** [review]
The open api CI task failed, do you need to update something to get it to pass or is that expected?

**Comment by billyvg** [comment]
Prev PR that was approved: https://github.com/getsentry/sentry/pull/64465

**Review by michellewzhang — APPROVED** [review]
lgtm, thanks for making the changes!

**Comment by michellewzhang** [comment]
> The open api CI task failed, do you need to update something to get it to pass or is that expected?

open api diff fail looks expected now👍🏼

**Comment by cmanallen** [comment]
@michellewzhang Is the openapi task supposed to fail when there are changes?

**Comment by michellewzhang** [comment]
> @michellewzhang Is the openapi task supposed to fail when there are changes?

@cmanallen yup, but specifically only the "compare open api" step of that test. everything else before and after that step should pass

**Pull request merged**
