### PR TITLE
(fix) Weekly Reports Button

### PR DESCRIPTION
**Pull request by LSSangha**
This update removes the confusion of the greyed out button and removes the greyed out Send Me Weekly Reports button.

Fixing this issue because many users are misled by the button and the ability to fine-tune reports. The fine-tune ability is a work in progress. Attached is the commit that has the previous features:

https://github.com/getsentry/sentry/pull/7239

### Before: 
**sentry.io/settings/account/notifications/**
screen shot 2018-11-19 at 4 48 22 pm
<br>
**sentry.io/settings/account/notifications/reports/**
screen shot 2018-11-19 at 4 48 32 pm

### After
**sentry.io/settings/account/notifications/**
screen shot 2018-11-19 at 4 46 56 pm
<br>
**sentry.io/settings/account/notifications/reports/**
screen shot 2018-11-19 at 4 47 41 pm

### CODE REVIEW

**Comment by maheskett** [comment]
@billyvg Want to make sure this wasn't implemented intentionally?

**Comment by billyvg** [comment]
@maheskett It was definitely implemented intentionally but I forgot the reasoning - @Chrissy 	do you remember?

It might be because the default state of Weekly Reports is true and you can only disable them 1 at a time.

**Comment by Chrissy** [comment]
When I did the designs I thought we could get the default switcher working—I'm guessing this disabled state was tossed in later.

It would certainly be nice to have the default switcher working, but I think the changes proposed here are an upgrade.

**Comment by LSSangha** [comment]
So... are the changes okay?

**Comment by maheskett** [comment]
@billyvg Oh, meant I wanted to make sure it wasn't a bug. Anyway, thanks for the extra context. Looks like it's been this way for a while [#6864](https://github.com/getsentry/sentry/pull/6864)

**Comment by Chrissy** [comment]
@LSSangha yes these should be fine

**Review by maheskett — APPROVED** [review]

**Comment by benvinegar** [comment]
@LSSangha – hey reminder in the future to use the commit message format [used here](https://docs.sentry.io/development/contribute/contributing/#commit-message-format). Not a big deal; for next time.

**Pull request merged**
