### PR TITLE
chore(snuba): Pass referrer to get_groups_user_counts

### PR DESCRIPTION
**Pull request by ceorourke**
The group model's method `count_users_seen` is called by a few different features but `get_groups_user_counts` hard codes the referrer so we can't tell who is actually calling it. This PR passes the referrer in with a description of where it's coming from.

### CODE REVIEW

**Review by JoshFerge — COMMENTED** [review]
do you need to update the snuba referrer enum?

**Review by nhsiehgit — APPROVED** [review]
any tests

**Comment by ceorourke** [comment]
> do you need to update the snuba referrer enum?

Oh yeah I forget about that thing, do you know what the deal is with it? There's a ton of stuff defined in it but most of the variables aren't actually used anywhere.

**Comment by ceorourke** [comment]
> any tests

There are tests for each of these features, do you mean tests that check the referrer string?

**Review by wedamija — APPROVED** [review]

**Comment by JoshFerge** [comment]
> > do you need to update the snuba referrer enum?
> 
> Oh yeah I forget about that thing, do you know what the deal is with it? There's a ton of stuff defined in it but most of the variables aren't actually used anywhere.

i'm not sure about it being unused, but i know that there are checks somewhere where it compares the referrer string to those enums. can ask sns for further details if needed.

**Pull request merged**
