### PR TITLE
ref(page-filters): Remove unused Global Selection Header

### PR DESCRIPTION
**Pull request by davidenwang**
With the change to page filters we can now safely remove the global selection header as it is not being used anymore.

### CODE REVIEW

**Review by scttcper — APPROVED** [review]
🪦 issues, alerts, releases look good

**Review by udameli — APPROVED** [review]
performance related changes look good 🙏

**Review by Zylphrex — APPROVED** [review]
profiling changes look good 🔥

**Comment by priscilawebdev** [comment]
Are we expecting the environment filter to be reset when checking one more project?

https://user-images.githubusercontent.com/29228205/174743348-240a47a5-2fed-4aa9-8fb8-0a4a7ad09841.mov

**Comment by davidenwang** [comment]
> I noticed that the environment filter is being reset when checking another project. is this expected?
> 
>  Screen.Recording.2022-06-21.at.09.37.20.mov

Yup this is consistent with how it worked in the past, mainly because the environments list may change when you select additional projects.

**Review by priscilawebdev — APPROVED** [review]
dashboard changes looks good to me 😉

**Review by ryan953 — APPROVED** [review]

**Review by dashed — APPROVED** [review]
LONG LIVE THE GLOBAL SELECTION HEADER 👑

**Pull request merged**
