### PR TITLE
fix(appconnect): Fix typo in appstore_connect.py

### PR DESCRIPTION
**Pull request by eltociear**
absense -> absence

### CODE REVIEW

**Review by evanpurkhiser — APPROVED** [review]
Thanks for fixing that!

**Review by flub — APPROVED** [review]

**Comment by flub** [comment]
oh snuba tests :( and i can't even trigger rerun it seems

**Comment by relaxolotl** [comment]
It looks like it's consistently failing on snuba (it has for ~3 runs, at least). Considering the age of this PR, it's possible that all that needs to be done is to merge `master` into this branch.

**Comment by flub** [comment]
lol, i give up 😢

**Pull request merged**
