### PR TITLE
fix(ui) Update design of stream sort options

### PR DESCRIPTION
**Pull request by markstory**
Make the stream sort options match the latest mockups. I've converted this component over to a styled component. This will unlock the potential to refactor this + savedsearch components to use common style/behavior components.

## Before

Screen Shot 2019-04-11 at 3 39 38 PM

## Now

Screen Shot 2019-04-11 at 3 39 31 PM

Fixes SEN-478

### CODE REVIEW

**Review by lynnagara — COMMENTED** [review]
Would be great to go ahead and apply these same styled components to the OrganizationSavedSearchSelector as well since the 2 dropdown look a bit different now.

There's a small horizontal line that sometimes appears under the button when you hover your mouse over the dropdown

Screen Shot 2019-04-11 at 4 24 10 pm

**Comment by markstory** [comment]
> Would be great to go ahead and apply these same styled components to the OrganizationSavedSearchSelector as well since the 2 dropdown look a bit different now.

That's my plan. I wanted to get the two buttons using the same styles before adding a common component.

**Comment by markstory** [comment]
@lynnagara Thanks for pointing out the bottom border problem. The `DropdownButton` component was missing a `:focus` style.

**Review by billyvg — APPROVED** [review]
There's a 1px gap between the button and menu but otherwise seems good

**Pull request merged**
