### PR TITLE
Logo additions for 3rd-party plugin (Visual Studio Team Services) Created Visual Studio Team Services plugin located at https://github.com/boylec/sentry-vsts

### PR DESCRIPTION
**Pull request by boylec**
I wrote up a basic Visual Studio Team Services plugin (IssuePlugin2 implementation) for creating work items in VSTS. This pull request consists of the static .png logo for the plugin as well as a .less entry necessary for logo display.

From what I can tell, in order to get the Sentry team to incorporate the plugin it seems I just need to give you guys the location of the repo so you can run the pip install? The internal dev doc says to submit a pull request of getsentry/sentry repo but it appears to me that 3rd-party plugins are simply hosted in their own repos. So I made my plugin located at the following:

https://github.com/boylec/sentry-vsts

I noticed a high demand for this plugin in the Sentry.io forums and stuff - my team would also really like to use it.

Please let me know if there is anything you guys would like me to do to get you to install this plugin on the Sentry server. Thanks! Love your product by the way! :)

### CODE REVIEW

**Comment by billyvg** [comment]
Thanks for your contribution @boylec! I'll take a look at the plugin this week and make sure everything looks good.

**Review by billyvg — CHANGES_REQUESTED** [review]
Everything looks good, can you publish to pip before we merge this in? Thanks!

**Comment by boylec** [comment]
Okay, the python package is now available via `pip install sentry-vsts`

**Review by billyvg — APPROVED** [review]

**Comment by billyvg** [comment]
Thanks for contributing!

**Comment by boylec** [comment]
thanks for the rapid response :)

**Comment by boylec** [comment]
out of curiosity - when will you guys install the plugin? tonight?

**Comment by dcramer** [comment]
@boylec likely today or tomorrow

**Pull request merged**
