### PR TITLE
fix(quick-trace-banner): adjust responsiveness and spacing

### PR DESCRIPTION
**Pull request by doralchan**
**Before:**
Screen Shot 2021-04-21 at 2 57 59 PM

**After:**
Screen Shot 2021-04-21 at 2 53 46 PM
responsiveness

### CODE REVIEW

**Review by Zylphrex — APPROVED** [review]
❤️

**Comment by benvinegar** [comment]
Have we done some work to ensure this doesn't appear at the same time as the "set up suspect commits" prompt?

**Comment by Zylphrex** [comment]
> Have we done some work to ensure this doesn't appear at the same time as the "set up suspect commits" prompt?

This currently is capable of showing up at the same time as the "set up suspect commits" prompt. Is there a reason why it should not?

**Comment by benvinegar** [comment]
> This currently is capable of showing up at the same time as the "set up suspect commits" prompt. Is there a reason why it should not?

Inundating users with multiple prompts seems like something worth avoiding, IMO. Can we do something clever to show just one? Even something as simple as just randomizing which one you get (if neither are dismissed). cc @jeremybourque

**Comment by Zylphrex** [comment]
> Inundating users with multiple prompts seems like something worth avoiding, IMO. Can we do something clever to show just one? Even something as simple as just randomizing which one you get (if neither are dismissed). cc @jeremybourque

That's a good point, I'll backlog something to address this.

**Comment by EvanPurkhiser** [comment]
Agree with this @benvinegar. If we dismiss one the other could show up too maybe

**Pull request merged**
