### PR TITLE
ref(ci): Clean up most mentions of travis

### PR DESCRIPTION
**Pull request by billyvg**

### CODE REVIEW

**Comment by joshuarli** [comment]
What about `build-utils/sentry-instrumentation.js`?

Also this seems unused:

```
sentry/tasks/test_reprocessing2.py
20:pytestmark = pytest.mark.skip(reason="Deadlock on Travis")
```

**Comment by billyvg** [comment]
@joshuarli I have a sep pr for that https://github.com/getsentry/sentry/pull/22034

**Review by evanpurkhiser — APPROVED** [review]
Love this

**Review by joshuarli — APPROVED** [review]

**Comment by billyvg** [comment]
@joshuarli I'll follow up w/ that pytest mark

**Pull request merged**
