### PR TITLE
ref(project-selector): Remove unnecessary styles

### PR DESCRIPTION
**Pull request by lynnagara**

### CODE REVIEW

**Comment by lynnagara** [comment]
@Chrissy These don't seem to make any difference - do you recall if there's any reason for this?

**Comment by Chrissy** [comment]
@lynnagara yeah it just increases the hit box for the hover states. not necessary I don't think but that is why it is there.

**Comment by lynnagara** [comment]
How so? I can't spot any differences with these 2 lines removed.

**Comment by Chrissy** [comment]
well there wouldn't be a visible difference, but there would be a larger area for the mouse to hover over.

If that isn't happening then the code is doing nothing lol.

**Comment by lynnagara** [comment]
yeah, i checked the hover area and it *seems* exactly the same? The difference might be the 1px but it's very imperceptible

**Comment by Chrissy** [comment]
the intent of the code was definitely to grow the hover area by ten pixels on each side, so if it isn't doing that let's just remove it.

**Review by Chrissy — APPROVED** [review]

**Comment by EvanPurkhiser** [comment]
👍 for increased hitbox if we can make that work

**Pull request merged**
