### PR TITLE
feat(ts): Add Client type to withAPI

### PR DESCRIPTION
**Pull request by dashed**
☝️

### CODE REVIEW

**Review by billyvg — APPROVED** [review]
Can you audit the other places where we need to update API types?

**Comment by dashed** [comment]
I will definitely audit other files for the API type in follow up PRs.

**Comment by dashed** [comment]
I updated `src/sentry/static/sentry/app/views/settings/projectIncidentRules/ruleForm.tsx`. Looks like it's the only other file that needs to be updated.

**Comment by billyvg** [comment]
🤭

**Pull request merged**
