### PR TITLE
fix(py3): Fix migrations to work correctly in Python 3.

### PR DESCRIPTION
**Pull request by wedamija**
Migrations fail in python 3 when there's a mix of bytestrings and unicode strings. This is because
all migrations import `unicode_literals` at the top of the file, and then each migration expects to
treat all string-like things in the same way.

We also had a couple cases where the choices from a dictionary.items() had changed order and
caused a new migration to get generated in py3. I made this a fixed order and corrected the old
migrations in this case.

Summary of what this pr does:
 - Remove all uses of `b""` strings in migrations.
 - Prevent new migrations from generating b strings:
  - For all fields that use `db_column`, make it explicitly unicode.
  - For all fields with a choice, make the values unicode
  - For all fields with a default that is a string, make sure it is unicode.

This doesn't guard against people making new models/fields with b strings. I think that we can just
guard against this in code review, hopefully it'll only be for a few months.

### CODE REVIEW

**Comment by wedamija** [comment]
To make reviewing easier I ran black on all the modified migrations ahead of time. Probably easiest to look at https://github.com/getsentry/sentry/pull/21038/commits/5aaf6a4bef5a11a1a3494f1658af51be1637f2a1 to see the changes.

**Comment by wedamija** [comment]
I ran `sentry django makemigrations -n test` in both py2 and py3,  no additional migrations are made. CI also ran with both of these. I'll enable migrations in py3 tests separately to this.

**Review by BYK — APPROVED** [review]
>This doesn't guard against people making new models/fields with b strings. I think that we can just
guard against this in code review, hopefully it'll only be for a few months.

If we ever feel the need, I'm okay adding a quick GitHub action to catch these. Should be easy enough.

Google Cloud Build passed w/o issues so I feel good about this change. Yay! The only thing I'm curious is where we try to upgrade from Py2 to Py3. Maybe there would be a one time migration or something?

One question though, should we not do `from __future__ import unicode_literals`in migrations at least now?

**Comment by wedamija** [comment]
> > This doesn't guard against people making new models/fields with b strings. I think that we can just
> > guard against this in code review, hopefully it'll only be for a few months.
> 
> If we ever feel the need, I'm okay adding a quick GitHub action to catch these. Should be easy enough.
I guess we could have a thing that checks that new migrations aren't generated with b strings, that should be enough to detect it. Probably worth duplicating the check that makes sure we're don't have pending github migrations as well, might bug billy about that.

> 
> Google Cloud Build passed w/o issues so I feel good about this change. Yay! The only thing I'm curious is where we try to upgrade from Py2 to Py3. Maybe there would be a one time migration or something?
I don't think there will be any migration necessary, these are now compatible in both 2 & 3, and they'll both generate the same migration given the same model changes.


> One question though, should we not do `from __future__ import unicode_literals`in migrations at least now?
No choice really, the migrations generate this by default. I guess we could change what is generated, but I think given that this work is done I think this is more compatible with how py3 will work.

**Pull request merged**
