### PR TITLE
feat(discover) Add sorting to discover saved queries

### PR DESCRIPTION
**Pull request by markstory**
Add a UI control to expose the sorting options that we have for discover saved queries. This helps improve saved query experience for orgs with many saved queries.

Screen Shot 2020-05-29 at 2 26 05 PM

### CODE REVIEW

**Comment by bowencai8** [comment]
I think the only additional one I'd want to add is "Created by me" or "My Queries"

Is that possible to add? (Even though it'd be a filter and not technically a sort)

**Review by dashed — APPROVED** [review]

**Comment by dashed** [comment]
This works fine. 

It can be awkward to show the loading state on the entire page after a sort CTA.

**Comment by markstory** [comment]
> It can be awkward to show the loading state on the entire page after a sort CTA.

Agreed, I can add a wrapper component for the static content.

**Comment by markstory** [comment]
> I think the only additional one I'd want to add is "Created by me" or "My Queries"

@bowencai8 We could add these as filter options, but I don't know how we make those options easy to learn.

**Comment by bowencai8** [comment]
Ah, didn't mean to suggest building another filter control here - I don't think we should do that either.

My thought was can we add a sort option:
Sort by: My Queries

that acts as a "filter" and only shows a list of the user's queries?
And if we can't filter down the list, could we show a list of the user's queries, and then sort the rest of the queries after by last modified?

**Comment by markstory** [comment]
> And if we can't filter down the list, could we show a list of the user's queries, and then sort the rest of the queries after by last modified?

Would having the current user's queries first sorted by name, then other users queries ordered by their userid and query name work?

**Comment by bowencai8** [comment]
@markstory yeah that works!

**Pull request merged**
