### PR TITLE
ref(whats-new): Add extra javascript update info

### PR DESCRIPTION
**Pull request by priscilawebdev**
Adds an extra message to the `sdks update alerts`, warning the users that all sentry `javascript` packages should also be updated and their versions should match.

This alert is being added based on the feedback received in the PR https://github.com/getsentry/sentry-javascript/issues/3223

**Preview:**

image

image

Fixed minor copy issue introduced in the PR: https://github.com/getsentry/sentry/pull/27046

**Before:**

image

**After:**

image

### CODE REVIEW

**Review by matejminar — APPROVED** [review]
Approving for staging

**Review by kamilogorek — APPROVED** [review]

**Review by doralchan — CHANGES_REQUESTED** [review]
This does not require an alert. The whole sidebar is opened with an alert in the first place. I will propose a new fix

**Comment by doralchan** [comment]
Screen Shot 2021-07-01 at 10 56 00 AM
Screen Shot 2021-07-01 at 10 54 34 AM

**Comment by priscilawebdev** [comment]
closing this PR in favor of https://github.com/getsentry/sentry/pull/27102

**Pull request closed without merging**
