### PR TITLE
fix(integrations) Only show repository delete buttons when they work

### PR DESCRIPTION
**Pull request by markstory**
Only users with org:admin can perform DELETE operations. Scope the repository delete buttons appropriately.

### CODE REVIEW

**Comment by benvinegar** [comment]
If it's not too much work, we've got to change our default understanding to "show the button, but its disabled" vs hiding.

**Comment by MeredithAnya** [comment]
@benvinegar If I'm reading it correctly this only hides the cancel pending deletions if they don't have access, but the trash button will be disabled

**Comment by markstory** [comment]
@MeredithAnya is correct. Making the 'Cancel Pending' button visible but disabled is a small change.

**Comment by markstory** [comment]
I've changed the blue cancel link to be one of our standard buttons. This allows the active/disabled state to be managed with less effort and removes the blue-link-button which is a bit of an anomaly in the app.

**Enabled State**
screen shot 2018-12-07 at 12 01 27 pm


**Disabled State**
screen shot 2018-12-07 at 12 14 32 pm

**Review by evanpurkhiser — APPROVED** [review]

**Pull request merged**
