### PR TITLE
[WIP] GitLab Integration

### PR DESCRIPTION
**Pull request by Coffee2CodeNL**
This PR is to track progress on the Integration of GitLab

- This will support gitlab.com
- This will support on-premise instances

Reason for opening a new PR is because I forgot to create a new branch for my work.

Notifying:
- @dcramer

### CODE REVIEW

**Comment by getsentry-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          3 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Changes require @getsentry/security sign-off</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is classed as Work in Progress</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
  </tbody>
</table>

### Security concerns found

- src/sentry/identity/oauth2.py


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by markstory** [comment]
Closing as the gitlab integration is actively being worked on, and has been taken in a different direction.

**Comment by Jean85** [comment]
Great! Can we follow the WIP somewhere?

**Comment by markstory** [comment]
The work will happen in various pull requests, but on of the currently open ones is #9832.

**Pull request closed without merging**
