### PR TITLE
fix(crons): Fix bug where a monitor can be unintentionally upserted to another project with an org.

### LINKED ISSUE #65633: Update upsert logic to prevent monitors from switching projects when different DSNs are used for the same slug
We currently have this scenario:
- send a checkin for org A project X, slug abc, creates a monitor
- send a checkin for org A project Y, slug abc. monitor upserts existing monitor to project Y 

We should update the logic to prevent monitors from switching projects and dropping the checkins. Then, when implementing https://github.com/getsentry/sentry/issues/48583, we should notify the customer their DSN is invalid and instruct them to either change it or delete the monitor.
```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/issues/66615
```

### PR DESCRIPTION
**Pull request by wedamija**
We have a bug where if we have a monitor that belongs to project A in org Z, and then we send an upsert checkin associated with the same monitor, but project B in org Z, then we'll inadvertently update the monitor to belong to project B.

This pr prevents this from happening and just drops the checkin.

Fixes https://github.com/getsentry/sentry/issues/65633

### CODE REVIEW

**Review by cmanallen — APPROVED** [review]
Is it not okay for two projects to share the same slug?  Or is it not okay to upsert a slug that exists for a different project?

If its the former is there any validation that needs to be done on the API endpoints?

**Review by davidenwang — APPROVED** [review]

**Comment by wedamija** [comment]
> Is it not okay for two projects to share the same slug? Or is it not okay to upsert a slug that exists for a different project?
> 
> If its the former is there any validation that needs to be done on the API endpoints?

The problem is that monitor slugs are unique per org, not per project. As well as that, the project on a monitor should never change once it has been created.

We can't really do validation here unfortunately, these all come in via relay straight to the consumer. What we're doing here basically is the validation, but we don't give feedback to the user. There's a plan to give users better feedback in the next quarter or two, rather than just dropping invalid checkins into a black hole.

**Comment by hillam** [comment]
> monitor slugs are unique per org, not per project

Can this be changed? What if I have several projects that all have a generic named cron like 'housekeeping'? If a monitor _**belongs**_ to a given project, why would another project within the organization not be able to have a same-named monitor?

**Comment by wedamija** [comment]
> > monitor slugs are unique per org, not per project
> 
> Can this be changed? What if I have several projects that all have a generic named cron like 'housekeeping'? If a monitor _**belongs**_ to a given project, why would another project within the organization not be able to have a same-named monitor?

Yep, I'm actually in the middle of this change now, it should be done this week. I no longer plan to merge this pr, closing it now

**Pull request closed without merging**
