### PR TITLE
fix(ui): Replace double loading spinner with placeholders

### PR DESCRIPTION
**Pull request by malwilley**
Before:

CleanShot 2023-01-09 at 10 13 56

After:

CleanShot 2023-01-09 at 11 29 20

### CODE REVIEW

**Comment by evanpurkhiser** [comment]
Are we able to approximate the size?

**Comment by malwilley** [comment]
> Are we able to approximate the size?

Unfortunately not, the number of tags it's going to load is unknowable

**Review by k-fish — APPROVED** [review]
I'm fine with it code-wise, I'll defer to @doralchan for how it looks

**Review by doralchan — APPROVED** [review]
smash

**Pull request merged**
