### PR TITLE
Proposal to fix generated URLs when SCRIPT_NAME is set.

### PR DESCRIPTION
**Pull request by ldrumm**
Please see comments on issue 1122 for discussion.

### CODE REVIEW

**Comment by ldrumm** [comment]
@dcramer Well nearly a year later, I went to upgrade my sentry instance, and was reminded I never finished with this patch.  Sorry about that...
Anyway, I decided it's best to resurrect this issue, and added all your requested test scenarios, which hopefully make sense.  Let me know if you can think of any extra cases, or improvements.

For what it's worth, I think an entry in the installation manual might be helpful for people struggling with this sort of configuration which seems to be common enough to be noteworthy.  Perhaps something along the lines of:

> If you intend to mount sentry on a path other than `/` (ie 
> `https://mysentry.example.com/mysentryinstance`) you need to make sure that the `SCRIPT_NAME` 
> environment variable is set to `'/mysentryinstance'` and `settings.SENTRY_URL_PREFIX` is set to `'https://mysentry.example.com'`

**Comment by ldrumm** [comment]
I think this PR maybe premature.  There's something still fishy about event URLS.  I'm going to check some more....

**Comment by resure** [comment]
It looks like currently Sentry installations on sub-paths (like /_sentry) are slightly broken. Links to events from project page (and in some other places) are incorrect when `FORCE_SCRIPT_NAME` is set (they lead to `/_sentry/_sentry/...`). Can this issue affect that things?

**Comment by dcramer** [comment]
@resure it's not supported in the current version of Sentry. There's configuration that has to be setup, and we dont document or support it at this time.

**Comment by resure** [comment]
@dcramer ah, that's sad. However, I was able to workaround that using nginx rewrite (from `/_sentry/_sentrty(.*)` to `/_sentry/$1`), not very elegant, but works quite well.

**Comment by mattrobenolt** [comment]
Closing since our support for this is sketchy at best and we don't recommend do this. :(

**Pull request closed without merging**
