### PR TITLE
build(babel): Upgrade babel deps to 7.4.4

### PR DESCRIPTION
**Pull request by billyvg**

### CODE REVIEW

**Comment by dashed** [comment]
@billyvg how confident are you of these upgrades? 

I'll cherry pick this into https://github.com/getsentry/sentry/pull/14345 and let it stew for a bit.

**Comment by billyvg** [comment]
Tests are passing ¯\_(ツ)_/¯

I've generally not had issues upgrading babel (at least non-major upgrades).

**Review by dashed — APPROVED** [review]
I went thru the changelogs of babel from v7.0 to v7.5.

Looks good to me. 👍

**Comment by billyvg** [comment]
I'll need to upgrade getsentry too

**Comment by dashed** [comment]
Oh true. 👍

**Review by dashed — CHANGES_REQUESTED** [review]
Holding back on my approval for a bit.

**Comment by dashed** [comment]
Hmm. @billyvg im running into this issue for getsentry https://github.com/babel/babel/issues/10264

**Comment by billyvg** [comment]
@dashed ah yeah, they merged a fix but no release yet.

**Comment by dashed** [comment]
@billyvg i think we can relax babel to `v7.4.5`

**Review by dashed — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
