### PR TITLE
Guard against invalid image data

### PR DESCRIPTION
**Pull request by mattrobenolt**
Fixes SENTRY-1AT

@getsentry/api @macqueen

### CODE REVIEW

**Comment by mitsuhiko** [comment]
Unrelated to the PR but I'm quite confused why we are uploading avatars as base64. Why are we not using multipart for this? This is very memory inefficient because it means we hold the entire avatar payload in memory 2.5 times wheras the multipart stream would be buffered on disk if above threshold.

**Comment by mattrobenolt** [comment]
@mitsuhiko From my understanding, that was a limitation on how the frontend had to send data? I'm not entirely sure, but if we could do it using a normal multipart form, that'd be great.

**Comment by dcramer** [comment]
Would be good for us to get some tests in here too

**Comment by mitsuhiko** [comment]
@mattrobenolt just for the record: there is a data api in javascript which can send multipart requests. It's very well supported.

**Comment by mattrobenolt** [comment]
> @mattrobenolt just for the record: there is a data api in javascript which can send multipart requests. It's very well supported.

@benvinegar @macqueen :)

**Pull request merged**
