### PR TITLE
ref: Remove JS tests from precommit

### PR DESCRIPTION
**Pull request by untitaker**
Those tests were added because people kept forgetting updating snapshot
files. However, we don't have those anymore.

Meanwhile backend devs see the entire js testsuite executing when they
merge master into their branch

This relates to, but doesn't fully solve
https://github.com/getsentry/sentry/issues/25291, as JS lints still run
on `git merge master`. In the longer-term it might be best to move
everything to pre-commit.yml which doesn't do that.

### CODE REVIEW

**Review by dashed — APPROVED** [review]

**Review by armenzg — APPROVED** [review]
Thanks for tackling this!

**Review by joshuarli — APPROVED** [review]
nice, now i don't have to `rm .git/hooks/pre-commit.legacy` anymore

**Review by priscilawebdev — APPROVED** [review]

**Review by flub — APPROVED** [review]
any reason this stalled?

**Comment by untitaker** [comment]
@flub yes, two reasons: flaky CI and short attention span :P

**Pull request merged**
