### PR TITLE
chore(hybrid-cloud): reorganize services

### PR DESCRIPTION
**Pull request by corps**
To reduce import cycles, split the service definitions from the implementations.
Adds test utility that counts and caps service calls.
Also forces stubs to declare their target silo.

### CODE REVIEW

**Comment by corps** [comment]
https://github.com/getsentry/getsentry/pull/8911

**Comment by RyanSkonnord** [comment]
I'm on board with the split between `__init__` and `impl`, but I'm not sure I agree with the change in package names. Why name it `auth_service` instead of just `auth`? These are all subpackages of `services/hybrid_cloud` already, so having the word "service" twice in the fully qualified name (e.g., "sentry/**services**/hybrid_cloud/auth_**service**/\_\_init__.py") seems redundant to me. (Has it got anything to do with `sentry/services/hybrid_cloud/auth` previously being a module name? Does it cause some headache if it refers to a module in one commit and a package in the next?)

**Comment by corps** [comment]
> I'm on board with the split between `__init__` and `impl`, but I'm not sure I agree with the change in package names. Why name it `auth_service` instead of just `auth`? These are all subpackages of `services/hybrid_cloud` already, so having the word "service" twice in the fully qualified name (e.g., "sentry/**services**/hybrid_cloud/auth_**service**/__init__.py") seems redundant to me. (Has it got anything to do with `sentry/services/hybrid_cloud/auth` previously being a module name? Does it cause some headache if it refers to a module in one commit and a package in the next?)

I could definitely change it back.  My main motivation with adding `_service` was because, fuzzy searching `user` and `auth` and `organization` is rough.   Adding `_service` gave me a more unique target to fuzzy search.  Honestly, that's the reason lol.  I optimize for differentiation in names to a certain degree esp when it increases clarity of searching for files.  For instance, seeing a stack trace with a bunch of `auth` files right now is a pain -- there many, many different components named "auth", but they aren't the same.  Having more visual clarity on quick look what I'm seeing does, help, in my experience.  Thoughts?

**Comment by dcramer** [comment]
@corp most fuzzy search will let you do wild matches e.g. "serv auth" will match services/auth" - you cant win the naming battle IMO and its worth keeping nomenclature keep vs bloated/duplicated. same problem exists in js

**Comment by RyanSkonnord** [comment]
Hmm... further complicating it is lines like this one:

https://github.com/getsentry/sentry/blob/f9194d3e351a2bd7adbafea4b027d2225963dfb7/src/sentry/auth/access.py#L39

For a minute I thought the module name was taking the place of the `*_service` variable that represents the global service instance, with all the service method names exported in the namespace. In other words, if it were possible to just do

```python
from sentry.services.hybrid_cloud import organization_service
```

and then write `organization_service.check_organization_by_slug(...)`, that would feel pretty elegant. But if it's the same thing with

```python
from sentry.services.hybrid_cloud.organization_service import organization_service
```

then `organization_service` refers to both the package name and the value exported from its `__init__` module, which just invites confusion IMHO.

**Comment by corps** [comment]
I'm willing to change the module names.  I'm not convinced that denormalization is always better, but I don't have a strong proposal at hand.

**Review by RyanSkonnord — APPROVED** [review]

**Pull request merged**
