### PR TITLE
feat(sampling): Better handle extra long tags/values in UI [TET-80]

### PR DESCRIPTION
**Pull request by matejminar**
Truncating tag keys+values and adjusting grid css so that we better handle edge-cases with super long strings.

### CODE REVIEW

**Comment by priscilawebdev** [comment]
**Before:** 

image


**After:**

image

**Comment by priscilawebdev** [comment]
the menu is overflowing on smaller devices. should we check it too?

image

**Comment by priscilawebdev** [comment]
sometimes there are still some places we could use before truncating 

image

**Comment by matejminar** [comment]
@priscilawebdev thanks for adding screenshots.

> the menu is overflowing on smaller devices. should we check it too?

good catch, I adjusted the truncation and grid on mobile devices

> sometimes there are still some places we could use before truncating

I am not too concerned about that, we can still see the value in the input

**Review by priscilawebdev — APPROVED** [review]
can confirm that the menu no longer overflows on smaller devices...thanks for fixing it 👏

**Pull request merged**
