### PR TITLE
ref(projects): Remove team data from deleted project audit

### PR DESCRIPTION
**Pull request by macqueen**
depends on https://github.com/getsentry/sentry/pull/6807

since projects will soon be able to be associated with multiple teams, i'm removing this data

### CODE REVIEW

**Comment by getsentry-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR includes migrations</td>
    </tr>
  </tbody>
</table>

## Migration Checklist

- [ ] new columns need to be nullable (unless table is new)
- [ ] migration with any new index needs to be done concurrently
- [ ] data migrations should not be done inside a transaction
- [ ] before merging, check to make sure there aren't conflicting migration ids


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Review by mattrobenolt — CHANGES_REQUESTED** [review]
This will cause a problem since the columns will be removed while the code still is running referencing it. This needs to remove the columns from code first, then ship the migration to drop the columns after that's out.

**Comment by macqueen** [comment]
@mattrobenolt i did that as part of https://github.com/getsentry/sentry/pull/6807/ (https://github.com/getsentry/sentry/pull/6807/commits/a3e514511b00a46e5e0c02c826bb1e5fcf18cdb5) which I was planning on merging first  for that reason. buuut maybe it just makes more sense for me to pull that out into it's own PR since it doesn't _have_ to be part of that. would that be better?

**Comment by mattrobenolt** [comment]
Oh, I see, then you're going to have a conflict here anyways. So we're good after #6807 merges. Your call if you want to split it out more or not, I don't personally think it's that important.

**Comment by macqueen** [comment]
ok @mattrobenolt this should be good to go now

**Review by mattrobenolt — APPROVED** [review]
You again need to recreate migration. :(

https://github.com/getsentry/sentry/pull/6961

**Pull request merged**
