### PR TITLE
Initial pass for tag efficiency

### PR DESCRIPTION
**Pull request by dcramer**
- Add GroupTagKey.key_id
- Add GroupTagValue.key_id
- Add GroupTagValue.value_id
- Remove usage of TagKey.values_seen
- Remove usage of TagValue.times_seen

/cc @getsentry/infrastructure

---

This change is [Reviewable](https://reviewable.io/reviews/getsentry/sentry/3780)

### CODE REVIEW

**Comment by dcramer** [comment]
Looking for feedback here since this is a huge change. IMO its needed to grow out the tag usage.

Follow ups would be:

- Backfill new fields
- Add unique constraints and missing indexes to mimic string fields
- Switch queries to use int fields

Longer term changes:

- Remove remaining foreign key constraints to enable sharding
- Add environment dimension
- Break apart tag tables into horizontal shards

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3780#-:-KNJLtC7YzhZkiB-X7WN:106001495)*

**Comment by dcramer** [comment]
Also we'll want to remove GroupTagValue.data and TagValue.data as they're no longer supported or used.

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3780#-:-KNJMkdwvmJZk39_cXMJ:227570080)*

**Comment by mattrobenolt** [comment]
Reviewed 9 of 10 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3780)*

**Comment by dcramer** [comment]
I want to follow up in person to see if everyone thinks this is the best course of action. Tag table bloat is our biggest concern at this stage, and these changes will help it, but its not the be-all-end-all. Given that, maybe we should also consider a more in-depth solution of splitting the data up.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3780#-:-KNwqk_yw0XrO3Aonvjr:-1782298060)*

**Comment by mattrobenolt** [comment]
I'm going to take this over and revisit.

**Comment by bretthoerner** [comment]
The ideas here will be folded into Tags 2.0 / TagStore.

**Pull request closed without merging**
