### PR TITLE
feat(feedback): Move contact-email and message fields outside the contexts object

### LINKED ISSUE #59928: [User Feedback Search] Add additional search conditions: User Description content and User Email
## Search Improvements

1. Being able to search by user email

As a Sentry user, I would like to see all feedbacks from a specific user so that I can get a better understanding of challenges they're facing holistically.

2. Being able to search description content

As a Sentry user, I would like to search the end-user description content (i.e, the message the user inputted) of a feedback, so I can easily go back to a feedback I previously viewed.

As a Sentry user, I would like to understand if there is a theme in my feedbacks by searching all of them by a key word.

Note: I would expect the above to work similar to event title/messages on the Issues Stream search. [[Link](https://docs.sentry.io/product/reference/search/?original_referrer=https%3A%2F%2Fdocs.sentry.io%2F#syntax)]

### PR DESCRIPTION
**Pull request by cmanallen**
@JoshFerge There's no `message` field in `event.schema.json`.  So I just put in the extra object for now just to have a code path to change later.  Consider it a todo.

I'm not entirely sure where this should live.  Without changing the schema, it feels like a tag is the best place at the moment...  That or a top-level contexts field e.g. `"feedback_message": message`.  I'm not sure what the etiquette is around adding fields to contexts.  Do you have any thoughts?

Closes: https://github.com/getsentry/sentry/issues/59928

### CODE REVIEW

**Comment by cmanallen** [comment]
@bruno-garcia 's [comment](https://github.com/getsentry/sentry/issues/59928#issuecomment-1832482421) isn't addresses as part of this work.  Waiting for confirmation before adding.

**Comment by cmanallen** [comment]
@bruno-garcia Yep I saw logentry but wasn't sure if we should overload it or not.  I agree another contender.  However, do we want people to type in the search box `logentry:*my_message*`?  Didn't seem like the best UX.

**Comment by bruno-garcia** [comment]
> @bruno-garcia Yep I saw logentry but wasn't sure if we should overload it or not. I agree another contender. However, do we want people to type in the search box `logentry:*my_message*`? Didn't seem like the best UX.

Agree, that's something to consider: What will people expect to search for. We need to close that gap somehow

**Comment by JoshFerge** [comment]
logentry.message is simply `message` when searching. so this should work great! https://github.com/getsentry/sentry/blob/4fd049ee9efcb8b0265ef1968efe442e15396558/src/sentry/eventstore/models.py#L110

**Review by JoshFerge — APPROVED** [review]

**Comment by cmanallen** [comment]
@JoshFerge Nice find!  I'll update to use logentry.

**Pull request merged**
