### PR TITLE
feat(semver): Set `current_release_version` on Activity model

### PR DESCRIPTION
**Pull request by ahmedetefy**
This PR:-
- Sets `current_release_version` on `Activity` when `ResolvedInNextRelease` is clicked on the UI for semver releases. 
- Also, updates `GroupResolution` to be of type `in_release` instead of `in_next_release` because since we are using `current_release_version` as an expression (i.e. `>current_release_version`), we pretty much know that we already have a `GroupResolution` of status resolved. Technically, there is no need to run `clear_expired_resolutions` as we are not awaiting any upcoming release
- Fix bug that was overriding the `release` version in the last activity prior to a regression activity

Follow up: 
- UI will use this `current_release_version` to say something like `This issue was resolved in versions >1.0.0` for example
- Will also change this for date based releases. Currently with date based releases and `ResolvedInNextRelease`, there is basically two scenarios

Scenario 1:
```
release 1 is created
issue 1 happens in release 1
release 2 is created
```

Clicking `ResolvedInNextRelease` resolves this issue in release 2 onwards, and so we know that release 2 is the release that resolves the issue
=> We can store the `release 2` in the `release` field for both `GroupResolution` and `Activity` + treat this resolve case as `ResolvedIn` release 2 (thereby updating relevant `GroupResolution` fields status and type to have `Resolved` and `in_release` respectively) => Hence, also not running `clear_expired_resolutions`

Scenario 2:

```
release 1 is created
issue 1 happens in release 1
```

Clicking `ResolvedInNextRelease` resolves this issue in the upcoming release that we do not know yet, and so we fallback to the model we have + `clear_expired_resolutions` runs updating all these fields once a new release is created

### CODE REVIEW

**Review by wedamija — COMMENTED** [review]
Won't this fail in this case?

- Create Release A
- Group occurs in Release A
- Click `resolve in next release`. 
- Resolution changes to `in_release` and is marked as Release A
- New event occurs in group, regresses

**Comment by ahmedetefy** [comment]
> Won't this fail in this case?
> 
> * Create Release A
> * Group occurs in Release A
> * Click `resolve in next release`.
> * Resolution changes to `in_release` and is marked as Release A
> * New event occurs in group, regresses

Nah because I will fetch the next release in terms of date (if it exists) and set release to that 
And if it doesn’t exist yet, fallback to our current model

**Comment by wedamija** [comment]
> > Won't this fail in this case?
> > 
> > * Create Release A
> > * Group occurs in Release A
> > * Click `resolve in next release`.
> > * Resolution changes to `in_release` and is marked as Release A
> > * New event occurs in group, regresses
> 
> Nah because I won’t set release to release A in that case, I will fetch the next release in terms of date (if it exists) and set release to that. However current_release_version will be set to release A
> And if it doesn’t exist yet, fallback to our current model

Ok, I think this makes sense. Just to make sure I understand:
 - When we're doing `resolvedInNextRelease`, we get `release` here: https://github.com/getsentry/sentry/pull/27830/files#diff-97433a352c770f38e184395d467561430d5744db9510861937f22f334c2d4171L615. If Release A is the most recent release it will be fetched here.
 - With your change, this will still be set in the `GroupResolution`. Then for any projects that `follow_semver`, we will change the type to `in_release`.
 - Since it's `in_release` now, it won't be cleared in `clear_expired_resolutions`
 - In `has_resolution`, if `current_release_version` and `follows_semver` are true, then we only return False when a release greater than `current_release_version` is passed, so this will still effectively work as `resolved in next release`.

**Review by wedamija — APPROVED** [review]
Semantically it's a bit weird that we are marking it as resolved in the current release, but this should work ok

**Comment by ahmedetefy** [comment]
> Semantically it's a bit weird that we are marking it as resolved in the current release, but this should work ok

We are not resolving in current release, we are resolving in an expression that includes current_release_version. I will hold off on merging this, and will whip up a notion doc explaining better and we can chat about this more.. if you'd like

**Review by matejminar — APPROVED** [review]
Played with this locally, looks good to me.

**Comment by wedamija** [comment]
> > Semantically it's a bit weird that we are marking it as resolved in the current release, but this should work ok
> 
> We are not resolving in current release, we are resolving in an expression that includes current_release_version. I will whip up a notion doc explaining better and we can chat about this more.. if you'd like

No need to hold off, I understand how it's working. What I mean is that I think it will be confusing to read this code without context, since we're setting the status to `resolved` and the type to `in_release`, which kind of implies it is resolved in the release it's set to, rather than the next semver release.

**Comment by ahmedetefy** [comment]
> > > Semantically it's a bit weird that we are marking it as resolved in the current release, but this should work ok
> > 
> > 
> > We are not resolving in current release, we are resolving in an expression that includes current_release_version. I will whip up a notion doc explaining better and we can chat about this more.. if you'd like
> 
> No need to hold off, I understand how it's working. What I mean is that I think it will be confusing to read this code without context, since we're setting the status to `resolved` and the type to `in_release`, which kind of implies it is resolved in the release it's set to, rather than the next semver release.

Agreed, do you have any ideas on how to disambiguate that? I try to hyper document 😅 but not sure if it’s enough

**Pull request merged**
