### PR TITLE
Improve barchart rendering perf by deferring tooltip title creation

### PR DESCRIPTION
**Pull request by benvinegar**
In my anecdotal testing with React.perf, this shaves > 100ms off of rendering from the stream (about 50% faster) and makes the page noticeably less janky on first render.

### CODE REVIEW

**Comment by benvinegar** [comment]
This also improves performance of the org dashboard.

**Comment by dcramer** [comment]
lgtm

**Comment by benvinegar** [comment]
This is based off the react-0.14 branch, so I will merge once #2172 lands.

**Comment by benvinegar** [comment]
Closing because wrong target; see #2208

**Pull request closed without merging**
