### PR TITLE
feat(ui): Add Confirm to "require 2fa" option

### PR DESCRIPTION
**Pull request by billyvg**
* move require2fa into data/forms + add confirm
* add `confirm` prop to BooleanField to open a Confirm modal
* refactor Confirm component to overload `children` and accept a render function
  * allow rendered child to control confirm state

Soft dependency on https://github.com/getsentry/sentry/pull/7303

### CODE REVIEW

**Comment by billyvg** [comment]
@lauryndbrown any suggestions for the confirm text? https://github.com/getsentry/sentry/pull/7480/files#diff-3e30d7ce62c4bd4860f0c9d9e4b7dd49R73

**Review by MaxBittker — APPROVED** [review]
this was hard for me to follow 100%, maybe we could talk about it when you're back?

**Comment by MaxBittker** [comment]
it did work well locally, except for the fact that the slider stayed green after failure
image

**Comment by MaxBittker** [comment]
oh, that makes sense, thanks!

**Review by MaxBittker — APPROVED** [review]
nice, works locally (although the form-local error goes away with resetOnError, the floating indicator remains)

**Pull request merged**
