### PR TITLE
chore: Bump sentry-kafka-schemas to 0.1.78

### PR DESCRIPTION
**Pull request by ayirr7**
Bumping to the latest schema version

### CODE REVIEW

**Comment by evanpurkhiser** [comment]
I actually am about to bump, can we wait?

**Comment by ayirr7** [comment]
@evanpurkhiser ok! Do you have a PR for that?

**Comment by evanpurkhiser** [comment]
Waiting for the relase to go out, can you bump this to 0.1.78 when it does?

**Comment by ayirr7** [comment]
@evanpurkhiser I don't have a ton of context on the changes in 0.1.78. Maybe it's safer to do it in increments?

**Comment by evanpurkhiser** [comment]
0.1.77 and 0.1.78 are the same, 0.1.76 is what you're trying to bump here. Don't worry it's just my change

image

**Comment by ayirr7** [comment]
@evanpurkhiser ah ok. Bumped to 0.1.78

**Review by evanpurkhiser — APPROVED** [review]

**Pull request merged**
