### PR TITLE
fix(onboarding): replace weird progress node circles with svgs

### PR DESCRIPTION
**Pull request by Chrissy**
image

I also did some tidying on the `progress` tests.

### CODE REVIEW

**Comment by billyvg** [comment]
How would it look if the Node was vertically centered?

**Review by markstory — APPROVED** [review]
Code changes look good to me.

**Comment by Chrissy** [comment]
@billy you good?

**Review by billyvg — APPROVED** [review]
imo it looks better either centered or top aligned (top of the circle being above the text makes it look funny I think even though it makes sense to align checkmark with text)

**Comment by Chrissy** [comment]
Centering the icons with the first line of text is pretty standard. Perhaps you are responding to the overly-large size? Here is what it looks like with the icons bumped down a bit and no negative margin:

image

**Comment by Chrissy** [comment]
if we wanted to keep them big, I would be ok centering them if we shorten the last element to two lines (which i think we should do anyways):

image

**Comment by Chrissy** [comment]
cc @billyvg let's get it right!

**Comment by EvanPurkhiser** [comment]
image

This one looks like a winner to me.

**Comment by EvanPurkhiser** [comment]
Yeah I agree, that looks good to me.

**Pull request merged**
