### PR TITLE
feat(issue-details): Header changes + tags distribution

### PR DESCRIPTION
**Pull request by leeandher**
Does a few small things:

- Remove empty functions from sidebar
- Omit `archive` actions at all screen sizes for streamlined UI
- Adds the `Issue Tags` button alongside the graph
- Fixes the links for the 'Events' and 'Users' header

### CODE REVIEW

**Comment by roggenkemper** [comment]
slightly confused by the header now - i can't click on either events or users, but one is underlined so i feel like they should do different things
Screenshot 2024-10-29 at 2 23 37 PM

**Comment by leeandher** [comment]
> slightly confused by the header now - i can't click on either events or users, but one is underlined so i feel like they should do different things

Makes sense! I refactored a bit so it'll only have the underline when there is a link 👍

**Comment by scttcper** [comment]
not getting a link on events

image

**Comment by leeandher** [comment]
> not getting a link on events

I think we're removing it since it'd imply you could see all the events though it would take you to a table where you only see those in the last 90 days (cc @vuluongj20)

**Review by roggenkemper — APPROVED** [review]

**Pull request merged**
