### PR TITLE
fix(settings): Move Istanbul to time zone +3

### PR DESCRIPTION
**Pull request by ilhanyumer**
Unfortunately Istanbul has been in time zone +3 for 3 years. https://www.timeanddate.com/worldclock/turkey/istanbul

### CODE REVIEW

**Review by BYK — APPROVED** [review]
😢

**Comment by BYK** [comment]
@dashed  - we should also opt Istanbul timezone from DST. Is that possible?

**Comment by dashed** [comment]
@BYK Very good question. 

It looks like the timezone stuff was added in https://github.com/getsentry/sentry/pull/6905

@billyvg would you know the answer to @BYK 's question? Essentially Turkey is on UTC+03:00 for both standard time and daylight saving time. see: https://en.wikipedia.org/wiki/Time_in_Turkey#History

**Comment by billyvg** [comment]
I think that would depend on `moment-timezone`

**Comment by dashed** [comment]
@billyvg does that mean this PR change is not sufficient?

**Comment by billyvg** [comment]
The output times should be correct, it's just the label when selecting in the dropdown I believe:

image

**Comment by dashed** [comment]
Looks like this was landed in `2016g` of the `tz` database: https://github.com/eggert/tz/commit/3e31dbe52b8730ed762880e88bf4c68ac00b8cc3

and `moment-timezone@0.5.25` has `2019a`.

It should be good 👍

**Pull request merged**
