### PR TITLE
[WIP] Reprocessing Part 2: Actual Reprocessing

### PR DESCRIPTION
**Pull request by mitsuhiko**
This pull request is going to be the actual work for making reprocessing work again. Continued work from #4774

issues mov

### CODE REVIEW

**Comment by dcramer** [comment]
Why use Group to store these? Schema change on that table is expensive and it seems like you wouldn't want any of the features it provides

**Comment by mitsuhiko** [comment]
@dcramer expensive despite of nullable? It felt like the best place to store it since it's a simple bool that will get checked in various places.

**Comment by mitsuhiko** [comment]
Going to investigate using a new status instead of the column.

**Comment by mitsuhiko** [comment]
Note to myself: we need to make a decision what to do with dsym files for libswift*, kscrash etc. See 274e3c0eb2c2d422c052cf95c5c2c2df1eabde14

**Comment by mitsuhiko** [comment]
Closing in favor of #4867.

**Pull request closed without merging**
