### PR TITLE
Fixed an off-by-one error for JavaScript processing

### PR DESCRIPTION
**Pull request by mitsuhiko**
This replaces #5666 

This fixes two things:

* the off by one (affects grouping)
* correctly restores the "previous token" behavior (does not affect grouping)

# Backstory

The way we deal with minified stacktraces in javascript right now is that we attempt to resolve the token of the previous frame in the frame where the error happens. The reason for this is that the token where the error is happening is not the function name but the token closest to the source of the error.

Case in point:

```javascript
function foo() {
  throw new Error('test');
}

function bar() {
  foo();
}
```

In this case the token closest to the error location is `Error` in `foo` but we are actually interested in the function name (`foo`). The way @mattrobenolt solved this originally is that the token resolved is the token of the previous frame. So in the case above one frame above the closest token is `foo` so that one is taken.

The problem however is that this currently uses a off by one so for calls like `this.foo()` not `foo` is taken but `this`.

This is incorrect in all stacktraces unless the token to the left is the same token. This depends on the browser version about where the column is pointing (might point to the end of a token and not the start for instance).

There are two issues with this. One is the off by one this PR is solving, the other one is if the code we wrote is actually correct in how it resolves the function name (eg: uses the calling frame). This is not attempting on solving the latter issue.

### CODE REVIEW

**Comment by mitsuhiko** [comment]
This turns out to be significantly more broken than i thought. The entire path that sets the function from the previous frame is no longer working.

**Comment by getsentry-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Changes to build requirements</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Review by mattrobenolt — COMMENTED** [review]
Wanna exclude this `example-project` folder from the entire python package? Not sure it's worth bundling all of that up in the dist.

**Comment by mitsuhiko** [comment]
@mattrobenolt i thought we already skip the tests entirely on bundling?

**Comment by mattrobenolt** [comment]
Hmm, that might be true. https://github.com/getsentry/sentry/blob/master/MANIFEST.in

I also didn't notice that this was within tests. So should be fine.

**Comment by mitsuhiko** [comment]
@mattrobenolt good to merge?

I want to later make a separate PR that uses a newer version of rust-sourcemap once I land this: https://github.com/getsentry/rust-sourcemap/pull/4

**Review by mattrobenolt — APPROVED** [review]
Seems ok now.

**Comment by HazAT** [comment]
🎉

**Pull request merged**
