### PR TITLE
feat(replays): Replay event data section

### PR DESCRIPTION
**Pull request by danecando**
### Changes
- Adds a Replay section to Event Data details list
- Adds a link to a replay in the new replay section

### Notes
First task is adding a section that links to the replay. I was able to accomplish this without any additional or changes to data fetching by getting a replay id from the list of tags. Not sure if I'll be able to do the same to render the actual player haven't dug into that yet.

Not sure if this needs an `!isShare` check as well. 

Screen Shot 2022-07-18 at 3 05 08 PM

Part 1 of #36589 

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Comment by danecando** [comment]
> We should probably not show the old player if replayId exists: https://github.com/getsentry/sentry/pull/36775/files#diff-daae708decaed46eddf9114cdc158d758da7d0ddfa3dff8efe4deb5a7e8a18e3R437

I was asking Ryan about the existing RRWeb player in there because I wasn't sure what the difference was or how it related since the ticket is pretty similar. It doesn't seem to actually work though currently? He told me just to leave it for now though

**Comment by billyvg** [comment]
@danecando The existing player is for our previous rrweb integration, which iirc, will show if we have any attachments that start with `rrweb*`. I think w/ this change, we will always see two Replay headers for both the old rrweb player and your current change.

**Comment by danecando** [comment]
> @danecando The existing player is for our previous rrweb integration, which iirc, will show if we have any attachments that start with `rrweb*`. I think w/ this change, we will always see two Replay headers for both the old rrweb player and your current change.

@billyvg I only see this existing replay section on this issue that is an aggregate of all the sentry-replay events (I assume this will probably go away with backend changes) https://dev.getsentry.net:7999/organizations/sentry-emerging-tech/issues/3306973937/?query=is%3Aunresolved

It doesn't show up anywhere else I that I can tell where the events have a replayId. Should I just take this existing one out. My next task is adding the player to the replay section that I added.

**Comment by billyvg** [comment]
The logic should be if `replayId` exists then show new replay embed, otherwise show old

**Review by ryan953 — APPROVED** [review]

**Comment by ryan953** [comment]
This is replaced by #36818 

Same conditions for when to show the new section, but in #36818 the section has more going on which is nicer.

**Pull request closed without merging**
