### PR TITLE
Add proxies param for url_safeopen

### PR DESCRIPTION
**Pull request by xtao**
RT

### CODE REVIEW

**Comment by mattrobenolt** [comment]
Hey @xtao, thanks for the contribution!

What is your use case for this? For a plugin you're writing? This obviously isn't used for anything inside Sentry today, so was wondering what you needed this for before we merge this in. :)

**Comment by xtao** [comment]
@mattrobenolt When we deploy sentry to our production servers, we have a problem. Our production can't connect internet except for using proxy. We want to add proxies for `url_safeopen`, since we could use sentry-slack with notification.

**Comment by mattrobenolt** [comment]
Ah, would you be forking sentry-slack and adding it there for yourselves?

**Comment by mattrobenolt** [comment]
@xtao fwiw, these can be configured automatically with the environment variables `HTTP_PROXY` and `HTTPS_PROXY`.

Would that help? Then all outbound requests will go through your proxy automatically without the need to change any code.

**Comment by xtao** [comment]
@mattrobenolt I have forked sentry & sentry-slack in house. In my views, sentry-slack uses `sentry.utils.http`, maybe `proxies` for `url_safeopen` is better choice. We also have another problem about `BlacklistAdapter`. Can we add a switch for using `BlacklistAdapter`?

**Comment by dcramer** [comment]
@xtao matt is saying you can use those env variables to set a proxy (they're a semi standard)

also you can change the blacklist adapter by configuring SENTRY_DISALLOWED_IPS

**Comment by xtao** [comment]
@dcramer @mattrobenolt In our cases, sentry is in a weird environment.

```
[root@384491c9e4f4 app]# ping hooks.slack.com
ping: unknown host hooks.slack.com
```

We cannot touch hooks.slack.com except for http proxy. So `SENTRY_DISALLOWED_IPS` is useless for us.

**Comment by dcramer** [comment]
I'm not sure what you mean. You can completely disable it if you want by setting it to an empty list.

**Comment by xtao** [comment]
@dcramer In our cases, we cannot get ip from `hooks.slack.com`, our production server's dns is internal.
`BlacklistAdapter` would failed at `ip_address = socket.gethostbyname` before DISALLOWED_IPS checking.

```
>>> ip_address = socket.gethostbyname('hooks.slack.com')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
socket.gaierror: [Errno -2] Name or service not known
```

**Comment by dcramer** [comment]
@xtao ah! -- I think ideally we would simply handle that error, though I'm not sure what we should do there

**Comment by mattrobenolt** [comment]
I'm closing this PR since we're going to address the situation with #2665. Thanks!

**Comment by mattrobenolt** [comment]
Specifically, to address the issue here, 112dd509a853143da51101ef746d0a44892d76fc skips the DNS query if `SENTRY_DISALLOWED_IPS` is empty.

**Comment by xtao** [comment]
@mattrobenolt Thanks for your new pull request.

**Pull request closed without merging**
