### PR TITLE
fix(selectControl): fix multiple field selection

### LINKED ISSUE #47276: Jira integration issue
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

22.12.0

### Link

_No response_

### DSN

_No response_

### Steps to Reproduce

As far as I know you don't support anymore jira plugin, but jira server integration. Unfortunately I can't use Jira Server Integration due to security policy of Jira Server in my company. I decided re-write jira plugin and get rid of jira's deprecated method createmeta as you did for jira integration. It works. But I have visual bug with fields "Affects version" and "Fix Version". When I select smth in dropdown list, it doesn't shown as selected, actually nothing happens. But issue will be created with selected item even if it's not displayed on the UI. Also seems multiple choice for these fields doesn't work. The question is do you have the same issue with Jira integration? or know how to fix this issue?
paveikslas

### Expected Result

selected items are displayed correctly on the UI for fields "Affects version" and "Fix Version"

### Actual Result

selected items are displayed as unselected on the UI but actually used when jira issue is being created.

### PR DESCRIPTION
**Pull request by RedShiba**
Fixes #47276
thx for help @m-khvoinitsky 

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Review by vuluongj20 — APPROVED** [review]

**Comment by chadwhitacre** [comment]
Thanks for taking a look at this @vuluongj20! Since @RedShiba is an external contributor they can't merge this PR. Can you do that for them? :)

**Comment by chadwhitacre** [comment]
I believe [this test](https://github.com/getsentry/sentry/actions/runs/5146887877/jobs/9468104363#step:8:263) may signal a genuine regression, @RedShiba. Can you look into it?

**Comment by RedShiba** [comment]
> I believe [this test](https://github.com/getsentry/sentry/actions/runs/5146887877/jobs/9468104363#step:8:263) may signal a genuine regression, @RedShiba. Can you look into it?

Seems you're right. Thanks for noticed. I re-pushed with another solution that was suggested  by @m-khvoinitsky at the beginning of this journey.
Looks better now.

**Comment by chadwhitacre** [comment]
What I don't like here is that there's no clear explanation for _why_ this fixes #47276. If/when this regresses in the future, and someone else is looking at this code, how are they going to know what it is doing? I would like to see some better explanation here, ideally in a code comment, ideally with a new test or two.

**Review by scttcper — APPROVED** [review]

**Comment by vuluongj20** [comment]
@RedShiba Could you add a code comment explaining your fix? That way future developers will know why the mapping function needs to be written like that. I'll merge the PR once that's in!

**Comment by RedShiba** [comment]
@chadwhitacre  @vuluongj20 sorry for late response, I understand your concern, for a detailed explanation of this frontend magic I'm summoning @m-khvoinitsky :mage_man: Misha, please, join this convo. After that I'll leave code comment.

**Comment by m-khvoinitsky** [comment]
My apologies for the delay.
So, in my understanding, you have a component `SelectControl` which wraps `ReactSelect`. `ReactSelect` demands its `value` to be exactly either one of or array of some of `options` (or at least the same type). However, `SelectControl` allows `value` property to be not only [OptionType](https://github.com/getsentry/sentry/blob/11ffc47c4239eb4931075e4d18d52e09d0cba9e2/static/app/components/roleSelectControl.tsx#LL8C6-L8C16) but also just OptionType's [`value` property](https://github.com/getsentry/sentry/blob/11ffc47c4239eb4931075e4d18d52e09d0cba9e2/static/app/components/roleSelectControl.tsx#L12).
Which is exactly what is written in the [comment](https://github.com/getsentry/sentry/blob/11ffc47c4239eb4931075e4d18d52e09d0cba9e2/static/app/components/forms/controls/selectControl.tsx#L137):
```
  /**
   * Unlike react-select which expects an OptionType as its value
   * we accept the option.value and resolve the option object.
 ```
So, resolving OptionType's value fileld into whole OptionType is happening [here](https://github.com/getsentry/sentry/blob/11ffc47c4239eb4931075e4d18d52e09d0cba9e2/static/app/components/forms/controls/selectControl.tsx#L400). But in case of single `value` (not array) you already had fallback `|| value` clause which apparently allows using `SelectControl` the same way as `ReactSelect` (i. e. passing whole OptionType as value). What I've added is `val.value ? option.value === val.value` which does almost exactly the same for `Array<OptionType>` `value`: if it's already looks like OptionType, look for matching option in the appropriate way. That's seems to be how it was used in Jira plugin and the old code in this case wouldn't able to find matching value from `options` and just forwarded `null` as a value to `ReactSelect`.

**Comment by RedShiba** [comment]
Can anyone reopen it? Seems it wasn't merged to master :(

**Pull request closed without merging**
