### PR TITLE
Create file tables without db constraint on fks

### PR DESCRIPTION
**Pull request by beezz**
To not break multi-database setup for getsentry in dev and test we need to create these foreign keys without database constraints.

https://github.com/getsentry/getsentry/pull/5884 moves multiple tables to a non-default (`files`) database connection (`secondary` in dev/test) therefore we need to create those tables already without db constraint.

### CODE REVIEW

**Comment by wedamija** [comment]
Why do we need to modify the old migrations?

**Comment by beezz** [comment]
> Why do we need to modify the initial migrations?

You asked (few seconds) before I was able to update the PR description. Does it answer your question?

**Comment by wedamija** [comment]
> > Why do we need to modify the initial migrations?
> 
> You asked (few seconds) before I was able to update the PR description. Does it answer your question?

Ahh fair enough. @billyvg is in the process of making `migrations / check if modified migration` not required, so I'll approve, then once he commits that to master you'll need to rebase and you'll be able to merge without someone forcing it.

**Review by wedamija — APPROVED** [review]

**Comment by billyvg** [comment]
No need to rebase

**Pull request merged**
