### PR TITLE
Fixed #2206 - Show error message if team slug already exists

### LINKED ISSUE #2206: 500 error when rename team slug
Error raised if same slug already exists

Traceback:
```
File "/home/www/pyenv/versions/sentry/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
     response = wrapped_callback(request, *callback_args, **callback_kwargs)
   File "/home/www/pyenv/versions/sentry/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
     return self.dispatch(request, *args, **kwargs)
   File "/home/www/pyenv/versions/sentry/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
     return bound_func(*args, **kwargs)
   File "/home/www/pyenv/versions/sentry/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
     response = view_func(request, *args, **kwargs)
   File "/home/www/pyenv/versions/sentry/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
     return func(self, *args2, **kwargs2)
   File "/home/www/pyenv/versions/sentry/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 144, in dispatch
     return self.handle(request, *args, **kwargs)
   File "/home/www/pyenv/versions/sentry/lib/python2.7/site-packages/sentry/web/frontend/team_settings.py", line 37, in handle
     team = form.save()
   File "/home/www/pyenv/versions/sentry/lib/python2.7/site-packages/django/forms/models.py", line 446, in save
     construct=False)
   File "/home/www/pyenv/versions/sentry/lib/python2.7/site-packages/django/forms/models.py", line 99, in save_instance
     instance.save()
   File "/home/www/pyenv/versions/sentry/lib/python2.7/site-packages/sentry/models/team.py", line 141, in save
     super(Team, self).save(*args, **kwargs)
   File "/home/www/pyenv/versions/sentry/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
     force_update=force_update, update_fields=update_fields)
   File "/home/www/pyenv/versions/sentry/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
     updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
   File "/home/www/pyenv/versions/sentry/lib/python2.7/site-packages/django/db/models/base.py", line 635, in _save_table
     forced_update)
   File "/home/www/pyenv/versions/sentry/lib/python2.7/site-packages/django/db/models/base.py", line 679, in _do_update
     return filtered._update(values) > 0
   File "/home/www/pyenv/versions/sentry/lib/python2.7/site-packages/django/db/models/query.py", line 510, in _update
     return query.get_compiler(self.db).execute_sql(None)
   File "/home/www/pyenv/versions/sentry/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 980, in execute_sql
     cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
   File "/home/www/pyenv/versions/sentry/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
     cursor.execute(sql, params)
   File "/home/www/pyenv/versions/sentry/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
     return self.cursor.execute(sql, params)
   File "/home/www/pyenv/versions/sentry/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
     six.reraise(dj_exc_type, dj_exc_value, traceback)
   File "/home/www/pyenv/versions/sentry/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
     return self.cursor.execute(sql, params)
 IntegrityError: duplicate key value violates unique constraint "sentry_team_organization_id_1e0ece47434a2ed_uniq"
 DETAIL:  Key (organization_id, slug)=(1, adwile) already exists.
```

### PR DESCRIPTION
**Pull request by alexm92**
Hi,

I did a check at save and if there is another team with the same slug I displayed a error message.

Thanks,
Alex M

### CODE REVIEW

**Comment by mattrobenolt** [comment]
Hey @alexm92, thanks for the contribution! Would it be troubling to ask for a test that covers this?

I'd be happy to give some guidance to help if needed. If not, I can merge and backfill.

**Comment by alexm92** [comment]
Hey @mattrobenolt, I'd be glad to do some tests, thus can you give me some hints? What am I doing wrong in the test? Isn't the second team created and saved?

**Comment by dcramer** [comment]
@alexm92 Thanks! I went ahead and fixed up the patch to be more how we do it elsewhere and expanded on your changes. It should give you a better idea for how we do tests (our fixtures require a bit of knowledge). We also had a bug in the API for changing team slugs and corrected that here as well.

**Comment by alexm92** [comment]
@dcramer Thanks! :)

**Pull request merged**
