### PR TITLE
Revert "fix(jira): adds content security policy"

### PR DESCRIPTION
**Pull request by scefali**
Reverts getsentry/sentry#20866

### CODE REVIEW

**Review by mattrobenolt — APPROVED** [review]
lol

**Comment by scefali** [comment]
@mattrobenolt Yea, this change didn't work unfortunately hahah

**Comment by mattrobenolt** [comment]
Why not? Any context on what the issue was would be useful.

**Comment by scefali** [comment]
> Why not? Any context on what the issue was would be useful.
@mattrobenolt I honestly don't know why it's not working. I don't see a console error for the iFrame like I saw the first time I made the change before the Getsentry PR. I know `X-Frame-Options` is set to `deny` here but it's that way in my local environment as well and it works. I can see the `frame-ancestors` block in `Content-Security-Policy`. So I just don't know...

**Comment by scefali** [comment]
@mattrobenolt And now it's working again before the revert PR has been deployed. This makes absolutely no sense...

**Pull request merged**
