### PR TITLE
Log when user enables or disables a plugin

### PR DESCRIPTION
**Pull request by gsan2**
WIP

### CODE REVIEW

**Comment by gsan2** [comment]
Made changes suggested by Eric to refactor (moving the audit log entry out of critical path) in the code.

**Comment by theharshitgarg** [comment]
@mattrobenolt I would like to help by working on this issue. can u please update the issue if not solved yet.

**Comment by markstory** [comment]
Is this something we're still interested in pursuing or can it be closed because it can no longer be merged?

**Comment by mattrobenolt** [comment]
@markstory if you wanna pick this up and finish it, I think it'd be reasonable. I thought we had this already in codebase, but I guess we don't.

**Comment by markstory** [comment]
Closing as we *do* have audit log events for plugins already. The current audit logs are `INTEGRATION_(ADD|EDIT|REMOVE)`

**Pull request closed without merging**
