### PR TITLE
Rebrand Rules as Alerts / Alert Rules

### PR DESCRIPTION
**Pull request by dcramer**
This renames "Rules" to "Alerts", and changes the context of Rules to be "Alert Rules". It also removes server-side components for rule list and delete rule, and moves them into React.

/cc @getsentry/team

---

This change is [Reviewable](https://reviewable.io/reviews/getsentry/sentry/3947)

### CODE REVIEW

**Comment by dcramer** [comment]
I think one more change I'd like to do as part of this:

- Move "Mail subject prefix" to General settings
- Combine Notifications with Alerts, and call it Alerts.

**Comment by dcramer** [comment]
Blocked on #3986

**Comment by dcramer** [comment]
So the remaining blocker is to deal with HipChat.

Here's the current plan:

- Move sentry-hipchat-ac into sentry-plugins
- Add a React component (transitional) that will implement the old UI
- Build webpack as part of sentry-plugins (using utilities from sentry if needed)
- Use the exposed "sentry" object as the public API for Sentry's JS. Alternatively we expose sentry.plugins though thats kind of wasteful since we might need form components/etc.

**Comment by dcramer** [comment]
Feeling pretty good about this now. It's fully implemented using new plugin APIs, and the new hipchat AC works in this model.

**Comment by dcramer** [comment]
@benvinegar @ckj would be good to get some eyes on this in its current form

**Comment by ckj** [comment]
This is a pretty big improvement. Appreciate how well it simplifies the concept.

The only feedback I have after poking around for a few minutes is that when I go to add or edit an alert rule, I lose the Alerts heading and active nav indicator. Since there's not a back or cancel button it took me a couple of clicks to get back to the rule list (though I guess I could have just used the back button).

screen shot 2016-09-08 at 3 03 21 pm

Overall, huge 👍 .

**Comment by dcramer** [comment]
@ckj yeah tbh i can spend more time and just finish this entirely. Right now edit rule renders on server yet, which sucks since it causes a huge wait time to unload/reload.

**Comment by dcramer** [comment]
I'm calling this done, as it's way too much work to refactor rule editor right now.

**Comment by benvinegar** [comment]
Reviewed 6 of 24 files at r1, 7 of 11 files at r2, 3 of 4 files at r3, 1 of 2 files at r4.
Review status: 17 of 33 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[src/sentry/static/sentry/app/views/projectAlertSettings.jsx, line 32 at r4](https://reviewable.io:443/reviews/getsentry/sentry/3947#-KRa0rDzKhiM1JRm4i1C:-KRa0rE-GQQavF6LCJUN:b-knh6dz) ([raw file](https://github.com/getsentry/sentry/blob/abc43d1f4b3b38ce7c757d450819d4d4145ccc07/src/sentry/static/sentry/app/views/projectAlertSettings.jsx#L32)):*
> ```JSX
>     formData[name] = value;
>     this.setState({
>       formData: formData,
> ```

This would also work:

```javascript
this.setState({
  formData: {
    ...formData,
    [name]: value
  }
});
```

... and will also return a new reference for `formData` to `setState`.

---

*[src/sentry/static/sentry/app/views/projectAlertSettings.jsx, line 74 at r4](https://reviewable.io:443/reviews/getsentry/sentry/3947#-KRa1MjZRRQdGKrq1VGA:-KRa1MjZRRQdGKrq1VGB:b-8tp9uf) ([raw file](https://github.com/getsentry/sentry/blob/abc43d1f4b3b38ce7c757d450819d4d4145ccc07/src/sentry/static/sentry/app/views/projectAlertSettings.jsx#L74)):*
> ```JSX
>     let isSaving = this.state.state === FormState.SAVING;
>     let {errors, formData} = this.state;
>     let hasChanges = !underscore.isEqual(this.props.initialData, formData);
> ```

Weirds me out to see underscore not imported as `_`

---

*[src/sentry/static/sentry/app/views/projectAlertSettings.jsx, line 197 at r4](https://reviewable.io:443/reviews/getsentry/sentry/3947#-KRa2W0fYHAhbatS3_ck:-KRa2W0fYHAhbatS3_cl:b3w39w0) ([raw file](https://github.com/getsentry/sentry/blob/abc43d1f4b3b38ce7c757d450819d4d4145ccc07/src/sentry/static/sentry/app/views/projectAlertSettings.jsx#L197)):*
> ```JSX
>     project.digestsMinDelay = data.digestsMinDelay;
>     project.digestsMaxDelay = data.digestsMaxDelay;
>     this.setState({project: project});
> ```

I think ES6 spreads makes this look nicer and again ensures we pass new instances to `setState`:

```javascript
this.setState({
  project: {
    ...project,
    digestsMinDelay: data.digestsMinDelay,
    digestsMaxDelay: data.digestsMaxDelay
  }
});
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3947)*

**Pull request merged**
