### PR TITLE
Stats not always available

### PR DESCRIPTION
**Pull request by Kronuz**
Otherwise on a clean install, I'm getting an exception when visiting an Issue

### CODE REVIEW

**Comment by mattrobenolt** [comment]
Kicking over to @benvinegar since I'm not sure if this is the best failure scenario or if there's a better option.

Thanks for the contribution! :cake: :icecream:

**Comment by Kronuz** [comment]
`groupChart.jsx` also has that `if()` there, but it doesn't check the length, but only stats. I added that check there too, assuming both should be almost the same... at least this fixes the crash for now

**Comment by dcramer** [comment]
@benvinegar ping

**Comment by benvinegar** [comment]
There's no harm with doing this, and not breaking things is good.

**Pull request merged**
