### PR TITLE
fix(workflow): Alert Rule creation bug

### PR DESCRIPTION
**Pull request by iProgramStuff**
Fixes https://sentry.io/organizations/sentry/issues/2274496929/

### CODE REVIEW

**Comment by alxu-sentry** [comment]
fwiw i think this is also needed to fix `load-mocks` use of `create_alert_rule`.

**Comment by iProgramStuff** [comment]
> fwiw i think this is also needed to fix `load-mocks` use of `create_alert_rule`.

I actually think it's okay. Which means it's probably currently broken. So this PR also fixes it.

**Comment by alxu-sentry** [comment]
> > fwiw i think this is also needed to fix `load-mocks` use of `create_alert_rule`.
> 
> I actually think it's okay. Because it doesn't pass the owner. Which means it's probably currently broken. So this PR also fixes it.

i think my wording was a little confusing: i meant that `load-mocks` is currently broken, but this PR should fix it, not that this PR needs to be changed to fix `load-mocks`. 👍 either way :)

**Review by wedamija — APPROVED** [review]

**Comment by iProgramStuff** [comment]
Closing in favour of https://github.com/getsentry/sentry/pull/24458

**Pull request closed without merging**
