### PR TITLE
feat(org-stats): Allow absolute date selection

### PR DESCRIPTION
**Pull request by leedongwei**
When selecting the date range by...
* relative periods (e.g. "last 14 days"), we will display datetime
  * in local timezone if interval is <24h
  * in UTC if interval is >= 24h (otherwise the 24 hour range for a date will vary in different timezones)
* in absolute date ranges (e.g. "Apr 1 - Apr 31"), we will display datetime
  * in local timezone if UTC is not selected
  * in UTC if UTC is selected
  * override to UTC if interval >= 24h

I've ensured that date strings being passed between components are always in UTC, otherwise doing add/subtract on them will cause weird behaviours on DST dates.

---

image

image

image

### CODE REVIEW

**Comment by benvinegar** [comment]
Is there a particular reason we're putting the data type dropdown (Errors/Transactions/Attachments) all the way on the right? Why not on the left?

**Comment by leedongwei** [comment]
Mostly because picking the data category doesn't require a lot of screen space.

I have no strong opinions on the layout, so happy to shuffle things around.

Screen Shot 2021-04-27 at 9 44 47 AM

**Review by RyanSkonnord — APPROVED** [review]
Code LGTM.

**Comment by EvanPurkhiser** [comment]
Could we do something to make the date range picker.. look nicer?

**Comment by leedongwei** [comment]
@EvanPurkhiser I took that from the GlobalSelectionHeader 😬

**Comment by EvanPurkhiser** [comment]
Why can't we just use the global selection header here?

**Comment by leedongwei** [comment]
@EvanPurkhiser In this version of the page, we don't want to support filtering by project or environment.

With the GSH, if I select a project on the header, I expect the bar chart to display the stats for the project and the table to show the environment. We want to keep the bar chart as org-level only.

**Comment by EvanPurkhiser** [comment]
We should change the height of the dropdown then maybe so the times don't look so squished in absolute mode.

cc @doralchan

**Pull request merged**
