### PR TITLE
Initial pass at new stacktrace rendering

### PR DESCRIPTION
**Pull request by dcramer**
- New cell-based stack rendering
- Hide line numbers and "application" notation
- Add PHP specific rendering
- Remove legacy CSS
- Left-truncate filenames (expand on hover)
- Add clipping to stack locals
- Prevent propagation of clicks on ClippedBox
- Dont collapse context on click (require header click)

screenshot 2016-06-11 17 02 30

TODO:
- [x] add way to expand/collapse stack locals
- [ ] add way to expand/collapse all frames
- [ ] tweak frame header details to be more concise based on language
- [ ] confirm cocoa isn't broken
- [ ] finalize visuals
- [x] indicator for app vs non-app frames
- [x] improve visuals when only single context line (remove active highlight?)
- [x] improve mouseover effects (no cursor) when no context
- [x] improve visuals around filename + function (truncation is awful in some cases like Java)
- [x] disable expand/collapse behavior when no context
- [ ] rename "App Only" to "Focused" or something similar

@getsentry/ui

### CODE REVIEW

**Comment by dcramer** [comment]
This is unfinished and I have not yet tested Cocoa

**Comment by dcramer** [comment]
This is live on staging

**Comment by dcramer** [comment]
@mitsuhiko is going to put this behind a feature switch

**Comment by mitsuhiko** [comment]
@dcramer should we roll this out?

**Comment by dcramer** [comment]
+1 -- we can probably push to staging without the switch enabled to make sure nothings butchered, but as long as we haven't regressed on the existing rendering no complaints here

**Pull request merged**
