### PR TITLE
Add gettext and trans tags to feedback form

### PR DESCRIPTION
**Pull request by bjornkri**
A premature PR but following from the discussion started here: https://forum.sentry.io/t/localising-the-feedback-form/81

This might well just work as is, but I seem to remember we need some extra steps to get django to  generate a catalog of translation strings that javascript can use. Using makemessages that means generating a separate one with `-d djangojs` as an argument. Not completely sure how to test this, any tips welcome.

---

This change is [Reviewable](https://reviewable.io/reviews/getsentry/sentry/4106)

### CODE REVIEW

**Comment by dcramer** [comment]
We'll want to do two things I think:

1. Change translation tags in the embed.js to use standard Django hooks. I think likely we can just provide the strings via the backend view (so escaping is less of an issue).
2. Add a setting to control what the language will be here, but focus on:
  - automatic (select how Django normally would
  - [list of choosable languages]

We can def help with the setting, and that can start as automatic with us following up on that. I would want to confirm that we haven't hijacked Django's mechanism here, possibly by having a test which asserts that we're rendering e.g. German language when the browser is requesting German.

**Comment by bjornkri** [comment]
Ok, sounds good. If I understood you correctly, I have completed step 1. Trying to figure out how to test this, having problems running the tests - or anything for that matter - on my branch locally.

**Comment by dcramer** [comment]
'make test' should give you a full time env though it assumes you have an active virtualenv. I'll see if I can't find someone (or some time) to help with a test here as well. I don't think we test localization anywhere else in the app.

**Comment by bjornkri** [comment]
I keep running into this (also with 'make test'):

`running [webpack]

Traceback (most recent call last):

  File "/Users/bjornkri/dev/sentry/src/sentry/utils/distutils/commands/build_assets.py", line 114, in _build

    self._build_static()

  File "/Users/bjornkri/dev/sentry/src/sentry/utils/distutils/commands/build_assets.py", line 136, in _build_static

    cwd=self.work_path, env=env)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 566, in check_output

    process = Popen(stdout=PIPE, *popenargs, **kwargs)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__

    errread, errwrite)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child

    raise child_exception

OSError: [Errno 2] No such file or directory

unable to build Sentry's static assets!

Hint: You might be running an invalid version of NPM.

----------------------------------------
Cleaning up...
Command /Users/bjornkri/.envs/sentry/bin/python -c "import setuptools, tokenize; __file__='/Users/bjornkri/dev/sentry/setup.py'; exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps failed with error code 1 in /Users/bjornkri/dev/sentry
Storing debug log for failure in /Users/bjornkri/.pip/pip.log
make: *** [install-python] Error 1
`

Originally with 2.14.12, upgraded to 3.10.7 and still get the same.

**Comment by dcramer** [comment]
Does webpack exist in ``node_modules/.bin`` for you?

**Comment by bjornkri** [comment]
Yep

**Comment by dcramer** [comment]
@bjornkri while I cant explain what exactly was going on, I whipped up a quick test and merged in the change.

**Comment by dcramer** [comment]
(of note once you have dependencies installed you *should* be able to simply ``py.test tests/``)

**Pull request closed without merging**
