### PR TITLE
feat(discover): Update drf-spectacular to latest

### PR DESCRIPTION
**Pull request by wmak**
- Updates the `drf-spectacular` library to latest, to get `many` support for the parameters
- Needed to rename the org stats name since spaces are no longer supported

### CODE REVIEW

**Review by AniketDas-Tekky — APPROVED** [review]
LGTM, Not sure if some other codeowner needs to approve though

**Comment by asottile-sentry** [comment]
looks like the checked in openapi json needs to be updated as well

**Comment by asottile-sentry** [comment]
> @asottile-sentry I believe that check just points out that there was a change to the json, and will push to `sentry-api-schema` once this branch merges

ah cool!

**Review by asottile-sentry — APPROVED** [review]

**Pull request merged**
