### PR TITLE
fix(tests): Cleanup after overwriting values

### PR DESCRIPTION
**Pull request by mnoble**
This was messing with other tests that end up resolving to the test blacklisted IPs here, since it's changing the module's value (opposed to stubbing it via `patch` or something that would be cleaned up).

This now just reverts back to the initial value at the end of each test that changes it.

### CODE REVIEW

**Review by mattrobenolt — APPROVED** [review]
Why don't we just move this to a decorator or something with a `with` block or anything better than manually setting/unsetting in each test case.

Could even just do this in `setUp` `tearDown` methods of this test class if we don't wanna reuse it.

Approving this since it works, but would like to see it made a little less clunky.

**Comment by mnoble** [comment]
@mattrobenolt 👍good suggestion. Switched it to a decorator.

**Review by markstory — APPROVED** [review]
Very nice :clap:

**Comment by MeredithAnya** [comment]
ty ty

**Pull request merged**
