### PR TITLE
feat: enable biome css formatter and linter

### PR DESCRIPTION
**Pull request by anonrig**
Probably too early to land this, since there might be some hidden bugs with the CSS formatter and linter, but it's nice to finally remove `stylelint` from Sentry.

cc @getsentry/app-frontend @getsentry/dev-infra

### CODE REVIEW

**Comment by scttcper** [comment]
`postcss-styled-syntax` is a related package

this could be removed 
https://github.com/getsentry/sentry/blob/master/config/tsconfig.base.json#L108-L112

**Comment by scttcper** [comment]
still just seeing stylelint and not biome pick these up

image

**Comment by anonrig** [comment]
> `postcss-styled-syntax` is a related package
> 
> this could be removed https://github.com/getsentry/sentry/blob/master/config/tsconfig.base.json#L108-L112

afaict, styled-components are still not yet supported. only CSS/LESS files are supported at the moment.

**Comment by scttcper** [comment]
@anonrig ah i see this is a replacement for linting the css files

**Pull request closed without merging**
