### PR TITLE
ref(relay): Display a grayed relay content if user hasn't org:write access

### PR DESCRIPTION
**Pull request by priscilawebdev**
closes: https://app.asana.com/0/1182975495223897/1199338049237258

### CODE REVIEW

**Comment by matejminar** [comment]
With access:
image

Without access:
image

Would it make sense to only disable mutating action buttons like Register Key, Edit, and Delete?

**Comment by priscilawebdev** [comment]
@matejminar this is how we are displaying the contents of a setting if the user does not have `org:write` access

**Comment by matejminar** [comment]
With forms, yes, but this looks more like a list of data that you can read but not mutate, kind of like tags:

image

**Comment by priscilawebdev** [comment]
@matejminar I agree and I have updated the PR

**Review by matejminar — APPROVED** [review]

**Review by jan-auer — APPROVED** [review]
Approving product changes & screen shots. Please double-check that every control is indeed disabled.

**Pull request merged**
