### PR TITLE
This fixes exception_name handling for ios

### PR DESCRIPTION
**Pull request by mitsuhiko**

### CODE REVIEW

**Comment by dcramer** [comment]
It'd be good to start commenting this stuff. There's no tests and at a glance I would have no clue what's going on, why this value isn't set, or why the other value makes sense.

**Comment by mitsuhiko** [comment]
Yeah. I need to start looking into test coverage for this.

**Comment by mitsuhiko** [comment]
FWIW i'm going to clean this up anyways with the new reporting interface so this is short living code most likely.

**Comment by markstory** [comment]
This pull request cannot be merged currently. Without further updates it will be closed in a few days.

**Pull request closed without merging**
