### PR TITLE
feat(echart): Enable lines to be drawn in BarChart

### PR DESCRIPTION
**Pull request by leedongwei**
Current implementation of `BarChart` is too restrictive and does not allow us to draw lines.

WIP: Running Percy to see if I'm breaking stuff.

### CODE REVIEW

**Comment by billyvg** [comment]
Is it still a bar chart if you're using lines?

**Comment by leedongwei** [comment]
@billyvg I'm working on a bar chart that has 1 line across the y-axis to indicate max values. `barSeries.jsx` overwrites all `series.type`, making it impossible to draw that line. 

I'm trying to use the `BaseChart` so we'll see where that leads me.

**Comment by billyvg** [comment]
@leedongwei Ahh -- I'd probably suggest we leave `barSeries` restrictive, and instead change the <BarChart> API to maybe take in an additional list of series that do not get coerced into using `BarSeries`.

**Comment by leedongwei** [comment]
Closing due to getsentry/getsentry#4243

**Pull request closed without merging**
