### PR TITLE
Add error handling when saving current search

### PR DESCRIPTION
**Pull request by MrSaints**
Previously, any errors in the `SaveSearchButton` component form
will not be displayed. The modal will simply remain open.
It is possible to trigger an error by saving a search with a name
that already exists. Thus, for UX, an error message should be shown.

This commit implements basic handling inspired by the `TeamSettingsForm`
component. It also replaces the custom `SaveSearchState` with `FormState`,
and resets the state to `READY` when the request succeeds. It would
previously however, always set the state to `ERROR`.

---

The way request errors are handled across Sentry frontend appears to be really inconsistent. I've opted for mimic'ing the `TeamSettingsForm` as it will result in the least significant changes so that further, major refactoring can be done in the future.

---

Here's how it looks:

screen shot 2017-04-26 at 18 24 40

### CODE REVIEW

**Review by MaxBittker — APPROVED** [review]
Solid improvement, this looks good to me. ⚡️

**Comment by MaxBittker** [comment]
totally agreed re: the inconsistent error handling, it's something that we do in an adhoc way still. This was a pragmatic solution for the component.

**Comment by MrSaints** [comment]
Cheers for the ⚡️ review, and merge @MaxBittker! 😅 Hopefully we can consolidate error handling in the near future.

**Comment by MaxBittker** [comment]
no problem, thank you for the PR! (after looking at it once more, I would have preferred 'error' over errors, and maybe false over {}, but it's clearly not a big deal)

**Comment by MrSaints** [comment]
Apologies, I took the naming from `TeamSettingsForm` since errors may be extended to encapsulate field specific errors.

**Comment by MaxBittker** [comment]
don't worry about it 👍  natural cost of having patterns be denormalized like this

**Pull request merged**
