### PR TITLE
Update Java example event.

### PR DESCRIPTION
**Pull request by bretthoerner**
@ehfeng 

This is viewable here (for now): https://sentry.io/bretthoerner/brett-hoerner-test/issues/322830602/

I tried to make use of all the features. The code is made up stuff, we can tweak it if we want.

I just downloaded the JSON from Sentry after sending the event. It seems like a lot of fields are left out of the samples (id, project, etc) so I removed those...

### CODE REVIEW

**Comment by getsentry-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Review by ehfeng — APPROVED** [review]
lgtm

**Comment by MaxBittker** [comment]
what about context lines?

**Comment by bretthoerner** [comment]
We don't support that on Java since it's compiled and the source is lost. 😑

**Comment by ehfeng** [comment]
But some glorious day, we'll have stack locals!

**Pull request merged**
