### PR TITLE
feat(perf-issues): Extract common base path of N+1 API Calls repeated spans

### PR DESCRIPTION
**Pull request by gggritso**
**Before:**
Screen Shot 2023-01-16 at 4 22 23 PM

**After:**
Screen Shot 2023-01-16 at 4 22 50 PM

I think the copy here could use work, but we'll come back to that in the near future.

### CODE REVIEW

**Review by 0Calories — APPROVED** [review]
Looks good, my suggestions for improving the copy in the future would be to leave in the API request method and the span op, i.e `http.client - GET /book`

**Comment by gggritso** [comment]
@0Calories I'll bring that up, thanks! I omitted both on purpose for since by definition the N+1 API calls detector is for `GET` requests of `http.client` spans

**Comment by 0Calories** [comment]
That's fair, my only concern is that at that point we're no longer pointing out repeating "spans", just a fragment of the API URL so maybe we should change the span evidence text accordingly?

**Comment by gggritso** [comment]
@0Calories definitely maybe! I have a task already to go over the complete page with Dora once it's all in production

**Pull request merged**
