### PR TITLE
Implement hashing for single threads

### LINKED ISSUE #5245: Support Thread Grouping
Currently we do not group by the threads interface if there is a single thread. This was done intentionally because we do not want to group by threads normally however for a single thread case and no exception we do want to do it since clients can send thread data long on iOS for log messages.

### PR DESCRIPTION
**Pull request by mitsuhiko**
The idea here is that for iOS we do not use message + stacktrace but message
+ single thread and we want to group there correctly.  The reason iOS does
this is that the stacktrace interface does not support raw stacktrace content
and so the thread interface was used as a workaround for this limitation.

Fixes #5245

### CODE REVIEW

**Comment by dcramer** [comment]
Could we put a test in that exhibits what this is solving?

**Review by mattrobenolt — CHANGES_REQUESTED** [review]
Yeah, I'd just love to see some tests cases here or something to actually explain the issue, as well as prove that we're not regressing anywhere else.

**Comment by edenman** [comment]
I raised the original support request that prompted this change, so I can at least comment on the "explain the issue" part.  The issue is that my iOS app is sending an event to Sentry with information about the event in the `message`.  Sentry is creating separate issues on the web for each different `message` value, regardless of the stacktraces being identical.

If you can see my project, here's an example:
https://sentry.io/recharge/consumer-ios/issues/253613441/
https://sentry.io/recharge/consumer-ios/issues/253613438/

**Comment by edenman** [comment]
bump.  @mitsuhiko can you explain how your change solves this problem?  it's really annoying that i have to play whack-a-mole with all of these duplicate Sentry issues.

**Comment by mitsuhiko** [comment]
Hi @edenman. I wanted to deploy this together with some other changes (https://github.com/getsentry/sentry/issues/5335) most likely monday next week unless something comes up. I understand the current situation is not great but since this changes grouping behavior for users and we have another grouping change coming up I wanted to get them out together to reduce the impact a bit.

**Comment by edenman** [comment]
@mitsuhiko works for me!  as long as you can get @mattrobenolt or @dcramer to give you a 👍 in the meantime :)

**Comment by mitsuhiko** [comment]
@mattrobenolt added tests for this.

**Comment by edenman** [comment]
(bump)

**Review by mattrobenolt — APPROVED** [review]

**Comment by mitsuhiko** [comment]
This is now merged.

**Pull request closed without merging**
