### PR TITLE
ref(admin): Convert most pages -> React

### PR DESCRIPTION
**Pull request by evanpurkhiser**
This is in an effort to completly remove the sidebar rendering fron the
layout.html

There are only a few more templates that don't disable the sidebar

### CODE REVIEW

**Comment by EvanPurkhiser** [comment]
Will need to check some getsentry stuff for this.

**Comment by dcramer** [comment]
dis good #hackweek

**Review by markstory — COMMENTED** [review]
Changes look good to me. Is it worth adding visual snapshots on these endpoints as they don't appear to have any other form of testing on them.

**Comment by EvanPurkhiser** [comment]
> Is it worth adding visual snapshots on these endpoints as they don't appear to have any other form of testing on them.

I'm not particularly worried about them right now. They are primarily for the OSS app.

**Review by markstory — APPROVED** [review]

**Pull request merged**
