### PR TITLE
ref(stream): Move constants out of props

### PR DESCRIPTION
**Pull request by lynnagara**

### CODE REVIEW

**Review by billyvg — COMMENTED** [review]
Why move these out of props?

**Comment by lynnagara** [comment]
It's way cleaner, I wanted to move all the constants for this file together

**Review by billyvg — APPROVED** [review]
It seems like a tiny step backwards removing props from `<Stream>` for marginal gains in legibility,  but we also don't re-use `<Stream>` anywhere ¯\_(ツ)_/¯

That said, the `default*` props do make much more sense as constants, but `maxItems` seems better fit as a prop imo.

**Comment by lynnagara** [comment]
I don't think we ever should use default props when we mean constants. You can't read the component and see what is actually being passed in and what is not

**Pull request merged**
