### PR TITLE
fix(modals): Do not nest modals inside links

### PR DESCRIPTION
**Pull request by lynnagara**
Do not nest modals inside links

Updated enzyme-to-json for React.Fragment support

### CODE REVIEW

**Comment by getsentry-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by MaxBittker** [comment]
why was the nesting a problem?

**Review by MaxBittker — APPROVED** [review]
looks good 💔

**Comment by macqueen** [comment]
thanks for fixing! ✨

**Comment by lynnagara** [comment]
@MaxBittker I think the click gets propagated to the original action button, which causes the toggle function to get called a second time. I think @billyvg might've spotted a couple of these in getsentry which we'll fix tomorrow. For some reason some of the modals were like this and others weren't.

**Pull request merged**
