### PR TITLE
fix(suspect-spans): Handle key error in suspect spans exclusive time

### PR DESCRIPTION
**Pull request by udameli**
This PR handles a [KeyError](https://sentry.io/share/issue/cb49bdad614945d1ad1823e8e33c822f/) in example transactions. The conditions when a `span` doesn't have a parent id are still not clear, but this should at least handle the error.

Fixes SENTRY-TCQ

### CODE REVIEW

**Comment by udameli** [comment]
not sure why visual tests are failing here since I haven't touched the code affecting user misery and transactions per minute charts 🤔 could be a flake?

**Review by dashed — APPROVED** [review]

**Review by Zylphrex — APPROVED** [review]

**Comment by Zylphrex** [comment]
> not sure why visual tests are failing here since I haven't touched the code affecting user misery and transactions per minute charts 🤔 could be a flake?

Yeah, this looks like a flake

**Comment by Zylphrex** [comment]
FYI, if you add Fixes SENTRY-TCQ in your commit message [docs](https://docs.sentry.io/product/integrations/source-code-mgmt/github/#resolve-via-commit-or-pull-request), sentry will automatically mark the issue as resolved for you. And as a convention, we try to append that as a footer in the commit message. See our develop docs [here](https://develop.sentry.dev/commit-messages/#commit-message-format).

**Comment by udameli** [comment]
> FYI, if you add Fixes SENTRY-TCQ in your commit message [docs](https://docs.sentry.io/product/integrations/source-code-mgmt/github/#resolve-via-commit-or-pull-request), sentry will automatically mark the issue as resolved for you. And as a convention, we try to append that as a footer in the commit message. See our develop docs [here](https://develop.sentry.dev/commit-messages/#commit-message-format).

Oh nice, I wasn't sure if SENTRY-TCQ was the issue ID. Updated the description 👍

**Pull request merged**
