### PR TITLE
feat(settings): styled copy text field

### PR DESCRIPTION
**Pull request by Chrissy**
for: https://github.com/getsentry/sentry/pull/6886

image

### CODE REVIEW

**Comment by getsentry-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by Chrissy** [comment]
@ckj 👋

**Review by ckj — APPROVED** [review]
LGTM 👍

**Comment by Chrissy** [comment]
Gonna merge through this despite the code coverage failure, because it is mostly related to css in js stuff. We should make sure code coverage can handle that kind of code in the future!

**Pull request merged**
