### PR TITLE
chore(python): don't autoformat migrations

### PR DESCRIPTION
**Pull request by MaxBittker**
it's arguably annoying and not helpful

### CODE REVIEW

**Comment by MaxBittker** [comment]
it's definitely annoying and arguably not helpful

**Review by dcramer — COMMENTED** [review]
Aren’t these exclusions defined somewhere else?

**Comment by MaxBittker** [comment]
are they? do you know where? didn't see anything

**Comment by dcramer** [comment]
i thought autopep8 read pep8's settings, which exclude south_migrations (setup.cfg), but could be wrong

**Comment by MaxBittker** [comment]
the commit hook always formats it for me, possibly the it passes the files in explicitly?

**Comment by markstory** [comment]
Is this something we're still interested in pursuing or can it be closed because it can no longer be merged?

**Comment by MaxBittker** [comment]
probably can be closed, if anything it should be an issue

**Pull request closed without merging**
