### PR TITLE
Inform user of SDK updates

### PR DESCRIPTION
**Pull request by dcramer**
@getsentry/ui

---

This change is [Reviewable](https://reviewable.io/reviews/getsentry/sentry/3826)

### CODE REVIEW

**Comment by dcramer** [comment]
screenshot 2016-07-27 16 59 41

**Comment by benvinegar** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/sentry/static/sentry/app/components/events/eventEntries.jsx, line 123 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/3826#-KNiAJMey6FM6RZXQ0tg:-KNiAJMey6FM6RZXQ0th:373865566) ([raw file](https://github.com/getsentry/sentry/blob/4a923f287037e8dd192274fd343a8196886c7466/src/sentry/static/sentry/app/components/events/eventEntries.jsx#L123)):*
> ```JSX
>             {evt.sdk.upstream.url &&
>               <a href={evt.sdk.upstream.url}
>                  style={{marginLeft: 10}}>{t('Learn More')}</a>
> ```

btw should this link to say, a releases page? (rather than just the sdk home)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3826)*

**Comment by dcramer** [comment]
Yeah we should build a releases page






On Wed, Jul 27, 2016 at 5:05 PM -0400, "Ben Vinegar" <notifications@github.com> wrote:












Reviewed 3 of 3 files at r1.

Review status: all files reviewed at latest revision, 1 unresolved discussion.





src/sentry/static/sentry/app/components/events/eventEntries.jsx, line 123 [r1] (raw file):


            {evt.sdk.upstream.url &&
              <a href={evt.sdk.upstream.url}
                 style={{marginLeft: 10}}>{t('Learn More')}</a>




btw should this link to say, a releases page? (rather than just the sdk home)





Comments from Reviewable

**Comment by mitsuhiko** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/getsentry/sentry/3826#-KNiD2f0m9zQJqjy1Xio:-KNiD2f1ZJb7WYzU_VUh:-1344505866) (no related file):*
btw I think it would be great if we could move the versions of the libraries directly into the docs.  That info there is valuable particularly for javascript since we most likely want to link to the most recent version automatically there and we already ingest that data into sentry server periodically.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3826)*

**Comment by dcramer** [comment]
We'll iterate on this once the SDK details endpoint lands in getsentry.com. We'll then build a cache in the local Sentry install (likely fed by the beacon checkin).

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3826#-:-KNmADLIUSIdEsygIfXo:-686142160)*

**Pull request merged**
