### PR TITLE
test(fix): Add the missing long type mapping to tests

### PR DESCRIPTION
**Pull request by BYK**
For some reason tests wouldn't run for me without this fix.

### CODE REVIEW

**Review by wedamija — COMMENTED** [review]
Just curious what actually fails here? Is it just that you're running tests on windows or something?

**Comment by EvanPurkhiser** [comment]
Looks like the linter is not happy.

**Comment by BYK** [comment]
>Just curious what actually fails here? Is it just that you're running tests on windows or something?

On WSL for some reason I get the following:
```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/www/sentry/local/lib/python2.7/site-packages/_pytest/main.py", line 103, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/www/sentry/local/lib/python2.7/site-packages/_pytest/config.py", line 914, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/www/sentry/local/lib/python2.7/site-packages/pluggy/__init__.py", line 628, in call_historic
INTERNALERROR>     res = self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/www/sentry/local/lib/python2.7/site-packages/pluggy/__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/www/sentry/local/lib/python2.7/site-packages/pluggy/__init__.py", line 216, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/www/sentry/local/lib/python2.7/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/www/sentry/local/lib/python2.7/site-packages/pluggy/callers.py", line 77, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "/www/sentry/local/lib/python2.7/site-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "C:\Users\byk\Documents\Projects\sentry\sentry\src\sentry\utils\pytest\sentry.py", line 163, in pytest_configure
INTERNALERROR>   File "src/sentry/runner/initializer.py", line 134, in bootstrap_options
INTERNALERROR>     load_defaults()
INTERNALERROR>   File "src/sentry/options/__init__.py", line 30, in load_defaults
INTERNALERROR>     from . import defaults  # NOQA
INTERNALERROR>   File "src/sentry/options/defaults.py", line 34, in <module>
INTERNALERROR>     register('system.maximum-file-size', default=2 ** 31, flags=FLAG_PRIORITIZE_DISK)
INTERNALERROR>   File "src/sentry/options/manager.py", line 221, in register
INTERNALERROR>     type = type_from_value(default_value)
INTERNALERROR>   File "src/sentry/utils/types.py", line 173, in type_from_value
INTERNALERROR>     return _type_mapping[type(value)]
INTERNALERROR> KeyError: <type 'long'>
```

Even weirder, the following reports `int`:
```
$ python -c 'print(type(2 ** 31))'
<type 'int'>
```

**Review by wedamija — APPROVED** [review]
Looks like `sys.maxint` on windows is `2147483647`, and `2 ** 31` is just above that, so it's converted over. Not sure why your other test fails though, maybe you're using python 3 there?

**Comment by BYK** [comment]
>Looks like sys.maxint on windows is 2147483647, and 2 ** 31 is just above that, so it's converted over.

Python in WSL reports a much larger number so I blame pytest for doing some weird stuff w/ selecting Python executables as I also got unexplainable import inconsistency issues.

>Not sure why your other test fails though, maybe you're using python 3 there?

Def not py3 also what other test failing? :D

**Comment by wedamija** [comment]
> > Looks like sys.maxint on windows is 2147483647, and 2 ** 31 is just above that, so it's converted over.
> 
> Python in WSL reports a much larger number so I blame pytest for doing some weird stuff w/ selecting Python executables as I also got unexplainable import inconsistency issues.
> 
> > Not sure why your other test fails though, maybe you're using python 3 there?
> 
> Def not py3 also what other test failing? :D

Sorry for not being clear, just referring to:

>Even weirder, the following reports int:
```
$ python -c 'print(type(2 ** 31))'
<type 'int'>
```

**Comment by BYK** [comment]
>Sorry for not being clear, just referring to:

Nah, py2 :(

**Pull request merged**
