### PR TITLE
fix(integrations) Make setup complete modal less empty

### PR DESCRIPTION
**Pull request by markstory**
Make the document displayed at setup complete a valid HTML document, and display a small bit of text so that if the window doesn't auto close the user knows they can close the page.

Fixes APP-598

### CODE REVIEW

**Review by lauryndbrown — COMMENTED** [review]
@markstory technically, I don't see anything wrong here. But it does bother me that we do it like this. Would you mind creating a screenshot of the dialogue response? It doesn't appear to use the general sentry template... Which might be splitting hairs, but I feel like it should.

Is there a small test that can be written here or is it already covered by existing tests?

**Comment by markstory** [comment]
The new text is unstyled but I think its an improvement over the entirely white page that currently exists.

screen shot 2018-10-22 at 5 01 13 pm

There are existing tests for successful pipeline completion, but they make no assertions on the visual appearance of the page's contents.

**Review by lauryndbrown — APPROVED** [review]
This is not a requirement as the code definitely is an improvement over what it was. In the past, when I have user-facing windows, I used the django templates so everything has the same look and feel. For example: https://github.com/getsentry/sentry/blob/master/src/sentry/templates/sentry/integrations/vsts-config.html

But it's definitely more me just being nit picky. I don't believe anyone is very concerned about this particular page.

**Comment by markstory** [comment]
@lauryndbrown I can do another pull request that applies the standard small modal design to this window.

**Pull request merged**
