### PR TITLE
fix(api): Bring back docs for monitor checkins / lists

### PR DESCRIPTION
**Pull request by evanpurkhiser**
Lost them here https://github.com/getsentry/sentry/pull/45672

### CODE REVIEW

**Review by JoshFerge — APPROVED** [review]
mind adding why they were lost, a TODO, and optionally put the value in a separate file and "$ref" it from this one?

**Comment by evanpurkhiser** [comment]
Am I able to add comments to the JSON?

**Comment by evanpurkhiser** [comment]
I can move to a separate file, that's a good idea.

I wasn't sure if the files were generated and would be overwritten in some way.

**Comment by evanpurkhiser** [comment]
Ah yeah, sounds good

**Comment by evanpurkhiser** [comment]
I've refactored this PR to instead of hardcoding the json just explicitly define the endpoints for DRF spectacular

**Review by JoshFerge — APPROVED** [review]

**Pull request merged**
