### PR TITLE
feat(api): Create audit log entry to track teams created through new flow

### PR DESCRIPTION
**Pull request by schew2381**

### CODE REVIEW

**Review by cathteng — APPROVED** [review]
do you want to specify the user that you updated to team admin?

**Comment by schew2381** [comment]
> do you want to specify the user that you updated to team admin?

I think so b/c if we only say that we created a new team, the user might not realize they have ownership of it and can edit/configure it

**Comment by cathteng** [comment]
oh i meant actually put the email of the user that has now become team admin. but i guess you can see from who created the audit log entry

**Comment by schew2381** [comment]
> oh i meant actually put the email of the user that has now become team admin. but i guess you can see from who created the audit log entry

oh ok that makes sense, my bad for misunderstanding lol

**Pull request merged**
