### PR TITLE
ref(event_search): Splitting up api/event_search.py

### PR DESCRIPTION
**Pull request by wmak**
`api/event_search.py` has been growing more and more as we add more logic for discover/issues. This splits the file up so that the field and filter parsing is split out into their own files. This should also help make typing these files easier, and I'll be testing these changes on staging first.

- This PR is huge +5000/-4900 but there's little to no change to any logic
- 025d10b: This is the commit where `api/event_search.py` was split
  - I considered functions.py for function specific logic as well, but functions depend too much on fields to do this without making the imports really convoluted
  - `InvalidSearchQuery` moved to `sentry.exceptions` since it was used everywhere and didn't really belong in any one of these files
  - The only logic change [here](https://github.com/getsentry/sentry/blob/025d10b3c5f729f5b3074e158d59c573bd246930/src/sentry/search/events/filter.py#L620) was because the group_id test was failing because the group id order was different. Was likely a flake that changing test order broke.
- ac6b504: This is where the tests were split
- d2f0d78: Updating imports everywhere

### CODE REVIEW

**Comment by dashed** [comment]
lol

**Review by wedamija — APPROVED** [review]
I think this generally makes sense and is an improvement.  We probably need to break `fields.py` up even further, since it's still massive at 1.5k lines, but probably something to tackle separately. Worth having someone else from discover have a look as well since I'm a bit more focused just on things related to issue search

**Comment by JTCunning** [comment]
lol

**Review by evanh — APPROVED** [review]
I am blown away by how big event search was. Crazy.

**Review by Zylphrex — APPROVED** [review]
Nice! 💯

**Review by shruthilayaj — APPROVED** [review]

**Pull request merged**
