### PR TITLE
Link breadcrumbs which reference an internal Sentry event

### PR DESCRIPTION
**Pull request by dcramer**
/cc @getsentry/ui

---

This change is [Reviewable](https://reviewable.io/reviews/getsentry/sentry/3910)

### CODE REVIEW

**Comment by dcramer** [comment]
This is not done, it needs:

- To figure out UI for the link
- Pass in org/project ID so the link can actually generate

screenshot 2016-08-10 17 59 01

**Comment by ckj** [comment]
Could we have a :octocat: style 'References <short id>' to the end of the crumb body? Maybe even change the error icon to the sentry logo when we have more details somewhere else?

**Comment by dcramer** [comment]
@ckj I think it should always be visible, as I might want to click through. Kind of silly to collapse/expand just for this. One thought I had was we show like an [Open] icon thats right-aligned on the first line.

Another thought, is we could totally change rendering for breadcrumb entries which reference a Sentry event

**Comment by ckj** [comment]
> Another thought, is we could totally change rendering for breadcrumb entries which reference a Sentry event
 
We could also maybe do an Issue card on hover cc @mattrobenolt

**Comment by mattrobenolt** [comment]
Always +1 to hover cards.

**Comment by benvinegar** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/sentry/static/sentry/app/components/events/interfaces/breadcrumbs/defaultRenderer.jsx, line 31 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/3910#-KPQ4W5PP4_WzKZEK85C:-KPQ4W5PP4_WzKZEK85D:b-vzhze9) ([raw file](https://github.com/getsentry/sentry/blob/cc2f275757218f6aa9b70729e6fd004b3ca9ce4f/src/sentry/static/sentry/app/components/events/interfaces/breadcrumbs/defaultRenderer.jsx#L31)):*
> ```JSX
>         {crumb.message && <pre><code>{crumb.message}</code></pre>}
>         {crumb.event &&
>           <Link to="" className="btn btn-sm">Jump To</Link>
> ```

Can we just use the standard "external link" icon here? Taking up an entire line for this seems pretty rough – it's not uncommon to see a *lot* of earlier errors in breadcrumbs (was just looking at one today that had ~10). That would be 10 extra lines of whitespace just to add a redundant "Jump to" link.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3910)*

**Pull request closed without merging**
