### PR TITLE
chore(ts): Update webpack to include babel-loader in tandem with ts-loader

### PR DESCRIPTION
**Pull request by dashed**
This alleviates this error occurring at runtime:

```
Error: Component selectors can only be used in conjunction with babel-plugin-emotion.
```

## TODO

- [x] add tsconfig config changes for `getsentry/getsentry` - https://github.com/getsentry/getsentry/pull/3097

-------

Some hints from https://github.com/emotion-js/emotion/issues/535

### CODE REVIEW

**Review by lynnagara — APPROVED** [review]
I like this. I wonder if there is any impact on compilation time.

**Comment by dashed** [comment]
Unsure. I got it from https://github.com/Microsoft/TypeScriptSamples/tree/master/react-flux-babel-karma

**Comment by lynnagara** [comment]
Will we need this in getsentry too?

**Comment by dashed** [comment]
Yea we'll probably need it in getsentry as well.

**Comment by dashed** [comment]
I've updated this PR with this change `module: "esnext"`.

References:
- https://github.com/Microsoft/TypeScript/issues/16820
- https://devblogs.microsoft.com/typescript/announcing-typescript-2-4/
- https://github.com/Microsoft/TypeScript/issues/14495

/cc @billyvg

**Review by billyvg — APPROVED** [review]

**Comment by dashed** [comment]
I'll open a PR for a similar webpack change for `getsentry/getsentry` later today.

**Pull request merged**
