### PR TITLE
Make Remove/Leave buttons consistent size

### PR DESCRIPTION
**Pull request by mattrobenolt**
- [ ] Need new icon for "leave". Probably like, a dood exiting a door or something. @ckj 

image

### CODE REVIEW

**Comment by benvinegar** [comment]
I don't like the trash icon without "leave". It suggests you can just straight-up delete it from here?

**Comment by mattrobenolt** [comment]
> I don't like the trash icon without "leave".

That's why there's a TODO checkbox thing waiting for an icon. :)

**Comment by benvinegar** [comment]
> That's why there's a TODO checkbox thing waiting for an icon. :)

Oh. I usually expect some kind of "WIP" label – didn't see it.

**Comment by EvanPurkhiser** [comment]
They have their own icons now:

image

Still want to do this? @ckj ?

image

**Comment by ckj** [comment]
I'm gonna be working on this section of the app in a different PR and can address it there if needed. Feel free to close.

**Comment by EvanPurkhiser** [comment]
It definitely looks a little nicer :-)

**Pull request closed without merging**
