### PR TITLE
Revert "fix(migrations): Fix NotificationSettings (#24762)"

### PR DESCRIPTION
**Pull request by lynnagara**
This reverts commit a9c4508eba67164ea01eeb0959b1ebb0458080c1.

### CODE REVIEW

**Review by wedamija — APPROVED** [review]

**Review by dashed — APPROVED** [review]

**Comment by billyvg** [comment]
Force merging this as this reverts a change that is blocking our builds.

**Comment by BYK** [comment]
@billyvg this broke self-hosted builds

**Comment by BYK** [comment]
@wedamija @lynnagara @billyvg this is the error we are getting:
```
django.core.management.base.CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0183_copy_useroptions_to_notificationsettings_2, 0183_make_codemapping_unique_on_projectcodeowners in sentry).
```

Need to get this fixed ASAP as it halted all self-hosted builds (and will cause all follwing PRs to be blocked on these builds) and also blocks any self-hosted work.

**Pull request merged**
