### PR TITLE
fix: Only render dsn if it's a valid dsn

### LINKED ISSUE #11105: Setup flow appears to be broken after upgrade to @sentry/Brower^4.0
## Important Details

This is in development in OSX Mojave

## Description

I regularly reset the database to load in new mocks. As of last night moving into today, I cannot proceed with the typical Sentry startup flow because of this js error:

image

I can move forward with the setup flow if I revert to the commit on `package.json` that immediately precedes this commit: https://github.com/getsentry/sentry/commit/5f0f87daf05cb3721a536153813a7322368324af#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

Once I am through the setup flow, I can return to latest master and everything runs fine.

This could be because of that specific commit, or it could be an unrelated benefit of returning to an old state in the repo. Either way, my only real hunch is that this bug involves the upgrade to `@sentry/browser^4` and probably @HazAT should be aware of this report.

UPDATE: I got a little less lazy and can now verify with 90% certainty that the above commit is the right one. I was able to reproduce the bug on that commit, and then successfully complete the initialization process on the commit that immediately precedes it in `master` history. I had to run `yarn cache clean` at one point when going backwards I think.

## Steps to Reproduce

1. Update to latest master and run `yarn`
2. Run `make reset-db`
3. Boot up server and try to set up Sentry

### What you expected to happen

I progress through the typical Sentry admin initialization flow (password, root url, email, etc.)

### Possible Solution

🤷‍♀️

### LINKED ISSUE #11337: Invalid Dsn in the browser console
After I update to the latest 9.10dev today。i got an "Invalid Dsn" erro in my browser console. And I found the dsn in the page is "://6f75457663974cac83a90f672e78bde2@/1", it is no valid to the regexp test. so I try to drop the database and create new to run migrate. but the error is still appear. and after i  login. the page is loading, I can't see anything.

### PR DESCRIPTION
**Pull request by HazAT**
Tested it in a clean Sentry setup + also added test for template tag `{% load sentry_dsn %}{% public_dsn %}`.

Fixes https://github.com/getsentry/sentry/issues/11105
Fixes https://github.com/getsentry/sentry/issues/11337

### CODE REVIEW

**Review by untitaker — APPROVED** [review]
LGTM for its purpose, but couldn't we fall back to a default scheme in `ProjectKey.get_dsn` instead? Or do the check there? We wouldn't need to have this regex around

**Comment by untitaker** [comment]
Actually I would prefer it strongly if we had the check here: https://github.com/getsentry/sentry/blob/1b695114fbdaa1f5dfc1f5cec4863ea12821fc80/src/sentry/models/projectkey.py#L156

```python
if not urlparts.netloc or not urlparts.scheme or not ...:
    return ""
```

**Comment by HazAT** [comment]
@untitaker Was thinking the same, but it's not just about `scheme` we also derive `hostname` from the `system.url-prefix` / `settings.SENTRY_PUBLIC_ENDPOINT or settings.SENTRY_ENDPOINT`.

So we end up with stuff like: `://53039209a22b4ec1bcc296a3c9fdecd1@/4291`

Also, I am afraid of touching this part ^^

**Comment by untitaker** [comment]
yes, so I would check `urlparts.netloc` as well. I think this is easier to test than a templatetag too..

**Review by jan-auer — APPROVED** [review]
LGTM

**Review by dcramer — APPROVED** [review]

**Review by untitaker — APPROVED** [review]

**Pull request merged**
