### PR TITLE
chore(js): Update javascript sdk to 6.10.0-beta.2

### PR DESCRIPTION
**Pull request by dashed**
https://github.com/getsentry/sentry-javascript/pull/3817

### CODE REVIEW

**Review by AbhiPrasad — CHANGES_REQUESTED** [review]
We need to run `yarn` to update `yarn.lock`

**Comment by AbhiPrasad** [comment]
Changelog: https://github.com/getsentry/sentry-javascript/compare/6.9.0...refs/heads/release/6.10.0-beta.2

**Comment by dashed** [comment]
@AbhiPrasad Forgot to update `yarn.lock` :(

**Review by AbhiPrasad — APPROVED** [review]
🚀

**Pull request merged**
