### PR TITLE
ref(native): Use debug identifiers instead of UUIDs for DSymFiles

### PR DESCRIPTION
**Pull request by jan-auer**
This migrates debug information files (dsym files) from UUIDs to debug identifiers, called `DebugId`. It is a computed *32-byte* identifier with a guaranteed stable but irreversible (i.e. lossy) conversion from Mach-O, ELF, PDB and Breakpad symbols and all future supported formats. It always starts with a UUID, followed by a variable number of additional components, e.g.:

```
3249d99d-0c40-4931-8610-f4e4fb0b6936-1
^-------------- uuid --------------^ ^-- optional components...
```

The change is required for Windows symbols (PDBs). Their identifiers consist of a UUID + 4-byte age, which do not fit in the current UUID. Also, the UUIDs returned by Breakpad for Linux symbols are not valid UUIDs.

### Migration

The database column `sentry_projectdsymfile.uuid` has been altered to `VARCHAR(64)`. This will allow to extend the type and add more components in the future.

### Symbolication

Changes for parsing the new identifiers as well as object lookup have been implemented in https://github.com/getsentry/symbolic/pull/58, as well as a couple follow-up PRs. Released with `symbolic#3.0.1`.

The model field `ProjectDSymFile.uuid` has been renamed to `ProjectDSymFile.debug_id` and only contains **Strings** going forward. Subsequently, all occurrences have been renamed to `debug_id` and consistently use strings now.

The `SymCache` binary format has been updated to version 2 to use debug identifiers instead of UUIDs in its header. **NOTE Ops: This will require a symcache update for all symbolications where SymCache v1 have been generated.** A test for this has been added.

The key `image_uuid` in ProcessingIssues has not been changed.

### API

The serializer for dsyms now includes an additional `debugId` field with the full debug identifier. The old `uuid` field is still present and only contains the UUID-portion for backwards compatibility. Example:

```json
{
    "uuid": "dfb8e43a-f242-3d73-a453-aeb6a777ef75",
    "debugId": "dfb8e43a-f242-3d73-a453-aeb6a777ef75-feedface",
    "cpuName": "x86_64",
    "objectName": "baz.dSYM",
    "symbolType": "macho",
    "size": 42,
    "sha1": "dc1e3f3e411979d336c3057cce64294f3420f93a",
    "headers": {"Content-Type": "application/x-mach-binary"},
}
```

Also, the Store endpoint will now accept `"id"` in `debug_meta.images` in a new image type `"symbolic"`. The minidump endpoint has been updated to generate such images instead of `"apple"`.

```json
"debug_meta": {
    "images": [
        {
            "id": "3249d99d-0c40-4931-8610-f4e4fb0b6936-1",
            "image_addr": "0x2a0000",
            "image_size": "0x9000",
            "name": "C:\\projects\\breakpad-tools\\windows\\Release\\crash.exe",
            "type": "symbolic"
        }
    ]
},
```

### CLI

Changes in the CLI have been implemented in https://github.com/getsentry/sentry-cli/pull/276. Since all UUIDs are also valid debug identifiers, all commands work as before and there is no breaking change. 

Old CLI will continue to work since legacy UUIDs are still being emitted and accepted in the API (see above).

### User Interface

The user interface mostly checks for `image.id || image.uuid` now. Also, a couple of table headers have been updated. The most notable change is in the event issues box, where the keys (`image_uuid`, `image_path` and `image_name`) are now mapped manually to provide better names to the user:

screen shot 2018-03-27 at 10 40 22

screen shot 2018-03-27 at 11 52 17

screen shot 2018-03-27 at 10 26 06

screen shot 2018-03-28 at 13 13 25

### CODE REVIEW

**Comment by mitsuhiko** [comment]
How much work would it be to also add a `native` type to the image section and use that for minidumps? It can just be an alias for `apple` or we already implement it like we discussed earlier (no cpu_type/cpu_subtype and throw away the uuid). It seems like now would be the time to do that.

Still reviewing the rest.

**Comment by mitsuhiko** [comment]
Also note for later: I think the UI should probably gain a component eventually that displays the debug ID in a format that makes sense for the platform (eg: splits the age off for windows for instance)

**Comment by jan-auer** [comment]
@mitsuhiko I agree that we should definitely do that. However, I'd propose we do that in a separate PR. Since the PR is already quite large, we should stick to just changing debug identifiers for now. 

Same goes for the `image_*` fields, especially `image_uuid`. They should all be changed, which propagates all the way into the UI.

**Comment by mitsuhiko** [comment]
I just don’t want to support non uuid inputs for the apple debug image value. I do not want to support that in the relay for instance.

**Comment by jan-auer** [comment]
@mitsuhiko In that case we should probably consider making more specific image types:

- `macho` alias `apple`: only accepts UUIDs
- `elf`: For now only accepts UUIDs
- `pdb`: Accepts UUID + age

Rendering could look like this for PDB ids:

screen shot 2018-03-27 at 12 40 32

Just note that right now we do not store the information which type of image we're dealing with (especially not in the minidump case, simply because we don't have it). So we'd somehow have to "guess" which kind of image (and ID) it is...

**Comment by jan-auer** [comment]
@mattrobenolt completely forgot that MySQL doesn't like indices on `TEXT` columns, so I think we'll have to stick with `CharField(max_length=64)`

**Comment by JTCunning** [comment]
Thanks for the heads up, Jan. Going to remove myself as a reviewer since this is in all of you smart peoples' hands now.

**Comment by jan-auer** [comment]
@mitsuhiko `symbolic` image type is now complete.

**Review by mitsuhiko — APPROVED** [review]

**Comment by jan-auer** [comment]
Erm, not sure what to do with all these Percy diffs - they seem to be unrelated to this changeset (maybe landed in master without review?)

**Review by mattrobenolt — APPROVED** [review]
This is a lot of code and I have almost no context, but nothing stands out as horribly wrong, and the migration should be fine.

Just make sure the migration ids don't conflict, etc.

**Pull request merged**
