### PR TITLE
feat(react): Upgrade to react 16 [WIP] 

### LINKED ISSUE #6495: Get onto React 16
Upgrade sentry to React 16.

- [x] Move all components from DropdownLink to DropdownReact
- [x] move to react-dom standalone
- [ ]  create-react-class standalone + class codemod
- [ ] upgrade jest + enzyme 
- [ ] upgrade eslint
- [ ] upgrade or patch react router 2.8.1 (it relies on react internal proptypes)
- [ ] ???

### PR DESCRIPTION
**Pull request by billyvg**
Some tests are broken/require snapshot updates.

Depends on #6500

Closes #6495

### CODE REVIEW

**Comment by MaxBittker** [comment]
Here's at least one more place that hasownproperty is causing problems:
/Users/maxbittker/workspace/sentry/src/sentry/static/sentry/app/components/group/releaseStats.jsx

**Comment by MaxBittker** [comment]
this prevented me from loading issue details pages locally

**Review by MaxBittker — CHANGES_REQUESTED** [review]
based on previous comments

**Comment by billyvg** [comment]
Closing in favor of #6984

**Pull request closed without merging**
