### PR TITLE
feat: Add flag to run under debuggable wsgi server

### PR DESCRIPTION
**Pull request by untitaker**
Run with `sentry run web --no-uwsgi`

### CODE REVIEW

**Review by bruno-garcia — APPROVED** [review]

**Comment by untitaker** [comment]
can somebody check if this actually adds any value? Unsure if wsgiref can actually be inspected by pycharm etc

**Review by bruno-garcia — CHANGES_REQUESTED** [review]
Seems like your debug message isnt' working:
image

**Review by bruno-garcia — CHANGES_REQUESTED** [review]

**Review by bruno-garcia — APPROVED** [review]

**Comment by mitsuhiko** [comment]
Context to this for observers is that this makes attaching a debugger work.

**Comment by bruno-garcia** [comment]
image
^ Like this! Life is good!

**Pull request merged**
