### PR TITLE
Decode quoted-printable email message payload

### PR DESCRIPTION
**Pull request by arachnopavel**

### CODE REVIEW

**Comment by markstory** [comment]
What problem does this solve?

**Comment by arachnopavel** [comment]
It makes comments containing 8-bit characters that Sentry extracts from QP-encoded incoming messages actually readable. Without this change, Sentry displays QP-encoded non-ASCII text in comments like this:
> =D1=82=D0=B5=D1=81=D1=82

And with this change:
> тест

**Comment by markstory** [comment]
Would the scenario that comes up in be someone creating a comment using bytes that would require QP-encoding when in an email?

Without tests or any description on the issue I'm having a hard time understanding the scenario this would help with.

**Comment by arachnopavel** [comment]
The scenario is pretty simple. Someone sends an email in reply to one of the issue notification emails sent by Sentry, to create a comment to that issue. The comment text happens to be in a language that uses non-latin symbols and, being encoded in UTF-8, contains 8-bit characters. Email provider's mail submission agent receives the comment email, sees the plain text with 8-bit chars and encodes it in QP before relaying further. Then Sentry receives the QP-encoded email, extracts its payload and creates a comment with it. Then, without this patch, the text of the created comment (not the email) will be displayed in user's web browser in QP-encoded form, just like this:
> =D1=82=D0=B5=D1=81=D1=82

And with this patch, the comment would contain originall human-readable text.

**Pull request closed without merging**
