### PR TITLE
chore(replay): Frontend timeline gap feature flag

### PR DESCRIPTION
**Pull request by c298lee**
Backend ff: https://github.com/getsentry/sentry/pull/74140

### CODE REVIEW

**Review by michellewzhang — APPROVED** [review]
not related to the ff but could we make the ReplayTimelineEvents component name more specific if it's just showing the gaps?

**Comment by c298lee** [comment]
> not related to the ff but could we make the ReplayTimelineEvents component name more specific if it's just showing the gaps?

omg I put the flag in the wrong spot let me fix it

**Review by michellewzhang — CHANGES_REQUESTED** [review]
wait nvm i think you did the ff check on the wrong component! should be on the gaps component up above

**Review by michellewzhang — APPROVED** [review]
WOO

**Pull request merged**
