### PR TITLE
link to github commit page from activity feed

### PR DESCRIPTION
**Pull request by macqueen**
looks like this:
screenshot 2017-04-24 15 25 57

and this:
screenshot 2017-04-24 15 27 32

cc @benvinegar

### CODE REVIEW

**Comment by benvinegar** [comment]
Seems like we need a slightly more space-constrained version of this button.

**Comment by macqueen** [comment]
@benvinegar do you mean you just want it to be a basic link? or literally this with less padding?

**Comment by benvinegar** [comment]
>  or literally this with less padding?

I'd leave that up to @ckj, but my feeling is that we shouldn't use the same button for inline text as we use elsewhere in tables, lists, etc.

**Comment by ckj** [comment]
@macqueen I agree with @benvinegar. I'd prefer it to be a basic link (same font color, just without the button chrome) in instances where we show these inline.

**Comment by macqueen** [comment]
ok, looks like:
screenshot 2017-04-25 17 38 13
and on hover:
screenshot 2017-04-25 17 38 22

**Review by ckj — APPROVED** [review]
Design-wise, I'm 👍 !

**Pull request merged**
