### PR TITLE
fix(workflow): Fix wrapping for actions with lots of inputs

### PR DESCRIPTION
**Pull request by billyvg**
This fixes wrapping for actions with lots of input
image

Fixes https://app.asana.com/0/1143846759074121/1159532264737075

### CODE REVIEW

**Comment by priscilawebdev** [comment]
I like the PR. Short and direct :)

Unfortunately, percy is just showing an error message on the right, but I believe your screenshot is from the screen already fixed.

Just a minor thing: wouldn't it be better to also align the trash icons with the drop-down components?

**Review by priscilawebdev — COMMENTED** [review]
I like the PR. Short and clear :)

Unfortunately, percy is just showing an error message on the right, but I believe your screenshot is from the screen already fixed.

Just a minor thing: wouldn't it be better to also align the trash icons with the drop-down components?

**Comment by billyvg** [comment]
@priscilawebdev updated to make the delete button a fixed height to match the inputs, thanks!

**Review by dashed — APPROVED** [review]
Looks good to me 👍

**Review by priscilawebdev — APPROVED** [review]
@billyvg Thank you :)

**Pull request merged**
