### PR TITLE
feat: add replays org flag to EXPOSABLE_FEATURES

### PR DESCRIPTION
**Pull request by JoshFerge**
add the replays feature flag to EXPOSABLE_FEATURES so relay can know about it.

### CODE REVIEW

**Comment by flub** [comment]
Is there any pointer as to why relay would like to know about this?

**Review by jjbayer — APPROVED** [review]
I assume this is used to conditionally enable processing of replays in Relay? https://github.com/getsentry/relay/blob/2f1f9dbbcaa59670d32f0833a0a983455031a0f6/relay-server/src/actors/project.rs#L57-L59
Maybe we could link the PRs.

**Review by untitaker — APPROVED** [review]
talked to josh yesterday, this is fine

**Comment by flub** [comment]
> talked to josh yesterday, this is fine

Not disagreeing, I like commit messages which explain how things work and say why things are the way they are though.  Instead of repeating what the code already says.

**Comment by JoshFerge** [comment]
@flub understandable, thanks for pointing out the ambiguity. Didn't think too hard to add details since @untitaker and i talked about but want to make sure everyone is in the loop. The related PRs are here:
https://github.com/getsentry/ops/pull/4813
https://github.com/getsentry/relay/pull/1239

This variable allows this org setting to propagate to the project config so that relay can pick it up and enforce it in ingestion, in relation to the new session replay data ingestion.

**Comment by untitaker** [comment]
sorry @flub I was being lazy here

**Pull request merged**
