### PR TITLE
fix: Replace nonfunctional `start_transaction` with new child span

### PR DESCRIPTION
**Pull request by szokeasaurusrex**
This `start_transaction` call within the `download` function has no function because it is never entered (Transactions are context managers, and so they either have to be started using a `with` statement or manually by calling `Transaction.__enter__` and `Transaction.__exit__`).

Additionally, starting a new transaction at this location would lead to undefined behavior because this `download` method is already auto-instrumented with a transaction since it is called within the `get` request handler, which the Django integration auto-instruments. You can view the auto-instrumented transaction [here](https://sentry.sentry.io/performance/?isDefaultQuery=false&metricSearchSetting=metricsOnly&project=1&query=transaction%3A%22%2Fapi%2F0%2Fprojects%2F%7Borganization_slug%7D%2F%7Bproject_slug%7D%2Freplays%2F%7Breplay_id%7D%2Frecording-segments%2F%7Bsegment_id%7D%2F%22&statsPeriod=14d).

Since this `start_transaction` currently does nothing useful, and since starting a transaction here would be inappropriate, I have replaced the `start_transaction` call with a call to start a child span.

ref: #63590

### CODE REVIEW

**Comment by JoshFerge** [comment]
> Additionally, starting a new transaction at this location would lead to undefined behavior because this download method is already auto-instrumented with a transaction since it is called within the get request handler, which the Django integration auto-instruments. You can view the auto-instrumented transaction [here](https://sentry.sentry.io/performance/?isDefaultQuery=false&metricSearchSetting=metricsOnly&project=1&query=transaction%3A%22%2Fapi%2F0%2Fprojects%2F%7Borganization_slug%7D%2F%7Bproject_slug%7D%2Freplays%2F%7Breplay_id%7D%2Frecording-segments%2F%7Bsegment_id%7D%2F%22&statsPeriod=14d).


There are actually problems with this as we observed that the django instrumentation ends the transaction once the request finishies, while we need to instrument the full streaming of the response, so thats why we were starting a new transaction. Will the change still have it so we get instrumentation of this function?

**Comment by szokeasaurusrex** [comment]
> There are actually problems with this as we observed that the django instrumentation ends the transaction once the request finishies, while we need to instrument the full streaming of the response, so thats why we were starting a new transaction. Will the change still have it so we get instrumentation of this function?

First of all, this transaction is never getting sent to Sentry in the first place, because `transaction.finish` is not being called (you can see that a [search for the transaction](https://sentry.sentry.io/performance/?isDefaultQuery=false&metricSearchSetting=metricsOnly&project=1&query=ProjectReplayRecordingSegmentDetailsEndpoint.download_segment&statsPeriod=14d) in Sentry yields no results).

Second, even if you were to correct this problem by adding a `transaction.finish` call, starting a transaction within a running transaction has undefined behavior, and we should not be doing it because it could have unexpected results, such as messing up the transaction data. The solution to get the transaction to be able to fully capture all of the streaming response is by adding support for this use case in the SDK. I will open an issue to look into this, and link it on the issue.

**Comment by szokeasaurusrex** [comment]
@JoshFerge https://github.com/getsentry/sentry-python/issues/2736

**Review by sl0thentr0py — APPROVED** [review]
lgtm, maybe wait for @JoshFerge's stamp before merging

**Comment by JoshFerge** [comment]
hmm well this certainly worked at some point, my viral tweet thread is based on it: https://x.com/JoshFerge/status/1649126756065107968?s=20

but sure, feel free to remove it

**Review by JoshFerge — APPROVED** [review]

**Comment by szokeasaurusrex** [comment]
> First of all, this transaction is never getting sent to Sentry in the first place, because `transaction.finish` is not being called (you can see that a [search for the transaction](https://sentry.sentry.io/performance/?isDefaultQuery=false&metricSearchSetting=metricsOnly&project=1&query=ProjectReplayRecordingSegmentDetailsEndpoint.download_segment&statsPeriod=14d) in Sentry yields no results).

@JoshFerge my previous comment, copied above, refers to the `"ProjectReplayRecordingSegmentDetailsEndpoint.download_segment"` transaction started in `src/sentry/replays/endpoints/project_replay_recording_segment_details.py`, which when I posted the comment, was the only transaction that this PR removed. That comment is still correct; your Tweet is about a different but similarly named transaction `"ProjectReplayRecordingSegmentindexEndpoint.download_segments"`, which was being sent to Sentry unlike the `"ProjectReplayRecordingSegmentDetailsEndpoint.download_segment"` transaction.

Since I posted the original comment, I had a discussion with @sl0thentr0py where we decided that we should also delete the `"ProjectReplayRecordingSegmentindexEndpoint.download_segments"` transaction and replace it with a span as a part of this PR, since it is also being started from within an auto-instrumented transaction. While I understand that this transaction may have appeared to work for you in the past, the behavior of starting a transaction within a transaction is and always has been undefined and should be avoided. There is no guarantee any data produced in this transaction is accurate, and we also know that starting a transaction within a transaction tends to mess up the data in the parent transaction and mess up trace data.

**Pull request merged**
