### PR TITLE
ref(docker): Move entrypoint out of $SENTRY_CONF

### PR DESCRIPTION
**Pull request by filesnate**
- docker-entrypoint.sh file is not a configuration file, so by moving
  it out, we can mount a volume onto $SENTRY_CONF containing the custom
  configuration files.

### CODE REVIEW

**Comment by markstory** [comment]
cc @BYK

**Comment by BYK** [comment]
The reason for this was to reduce the `COPY` instructions, and the total layer count. I'll see if I can find a way to bundle this file in another existing `COPY` first as I want to be able to do the mounting too.

**Review by BYK — APPROVED** [review]
I guess there's no way around this for now. Thanks a lot for the patch!

**Comment by filesnate** [comment]
Thank you

**Pull request merged**
