### PR TITLE
fix(jira): adds content security policy

### PR DESCRIPTION
**Pull request by scefali**
The header `X-Frame-Options` with the `ALLOW_FROM` block [has been deprecated in supporting browsers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options) in favor of the `Content-Security-Policy` header with the `frame-ancestors` block. A recent getsentry PR (https://github.com/getsentry/getsentry/pull/4460) allows us to specify a block in the `Content-Security-Policy` header without it getting wiped out by getsentry.

### CODE REVIEW

**Review by mattrobenolt — CHANGES_REQUESTED** [review]
Umm, this might not actually work in getsentry fwiw, and this might break stuff by reversing the policy that getsentry applies.

Wanna just eyeball that and double check? No matter what, this behavior won't be desirable. One is going to override the other. Nothing is going to merge for sure.

**Comment by scefali** [comment]
@mattrobenolt We have a decorator `allow_sameorigin_iframe` but that's not used here. Totally agree that specifying conflicting headers is not good. Do you think it makes sense to update `SecurityHeadersMiddleware` so that we don't set the `X-Frame-Options` header if we set the `Content-Security-Policy` header?

**Comment by mattrobenolt** [comment]
I'm not sure what that does, but I'm referring to the conflict here:

https://github.com/getsentry/getsentry/blob/master/getsentry/middleware/csp.py#L7-L20

getsentry does it's own management and setting the header, which is just going to clobber this one.

**Comment by scefali** [comment]
@mattrobenolt I see what you mean now, thanks

**Review by mattrobenolt — APPROVED** [review]
I'd just also clarify with a comment here that this will get merged with the CSP header being applied by getsentry.

**Comment by mattrobenolt** [comment]
Good clarification with a comment.

**Pull request merged**
