### PR TITLE
feat(loader): Add `JS_SDK_DYNAMIC_LOADER_SDK_VERSION` to config

### PR DESCRIPTION
**Pull request by AbhiPrasad**
Add `JS_SDK_DYNAMIC_LOADER_SDK_VERSION`, which matches the `JS_SDK_LOADER_SDK_VERSION` set. This will be used to set the `Surrogate-Key` for fastly caches (meaning we can on demand purge the cache for the dynamic sdk loader template)

ref https://github.com/getsentry/sentry/issues/44225

### CODE REVIEW

**Comment by lforst** [comment]
Just a thought so we don't forget: I think we need to set a default for this in getsentry.

**Comment by AbhiPrasad** [comment]
> Just a thought so we don't forget: I think we need to set a default for this in getsentry.

Will add a task to track this!

**Comment by AbhiPrasad** [comment]
> I think we need to deploy that change before this pr though right?

We shouldn't need to as the `getsentry` config inherits from the `sentry` one: https://github.com/getsentry/getsentry/blob/037708cf4d5d39a68eb74c1a44edefa978155f1c/getsentry/conf/settings/defaults.py#L12

**Comment by lforst** [comment]
> > I think we need to deploy that change before this pr though right?
> 
> We shouldn't need to as the `getsentry` config inherits from the `sentry` one: [getsentry/getsentry@`037708c`/getsentry/conf/settings/defaults.py#L12](https://github.com/getsentry/getsentry/blob/037708cf4d5d39a68eb74c1a44edefa978155f1c/getsentry/conf/settings/defaults.py#L12)

Will `""` as a default break anything?

**Comment by AbhiPrasad** [comment]
> Will "" as a default break anything?

It shouldn't! We don't use it anywhere atm.

**Review by lforst — APPROVED** [review]

**Pull request merged**
