### PR TITLE
fix(ui): resolve scoping issue with dropdownButton in production css

### PR DESCRIPTION
**Pull request by Chrissy**
image

image

fwiw I did some serious due diligence trying to fix this the *right* way (converting `Button` to styled components). I've noticed this has been causing problems in several other places as well, and it will likely continue to create bugs because production css is in a different order than development css.

Moving forward, I'm gonna try to be on my toes about css compilation order and it's ability to cause annoying regressions in any feature that mixes styled components with global classes.

Anyways, here is the cheap fix for now don't judge me!

### CODE REVIEW

**Review by ckj — APPROVED** [review]
👍

**Comment by billyvg** [comment]
btw I have a PR that converts Button into a styled component (it's waiting for emotion upgrade):

https://github.com/getsentry/sentry/pull/7772

**Comment by Chrissy** [comment]
@billy that is pretty funny. I wrote a *very* similar component before i wrote this, but got hung up on the test/theme issues and the element switching. Glad you were able to get something working!

**Comment by Chrissy** [comment]
also when is it gonna be out you think?

**Comment by Chrissy** [comment]
i see it is still WIP so i'm gonna go ahead and merge this.

**Pull request merged**
