### PR TITLE
fix: Fix problematic method signatures in serializers

### PR DESCRIPTION
**Pull request by markstory**
serialize() had `*args` following keyword arguments. This results in `*args` not being usable as python globs too many arguments into keyword args.

Refs SEN-64

### CODE REVIEW

**Review by evanpurkhiser — DISMISSED** [review]

**Review by logicalbomb — APPROVED** [review]
This seems more correct to me. 👍

**Review by dcramer — COMMENTED** [review]
I’m confused - you can pass the named args and the remainder will be treated as expanded args. I’ve generally found that to be safer than relying on argument order. It especially helps in refactor scenarios where you inevitably miss a caller.

**Review by mattrobenolt — DISMISSED** [review]
In what situation was the current implementation not working? This is a pretty fundamental and core change that could make some stuff problematic, if not now, in the future, as @dcramer points out.

So something this major should come with at minimum tests proving the bad behavior.

**Comment by markstory** [comment]
@mattrobenolt @dcramer The current implementation fails as soon as you attempt to use an additional un-named argument. I attempted to do just that in [another pull request](https://github.com/getsentry/sentry/pull/12342/files#diff-36ebd54fa660bd686e7b75e3e44ee463R384) and it failed with. 

```
TypeError: serialize() got multiple values for keyword argument 'user'
```

A small scale example of this problem is

```python
def test(one, two, *args, **kwargs):
  print 'args', args
  print 'kwargs', kwargs
  if two is not None:
    test(one=one, two=None, *args, **kwargs)

test('a', 'b', 'c', 'd', e='e')
```

It fails in the same way as the current implementation of `serialize()` does. I'll add a test scenario for this and additional keyword arguments.

**Comment by dcramer** [comment]
I would suggest removing unnamed arg support then. It’s more clear than overloading with additional positional args. At the very least you can just pass your new arg as a named arg.

**Comment by markstory** [comment]
> I would suggest removing unnamed arg support then. It’s more clear than overloading with additional positional args.

I'm ok with that. I was trying to make the least disruptive change to the interface of serialize().

**Comment by dcramer** [comment]
Can you show what you’re trying to do? We have used the arg support in the past without a problem. I don’t think removing *args will be an issue but I still think there’s a misunderstanding here.

**Comment by markstory** [comment]
https://github.com/getsentry/sentry/pull/12342/files#diff-36ebd54fa660bd686e7b75e3e44ee463R316

Is the relevant line from the change I'm trying to make. I attempted to pass an additional positional argument to `serialize()` as the signature implied it would work (but it doesn't). Additional keyword arguments work fine though.

**Comment by dcramer** [comment]
Makes sense - yeah my preferred approach would be top remove *args support so this is less confusing. It was never intended to be used that way (for the problems you point out) anyways.

**Review by dcramer — APPROVED** [review]

**Pull request merged**
