### PR TITLE
feat: Add util.retries.timed_retry decorator

### PR DESCRIPTION
**Pull request by evanpurkhiser**

### CODE REVIEW

**Review by tkaemming — APPROVED** [review]
This seems fine to me.

My opinion: I'd maybe consider changing it to be a `wrap` method on the base `RetryPolicy` instead so passing through parameters is a little less awkward, and it would then be automatically added to any retry policies we add in the future.

**Comment by dcramer** [comment]
Nit: util.retries isn’t a component (I’d just axe it)

**Comment by EvanPurkhiser** [comment]
> util.retries isn’t a component

What do you mean isn't a 'component'?

**Comment by dcramer** [comment]
@evanpurkhiser component would be like 'auth' or 'api' or something more broad, not the literal file you're modifying (if anything, it'd be utils, but not sure that provides a ton of value)

**Comment by EvanPurkhiser** [comment]
Ah the commit, I see, yeah I'll change the commit message. Wanted to revisit Ted's comment first.

Thanks

**Comment by EvanPurkhiser** [comment]
Updated as a class method on the `RetryPolicy` base class.

**Pull request merged**
