### PR TITLE
ref: Fetch SDK versions from release registry

### PR DESCRIPTION
**Pull request by untitaker**
Not sure whether we want to allow onprem users to use the registry. If not, we should move the value to getsentry.

### CODE REVIEW

**Review by bruno-garcia — APPROVED** [review]
Not sure about the logging error though in case of on-prem installation without access to the internet to fetch the SDK versions.
Maybe a config value to opt in to the external registry?

**Comment by untitaker** [comment]
You can opt out by setting the release registry URL to `None`, but I am not sure if we support offline Sentries in general?

**Comment by bruno-garcia** [comment]
> I am not sure if we support offline Sentries in general?
Not sure if there's a reason for the server to have to access the Internet. 

> You can opt out by setting the release registry URL to `None`
What about an opt-in instead? We can set the url via config instead of checked in here?

**Comment by untitaker** [comment]
@bruno-garcia we will set this in getsentry instead of here. With the way the registry is deployed right now, we don't know if we can handle the load if every onprem instance starts pinging it

**Pull request merged**
