### PR TITLE
feat(tsdb): Filter new outcome category types in snuba TSDB module

### PR DESCRIPTION
**Pull request by JoshFerge**
In support of https://github.com/getsentry/snuba/pull/1683, this change will limit the current org stats page and other places where Snuba Outcomes TSDB is used to only receive Errors. Places where this is used do not currently support showing outcomes of different categories, so they need to be restricted to errors. It is my understanding that going forward we will use the new outcomes snuba module in places where we need to query the outcomes dataset.

Note that the test cases added don't actually test the required snuba changes since this change is going out first. However, I have tested locally and confirmed intended behavior with that branch.

#sync-getsentry

### CODE REVIEW

**Review by markstory — COMMENTED** [review]
Looks good to me.

**Review by evanh — APPROVED** [review]
Looks good to me. I think I saw the Snuba migration has already been run, right?

**Comment by JoshFerge** [comment]
@evanh yep! going to test on staging real quick then this should be good to deploy

**Comment by JoshFerge** [comment]
staging looks good. 🚢

**Pull request merged**
