### PR TITLE
fix(crons): Allow CheckIn expected at to be blank

### PR DESCRIPTION
**Pull request by natikgadzhi**
## Summary

This pull request fixes a tiny bug in Crons web UI. 

## Problem

When the client reported the very first check-in of a new monitor, it's Expected At will render as "Invalid Date", which is not entirely technically correct — this check-in just does not have the `checkIn.expectedAt` at all. 

## Solution

Just show the blank field, like empty Duraction or Issues. That pattern is already used across the products, so users won't be surprised to see it.

## Screenshots

Left: before, right: after.

Screenshot 2023-11-25 at 4 15 57 PM

## Review

- I finally have Sentry running locally end to end, including relay and consumers.
- I've verified that this works (see screenshot) locally.
- I did not write unit tests for this change. Should we add one? I'm new to the codebase and didn't yet find the component-level tests for this.

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Comment by natikgadzhi** [comment]
Hypothetically, _maybe_ it's worth checking that the `checkIn` in question is the very first one for this monitor.

**Review by davidenwang — APPROVED** [review]
thanks for this! I think as you mentioned it might be worth to check if the checkin was the first, but i think what you wrote is generally good to have, we probably wouldn't want to show "Invalid Date" and just fall back to the empty cell anyways.

**Comment by natikgadzhi** [comment]
@davidenwang thank you for the review! I'm down to work on this more, but want to move in small steps that are easy to review and ship. Do you think we can merge and ship this, or would you like me to implement the "is this the first check-in" check?

**Comment by natikgadzhi** [comment]
Sounds great!

@davidenwang, I'm incrementally diving into Sentry's codebase. If you see any other small-ish issues, not necessarily limited to the frontend, feel free to tag me for some extra free labor! 🙃

**Pull request closed without merging**
