### PR TITLE
dev: remove virtualenv

### PR DESCRIPTION
**Pull request by joshuarli**
This removes virtualenv, since we only support py3.6 now. Will follow up with getsentry and documentation changes.

This also frees us from the virtualenv pin needed to keep pre-commit happy.

### CODE REVIEW

**Comment by joshuarli** [comment]
I also want to upgrade pre-commit, black, flake8, but just gonna test that in this PR for now.

**Review by untitaker — APPROVED** [review]
💯

**Comment by joshuarli** [comment]
lol

```
Oh no! 💥 💔 💥
150 files reformatted, 2717 files left unchanged, 1 file failed to reformat.
```

also

```
error: cannot format tests/sentry/integrations/jira/test_integration.py: INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/psf/black/issues.
```

**Comment by joshuarli** [comment]
Oh huh, logs reveal `<TargetVersion.PY27: 2>`, but configuring pc `args: ["--target-version", "py36"]` for black doesn't solve the issue.

**Comment by joshuarli** [comment]
Okay, I was able to manually format the file black tripped on, and now it likes it.

**Comment by joshuarli** [comment]
So if I pass `--target-version py36` to black, it strips away all the unnecessary `u` prefixes... nice.

**Comment by EvanPurkhiser** [comment]
We should apply some of these commits separately for sure

**Comment by joshuarli** [comment]
Superseded by https://github.com/getsentry/sentry/pull/22903.

**Pull request closed without merging**
