### PR TITLE
Add artifact upload modal to release artifacts page (WIP)

### PR DESCRIPTION
**Pull request by benvinegar**
image

### CODE REVIEW

**Comment by dcramer** [comment]
lgtm

**Comment by benvinegar** [comment]
The button for launching this:

image

Everything's a little off. Will need a hand from @ckj.

**Comment by mattrobenolt** [comment]
Is it possible to detect if the upload was rejected for being too large? nginx should spit back a 413 in that case.

**Comment by benvinegar** [comment]
> Is it possible to detect if the upload was rejected for being too large? nginx should spit back a 413 in that case.

Yes.

**Comment by markstory** [comment]
This pull request cannot be merged currently. Without further updates it will be closed in a few days.

**Comment by benvinegar** [comment]
RIP

**Pull request closed without merging**
