### PR TITLE
feat(rrweb): Bump version to include StyleSheetRule events

### PR DESCRIPTION
**Pull request by dcramer**

### CODE REVIEW

**Comment by billyvg** [comment]
Shouldn't this be bumped in `@sentry/rrweb`? We never directly import rrweb from sentry

**Comment by billyvg** [comment]
@BYK what's the idiomatic way to have `rrweb-player` resolve to `rrweb@^0.7.28`?

**Comment by BYK** [comment]
>@BYK what's the idiomatic way to have rrweb-player resolve to rrweb@^0.7.28 (without making rrweb an explicit dependency)?

https://classic.yarnpkg.com/en/docs/selective-version-resolutions#toc-how-to-use-it

**Review by BYK — CHANGES_REQUESTED** [review]
We should use the resolutions field for this.

**Comment by billyvg** [comment]
Is there a way without `resolutions`? e.g. if you were to reinstall `rrweb-player`, wouldn't yarn lock file would use `rrweb@0.7.28` since its dependency constraint is `rrweb@^0.7.25`

**Comment by dcramer** [comment]
Are you all bike shedding my PR

**Comment by billyvg** [comment]
Yes, I'm curious what the correct way to handle this is, it doesn't matter much for this PR since this is staff only, but you can imagine someone in the future removing this dependency because we don't directly import `rrweb` anywhere

**Review by billyvg — APPROVED** [review]

**Comment by dcramer** [comment]
I chatted offline with @BYK and I agree with resolutions here. I dont think their docs do a good job of explaining why you actually need it, or really explaining how you do it, so my biggest fear here is a developer wont understand what its for. I'm hoping they'll look at the PR and ask one of us if it comes up.

**Review by BYK — APPROVED** [review]

**Comment by BYK** [comment]
>Is there a way without resolutions? e.g. if you were to reinstall rrweb-player, wouldn't yarn lock file would use rrweb@0.7.28 since its dependency constraint is rrweb@^0.7.25

Yarn will warn you if the semver ranges are not compatible. If they are, then it will reuse any existing resolutions when there is one. This latter part is the default behavior w/o resolutions anyway.

**Comment by billyvg** [comment]
What was the explanation?

**Comment by dcramer** [comment]
@billyvg that if sentry-rrweb or rrweb-player changed versions upstream, they wouldnt use the pinned version we have (if it didnt match)

**Comment by BYK** [comment]
>@billyvg that if sentry-rrweb or rrweb-player changed versions upstream, they wouldnt use the pinned version we have (if it didnt match)

This is the case when you _don't_ use resolutions. When using `resolutions`, they always take precedence but then you get a warning with every install when ranges are not semver compatible.

**Review by iProgramStuff — APPROVED** [review]

**Pull request merged**
