### PR TITLE
feat(open-pr-comments): comment template

### PR DESCRIPTION
**Pull request by cathteng**
Example comment

---

## 🚀 Sentry Issue Report
You modified these files in this pull request and we noticed these issues associated with them.

📄 **tests/sentry/tasks/integrations/github/test_open_pr_comment.py**

| Issue  | Additional Info |
| :--------- | :-------- |
| ‼️ [**Exception**](https://sentry.io/?referrer=github-open-pr-bot) /extensions/gitlab/webhook/ | `Handled:` **True** `Event Count:` **4.6m** `Users:` **37k** |
| ‼️ [**ApiError**](https://sentry.io/?referrer=github-open-pr-bot) sentry.tasks.process_commit_context  | `Handled:` **True** `Event Count:` **4.6m** `Users:` **0** |
| ‼️ [**IntegrationError**](https://sentry.io/?referrer=github-open-pr-bot) sentry.tasks.process_commit_context | `Handled:` **False** `Event Count:` **546k** `Users:` **0** |
| ‼️ [**OperationalError**](https://sentry.io/?referrer=github-open-pr-bot) sentry.tasks.assemble.assemble_dif | `Handled:` **True** `Event Count:` **27k** `Users:` **146** |
| ‼️ [**AssertionError**](https://sentry.io/?referrer=github-open-pr-bot) /auth/login/ | `Handled:` **False** `Event Count:` **24k** `Users:` **1.1k** |
<details>
<summary><b>📄 tests/sentry/tasks/integrations/github/test_pr_comment.py (Click to Expand)</b></summary>

| Issue  | Additional Info |
| :--------- | :-------- |
| ‼️ [**RateLimitExceeded**](https://sentry.io/?referrer=github-open-pr-bot) sentry.tasks.post_process.post_... | `Handled:` **True** `Event Count:` **5.8m** `Users:` **0** |
| ‼️ [**SoftTimeLimitExceeded**](https://sentry.io/?referrer=github-open-pr-bot) sentry.tasks.low_priority_s... | `Handled:` **False** `Event Count:` **1.3m** `Users:` **0** |
</details>
---

<sub>Did you find this useful? React with a 👍 or 👎</sub>

---

For ER-1809

### CODE REVIEW

**Comment by cathteng** [comment]
i'm thinking the rows might look better left justified. or we can limit the number of characters total for the issue name

---

## 🚀 Sentry Issue Report
You modified these files in this pull request and we noticed these issues associated with them.

📄 **tests/sentry/tasks/integrations/github/test_open_pr_comment.py**

| Issue  | Additional Info |
| :--------- | :-------- |
| ‼️ [**Exception**](https://sentry.io/?referrer=github-open-pr-bot) /extensions/gitlab/webhook/ | `Handled:` **True** `Event Count:` **4.6m** `Users:` **37k** |
| ‼️ [**ApiError**](https://sentry.io/?referrer=github-open-pr-bot) sentry.tasks.process_commit_context  | `Handled:` **True** `Event Count:` **4.6m** `Users:` **0** |
| ‼️ [**IntegrationError**](https://sentry.io/?referrer=github-open-pr-bot) sentry.tasks.process_commit_context | `Handled:` **False** `Event Count:` **546k** `Users:` **0** |
| ‼️ [**OperationalError**](https://sentry.io/?referrer=github-open-pr-bot) sentry.tasks.assemble.assemble_dif | `Handled:` **True** `Event Count:` **27k** `Users:` **146** |
| ‼️ [**AssertionError**](https://sentry.io/?referrer=github-open-pr-bot) /auth/login/ | `Handled:` **False** `Event Count:` **24k** `Users:` **1.1k** |
<details>
<summary><b>📄 tests/sentry/tasks/integrations/github/test_pr_comment.py (Click to Expand)</b></summary>

| Issue  | Additional Info |
| :--------- | :--------:|
| ‼️ [**RateLimitExceeded**](https://sentry.io/?referrer=github-open-pr-bot) sentry.tasks.post_process.post_process_group | `Handled:` **True** `Event Count:` **5.8m** `Users:` **0** |
| ‼️ [**SoftTimeLimitExceeded**](https://sentry.io/?referrer=github-open-pr-bot) sentry.tasks.low_priority_symbolication.scan_for_suspect_pro... | `Handled:` **False** `Event Count:` **1.3m** `Users:` **0** |
</details>
---

<sub>Did you find this useful? React with a 👍 or 👎</sub>

**Review by nhsiehgit — APPROVED** [review]
👌

**Comment by Dhrumil-Sentry** [comment]
## 🚀 Sentry Issue Report - Existing Issues
You modified these files in this pull request and we noticed these issues associated with them.

📄 **src/sentry/event_manager.py**

| Issue | Actions |
| :---- | :-----: |
| ‼️ [**HashDiscarded: Timeout when getting next_short_id**](https://sentry.sentry.io/issues/4664909353/?referrer=github-open-pr-bot) issues.occurrence_consume...<br>`Handled:` **True** `Event Count:` **69** `Users:` **0** | [Archive](archive-link-1) / [Resolve](resolve-link-1) |
| ‼️ [**HashDiscarded: Matches group tombstone 108268**](https://sentry.sentry.io/issues/4496066583/?referrer=github-open-pr-bot) Pro...<br>`Handled:` **True** `Event Count:` **20** `Users:` **6** | [Archive](archive-link-2) / [Resolve](resolve-link-2) |
| ‼️ [**HashDiscarded: Timeout when getting next_short_id**](https://sentry.sentry.io/issues/4664921141/?referrer=github-open-pr-bot) issues.occurrence_consume...<br>`Handled:` **True** `Event Count:` **12** `Users:` **0** | [Archive](archive-link-3) / [Resolve](resolve-link-3) |
| ‼️ [**HashDiscarded: Timeout when getting next_short_id**](https://sentry.sentry.io/issues/4664915182/?referrer=github-open-pr-bot) issues.occurrence_consume...<br>`Handled:` **True** `Event Count:` **5** `Users:` **0** | [Archive](archive-link-4) / [Resolve](resolve-link-4) |

---

<sub>Did you find this useful? React with a 👍 or 👎 or let us know in #proj-github-pr-comments</sub>

**Comment by Dhrumil-Sentry** [comment]
## 🚀 Sentry PR Impact Analysis
**Summary:** This report identifies potential issues in your PR based on the files you've modified.

### Summary Box
- **Critical Issues:** 2 (Directly Related)
- **Additional Issues:** 3 (Potentially Related), 2 (Historical)
- [View Detailed Report](detailed-report-link)

### 📄 Modified File: `src/sentry/event_manager.py`
#### Directly Related Issues
| Issue | Actions | Reason |
| :---- | :-----: | :----- |
| ‼️ [**HashDiscarded: Timeout when getting next_short_id**](https://sentry.sentry.io/issues/4664909353/?referrer=github-open-pr-bot) | [Review](review-link-1) / [Ignore](ignore-link-1) | Direct impact on code changes. |
| ‼️ [**HashDiscarded: Matches group tombstone 108268**](https://sentry.sentry.io/issues/4496066583/?referrer=github-open-pr-bot) | [Review](review-link-2) / [Ignore](ignore-link-2) | Affected by recent changes in dependencies. |

#### Potentially Related Issues
<details>
<summary>View Issues</summary>

| Issue | Actions |
| :---- | :-----: |
| 🔶 [**HashDiscarded: Timeout when getting next_short_id**](https://sentry.sentry.io/issues/4664921141/?referrer=github-open-pr-bot) | [Review](review-link-3) / [Ignore](ignore-link-3) |
| 🔶 [**HashDiscarded: Timeout when getting next_short_id**](https://sentry.sentry.io/issues/4664915182/?referrer=github-open-pr-bot) | [Review](review-link-4) / [Ignore](ignore-link-4) |

</details>

#### Historical Issues
<details>
<summary>View Issues</summary>

| Issue | Actions |
| :---- | :-----: |
| 🔘 [**Old Issue Example 1**](historical-issue-link-1) | [Review](historical-review-link-1) |
| 🔘 [**Old Issue Example 2**](historical-issue-link-2) | [Review](historical-review-link-2) |

</details>

### Feedback
- How relevant did you find these issues? [👍 Very Relevant](feedback-link-up) / [👎 Not Relevant](feedback-link-down)
- [Provide detailed feedback](detailed-feedback-link)

---

<sub>Questions or suggestions? Let us know in #proj-github-pr-comments</sub>

**Pull request merged**
