### PR TITLE
fix: Correct issue group button padding for plugin actions

### PR DESCRIPTION
**Pull request by evanpurkhiser**
sentry io_sentry_sentry_issues_393454866_ 4
↓
sentry io_sentry_sentry_issues_393454866_ 3

### CODE REVIEW

**Comment by MaxBittker** [comment]
>percy/sentry — Visual review automatically approved. No visual diffs found.

huh?

**Comment by MaxBittker** [comment]
oh, because it doesn't have this plugin enabled

**Review by MaxBittker — APPROVED** [review]
<3 padding

**Comment by EvanPurkhiser** [comment]
Damn, something has the inconsistent classes:

image

**Pull request merged**
