### PR TITLE
feat(adoption): Add project has_sourcemaps flag

### PR DESCRIPTION
**Pull request by maheskett**
We track source map adoption by organization, but adding this on a project basis as well for an upcoming source map empty state / minified code warning

### CODE REVIEW

**Review by wedamija — COMMENTED** [review]
Please included the generated ddl, instructions here: https://www.notion.so/sentry/Django-migrations-103e5994029d4345b5b6f5f6f9cac9c7

**Comment by maheskett** [comment]
Are you talking about this: https://github.com/getsentry/sentry/pull/16917/files#diff-05243c01b947e69f10c86552f23008d4R11. Should this change produce a migration?

**Comment by wedamija** [comment]
> Are you talking about this: https://github.com/getsentry/sentry/pull/16917/files#diff-05243c01b947e69f10c86552f23008d4R11. Should this change produce a migration?

It should hopefully generate no ddl, but it's good to confirm.

**Review by wedamija — APPROVED** [review]
Confirmed that this flag hasn't been used before
```
select count(*)
from sentry_project
where (flags & (2 ^ 1)::int) > 0
```

Probably will have to regenerate your migration since someone pushed one ahead of you.

**Pull request merged**
