### PR TITLE
fix(replay): Frame message null check

### PR DESCRIPTION
**Pull request by c298lee**
Adds a null check for frame message, however doesn't fix the underlying problem that SDKs can send junk
Related to JAVASCRIPT-2W7W

### CODE REVIEW

**Review by billyvg — APPROVED** [review]

**Comment by billyvg** [comment]
Do we have any tests for this?

**Review by michellewzhang — APPROVED** [review]
thanks!

**Comment by c298lee** [comment]
closing this in favour of setting null fields that are required to an empty string during breadcrumb/frame hydration

**Comment by c298lee** [comment]
Reopening to fix the errors while we are investigating how a mobile replay has User Click breadcrumbs

**Review by aliu39 — APPROVED** [review]

**Pull request merged**
