### PR TITLE
ci(pg): Add PostgreSQL v14 to testing matrix

### PR DESCRIPTION
**Pull request by beezz**
Since PostgreSQL v9.6 is no longer supported [^1] we will be migrating to a newer version. To make sure we are not breaking other environments with v9.6 in the process of migrations we'll be running tests for both versions.

[^1]:  https://www.postgresql.org/support/versioning/

### CODE REVIEW

**Comment by armenzg** [comment]
Is this because we're looking into moving from 9.6 to version 12? Just trying to figure out the context of the PR.

**Review by armenzg — COMMENTED** [review]
There's few more workflows that use the setup-sentry action.
Do we want to use dual matrix for all of those? or closer to the date we switch the default and see how they fair? I'm fine with either approach.

```
.github/workflows/api-docs-test.yml:        uses: ./.github/actions/setup-sentry
.github/workflows/backend-test.yml:        uses: ./.github/actions/setup-sentry
.github/workflows/check-if-migration-is-required.yml:        uses: ./.github/actions/setup-sentry
.github/workflows/command-line-test.yml:        uses: ./.github/actions/setup-sentry
.github/workflows/migrations.yml:        uses: ./.github/actions/setup-sentry
.github/workflows/openapi-diff.yml:        uses: ./.github/actions/setup-sentry
.github/workflows/openapi.yml:        uses: ./.github/actions/setup-sentry
.github/workflows/plugins-test.yml:        uses: ./.github/actions/setup-sentry
.github/workflows/relay-integration-test.yml:        uses: ./.github/actions/setup-sentry
.github/workflows/snuba-integration-test.yml:        uses: ./.github/actions/setup-sentry
.github/workflows/symbolicator-integration-test.yml:        uses: ./.github/actions/setup-sentry
```

**Comment by armenzg** [comment]
Let's coordinate landing early on a morning so I can make sure to add the new set of required checks. We will need to ask devs to rebase once the changes merge.

**Review by armenzg — APPROVED** [review]

**Review by armenzg — CHANGES_REQUESTED** [review]
@billyvg I would like your input in here.

I see some Visual Snapshot differences:
https://storage.googleapis.com/sentry-visual-snapshots/getsentry/sentry/dd3ca21b7821cc5d7a356e98085ddb98d462408d/index.html

Is there a way that we're running Visual Snapshots against snapshots generated by PG 14? I wonder if the database is not ready on time. See these two screenshots:
image
image


I'm thinking that we should take a different approach with the PR. Instead of testing against two versions until we switch over, we should do a PR for the day that we want to switch over.

Partly because of the huge headache of timing different "Required checks" now (include Pg9 in all the names and remove the other ones) and then in the future (when we need to swamp version 9 for 14 in all workflows).

**Comment by billyvg** [comment]
@armenzg That looks like a flaky test -- however it's possible that we have a *mix* of 9.6/14 snapshots.

What I've done in the past is to make an entirely new workflow for the new tests so that the existing required checks do not need to be updated. 

- [ ] Add new workflow for acceptance + backend tests for v14
- [ ] If you wanted to not disturb developers, wait <x> days before making new v14 checks required
- [ ] On cutover: update pg version in required workflows
  - [ ] remove the added workflow for v14
  - [ ] remove required checks

**Comment by armenzg** [comment]
> @armenzg That looks like a flaky test -- however it's possible that we have a _mix_ of 9.6/14 snapshots.
> 
> What I've done in the past is to make an entirely new workflow for the new tests so that the existing required checks do not need to be updated.
> 
>     * [ ]  Add new workflow for acceptance + backend tests for v14
> 
>     * [ ]  If you wanted to not disturb developers, wait  days before making new v14 checks required
> 
>     * [ ]  On cutover: update pg version in required workflows
>       
>       * [ ]  remove the added workflow for v14
>       * [ ]  remove required checks

Good point. @beezz would this work for you?

**Comment by beezz** [comment]
> > @armenzg That looks like a flaky test -- however it's possible that we have a _mix_ of 9.6/14 snapshots.
> > What I've done in the past is to make an entirely new workflow for the new tests so that the existing required checks do not need to be updated.
> > ```
> > * [ ]  Add new workflow for acceptance + backend tests for v14
> > 
> > * [ ]  If you wanted to not disturb developers, wait  days before making new v14 checks required
> > 
> > * [ ]  On cutover: update pg version in required workflows
> >   
> >   * [ ]  remove the added workflow for v14
> >   * [ ]  remove required checks
> > ```
> 
> Good point. @beezz would this work for you?

Yes, that will work. Great idea, thanks!

**Pull request closed without merging**
