### PR TITLE
Test Sentry Python SDK 2.0.0a2 on Canary

### PR DESCRIPTION
**Pull request by antonpirker**
This is a branch to run the new Python SDK 2.0.0a2 on our Canary infrastructure to check for eventual changes in CPU/memory consumption.

The SDK 2.0 was running on Canary from **11:30 - 12:15** on 2024-03-08.

### CODE REVIEW

**Review by cleptric — APPROVED** [review]

**Review by beezz — APPROVED** [review]

**Comment by antonpirker** [comment]
canary-web-cpu

Canary Web Worker CPU.
The SDK 2.0 was running from 11:30 - 12:15

**Comment by antonpirker** [comment]
canary-web-mem

Canary Web Worker Memory.
The SDK 2.0 was running from 11:30 - 12:15

**Comment by antonpirker** [comment]
canary-celeryworker-mem

Canary Celery Worker Memory.
The SDK 2.0 was running from 11:30 - 12:15

**Comment by antonpirker** [comment]
Zooming out further shows that there was no change in CPU/Memory when using Python SDK 2.0

**Pull request merged**
