### PR TITLE
fix: Add functools32 requirement

### PR DESCRIPTION
**Pull request by alex-hofsteede**

### CODE REVIEW

**Comment by adhiraj** [comment]
How do we generally keep requirements files updated with code changes? pip freeze? The code works without this change because functools gets installed as a dependency of another package, but this seems brittle.

**Comment by mattrobenolt** [comment]
What is this for?

**Comment by adhiraj** [comment]
https://github.com/getsentry/sentry/blob/master/src/sentry/interfaces/schemas.py#L11

**Comment by alex-hofsteede** [comment]
Yeah its a requirement that is installed through an implicity dependency in some other package, so I guess the question is, should we also explicitly add it since we depend on it directly?

**Comment by mattrobenolt** [comment]
Yeah, if we’re using it explicitly, we should explicitly declare it as our own dependency. I’d just make sure to cap the upper bound to something reasonable so we don’t major version bump and break things.

**Review by mattrobenolt — APPROVED** [review]
Make sure to add an explicit pin into `getsentry`.

**Pull request merged**
