### PR TITLE
fix(api): Actually order body params by required vs optional

### PR DESCRIPTION
**Pull request by schew2381**
Closed in favor of manual dereferencing in: https://github.com/getsentry/sentry/pull/57639
There were concerns about the `jsonrefs` package and it's actually quite simple to manually dereference
-----

Previously, this ordering silently failed because the request body `schema` we were fetching only had a reference to it's actual key-value pairs. At the very start of the hook, we now replace all references with a lazy lookup object, which will replace the reference with the real key-value pairs when called upon.

See `jsonref` [documentation](https://jsonref.readthedocs.io/en/latest/#jsonref.replace_refs) for more info

### CODE REVIEW

**Review by sentaur-athena — APPROVED** [review]
Neat!

**Comment by JoshFerge** [comment]
I would also be interesting explroring dropping dereferencing. i'm not sure if we actually have to do that.

**Comment by schew2381** [comment]
> I would also be interesting explroring dropping dereferencing. i'm not sure if we actually have to do that.

Is it drf-spec that's automatically dereferencing or something else internally?

**Comment by JoshFerge** [comment]
here: https://github.com/getsentry/sentry/blob/8a7b2b8d656f6c815f406439176b9807f856164c/api-docs/index.ts#L32

You could also consider modifying that code, it may be easier to do that than to add a new python library. and yes, can see if it would make sense not to derference the JSON.

**Pull request closed without merging**
