### PR TITLE
ref(externalteam): Remove foreign key constraint from ExternalTeam

### PR DESCRIPTION
**Pull request by ceorourke**
The `ExternalTeam` and `ExternalUser` tables are currently unused and have been replaced with an `ExternalActor` table.

This is step 1 to remove the unused tables by dropping the foreign key constraints to the `Team` and `OrganizationMember` tables. Step 2 will be to remove the code, and step 3 will be to create a migration to remove the table (for each).

### CODE REVIEW

**Comment by ceorourke** [comment]
Is it safe enough for me to remove the fk constraint on the `ExternalUser` model in this PR too? 🤔

**Comment by scefali** [comment]
> Is it safe enough for me to remove the fk constraint on the `ExternalUser` model in this PR too? 🤔

@ceorourke You can just remove the tables as well. Since these tables are not actively being written to by users (I see 3 rows in the `ExternalTeam` table which are all from us testing, you don't have to worry about the migration being run after the code change is active. Easier to remove everything in one go I think.

**Comment by scefali** [comment]
@ceorourke Just spoke to @wedamija about this. We should just stick to the prodedure.

**Review by wedamija — COMMENTED** [review]
Yeah I'd recommend just following the procedure. It's fine to remove the constraints for both tables in the same pr though.

**Review by scefali — APPROVED** [review]

**Review by wedamija — APPROVED** [review]

**Pull request merged**
