### PR TITLE
fix(ui): Hide adoption stage tag earlier

### PR DESCRIPTION
**Pull request by taylangocmen**
This fixes the release adoption stage label ui for smaller widths.

### CODE REVIEW

**Review by matejminar — COMMENTED** [review]
I think we also need to update these grid-template-columns:
https://github.com/getsentry/sentry/blob/f6951539c1b0577bb424e1c79151fa6c00043372/static/app/views/releases/list/releaseHealth/content.tsx#L313-L360

**Comment by matejminar** [comment]
We still need to check hasAdoptionStages prop (some users have not this feature flag enabled). We just need to reduce the number of columns once we hide the adoption column at certain breakpoint.

**Comment by taylangocmen** [comment]
> We still need to check hasAdoptionStages prop (some users have not this feature flag enabled). We just need to reduce the number of columns once we hide the adoption column at certain breakpoint.

We check for the prop at here: https://github.com/getsentry/sentry/pull/27162/files#diff-4dbcf06343de02df9eee14c8cf41d1b7bf65c406d331b15239b9bd4d0806348aL350

For widths smaller than breakpoints[3], the columns will be the same regardless of the prop.

**Review by matejminar — APPROVED** [review]
You are right! That's what I get for reviewing code on my phone 😅

**Pull request merged**
