### PR TITLE
Add server-side data filters

### PR DESCRIPTION
**Pull request by dcramer**
This adds new server-side filters. To make this possible, we've moved data validation and normalization into LazyData, so it can execute on demand.

Of note, it always executes at the moment because platform is part of the data payload :(

This adds four filters:
- Browser extensions
- Localhost
- Legacy browsers
- Web crawlers

/cc @getsentry/javascript @getsentry/infrastructure

---

This change is [Reviewable](https://reviewable.io/reviews/getsentry/sentry/3921)

### CODE REVIEW

**Comment by dcramer** [comment]
No UI around this yet. Wanted to get initial thoughts here.

We should pay attention when pushing this out as it may dramatically increase CPU on workers

**Comment by dcramer** [comment]
Might be nice in the future to tweak SDK API to hint at the platform via credentials

**Comment by dcramer** [comment]
I think we should add in old browsers as well as crawlers to this yet. If someone can help me come up with the rules around those I'll get them in.

// @benvinegar

**Comment by dcramer** [comment]
screenshot 2016-08-12 11 51 13

Probably could improve messaging around what filters are, as well as move away from a checkbox here.

Also needs polish to have loading/error per-row.

**Comment by mattrobenolt** [comment]
Review status: 0 of 20 files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

*[src/sentry/filters/browser_extensions.py, line 7 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/3921#-KP-4e8IkM2-XPa-HHAS:-KP-4e8IkM2-XPa-HHAT:bj2d5aj) ([raw file](https://github.com/getsentry/sentry/blob/9fcae2136d62dfb01579325ee4db563743513ae3/src/sentry/filters/browser_extensions.py#L7)):*
> EXTENSION_EXC_VALUES = (
<details><summary><i alt="summary">Quoted 21 lines of code…</i></summary>
>     # Random plugins/extensions
>     'top.GLOBALS',
>     # See: http://blog.errorception.com/2012/03/tale-of-unfindable-js-error. html
>     'originalCreateNotification',
>     'canvas.contentDocument',
>     'MyApp_RemoveAllHighlights',
>     'http://tt.epicplay.com',
>     'Can\'t find variable: ZiteReader',
>     'jigsaw is not defined',
>     'ComboSearch is not defined',
>     'http://loading.retry.widdit.com/',
>     'atomicFindClose',
>     # Facebook borked
>     'fb_xd_fragment',
>     # ISP "optimizing" proxy - `Cache-Control: no-transform` seems to
>     # reduce this. (thanks @acdha)
>     # See http://stackoverflow.com/questions/4113268
>     'bmi_SafeAddOnload',
>     'EBCallBackMessageReceived',
>     # See http://toolbar.conduit.com/Developer/HtmlAndGadget/Methods/JSInjection.aspx
>     'conduitPage'
</details>
> )


I'm pretty sure these being one big regular expression would be faster too, than checking `in` for every one against the string. I can confirm.

---

*[src/sentry/filters/browser_extensions.py, line 31 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/3921#-KP-4T6WkZTOGdFVaY02:-KP-4T6WkZTOGdFVaY03:b-f6hgj6) ([raw file](https://github.com/getsentry/sentry/blob/9fcae2136d62dfb01579325ee4db563743513ae3/src/sentry/filters/browser_extensions.py#L31)):*
> EXTENSION_EXC_SOURCES = (
<details><summary><i alt="summary">Quoted 15 lines of code…</i></summary>
>     # Facebook flakiness
>     re.compile(r'graph\.facebook\.com', re.I),
>     # Facebook blocked
>     re.compile(r'connect\.facebook\.net\/en_US\/all\.js', re.I),
>     # Woopra flakiness
>     re.compile(r'eatdifferent\.com\.woopra-ns\.com', re.I),
>     re.compile(r'static\.woopra\.com\/js\/woopra\.js', re.I),
>     # Chrome extensions
>     re.compile(r'extensions\/', re.I),
>     re.compile(r'^chrome:\/\/', re.I),
>     # Cacaoweb
>     re.compile(r'127\.0\.0\.1:4001\/isrunning', re.I),
>     # Other
>     re.compile(r'webappstoolbarba\.texthelp\.com\/', re.I),
>     re.compile(r'metrics\.itunes\.apple\.com\.edgesuite\.net\/', re.I),
</details>
> )

We should compile these into one regular expression with pipes to be a big OR. It'll perform much faster, especially as this list grows.

---

*[src/sentry/filters/browser_extensions.py, line 40 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/3921#-KP-5xwEIGUrl_un8A0b:-KP-5xwEIGUrl_un8A0c:b-mqfhzh) ([raw file](https://github.com/getsentry/sentry/blob/9fcae2136d62dfb01579325ee4db563743513ae3/src/sentry/filters/browser_extensions.py#L40)):*
> ```Python
>     re.compile(r'static\.woopra\.com\/js\/woopra\.js', re.I),
>     # Chrome extensions
>     re.compile(r'extensions\/', re.I),
> ```

Not trying to audit every single one of these, but this one seems like it might be way too liberal. Literally the string "extensions/" somewhere in the url. All of the others seem fine and wouldn't be too eager.

---

*[src/sentry/filters/browser_extensions.py, line 57 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/3921#-KP-4yQcn0tK7ihKrBI7:-KP-4yQcn0tK7ihKrBI8:b-6ro8kf) ([raw file](https://github.com/getsentry/sentry/blob/9fcae2136d62dfb01579325ee4db563743513ae3/src/sentry/filters/browser_extensions.py#L57)):*
> ```Python
>         try:
>             return data['sentry.interfaces.Exception']['values'][0]['value']
>         except (KeyError, IndexError):
> ```

ProTip: `LookupError` is the superclass of both `KeyError` and `IndexError`

---

*[src/sentry/filters/localhost.py, line 17 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/3921#-KP-5GIZmHX729jcm7xp:-KP-5GIZmHX729jcm7xq:b-qeob2m) ([raw file](https://github.com/getsentry/sentry/blob/9fcae2136d62dfb01579325ee4db563743513ae3/src/sentry/filters/localhost.py#L17)):*
> ```Python
> 
>     def test(self, data):
>         return self.get_ip_address(data) == '127.0.0.1'
> ```

We should add ipv6 here as well. It's pretty common now to hit that when developing on localhost now. Should just be `::1`. If you "bind to all interfaces" on modern things, you're generally going to bind to both ipv4 and ipv6, with ipv6 addr being prioritized.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3921)*

**Comment by mattrobenolt** [comment]
Review status: 0 of 20 files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

*[src/sentry/filters/browser_extensions.py, line 31 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/3921#-KP-4T6WkZTOGdFVaY02:-KP-7yypsE0taTnPLIZJ:brquyyt) ([raw file](https://github.com/getsentry/sentry/blob/9fcae2136d62dfb01579325ee4db563743513ae3/src/sentry/filters/browser_extensions.py#L31)):*
<details><summary><i>Previously, mattrobenolt (Matt Robenolt) wrote…</i></summary>
> > EXTENSION_EXC_SOURCES = (
> >     # Facebook flakiness
> >     re.compile(r'graph\.facebook\.com', re.I),
> >     # Facebook blocked
> >     re.compile(r'connect\.facebook\.net\/en_US\/all\.js', re.I),
> >     # Woopra flakiness
> >     re.compile(r'eatdifferent\.com\.woopra-ns\.com', re.I),
> >     re.compile(r'static\.woopra\.com\/js\/woopra\.js', re.I),
> >     # Chrome extensions
> >     re.compile(r'extensions\/', re.I),
> >     re.compile(r'^chrome:\/\/', re.I),
> >     # Cacaoweb
> >     re.compile(r'127\.0\.0\.1:4001\/isrunning', re.I),
> >     # Other
> >     re.compile(r'webappstoolbarba\.texthelp\.com\/', re.I),
> >     re.compile(r'metrics\.itunes\.apple\.com\.edgesuite\.net\/', re.I),
> > )
> 
> We should compile these into one regular expression with pipes to be a big OR. It'll perform much faster, especially as this list grows.
</details>
To be concrete, I'd do:

```python
EXTENSION_EXC_SOURCES = (
    r'graph\.facebook\.com',
    r'connect.facebook.net\/en_US\/all.js',
    ...
)

EXTENSION_EXC_SOURCES_RE = re.compile('|'.join(EXTENSION_EXC_SOURCES), re.I)
```

Then test against `EXTENSION_EXC_SOURCES_RE` once.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3921)*

**Comment by dcramer** [comment]
Review status: 0 of 20 files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

*[src/sentry/filters/browser_extensions.py, line 40 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/3921#-KP-5xwEIGUrl_un8A0b:-KP-PcYJR1EQ4V0JzYJS:bclqxnr) ([raw file](https://github.com/getsentry/sentry/blob/9fcae2136d62dfb01579325ee4db563743513ae3/src/sentry/filters/browser_extensions.py#L40)):*
<details><summary><i>Previously, mattrobenolt (Matt Robenolt) wrote…</i></summary>
> Not trying to audit every single one of these, but this one seems like it might be way too liberal. Literally the string "extensions/" somewhere in the url. All of the others seem fine and wouldn't be too eager.
</details>
I literally copy pasted from our docs. I'd rather not change it unless we know exactly what it was from/etc. And then I would question why our docs are wrong.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3921)*

**Comment by benvinegar** [comment]
:lgtm:

---

Reviewed 6 of 20 files at r1.
Review status: 6 of 20 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/sentry/filters/browser_extensions.py, line 40 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/3921#-KP-5xwEIGUrl_un8A0b:-KP-RyOOI8mZVO9D1rLC:b-b5iox2) ([raw file](https://github.com/getsentry/sentry/blob/9fcae2136d62dfb01579325ee4db563743513ae3/src/sentry/filters/browser_extensions.py#L40)):*
<details><summary><i>Previously, dcramer (David Cramer) wrote…</i></summary>
> I literally copy pasted from our docs. I'd rather not change it unless we know exactly what it was from/etc. And then I would question why our docs are wrong.
</details>
These example values haven't been updated in at least a year. As a follow-up (don't think this is a blocker), we can update them.

---

*[src/sentry/static/sentry/app/views/projectFilters.jsx, line 103 \[r2\]](https://reviewable.io:443/reviews/getsentry/sentry/3921#-KP-Sb5PfENvKUnRzFZY:-KP-Sb5PfENvKUnRzFZZ:bxh80uq) ([raw file](https://github.com/getsentry/sentry/blob/8b96569edbea658ea8ec77cb350fa4596ba428a4/src/sentry/static/sentry/app/views/projectFilters.jsx#L103)):*
> ```JSX
> 
>   onToggleFilter(filter, active) {
>     underscore.find(this.state.filterList, (f) => f.id === filter.id).active = active;
> ```

ES6 adds `Array.prototype.find`, so using underscore here is unnecessary. Also for arrow fns, if there is a single argument the parens are optional:

```javascript
this.state.filterList.find(f => f.id === filter.id).active = active;
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3921#-:-KP-Risvvi4Tt8gRw4gC:bnfp4nl)*

**Comment by mattrobenolt** [comment]
Reviewed 11 of 20 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/sentry/filters/browser_extensions.py, line 40 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/3921#-KP-5xwEIGUrl_un8A0b:-KP-TIIPpckuU-crtAeU:bspe3dz) ([raw file](https://github.com/getsentry/sentry/blob/9fcae2136d62dfb01579325ee4db563743513ae3/src/sentry/filters/browser_extensions.py#L40)):*
<details><summary><i>Previously, benvinegar (Ben Vinegar) wrote…</i></summary>
> These example values haven't been updated in at least a year. As a follow-up (don't think this is a blocker), we can update them.
</details>
Yeah, I'm not sure where it came from either, but I know we didn't put it together ourselves. So I wouldn't treat it as 100% fact. This was never imposed as a default, and this entire list became irrelevant in raven-js anyways and isn't needed there. With the introduction of `whitelistUrls`, none of this garbage is even collected anymore. So I'd be hesitant to apply this rule by default over an already configured `whitelistUrls` personally. The other rules here wouldn't even get hit if that was configured since the url would never match these.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3921)*

**Comment by dcramer** [comment]
Review status: 18 of 21 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/sentry/filters/browser_extensions.py, line 40 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/3921#-KP-5xwEIGUrl_un8A0b:-KP-YNlGJ37EYaZUZTn-:b-r93bgl) ([raw file](https://github.com/getsentry/sentry/blob/9fcae2136d62dfb01579325ee4db563743513ae3/src/sentry/filters/browser_extensions.py#L40)):*
<details><summary><i>Previously, mattrobenolt (Matt Robenolt) wrote…</i></summary>
> Yeah, I'm not sure where it came from either, but I know we didn't put it together ourselves. So I wouldn't treat it as 100% fact. This was never imposed as a default, and this entire list became irrelevant in raven-js anyways and isn't needed there. With the introduction of `whitelistUrls`, none of this garbage is even collected anymore. So I'd be hesitant to apply this rule by default over an already configured `whitelistUrls` personally. The other rules here wouldn't even get hit if that was configured since the url would never match these.
</details>
I removed the one

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3921)*

**Comment by ckj** [comment]
Sorry for the late addition, but I added a switch component for this feature that looks like this: 

screen shot 2016-08-15 at 1 55 06 pm

It can most definitely be optimized on the js side and may benefit from additional states down the road (e.g.  loading, success, fail, ...).

cc @getsentry/ui

**Comment by dcramer** [comment]
screenshot 2016-08-15 16 02 42

**Comment by dcramer** [comment]
This is good to go

---

Review status: 11 of 29 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3921#-:-KPFSU28V8hbUKyisID8:b-ekwi59)*

**Comment by dcramer** [comment]
Review status: 11 of 29 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/sentry/static/sentry/app/views/projectFilters.jsx, line 103 \[r2\]](https://reviewable.io:443/reviews/getsentry/sentry/3921#-KP-Sb5PfENvKUnRzFZY:-KPKGG24JJK6v2B2RzTc:b-896fix) ([raw file](https://github.com/getsentry/sentry/blob/8b96569edbea658ea8ec77cb350fa4596ba428a4/src/sentry/static/sentry/app/views/projectFilters.jsx#L103)):*
<details><summary><i>Previously, benvinegar (Ben Vinegar) wrote…</i></summary>
> ES6 adds `Array.prototype.find`, so using underscore here is unnecessary. Also for arrow fns, if there is a single argument the parens are optional:
> 
> ```javascript
> this.state.filterList.find(f => f.id === filter.id).active = active;
> ```
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3921)*

**Comment by benvinegar** [comment]
Reviewed 1 of 3 files at r4, 1 of 1 files at r5, 3 of 16 files at r6, 1 of 2 files at r7.
Review status: 17 of 29 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3921)*

**Comment by benvinegar** [comment]
Review status: 17 of 29 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tests/sentry/filters/test_legacy_browsers.py, line 39 \[r7\]](https://reviewable.io:443/reviews/getsentry/sentry/3921#-KPKHICPj3AnFBfU2VpG:-KPKHICQXBlv-WGb-nhV:b4m4qk4) ([raw file](https://github.com/getsentry/sentry/blob/f96e707cb27d221fe47e901bfa9b1f35e0374cec/tests/sentry/filters/test_legacy_browsers.py#L39)):*
> ```Python
>     def test_does_not_filter_chrome(self):
>         data = self.get_mock_data('Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36')
>         assert self.apply_filter(data) is False
> ```

I think you should add a test for Edge because it has a user agent that includes pretty much every browser:

```
Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10136
```

More: 
* http://stackoverflow.com/questions/30591706/what-is-the-user-agent-string-name-for-microsoft-edge
* https://msdn.microsoft.com/en-us/library/hh869301(v=vs.85).aspx

Same goes for Firefox. Basically, I wouldn't take any chances here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3921)*

**Comment by dcramer** [comment]
Review status: 17 of 29 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tests/sentry/filters/test_legacy_browsers.py, line 39 \[r7\]](https://reviewable.io:443/reviews/getsentry/sentry/3921#-KPKHICPj3AnFBfU2VpG:-KPKIw0iG8mApNMQ1CdN:bjau4sf) ([raw file](https://github.com/getsentry/sentry/blob/f96e707cb27d221fe47e901bfa9b1f35e0374cec/tests/sentry/filters/test_legacy_browsers.py#L39)):*
<details><summary><i>Previously, benvinegar (Ben Vinegar) wrote…</i></summary>
> I think you should add a test for Edge because it has a user agent that includes pretty much every browser:
> 
> ```
> Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10136
> ```
> 
> More: 
> * http://stackoverflow.com/questions/30591706/what-is-the-user-agent-string-name-for-microsoft-edge
> * https://msdn.microsoft.com/en-us/library/hh869301(v=vs.85).aspx
> 
> Same goes for Firefox. Basically, I wouldn't take any chances here.
</details>
fwiw ua-parser has these tests -- my goal was basically to prove a couple of the checks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3921)*

**Comment by mattrobenolt** [comment]
Reviewed 9 of 16 files at r6, 1 of 2 files at r7.
Review status: 27 of 29 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/sentry/filters/legacy_browsers.py, line 17 \[r7\]](https://reviewable.io:443/reviews/getsentry/sentry/3921#-KPKGu1LQ8JKreCwI3aR:-KPKGu1LQ8JKreCwI3aS:b-hmfre3) ([raw file](https://github.com/getsentry/sentry/blob/f96e707cb27d221fe47e901bfa9b1f35e0374cec/src/sentry/filters/legacy_browsers.py#L17)):*
> ```Python
> 
> 
> class LegacyBrowsersFilter(Filter):
> ```

I don't like this one being enabled by default.

It's being too aggressive if there's a parser error, or if the value were handled as "Other", etc. Those will all be rejected by default and I don't think that's good behavior. There's lots of weird browsers that are legitimate and they don't mean "Legacy".

In this case, aren't a lot of Opera browsers being tracked as "Other"? They'd all be dropped here 100% by default.

This will be double bad since this is also being applied to all events, and not just JavaScript. Most http clients aren't going to be setting legit User-Agents that map up to browsers, which means everything is going to be ignored.

---

*[src/sentry/filters/web_crawlers.py, line 16 \[r7\]](https://reviewable.io:443/reviews/getsentry/sentry/3921#-KPKIGdxrZYg2SBjyJ0F:-KPKIGdxrZYg2SBjyJ0G:b-4mjpc0) ([raw file](https://github.com/getsentry/sentry/blob/f96e707cb27d221fe47e901bfa9b1f35e0374cec/src/sentry/filters/web_crawlers.py#L16)):*
> ```Python
>     r'Mediapartners',
>     # Google+ and Google web search
>     r'Google',
> ```

I don't know enough, but are we sure "Google" anywhere in the User-Agent isn't too aggressive? I'm not sure if it's possible for that string to exist in like, Chrome or anything outside of being a bot. Again, I am concerned since this is going to be enabled by default, and we'll basically never figure out why something is being filtered.

---

*[src/sentry/filters/web_crawlers.py, line 37 \[r7\]](https://reviewable.io:443/reviews/getsentry/sentry/3921#-KPKIstgac3WyOVUH6oO:-KPKIsth_HqSBOy1SB79:bg0zkj2) ([raw file](https://github.com/getsentry/sentry/blob/f96e707cb27d221fe47e901bfa9b1f35e0374cec/src/sentry/filters/web_crawlers.py#L37)):*
> ```Python
>     id = 'web-crawlers'
>     name = 'Filter out known web crawlers'
>     description = 'Some crawlers may try to parse and execute JavaScript, but in an incompatible way which then triggers an error.'
> ```

I think this is misleading description since this isn't just applying to browsers. It's also everything else.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3921)*

**Comment by dcramer** [comment]
Review status: 27 of 29 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/sentry/filters/legacy_browsers.py, line 17 \[r7\]](https://reviewable.io:443/reviews/getsentry/sentry/3921#-KPKGu1LQ8JKreCwI3aR:-KPKKgAxNbilAv36SLHA:b-f72irf) ([raw file](https://github.com/getsentry/sentry/blob/f96e707cb27d221fe47e901bfa9b1f35e0374cec/src/sentry/filters/legacy_browsers.py#L17)):*
<details><summary><i>Previously, mattrobenolt (Matt Robenolt) wrote…</i></summary>
> I don't like this one being enabled by default.
> 
> It's being too aggressive if there's a parser error, or if the value were handled as "Other", etc. Those will all be rejected by default and I don't think that's good behavior. There's lots of weird browsers that are legitimate and they don't mean "Legacy".
> 
> In this case, aren't a lot of Opera browsers being tracked as "Other"? They'd all be dropped here 100% by default.
> 
> This will be double bad since this is also being applied to all events, and not just JavaScript. Most http clients aren't going to be setting legit User-Agents that map up to browsers, which means everything is going to be ignored.
</details>
We dont reject 'Other' by default.

I dont think theres any safety concerns about leaving this enabled as a default, as the browsers we're rejecting are versions which dont support stacktraces correctly.

---

*[src/sentry/filters/web_crawlers.py, line 16 \[r7\]](https://reviewable.io:443/reviews/getsentry/sentry/3921#-KPKIGdxrZYg2SBjyJ0F:-KPKKwMV42mI8yTIDMqz:bsl0usi) ([raw file](https://github.com/getsentry/sentry/blob/f96e707cb27d221fe47e901bfa9b1f35e0374cec/src/sentry/filters/web_crawlers.py#L16)):*
<details><summary><i>Previously, mattrobenolt (Matt Robenolt) wrote…</i></summary>
> I don't know enough, but are we sure "Google" anywhere in the User-Agent isn't too aggressive? I'm not sure if it's possible for that string to exist in like, Chrome or anything outside of being a bot. Again, I am concerned since this is going to be enabled by default, and we'll basically never figure out why something is being filtered.
</details>
default is a mistake here. Chrome doesn't have "google" in the user agent:

https://developer.chrome.com/multidevice/user-agent

---

*[src/sentry/filters/web_crawlers.py, line 37 \[r7\]](https://reviewable.io:443/reviews/getsentry/sentry/3921#-KPKIstgac3WyOVUH6oO:-KPKL6MwZt_QiQF71r4k:b-aiw2yh) ([raw file](https://github.com/getsentry/sentry/blob/f96e707cb27d221fe47e901bfa9b1f35e0374cec/src/sentry/filters/web_crawlers.py#L37)):*
<details><summary><i>Previously, mattrobenolt (Matt Robenolt) wrote…</i></summary>
> I think this is misleading description since this isn't just applying to browsers. It's also everything else.
</details>
im assuming you didnt mean to make this comment here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3921)*

**Comment by mattrobenolt** [comment]
Review status: 27 of 29 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/sentry/filters/legacy_browsers.py, line 17 \[r7\]](https://reviewable.io:443/reviews/getsentry/sentry/3921#-KPKGu1LQ8JKreCwI3aR:-KPKLZACFnIwGYQZ3Pow:b-1nd4rs) ([raw file](https://github.com/getsentry/sentry/blob/f96e707cb27d221fe47e901bfa9b1f35e0374cec/src/sentry/filters/legacy_browsers.py#L17)):*
<details><summary><i>Previously, dcramer (David Cramer) wrote…</i></summary>
> We dont reject 'Other' by default.
> 
> I dont think theres any safety concerns about leaving this enabled as a default, as the browsers we're rejecting are versions which dont support stacktraces correctly.
</details>
Can we apply this to only JavaScript errors then like we do on the one? I don't see much value in even having this rule for server-side stuff.

---

*[src/sentry/filters/web_crawlers.py, line 37 \[r7\]](https://reviewable.io:443/reviews/getsentry/sentry/3921#-KPKIstgac3WyOVUH6oO:-KPKLm0YomY6xj4SWZh_:b-oawh03) ([raw file](https://github.com/getsentry/sentry/blob/f96e707cb27d221fe47e901bfa9b1f35e0374cec/src/sentry/filters/web_crawlers.py#L37)):*
<details><summary><i>Previously, dcramer (David Cramer) wrote…</i></summary>
> im assuming you didnt mean to make this comment here
</details>
Why didn't I? The description says "Some crawlers may try to parse and execute JavaScript, but in an incompatible way which then triggers an error.". But this rule is being applied to more than just JavaScript. If we limited this to just javascript, it'd be more accurate.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3921)*

**Comment by dcramer** [comment]
Review status: 27 of 29 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/sentry/filters/legacy_browsers.py, line 17 \[r7\]](https://reviewable.io:443/reviews/getsentry/sentry/3921#-KPKGu1LQ8JKreCwI3aR:-KPKNZBfYg-2ARHtgCGi:b679u4c) ([raw file](https://github.com/getsentry/sentry/blob/f96e707cb27d221fe47e901bfa9b1f35e0374cec/src/sentry/filters/legacy_browsers.py#L17)):*
<details><summary><i>Previously, mattrobenolt (Matt Robenolt) wrote…</i></summary>
> Can we apply this to only JavaScript errors then like we do on the one? I don't see much value in even having this rule for server-side stuff.
</details>
AS3? CSP?

---

*[src/sentry/filters/web_crawlers.py, line 37 \[r7\]](https://reviewable.io:443/reviews/getsentry/sentry/3921#-KPKIstgac3WyOVUH6oO:-KPKNdiZGhkSB8pRow61:bw5q1fy) ([raw file](https://github.com/getsentry/sentry/blob/f96e707cb27d221fe47e901bfa9b1f35e0374cec/src/sentry/filters/web_crawlers.py#L37)):*
<details><summary><i>Previously, mattrobenolt (Matt Robenolt) wrote…</i></summary>
> Why didn't I? The description says "Some crawlers may try to parse and execute JavaScript, but in an incompatible way which then triggers an error.". But this rule is being applied to more than just JavaScript. If we limited this to just javascript, it'd be more accurate.
</details>
i'll just remove 'javascript' then, as crawlers also cause server-side errors

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3921)*

**Comment by mattrobenolt** [comment]
Review status: 27 of 29 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/sentry/filters/legacy_browsers.py, line 17 \[r7\]](https://reviewable.io:443/reviews/getsentry/sentry/3921#-KPKGu1LQ8JKreCwI3aR:-KPKNyY9-gMHbRS_Bzwb:bk9qsu5) ([raw file](https://github.com/getsentry/sentry/blob/f96e707cb27d221fe47e901bfa9b1f35e0374cec/src/sentry/filters/legacy_browsers.py#L17)):*
<details><summary><i>Previously, dcramer (David Cramer) wrote…</i></summary>
> AS3? CSP?
</details>
It won't apply to CSP, at least not as of yet. CSP already does it's own filtering based on features. Like, certain keys must exist, etc, etc.

And for AS3... I can't tell what User-Agent it uses. I can only find information for a non-browser instance. I can test if you want and figure it out. But it's small enough share that I don't think it's significant to address specially.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3921)*

**Comment by mattrobenolt** [comment]
Review status: 27 of 29 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/sentry/filters/web_crawlers.py, line 37 \[r7\]](https://reviewable.io:443/reviews/getsentry/sentry/3921#-KPKIstgac3WyOVUH6oO:-KPKPpLLAHsi9atsqQgb:bmwv7si) ([raw file](https://github.com/getsentry/sentry/blob/f96e707cb27d221fe47e901bfa9b1f35e0374cec/src/sentry/filters/web_crawlers.py#L37)):*
<details><summary><i>Previously, dcramer (David Cramer) wrote…</i></summary>
> i'll just remove 'javascript' then, as crawlers also cause server-side errors
</details>
Yeah, I think that's reasonable. I agree that this rule should apply to both server and client.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3921)*

**Comment by mitsuhiko** [comment]
Reviewed 11 of 20 files at r1, 1 of 3 files at r4, 1 of 1 files at r5, 11 of 16 files at r6, 2 of 2 files at r7, 3 of 3 files at r8.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3921)*

**Comment by dcramer** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/sentry/filters/legacy_browsers.py, line 17 \[r7\]](https://reviewable.io:443/reviews/getsentry/sentry/3921#-KPKGu1LQ8JKreCwI3aR:-KPZ3EqOOBxtdul_5_9A:b-896fix) ([raw file](https://github.com/getsentry/sentry/blob/f96e707cb27d221fe47e901bfa9b1f35e0374cec/src/sentry/filters/legacy_browsers.py#L17)):*
<details><summary><i>Previously, mattrobenolt (Matt Robenolt) wrote…</i></summary>
> It won't apply to CSP, at least not as of yet. CSP already does it's own filtering based on features. Like, certain keys must exist, etc, etc.
> 
> And for AS3... I can't tell what User-Agent it uses. I can only find information for a non-browser instance. I can test if you want and figure it out. But it's small enough share that I don't think it's significant to address specially.
</details>
Done.

---

*[src/sentry/filters/web_crawlers.py, line 37 \[r7\]](https://reviewable.io:443/reviews/getsentry/sentry/3921#-KPKIstgac3WyOVUH6oO:-KPZ3GLe4h1R_zHdnK9N:b-896fix) ([raw file](https://github.com/getsentry/sentry/blob/f96e707cb27d221fe47e901bfa9b1f35e0374cec/src/sentry/filters/web_crawlers.py#L37)):*
<details><summary><i>Previously, mattrobenolt (Matt Robenolt) wrote…</i></summary>
> Yeah, I think that's reasonable. I agree that this rule should apply to both server and client.
</details>
Done.

---

*[tests/sentry/filters/test_legacy_browsers.py, line 39 \[r7\]](https://reviewable.io:443/reviews/getsentry/sentry/3921#-KPKHICPj3AnFBfU2VpG:-KPZ3GtJvz1CIKUzI7pj:b-896fix) ([raw file](https://github.com/getsentry/sentry/blob/f96e707cb27d221fe47e901bfa9b1f35e0374cec/tests/sentry/filters/test_legacy_browsers.py#L39)):*
<details><summary><i>Previously, dcramer (David Cramer) wrote…</i></summary>
> fwiw ua-parser has these tests -- my goal was basically to prove a couple of the checks
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3921)*

**Comment by mattrobenolt** [comment]
Reviewed 8 of 13 files at r9.
Review status: 30 of 34 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3921)*

**Pull request merged**
