### PR TITLE
ref(spotlight): Remove all Spotlight related code

### PR DESCRIPTION
**Pull request by BYK**
Python SDK now has support for `SENTRY_SPOTLIGHT` env variable support so removing anything we have added here specifically. Also removing the 'default on' behavior as it is creating more confusion than usefulness.

### CODE REVIEW

**Review by JoshFerge — COMMENTED** [review]
what about the frontend js code that references spotlight?

**Review by sl0thentr0py — APPROVED** [review]

**Comment by BYK** [comment]
@JoshFerge 
>what about the frontend js code that references spotlight?

Good catch, updated the code.

Also what's with the test failures?

**Review by JoshFerge — APPROVED** [review]

**Review by sl0thentr0py — APPROVED** [review]

**Comment by JoshFerge** [comment]
unsure about the test failure. also it wants us to split up the frontend/backend changes. not sure if it matters in this case.

**Comment by BYK** [comment]
The split thing is just a warning as far as I can tell. We're fine with that in this case. I'll see what the test failures are about later on.

**Pull request merged**
