### PR TITLE
chore(migrations): Use FlexibleForeignKey for PlatformExternalissue.group

### PR DESCRIPTION
**Pull request by saifelse**
This change is a preparatory refactor to simplify the backfill migration
for PlatformExternalissue.project_id to be introduced in #21860.

### CODE REVIEW

**Review by scefali — COMMENTED** [review]
LGTM but we should get the parent PR merged before approving this. Also want one of the migration owners to take a look.

**Comment by saifelse** [comment]
@scefali : (from PR TODO): Is it known that the corresponding Group still exists, or is there a chance it got deleted? If it's not guaranteed to exist, should I avoid adding the FlexibleForeignKey... or was an FFK intended to handle this case?

**Comment by mattrobenolt** [comment]
db_constraint=False means the database won't enforce the relationship. This ends up purely being in Python so you can do the normal query syntax and relationship traversals.

**Comment by saifelse** [comment]
> `db_constraint=False` means the database won't enforce the relationship. This ends up purely being in Python so you can do the normal query syntax and relationship traversals.
> 
> But code that uses this should absolutely guard against a `Group.DoesNotExist` when necessary because there are no guarantees.

@mattrobenolt : Thanks. This change was a preparatory refactor for #21860 to backfill PlatformExternalIssue.project_id. If in practice (i.e. in prod sentry.io database) every PlatformExternalIssue has a Group that still exists, it seems nice to be able to make the project non-nullable (after verifying that this is the case). However, it seems since we can't verify if this condition happens to be true for all self-hosted sentry databases if this scenario is actually expected to happen under normal operations of running Sentry... so it seems like I should just get rid of making PlatformExternalIssue.project_id non-nullable. Does that sound right to you?

**Comment by mattrobenolt** [comment]
It definitely needs to be left nullable.

**Review by wedamija — APPROVED** [review]
Just to be overcautious, here's the generated raw sql:
```
BEGIN;
--
-- Custom state/database change combination
--
COMMIT;
```

lgtm, I'll merge shortly

**Pull request merged**
