### PR TITLE
feat(slack): Show culprit in notifications

### PR DESCRIPTION
**Pull request by olagjo**
Relates to/part of #30164 (which has absorbed #26006). 

This adds a context-like culprit-block directly under the title, which mirrors how the culprit is presented in the web UI.

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Comment by olagjo** [comment]
I see that this is red, but I believe that it is only because I am missing some permissions as an outsider, and an employee needs to allow some of the checks to run?

**Review by iamrajjoshi — COMMENTED** [review]
@olagjo thanks for the PR! Could you add a screen shot on how the notification looks after these changes?

**Comment by olagjo** [comment]
Hi! Of course! 
<pre align="center"></pre>
<pre align="center"></pre>

**Comment by iamrajjoshi** [comment]
Thanks for your work here!, I am gonna toss this behind a feature flag and get this reviewed by the team 🙌🏽

**Comment by olagjo** [comment]
Thank you! I will just close this PR then and follow-up discussion can happen on yours :)

**Pull request closed without merging**
