### PR TITLE
test(hc): Refactor and simplify overriding of silo settings

### PR DESCRIPTION
**Pull request by RyanSkonnord**

### CODE REVIEW

**Comment by RyanSkonnord** [comment]
Pursuant to the eventual goal of having undecorated tests run as though decorated with `@region_silo_test` by default. Simplified and extracted some of the setting overrides, with the hope of pulling them into the general test environment setup (and then probably undoing them when a non-region decorator is present, including the "include monolith run" tests). See https://github.com/getsentry/sentry/pull/60923 as part of the same investigation.

Also some incidental refactoring that I did as part of my overall process.

**Review by corps — COMMENTED** [review]
I like the direction so far.

**Comment by RyanSkonnord** [comment]
With [ab61e2b](https://github.com/getsentry/sentry/pull/60924/commits/ab61e2bb2c0752ee48895ff9367749c310236ec8), I'm trying to solve the problem that breaks tests when I do [this](https://github.com/getsentry/sentry/pull/60923/commits/1c4e69c4474afbd021e29231e8b9142c9621ccbf). The gist is that we're dependent on `override_regions` (not merely `override_settings`) to keep `get_local_region()` well-behaved. We need to do *that* because we might be calling `get_local_region()` no matter what silo mode the test actually runs in, because of the `with assume_test_silo_mode(SiloMode.REGION)`s all over the place.

Basically, my strategy at the moment is:
1. Front-load all of the times we look at Django settings into the construction of the `RegionDirectory` object, so that we can swap it cleanly and not peek at settings at unexpected times.
2. Give `get_local_region()` a sensible fallback in case of a missing `SENTRY_REGION` value, but only in the test environment. My expectation is that region-silo tests will load the default region map, and in other test cases it Just Works.

(Currently we have `SENTRY_REGION = "us"` by default in the test environment. That's causing me more inconvenience than it prevents and I'd like to make it `None`.)

**Comment by RyanSkonnord** [comment]
Superseded by https://github.com/getsentry/sentry/pull/61331 and https://github.com/getsentry/sentry/pull/61500.

**Pull request closed without merging**
