### PR TITLE
Add encoding to human log lines.

### PR DESCRIPTION
**Pull request by JTCunning**
@getsentry/infrastructure

### CODE REVIEW

**Comment by mattrobenolt** [comment]
:cookie:

**Comment by mitsuhiko** [comment]
Why are we forcing things to bytes and not leave them as unicode? That's weird.

**Comment by mitsuhiko** [comment]
NO COOKIE

**Comment by JTCunning** [comment]
No reason other than "This does not break things anymore." Open to suggestions on how to approach this.

**Comment by mitsuhiko** [comment]
@JTCunning everything should be unicode or made unicode.

In your case you already have unicode everywere but the format string. If you use new style formatting (`.format`) then you need to make the string unicode: `u'foo'.format(things, that, are unicode here)`. If you use `%` formatting then the string upgrades to unicode as needed if it's ascii only.

**Comment by mitsuhiko** [comment]
@JTCunning generally anything that is text we should treat as unicode and only ever encode when we hit an IO layer.

**Pull request merged**
