### PR TITLE
chore(sdk): Set `project_root` to `/usr/src`

### PR DESCRIPTION
**Pull request by sentrivana**
Query source detection via the SDK isn't working properly in our sentry/getsentry production setup. This might be due to `project_root` not being set since our frame picking logic only takes into account frames coming from files that start with `project_root` (which, if unset, is set to current working directory when the SDK initializes). In this PR we're setting `project_root` explicitly to `/usr/src`.

### CODE REVIEW

**Review by gggritso — APPROVED** [review]
👍🏻

**Review by antonpirker — APPROVED** [review]

**Comment by asottile-sentry** [comment]
I think this will break `self-hosted` which does not live at that path -- CC @getsentry/open-source

**Comment by asottile-sentry** [comment]
I would prefer reverting personally -- and instead working on the sdk to get this right since it'll be a problem for customers as well (and they're less likely to find this option than us)

**Comment by asottile-sentry** [comment]
I'm not even sure `/usr/src` makes sense as a project root either -- there's two project roots for `getsentry` (one for `sentry` and one for `getsentry`)

**Comment by hubertdeng123** [comment]
What part of self-hosted would we expect this to break? Looks like our integration tests ran with the `sentry` image from 5 hours ago successfully:
https://github.com/getsentry/self-hosted/actions/runs/7474599040

**Comment by asottile-sentry** [comment]
I'm not exactly sure -- I think the in-app frame classification might be incorrect for things reported from self-hosted

**Comment by hubertdeng123** [comment]
Ah ok, that workflow is untested

**Pull request merged**
