### PR TITLE
ref(migration): update Group.message value with Group.data.metadata.title value for perf issues

### PR DESCRIPTION
**Pull request by barkbarkimashark**
Related to this [PR](https://github.com/getsentry/sentry/pull/41048)

For perf issues, `Group.message` value isn't very useful for searching. They look like the transaction 'location'. This PR updates the message value with the Performance issue group title after detection occurs.

### CODE REVIEW

**Review by wedamija — COMMENTED** [review]
Oof, this is a tricky migration because we don't have an index directly on `Group.type`, and iterating over all 240mm rows will take a long time.

I'm wondering if we should do this like:
 - Mark this migration as dangerous so that it will run in ST and self-hosted, and not in saas. (Do we even have performance issues enabled elsewhere? If not, then we could just skip this migration entirely)
 - Run a query on redash to get all the existing groups that are performance issues, then write a separate script in getsentry to update just those rows. Since we're already writing these rows correctly at the moment it doesn't matter if the list is out of date.

**Comment by barkbarkimashark** [comment]
> Oof, this is a tricky migration because we don't have an index directly on `Group.type`, and iterating over all 240mm rows will take a long time.
> 
> I'm wondering if we should do this like:
> 
>     * Mark this migration as dangerous so that it will run in ST and self-hosted, and not in saas. (Do we even have performance issues enabled elsewhere? If not, then we could just skip this migration entirely)
> 
>     * Run a query on redash to get all the existing groups that are performance issues, then write a separate script in getsentry to update just those rows. Since we're already writing these rows correctly at the moment it doesn't matter if the list is out of date.

I tried querying for the Groups table for perf issues, but redash basically span for 25+ mins and I lost hope it would return anything. 

An alternative I thought up was querying snuba for transactions with `notEmpty` group_ids to get the list of Groups for the getsentry migration.

**Comment by wedamija** [comment]
> > Oof, this is a tricky migration because we don't have an index directly on `Group.type`, and iterating over all 240mm rows will take a long time.
> > I'm wondering if we should do this like:
> > ```
> > * Mark this migration as dangerous so that it will run in ST and self-hosted, and not in saas. (Do we even have performance issues enabled elsewhere? If not, then we could just skip this migration entirely)
> > 
> > * Run a query on redash to get all the existing groups that are performance issues, then write a separate script in getsentry to update just those rows. Since we're already writing these rows correctly at the moment it doesn't matter if the list is out of date.
> > ```
> 
> I tried querying for the Groups table for perf issues, but redash basically span for 25+ mins and I lost hope it would return anything.
> 
> An alternative I thought up was querying snuba for transactions with `notEmpty` group_ids to get the list of Groups for the getsentry migration.

Redash will eventually succeed, you can just leave it running. Maybe just do a count first to see how many ids it's going to return, just in case the number of returned results is too large for the redash server to keep in memory. Once you know the counts, you can also just ask ops to run that query and save the result as csv to be used in the migration.

**Comment by barkbarkimashark** [comment]
> 

Lol, the count was the one that ran for 25+ minutes. But fair enough, I'll leave the query in the background and see whether it returns anything.

**Comment by barkbarkimashark** [comment]
> > 
> 
> Lol, the count was the one that ran for 25+ minutes. But fair enough, I'll leave the query in the background and see whether it returns anything.

The redash counts query return with about 90k+ rows - that's a lot of rows .. @wedamija do we have a sample migration that follows this pattern of querying from a hard-coded list of Ids?

**Comment by wedamija** [comment]
> > > 
> > 
> > 
> > Lol, the count was the one that ran for 25+ minutes. But fair enough, I'll leave the query in the background and see whether it returns anything.
> 
> The redash counts query return with about 90k+ rows - that's a lot of rows .. @wedamija do we have a sample migration that follows this pattern of querying from a hard-coded list of Ids?

We don't have a script that follows this specific pattern, but here's an example script we've used in getsentry before: https://github.com/getsentry/getsentry/blob/f3971ee8cbe10714c764fd11fb796782135bf430/bin/subscription-migrate.py
You can use this as a template.

The number of rows isn't too bad, the migration won't take long to run once we have all the ids. What we should do here is have ops run a query directly on redash to get all the group ids and just dump to a file in some format (csv?). Then you can do something like
```
group_ids = <read file>
for group_id in group_ids:
    <do update>
```

**Comment by beezz** [comment]
> > > > 
> > > 
> > > 
> > > Lol, the count was the one that ran for 25+ minutes. But fair enough, I'll leave the query in the background and see whether it returns anything.
> > 
> > 
> > The redash counts query return with about 90k+ rows - that's a lot of rows .. @wedamija do we have a sample migration that follows this pattern of querying from a hard-coded list of Ids?
> 
> We don't have a script that follows this specific pattern, but here's an example script we've used in getsentry before: https://github.com/getsentry/getsentry/blob/f3971ee8cbe10714c764fd11fb796782135bf430/bin/subscription-migrate.py You can use this as a template.
> 
> The number of rows isn't too bad, the script won't take long to run once we have all the ids. What we should do here is have ops run a query directly on redash to get all the group ids and just dump to a file in some format (csv?). Then you can do something like
> 
> ```
> group_ids = <read file>
> for group_id in group_ids:
>     <do update>
> ```

I like the option with csv script for this case 👍 

Another option would be to iterate over projects and prefilter by project id. Similar to what we do in the cleanup script ~ https://github.com/getsentry/sentry/blob/master/src/sentry/runner/commands/cleanup.py#L326-L358

**Review by wedamija — COMMENTED** [review]
Actually... since `organizations:performance-issues` is False by default, it means no one using self-hosted or ST actually has performance issues. So we could probably just skip this migration altogether and just rely on the backfill script to fix sentry.io

**Pull request closed without merging**
