### PR TITLE
feat(ui): added Flex Component

### PR DESCRIPTION
**Pull request by priscilawebdev**
**Type:** Feature

**Description:**

I believe that the Flexible Box Layout Module makes it easier to design flexible responsive layout structure and we were in need of a Flex component of our own.

This Draft PR introduces a Flex Component .

**Future implementation:**

At the moment, this component is not responsive as it should be, but this functionality will be introduced in another upcoming PR. So, you can use something like:

`<Flex display={['flex', 'inline-flex']}>{children}</Flex>`

where each position in the array represents a breakpoint with the rule to be used

Please, let me know your thoughts on this

### CODE REVIEW

**Comment by EvanPurkhiser** [comment]
We’re actually actively trying to phase out a library that we currently use which provides something similar to this: https://github.com/jxnblk/reflexbox

We’ve been favoring making simple semantic styled components that have their respective flex properties on them instead of using components like this.

I can add more context, but just writing on my phone right now

**Comment by priscilawebdev** [comment]
@EvanPurkhiser thank you for the feedback. 

I'd love to know why you preferred not to have a Flex component anymore... I particularly find this component very useful

maybe we can discuss more about it during the TSC meeting 😉

**Comment by EvanPurkhiser** [comment]
Let's discuss in the TSC meeting :)

**Comment by priscilawebdev** [comment]
closed for now :)

**Pull request closed without merging**
