### PR TITLE
feat(onboarding): Update NextJS onboarding page

### LINKED ISSUE #60054: DSN in Installation
### Problem

When onboarding to Next.js, we don’t show the DSN in the UI

Image

If you are using a repo that already has Sentry configured and you just need a DSN, then you have to go to the settings for that project and copy that.

### ACs
Include the DSN in the instructions explicitly.

### PR DESCRIPTION
**Pull request by roggenkemper**
this pr updates the NextJS onboarding page in a few ways. First, it correctly groups all the information about the Sentry wizard into one section. Second, it separates our the alternate method while adding in the project's DSN for users who just need to get that, since their application already has the rest of the starter code for Sentry. Third, it cleans up the bullet points of what the Wizard does and fixes a typo. 

Screenshot 2023-11-17 at 11 34 57 AM

Closes https://github.com/getsentry/sentry/issues/60054

### CODE REVIEW

**Comment by roggenkemper** [comment]
making a draft pr to gather feedback on design / copy of the updated page

**Comment by rachrwang** [comment]
Nice work!!

**Review by scttcper — APPROVED** [review]

**Comment by ale-cota** [comment]
hey, @roggenkemper! Thanks for working to improve this :) I have one concern I wanted to voice about this revamp and that is the fact that it now basically puts the two options - using the Sentry wizard or doing the setup manually - almost on the same level. I think we have a clear preference for customers to use the wizard because it is less error prone, takes care of setting up source maps, etc. Manual setup is really just an option for edge cases where someone really doesn't want to use a wizard. 

You can see that in the previous version this isn't the case, it's really more of a footnote.
Screenshot 2023-11-17 at 10 44 08

This update still puts the wizard first (which is good), but definitely makes the manual option much more visible. Just wanted to put this out there (also FYI, @rachrwang). Thanks!

**Comment by roggenkemper** [comment]
> hey, @roggenkemper! Thanks for working to improve this :) I just have one concern I wanted to voice about this revamp and that is the fact that it now basically puts the two options - using the Sentry wizard or doing the setup manually - almost on the same level. I think we have a clear preference for customers to use the wizard because it is less error prone, takes care of setting up source maps, etc. Manual setup is really just an option for edge cases where someone really doesn't want to use a wizard.
> 
> You can see that in the previous version this isn't the case, it's really more of a footnote. Screenshot 2023-11-17 at 10 44 08
> 
> This update still puts the wizard first (which is good), but definitely makes the manual option much more visible. Just wanted to put this out there (also FYI, @rachrwang). Thanks!

@ale-cota thanks for the feedback, i definitely agree and had this concern as well. i'll spend some more time today trying to think of a way to de-emphasize the "manual setup" portion

**Review by scttcper — APPROVED** [review]

**Pull request merged**
