### PR TITLE
Format javascript stackstraces after submission

### PR DESCRIPTION
**Pull request by ChadKillingsworth**
Raven.js goes through numerous hoops to standardize browser stack traces prior to sending to Sentry. The downfall of this method is that the source code needed is rather large.

This PR allows passing the unformatted stack property on an JS error object as an extra and allowing Sentry to format the stacktrace. This allows the client code to be significantly reduced in size.

### CODE REVIEW

**Comment by dcramer** [comment]
To be perfectly honest I'm kind of in favor of this for JS if w can ensure adequate information to process the trace back when it's sent. It's definitely the opposite stance of what we've done in the past but soon sentry will support platform specific preprocessing layers and this kind of thinking fits in well there. 
Not to mention we already have a ton of "if JavaScript" hacks. 






On Fri, Jan 2, 2015 at 2:22 PM -0800, "Chad Killingsworth" <notifications@github.com> wrote:












Raven.js goes through numerous hoops to standardize browser stack traces prior to sending to Sentry. The downfall of this method is that the source code needed is rather large.



This PR allows passing the unformatted stack property on an JS error object as an extra and allowing Sentry to format the stacktrace. This allows the client code to be significantly reduced in size.



You can merge this Pull Request by running
  git pull https://github.com/ChadKillingsworth/sentry parse-raw-js-stack


Or view, comment on, or merge it at:


  https://github.com/getsentry/sentry/pull/1363

Commit Summary

  For javascript events, allow submitting the raw stack in the 'extras' field and parse the value in sentry.
  Fix lint errors.
  Add unit tests - and fix case where column number isn't provided.


File Changes

  
    M
    src/sentry/tasks/fetch_source.py
    (104)
  
  
    M
    tests/sentry/tasks/fetch_source/tests.py
    (98)
  


Patch Links:

  https://github.com/getsentry/sentry/pull/1363.patch
  https://github.com/getsentry/sentry/pull/1363.diff

**Comment by mattrobenolt** [comment]
Not sure I 100% agree. I have plans in raven-js to extract more data out of the running environment to augment the frames. We wouldn't be able to do this if we moved the handling purely to the server.

Like, fetching function arguments, a trace of events that led up to the exception, etc.

**Comment by mattrobenolt** [comment]
Also, raven.js is only 5KB. Not sure that's big enough to worry about bloat IMO.

**Comment by ChadKillingsworth** [comment]
I'm not advocating changing Raven.js - I simply wish to have my own very lite client. I could also handle this myself if there was a "preprocess" plugin interface.

**Comment by dcramer** [comment]
@ChadKillingsworth I added a hook for the preprocessors. I like the idea of breaking our platform specific logic into there. Let me know if that sounds good to you.

**Comment by ChadKillingsworth** [comment]
Yes that makes much more sense than a bunch of "if javascript" style code. It'll help with future PRs. I'm needing custom logic for obtaining source maps and so that will dovetail nicely. I'll refactor my code and work this into a plugin - which I hope to be able to open source (still waiting to here about the details of that from my employer).

**Pull request closed without merging**
