### PR TITLE
feat(backend): Create an endpoint to return if a user has access to projects

### PR DESCRIPTION
**Pull request by davidenwang**
On all of the frontend pages there is a `<NoProjectMessage>` component which uses `organization.projects` to detect if a user has access to any projects. With the change to make organization details lighter (exclude `teams` and `projects` inside organization) it would be useful for an endpoint to return the information necessary to render `<NoProjectMessage>` instead of having to wait for all projects in the organization to load. I tried to mimic the functionality of `<NoProjectMessage>` with this endpoint.

https://github.com/getsentry/sentry/blob/ea2dfd3f078848a8b1864637a839eedc941108ba/src/sentry/static/sentry/app/components/noProjectMessage.tsx#L37-L42

### CODE REVIEW

**Comment by wedamija** [comment]
This is a pretty specific endpoint. Could we use `OrganizationProjectsEndpoint` with `per_page=1` instead?

**Comment by davidenwang** [comment]
> This is a pretty specific endpoint. Could we use `OrganizationProjectsEndpoint` with `per_page=1` instead?

Mmmm yea that seems to be fine. Does the endpoint get all projects in an organization or just the organizations that the user has access to via team membership? I had a look at the endpoint and it seems like it gets all projects in the organization but wanted to confirm.

**Comment by billyvg** [comment]
Yeah I don't think they are 100% equivalent

**Comment by wedamija** [comment]
> Yeah I don't think they are 100% equivalent

I think it's equivalent. For an authenticated user it will filter the projects like
`queryset = Project.objects.filter(organization=organization).prefetch_related("teams")`. It will then apply `query` if passed, which we won't be. It adds a couple of extra fields, but this should be equivalent. If we find that using this is slow for some reason I'd say we could parameterize this endpoint further to remove extra calls (like the call to bookmarks).

**Comment by davidenwang** [comment]
> > Yeah I don't think they are 100% equivalent
> 
> I think it's equivalent. For an authenticated user it will filter the projects like
> `queryset = Project.objects.filter(organization=organization).prefetch_related("teams")`. It will then apply `query` if passed, which we won't be. It adds a couple of extra fields, but this should be equivalent. If we find that using this is slow for some reason I'd say we could parameterize this endpoint further to remove extra calls (like the call to bookmarks).

Ahhh gotcha okay sweet I think that should be good then. I'll switch out the frontend to using that endpoint.

**Comment by billyvg** [comment]
What about for superusers?

**Comment by davidenwang** [comment]
> What about for superusers?

If there is no way to determine superuser from the backend we could have the frontend conditionally request with query ?allProjects=1 to mimic the super user being able to see all projects

**Comment by wedamija** [comment]
> What about for superusers?

What issues do you see for superusers in that endpoint?

**Comment by billyvg** [comment]
@davidenwang you could prob rework this PR for InstallPromptBanner though yeah?

**Pull request closed without merging**
