### PR TITLE
add chinese translation

### PR DESCRIPTION
**Pull request by huanz**

### CODE REVIEW

**Comment by getsentry-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by mattrobenolt** [comment]
Hey, thanks for the contribution, but unfortunately, our translations come through Transifex: https://www.transifex.com/getsentry/sentry/

So we can’t accwpt any changes here. If we do, they’d just be clobbered the next time we synced with Transifex. If you’d like, we would happily accept the translation over there.

**Comment by huanz** [comment]
@mattrobenolt ok, i have applied for it

**Comment by huanz** [comment]
@mattrobenolt how can i add translate msgid eg: [Queue  #Overview](https://github.com/getsentry/sentry/pull/6650/files#diff-e473bf13cbc48056a9c9a72f7ba443d5R821)

[Buffers](https://github.com/getsentry/sentry/pull/6650/files#diff-f71d923e68823bbbcb1062ac4145a18aL18)

**Pull request closed without merging**
