### PR TITLE
array index of instead of includes

### PR DESCRIPTION
**Pull request by MaxBittker**
this was annoying IE11 users because it used Array.includes 
fixes JAVASCRIPT-21V

### CODE REVIEW

**Review by macqueen — APPROVED** [review]
i think you might wanna keep the `fixes JAVASCRIPT-21V` in the title if you're gonna squash and merge so it'll get auto resolved by the release

**Comment by mattrobenolt** [comment]
@macqueen They work anywher ein the body. Doesn't have to be in the title.

**Comment by macqueen** [comment]
@mattrobenolt are you sure? we only check the commit message (see https://github.com/getsentry/sentry/blob/master/src/sentry/models/commit.py#L57) and it doesn't look like github includes the pr description as the message, for example, the message for this commit https://github.com/getsentry/sentry/pull/5796 is just `add todo for logging of discarded hash (#5796)` and doesn't include the body/description

**Comment by mattrobenolt** [comment]
Sorry, I meant the body of the commit. I never put these in the title itself since I feel that's clunky.

I'd do like:

```
Doing the thing

Fixes XXXX
```

**Comment by mattrobenolt** [comment]
In the case here: https://github.com/getsentry/sentry/commit/6934851b1a64b5bad36cd088b52ce2445f01758d it's being repeated twice in the message now. :)

**Pull request merged**
