### PR TITLE
fix(perf-setting): Disable form submit on enter

### PR DESCRIPTION
**Pull request by shruthilayaj**
Hitting enter after changing a form field re-submits
the form. Fixed it by adding type="button" so that
hitting enter now only updates the field and displays
any error messages related to it correctly.

Fixes github [issue](https://github.com/getsentry/sentry/issues/28074)

### CODE REVIEW

**Review by k-fish — COMMENTED** [review]
What kind of element is it that you need to specify the type? I think the button components changes elements under the hood based on what props get passed.

**Comment by dashed** [comment]
@k-fish I think it's an anchor link if you don't specify the type.

**Comment by shruthilayaj** [comment]
> What kind of element is it that you need to specify the type? I think the button components changes elements under the hood based on what props get passed.

It's a button, but from what I understand, `type` [defaults to submit](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-type) (so when a user changes a field and hits enter, it submits and reloads the whole page and the context around the error is lost)

**Review by k-fish — APPROVED** [review]
👍

**Pull request merged**
