### PR TITLE
ref(dashboards): Prebuilt issue widget remove assignee_or_suggested condition and fixed count field

### PR DESCRIPTION
**Pull request by edwardgou-sentry**
Feedback on prebuilt issue widget, we want Issues to be cross team so removing the assignee_or_suggested condition for now

Also changed the count field to events (new name)

### CODE REVIEW

**Comment by edwardgou-sentry** [comment]
@jas-kas

**Review by shruthilayaj — APPROVED** [review]
do we need to update the docs 😛

**Comment by edwardgou-sentry** [comment]
> do we need to update the docs 😛

😆  true, let me put up a pr

**Comment by edwardgou-sentry** [comment]
Docs pr https://github.com/getsentry/sentry-docs/pull/4654

**Pull request merged**
