### PR TITLE
feat(ui): Allow explicit alert icon centering

### PR DESCRIPTION
**Pull request by evanpurkhiser**

### CODE REVIEW

**Review by billyvg — COMMENTED** [review]
I feel like we have gone back and forth with centering in this component. What happens if text wraps?

**Comment by EvanPurkhiser** [comment]
> This is explicitly JUST for cases where we have a single line that is larger than our usual line height.

**Comment by billyvg** [comment]
@EvanPurkhiser Yeah but there's no way to identify in code if the text were to wrap? Can we add some explicit comments in the prop docs, as well as a storybook story for this?

**Comment by BYK** [comment]
Closing due to staleness and conflicts.

**Pull request closed without merging**
