### PR TITLE
build(jest): Upgrade jest to 24.8.0

### PR DESCRIPTION
**Pull request by billyvg**
See changelog: https://github.com/facebook/jest/blob/master/CHANGELOG.md

### CODE REVIEW

**Review by evanpurkhiser — APPROVED** [review]
Any significant changes?

**Comment by billyvg** [comment]
Didn't see any, but something definitely changed with module resolution -- had to change some things w/ moment-timezone

**Comment by billyvg** [comment]
Sigh, this warning keeps getting thrown:

```

**Comment by billyvg** [comment]
Warnings might be due to https://github.com/babel/babel/issues/10264 which is fixed in https://github.com/babel/babel/pull/10302

**Review by markstory — APPROVED** [review]

**Comment by billyvg** [comment]
Closing in favor of https://github.com/getsentry/sentry/pull/15533

**Pull request closed without merging**
