### PR TITLE
test(js): Use jest mock fns in API Client mock

### PR DESCRIPTION
**Pull request by billyvg**
`addMockResponse` now returns a jest mock function that represents
`Client.request` calls. Now we can write assertions with jest matchers
for Client.request.

### CODE REVIEW

**Comment by getsentry-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Review by MaxBittker — APPROVED** [review]
I'm slightly inclined to use an object over a "tuple" but this looks nice! good idea.

**Comment by MaxBittker** [comment]
just because it's harder to remember the order and it can be awkward to destructure the second one only

**Comment by billyvg** [comment]
`let [,mock] = ...`?

Agree on order, feel free to change, it's an internal API so I just did whatever

**Pull request merged**
