### PR TITLE
Ignore API Origin check when using ApiKey/ApiToken for auth

### LINKED ISSUE #3722: DELETE release using an Auth Token errors
It appears that we have an implicit assumption that this endpoint requires a browser session since we're erroring on a CSRF check.

See: SENTRY-HP

### PR DESCRIPTION
**Pull request by mattrobenolt**
Fixes GH-3722

@getsentry/api

---

This change is [Reviewable](https://reviewable.io/reviews/getsentry/sentry/3738)

### CODE REVIEW

**Comment by mitsuhiko** [comment]
Request: can we move this into an utility function? We have the same stuff in the sudo check and they already dsynched once before.

**Comment by mitsuhiko** [comment]
Also BTW we have a third request thing: the global access key.

**Comment by mattrobenolt** [comment]
I'm going to expand this a bit more because we have an explicit test that checks CORS for `Basic` auth. Which, this test doesn't break since it never checks the 40x path. :) But it seems like there was an explicit reason to use this for an ApiKey. So I'm going to change this to only check against ApiToken.

**Comment by mitsuhiko** [comment]
-1 for changing this. Thinking about this more this would break the entire point of the origin check. A client should not send an Origin if it's not a browser.

**Comment by mattrobenolt** [comment]
Yeah, agreed. This is bad. Thanks for sanity checking. :)

**Pull request closed without merging**
