### PR TITLE
feat(replay): Add "Method" column to Network table and allow filtering by that value

### PR DESCRIPTION
**Pull request by billyvg**
Add 'method' column to the left, defaulting to 'GET' for the css/img/js asset requests.

SCR-20230504-kfgm

Relates to https://github.com/getsentry/team-replay/issues/35

### CODE REVIEW

**Comment by billyvg** [comment]
cc @Jesse-Box - I kind of wish we scrunched up the status + method columns here to have fixed widths based on size of content instead of header (and just have header overflow with ellipsis). I feel like most people would infer the column type based on content.

**Comment by Jesse-Box** [comment]
> cc @Jesse-Box - I kind of wish we scrunched up the status + method columns here to have fixed widths based on size of content instead of header (and just have header overflow with ellipsis). I feel like most people would infer the column type based on content.

@billyvg I'm totally fine with you doing this. Would it be a pain in the arse, to make these columns draggable? At least then, the use can get more clarity of the titles.

**Review by ryan953 — APPROVED** [review]

**Comment by ryan953** [comment]
I kinda stole the PR and made two changes:
1. Put the column on the very left, so the order is `[method] [status] [url] [type]`
2. Add a dropdown filter

The dropdown filter takes up a bunch of space, but I think I can followup with changes to all tabs that makes the dropdowns smaller (pixels wise) and actually easier to use (fewer clicks)

**Comment by billyvg** [comment]
+1 to merge... though we really need resizable cols here because path keeps getting harder to read.

I think ideally I would smush non-path columns to be the width of its content cells *ignoring* the header (force headers to be ellipsed). Content will give you enough context as to what the column type is (provided we fill in the data for status code 😬 ).

**Comment by ryan953** [comment]
@billyvg resizable cols followup: https://github.com/orgs/getsentry/projects/23/views/29?pane=issue&itemId=27392039

**Pull request merged**
