### PR TITLE
chore(deps): Remove unused gettext-parser

### PR DESCRIPTION
**Pull request by evanpurkhiser**
We do not directly use this at all

### CODE REVIEW

**Review by scttcper — APPROVED** [review]

**Comment by EvanPurkhiser** [comment]
Hmm, apparently it's needed.. for something?

**Review by priscilawebdev — APPROVED** [review]

**Comment by priscilawebdev** [comment]
https://github.com/getsentry/sentry/commit/419db707eb63f90da049acda3aa822a2f0ba9c0b

**Comment by EvanPurkhiser** [comment]
afaict it's a dependency here https://github.com/getsentry/sentry/blob/4f3267456c1376c6444af9ce6fd2398f629f3bad/yarn.lock#L4280

**Comment by EvanPurkhiser** [comment]
Will deal with it later I think this has it as a dep but it's a devDependency

https://github.com/getsentry/sentry/blob/17f8591ef190b0c865a13c4271320655266ca0a2/package.json#L154

When it probably shouldn't be.

**Comment by EvanPurkhiser** [comment]
Actually tbh maybe not. I'm not sure lol

**Pull request closed without merging**
