### PR TITLE
fix(dashboard-layout): Increase hovered widget z-index to prevent hidden tooltip

### PR DESCRIPTION
**Pull request by narsaynorath**
With CSS transforms being applied to the grid items, they're creating
new stacking contexts and so the tooltip z-index: 999999 is being
ignored across grid items. This results in tooltips being partially covered
by the next widget.

Assigning a higher z-index to the currently hovered widget fixes this
because it (and its children) gains priority over the other widgets in the layout.

### CODE REVIEW

**Comment by JonasBa** [comment]
@narsaynorath would it be feasible to render the tooltip inside the transformed element instead? That way it would just get added to the new stacking context and we wouldn't have to handle this case.

**Comment by narsaynorath** [comment]
> @narsaynorath would it be feasible to render the tooltip inside the transformed element instead? That way it would just get added to the new stacking context and we wouldn't have to handle this case.

Hi @JonasBa! The tooltips do render as children of the transformed element, but because each stacking context shares the same priority for z-index, I believe the z-index on the tooltip is ignored and the calculation on what to show in front falls back to the order of elements in the DOM.

Here's a screenshot where the HTML elements are higher up in the children array, showing it becomes hidden:
Screen Shot 2021-12-09 at 10 33 11 AM

and here's one of the last element, showing it doesn't become hidden
Screen Shot 2021-12-09 at 10 38 32 AM

This gave me two ideas, if I switch off CSSTransforms then the stacking context for the grid items never gets created and the z-index of the tooltip is respected, but the UX and performance is degraded imo. Another solution was to increase the z-index of a widget temporarily while hovering, causing the widget and its tooltip to take priority. This seems to work well for now.

I just learned about stacking contexts the other day so if I've said anything incorrect and you have a suggestion on something to investigate then please let me know!

**Comment by JonasBa** [comment]
@narsaynorath yeah, you are absolutely correct about the z-index, one thing to note is that a similar bug can occur if the grid items just have position:relative.

There is also another solution where you render the tooltip in the parent container of the grid item and rely on the placement engine of the tooltip to absolutely position it on the page where it should sit. I've previously used Tippy and it supports `appendTo` prop, a quick google search shows up something similar where someone used a React portal to achieve this - https://github.com/Hacker0x01/react-datepicker/issues/1366

I think your solution is fine and we probably shouldn't overthink it, but these kind of hacks usually stick around the codebase for too long as they are scary to remove and just prone to just living in our codebase rent free forever (You can search for the word hack in the codebase :D). 

Btw, it looks like the backend part of the codebase and partly frontend uses a `HACK: ` style comment, so I would just stick to that, small change but hopefully it makes it easier to track this down in the future.

Aaaaaaand I just noticed I reviewed a draft PR... Sorry if this was too soon, I havent noticed

**Comment by narsaynorath** [comment]
Going with this z-index fix for now. I made a ticket to track suggestions for alternative solutions because I think they require more time.

**Review by shruthilayaj — APPROVED** [review]

**Pull request merged**
