### PR TITLE
feat(api): Add `sudo` API endpoint

### PR DESCRIPTION
**Pull request by billyvg**
Also, change `sudo_required` decorator's http resp to 403

### CODE REVIEW

**Comment by getsentry-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Changes require @getsentry/security sign-off</td>
    </tr>
  </tbody>
</table>

### Security concerns found

- src/sentry/api/endpoints/sudo.py


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Review by mattrobenolt — COMMENTED** [review]
How does this work with the frontend? Today, you're able to `sudo` through Yubikey as an alternative for password. Also, what about accounts that don't have passwords? Like SAML or SSO? (I'm not actually sure how we handle this today elsewhere, we probably skip the feature is my guess since we can't do anything additional)

**Comment by dcramer** [comment]
Ideally we could pop a window (same way we do oauth modals) that just does the 'sudo' auth flow (and defers to the server on it). The window can callback/close same way as oauth, and then the UI can assume its been upgraded, and re-send a request.

**Comment by billyvg** [comment]
I'm working on frontend PR right now, but basically in `api.jsx` it will check for a 403 + `sudoRequired: true` in response and then open a modal asking for password. On success, will reattempt previous API request.

Currently it looks like we have a middleware that assumes users without a password have su access https://github.com/getsentry/sentry/blob/master/src/sentry/middleware/sudo.py#L15

But the API decorator doesn't seem to check for that https://github.com/getsentry/sentry/blob/master/src/sentry/api/decorators.py#L12

**Comment by billyvg** [comment]
Re: yubikey, should I re-use this? https://github.com/getsentry/sentry/blob/master/src/sentry/web/frontend/sudo.py#L16

**Comment by mattrobenolt** [comment]
@billyvg yeah, that all makes sense. :)

**Comment by billyvg** [comment]
Closing in favor of #6727

**Pull request closed without merging**
