### PR TITLE
Register `chrome-extension` as a valid url scheme

### LINKED ISSUE #5459: chrome-extension:// URLs do not resolve source map location properly
When evaluating `sourceMappingURL` directives inside JavaScript files, the source map file URL is resolved relative to the JavaScript file.

Meaning in `http://example.com/static/app.js`, if `//# sourceMappingURL=app.js.map` is found, then the source map is expected to be located at `http://example.com/static/app.js.map`.

This works fine for `http://`, `https://`, `file://` and other standard protocols. But fails for `chrome-extension://` and other non-standard protocols.

The source is [six.moves.urllib.parse](https://docs.python.org/2/library/urlparse.html#urlparse.urljoin), which we use in [javascript/processor.py](https://github.com/getsentry/sentry/blob/master/src/sentry/lang/javascript/processor.py#L190):

```python
from six.moves.urllib.parse import urljoin

urljoin('http://example.com/app/app.js', 'app.js.map')
# result => 'http://example.com/app/app.js.map'

urljoin('chrome-extension://hgfakmfpmkaaamdjfolpjgdofepbfhke/static/app.js', 'app.js.map')
# result => 'app.js.map'
```

cc @mitsuhiko @MaxBittker @benvinegar

### PR DESCRIPTION
**Pull request by mattrobenolt**
Fixes GH-5459

@MeredithAnya were there other protocols that we should add here?

### CODE REVIEW

**Comment by MaxBittker** [comment]
this is going to break some people's source map workarounds. it's a good idea in the long run but might cause some pain

**Comment by MeredithAnya** [comment]
@MaxBittker at least we will know why their workaround doesn't work anymore :)

**Comment by tranotheron** [comment]
How guys. And how it's going with this PR? :-)

**Review by mitsuhiko — APPROVED** [review]
I'm okay with that for now.

**Pull request merged**
