### PR TITLE
ref(ui): Incremental upgrade to react-select to v3

### PR DESCRIPTION
**Pull request by evanpurkhiser**
Upgrades the SelectControl to use react-select v3. This is a breaking change for many of our components, so a deprecatedSelectControl prop is added to use the old v1 version of the SelectControl.

This flag should be incrementally dropped until we have no more usages of our legacy react select control, at which point we can remove the legacy component and `react-select-legacy` package.

### CODE REVIEW

**Comment by dashed** [comment]
@EvanPurkhiser this PR diff is so long 😱

**Comment by EvanPurkhiser** [comment]
This has some stuff in it it shouldn't it looks like

**Review by billyvg — COMMENTED** [review]
What do we gain here by adding in react select but still using the legacy library as well?  How does this affect our bundle size?

**Comment by EvanPurkhiser** [comment]
> What do we gain here by adding in react select but still using the legacy library as well? How does this affect our bundle size?

I can't convert all of these at once, there's a lot of prop renames that happened in v2 that I want to make sure I individually get right on each select control. A lot of our selects should be pretty easy to convert, just remove the legacy prop and verify it's working. But some other controls are a lot more difficult because some specific APIs for option filtering were changed.

I'm not sure how this affects the bundle size. I could look closer into it. How do you feel about the general approach here though?

**Comment by billyvg** [comment]
Ah sorry didn't read the PR description first... yeah I think it will be helpful to compare bundle sizes -- I agree with the approach to incrementally migrate the component usage over. My biggest concern will be with how integrations currently use the field and how we can be confident when changing those integrations.

**Comment by EvanPurkhiser** [comment]
> how integrations currently use the field and how we can be confident when changing those integrations.

Agreed, that's tricky for select2 stuff as well, I believe we still have that roaming around.

**Comment by scefali** [comment]
@EvanPurkhiser Looks like these changes are clashing with my ongoing changes to convert some select based components in `components/forms` to TS. I will halt my work there until we figure out what we're going here. BTW, you have some merge conflicts.

**Comment by EvanPurkhiser** [comment]
This is ready to go aside from this eslint error.

**Comment by EvanPurkhiser** [comment]
Would like to merge this soon @billyvg

**Comment by billyvg** [comment]
Can we do the bundle size comparisons?

We may need to slap eslint disables for finddomnode too

**Comment by EvanPurkhiser** [comment]
With react-select v3:
image

Without react-select v3:
image

Doesn't look like it adds much bloat, likely from gzip compression.

**Comment by priscilawebdev** [comment]
Wow this PR is large, but completely understandable... I like the idea of  the gradually migration..the difference between the size of the two packages is not that much...I believe it is ok . I'll do CR as soon as I have some time 😉

**Review by billyvg — APPROVED** [review]
This looks good to me, let's get some documentation up on the frontend guide and maybe slap an eslint rule that points to it

**Pull request merged**
