### PR TITLE
chore(py3): remove utf-8 coding comments

### PR DESCRIPTION
**Pull request by joshuarli**
See https://github.com/getsentry/sentry/pull/23506#discussion_r568135817.

The eventual goal is to prep the codebase to add `pyupgrade`.

Oh, this is a better regex, taken from PEP 263: `rg -tpy '^[ \t\f]*#.*?coding[:=][ \t]*([-_.a-zA-Z0-9]+)'`

### CODE REVIEW

**Review by evanpurkhiser — APPROVED** [review]
good

**Comment by EvanPurkhiser** [comment]
Will new migrations still add it?

**Comment by joshuarli** [comment]
> Will new migrations still add it?

No, it got removed from `SENTRY_MIGRATION_TEMPLATE`. I generated a migration to verify, there's a newline I'll remove for cosmetics.

**Pull request merged**
