### PR TITLE
ref(js): Remove jQuery from the SPA completely

### PR DESCRIPTION
**Pull request by evanpurkhiser**
Believe it or not this can land.

There is no getsentry or sentry usage _outside_ of plugins, which import it themselves:

- Bootstrap is gone
- _admin no longer uses any jQuery

https://github.com/getsentry/sentry/blob/0699160f3723f1577c0b834d40ea57e62235be41/src/sentry/templates/sentry/plugins/bases/issue/create_issue.html#L15

https://github.com/getsentry/sentry/blob/0699160f3723f1577c0b834d40ea57e62235be41/src/sentry_plugins/jira_ac/templates/base.html#L54

### CODE REVIEW

**Review by dashed — APPROVED** [review]
lfggggggg

**Review by priscilawebdev — APPROVED** [review]
🛳🇮🇹

**Review by k-fish — APPROVED** [review]
🔥

**Comment by JTCunning** [comment]
rip

**Comment by robinrendle** [comment]
Amazing

**Pull request merged**
