### PR TITLE
ref(js): Remove ApiMixin [SEN-212]

### PR DESCRIPTION
**Pull request by billyvg**
WIP -- tests either need to update snapshots and/or export the base component (because of enzyme and testing state, as well as shallow vs mount)

Relates to SEN-212

### CODE REVIEW

**Comment by billyvg** [comment]
@markstory tests are passing (there's a bunch of lint errors, but those should be easy to fix). Do we trust our test coverage? How should we handle this to limit risk and minimize efforts?

**Comment by markstory** [comment]
> Do we trust our test coverage? How should we handle this to limit risk and minimize efforts?

Yes and no. I think the tests we have are good, but we don't have coverage on all these components. We could spend sometime manually ensuring there aren't any warnings/broken screens in staging as a way to reduce risk.

**Comment by billyvg** [comment]
A few of us clicked through this on staging the other day and it seems good

**Review by evanpurkhiser — APPROVED** [review]

**Comment by billyvg** [comment]
There's still a few more cases where my transforms didn't catch it, I'll probably update these manually

**Pull request merged**
