### PR TITLE
chore(tests): Upgrade clickhouse version to match current Production.

### PR DESCRIPTION
**Pull request by JTCunning**

### CODE REVIEW

**Comment by lynnagara** [comment]
By the way where do we define the version for prod?

**Comment by JTCunning** [comment]
Ops repo.

**Review by lynnagara — APPROVED** [review]
Are we dropping the patch number now? Any particular reason for that?

**Comment by JTCunning** [comment]
Their Dockerhub is kind of a mess. They skipped straight over 19.4 patch releases and went to 19.5.

**Pull request merged**
