### PR TITLE
feat(features): Add more feature adoption signals

### PR DESCRIPTION
**Pull request by adhiraj**
Taking over https://github.com/getsentry/sentry/pull/9290 from eric

### CODE REVIEW

**Review by mattrobenolt — COMMENTED** [review]
What are the receivers going to be doing on these? I feel like they should be `send_robust` instead of just `send`, but that depends on what the receivers are going to do.

**Comment by adhiraj** [comment]
they're all going to write to the feature adoption table, and in the future to big query. yeah I was thinking of send_robust but everything except 1 signal uses send() in our code base so wasn't sure

**Comment by mattrobenolt** [comment]
> yeah I was thinking of send_robust but everything except 1 signal uses send() in our code base so wasn't sure

That's not true at all. Most of our signals are send_robust that we use in our application code. The only ones I see that aren't robust are ones that have been added for these kinds of things. So I don't think we should use prior art here as an excuse to continue doing it.

`send_robust` is really important if we think something in a receiver might error. And the question is, do we want the thing to fail... and fail the entire main request? `send` bubbles up the exception from any receiver and causes eveerything to fail.

Whereas `send_robust` swallows it, logs it, and continues on.

**Review by mattrobenolt — APPROVED** [review]
Regardless, I think it's fine. It's up to you to decide if you want send or send_robust. Just please don't break things from a bad receiver in the future.

**Comment by adhiraj** [comment]
where do you see send_robust being used more? misspoke when I said "1 event" -- it's a few events, but quick code search gives me 13 results for send_robust and 71 for send (with half of them being signal-related sends)

Anyway, not to beat a dead horse, I'll change this to send_robust

**Pull request merged**
