### PR TITLE
feat(issue-consumer): make batched parallel mode default

### PR DESCRIPTION
**Pull request by scefali**
Making `batched-parallel` mode default now that it has been rolled out in all env

### CODE REVIEW

**Review by untitaker — APPROVED** [review]

**Review by lynnagara — APPROVED** [review]

**Comment by scefali** [comment]
@snigdhas has the feature stabilized yet? Can this be merged?

**Comment by snigdhas** [comment]
Hey @scefali, not yet - @vartec might have more context here

**Comment by vartec** [comment]
> Hey @scefali, not yet - @vartec might have more context here

I'm about to GA change that re-orders and collapses status changes (https://github.com/getsentry/sentry/pull/72570). As far as I understand that was the thing blocking landing this PR.

**Comment by vartec** [comment]
Working great. Thank you @scefali!

**Pull request merged**
