### PR TITLE
feat(orgdash): Show helpful stuff when org dash empty

### PR DESCRIPTION
**Pull request by adhiraj**
The org dash is kinda useless when an org has 1 project and 0 issues. Put useful stuff / CTAs in there instead.

Before
image

After
image

### CODE REVIEW

**Comment by adhiraj** [comment]
image

**Review by ckj — CHANGES_REQUESTED** [review]
@adhiraj hey, sorry for the hold up here. Some minor feedback about padding (audible groan):

dash-welcome-feedback

tl;dr the images are 10% smaller, and there's some additional padding between the text label and the bottom of the box. Both could probably be achieved by using a combination of [utility classes](https://github.com/getsentry/sentry/blob/master/src/sentry/static/sentry/less/spacing.less).

**Comment by adhiraj** [comment]
How's this (tried a few combinations, this one seemed best)
image

**Comment by adhiraj** [comment]
Bottom padding seems to be a bit larger than your image, but I used the lowest padding possible :/

**Comment by ckj** [comment]
@adhiraj that looks good! @cameronmcefee provided an alternate version of the image you're using for the Docs box that features a slightly less mind-bending perspective: 
[code-arguments-tags-mirrored.svg.zip](https://github.com/getsentry/sentry/files/1873821/code-arguments-tags-mirrored.svg.zip)

Once that's in place i'll 👍.

**Comment by adhiraj** [comment]
Done

**Review by ckj — APPROVED** [review]

**Comment by adhiraj** [comment]
@ckj on a 1280px width (one of percy's 2 standard widths) this is what's happening:
image

is this ok? I looked at the support page and it also has the same problem, but it's not visible there because there are no borders. on this page though borderless looks a little weird:
image

**Comment by ckj** [comment]
@adhiraj Ideally they'd have equal heights. Maybe wrap them in `<div className="flex">` and see if that sorts it out?

**Pull request merged**
