### PR TITLE
fix(ui) Fix tag bars being hidden by tooltip container

### PR DESCRIPTION
**Pull request by markstory**

### CODE REVIEW

**Review by billyvg — APPROVED** [review]
Do our percy snapshots not have tag data in them?

**Review by evanpurkhiser — APPROVED** [review]

**Comment by markstory** [comment]
@billyvg I'm guessing not as the diffs in https://percy.io/getsentry/sentry/builds/1843093 didn't flag tag values as changing.

**Comment by billyvg** [comment]
yeah :/

image

**Comment by markstory** [comment]
@billyvg I'll update our snapshot data once this gets out.

**Pull request merged**
