### PR TITLE
auth: Stop using access_token as a querystring

### PR DESCRIPTION
**Pull request by mattrobenolt**
Ref: https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters

### CODE REVIEW

**Comment by mattrobenolt** [comment]
I don't know if any of this works and don't have a reasonable way to test, I just wanted GitHub to stop emailing me every 3 days about this.

**Comment by scefali** [comment]
@mattrobenolt Looks like this code touches a number of our Github integrations. So someone on our team will have to test out a few of them to make sure it works.

**Comment by mattrobenolt** [comment]
Yup, that's fine.

**Comment by scefali** [comment]
Thanks for all your work on this PR, it was very helpful. I ended up splitting this PR into 4 parts and merged separately. Though in one PR I simply took out the auth that was not needed.
https://github.com/getsentry/sentry/pull/17255
https://github.com/getsentry/sentry/pull/17284
https://github.com/getsentry/sentry/pull/17216
https://github.com/getsentry/sentry/pull/17178

**Pull request closed without merging**
