### PR TITLE
buffers: implementation for generic callbacks

### PR DESCRIPTION
**Pull request by mattrobenolt**
```
>>> buffer.register_cb('foo.bar', do_stuff)
>>> buffer.apply('foo.bar', value='1')
```

/cc @macqueen 

Throwing this up for early feedback on implementation. The idea is that we can buffer multiple calls with a simple argument.

So in our immediate need, we'd want to buffer up calls to the GitHub API. We'd have a simple value, their GitHub username as input.

So we'd use this somethign like:

```python

def github_resolve_username(value):
  # make API call with value (username)

buffer.register_cb('github.resolve_username', github_resolve_username)

buffer.apply('github.resolve_username', value='mattrobenolt')
```

This then piggy backs off normal buffer flushing periodically.

The implementation is a simple redis `SET` since all we care about is unique elements.

TODO: add `__doc__`s and tests if @tkaemming isn't mad about this.

### CODE REVIEW

**Comment by dcramer** [comment]
is this effectively trying to implement debounce?

if so, thoughts on just making this a separate service instead of overloading buffers?

**Comment by mattrobenolt** [comment]
Effectively, yeah.

I could split it out, but seemed to make logical sense to leverage existing buffers code.

If there are strong opinions, I can split this out into it's own app. The part I was trying to avoid was having to have configuration options for yet another thing. Which is a duplicate of the existing `SENTRY_BUFFER_OPTIONS` stuff since we'd want it to share the same cluster. I could reuse `SENTRY_BUFFER_OPTIONS` for this as well, but that seemed weird to have a different app entirely that shared configs from another. And I see in no way would someone configure one without the other. Seems odd.

**Comment by dcramer** [comment]
@mattrobenolt yeah i figured -- it just seems to only reuse a tiny portion of what buffers do, and, while this doesn't matter here likely, breaks compatibility with the service's API contract.

**Comment by mattrobenolt** [comment]
> breaks compatibility with the service's API contract.

That's fair, I can add back a shim with `warnings.warn` calls in the API compat calls. I really don't think it's worth splitting this into it's own entire system since it's not even technically debouncing or throttling. It's definitely buffering.

**Review by tkaemming — CHANGES_REQUESTED** [review]
Bumping this back over to get it out of the bot email.

> if @tkaemming isn't mad about this

I wasn't. 🙂 

I think you mentioned that you're planning on resurrecting this at some point, so just let me know when that is and we can come back to this (assuming you and @dcramer have sorted out your design concerns in the other comments.)

**Comment by BYK** [comment]
Closing due to staleness and reduced importance as we now avoid using buffers as much as we can.

**Pull request closed without merging**
