### PR TITLE
feat(django): pytest startup and test collection on Django 1.11

### PR DESCRIPTION
**Pull request by joshuarli**
At this point, pytest should start and successfully collect all tests on Django 1.11.

### CODE REVIEW

**Comment by joshuarli** [comment]
Decoupling bac7f7bf8c6c9026dea4449de64f415f8caa755b into https://github.com/getsentry/sentry/pull/16115.

**Review by wedamija — APPROVED** [review]
Damn, hopefully not too much work to get this working 🤞 .

Just to be overcautious, let's not merge this until 1.10 is out in production.

**Comment by joshuarli** [comment]
Hmm, had to revert moving pytest_plugins to the root conftest because 

```
INTERNALERROR>   File "/Users/joshua.li/.local/share/virtualenvs/getsentry2/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
INTERNALERROR>     app_config = AppConfig.create(entry)
INTERNALERROR>   File "/Users/joshua.li/.local/share/virtualenvs/getsentry2/lib/python2.7/site-packages/django/apps/config.py", line 90, in create
INTERNALERROR>     module = import_module(entry)
INTERNALERROR>   File "/Users/joshua.li/.local/share/pyenv/versions/2.7.15/lib/python2.7/importlib/__init__.py", line 37, in import_module
INTERNALERROR>     __import__(name)
INTERNALERROR>   File "/Users/joshua.li/dev/sentry/sentry/src/sentry/analytics/__init__.py", line 22, in <module>
INTERNALERROR>     Analytics, get_backend_path(options.get("analytics.backend")), options.get("analytics.options")
INTERNALERROR>   File "/Users/joshua.li/dev/sentry/sentry/src/sentry/options/manager.py", line 131, in get
INTERNALERROR>     opt = self.lookup_key(key)
INTERNALERROR>   File "/Users/joshua.li/dev/sentry/sentry/src/sentry/options/manager.py", line 105, in lookup_key
INTERNALERROR>     raise UnknownOption(key)
INTERNALERROR> UnknownOption: 'analytics.backend'
```

In getsentry. Oh well.

**Comment by joshuarli** [comment]
@wedamija Verified `LAST_VERIFIED_DJANGO_VERSION`.

Looks like the migration template didn't change in Django 1.11, so no changes required to `SENTRY_MIGRATION_TEMPLATE`.

I then followed the exact procedure I did as described here: https://github.com/getsentry/sentry/pull/15399#issue-335598538

**Pull request merged**
