### PR TITLE
feat(discover): updates discover results page table to use events instead of eventsv2

### PR DESCRIPTION
**Pull request by edwardgou-sentry**
Updates the Discover results page to use the new `events/` endpoint when feature flagged with `discover-frontend-use-events-endpoint`.

Also duplicated results page tests to test for using `events/` endpoint.

Will probably break and need a follow up when the following backend prs are merged:
https://github.com/getsentry/sentry/pull/34835
https://github.com/getsentry/sentry/pull/34801

### CODE REVIEW

**Review by narsaynorath — APPROVED** [review]
Looks good to me. Looked at the tests locally and it makes sense you made two describe blocks and assigned the feature flag to the new set of tests.

**Review by priscilawebdev — APPROVED** [review]
code looks good to me.

**Comment by edwardgou-sentry** [comment]
Rerequesting review. Some changes that were made:
- updated to support the new `meta` signature from the `events` endpoint
- updated to support `events` endpoint result using full equation keys instead of equation aliases
- fixed tests to match new `events` signature

**Review by wmak — APPROVED** [review]
Only reviewed commits since last approval, but LGTM

**Pull request merged**
