### PR TITLE
Show org sidebar on team edit page

### PR DESCRIPTION
**Pull request by benvinegar**
After:

image

/cc @getsentry/product @ckj

### CODE REVIEW

**Comment by dcramer** [comment]
Needs an obvious way back to the list of projects/teams

**Comment by benvinegar** [comment]
> Needs an obvious way back to the list of projects/teams

The "Projects & Teams" link on the left? To get here, they had to have clicked that to begin with, so they should be familiar with it.

**Comment by dcramer** [comment]
@benvinegar when a link is active its not obvious thats how you click it to get back. We're building an application not a website. You dont click a navigation header in an application to get back to whatever you were originally on. This is the same confusion people have with the "Issues" link being how you get back to the list of Issues.

**Comment by benvinegar** [comment]
I mean, GitHub has many, many examples of this paradigm, and nobody really complains about that.

But sure, I can add a "Back to Projects & Teams" link. Or I can arbitrarily make this a modal again.

**Comment by benvinegar** [comment]
@dcramer – mind taking another look and signing off?

**Review by dcramer — APPROVED** [review]

**Pull request merged**
