### PR TITLE
Revert "feat(IntegrationDirectory): Add category selector to filter integrations"

### PR DESCRIPTION
**Pull request by NisanthanNanthakumar**
Reverts getsentry/sentry#17852

### CODE REVIEW

**Comment by EvanPurkhiser** [comment]
I think we can roll-forward instead of reverting. Should be a relatively easy fix

**Comment by scefali** [comment]
@NisanthanNanthakumar what happened? I am generally in favor of rolling back and then applying the fix.

**Comment by NisanthanNanthakumar** [comment]
> @NisanthanNanthakumar what happened? I am generally in favor of rolling back and then applying the fix.

@scefali @EvanPurkhiser and @billyvg said I can just roll-forward and apply a fix.

**Comment by scefali** [comment]
@NisanthanNanthakumar Ok sure, let's roll forward. But I'm still unclear what broke.

**Comment by NisanthanNanthakumar** [comment]
> @NisanthanNanthakumar Ok sure, let's roll forward. But I'm still unclear what broke.

@scefali From my understanding, the use of `grid` in the css is causing issues in percy. So I'm going to replace it with `flex`.

**Comment by EvanPurkhiser** [comment]
image

Check out the search input in the before after

**Comment by EvanPurkhiser** [comment]
@NisanthanNanthakumar : You can just render a empty `<div />` when the sorter is disabled, causing the search to be in the correct grid cell.

**Pull request closed without merging**
