### PR TITLE
feat(plugins): mail support ssl 

### PR DESCRIPTION
**Pull request by Jetsly**

### CODE REVIEW

**Comment by mattrobenolt** [comment]
This won’t work with our version of Django.

**Comment by mattrobenolt** [comment]
At least I don’t think so? Were you able to test this?

**Comment by Jetsly** [comment]
yes，i find will work on Django >= 1.7
https://docs.djangoproject.com/en/1.7/ref/settings/#email-use-ssl

**Comment by Jetsly** [comment]
but you project is Django>=1.6.11,<1.7

**Pull request closed without merging**
