### PR TITLE
feat: Added basic support for event attachment retention

### PR DESCRIPTION
**Pull request by mitsuhiko**
This is the initial support for custom attachment retention.

### CODE REVIEW

**Comment by mitsuhiko** [comment]
@mattrobenolt i think we should still merge this

**Comment by mattrobenolt** [comment]
This doesn't really do anything except filter on read? Is this valuable then? Assuming it is since you're pinging about it. But this seems like something we'd want to also include as a part of cleanup or some kind of deletion, otherwise this is just an cosmetic thing.

**Comment by mitsuhiko** [comment]
@mattrobenolt cleanup already happens as part of the normal cleanup procedure which has a different retention window anyways. However this would make this pattern consistent with the way we handle precise retention for the API for the event code paths.

**Review by mattrobenolt — APPROVED** [review]
Yeah, I know cleanup happens on the normal retention window, but ideally we'd want to cleanup to match this artificial limit.

🍕

**Comment by mitsuhiko** [comment]
TBF I just kicked the can down the road. This is just a copy paste of the pattern for event retention :)

Ideally we would have a system in place that controls this better (how do we do this for single tenant?)

**Pull request closed without merging**
