### PR TITLE
Updated Onboarding Docs for Maven Plugin

### PR DESCRIPTION
**Pull request by lbloder**
Updates Onboarding Docs for Kotlin/Java to use sentry-maven-plugin.

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Comment by ArthurKnaus** [comment]
Tests are failing as they check for the version number of `sentry.java.mavenplugin` being rendered. (which was wrong to begin with as it does not exist and always falls back to `0.0.4`). The tests only work because we add it by mocking...
This PR switches to rendering the correct entry of the release registry (`sentry.java.maven-plugin`).
@lbloder pls adjust the test in https://github.com/lbloder/sentry/blob/f524d64015c8dc694a866c1fdd23cf227d5b0e7d/static/app/gettingStartedDocs/java/spring-boot.spec.tsx#L9

```ts
renderWithOnboardingLayout(docs, {
  releaseRegistry: {
    'sentry.java.spring-boot.jakarta': {
      version: '2.99.9',
    },
    'sentry.java.maven-plugin': {
      version: '3.99.9',
    },
  },
  selectedOptions: {
    packageManager: PackageManager.MAVEN,
  },
});
```

cc @adinauer

**Comment by lbloder** [comment]
Thank you for pointing that out @ArthurKnaus.
Tests are fixed.
I also removed the Version switch for `spring-boot` as it does not make a difference when using our plugin to install.

Also streamlined the structure of the docs between `spring` and `spring-boot`

**Review by adinauer — APPROVED** [review]
LGTM

**Review by ArthurKnaus — APPROVED** [review]

**Pull request merged**
