### PR TITLE
Add ProGuard parser.

### PR DESCRIPTION
**Pull request by tkaemming**
This adds a module for parsing ProGuard mapping files.

### CODE REVIEW

**Comment by tkaemming** [comment]
So, the current situation with this PR: this adds the ability to parse a ProGuard mapping file (used primarily with Android to my knowledge, but can work with any other Java deployment) in Python. This has a few advantages over using [retrace](https://www.guardsquare.com/en/proguard/manual/retrace), which is the tool typically used to deobfuscate stack traces:

1. We don't have to spin up an entire JVM (or do IPC with something like [nailgun](https://github.com/martylamb/nailgun) to avoid VM startup overhead) to process these stack traces.
2. We don't have to stringify the stacktrace interface, process it, and then parse it back to an interface again.

I wasn't planning on adding this to CHANGES, because it doesn't have any user-facing effects (and right now you can only use it to validate a `mapping.txt` file via `python -m sentry.lang.java.proguard.parser`.

As a follow up, I'll add a PR for indexing the mapping file and add a `ProGuardDeobfuscationPlugin` for transforming the stack trace interface(s), but I'd like to keep these patches separate. There are also probably some design decisions that need to be made around things like reprocessing that need to be made before that plugin is ready to go.

**Comment by mitsuhiko** [comment]
Given some of the proguard files I found on basic googling it sounds like we would hit the same issue with this as with sourcemaps and dsyms. This probably should not be done in Python but I did not bench it yet.

**Comment by tkaemming** [comment]
I agree there would be more efficient and faster implementations, but considering the difference in volume of errors received between source mapped JavaScript events and Java events obfuscated with ProGuard I wasn't particularly concerned with optimizing this until it manifested itself as an issue.

**Comment by mitsuhiko** [comment]
I agree but we should not go down the path where we create an api that cannot be optimized later. We had major problems refactoring the sourcemap thing. So ideally we end up with a similar setup where there is one object that you create from X with one method to look up a token and the rest is internal and implementation defined.

**Comment by tkaemming** [comment]
The indexing component you're talking about isn't part of this pull request.

This implementation doesn't preclude swapping out the parser, either.

**Comment by mitsuhiko** [comment]
Yeah, this is just to make sure we don't repeat this :)

**Pull request closed without merging**
