### PR TITLE
feat(am2): Add project to the blended sample rate function

### PR DESCRIPTION
**Pull request by wmak**
- Without this we can't change the blended sample rate per project

### CODE REVIEW

**Review by k-fish — APPROVED** [review]
Is this why checks against projects in the sample rate function weren't working? 👍

**Comment by iambriccardo** [comment]
Hi, this function won't achieve what you might expect. The `project` is used to get the organization id in case no `organization_id` is supplied. It's not the most pragmatic function signature, I am aware.

Definition is here: https://github.com/getsentry/getsentry/blob/114f2afaa986d3d5c8d70ee7c9a8f84e64ac9233/getsentry/quotas.py#L835-L835

**Comment by wmak** [comment]
@iambriccardo isn't that overriden by https://github.com/getsentry/getsentry/blob/114f2afaa986d3d5c8d70ee7c9a8f84e64ac9233/getsentry/quotas_override.py#L168 which does use the project

**Comment by iambriccardo** [comment]
> @iambriccardo isn't that overriden by [getsentry/getsentry@`114f2af`/getsentry/quotas_override.py#L168](https://github.com/getsentry/getsentry/blob/114f2afaa986d3d5c8d70ee7c9a8f84e64ac9233/getsentry/quotas_override.py#L168) which does use the project

Ah yeah, are you adding the projects to that list?

**Comment by wmak** [comment]
@iambriccardo yep https://github.com/getsentry/getsentry/blob/master/getsentry/quotas_override.py#L188-L198

**Comment by iambriccardo** [comment]
> @iambriccardo yep [getsentry/getsentry@`master`/getsentry/quotas_override.py#L188-L198](https://github.com/getsentry/getsentry/blob/master/getsentry/quotas_override.py?rgh-link-date=2024-06-18T13%3A36%3A01Z#L188-L198)

Ah okay great! All good

**Pull request merged**
