### PR TITLE
Mail: prefix with tags

### PR DESCRIPTION
**Pull request by zacharya19**
This change is [Reviewable](https://reviewable.io/reviews/getsentry/sentry/3956)

### CODE REVIEW

**Comment by dcramer** [comment]
Please provide more information on what this change is intended to do

**Comment by zacharya19** [comment]
This is a little feature for the mail alert.
In the project settings you can set "%tag%" and it will be replaced with the content of the tag, so in this way for example you can see the level on the mail subject.

**Comment by mattrobenolt** [comment]
fwiw, I'm -0 on doing this, especially in this implementation. If anything, we could leverage normal python formatting instead of inventing our own syntax. Something maybe like:

```python
tags = {}
if 'event' in context:
    tags = dict(context['event'].get_tags())

subject_prefix = self.get_option('subject_prefix', project) or self._subject_prefix()
try:
    subject_prefix = subject_prefix.format(tags=tags)
except Exception:
    pass
```

That'd allow the subject_prefix to be `foo {tags[level]}`

**Comment by dcramer** [comment]
My concerns are still the same as always: tags are for an individual events, and alerts are primarily about an aggregate.

**Comment by zacharya19** [comment]
Got it.
Any better idea?

**Comment by mitsuhiko** [comment]
For what it's worth if we want to use this, we should probably use a similar trick we do elsewhere where instead of failing we fill in placeholders for missing values.

**Comment by zacharya19** [comment]
@mitsuhiko Not sure I understood.

**Comment by zacharya19** [comment]
Sentry has support for this now, so I'm closing it.

**Pull request closed without merging**
