### PR TITLE
ci(github): Add eslint fixer

### PR DESCRIPTION
**Pull request by billyvg**
Changes our eslint action to use https://github.com/getsentry/action-eslint-fix which runs `eslint --fix` on files changed in PR and commits the changes for you.

### CODE REVIEW

**Comment by priscilawebdev** [comment]
@billyvg please, what do you want to achieve here? I noticed that you removed semicolons ... is that right?

**Comment by EvanPurkhiser** [comment]
@priscilawebdev I think this isn't quite ready for any kind of review yet.

I think this is a github action that will auto-fix PRs with eslint errors

**Comment by billyvg** [comment]
@priscilawebdev yeah sorry just testing stuff (:

**Comment by billyvg** [comment]
Note: this does not run eslint on the entire codebase like previously, do we still want that as well? cc @getsentry/app-frontend

**Comment by dashed** [comment]
@billyvg I prefer eslint to fix on newer PRs.

**Review by dashed — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
