### PR TITLE
feat(ecosystem): Include error level in Segment data

### PR DESCRIPTION
**Pull request by chrismdp**
So that we can filter out less worrying log levels in our segment destinations, we include log level in the integration with Segment.

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Comment by scttcper** [comment]
could you take a look at fixing the test?

**Comment by chrismdp** [comment]
> could you take a look at fixing the test?

@scttcper hopefully that should do it! Let me know if you'd like further changes

**Review by scttcper — APPROVED** [review]

**Pull request merged**
