### PR TITLE
feat(perf): Update components to use CommitterStore

### PR DESCRIPTION
**Pull request by leedongwei**
Depends on #20725

### CODE REVIEW

**Review by priscilawebdev — COMMENTED** [review]
it looks good to me. is it still work in progress?

**Comment by leedongwei** [comment]
Oops, I've removed the WIP tag. This PR is ready for review.

**Review by priscilawebdev — APPROVED** [review]
Nice work 👏

**Comment by leedongwei** [comment]
Rebased onto `master`

**Pull request merged**
