### PR TITLE
fix(ui): Remove old blue/green/yellow/red colors

### PR DESCRIPTION
**Pull request by robinrendle**
Removing more old color variables.

### CODE REVIEW

**Review by billyvg — COMMENTED** [review]
Hmm typescript has caught a few instances, I wonder if there are non-ts files that have been missed as well

**Comment by robinrendle** [comment]
@billyvg Those should be fixed now.

**Review by markstory — COMMENTED** [review]
You might also need to update snapshots in getsentry for this as you're changing the theme object which invariably breaks snapshots.

**Comment by billyvg** [comment]
This looks good, like mark said we should check for snapshot changes in getsentry.

**Review by billyvg — APPROVED** [review]
getsentry PR looks good, we may want to rebase with master before merging to make sure nothing snuck-in between the last rebase (since we are removing theme keys that can break things).

**Comment by robinrendle** [comment]
@billyvg The getsentry branch landed so this should be good to go now!

**Review by priscilawebdev — APPROVED** [review]

**Pull request merged**
