### PR TITLE
fix(ui): rename/simplify settings nav labels

### PR DESCRIPTION
**Pull request by ckj**
fixes [APP-129](https://getsentry.atlassian.net/secure/RapidBoard.jspa?rapidView=11&projectKey=APP&view=planning&selectedIssue=APP-129) and [APP-182](https://getsentry.atlassian.net/secure/RapidBoard.jspa?rapidView=11&projectKey=APP&view=planning&selectedIssue=APP-182)

Are there other changes we want to make here? E.g. I think there is some confusion around having a **Teams** nav item at both the organization and project level. At the team level, should it say **Associated teams** or something a little more descriptive?

@benvinegar

### CODE REVIEW

**Comment by billyvg** [comment]
What about "Team Management" for org teams?

**Comment by benvinegar** [comment]
I like "Associated Teams" or "Project Teams" (a little shorter).

**Comment by benvinegar** [comment]
Sorry, also don't rename "Data" to "Client". We'll leave that for now (spoke w/ David about this like a month ago).

**Comment by ckj** [comment]
Heads up: since [APP-129](https://getsentry.atlassian.net/secure/RapidBoard.jspa?rapidView=11&projectKey=APP&view=planning&selectedIssue=APP-129) and [APP-182](https://getsentry.atlassian.net/secure/RapidBoard.jspa?rapidView=11&projectKey=APP&view=planning&selectedIssue=APP-182) are language fixes, I've went ahead and addressed them both in this PR.

**Review by benvinegar — APPROVED** [review]

**Pull request merged**
