### PR TITLE
Fix alerts on legacy pages

### LINKED ISSUE #1984: Green notification bar cannot be closed on some pages

### PR DESCRIPTION
**Pull request by benvinegar**
- Moves success alert on account details into nav header (with other alerts)
- Fixes alerts on non-React pages not dismissable

Fixes #1984, #1878

### CODE REVIEW

**Comment by benvinegar** [comment]
Before:

image

After:

image

**Comment by mattrobenolt** [comment]
Does this fix clicking the "x" too?

**Comment by dcramer** [comment]
This wont fix clicking the X as thats an issue with the component.

lgtm

**Comment by mattrobenolt** [comment]
Looks like it does.

**Comment by benvinegar** [comment]
> Fixes alerts on non-React pages not dismissable

Yes.

> This wont fix clicking the X as thats an issue with the component.

These are non-React alerts.

**Comment by ckj** [comment]
Can we hide the 'x' on these then?

**Pull request merged**
