### PR TITLE
fix(replays): adjust replay issue

### PR DESCRIPTION
**Pull request by JoshFerge**
- [x] change issue title
- [x] move from "warning" level, to "error" level.

### CODE REVIEW

**Comment by ryan953** [comment]
Will making it an error help to associate it with replays?

**Review by ryan953 — APPROVED** [review]

**Review by billyvg — APPROVED** [review]

**Comment by JoshFerge** [comment]
> Will making it an error help to associate it with replays?

hmm i'm not sure -- maybe? we shall see.

**Comment by billyvg** [comment]
I think it'll help tell users to go fix it (maybe)

**Comment by bruno-garcia** [comment]
> Will making it an error help to associate it with replays?

I believe we filter by `level` so might do the job

**Pull request merged**
