### PR TITLE
feat(perf-issues): Add issue type to latest

### PR DESCRIPTION
**Pull request by wmak**
- this adds the issue type to the latest event endpoint too so that it can be used to determine how we want to display the span evidence preview

### CODE REVIEW

**Comment by gggritso** [comment]
🤔 question/comment!

1. A transaction can have N problems on it. Having a single `perfProblem` is an artificial limit, so adding an `issueType` field I think is a little janky?
2. If this is for setting up conditionals on the FE, why is `perfProblem.type` not sufficient? Adding more type-like fields (on top of the existing `type` is a bit confusing
3. If that's not sufficient, why not use `perfProblem.title`?

**Comment by wedamija** [comment]
> 🤔 question/comment!
> 
> 1. A transaction can have N problems on it. Having a single `perfProblem` is an artificial limit, so adding an `issueType` field I think is a little janky?
There's an assumption here that a `GroupEvent` is passed when these events are associated with a performance issue. `GroupEvents` bind a transaction to a specific group, so the issue type is roughly the same as returning the problem here. I wonder if we should return the issue type as part of the perf problem though to at least keep it contained

**Comment by wmak** [comment]
1. Agreed moved the type into the perf problem instead
2. perfProblem.type is the enum value (eg. `1008`) which the frontend doesn't have a mapping for, and I think we should probably just translate that on the backend anyways
3. 🤔 It just feels janky to me to use title when we already have the concept of "issueType"s

**Comment by gggritso** [comment]
@wedamija @wmak 🙏🏻 reasonable!

**Review by gggritso — APPROVED** [review]
👍🏻

**Pull request merged**
