### PR TITLE
build(yarn): Upgrade yarn to 1.16.0, embed in repo

### PR DESCRIPTION
**Pull request by BYK**
The best way to install yarn in repos like this is to use the single
JS file version from GitHub instead of installing it via npm. An
even better way is to embed this file in the repo and add a yarn-path
directive to the `.yarnrc` file to ensure everyone always uses the same
yarn version for this repo at all times.

This patch does all this, removes all references to npm too.

### CODE REVIEW

**Comment by dashed** [comment]
I haven't seen yarn embed into a repo like this before. 

Is the rationale to lock down yarn is to ensure `yarn.lock` is consistent?

**Comment by BYK** [comment]
@dashed - yup. This is also what Facebook does in their repo. They also check-in the offline-mirror to remove network dependencies but that's a more radical approach which I'll only push for later on :D

**Comment by BYK** [comment]
I'll also be following up with a diff that replaces `--pure-lockfile` with `--frozen-lockfile` which is what we actually want. The former doesn't alter the lockfile whereas the latter actually stops and complains that the lockfile is ouf of sync with `package.json`.

**Review by billyvg — COMMENTED** [review]
LGTM, we'll want to make similar changes to https://github.com/getsentry/getsentry as well

**Review by billyvg — CHANGES_REQUESTED** [review]
LGTM, but we'll want to make similar changes to https://github.com/getsentry/getsentry as well. It has its tentacles into this repo, so we want to be sure the dev environment (as well as deploy) work before merging this.

**Review by billyvg — APPROVED** [review]
tests are passing, it deploys to staging, wcgw

**Pull request merged**
