### PR TITLE
chore(chartcuterie): Revert Style Changes

### PR DESCRIPTION
**Pull request by iamrajjoshi**
This reverts 1354478967d580699107222d42a95373b5a4dcaa and 173b69012db4737336284ebb4c75adbf08704e70

### CODE REVIEW

**Review by ellisonmarks — APPROVED** [review]

**Comment by sentaur-athena** [comment]
Do we know what caused the failure? Or just reverting because the timing matches

**Comment by iamrajjoshi** [comment]
> Do we know what caused the failure? Or just reverting because the timing matches

We are trying to see if this helps

**Comment by ellisonmarks** [comment]
> Do we know what caused the failure? Or just reverting because the timing matches

I believe the chartcuterie deployment is crashing because it's encountering `URLSearchParams` in https://sentry.io/_chartcuterie-config.js. Presumably that wasn't there before this change?

**Comment by sentaur-athena** [comment]
@ellisonmarks oh I thought this PR fixed it. https://github.com/getsentry/chartcuterie/pull/149
Just checked the logs though and seems like the issue is still going on.

**Pull request merged**
