### PR TITLE
ref(replay/feedback): don't suggest empty tag

### PR DESCRIPTION
**Pull request by michellewzhang**
resolves JAVASCRIPT-2WH4

before:

https://github.com/user-attachments/assets/fffce18d-99a3-488a-94a1-c9870f16adbb

after:

https://github.com/user-attachments/assets/1b8cc0d2-e3a8-4185-9b91-29d86b42655c

### CODE REVIEW

**Comment by aliu39** [comment]
We should look into why we're storing empty tags in the first place 🤔🤔

**Comment by michellewzhang** [comment]
> We should look into why we're storing empty tags in the first place 🤔🤔

it's based on most commonly searched values

**Review by billyvg — COMMENTED** [review]
I think we should leave it in because it's a valid use case to look for untagged events

**Comment by aliu39** [comment]
@billyvg oh is searching for os.name="" meant to be the same as searching for replays without the os.name tag?

Just did a [search](https://sentry.sentry.io/replays/?project=11276&query=os.name%3A%22%22&statsPeriod=90d&utc=true) and [this replay](https://sentry.sentry.io/replays/948ea6fd9ec342c480dbb8f4e1debdaf/?project=11276&query=os.name%3A%22%22&referrer=%2Freplays%2F&statsPeriod=90d&t_main=tags&yAxis=count%28%29) with os.name=MacOS is returned.

**Comment by billyvg** [comment]
> @billyvg oh is searching for os.name="" meant to be the same as searching for replays without the os.name tag?
> 
> Just did a [search](https://sentry.sentry.io/replays/?project=11276&query=os.name%3A%22%22&statsPeriod=90d&utc=true) and [this replay](https://sentry.sentry.io/replays/948ea6fd9ec342c480dbb8f4e1debdaf/?project=11276&query=os.name%3A%22%22&referrer=%2Freplays%2F&statsPeriod=90d&t_main=tags&yAxis=count%28%29) with os.name=MacOS is returned.

No, just literal empty string -- though maybe I am making this up and it's not a valid tag value?

**Comment by michellewzhang** [comment]
> > @billyvg oh is searching for os.name="" meant to be the same as searching for replays without the os.name tag?
> > Just did a [search](https://sentry.sentry.io/replays/?project=11276&query=os.name%3A%22%22&statsPeriod=90d&utc=true) and [this replay](https://sentry.sentry.io/replays/948ea6fd9ec342c480dbb8f4e1debdaf/?project=11276&query=os.name%3A%22%22&referrer=%2Freplays%2F&statsPeriod=90d&t_main=tags&yAxis=count%28%29) with os.name=MacOS is returned.
> 
> No, just literal empty string -- though maybe I am making this up and it's not a valid tag value?

@aliu39 @billyvg i think my reasoning for removing the empty string suggestion is more like, having an empty tag value isn't a useful suggestion for users most of the time since they probably want to search on an actual name/version - i'd rather save cognitive load and just show suggestions that are actually values. maybe it _is_ a valid tag to search on but it's not necessarily useful to suggest

**Comment by aliu39** [comment]
Based on the results of the search I linked above, I don't think the search for "" is valid, so I'm good with removing it. My question is still why is this value returned by the backend - can maybe open a separate ticket for that.

We can also, maybe, support an explicit value that indicates "I want to search for replays missing this tag". Similar to what I did for user fields a while back. But if we don't have this functionality already, that's out of scope from this pr too.

**Comment by michellewzhang** [comment]
> Based on the results of the search I linked above, I don't think the search for "" is valid, so I'm good with removing it. My question is still why is this value returned by the backend - I can make a note for that or open a separate ticket.
> 
> We can also, maybe, support an explicit value that indicates "I want to search for replays missing this tag". Similar to what I did for user fields a while back. But if we don't have this functionality already, that's out of scope from this pr too.

SCR-20241107-jtin
SCR-20241107-jtjr

to me it just looks like these are the commonly searched values

**Comment by aliu39** [comment]
I worked on this endpoint for replays, these suggestions are from our database and `count` is the number of times a value appears in the table. Can follow up to look into this, but yeah for now, definitely seems like we shouldn't suggest these

**Review by aliu39 — APPROVED** [review]

**Pull request merged**
