### PR TITLE
feat: gtfo south

### PR DESCRIPTION
**Pull request by wedamija**
May need corresponding prs in getsentry and sentry-plugins

holt_burn
t2_thumb_burn
dsalderaan
dsexplode
simpsonsburnvillain

### CODE REVIEW

**Review by dashed — APPROVED** [review]
Looks like South has gone south.

**Review by joshuarli — APPROVED** [review]
> +2 −811,654

image

**Comment by joshuarli** [comment]
giphy

giphy

giphy

giphy

**Comment by markstory** [comment]
:clap::fire::clap::fire::clap::fire::clap::fire::clap::fire::clap::fire::clap::fire::clap::fire::clap::fire::clap::fire::clap::fire::clap::fire::clap::fire::clap::fire::clap::fire::clap::fire::clap::fire::clap::fire::clap::fire::clap::fire::clap::fire::clap::fire::clap::fire::clap::fire::clap::fire::clap::fire::clap::fire::clap::fire::clap::fire::clap::fire::clap::fire::clap::fire::clap::fire::clap::fire::clap::fire::clap::fire::clap::fire::clap::fire::clap::fire::clap::fire::clap:

**Pull request merged**
