### PR TITLE
feat(upgrade): Upgrade to react@16.7.0

### PR DESCRIPTION
**Pull request by billyvg**
This upgrades react to 16.7.0. This is the latest version before hooks. It looks like most changes in 16.8.x are related to hooks and since we currently do not have any plans surround hooks, lets just upgrade to 16.7 until we do.

Summary of changes:
- `React.memo()`
- `React.lazy()` for code splitting

See https://github.com/facebook/react/blob/master/CHANGELOG.md#1660-october-23-2018 for full changelog

### CODE REVIEW

**Comment by EvanPurkhiser** [comment]
Do you feel pretty confident about this, or do you want to deploy to staging?

**Comment by billyvg** [comment]
It's worth a deploy to staging

**Review by markstory — APPROVED** [review]

**Review by dashed — APPROVED** [review]
⚛️

**Comment by billyvg** [comment]
Clicked around, seems good

**Pull request merged**
