### PR TITLE
fix(discover): Disable top 5 mode when no aggregates present

### PR DESCRIPTION
**Pull request by Zylphrex**
Top 5 mode should only be available when there is at least one aggregate. If
there are no aggregate present, disable top 5 modes and default back to total
period. This will also cause the top 5 indicators to be hidden when top 5 mode
is turned off.

### CODE REVIEW

**Review by markstory — COMMENTED** [review]
Looks good, should we also remove top5 modes when doing a drilldown navigation? Right now if you open a stack when top5 is active the chart stays in top5 and only shows a few spikes. Converting the top5 -> and top5daily -> daily would give better results.

**Comment by Zylphrex** [comment]
> Looks good, should we also remove top5 modes when doing a drilldown navigation? Right now if you open a stack when top5 is active the chart stays in top5 and only shows a few spikes. Converting the top5 -> and top5daily -> daily would give better results.

When you click open stack, the aggregates are removed. So what happens is that the graph switches to total period mode, this behaviour makes sense for top 5 period. I do see what you mean about top 5 daily. Switching it to total daily would make more sense than defaulting back to to total period. I'll update that.

**Review by markstory — APPROVED** [review]
:clap::clap:

**Comment by benvinegar** [comment]
Reminder: preference to disable/grey out vs. hide.

**Pull request merged**
