### PR TITLE
fix(alert-rule): Allow word break to show 256 char name with no breaks

### PR DESCRIPTION
**Pull request by jangjodi**
Allow for word break to accommodate 256 char alert rule names with no spaces/hyphens  

After change:
Screenshot 2024-01-04 at 10 42 46 AM

Before change:
Screenshot 2024-01-04 at 10 12 32 AM

### CODE REVIEW

**Review by vartec — APPROVED** [review]

**Comment by scttcper** [comment]
i feel like there has to be a css solution

**Review by scttcper — CHANGES_REQUESTED** [review]
wrapping this in a span with `word-break: break-word;` would be preferred since they likely have spaces/hypens/etc already in the title

**Comment by jangjodi** [comment]
> wrapping this in a span with `word-break: break-word;` would be preferred since they likely have spaces/hypens/etc already in the title

it breaks up properly for alert rules that are formatted like that, so I guess we don't need to fix it for this use case?

**Comment by scttcper** [comment]
css would also prevent the overflow for one giant word

**Review by scttcper — APPROVED** [review]
makes sense to me for this component

**Comment by jangjodi** [comment]
> makes sense to me for this component

thanks for all your feedback!

**Pull request merged**
