### PR TITLE
ref: Rename Data Privacy to Scrubbing and align other related language

### PR DESCRIPTION
**Pull request by untitaker**
We decided to get rid of our remaining uses of Data Privacy as it has been argued that data scrubbing does not really *only* cater to privacy aspects. We looked at what other terminology is in use and found ~anonymization to be the nicest of them all.~ scrubbing already widely in use.

* Mass-rename Data Privacy to Data ~Anonymization~ Scrubbing or Security & Privacy depending on context
* Split up org settings into multiple panes
* Retain Data Privacy phrasing in places where it would affect non-EA orgs (will go away with GA)

## Organization settings

Screenshot_2020-06-09 Sentry(1)

## Project settings

Screenshot_2020-06-09 Sentry

### CODE REVIEW

**Comment by mitsuhiko** [comment]
Why are we using the term "data anonymization" instead of "data scrubbing" which is a term we have all over the product?

**Comment by untitaker** [comment]
data privacy is not really used at all. it was the name of a section header before this project started and so we doubled down on using that term, but david argued that it's not really a good name to begin with (updated pr description)

**Review by priscilawebdev — APPROVED** [review]
LGTM ✅

**Comment by dcramer** [comment]
The complexity here is that some of the settings which now live under this category don't have anything to do with anonymization. For example, "Store Native Crash Reports" is about privacy, compliance, security, but is not at all about anonymization.

**Comment by untitaker** [comment]
@dcramer but it's not structured under anonymization... see screenshots.

I also need guidance on whether we want to go with anonymization here or with scrubbing. I can't do this decision on my own.

**Comment by dcramer** [comment]
It looks like it is in the project settings screenshot?

**Comment by untitaker** [comment]
Okay got it, yes we can split off Store Native Crash reports into its own section. I can update that, and it's more of an oversight... a similar split-up has already occured for org settings.

**Comment by untitaker** [comment]
Fixed. *That's* how it was supposed to look like.

Still, do we want to go with anonymization or would we be fine with Data Scrubbing everywhere where this PR currently says anonymization?

**Comment by dcramer** [comment]
I'm fine with anonymization. I think it's fairly obvious what it means, and I think ultimately the test is from non-native speakers.

**Comment by untitaker** [comment]
I've decided to revert everything back to Data Anonymization following the concerns from armin. Got informal buyin from cramer.

**Review by dcramer — APPROVED** [review]
This looks good but it'd be worth seeing if we can follow up with moving the stuff that's under Project -> Settings that's relevant to security into the new subheading.

**Comment by mitsuhiko** [comment]
LGTM

**Review by mitsuhiko — APPROVED** [review]

**Pull request merged**
