### PR TITLE
feat(discover): enable multi y axis for previous period view

### PR DESCRIPTION
**Pull request by edwardgou-sentry**
Adds  multi y axis support for `Previous Period` display view in Discover results chart:
image

When using multiple y axis series, previous period series will be plotted as stacked dotted lines using colours based off the original series. Single y axis previous period display is unchanged (will still use grey when plotting previous period series).

`currentSeriesName` and `previousSeriesName` props in `EventsRequest` were pluralized and changed from `string` type to `string[]` to support multiple previous series. Some dependants of `EventsRequest` were updated to reflect this but without any functional changes.

### CODE REVIEW

**Comment by edwardgou-sentry** [comment]
> ## [size-limit](https://github.com/ai/size-limit) report
> Path	[Base Size (493559e)](https://github.com/getsentry/sentry/actions/runs/1292849028)	Current Size	Change
> src/sentry/static/sentry/dist/entrypoints/app.js	52.51 KB	52.51 KB	-0.02% 🔽
> src/sentry/static/sentry/dist/entrypoints/sentry.css	70.89 KB	70.89 KB	0%

is this a false alarm?

**Comment by scttcper** [comment]
> Is this a false alarm?

I think baseChart is in the main bundle

**Review by wmak — COMMENTED** [review]
Mostly looks good to me, but I think this might have broken previous period legends on single axis

image

And isn't formatting equations properly when multi-axis is enabled:

image

**Review by wmak — APPROVED** [review]
LGTM

**Pull request merged**
