### PR TITLE
feat(ui): Change overlay setting to false

### PR DESCRIPTION
**Pull request by iProgramStuff**
Separating out a change from another PR.

### CODE REVIEW

**Review by dashed — APPROVED** [review]
Looks good to me 👍

**Comment by leedongwei** [comment]
@billyvg @iProgramStuff @dashed Even with the overlay setting at false, webpack will not compile when there's errors.

**Comment by leedongwei** [comment]
It might make sense to have a separate webpack config for development where some rules are relaxed. 

Example here: https://webpack.js.org/guides/production/

**Comment by dashed** [comment]
@leedongwei yep. It can potentially send a false signal. But there seems to be a demand to disable it.

**Pull request merged**
