### PR TITLE
build: write egg info to work around pip caching bug

### PR DESCRIPTION
**Pull request by mitsuhiko**
Potentially better fix for #10649.  Refs https://github.com/pypa/pip/issues/4537

### CODE REVIEW

**Comment by mattrobenolt** [comment]
Did you link to the right Travis CI issue? It seems unrelated.

**Comment by mitsuhiko** [comment]
@mattrobenolt obviously i did not not. Fixed.

**Review by mattrobenolt — APPROVED** [review]
🤔

**Comment by untitaker** [comment]
@mitsuhiko I am testing that on https://github.com/getsentry/sentry/pull/10649

**Review by untitaker — APPROVED** [review]
seems to work. percy problem can probably be fixed with rebase

**Pull request merged**
