### PR TITLE
feat(react): Make nav issues button reload page

### PR DESCRIPTION
**Pull request by HazAT**
issues-click mov

cc https://forum.sentry.io/t/reloading-issues-list/2326
#makesentrybetteronelineatatime

### CODE REVIEW

**Comment by MaxBittker** [comment]
this is better behavior, but putting it in willrecieveprops scares me a little bit (imagine something down the line causes this to thrash)?

**Comment by MaxBittker** [comment]
>#componentWillReceiveProps()
>Note that React may call this method even if the props have not changed, so make sure to compare the current and next values if you only want to handle changes. This may occur when the parent component causes your component to re-render.

https://facebook.github.io/react/docs/react-component.html#componentwillreceiveprops

**Comment by HazAT** [comment]
@MaxBittker so I've tried to click every button/searches/filter/live feed/sorting on the page I could find and wasn't able to get it stuck in an endless loop.
Also, we have `shouldComponentUpdate` which should prevent it

https://github.com/getsentry/sentry/blob/c9f8736b8ef28195802e6f3edb70146f3871ac53/src/sentry/static/sentry/app/views/stream.jsx#L121-L123

Still, I am pretty sure you can't test every possible combination of the stream so a risk remains, we just have to decide if we want to try it.

**Comment by billyvg** [comment]
I think it's probably fine because of SCU, although I think if this is a feature we want, an explicit refresh button in the stream toolbar feels more intuitive to me.

**Review by billyvg — APPROVED** [review]

**Comment by MaxBittker** [comment]
i agree that it's safe to merge, just being paranoid and anticipating a possible way it could regress in the future. don't really have a more elegant solution either but i'm glad you tested a few things

**Comment by EvanPurkhiser** [comment]
I'm also paranoid about this, since I think it could definitely lead to unexpected behavior simply from adding additional prosp to the component.

**Review by evanpurkhiser — APPROVED** [review]
I'm also paranoid about this, since I think it could definitely lead to unexpected behavior simply from adding additional prosp to the component.

**Comment by HazAT** [comment]
OK, thx guys I will merge this now. 
@billyvg regarding refresh button; this would also be a solution it's just that most of the other tabs refresh themselves when you click on them again that's why I wanted to do this.

**Pull request merged**
