### PR TITLE
Enhanced Rate Limits

### LINKED ISSUE #2289: Enhanced Rate Limits
Right now Sentry provides rate limits in two systems:

1. getsentry.com has a custom implementation of Quotas that are organization bound
2. Sentry itself provides team and project based rate limits (disabled on getsentry.com)

We want to converge these systems so that getsentry.com can provide a usable implementation of project rate limits.

### Approach

- Add organization rate limits to Sentry core
- Organizational quota is only controllable via plugin (by default), inherits from system quota
- Move rate limit controls to organizational level<br />
  (This ensures that only people with access can control rate limits, as it's generally an administrator who would need to mind over this and not a project owner)
- Change all limits to be percentage based (1-100) of the entire organization quota

### Tiered Limits

The current model of rate limits generally does an increment in Redis and then uses that result to test things. This is a problem if we want to say "there was enough room in the organization but not the project", as it would have effectively counted the event in both. We should move this to a LUA script for the Redis implementation so it can happen in a single transaction, and to the appropriate key. To ensure the key isn't partitioned, we'd (likely) do this within a hash.

### PR DESCRIPTION
**Pull request by dcramer**
Fixes GH-2289

### CODE REVIEW

**Comment by dcramer** [comment]
Need to review this with clear eyes, but I think it's good minus a few minor touchups.

**Comment by tkaemming** [comment]
Seems reasonable to me at a glance (I didn't review the UI.)

**Comment by dcramer** [comment]
Reassigning to you @tkaemming as we need expirations on keys (we do 2x the time window)

**Comment by tkaemming** [comment]
The quota backend work that I was doing should be at a stable point now — let me know if there's anything else I can do to help out here.

**Comment by dcramer** [comment]
Merged

**Pull request closed without merging**
