### PR TITLE
feat(db): Add last_deploy_id column to ReleaseProjectEnvironment

### PR DESCRIPTION
**Pull request by lynnagara**
Uses BoundedPositiveInteger field to match Release table

### CODE REVIEW

**Review by mattrobenolt — COMMENTED** [review]
Will this need an index or anything? I assume so.

**Comment by lynnagara** [comment]
👍 Updated to add index

**Comment by mattrobenolt** [comment]
Sorry, I wasn't necessarily suggesting to do it, but I wasn't sure if it was needed. So was asking. If you don't need the index, we shouldn't add it now. We can always add it later if we need it for something.

**Comment by lynnagara** [comment]
We'll want to join on this field to the deploys table so I think it'll be good to have in this case

**Review by mattrobenolt — APPROVED** [review]
You'll need to recreate the migration id.

**Pull request merged**
