### PR TITLE
feat(dashboards): Force Issue field on Issue widgets and remove redundant permalink field

### PR DESCRIPTION
**Pull request by edwardgou-sentry**
Forces the Issue field to always be displayed on Issue widgets as the first column. This is because Issue table results are always grouped by the Issue # regardless of fields selected so we should always display the Issue #. 

Permalink is no longer selectable in the field dropdown because it is functionally the same as the Issue column, therefore redundant.

image

### CODE REVIEW

**Comment by wmak** [comment]
Hmm thoughts on leaving Issue as a disabled column in the column editor?

**Comment by edwardgou-sentry** [comment]
> Hmm thoughts on leaving Issue as a disabled column in the column editor?

Haha was just about to post in the channel to get some thoughts on design. Yeah this would be possible, and might give some more transparency to the user. I'll make a change and post back

**Comment by edwardgou-sentry** [comment]
Refactored to have the Issue column disabled and immovable

**Comment by wmak** [comment]
Should we still allow drag and drop on the issue field so it doesn't have to be the first one?

It looks like this doesn't work if there's an existing widget where issue isn't the first field, eg.
image

**Review by narsaynorath — APPROVED** [review]
Looks good to me. I was slightly worried about the fixed column being triggered on a different page, e.g. Discover, but we don't set `source` on any of those so we're good in this case. I was wondering if we could add `fixed` as a boolean to the field instead of having specifically a `isFixedIssueColumn` but after digging around I realized that would involve modifying the types and might make things overcomplicated if we just want this one field now.

**Comment by narsaynorath** [comment]
Oops, listen to @wmak haha

**Comment by edwardgou-sentry** [comment]
Hey @wmak @ narsaynorath, made some changes:
`issue` column is now draggable at all times.
`issue` column is only deletable/changeable if there is more than one `issue` column in the widget. This enforces at least one `issue` column to exist.
Thanks!

**Review by narsaynorath — APPROVED** [review]
Tested it through dev-ui and existing issue widgets have disabled `issue` columns. If there's more than one then we can remove or change any of them. Deleting until there's one Issue column disables the row and keeps it draggable. Deleting until there's just that row left disables the drag functionality.

Adding a widget behaves the same way, but the Issue field is at the top, disabled, and draggable since there are other default fields.

**Review by wmak — APPROVED** [review]

**Pull request merged**
