### PR TITLE
ref(ts): Convert repositoryFileSummary

### PR DESCRIPTION
**Pull request by evanpurkhiser**

### CODE REVIEW

**Comment by joshuarli** [comment]
Why is this python-apocalypse.

**Comment by joshuarli** [comment]
What is Javascript.

**Comment by EvanPurkhiser** [comment]
Oops sorry, habbit

**Review by billyvg — APPROVED** [review]

**Review by priscilawebdev — APPROVED** [review]

**Comment by EvanPurkhiser** [comment]
oops, pushed the wrong thing

**Comment by EvanPurkhiser** [comment]
Please re-approve here https://github.com/getsentry/sentry/pull/20679

**Pull request closed without merging**
