### PR TITLE
ref(new-widget-builder-experience): Revert MetricsSearchbar logic

### PR DESCRIPTION
**Pull request by priscilawebdev**
Revert changes made to the MetricsSearchBar in the PR https://github.com/getsentry/sentry/pull/33047

### CODE REVIEW

**Review by shruthilayaj — APPROVED** [review]
Approving this so that the page doesn't crash. But it seems like fields and tags are no longer being populated in the column selectors (screenshot is on dev-ui) 👀
Screen Shot 2022-04-05 at 9 44 14 AM

**Comment by priscilawebdev** [comment]
@shruthilayaj do you have all conditions passing?

```
 organization.features.includes('dashboards-metrics') &&
      !organization.features.includes('new-widget-builder-experience') &&
      organization.features.includes('new-widget-builder-experience-modal-access')
```

**Comment by shruthilayaj** [comment]
> @shruthilayaj do you have all conditions passing?
> 
> ```
>  organization.features.includes('dashboards-metrics') &&
>       !organization.features.includes('new-widget-builder-experience') &&
>       organization.features.includes('new-widget-builder-experience-modal-access')
> ```

I think these should be populated if I just have `dashboards-metrics` enabled though (which I do)

**Review by shruthilayaj — APPROVED** [review]

**Comment by priscilawebdev** [comment]
@shruthilayaj I removed that because wanted to avoid having to fetch 2x, but I think it's fine to leave it for now

**Pull request merged**
