### PR TITLE
ref(savedsearch): Remove totally unused SavedSearchUserDefault (state)

### PR DESCRIPTION
**Pull request by evanpurkhiser**
This table has no use whatsoever

### CODE REVIEW

**Review by wedamija — COMMENTED** [review]
I think ci is failing because you haven't removed the constraints from related tables. Basically you need to follow these steps: https://develop.sentry.dev/database-migrations/#tables

You can remove the constraints in this pr if you want to avoid two prs

**Review by wedamija — APPROVED** [review]
lgtm. jfyi, you can combine these into one migration

**Comment by evanpurkhiser** [comment]
Ah, should I or it doesn't matter? I kinda like that it's clear the ordering

**Comment by wedamija** [comment]
> Ah, should I or it doesn't matter? I kinda like that it's clear the ordering

It's fine either way, just more painful if you need to rebase both

**Comment by wedamija** [comment]
> > Ah, should I or it doesn't matter? I kinda like that it's clear the ordering
> 
> It's fine either way, just more painful if you need to rebase both

I think it's also breaking the generate migration sql step?

**Review by wedamija — APPROVED** [review]

**Pull request merged**
