### PR TITLE
build(ui): Upgrade webpack, fix react hot reload

### PR DESCRIPTION
**Pull request by scttcper**
fixes hot module reloading during development

### CODE REVIEW

**Comment by scttcper** [comment]
upgrading webpack makes this scary

**Review by priscilawebdev — APPROVED** [review]
tested locally and everything looks good! 🛳🇮🇹

**Review by billyvg — APPROVED** [review]
Can you upgrade this on getsentry too?

**Review by evanpurkhiser — APPROVED** [review]
Tests pass, preview build works... looks pretty good to me

**Pull request merged**
