### PR TITLE
test(ui): Mock `window.getComputedStyle`

### PR DESCRIPTION
**Pull request by scttcper**
`window.getComputedStyle` is very slow in jsdom especially when there are many components. It is called when react-select is opened and on `userEvent.click`. This function helps with  placing dropdown menus for react-select and reading through all global styles to find `pointer-events: 'none'` for click. In the browser, this is not a performance issue.

What this PR does is change getComputedStyle to not parse stylesheets (from emotion) which has some pros/cons that i've listed in a comment below.

widgetBuilder.spec.tsx
before - 94.93s
after - 47.52s

### CODE REVIEW

**Review by dashed — DISMISSED** [review]

**Comment by scttcper** [comment]
There's some downsides to this i'm finding, might be worth talking about at TSC

**Comment by scttcper** [comment]
For TSC:

Downsides:
- can't use `expect(element).toHaveStyle({color: 'red'});` for emotion styles
- `userEvent.click` sometimes needs `skipPointerEventsCheck` and will ignore `pointer-events` from emotion 

Upsides:
- Even tests that only use `userEvent.click` are faster because it no longer has to parse all global styles to detect pointer-events
- We still check aria attributes like "disabled" when clicking

It might be possible to apply the mock to just a few files?

another performance example `performance/transactionSummary.spec.tsx`

before - 45s
https://sentry.io/organizations/sentry/discover/jest:27ab61a97554439baf177bc726a53202/?display=top5&environment=ci&field=title&field=transaction.duration&field=timestamp&name=All+Events&project=4857230&query=transaction.op%3A%22jest+test+suite%22+transaction.duration%3A%3C2min+branch%3Arefs%2Fheads%2Fmaster+title%3A%2Ftests%2Fjs%2Fspec%2Fviews%2Fperformance%2FtransactionSummary.spec.tsx&sort=-timestamp&statsPeriod=14d&yAxis=count%28%29

image


after - 10s
https://sentry.io/organizations/sentry/discover/jest:80f8aabfb3d44b7f9dd3df8233311d18/?display=top5&end=2022-05-03T21%3A00%3A00.000&environment=ci&field=title&field=transaction.duration&name=All+Events&project=4857230&query=transaction.op%3A%22jest+test+suite%22+transaction.duration%3A%3C2min+branch%3A%2Amock-get-computed-style+title%3A%2Ftests%2Fjs%2Fspec%2Fviews%2Fperformance%2FtransactionSummary.spec.tsx&sort=-transaction.duration&start=2022-05-03T19%3A04%3A26.000&yAxis=count%28%29

image

**Comment by scttcper** [comment]
> 
> > userEvent.click sometimes needs skipPointerEventsCheck and will ignore pointer-events from emotion
> 
> Do we at least get a useful error when this is required?

@markstory it says that it can't click because of pointer-events, it is a little confusing since you might have emotion styles applying the correct pointer-events. There was 2 tests that have been updated in this pr

**Comment by markstory** [comment]
An error related to pointer events is pretty good. That at least gives you some indication around where to look next.

**Review by evanpurkhiser — APPROVED** [review]

**Pull request merged**
