### PR TITLE
fix(email): ensure that each monthly graph in the email report is the same width

### PR DESCRIPTION
**Pull request by Chrissy**
I forgot to properly prefix my commit but I won't forget next time!

### CODE REVIEW

**Comment by MaxBittker** [comment]
closes https://github.com/getsentry/sentry/issues/6289

**Comment by Chrissy** [comment]
Thanks I knew I forgot something!

**Review by ckj — APPROVED** [review]
Great first commit!

**Comment by MaxBittker** [comment]
ship it! 👍

**Comment by Chrissy** [comment]
@MaxBittker @ckj it is actually a crummy first commit (at present) because it doesn't really fix the bug! Real fix coming v soon.

**Comment by Chrissy** [comment]
@ckj wanna take a quick peep again. I think this is *actually* ready to go now.

**Review by ckj — APPROVED** [review]
Even better this time 😎

**Pull request merged**
