### PR TITLE
fix(integrations) Fix disappearing tags after assigning Issue 

### LINKED ISSUE #22535: Slack Integration - Tags disappear after assigning issue
## Important Details

How are you running Sentry?

Saas (sentry.io)

## Description

The slack integration allows you to add tags from the event to the slack message. They show up perfectly fine but after assigning the issue to a user, the message changes and the tags are removed.

## Steps to Reproduce

1. Create a slack alert with tags in the alert message
2. Trigger an alert
3. Note the alert has the tags
4. Assign the issue to a user
5. Note the tags are gone

Good items to include here include:

- Include a stacktrace or other logs when relevant
- Include a redacted version of your configuration (`sentry.conf.py` and `config.yml` files) when relevant

### What you expected to happen

[What you think should be happening]

### Possible Solution

[If you have an idea on how this could be solved include that detail here.]

### PR DESCRIPTION
**Pull request by sdshone**
(Slack Integration)

The slack integration allows you to add tags from the event to the slack message. They show up perfectly fine but after assigning the issue to a user, the message changes and the tags are removed. This commit fixes the issue.

Fixes GH-22535

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Review by armenzg — COMMENTED** [review]
Hi @sdshone 
I'm very grateful for your help here! Unfortunately, there's two changes that I would need to see here to take this:

- Add a test for this functionality
- Try to add the functionality to message_builder. Probably the issues.py module

I've briefly looked at the repo and it seems that it's the issues.py module that has the original logic and we should try to keep the logic there where possible.

Let me know if you're still interested on working on this and I will be happy to help.

```
git grep tags src/sentry/integrations/slack/
src/sentry/integrations/slack/actions/form.py:    tags = forms.CharField(required=False, widget=forms.TextInput())
src/sentry/integrations/slack/actions/notification.py:    label = "Send a notification to the {workspace} Slack workspace to {channel} (optionally, an ID: {channel_id}) and show tags {tags} in notification"
src/sentry/integrations/slack/actions/notification.py:            "tags": {"type": "string", "placeholder": "i.e environment,user,my_tag"},
src/sentry/integrations/slack/actions/notification.py:        tags = set(self.get_tags_list())
src/sentry/integrations/slack/actions/notification.py:            attachments = [build_group_attachment(event.group, event=event, tags=tags, rules=rules)]
src/sentry/integrations/slack/actions/notification.py:        tags = self.get_tags_list()
src/sentry/integrations/slack/actions/notification.py:            tags="[{}]".format(", ".join(tags)),
src/sentry/integrations/slack/actions/notification.py:    def get_tags_list(self) -> Sequence[str]:
src/sentry/integrations/slack/actions/notification.py:        return [s.strip() for s in self.get_option("tags", "").split(",")]
src/sentry/integrations/slack/client.py:            tags={"ok": is_ok, "status": code},
src/sentry/integrations/slack/message_builder/issues.py:from sentry import tagstore
src/sentry/integrations/slack/message_builder/issues.py:    event_for_tags: Any, tags: set[str] | None = None
src/sentry/integrations/slack/message_builder/issues.py:    if tags:
src/sentry/integrations/slack/message_builder/issues.py:        event_tags = event_for_tags.tags if event_for_tags else []
src/sentry/integrations/slack/message_builder/issues.py:        for key, value in event_tags:
src/sentry/integrations/slack/message_builder/issues.py:            std_key = tagstore.get_standardized_key(key)
src/sentry/integrations/slack/message_builder/issues.py:            if std_key not in tags:
src/sentry/integrations/slack/message_builder/issues.py:            labeled_value = tagstore.get_tag_value_label(key, value)
src/sentry/integrations/slack/message_builder/issues.py:def get_color(event_for_tags: GroupEvent | None, notification: BaseNotification | None) -> str:
src/sentry/integrations/slack/message_builder/issues.py:    if event_for_tags:
src/sentry/integrations/slack/message_builder/issues.py:        color: str | None = event_for_tags.get_tag("level")
src/sentry/integrations/slack/message_builder/issues.py:        tags: set[str] | None = None,
src/sentry/integrations/slack/message_builder/issues.py:        self.tags = tags
src/sentry/integrations/slack/message_builder/issues.py:        # If an event is unspecified, use the tags of the latest event (if one exists).
src/sentry/integrations/slack/message_builder/issues.py:        event_for_tags = self.event or self.group.get_latest_event()
src/sentry/integrations/slack/message_builder/issues.py:        color = get_color(event_for_tags, self.notification)
src/sentry/integrations/slack/message_builder/issues.py:        fields = build_tag_fields(event_for_tags, self.tags)
src/sentry/integrations/slack/message_builder/issues.py:        tags: set[str] | None = None,
src/sentry/integrations/slack/message_builder/issues.py:        self.tags = tags
src/sentry/integrations/slack/message_builder/issues.py:        # If an event is unspecified, use the tags of the latest event (if one exists).
src/sentry/integrations/slack/message_builder/issues.py:        event_for_tags = self.event or self.group.get_latest_event()
src/sentry/integrations/slack/message_builder/issues.py:        color = get_color(event_for_tags, self.notification)
src/sentry/integrations/slack/message_builder/issues.py:        fields = build_tag_fields(event_for_tags, self.tags)
src/sentry/integrations/slack/message_builder/issues.py:    tags: set[str] | None = None,
src/sentry/integrations/slack/message_builder/issues.py:        group, event, tags, identity, actions, rules, link_to_event, issue_details
src/sentry/integrations/slack/message_builder/notifications/issues.py:            tags=self.context.get("tags", None),
src/sentry/integrations/slack/message_builder/notifications/issues.py:            tags=self.context.get("tags", None),
```

**Comment by sdshone** [comment]
@armenzg , Thanks a lot for reviewing this. I am determined to get this work completed. Also, I am happy that you pointed to me the right direction so I will be working on making those changes. 
While debugging this, I had noticied the logic inside src/sentry/integrations/slack/message_builder/issues.py specifically the method build_tag_fields which takes the self.tags and event_for_tags. The thing that I could not clearly understand the method returns tags only if the self.tags was set, which seemed like a obvious way a bug can be introduced (if the SlackIssuesMessageBuilder is not initialised with tags)
From what I read I felt that the build_tag_fields should return be returning tags even if the self.tags was not set but has event_for_tags(I could be wrong about this, let me know your opinion)

Meanwhile, on a less priority, the linked issue is not currently assigned to me, if you could help me in getting it assigned that would be great!

**Review by armenzg — COMMENTED** [review]
Trying to get a pass on the PR checks and we will merge this then.

Thanks @sdshone for your contribution!

**Comment by sdshone** [comment]
> Trying to get a pass on the PR checks and we will merge this then.
> 
> Thanks @sdshone for your contribution!

Hi @armenzg , thank you so much for helping me with this. I'm happy to take up more challenging issues going forward!

**Comment by armenzg** [comment]
Please don't merge master as it blocks the CI. Just FYI, every time a contributor pushes a change the CI stops and requires an approval from me.

**Review by armenzg — APPROVED** [review]

**Comment by armenzg** [comment]
🎉

**Comment by armenzg** [comment]
Please let us know once you confirm that it works as expected.

**Comment by sdshone** [comment]
> Please let us know once you confirm that it works as expected.

I have tested this change and I also had attached screenshot showing the expected change in behaviour. Let me know if you meant anything specific. @armenzg

**Comment by armenzg** [comment]
All good! Thanks for verifying it.

**Pull request merged**
