### PR TITLE
feat(crons): Ensure that org level monitor endpoints will continue working if there are multiple monitors with the same slug

### LINKED ISSUE #65954: Make organization level cron monitor endpoints attempt to fetch the monitor using the slug
We're moving over to unique slugs per project rather than org. This has the potential to break the existing org endpoints. We should do our best to fetch a monitor here rather than just fail.

Ideally this is just a stopgap, and longer term we remove these endpoints.

### PR DESCRIPTION
**Pull request by wedamija**
Since we're making the constraint for monitor slug on (project, slug) we might end up with multiple potential monitors in the org level endpoints. This puts in a temporary fix so that we just return the oldest monitor.

I can't write a test for this yet since we still have the old constraint in place.

Fixes https://github.com/getsentry/sentry/issues/65954

### CODE REVIEW

**Review by cmanallen — APPROVED** [review]
Can we fetch the oldest monitor and not worry about the rest?  I.e. Add a sort to your query and limit by `1`?

**Comment by wedamija** [comment]
> Can we fetch the oldest monitor and not worry about the rest? I.e. Add a sort to your query and limit by `1`?

I'm basically doing that in memory. I've seen issues in the past with sorting by id causing problems, so I just decided it's safer in memory. We're not likely to have many rows here

**Comment by cmanallen** [comment]
@wedamija Makes sense.  Last thing I'll mention is that `min` takes a key kwarg.  `monitor = min(monitors, key=lambda m: m.id)` would be equivalent.  One fewer line :D

**Comment by wedamija** [comment]
> @wedamija Makes sense. Last thing I'll mention is that `min` takes a key kwarg. `monitor = min(monitors, key=lambda m: m.id)` would be equivalent. One fewer line :D

Nice tip! I rarely use min

**Pull request merged**
