### PR TITLE
feat(issue-details): Update release in group header

### PR DESCRIPTION
**Pull request by roggenkemper**
this pr updates the group header with an updated design to show the first and last release the group was seen in 

Screenshot 2024-07-31 at 11 52 20 AM

### CODE REVIEW

**Comment by MichaelSun48** [comment]
@roggenkemper I'm seeing some padding issues in the divider and release section 

image

**Comment by roggenkemper** [comment]
> @roggenkemper I'm seeing some padding issues in the divider and release section. I'm trying to figure out the cause right now
> 
> image

ah - good catch , i know what the problem is, i had a git issue and fixing it broke this

**Review by MichaelSun48 — APPROVED** [review]
code lgtm but minor nit: 
Id prefer "Releases" -> "Releases: " (with the little extra space after). 

image

**Comment by roggenkemper** [comment]
> code lgtm but minor nit: Id prefer "Releases" -> "Releases: " (with the little extra space after).
> 
> image

what i have rn is what the design shows - ill bring up your suggestion but for now ill keep it as is

**Pull request merged**
