### PR TITLE
ref(sdk): Temporarily remove parent sampling

### PR DESCRIPTION
**Pull request by k-fish**
### Summary
This will test the effects of parent sampling on event ingestion. Will pair it with getsentry change for conf. Going to run it for a short period (likely tomorrow) then revert.

### CODE REVIEW

**Review by untitaker — COMMENTED** [review]
Just so I understand, we think that there are particular *transaction names* (ie specific celery tasks or endpoints) that are not being sampled and this is the attempt to figure out why?

Thanks for taking a look btw

**Review by untitaker — APPROVED** [review]
approving since it seems harmless enough. I recommend using the `"transaction-events.force-disable-internal-project"` option to shed load fast if things go south during deployment.

**Comment by wmak** [comment]
+1 using an option for this in case something goes wrong

**Comment by k-fish** [comment]
The options is already in place in the `capture_envelope` function to drop transactions, but I added it to the sampler to test out.

**Comment by untitaker** [comment]
I didn't mean to suggest you should change your PR in any way, I was just pointing out this option in case this change to the sampler causes a lot of transactions to be sent and you need a way to cut off the traffic.

**Comment by k-fish** [comment]
@untitaker yeah I realized after you probably meant just that the option was available.

**Pull request merged**
