### PR TITLE
chore(py38): upgrade mmh3 to 3.0.0

### PR DESCRIPTION
**Pull request by joshuarli**
mmh3 3.0.0 adds support for Python 3.8, and also they have wheels on pypi so we don't need `g++` to build our own anymore.

mmh3 2.4+ added 64-bit hashes but they kept the `mmh3.hash` 32-bit, so we don't need to change.

However 2.4 changed the type of seeds from signed 32-bit int to unsigned 32-bit int. The resulting values with signed seeds still remain the same as before, as long as they are 32-bit. See [here](https://github.com/hajimes/mmh3#unexpected-results-when-given-non-32-bit-seeds). I uh, don't understand what our code is doing, but I feel like column in `mmh3.hash(feature, column)` wouldn't exceed 2**32?

I also just double checked to see that this is the same across these 2 versions since our tests don't do that:

```
>>> import mmh3
>>> mmh3.__version__
'2.3.1'
>>> from sentry.similarity.signatures import MinHashSignatureBuilder
>>> MinHashSignatureBuilder(32, 0xFFFF)({"foo", "bar", "baz"})
[24146, 35463, 32982, 5089, 5355, 4077, 9210, 11583, 20316, 6712, 37199, 16911, 4513, 23040, 35860, 9195, 3309, 6325, 19067, 3431, 25885, 7436, 18086, 16365, 24873, 17724, 13555, 10876, 32966, 5293, 44737, 41540]
```

```
>>> import mmh3
>>> mmh3.__version__
'3.0.0'
>>> from sentry.similarity.signatures import MinHashSignatureBuilder
>>> MinHashSignatureBuilder(32, 0xFFFF)({"foo", "bar", "baz"})
[24146, 35463, 32982, 5089, 5355, 4077, 9210, 11583, 20316, 6712, 37199, 16911, 4513, 23040, 35860, 9195, 3309, 6325, 19067, 3431, 25885, 7436, 18086, 16365, 24873, 17724, 13555, 10876, 32966, 5293, 44737, 41540]
```

### CODE REVIEW

**Comment by joshuarli** [comment]
pypi being flaky, nice

**Comment by joshuarli** [comment]
rip pip again

**Comment by tkaemming** [comment]
> also they have wheels on pypi so we don't need `g++` to build our own anymore.

🙏 

> I feel like column in `mmh3.hash(feature, column)` wouldn't exceed 2**32?

Yep, that's the correct read on this. This should be fine.

**Review by evanpurkhiser — APPROVED** [review]
If ted says yes I say yes

**Pull request merged**
