### PR TITLE
dev: improve tooling + autopep8

### PR DESCRIPTION
**Pull request by dcramer**

### CODE REVIEW

**Comment by dcramer** [comment]
https://github.com/getsentry/sentry/pull/5677

**Comment by getsentry-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Changes to build requirements</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by dcramer** [comment]
@getsentry/team

**Review by mitsuhiko — APPROVED** [review]

**Comment by dcramer** [comment]
i took the liberty of cleaning up the lint engine as well so its a little less repetitive

**Comment by dcramer** [comment]
ive enabled aggressive (fixes things like type vs isinstance), and disabled W690 which breaks some things

Does anyone have concerns w/ the isinstance rewrite?

-        if data.get('extra') is not None and type(data['extra']) != dict:
+        if data.get('extra') is not None and not isinstance(data['extra'], dict):

**Comment by dcramer** [comment]
the autoformatting now prompts before staging changes from prettier/autopep8

**Comment by dcramer** [comment]
screenshot 2017-07-05 13 45 56

**Comment by mitsuhiko** [comment]
still 🍪

**Pull request merged**
