### PR TITLE
Stack trace linking for VSTS

### PR DESCRIPTION
**Pull request by jianyuan**
This PR enables Stack trace linking for VSTS.

Depends on https://github.com/getsentry/sentry/pull/53584

### CODE REVIEW

**Review by leeandher — COMMENTED** [review]
Looks good! Could we also get a test for the `project_stacktrace_link` endpoint that VSTS links are added to the payload? That is how we can get these links to the frontend.

**Comment by jianyuan** [comment]
@leeandher The `test_get_stacktrace_link` test should cover that particular use case.

The `project_stacktrace_link` endpoint invokes the `get_stacktrace_link` method [here](https://github.com/getsentry/sentry/blob/0edd43558cc9ce9b26fae1024d35a51b276af189/src/sentry/api/endpoints/project_stacktrace_link.py#L41-L43). The [existing tests for this endpoint](https://github.com/getsentry/sentry/blob/0edd43558cc9ce9b26fae1024d35a51b276af189/tests/sentry/api/endpoints/test_project_stacktrace_link.py) utilise the `ExampleIntegration` for all their tests rather than a specific integration. Moreover, these tests patch the `get_stacktrace_link` method to return the URL that the frontend displays.

**Comment by leeandher** [comment]
Looks great! Tested it locally with no issues! I'll run the CI and merge this early next week :+1:
image

**Review by leeandher — APPROVED** [review]

**Pull request merged**
