### PR TITLE
allow API client to specify additional fields to sanitize

### PR DESCRIPTION
**Pull request by wyattisimo**
This affords the API client some level of data scrubbing customization:
- API client can turn data scrubbing on/off.
- API client can send fields to sanitize in addition to the server defaults.

### CODE REVIEW

**Comment by dcramer** [comment]
This seems reasonable to me. That said, I'd like to shorten the option name to something like "sentry:scrub_data_fields" or "sentry:sensitive_fields"

**Comment by wyattisimo** [comment]
@dcramer now using `sentry:sensitive_fields`

**Comment by dcramer** [comment]
Thanks!

**Comment by dcramer** [comment]
FYI this will also be available in the 7.2.0 release which we're about to push out shortly.

We'll eventually add some UI around this once we give it a bit more thought.

**Comment by dcramer** [comment]
Actually, I lied, it didn't make the 7.2.0 cut as I forgot to pull -.-

**Pull request merged**
