### PR TITLE
feat(hybrid-cloud): Setup integration/identity services and use them for Slack

### PR DESCRIPTION
**Pull request by leeandher**
See: [HC-549](https://getsentry.atlassian.net/browse/HC-549)

This PR uses new services for interacting with Slack to prepare for my hybrid cloud changes.

### CODE REVIEW

**Review by corps — APPROVED** [review]
Looks pretty solid.

**Review by vbro — APPROVED** [review]

**Comment by leeandher** [comment]
This PR is ALSO growing unmanagable as I try to implement Identity and Integration services all at once. It wasn't apparent at the start/review time, but there are many instance methods which have to be accounted for on the Integration model.

Far too risky to merge confidently as is. I'll be spinning off another set of PRs, for each model independently and get reviews once more.

**Comment by corps** [comment]
Gonna take a closer look at this next.

**Comment by leeandher** [comment]
The two PRs spun off of this one are https://github.com/getsentry/sentry/pull/42677 and https://github.com/getsentry/sentry/pull/42681.

This is too large/risky to merge as is.

**Pull request closed without merging**
