### PR TITLE
ref(ci): Increase acceptance / frontend test parallelization

### PR DESCRIPTION
**Pull request by k-fish**
### Summary
Increasing parallelization should help uncover any remaining isolation issues (certain kinds, anyway), on top of providing a benefit of reduced time in PR. 

Bringing this up since if we move to frontend-only deploys we can potentially get code-to-mainline times down into the minutes range, increasing parallelization and reduce parallelization overhead will get us there. 

Again, we should be doing work to reduce our overhead and test times etc. but we will also need to increase parallelization, which we might as well do now.

#### Overhead
Going to be measuring after running this a few times, but it should roughly be around 30s-1min * 4 more nodes of additional overhead, which would only be what matters in terms of cost, the actual parallel work doesn't count. 

The overhead time / costs can be reduced later in a few different ways (eg. moving build steps in a build image on gchr as a precursor step to the parallelization stage, and re-using that build image when yarn.lock is the same) but we might as well take advantage of the wall time savings now.

### CODE REVIEW

**Comment by k-fish** [comment]
After bumping acceptance test node count, I just realized it's doing about 5 minutes of setup, so I'm going to leave it as is for now.

**Comment by k-fish** [comment]
re: overhead times / build steps, we can improve them by only updating them on yarn.lock / requirements.txt changes, and building them into a docker image with `<image-name>:<sha of all the cat of all package files>` for example. That way the GHA can lookup an image and if available skip the build step for the vast majority of PRs.

**Comment by asottile-sentry** [comment]
I don't think increasing parallelism on frontend actually buys us anything at the moment since it's not the slowest thing -- it does however theaten to take up our parallel worker pool -- which iirc we've been pretty close to exhausting recently

**Review by armenzg — CHANGES_REQUESTED** [review]
Okay to close?

**Comment by k-fish** [comment]
Discussed this offline with @asottile-sentry, will probably put up another PR that addresses the Amdahl's law problem w/ acceptance to actually get PR times down, at least as an example.

**Pull request closed without merging**
