### PR TITLE
fix(ui): Disable releases modal if releases set up

### PR DESCRIPTION
**Pull request by mikellykels**
Add another condition where the releases modal will not display if releases have been set up.

### CODE REVIEW

**Review by MaxBittker — APPROVED** [review]
i think this will potentially remove spam for some users

**Comment by ehfeng** [comment]
This is slightly different for users who have enabled release tracking vs releases. In some ways, users who have configured release tracking are the best audience for releases.

**Comment by ehfeng** [comment]
@mikellykels was this solved for our customer? if so, we should close this PR.

**Comment by mikellykels** [comment]
@ehfeng Yup, this was resolved outside of this PR. Closing!

**Pull request closed without merging**
