### PR TITLE
feat(ui): Add EmptyHeader + EmptyDescription w/ story

### PR DESCRIPTION
**Pull request by evanpurkhiser**

### CODE REVIEW

**Comment by billyvg** [comment]
I feel like title should just be a prop of `EmptyMessage` (and maybe even description) since it should be a very common pattern (and we already have props for icon and action).

**Comment by EvanPurkhiser** [comment]
Yeah I would agree with that. Then just allow no children?

**Comment by billyvg** [comment]
I would leave `children` since it's used so much (unless you want to update all of our uses of `EmptyMessage`)

**Comment by EvanPurkhiser** [comment]
Yeah that's what I mean, children isn't a required prop.

**Review by billyvg — APPROVED** [review]

**Pull request merged**
