### PR TITLE
Breadcrumb visual enhancements

### PR DESCRIPTION
**Pull request by ckj**
Addresses various feedback including the removal of code bg, padding and alignment fixes, and a contrast pass:

**Before:**

screen shot 2016-05-10 at 4 44 19 pm

**After:**

screen shot 2016-05-10 at 4 27 45 pm

cc @getsentry/ui

### CODE REVIEW

**Comment by benvinegar** [comment]
🍕

**Comment by ckj** [comment]
> show 1 collapsed crumbs

I think I remember some talk around only collapsing if there's more than one crumb to collapse. That still the plan?

**Comment by benvinegar** [comment]
> I think I remember some talk around only collapsing if there's more than one crumb to collapse. That still the plan?

I mean, yes. But this is more a coincidence of the mock data. In 90% of the examples I've seen, there is the full # of breadcrumbs (e.g. 30 or 50, depending on client).

**Comment by ckj** [comment]
I added a before and after for the curious.

**Comment by benvinegar** [comment]
Looks great.

**Comment by macqueen** [comment]
yeah, looks awesome!

**Pull request merged**
