### PR TITLE
fix(integrations): Make pipeline completion atomic

### PR DESCRIPTION
**Pull request by evanpurkhiser**

### CODE REVIEW

**Review by mattrobenolt — COMMENTED** [review]
Why? I don't see any reason you'd need to?

Everything here seems like it'd be idempotent.

**Comment by EvanPurkhiser** [comment]
@mattrobenolt: If the integration is setup without the identity provider users simply won't be able to link their accounts. Of course, that should only happen if there's some kind of issue. It _should_ be completely idempotent, but things break sometimes :) 

Any specific concerns about putting this into a transaction?

**Comment by mattrobenolt** [comment]
Nothing really wrong, but if we can avoid explicit transaction blocks, I prefer it since transactions are relatively heavy. But I don't see it really bringing you any value here either.

You're also wrapping the serializer in a transaction too since you're wrapping the whole function.

**Comment by EvanPurkhiser** [comment]
> if we can avoid explicit transaction blocks, I prefer it since transactions are relatively heavy. But I don't see it really bringing you any value here either.

Yeah. Thinking about this a little more I'm going to go ahead and close this for now.

**Pull request closed without merging**
