### PR TITLE
feat(discover): Add analytics event when discover query is run

### PR DESCRIPTION
**Pull request by lynnagara**
Depends on https://github.com/getsentry/reload/pull/48

### CODE REVIEW

**Comment by adhiraj** [comment]
Normally we use reload for clicks/views/UI interactions where we don't hit an API. If we do, we use analytics.record() in python code. Generally there's always a question of whether something should be on the frontend or backend, and by default we choose backend because it's more robust, and accurate (e.g. less risk of double recording things compared to frontend where there are re-mounts etc.)

**Comment by lynnagara** [comment]
I think I'd still prefer to do this on the frontend in order to separate explicit clicks as opposed to queries that are run (for example we might run a number of queries behind the scenes for each time run query is actually clicked but don't wish to record them all)

**Comment by adhiraj** [comment]
If each click corresponds to a single API request (that can later fan out from the python handler), doing it on the backend still makes sense. But not a blocker, up to you which you choose.

**Review by adhiraj — APPROVED** [review]

**Comment by lynnagara** [comment]
The requests that require analytics are not distinguishable from those that we don't want to track on the backend side.

**Comment by adhiraj** [comment]
👍 frontend makes more sense then

**Pull request merged**
