### PR TITLE
Cleaner ui for assigning members to teams

### PR DESCRIPTION
**Pull request by benvinegar**
/cc @getsentry/ui

Before:

image

After:

image

---

This change is [Reviewable](https://reviewable.io/reviews/getsentry/sentry/4055)

### CODE REVIEW

**Comment by macqueen** [comment]
Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/4055)*

**Comment by macqueen** [comment]
*[src/sentry/web/forms/edit_organization_member.py, line 34 \[r2\]](https://reviewable.io:443/reviews/getsentry/sentry/4055#-KQXuj001SMsHQv63IVV:-KQXuj001SMsHQv63IVW:b-22kmr3) ([raw file](https://github.com/getsentry/sentry/blob/64952a2952c2fe046c5f8f8ea4eb370dfe4df716/src/sentry/web/forms/edit_organization_member.py#L34)):*
> ```Python
>         )
> 
>         self.fields['teams'].queryset = (
> ```

you might want this to be choices (guessing based on the failing tests...)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/4055)*

**Comment by benvinegar** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/sentry/web/forms/edit_organization_member.py, line 34 \[r2\]](https://reviewable.io:443/reviews/getsentry/sentry/4055#-KQXuj001SMsHQv63IVV:-KQXx-WCqNmwKI3cuwZr:b-ebpkjb) ([raw file](https://github.com/getsentry/sentry/blob/64952a2952c2fe046c5f8f8ea4eb370dfe4df716/src/sentry/web/forms/edit_organization_member.py#L34)):*
<details><summary><i>Previously, macqueen (Jess MacQueen) wrote…</i></summary>
> you might want this to be choices (guessing based on the failing tests...)
</details>
fixed (thanks)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/4055)*

**Comment by macqueen** [comment]
Reviewed 1 of 2 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/4055)*

**Pull request merged**
