### PR TITLE
ref: Switch LPQ to a budgeting implementation.

### PR DESCRIPTION
**Pull request by Swatinem**
Here is the main logic of the new approach to LPQ demotion:

---

Records the duration of a symbolication request for the given project_id.

The duration (from the start of the symbolication request)
should be recorded at regular intervals *as the event is being processed*.

The duration is used to track the used "symbolication time budget" of a project.
Each project is allocated a certain per-second budget.
If that budget is exceeded, the project will be demoted to the low priority queue.

This can happen when a project either submits *a lot* of fast events,
or a few *very slow* events.

As the running duration is recorded at regular intervals,
it naturally forms a quadratic function:

Assuming we record at 1-second intervals and the request took 5 seconds
in total, the used budget is:

1 + 2 + 3 + 4 + 5 = 15

In general, a request that takes n seconds to symbolicate will cost
1 + 2 + … + n = n * (n+1) / 2 = O(n²) time units.

This method will "punish" slow events in particular, as our main goal is
to maintain throughput with limited concurrency.

### CODE REVIEW

**Comment by Swatinem** [comment]
NOTE to self:

The p99 time for symbolication is around the ~2s mark. We can also adjust `SYMBOLICATOR_POLL_TIMEOUT` and friends to more regularly poll symbolicator and record these metrics.

**Comment by loewenheim** [comment]
Is the functionality of regularly recording symbolication time yet to be implemented or is the intention that it happens "naturally" as part of the loop and the `RetrySymbolication` exception handling?

**Comment by Swatinem** [comment]
I have already added this to the `RetrySymbolication` loop.

**Comment by loewenheim** [comment]
The default values of `budget_time_window` and `project_budget` are 300 and 10.0, respectively. Does this mean that a project should, by default, have a budget of 10 Symbolication Time Credits™ every 5 minutes?

**Comment by Swatinem** [comment]
> The default values of `budget_time_window` and `project_budget` are 300 and 10.0, respectively. Does this mean that a project should, by default, have a budget of 10 Symbolication Time Credits™ every 5 minutes?

I changed the default and added a bit more docs for all that.

The `budget_time_window` is meant as a sliding window, and the `project_budget` is meant as credits averaged per second over the sliding window.

I hope this makes sense? I’m open to suggestions of how to improve the wording and docs here.

**Comment by Swatinem** [comment]
Now that I think about it, the "averaging over the sliding window" code would need a bit more logic, as it is using discrete buckets, and going one bucket past the window.

**Comment by Swatinem** [comment]
Also, shortening this window would have two effects:
- less data to retain in redis
- it could then probably react faster to spikes, as the likelyhood that a spike wood tip over the rolling average is a bit higher.

**Review by loewenheim — APPROVED** [review]

**Pull request merged**
