### PR TITLE
fix(tagstore): Make sure all reads are correctly using partition keys

### PR DESCRIPTION
**Pull request by mattrobenolt**
Fixes SENTRY-6FN

tl;dr some queries were flat out missing `project_id` filters entirely, but also each join needs to be overly explicit otherwise, it'll try to map/reduce the whole cluster.

### CODE REVIEW

**Comment by mattrobenolt** [comment]
Ok, so the blocking thing here is `get_group_tag_values_for_users`.

As it turns out, this is used to span across EventUser objects from multiple projects, this means we need to actually query multiple shards, in which case, this is strictly disallowed. So this will need to be refactored into an O(n), one for each project and just merged together.

**Comment by mattrobenolt** [comment]
And `get_group_ids_for_users` and `get_release_tags`.

Need to decide if we should explicitly disallow this and always do O(n) or if we want to let Citus actually distribute to multiple shards and actually parallelize these instead of doing it sequentially in code.

My concerns are: If I enable the ability for Citus to query multiple shards, we now lose the ability to easily detect a query that is unqualified. Meaning, it has no partition key at all, which means it'll map to all shards instead. But on the other hands, being able to actually offload this will be nice and should be significantly faster.

**Comment by mattrobenolt** [comment]
Another alternative, explicitly for Citus, is to issue a `SET` query along with these, to explicitly enable querying across shards. This might be a good middleground. Then we get the benefit of querying multiple shards in parallel, without letting the request runaway.

Going to sleep on this one.

**Comment by bretthoerner** [comment]
By your second comment I was already mentally writing what you wrote in the 3rd comment. So yeah, I'm +1 on having a context manager to selectively enable this, since it seems nice to let Citus do it in parallel (when we opt in) vs us doing it serially/manually. Since it's basically the same thing anyway.

**Review by bretthoerner — APPROVED** [review]
Not sure if you want to do the other change in a different PR or not, but the `project_id` additions look good.

**Comment by mattrobenolt** [comment]
Yeah, I'm going to pull that bit into a different PR. I'll fix the test here though, the query will just 100% fail in production though since it is trying to span multiple shards. Then follow up on the context manager.

**Pull request merged**
