### PR TITLE
ref(features) Remove unused feature flags

### PR DESCRIPTION
**Pull request by markstory**
This feature flag has no checks in sentry or getsentry.

### CODE REVIEW

**Review by untitaker — CHANGES_REQUESTED** [review]
similarity-view and similarity-indexing are not enabled for some Sentry instances we run as part of ST. similarity-indexing causes extreme additional load on either the default redis or a separate redis cluster one can configure.

If you want to do this, you need to

* talk to ops about turning on similarity feature for every ST instance and provisioning the extra Redis needed
* check if onpremise already has it enabled + warn onpremise users that they need to scale their redis up

Turning it on for 100% without configuration changes is likely to take down at least one high-volume Sentry instance as Redis will become overloaded.

**Comment by markstory** [comment]
> similarity-view and similarity-indexing are not enabled for some Sentry instances we run as part of ST. similarity-indexing causes extreme additional load on either the default redis or a separate redis cluster one can configure.

Did not know that. I'll revert those changes for now.

**Comment by wedamija** [comment]
> > similarity-view and similarity-indexing are not enabled for some Sentry instances we run as part of ST. similarity-indexing causes extreme additional load on either the default redis or a separate redis cluster one can configure.
> 
> Did not know that. I'll revert those changes for now.

Might be worth leaving a comment next to this explaining why it's disabled

**Review by wedamija — APPROVED** [review]

**Comment by markstory** [comment]
> Might be worth leaving a comment next to this explaining why it's disabled

Agreed. I left comments in getsentry so that future us doesn't think the features are always enabled.

**Review by untitaker — APPROVED** [review]

**Pull request merged**
