### PR TITLE
feat: store symbolicated source_link

### PR DESCRIPTION
**Pull request by vaind**
Makes sure `source_link` frame attribute that is provided by the symbolicator makes it to Sentry. 

Enables https://github.com/getsentry/sentry/issues/46024

Example: look for "source_link" in the attached [JSON](https://github.com/getsentry/sentry/files/11098268/download.txt) that has been saved from a local developer instance

### CODE REVIEW

**Review by Swatinem — APPROVED** [review]
lgtm! We just had a discussion that the relay store normalizer might throw away stuff from the stack trace, so might be good if some relay people can also review this.

**Review by bruno-garcia — APPROVED** [review]
🚀

**Comment by bruno-garcia** [comment]
The missing piece to get stacktrace linking in dotnet from source link

**Comment by vaind** [comment]
It would be nice if this could get merged. Who could do that?

**Comment by Swatinem** [comment]
I guess CI expects someone to:

/gcbrun

**Comment by Swatinem** [comment]
I would love to merge this, but TBH I have no idea to trigger the needed CI checks that don’t seem to run for external PRs by default. I reached out internally but haven’t got an answer yet.

**Comment by vaind** [comment]
> I would love to merge this, but TBH I have no idea to trigger the needed CI checks that don’t seem to run for external PRs by default. I reached out internally but haven’t got an answer yet.

Thanks. Maybe you could adopt this and push to the main repo then? I don't have push permissions & it's such a small PR...

**Comment by Swatinem** [comment]
I can do that as a last resort, yes. But I want to do that the "proper" way, because this situation is untenable TBH.

**Comment by Swatinem** [comment]
Lets try this:

Trigger: getsentry tests

**Comment by Swatinem** [comment]
Wow, that was a long ride…

**Comment by vaind** [comment]
thx a lot @Swatinem

**Pull request merged**
