### PR TITLE
ref(devservices): Disable access log output

### PR DESCRIPTION
**Pull request by evanpurkhiser**
Does anyone ACTUALLY need this by default

### CODE REVIEW

**Comment by dashed** [comment]
@EvanPurkhiser backend folks probably aren't the right folks to review this.

**Comment by EvanPurkhiser** [comment]
Yeah I forgot exactly who added this stuff

**Review by joshuarli — APPROVED** [review]
unblocking

**Comment by billyvg** [comment]
🌮

**Review by wmak — APPROVED** [review]

**Pull request merged**
