### PR TITLE
Use django.utils.http.urlencode for proper encoding handling

### PR DESCRIPTION
**Pull request by daevaorn**

### CODE REVIEW

**Comment by dcramer** [comment]
What was breaking before this change?

**Comment by daevaorn** [comment]
Django's `urlencode` does almost the same thing as deleted `safe_urlencode`. It handles correct non ASCII values in query string parameters. I have an issue with such parameters in my Sentry installation.

**Comment by mattrobenolt** [comment]
@daevaorn Sorry, I guess we're asking for something with a test case so we can see that it's broken. We haven't experienced this issue in all of getsentry.com, so I'm curious what you're hitting that we're not.

**Comment by daevaorn** [comment]
Oh, it will quite complicated to reproduce on current master. I'm using 7.7.x version right now and having problem with this code – https://github.com/getsentry/sentry/blob/master/src/sentry/interfaces/http.py#L141-L142. Armin have recently added explicit to bytes conversion with https://github.com/getsentry/sentry/commit/1e516a69c90f6d5a9139a091f6a552285b26e9c6 commit. But I propose more generic way to fix the problem. Plus it can be easily backported to 7.7.x branch as I can see.

**Review by Wyatt133 — APPROVED** [review]

**Review by Wyatt133 — APPROVED** [review]

**Comment by dcramer** [comment]
I'd prefer we use six here fwiw

**Comment by dcramer** [comment]
Also aside I just realized how ancient this PR is

**Comment by EvanPurkhiser** [comment]
We're using six for this now, lots of that was done in https://github.com/getsentry/sentry/commit/461204944f5a6c13159b1a4ff0b6849c17d1daa7. Closing

**Pull request closed without merging**
