### PR TITLE
fix(replays): Update event-id filter configuration to target legacy error_ids column

### PR DESCRIPTION
**Pull request by cmanallen**

### CODE REVIEW

**Review by JoshFerge — COMMENTED** [review]
sorry, what problem/issue is this PR solving?

**Comment by cmanallen** [comment]
@JoshFerge PR got a little wonky due to cascading issues.  Basically this file sums it up: https://github.com/getsentry/sentry/pull/62175/files#diff-9f130e6d47e388ac551e03e88ad0c2b6db5cffcd09ff099a6bf1c1bab16f9fc6

We need to target the ErrorIdsArray when filtering by error_id.  There was an oversight before where in some contexts we were doing that and in others we weren't.  This makes it so we filter by client provided the ErrorIdsArray in both contexts.

**Review by JoshFerge — APPROVED** [review]

**Comment by cmanallen** [comment]
Waited too long to merge this.  Its about time to _remove_ the old error_ids column!

**Comment by cmanallen** [comment]
I thought I merged master yesterday.  But that doesn't seem to be the case.  I checked the squashed commit on the master branch and it looks correct.  I don't think merging this stale PR will cause any issues.

**Pull request merged**
