### PR TITLE
Add saved searches to UI

### PR DESCRIPTION
**Pull request by dcramer**

### CODE REVIEW

**Comment by benvinegar** [comment]
Bug: refreshing the stream from a saved search URL (e.g. /sentry/earth/searches/2/) spins forever:

image

**Comment by benvinegar** [comment]
Bug: changing "Sort by" doesn't actually change the XHR (the URL does change appropriately, though).

These are XHRs fired by me while toggling between Last Seen, First Seen, Priority, etc:

image

This is from a saved search.

**Comment by dcramer** [comment]
- Fixed `sort`
- Add filler text when there are no saved searches

**Comment by benvinegar** [comment]
Todo: should probably truncate long titles ...

image

I'd also probably reduce the search box a bit to give more room for titles.

**Comment by benvinegar** [comment]
Todo: there's no feedback/error when you attempt to save a search w/ no name. We should probably say something like, "Title required."

image

**Comment by dcramer** [comment]
- fixed make default
- added confirm to delete
- added indicators to delete/make default

**Comment by dcramer** [comment]
```
Needs Triage
is:unresolved is:unassigned

Assigned to Me
is:unresolved assigned:me

*My Bookmarks
is:unresolved bookmarks:me

*New Issues
is:unresolved firstSeen.since:"now - 24h"

*Needs implemented
```

**Pull request closed without merging**
