### PR TITLE
feat(widget viewer): refactoring styles

### PR DESCRIPTION
**Pull request by doralchan**
- Removing excess styling
- Changing copy in tooltip and tooltip styling for single query 
- Adding copy in alert for multiple queries

**Before:**
Screen Shot 2022-04-06 at 7 07 14 PM
Screen Shot 2022-04-06 at 7 06 46 PM
Screen Shot 2022-04-06 at 7 06 32 PM

**After:**
Screen Shot 2022-04-06 at 7 02 00 PM
Screen Shot 2022-04-06 at 7 03 43 PM
Screen Shot 2022-04-06 at 7 03 55 PM

### CODE REVIEW

**Review by edwardgou-sentry — APPROVED** [review]
LGTM!

**Review by priscilawebdev — CHANGES_REQUESTED** [review]
this PR regresses the footer

**Before:**
image


**After:**
image

**Comment by priscilawebdev** [comment]
really like this change! thanks for updating this

Before:

image


After:
image

**Comment by priscilawebdev** [comment]
don't we want to display the question mark in case of a dropdown anymore?

**Before:**
image

**After:**
image

**Comment by doralchan** [comment]
@priscilawebdev The questionmark content was moved into the alert in the event there are multiple queries. I'll update the footer to be more mobile responsive.

**Review by priscilawebdev — APPROVED** [review]
tested locally and it looks good to me. Thanks for fixing the "responsiveness" issue 👏

**Pull request merged**
