### PR TITLE
ref(migrations): Add hints to old migrations

### PR DESCRIPTION
**Pull request by beezz**
This PR adds hints to old migrations that will soon be deleted to all onprem to upgrade past 21.6.

- https://github.com/getsentry/onpremise/issues/1016

### CODE REVIEW

**Comment by BYK** [comment]
@beezz does this mean we should release a `21.6.2` before `21.7.0`?

**Comment by beezz** [comment]
Did not mean to delete the squashed one. Will fix.

**Comment by beezz** [comment]
> Did not mean to delete the squashed one. Will fix.

Fixed.

**Review by wedamija — APPROVED** [review]
lgtm, thanks for fixing

**Comment by wedamija** [comment]
> @beezz does this mean we should release a `21.6.2` before `21.7.0`?

Yeah, we will need to. This got through CI due to a mix of two changes:
 - We squashed old migrations, which removed most of these from the squash, and correctly hinted the rest. This means that CI just runs the squash and any unsquashed migrations, and skips all the old squashed migrations that were missing the required hints.
 - We added this hints requirement to uses on `RunSQL` and `RunPython`, but then CI didn't test this for the old, unsquashed migration.

**Comment by BYK** [comment]
@wedamija I think this needs you to force-merge now? Then I'll kick off a 21.6.2 release before it is too late.

**Comment by wedamija** [comment]
@BYK I can't force merge 😬

**Pull request merged**
