### PR TITLE
WIP: iTunes Connect support for Debug Symbols

### PR DESCRIPTION
**Pull request by mitsuhiko**
We should decide what to do with this but for accounts without 2FA this can sign into ITC and we have enough methods available to poll for debug symbols there. Here is how this could work:

* you can go to the project settings page and link sentry with an itunes connect account
* there we can press a "sync" button and it shows you a list of all apps that exist and that the account has access to (similar to how travis does it)
* you enable all the apps and platforms that you want to auto pull into that project

Then we regularly poll ITC for new symbols we have not seen yet. The archives can be uniquely identified by the tuple `app_id, platform, version, build_id`. We would have to store this somewhere. Additionally the itc client that exists could be cached in memcache which would save a ton of HTTP requests for as long as the session did not expire.

@dcramer @HazAT

### CODE REVIEW

**Comment by mitsuhiko** [comment]
Separately here the motivation: while the fastlane integration is pretty good, the issue that users will run into is that it takes apple quite some time to process the debug symbols and to make them available. Early feedback we got is that events come in before someone goes in and downloads the debug symbols. Generally also even with fastlane this is a major in pain and the situation is even worse for people that do not use fastlane.

With this we could take the pain away but it would require us to test this regularly since apple might change their portal.

**Comment by dcramer** [comment]
I'm not against doing this but:

1. It needs some mocked HTTP response tests
2. We need some automated way to do test this daily

**Comment by mitsuhiko** [comment]
We will put this into a plugin instead.

**Comment by HazAT** [comment]
https://github.com/getsentry/sentry-plugins/pull/135

**Pull request closed without merging**
