### PR TITLE
feat(onboarding): Add bun onboarding docs

### LINKED ISSUE #56856: Bun Project Creation
### Problem Statement

For users setting up a Bun with Sentry there is no existing paltform to point users down the right path.

### Solution Brainstorm

For users setting up a Bun project with Sentry there should be a respective platform type, under browser?

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/pull/56913
- [ ] https://github.com/getsentry/sentry/pull/56928
```

### Product Area

Projects - Project Creation

### PR DESCRIPTION
**Pull request by AbhiPrasad**
resolves https://github.com/getsentry/sentry/issues/56856

image

### CODE REVIEW

**Review by ArthurKnaus — APPROVED** [review]
Awesome! 👍

**Review by matejminar — COMMENTED** [review]
I don't see a bun icon. Is that a me problem, or do you have it the same?
image

Based on platformicons we should have a support for it:
https://github.com/getsentry/platformicons/blob/master/src/platformIcon.tsx#L6

**Comment by AbhiPrasad** [comment]
I was able to see it locally and on `dev-ui`:

image

**Comment by matejminar** [comment]
perfect 👍

**Pull request merged**
