### PR TITLE
feat(perf-issues): update consecutive db detector to support span evidence

### PR DESCRIPTION
**Pull request by DominikB2014**
This PR makes the required backend changed to support #43278

1. Renames `PERFORMANCE_CONSECUTIVE_DB_OP` to `PERFORMANCE_CONSECUTIVE_DB_QUERIES` to be more consistent with other detectors and match UI name/enum see https://github.com/getsentry/sentry/blob/e4892f7a5f644d0d1688621e8278af35c156e867/static/app/types/group.tsx#L59

2. `PerformanceProblem.offender_span_ids` are now only the independent db queries rather then all of the consecutive db queries. 

3. `PerformanceProblem.cause_span_ids` are now all the consecutive db queries, so that we can display them in the UI under span evidence and eventually the span tree.

To understand the changes better, note that, In a set of consecutive db spans, which are non-overlapping sequential queries, Independent db spans are the ones we flag as parallelizable, aka ones that can be done independently on the other queries. More info can be found in the following [document](https://www.notion.so/sentry/Consecutive-DB-I-O-9c3b55e64a774b0f898af0e5b6832f3a)

### CODE REVIEW

**Comment by k-fish** [comment]
For posterity, can you elaborate on why/what independent queries vs. consecutive are either in PR description or in the code?

**Comment by DominikB2014** [comment]
> For posterity, can you elaborate on why/what independent queries vs. consecutive are either in PR description or in the code?

@k-fish Thanks for the suggestion! I've updated the description to make it more clear, let me know if it makes sense, or if more clarification would be benifical.

**Review by k-fish — APPROVED** [review]
@DominikB2014 okay so the cause is all the spans found including the initial one duplicated, and the 'offenders' is a subset of the ones that are potentially optimizable via parallelization? That works for me, thanks for the updated desc.

**Comment by DominikB2014** [comment]
> Yes that is correct!

**Pull request merged**
