### PR TITLE
fix(store): Wipe attachment cache unconditionally

### PR DESCRIPTION
**Pull request by untitaker**
I believe the old logic was in place from a time where we stackwalked minidumps in the store endpoint. There the logic makes perfect sense as a project without the event attachments feature would never have anything in the attachments cache.

#sync-getsentry

### CODE REVIEW

**Review by jan-auer — COMMENTED** [review]
This condition was initially introduced by @mitsuhiko in https://github.com/getsentry/sentry/pull/9393 because we were observing too many hits to the cache if we did this unconditionally. 

We will need to retain some condition most likely, although I don't know what the right one is off the bat.

Either way, we should try this on a canary first, to observe what the impact is.

**Comment by jan-auer** [comment]
Actually, thinking about this again: Soon every organization will have attachments enabled. That means, that we should try this out regardless, since we soon won't be able to optimize that anymore.

There is no way of knowing up front if an event has attachments. The only way to know is by checking the cache.

**Comment by untitaker** [comment]
I do not think that the store task has any way to determine whether the event has attachments without hitting redis at least once. This hits redis exactly once for the case there are no attachments and the index is missing or empty.

**Comment by untitaker** [comment]
we could do the following condition instead, for now:

```
event is None or <feature enabled> or <is native event>
```

**Comment by jan-auer** [comment]
Let's actually try this on a canary on Monday to assess impact. One way or the other, we'll have to accommodate for a higher frequency of these queries.

**Comment by untitaker** [comment]
no impact in prod, tested on third of traffic of save_event

**Review by jan-auer — APPROVED** [review]

**Pull request merged**
