### PR TITLE
feat(discover): Increase requested results for by day queries

### PR DESCRIPTION
**Pull request by lynnagara**
Because of the way by day graphs are generated, we should request as
many results as possible to avoid truncating data. This increases the
requested limit from 1000 to 10000.

Closes SEN-409

### CODE REVIEW

**Comment by mnoble** [comment]
Do we have any idea how Snuba will handle a 10x increase in load per request?

**Comment by lynnagara** [comment]
I was actually aiming to align the limit to the same as what we have for dashboards currently (just realised that it's actually 2000 there not 10000 though). I suspect that not many queries actually submitted by users will fall into this category (happens when aggregating over a field with a large number of values)

**Review by billyvg — APPROVED** [review]

**Comment by lynnagara** [comment]
@billyvg IIRC we reduced the dashboard limit from 10000 initially to 2000, do you recall the concerns there?

**Comment by lynnagara** [comment]
I'm going to go with a more conservative 5000 for now, we can bump this up later if we're still missing too much

**Pull request merged**
