### PR TITLE
javascript: don't explode attempting to jump to a bad query selector

### PR DESCRIPTION
**Pull request by mattrobenolt**
Fixes JAVASCRIPT-1NE

### CODE REVIEW

**Comment by mattrobenolt** [comment]
To clarify, testing this explicitly doesn't yield a broken page or anything like that, so not entirely sure if the side effects actually result in anything tangible other than it being reported to Sentry.

**Comment by macqueen** [comment]
couldn't it be helpful to know that there are bad hashes? i get that this could be from users creating bad hashes themselves, but if we accidentally are making bad links somewhere, seems like it'd be good to know about them

**Comment by mattrobenolt** [comment]
> couldn't it be helpful to know that there are bad hashes?

The difference here is that this is explicitly from a malformed hash causing the browser to raise an exception, not a hash that doesn't exist on the page. The hash that triggered this was specifically `#_=_` which comes from Google when doing SSO auth. They redirect back with this. Not sure why.

I think the value of having information here is very low imo since it's literally just reimplementing browser behavior that has existed since the 90s which wouldn't have triggered an error before.

**Comment by mattrobenolt** [comment]
The alternative is to attempt to sanitize the hash before querying on it, but I think that's little value in doing that as well, since a url fragment is not really structured and nothing prevents it from just being garbage.

**Review by macqueen — APPROVED** [review]

**Pull request merged**
