### PR TITLE
fix(integrations): Handle jira ExpiredSignatureError

### PR DESCRIPTION
**Pull request by macqueen**
fixes SENTRY-77X

This just shows a message telling the user to refresh the page. Unfortunately, we can't refresh the parent page from the iframe, so I think this is all we can do.

### CODE REVIEW

**Comment by mattrobenolt** [comment]
🙏

**Comment by mnoble** [comment]
I think you can `parent.location.reload()` to reload the parent of an iframe.

**Comment by macqueen** [comment]
@mnoble i think that's only if the site / browser doesn't block the iframe from doing it. that's what i originally tried but got `Uncaught DOMException: Blocked a frame with origin "<iframe origin>" from accessing a cross-origin frame`

**Comment by markstory** [comment]
If you control both the parent and child frame you can use `window.postMessage()` to send messages between the frames and get around cross origin issues.

**Comment by markstory** [comment]
This [MDN doc](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) has info and a few examples. This [gist](https://gist.github.com/pbojinov/8965299) also has an example.

**Comment by macqueen** [comment]
@markstory we don't control the parent -- this is iframed within jira.

**Review by benvinegar — APPROVED** [review]

**Pull request merged**
