### PR TITLE
Fix assignment notifications.

### PR DESCRIPTION
**Pull request by tkaemming**
This got broken at some point by comparing a string to an integer, this
corrects the comparison and adds a test to ensure this doesn't break again in
the future.

### CODE REVIEW

**Comment by mattrobenolt** [comment]
Is this just 100% broken? Or only broken in some scenarios?

**Comment by dcramer** [comment]
look-of-shock

**Comment by tkaemming** [comment]
> Is this just 100% broken? Or only broken in some scenarios?

Yep, broken.

**Comment by tkaemming** [comment]
(Tests passed locally, just went and merged since Travis build is stuck.)

**Pull request merged**
