### PR TITLE
fix(integrations) Compare migratable repositories as case-insensitive

### PR DESCRIPTION
**Pull request by markstory**
Old integrations have created repositories with Titlecased organization names. This prevents these repositories from being migrated to the new integrations as the names we have in our database don't match the names from the provider. Instead the frontend tries to create a new repository which creates a unique key conflict with the old repository.

I've checked the various repository integration providers we have and they require repository/project slugs to have unique lower case representations. This makes comparing repository names by lower case reasonably safe and unlikely to cause problems in the future.

Fixes ISSUE-201

### CODE REVIEW

**Review by lobsterkatie — APPROVED** [review]
Per my understanding of the problem, this seems like it will fix it. Would love @lauryndbrown to give the okay also, though, since they're more familiar with this part of the codebase.

Thanks for fixing, @markstory!

**Comment by mnoble** [comment]
oof, good catch.

Maybe we should default to comparing UUIDs when possible and fall back on comparing name? I know GitHub includes UUIDs and I suspect some others do as well, but I vaguely remember one integration not including a unique id. 🤷‍♂️

**Review by mnoble — APPROVED** [review]
I appreciate the phrase/sentence rewriting to make sense with `it` 😄

**Comment by markstory** [comment]
@mnoble We could compare the values that end up in `sentry_repositories.external_id`. Each integration exposes some form of 'id'. The sometimes case-sensitive name column is not ideal.

**Pull request merged**
