### PR TITLE
Overhaul plugin API for future React support

### PR DESCRIPTION
**Pull request by dcramer**
This is a number of fairly large changes to both the new plugin configuration as well as the old, including exposing an API for configuration all plugins.

/cc @getsentry/team

---

This change is [Reviewable](https://reviewable.io/reviews/getsentry/sentry/3986)

### CODE REVIEW

**Comment by dcramer** [comment]
This is my attempt at breaking out a lot of the unrelated changes required for #3947

**Comment by dcramer** [comment]
This is mostly done now. I do intend to add some tests based on the example plugin, but it should be code complete outside of that.

---

Review status: 0 of 38 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3986#-:-KQNunclGw-eyibWqaPu:b-b3k0mn)*

**Comment by dcramer** [comment]
Review status: 0 of 38 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[src/sentry/api/endpoints/project_details.py, line 137 \[r2\]](https://reviewable.io:443/reviews/getsentry/sentry/3986#-KQO-0H8hZu0a2lpKyXj:-KQO-0H9fb-ibnjnhAkJ:b-x115jl) ([raw file](https://github.com/getsentry/sentry/blob/27355df2d53f250d66db99e016c7391daaac4f7e/src/sentry/api/endpoints/project_details.py#L137)):*
> ```Python
>             'feedback:branding': project.get_option('feedback:branding', '1') == '1',
>         }
>         data['plugins'] = [
> ```

we probably should just add serializers for Plugin/Plugin2

---

*[src/sentry/api/endpoints/project_plugin_details.py, line 48 \[r2\]](https://reviewable.io:443/reviews/getsentry/sentry/3986#-KQO-5GoINZYQDUo3Wy5:-KQO-5GoINZYQDUo3Wy6:bj6e189) ([raw file](https://github.com/getsentry/sentry/blob/27355df2d53f250d66db99e016c7391daaac4f7e/src/sentry/api/endpoints/project_plugin_details.py#L48)):*
> ```Python
>         plugin = self._get_plugin(plugin_id)
> 
>         return Response({
> ```

re: serializer same as above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3986)*

**Comment by macqueen** [comment]
Reviewed 1 of 2 files at r1, 32 of 36 files at r2.
Review status: 33 of 38 files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

*[src/sentry/api/bases/project.py, line 58 \[r2\]](https://reviewable.io:443/reviews/getsentry/sentry/3986#-KQO-4Ss5cIAZ5JwB0MC:-KQO-4StlKenxxcHQ8V6:b1lt6c7) ([raw file](https://github.com/getsentry/sentry/blob/27355df2d53f250d66db99e016c7391daaac4f7e/src/sentry/api/bases/project.py#L58)):*
> ```Python
> 
> 
> class ProjectSettingPermission(ProjectPermission):
> ```

doesn't seem like this is used

---

*[src/sentry/api/endpoints/project_plugin_details.py, line 15 \[r2\]](https://reviewable.io:443/reviews/getsentry/sentry/3986#-KQO5dC7v32u9kXhIVr3:-KQO5dC7v32u9kXhIVr4:bbt9ijk) ([raw file](https://github.com/getsentry/sentry/blob/27355df2d53f250d66db99e016c7391daaac4f7e/src/sentry/api/endpoints/project_plugin_details.py#L15)):*
> ```Python
> ERR_ALWAYS_ENABLED = 'This plugin is always enabled.'
> ERR_FIELD_REQUIRED = 'This field is required.'
> ERR_FIELD_INVALID = 'Invalid value.'
> ```

this doesn't seem to be used

---

*[src/sentry/api/endpoints/project_plugin_details.py, line 70 \[r2\]](https://reviewable.io:443/reviews/getsentry/sentry/3986#-KQO0CtOQA5ERIlgJBqh:-KQO0CtOQA5ERIlgJBqi:b-4oo72z) ([raw file](https://github.com/getsentry/sentry/blob/27355df2d53f250d66db99e016c7391daaac4f7e/src/sentry/api/endpoints/project_plugin_details.py#L70)):*
> ```Python
> 
>         if not plugin.can_disable:
>             return Response({'detail': ERR_ALWAYS_ENABLED}, status=400)
> ```

is `detail` the key we usually use for this? seems like something we should standardize so it's easier to make sure they're displayed in the ui

---

*[src/sentry/static/sentry/app/components/forms/rangeField.jsx, line 34 \[r2\]](https://reviewable.io:443/reviews/getsentry/sentry/3986#-KQO4TneYt4rskk8Qa58:-KQO4TneYt4rskk8Qa59:b-z1poia) ([raw file](https://github.com/getsentry/sentry/blob/27355df2d53f250d66db99e016c7391daaac4f7e/src/sentry/static/sentry/app/components/forms/rangeField.jsx#L34)):*
> ```JSX
>   }
> 
>   removeSlider() {
> ```

... should this be implemented?

---

*[src/sentry/static/sentry/app/views/organizationStats/index.jsx, line 251 \[r2\]](https://reviewable.io:443/reviews/getsentry/sentry/3986#-KQNzH20k1yTR2ZU6ghj:-KQNzH20k1yTR2ZU6ghk:bv6ywim) ([raw file](https://github.com/getsentry/sentry/blob/27355df2d53f250d66db99e016c7391daaac4f7e/src/sentry/static/sentry/app/views/organizationStats/index.jsx#L251)):*
> ```JSX
>             Limited events are entries that the system threw away due to quotas
>             being hit, and Filtered events are events that were blocked
>             due to your data filters and blocklists.`)}</p>
> ```

is this supposed to be blocklists or blacklists? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3986)*

**Comment by dcramer** [comment]
Review status: 33 of 38 files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

*[src/sentry/api/endpoints/project_plugin_details.py, line 70 \[r2\]](https://reviewable.io:443/reviews/getsentry/sentry/3986#-KQO0CtOQA5ERIlgJBqh:-KQRZtrs0Fp86zG9NhZf:bfwg67v) ([raw file](https://github.com/getsentry/sentry/blob/27355df2d53f250d66db99e016c7391daaac4f7e/src/sentry/api/endpoints/project_plugin_details.py#L70)):*
<details><summary><i>Previously, macqueen (Jess MacQueen) wrote…</i></summary>
> is `detail` the key we usually use for this? seems like something we should standardize so it's easier to make sure they're displayed in the ui
</details>
Its a grab-bag. I agree we need to standardize on this. I'm open to opinions here. I think we should aim for two things:

1. A generic error message
2. param-specific error messages

---

*[src/sentry/static/sentry/app/components/forms/rangeField.jsx, line 34 \[r2\]](https://reviewable.io:443/reviews/getsentry/sentry/3986#-KQO4TneYt4rskk8Qa58:-KQRaAVX0Bn7fpgyIhDe:bys8hoz) ([raw file](https://github.com/getsentry/sentry/blob/27355df2d53f250d66db99e016c7391daaac4f7e/src/sentry/static/sentry/app/components/forms/rangeField.jsx#L34)):*
<details><summary><i>Previously, macqueen (Jess MacQueen) wrote…</i></summary>
> ... should this be implemented?
</details>
Im not sure we can actually implement it. I'll put a comment here to explain

---

*[src/sentry/static/sentry/app/views/organizationStats/index.jsx, line 251 \[r2\]](https://reviewable.io:443/reviews/getsentry/sentry/3986#-KQNzH20k1yTR2ZU6ghj:-KQRa-hbL-YoZdcm56aB:b-pyhfrx) ([raw file](https://github.com/getsentry/sentry/blob/27355df2d53f250d66db99e016c7391daaac4f7e/src/sentry/static/sentry/app/views/organizationStats/index.jsx#L251)):*
<details><summary><i>Previously, macqueen (Jess MacQueen) wrote…</i></summary>
> is this supposed to be blocklists or blacklists? 
</details>
havent rebased this branch yet, but you can ignore this as its unrelated

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3986)*

**Comment by dcramer** [comment]
Review status: 26 of 36 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/sentry/api/endpoints/project_details.py, line 137 \[r2\]](https://reviewable.io:443/reviews/getsentry/sentry/3986#-KQO-0H8hZu0a2lpKyXj:-KQRaZ-elkmDtl3vHUCj:b-896fix) ([raw file](https://github.com/getsentry/sentry/blob/27355df2d53f250d66db99e016c7391daaac4f7e/src/sentry/api/endpoints/project_details.py#L137)):*
<details><summary><i>Previously, dcramer (David Cramer) wrote…</i></summary>
> we probably should just add serializers for Plugin/Plugin2
</details>
Done.

---

*[src/sentry/api/endpoints/project_plugin_details.py, line 15 \[r2\]](https://reviewable.io:443/reviews/getsentry/sentry/3986#-KQO5dC7v32u9kXhIVr3:-KQRaYDQSDYe7Dy1qEgf:b-896fix) ([raw file](https://github.com/getsentry/sentry/blob/27355df2d53f250d66db99e016c7391daaac4f7e/src/sentry/api/endpoints/project_plugin_details.py#L15)):*
<details><summary><i>Previously, macqueen (Jess MacQueen) wrote…</i></summary>
> this doesn't seem to be used
</details>
Done.

---

*[src/sentry/api/endpoints/project_plugin_details.py, line 48 \[r2\]](https://reviewable.io:443/reviews/getsentry/sentry/3986#-KQO-5GoINZYQDUo3Wy5:-KQRaZi05eWWIA0g8yq9:b-896fix) ([raw file](https://github.com/getsentry/sentry/blob/27355df2d53f250d66db99e016c7391daaac4f7e/src/sentry/api/endpoints/project_plugin_details.py#L48)):*
<details><summary><i>Previously, dcramer (David Cramer) wrote…</i></summary>
> re: serializer same as above
</details>
Done.

---

*[src/sentry/static/sentry/app/components/forms/rangeField.jsx, line 34 \[r2\]](https://reviewable.io:443/reviews/getsentry/sentry/3986#-KQO4TneYt4rskk8Qa58:-KQRa_RP1PbWlL8sYWDl:b-896fix) ([raw file](https://github.com/getsentry/sentry/blob/27355df2d53f250d66db99e016c7391daaac4f7e/src/sentry/static/sentry/app/components/forms/rangeField.jsx#L34)):*
<details><summary><i>Previously, dcramer (David Cramer) wrote…</i></summary>
> Im not sure we can actually implement it. I'll put a comment here to explain
</details>
Done.

---

*[src/sentry/api/bases/project.py, line 58 \[r2\]](https://reviewable.io:443/reviews/getsentry/sentry/3986#-KQO-4Ss5cIAZ5JwB0MC:-KQRaa6GcXN-bP03LQpu:b-896fix) ([raw file](https://github.com/getsentry/sentry/blob/27355df2d53f250d66db99e016c7391daaac4f7e/src/sentry/api/bases/project.py#L58)):*
<details><summary><i>Previously, macqueen (Jess MacQueen) wrote…</i></summary>
> doesn't seem like this is used
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3986)*

**Comment by dcramer** [comment]
This has a backwards incompat change: get_configure_plugin_fields no longer has a request object. I looked at sentry-plugins and it seems unused, so as a followup we'll remove it from there, then fully remove it here (instead of sending None)

---

Review status: 25 of 36 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3986#-:-KQRb3r6_DL3Ng19YQx1:bb1x5bb)*

**Comment by dcramer** [comment]
I think this is done now. It's got some base tests for the config and endpoints, and I believe all concerns are resolved.

---

Review status: 25 of 37 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3986#-:-KQRz1VJ8FoMbis2suOp:bzd9yls)*

**Comment by macqueen** [comment]
Reviewed 1 of 2 files at r1, 1 of 36 files at r2, 12 of 12 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3986)*

**Pull request merged**
