### PR TITLE
py3: Update boto3 & botocore versions

### LINKED ISSUE #13705: Ancient boto3 & botocore versions
Any particular reason these are pinned? This gets in the a way a bit as I am developing an AWS plugin and the old boto3 api is lacking in some places. 
Thanks!

### PR DESCRIPTION
**Pull request by mikeroll**
boto3==1.4.5 is just too old - some AWS resource definitions are outdated, the old docs are not available, this causes some trouble when developing AWS-enabled plugins.

Fixes GH-13705

### CODE REVIEW

**Comment by mattrobenolt** [comment]
We need to make sure this doesn't break with our uses of boto. We use this for SQS at minimum, and I'm not sure what else. We also rely on a specific string in an error message.

https://github.com/getsentry/sentry-plugins/blob/master/src/sentry_plugins/amazon_sqs/plugin.py#L83

So we need to make sure all of this still works correctly and the strings are still the same.

**Comment by mattrobenolt** [comment]
This also means we'll need to bump here: https://github.com/getsentry/sentry-plugins/blob/master/setup.py#L35-L36 or the requirements will conflict.

**Comment by mikeroll** [comment]
@mattrobenolt searching `boto3` in the whole org [yields](https://github.com/search?q=org%3Agetsentry+org%3Agetsentry+extension%3Apy+boto3&unscoped_q=org%3Agetsentry+extension%3Apy+boto3) just these two cases (`sentry` and `sentry-plugins`). Would that be a good indication of the usage?

The PR for the plugins is on the way, and I'll double check that error string, thanks for the heads up!

**Comment by BYK** [comment]
@mattrobenolt - according to https://botocore.amazonaws.com/v1/documentation/api/latest/index.html#upgrading-to-1-12-0 and https://github.com/boto/boto3/blob/develop/CHANGELOG.rst, these upgrades should be fully bw-compatible.

Is there a way to safely test these?

**Comment by mattrobenolt** [comment]
Not as far as I know other than reading their docs and making sure the public APIs didn't change.

**Comment by BYK** [comment]
Superseded by #22543

**Pull request closed without merging**
