### PR TITLE
fix(perf): Generate instrumentation gap spans before spans groups

### PR DESCRIPTION
**Pull request by gggritso**
There's a bug in the span waterfall model in which if there's a long gap between a span and a _span group_, we don't show a "Missing span instrumentation" span! As far as I can tell, this is due to a small gap (ha) in logic. I went through and made sure that we also calculate gaps before creating a collapsed span group, and before an expanded span group.

**e.g.,**
Screenshot 2024-01-19 at 3 23 17 PM

### CODE REVIEW

**Review by 0Calories — APPROVED** [review]
Great catch, George! This seems to be working well, I tested this out locally by grabbing a sample transaction and modifying its shape, then injecting it locally. I’ve confirmed that the gap span is now appearing immediately before an auto group of spans, and it also is able to appear after one.

### Before
Screenshot 2024-01-22 at 12 21 02 AM

### After
image


One thing I noticed, and this may be a bit of a nitpick, is that gap spans will not appear within an auto group of spans once you expand it. There’s a bunch of different specific cases that have their own branch in logic in the span tree, which makes debugging it a nightmare and it’s easy to miss things like this!

image

**Comment by gggritso** [comment]
@0Calories that's a really good catch! Is there an easy way for me to reproduce this locally? I'm tempted to just merge this PR as-is for now, and come back to the case you found if it shows up in the wild. I'm guessing it's pretty rare to have an instrumentation gap in a set of grouped spans, since they're happening in a loop

**Comment by 0Calories** [comment]
@gggritso I just made a custom transaction object and adjusted the timestamps to create the patterns you see in that screenshot, I'll send you a message with the code I used!

**Comment by 0Calories** [comment]
But yes, this is definitely a very rare case and it's probably fine to just address it later

**Pull request merged**
