### PR TITLE
Add Convex to onboarding

### PR DESCRIPTION
**Pull request by nipunn1313**
https://www.convex.dev/ is a backend-as-a-service that can run serverless functions. Sentry integration for exception reporting comes out of the box via a configuration.

https://github.com/getsentry/sentry/assets/1300387/cdced079-77ab-4b0c-812b-e06476853979

Depends on https://github.com/getsentry/platformicons/pull/150

There is also a page on sentry's side here
https://sentry.io/integrations/convex/

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Comment by nipunn1313** [comment]
Hello - I am waiting for a Sentry team member to take a look.

**Comment by nipunn1313** [comment]
Hello sentry! I believe this was incorrectly closed by the bot. Could someone from the sentry team take a look? Perhaps @ArthurKnaus could help (just looking at history in this area of the codebase). Thanks.

Happy to provide more context or chat offline if that would be helpful. Thanks.

**Comment by stephanie-anderson** [comment]
I'll have a look to sort this out, @nipunn1313

**Comment by nipunn1313** [comment]
Thanks @stephanie-anderson - let me know if there's anything I can do from my side.

I can rebase to resolve conflicts.

**Pull request closed without merging**
