### PR TITLE
ref(ui): Replace deprecatedTag component with Tag component

### PR DESCRIPTION
**Pull request by priscilawebdev**
Below you can see the before and after of replacements in places that are not very common in the UI:

**RequestLog:**

_Before:_

image

_After:_

image

**DebugFileRow**

_Before:_

image

_After:_

image

**UnhandledTag**

_Before:_

image

_After:_

image

**ProviderItem**

_Before:_

image

_After:_

image

**Sentry App Details Modal**

_Before:_

image

_After:_

image

**Invitation Row**

_Before:_

image

_After:_

image

### CODE REVIEW

**Review by markstory — APPROVED** [review]
Code changes look good.

**Review by doralchan — APPROVED** [review]

**Comment by matejminar** [comment]
@doralchan @robinrendle I think unhandled here feels a bit heavy?

image

**Comment by doralchan** [comment]
I think unhandled in Issues looks good - ship it 🚢

**Review by robinrendle — APPROVED** [review]
This all looks great but I think we should remove Tooltips from Tags and keep them separate. The Tag component should do Tag stuff, the Tooltip component should do Tooltip stuff.

These are atomic components that shouldn’t be tied together at all. We can do that in a separate PR though, as I don’t think it should block this work for now.

**Pull request merged**
