### PR TITLE
ref(discover2) Remove dead groupid param

### PR DESCRIPTION
**Pull request by markstory**
We don't use (and have no immediate plans to use) the group query parameter. This code doesn't have any tests either.

Refs SEN-887

### CODE REVIEW

**Review by dashed — APPROVED** [review]
Looks good to me.

**Comment by wedamija** [comment]
This is still used by incidents at the moment

**Comment by dashed** [comment]
@wedamija thanks. going to retract my approval.

**Review by dashed — DISMISSED** [review]
retract.

**Comment by wedamija** [comment]
`issue.id:987955208 issue.id:1142633419 issue.id:959531963` works fine, I've made a ticket here https://getsentry.atlassian.net/browse/SEN-928. Since we're just removing this from new events I think this is actually fine, just don't remove it from legacy until that ticket is finished.

**Review by wedamija — APPROVED** [review]

**Comment by markstory** [comment]
> Since we're just removing this from new events I think this is actually fine, just don't remove it from legacy until that ticket is finished.

Sounds good. I was going to leave old-events list alone as I'm not as familiar with its consumers and input set.

**Pull request merged**
