### PR TITLE
ref(ui): Update Sentry to js sdk 7 beta

### PR DESCRIPTION
**Pull request by k-fish**
### Summary
This will let us try out the new beta sdk on Sentry itself to find out if we have any issues earlier and give feedback to the sdk team.

### CODE REVIEW

**Review by billyvg — DISMISSED** [review]
No breaking changes?

**Comment by smeubank** [comment]
@billyvg there are breaking changes, but I am not sure which ones impact Sentry so please refer to the change log and let us know what you think of those as well. Since we also want to know if the way we communicate breaking changes is clear

**Comment by k-fish** [comment]
@smeubank, I've gone over the migration guide w.r.t Sentry js and updated it now to fix the breaking change. The migration guide had pretty much all our breaking changes in it, there were only a couple notes.

The only thing still needing work is that it looks like we have a breaking change because our jest environment is using deprecated sdk api as well, so need to fix that, if someone from the sdk could confirm that child->startChild is correct? I don't see it in the guide. See the linked PR below.

Only other update for the migration guide is that maybe we could improve clarity for the `BrowserClient` changes since there are two sections referring to it. I was mistakenly looking at [less-sync-api](https://github.com/getsentry/sentry-javascript/blob/50361b68d3b532e9a6b807e281922586a1e7ec76/MIGRATION.md#less-async-api ) section for a minute before finding the[ explicit client options](https://github.com/getsentry/sentry-javascript/blob/50361b68d3b532e9a6b807e281922586a1e7ec76/MIGRATION.md#explicit-client-options), might be worth adding a link in less-async-api if that's the same relation? I'm not 100% what the less-async-api section migration path is, seems a bit unclear in general since there is no action item.

**Comment by billyvg** [comment]
@k-fish published `1.7.1` that fixed a syntax error

**Comment by lforst** [comment]
> if someone from the sdk could confirm that child->startChild is correct? I don't see it in the guide. See the linked PR below.

This looks kinda weird. I can't find any reference to `child()` in the SDK whatsoever - not even when going back to old versions. Is it possible that this doesn't reference SDK code at all? 🤔 

> I'm not 100% what the less-async-api section migration path is, seems a bit unclear in general since there is no action item.

The less-async-api section is part of the migration guide from 4.x -> 5.x/6.x. I sadly don't have much context to share here. Is this relevant for the v7 version bump? If it is, let me know and I'll investigate further!

We will discuss creating a code mod for the major -  definitely an awesome suggestion.

---

Thank you so much for helping us dogfood this release 🙏  - really important to get some early feedback in as this is a huge update!

If there's anything else you need from the SDK team for getting this merged in, feel free to ping me :)

**Comment by billyvg** [comment]
Ah need to apply this to getsentry too

**Comment by AbhiPrasad** [comment]
We just released a new beta: https://www.npmjs.com/package/@sentry/browser/v/7.0.0-beta.1

This shouldn't change anything with the migration though (and has the LCP fixes merged in!)

**Comment by k-fish** [comment]
Anyone want to give an approve?

**Review by AbhiPrasad — APPROVED** [review]

**Pull request merged**
