### PR TITLE
fix(settings): Handle Manager access to configure auth provider

### PR DESCRIPTION
**Pull request by mikellykels**
Enable the configure button for Auth Providers for the Manager role and allow the Manager role to configure an auth provider. The Alert displays that Managers and Owners can edit these settings, but configure is disabled for Managers.

[Fixes ISSUE-854](https://getsentry.atlassian.net/browse/ISSUE-854)

**Before:**
- Alert displays that Managers or Owners can make edits to the Auth page (logged in as a Member in the screenshot)
Screen Shot 2020-06-11 at 1 24 09 AM

- As a Manager, the configure button is still disabled (logged in as a Manager in the screenshot)
Screen Shot 2020-06-11 at 1 22 35 AM

**After:**
- Enable the Configure button when the user role is Manager
Screen Shot 2020-06-11 at 12 03 32 PM

### CODE REVIEW

**Comment by leedongwei** [comment]
Tagging @slohmes for review because they did some recent work with auth providers.

**Review by slohmes — APPROVED** [review]
nice! It'd be nice to have tests to cover the different behavior based on permissions, but I'm guessing there weren't any tests for the previous functionality, so I leave it to your discretion.

**Comment by mikellykels** [comment]
Yeah, I don't think I saw any tests for this, but I think there should be 😅 Let me see if I can write some, at least for this!

**Review by slohmes — APPROVED** [review]
Awesome, thank you!

**Pull request merged**
