### PR TITLE
py38: Django 2.2

### PR DESCRIPTION
**Pull request by joshuarli**
Notable PRs: just a few small ones this time.

Prerequisite testing:

- X-Django model pickling testing (done), see https://github.com/getsentry/sentry/tree/joshuarli/test-x-django-pickles
- LAST_VERIFIED_DJANGO_VERSION verification (done)

### CODE REVIEW

**Comment by EvanPurkhiser** [comment]
Is it just this simple, will it just work?

**Review by wedamija — APPROVED** [review]
approved for staging

**Comment by joshuarli** [comment]
> Is it just this simple, will it just work?

Don't jinx me Evan.

**Comment by joshuarli** [comment]
> approved for staging

Dan wrong PR. lol

**Pull request merged**
