### PR TITLE
feat(perf-issues): don't use span hash for fingerprinting consecutive http

### PR DESCRIPTION
**Pull request by DominikB2014**
Relying on span hashes rn to fingerprint is brittle, especially with span url parametrization potentially changing them.
This PR uses the url path (mostly copied over from n plus one api calls), in order to fingerprint the urls.

I think a future task, it would be good to share this code (a fingerprint http span function).

### CODE REVIEW

**Comment by gggritso** [comment]
Makes sense to me! How much trouble would it be to re-use the regex and parameterization code from N+1 API Calls? If you don't think they'll diverge, it'd be better to extract that stuff, put it in `base.py` and import it into both detectors rather than copy-pasta

**Comment by DominikB2014** [comment]
> Makes sense to me! How much trouble would it be to re-use the regex and parameterization code from N+1 API Calls? If you don't think they'll diverge, it'd be better to extract that stuff, put it in `base.py` and import it into both detectors rather than copy-pasta

Not much trouble, I just didn't give it too much thought tbh. I don't see how they would diverge, I can make the change.

**Comment by DominikB2014** [comment]
@gggritso I updated to share the parameterization code, and also the fingerprinting code.
Lmk if you have any concerns over the fingerprinting code, but it shouldn't affect n plus one api calls detector.

**Comment by gggritso** [comment]
@DominikB2014 LGTM, the fingerprints are covered by tests, so it should be fine 👌🏻

**Review by gggritso — APPROVED** [review]
👍🏻

**Pull request merged**
