### PR TITLE
fix(projects): Signal project creation after the transaction is committed

### PR DESCRIPTION
**Pull request by phacops**
This aims to fix https://getsentry.atlassian.net/browse/INGEST-1348

### CODE REVIEW

**Review by lynnagara — APPROVED** [review]
Thanks

**Review by wedamija — CHANGES_REQUESTED** [review]
This will fix the issue, but it means that everything that happens on a `project_created` event now runs outside of a transaction. I'm not sure if that's our desired behaviour here. For example, now we're not guaranteed that the audit entry will be created.


I think that what might be better is defer the task that fired a cache update request to run after any transactions using `on_commit`: https://github.com/getsentry/sentry/blob/57fa2fca83f2f8ea3b15ca6606cc8474e0aa7da4/src/sentry/tasks/relay.py#L142-L148

cc @untitaker

**Review by untitaker — COMMENTED** [review]
This signal is not directly responsible for triggering the update_config_cache task. It would be better to detect an ongoing transaction in either `schedule_config_cache` or all models' `post_save` hook, and defer the scheduling then as Dan said. I don't have a solid grasp of what exactly within this transaction triggers the projectoption updates that are responsible for the errors we see so I can't speak to whether this fix will be effective at all.

**Comment by dashed** [comment]
@phacops can you add a test?

**Comment by untitaker** [comment]
successor pr: https://github.com/getsentry/sentry/pull/35523

thanks @phacops for attempting a fix in a more timely manner than that though!

**Pull request closed without merging**
