### PR TITLE
chore(discover) Update field list with python code.

### PR DESCRIPTION
**Pull request by markstory**
Update the field lists used in the discover UI to match the public schema defined in python. A few fields have been omitted as they are deprecated or have better replacements via field aliases.

### CODE REVIEW

**Review by evanh — APPROVED** [review]
I assume the FUNCTIONS from event_search will end up here with your column builder changes?

**Comment by markstory** [comment]
@evanh Yes. I think we'll need to move the existing functions to the improved function parser as well. I then plan on building a similar but simpler implementation of that for the client side.

**Review by dashed — APPROVED** [review]
Looks good to me 👍

**Comment by dashed** [comment]
Did you automate this process?

**Comment by markstory** [comment]
> Did you automate this process? 

No. It took all of 5 minutes to do manually. Automating it would have taken ~1hr or more, and then required additional updates each time either file changed. The return on investment did not look promising.

**Pull request merged**
