### PR TITLE
[mocks] general improvements

### PR DESCRIPTION
**Pull request by dcramer**
- randomize commits
- add ip/name to users
- add deploy activity item
- expand users in events

#nochanges

### CODE REVIEW

**Comment by dcramer** [comment]
This pulls most of our improvements from Hackweek out (barring EventUser and frequency mock changes).

**Comment by dcramer** [comment]
ill note that this breaks sentry if you dont have sentry-plugins installed, but tbh who cares

**Review by mattrobenolt — APPROVED** [review]
Not sure I see how this requires sentry-plugins.

**Comment by dcramer** [comment]
@mattrobenolt jk it already required github (due to the repository provider) - i think i just assumed that was an addition here but its not

**Pull request merged**
