### PR TITLE
fix: restore Alert on performance landing

### PR DESCRIPTION
**Pull request by alxu-sentry**
I think this was accidentally lost in #17582. Table accepts setError but
doesn't do anything with it, probably because DiscoverQuery (then EventsV2)
didn't support it.

### CODE REVIEW

**Review by Zylphrex — COMMENTED** [review]
So the performance landing page already includes an error message in the corner, which I do think is possibly too small. Though I'm not sure about including the same message twice on the same page so we should think about consolidating it into a single error message.

**Comment by alxu-sentry** [comment]
> So the performance landing page already includes an error message in the corner, which I do think is possibly too small. Though I'm not sure about including the same message twice on the same page so we should think about consolidating it into a single error message.

More backstory:

This PR is specifically a response to https://github.com/getsentry/sentry/pull/24484#discussion_r596029807, tl;dr "you can copy and paste the error", "no actually you can't always". Issues and discover have Alert components, so you can. Perf landing, perf summary, and metric alert setup don't; the former shows a toast and the latter just spins forever.

I think perf landing previously had an Alert, but it was accidentally broken. It doesn't make sense to keep Alert half-implemented though.

The toast comes from https://github.com/getsentry/sentry/blob/master/src/sentry/static/sentry/app/components/charts/eventsRequest.tsx#L236, and it seems like a pain to push setError down into there. I agree that having two errors is a little noisy, but I don't think it's a high priority to fix immediately.

**Comment by Zylphrex** [comment]
@alxu-sentry rather than pushing `setError` all the way down into `EventsRequest`, can we add a prop to disable the toast in `EventsRequest` instead?

**Comment by alxu-sentry** [comment]
> @alxu-sentry rather than pushing `setError` all the way down into `EventsRequest`, can we add a prop to disable the toast in `EventsRequest` instead?

I think we can, but I'm not sure it's a good idea. What if the event-stats fails but eventsV2 succeeds?

**Comment by Zylphrex** [comment]
> I think we can, but I'm not sure it's a good idea. What if the event-stats fails but eventsV2 succeeds?

For the performance landing page, the `event-stats` endpoint always performs a simple timeseries query. So afaict, in most (if not all) cases, `eventsv2` should fail alongside `event-stats`.

And if an unexpected error occurs, these should be forwarded to Sentry where we would be notified.

**Comment by alxu-sentry** [comment]
Turns out it was inconsistent anyways because histogram chart doesn't show an error, so I think it's fine to do it the way you're suggesting.

**Review by Zylphrex — APPROVED** [review]

**Pull request merged**
