### PR TITLE
chore: remove examples/

### PR DESCRIPTION
**Pull request by joshuarli**
It's always nice to clean up top-level stuff. This dir was introduced in 2017 in https://github.com/getsentry/sentry/pull/4164 and then never modifed afterwards (excluding sweeping formatting changes), and it doesn't seem to be useful.

### CODE REVIEW

**Comment by EvanPurkhiser** [comment]
I'm fine w/ removing this.

Do we think any of this is useful @dcramer ?

**Review by BYK — APPROVED** [review]
yes please

**Comment by dcramer** [comment]
Arent these still valid?

Why are we removing stuff that works fine?

**Comment by dcramer** [comment]
Like, I get that you all like deleting code, but more often than not, its not a good spend of time, especially when its code that is still valid (even if not "actively used").

**Comment by joshuarli** [comment]
Well, it's top-level and there isn't any clear documentation on why it's useful AFAICT. Those are my arguments. It only took me a few minutes to assess this.

**Comment by dcramer** [comment]
Its an example, its for setting up an oauth consumer on Sentry. What is not clear about that?

I'm not sure if its valuable or not, or the level of value it currently has. For all I know 1000 people look at it a day. It could also be 0. The point I'm making is that removing this code is no different than not removing it, other than if it was valuable to anyone, its now gone.

There is a lot of history to Sentry, and just because you don't see immediately context for something doesn't mean it isn't important.

If anything, no one in this thread should be making this decision, as it is outside of your scope of ownership. It should be up to the ecosystem team if they want to remove this, if they want to move it somewhere else, or if they want to kick this can down the road.

**Comment by BYK** [comment]
@joshuarli are we able to close this?

**Pull request closed without merging**
