### PR TITLE
fix inclusivity issue in event.timestamp tags and rewrite query parser

### PR DESCRIPTION
**Pull request by travisoneill**
Fixes issue #5121 and refactors 'parse_query' to get rid of that enormous if/else block.  Behaviors for each tag type have been moved into their own methods that contain instructions for how that specific tag modifies the results dictionary returned by 'parse query'.  Tags are now tokenized by the 'tokenize_tag' method and passed in with the results dictionary as arguments to the methods for a tag.  I think this change will make it easier to add new tags since each tag behavior is now modular.  

The inclusivity behavior for '+' and '-' operators seems strange and there is a TODO in there: 
```
TODO(dcramer): currently inclusivity is not controllable by the query
as from date is always inclusive, and to date is always exclusive
```
If you tell me what functionality you want here, I can add it.

### CODE REVIEW

**Comment by mattrobenolt** [comment]
@travisoneill do you know why the tests are failing?

**Comment by travisoneill** [comment]
@mattrobenolt These are the failures:
tests/sentry/api/endpoints/test_project_index.py::ProjectsListTest::test_id_query
tests/sentry/api/endpoints/test_project_index.py::ProjectsListTest::test_slug_query 

The error is that the api is returning too many results from the queries.  I have not yet been able to figure out the cause as I am unable to print to the console from inside the search/utils.py code during the test run.  Haven't had that much time to mess with it yet, but I'm going to take another shot this weekend.

**Comment by travisoneill** [comment]
@mattrobenolt  I'm completely stumped.  The return value from the 'parse_query' method that I changed is is exactly the same as it is on master for the queries sent in the failing tests.  And you can see from the diffs that I didn't change any files other than that and its tests, so I have no idea what could be causing this.  Do you have any idea why this would happen?

**Comment by travisoneill** [comment]
@mattrobenolt Found it!  That one endpoint is calling 'tokenize_query' instead of parse query like the others and I changed some behavior there thinking it was only a helper method for 'parse_query'.  Will fix and add unit tests for this as well.

**Comment by mattrobenolt** [comment]
@travisoneill I'm watching along, but lemme know when you're ready for me to review. :)

**Comment by travisoneill** [comment]
@mattrobenolt Got it passing now.  Ready for review.  Might need more comments to be readable, though.  Here is an overview of how it works:

Question:  Is the 'age' tag supposed to have identical behavior to the 'first_seen' tag?  That's how it was before, I changed it, but then realized that it might have been intended behavior.

tokenize_tag:310 - takes tags as a string and splits them into tokens to handle operators like '>', '+', and 'h' (on age tags)

parse_query:414 - uses tokenized tags to look up special tag behaviors from the special_tag_behaviors dictionary (line 427).  Each special tag behavior contains logic for how the results dictionary is to be modified based on the value and operators in the tokenized_tag.  If there is no entry in the special tag behaviors dictionary the default '_default_tag' method is used. 

_parse_timestamp:345 - returns timestamp from the string value of a tag based on the operators.  Uses _scale_time:368 to handle time interval ('m', 'h', 'd', 'w')  if an integer value is provided as with a 'age:-24h' tag.

**Comment by travisoneill** [comment]
@mattrobenolt Did you get a chance to take a look at the code?

**Comment by kmcminn** [comment]
bump

**Comment by BYK** [comment]
Closing due to staleness. I think all this stuff is replaced by Snuba so I see no potential to somehow revive this PR and merge it.

Thanks a lot for all the effort you've put in and apologies for not responding to this in a timely manner in the past. <3

**Pull request closed without merging**
