### PR TITLE
need files in this folder such as jsx

### PR DESCRIPTION
**Pull request by MaxBittker**

### CODE REVIEW

**Comment by MaxBittker** [comment]
still looking into this, but i think that static may be matching  `src/sentry/static` paths

**Comment by MaxBittker** [comment]
since vscode update

**Review by dcramer — APPROVED** [review]
if you can confirm this is fine it seems good to me

(update commit message though)

**Comment by MaxBittker** [comment]
thinking this was slightly wrong, should be `static/`

**Pull request merged**
