### PR TITLE
Use the right variable for emails being queued.

### LINKED ISSUE #3493: Don't log empty emails.
We send notifications through django mail that can possibly go out to no one. It's totally fine, but it probably isn't worth logging.

### PR DESCRIPTION
**Pull request by JTCunning**
cc @getsentry/infrastructure 

Fixes #3493.

### CODE REVIEW

**Comment by mattrobenolt** [comment]
Hmm, what's happening to cause empty emails to get here in the first place? Shouldn't we be not even attempting to send them?

**Comment by mattrobenolt** [comment]
I just think these empty "To" addresses should be filtered even before it gets to this point.

**Comment by mattrobenolt** [comment]
That seems better. :+1:

**Comment by JTCunning** [comment]
Meatspaced.

Turns out I was using the wrong variable for `to` and it can turn out to be empty when users are added to the `MessageBuilder`.

**Pull request merged**
