### PR TITLE
fix(discover) - Fixing style issues from moving errors around

### PR DESCRIPTION
**Pull request by wmak**
- This adds back padding removed during #16798

### CODE REVIEW

**Review by markstory — APPROVED** [review]
Looks good. Percy diffs look better.

**Review by dashed — APPROVED** [review]
Looks good to me 👍

**Comment by dashed** [comment]
Adding Dora for UX/UI lint.

**Comment by wmak** [comment]
Kept no text error centered:
image

With text its left aligned:
image

**Review by billyvg — APPROVED** [review]
lgtm!

**Review by doralchan — APPROVED** [review]

**Pull request merged**
