### PR TITLE
feat(replay): support replay dataset in snuba tagstore.get_tag_keys

### PR DESCRIPTION
**Pull request by aliu39**
A change to the backend of the organization_tags endpoint allowing it to support replays. Context at https://github.com/getsentry/sentry/pull/75878

### CODE REVIEW

**Comment by aliu39** [comment]
This might require more complex aggregations like in replay/query.py, `query_replay_dataset_tagkey_values`

Also need to disable sampling ("turbo" option) in tagstore.get_tag_keys - replays doesn't support this

**Comment by aliu39** [comment]
Figured out a SQL clickhouse query, just need to implement it with Snuba SDK:
```
SELECT
    (arrayJoin(arrayMap(i -> (i, tags.key[i]), arrayEnumerate(tags.key))) AS key_enum).2 AS key, 
    uniq((arrayJoin(arrayMap(i -> (i, tags.value[i]), arrayEnumerate(tags.value))) AS val_enum).2) AS totalValues
FROM
    replays_local
WHERE
    key_enum.1 = val_enum.1
GROUP BY
    key
```

**Comment by jas-kas** [comment]
Reported in [JAVASCRIPT-2VX1](https://sentry.sentry.io/feedback/?feedbackSlug=javascript%3A5874375965&project=11276)

**Comment by jas-kas** [comment]
Reported in [JAVASCRIPT-2W01](https://sentry.sentry.io/feedback/?feedbackSlug=javascript%3A5900621324&project=11276)

**Comment by aliu39** [comment]
Instead of writing a custom query just for replays, let's enhance our entity config. Going to track this in https://github.com/getsentry/sentry/issues/78531

**Pull request closed without merging**
