### PR TITLE
test(events): Add tests for group events view

### PR DESCRIPTION
**Pull request by lynnagara**

### CODE REVIEW

**Review by billyvg — COMMENTED** [review]
Does this test case catch the bug that was fixed in #10144 ?

**Comment by lynnagara** [comment]
@billyvg It didn't exactly test that, I added another example that hopefully captures that functionality better

**Review by billyvg — APPROVED** [review]
Any ideas on how we can have better testing around the environment selector? It seems to have caused issues in the past too.

**Comment by lynnagara** [comment]
I think Selenium tests would be the better way

**Pull request merged**
