### PR TITLE
Dev createuser api

### PR DESCRIPTION
**Pull request by Venus713**
added an api to create the user.

### CODE REVIEW

**Comment by Venus713** [comment]
Hi @markstory 
If Vercel is disabled for external contributors, then how should I pass the above failing checks?

**Comment by markstory** [comment]
>  If Vercel is disabled for external contributors, then how should I fix the failing issue in my pull request?

You don't. Vercel passing is not required.

**Comment by markstory** [comment]
How do you see this API being used? We don't already have an API for this as the organization invitation flow lets users be added in bulk, or you can use an SSO provider to entirely side step needing to create users manually.

**Comment by ecmadeveloper** [comment]
Hi @markstory 
Yeah, honestly I have been wondering if this case is worth to be considered in practice. But this issue has been kept open for long and someone asked me to take one to resolve. That was the reason why I wanted to resolve this issue.
The purpose of this API is to let super users create users without having to visit admin page or by implementing any 3rd party web dashboard to manage users.
Finally the cases (except the `vercel` thing) are successfully passed and looks like ready to be merged.

Thanks,

**Pull request closed without merging**
