### PR TITLE
ref(context-logos): replaced pngs with svgs

### PR DESCRIPTION
**Pull request by doralchan**
- Replaced pngs and large svgs with compressed svgs
- Added Dell, Node, UC, Motorola and Samsung

Screen Shot 2021-03-14 at 10 25 24 AM

**Before:**
Screen Shot 2021-03-14 at 10 34 12 AM

**After:**
Screen Shot 2021-03-14 at 10 33 16 AM

### CODE REVIEW

**Review by bruno-garcia — APPROVED** [review]
RSLGTM

**Comment by bruno-garcia** [comment]
I've raised #24440 to verify we can actually get the Samsung and Motorola logs show up

**Comment by dashed** [comment]
@doralchan your screenshots have no logo for cpython. Should the python logo be re-used for the context logos for python/cpython?

**Comment by priscilawebdev** [comment]
Great Work @doralchan 👏 I just noticed that we don't have the internet explorer logos in the 8 and 9 version. Can we please add them?

**Review by priscilawebdev — APPROVED** [review]

**Pull request merged**
