### PR TITLE
fix: accept non-str keys on autofix

### PR DESCRIPTION
**Pull request by anonrig**
Fixes https://sentry.sentry.io/issues/5326989067/?project=1&referrer=github-pr-bot

### CODE REVIEW

**Comment by anonrig** [comment]
@armenzg It seems you reproduced this problem. According to JSON specification, we shouldn't accept key's that are not string, but for the sake of fixing this issue, I added the fix.

**Comment by armenzg** [comment]
Bull's eye 🎯 😄

**Review by asottile-sentry — APPROVED** [review]
what's weird is it looks like all the keys _are_ strings -- unless there's something funky in `serialized_event` that I'm not seeing in the sentry error

**Review by jennmueng — APPROVED** [review]
yeah second @asottile-sentry, looks like all the immediate keys are strings, probably something with the serialized event?

**Pull request merged**
