### PR TITLE
Addition of typescript-eslint/consistent-type-imports rule 

### PR DESCRIPTION
**Pull request by anonrig**
This pull request proposes the addition of the `@typescript-eslint/consistent-type-imports` eslint rule.

The `consistent-type-imports` rule enforces consistent usage of type imports. This could improve the comprehension and clarity of our code by clearly distinguishing between type imports and value imports. 

Some types are large or bring in lots of dependencies, this rule could potentially improve bundling performance by ensuring large types aren't accidentally included in the JavaScript output.
  
Please review this change and provide your feedback.

---

Note: The `consistent-type-imports` rule in `typescript-eslint` encourages use of type-only imports (`import type X from '...';`) when importing only types. This is especially beneficial in large projects, as not importing code when it's not needed can reduce complexity in dependency graphs and improve performance by making the emitted JavaScript bundle smaller.

### CODE REVIEW

**Comment by ryan953** [comment]
Is there a way to do this in more than 1 PR? 7,000 lines sounds like a recipe for PR conflicts across the board.

**Comment by anonrig** [comment]
> Is there a way to do this in more than 1 PR? 7,000 lines sounds like a recipe for PR conflicts across the board.

This change was done through `yarn lint --fix`, so no human intervention. I'm not sure if there's anything we could do.

**Comment by ryan953** [comment]
It's good to know that it was automatic, that changes how I would approach reviewing the files.

But since it's so large, it really seems like it is touching every single TS file, and therefore every open PR will need to resolve conflicts. It'd be nice if there were some options to split it up, so that we could say 'oh, none of these ideas worked'.

If we're not there already, then one day we surely will be at the scale where overhauls like this are impossible to think about as a single change.

**Review by onurravli — APPROVED** [review]

**Comment by mitsuhiko** [comment]
@ryan953 this would not be the first time we land something like this. Yes it sucks, but the right way to do it is to just send an email, announce that it's going to happen, encourage people to close their PRs before the weekend and merge over the weekend. 

I think the change itself is good, and we should make it. The pain also won't get smaller breaking it into smaller PRs.

**Comment by JonasBa** [comment]
I saw you disabled import/no-duplicates. Does that have an effect on when the import error for duplicate imports it shown? I suspect previously, duplicate value imports would break at typescript whereas something like this will now fail at build time?

Example
```ts
import {Something} from "file";
import {Something} from "file";
```

In any case, I'm very much in favor of the rule. Our dependency graph is a mess that needs untangling. We are often parsing a lot of unnecessary modules as any imports bring in half the repository, slowing down our tooling. Anything that gets us closer to that is a +, especially if it is enforceable and fixable via lint rules like these.

P.S: can we make sure we do the same thing for getsentry?

**Comment by mitsuhiko** [comment]
I would propose next step here is to set a scheduled day for where we merge this and give people just a small heads up.

**Review by mitsuhiko — APPROVED** [review]

**Comment by ryan953** [comment]
@mitsuhiko i don't think this is the o Ly way to do things, especially as things get bigger, changes and open PR wise. But that's always something to reevaluate case by case

It good to know the plan is to shout it out so people know what's coming, and tell 'em how to avoid getting caught up 👍

**Comment by mitsuhiko** [comment]
It might be worthwhile adding the change here to our `ignore-refs` file: https://github.com/getsentry/sentry/blob/master/.git-blame-ignore-revs

**Comment by anonrig** [comment]
> It might be worthwhile adding the change here to our `ignore-refs` file: https://github.com/getsentry/sentry/blob/master/.git-blame-ignore-revs

Good catch. I'll update the `ignore-refs` in a follow-up pull request.

**Review by scttcper — APPROVED** [review]

**Review by davidenwang — APPROVED** [review]

**Review by malwilley — APPROVED** [review]

**Comment by mitsuhiko** [comment]
Forcing this merge as the tests cannot pass due to the size of the change set.

**Pull request merged**
