### PR TITLE
fix(n1-api-calls): Omit span URL subdomain from fingerprinting

### PR DESCRIPTION
**Pull request by gggritso**
Closes PERF-1937. Sometimes we get spans with URLs like `"http://<client>.service.io/resource"` in them. The `<client>` is a hard-to-parameterize string of some kind. This causes a fingerprint explosion if different transactions are getting data from different clients.

Omit the subdomain from fingerprinting (but leave detection alone). For fingerprinting, we actually _want_ to ignore this, and only fingerprint on the path. There's basically no scenario where an application would use the same path structure from different domains and it's _not_ an error.

### CODE REVIEW

**Review by DominikB2014 — APPROVED** [review]
A test case would probably be good to add here.

**Comment by gggritso** [comment]
Yeah I should write some fingerprinting tests, I just haven't figured out a good way to do it yet. For N+1 API we need 10 or more spans, and they're hard to construct 🤔 I have a Jira task to increase coverage, though, so I'll do that soon!

**Review by k-fish — COMMENTED** [review]
@gggritso I think the fingerprinting probably needs the most coverage since it has some permutations, doesn't `create_span` from `event_generators` do the trick for making more spans? (using the SpanBuilder?)

**Comment by gggritso** [comment]
Added test coverage in https://github.com/getsentry/sentry/pull/43732 for the sake of accuracy

**Comment by gggritso** [comment]
@DominikB2014 @k-fish merged my test coverage PR, so now _this_ PR includes a test 👍🏻

**Review by DominikB2014 — APPROVED** [review]
lgtm!

**Pull request merged**
