### PR TITLE
chore(deps): Update symbolic to 12.1.6

### PR DESCRIPTION
**Pull request by adinauer**
symbolic `12.1.6` comes with `rust-proguard` `5.0.2` which fixes some mismatching line numbers in stacktraces when ProGuard is used.

### CODE REVIEW

**Comment by adinauer** [comment]
Not sure if there's any reason why the version hasn't been bumped since `12.1.2`.

**Comment by adinauer** [comment]
Will take a look at tests

**Comment by asottile-sentry** [comment]
ah -- if the test fixes looks good I have this in #51604

**Comment by adinauer** [comment]
Closing in favor of https://github.com/getsentry/sentry/pull/51604

**Pull request closed without merging**
