### PR TITLE
Capture events per release by issue

### PR DESCRIPTION
**Pull request by dcramer**
@getsentry/infrastructure

---

This change is [Reviewable](https://reviewable.io/reviews/getsentry/sentry/3656)

### CODE REVIEW

**Comment by dcramer** [comment]
@tkaemming

**Comment by mattrobenolt** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/sentry/tsdb/base.py, line 65 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/3656#-KM2RRbyCnABWMBHIg6X:-KM2RRbz_Fh6h8oOOKC8:1051069259) ([raw file](https://github.com/getsentry/sentry/blob/920969c9c531ea338d2484b2e2e2da82d63d279a/src/sentry/tsdb/base.py#L65)):*
> ```Python
>     frequent_issues_by_project = 404
>     # number of events seen for a release, by issue
>     frequent_events_by_release = 405
> ```

I'm not super familiar with this tsdb stuff, but wouldn't this stat accurately be `frequent_issues_by_release` since the metric is for the entire group? But it's possible that I'm misunderstanding what the counter is. In that case, +1.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3656)*

**Comment by mattrobenolt** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3656)*

**Comment by mattrobenolt** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/sentry/tsdb/base.py, line 65 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/3656#-KM2RRbyCnABWMBHIg6X:-KM2TI2BDJrpKSWnFgEE:1826346) ([raw file](https://github.com/getsentry/sentry/blob/920969c9c531ea338d2484b2e2e2da82d63d279a/src/sentry/tsdb/base.py#L65)):*
<details><summary><i>Previously, mattrobenolt (Matt Robenolt) wrote…</i></summary>
> I'm not super familiar with this tsdb stuff, but wouldn't this stat accurately be `frequent_issues_by_release` since the metric is for the entire group? But it's possible that I'm misunderstanding what the counter is. In that case, +1.
</details>
Trying to mark this as "Satisfied".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3656)*

**Comment by dcramer** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/sentry/tsdb/base.py, line 65 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/3656#-KM2RRbyCnABWMBHIg6X:-KM2UBad9j7a06pzBNpU:-1266579346) ([raw file](https://github.com/getsentry/sentry/blob/920969c9c531ea338d2484b2e2e2da82d63d279a/src/sentry/tsdb/base.py#L65)):*
<details><summary><i>Previously, mattrobenolt (Matt Robenolt) wrote…</i></summary>
> Trying to mark this as "Satisfied".
</details>
Its a count of events, not issues (which are groups)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3656)*

**Comment by tkaemming** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/sentry/tsdb/base.py, line 65 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/3656#-KM2RRbyCnABWMBHIg6X:-KM2TcKRaG2WDEyJ_23P:225517210) ([raw file](https://github.com/getsentry/sentry/blob/920969c9c531ea338d2484b2e2e2da82d63d279a/src/sentry/tsdb/base.py#L65)):*
<details><summary><i>Previously, dcramer (David Cramer) wrote…</i></summary>
> Its a count of events, not issues (which are groups)
</details>
If consistency matters*, to follow the pattern established by the other names, it'd actually be `frequent_releases_by_groups`. (Look at the other invocations in `_save_aggregate` if you don't believe me — "by" is the key of the frequency table, the word that precedes "by" establishes the key of the item in the table.)

* (I don't have a preference whether it does here one way or another.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3656)*

**Comment by tkaemming** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3656#-:-KM2VSljIdRcQab4-Vat:1417088721)*

**Comment by tkaemming** [comment]
*[src/sentry/tsdb/base.py, line 58 \[r1\]](https://reviewable.io:443/reviews/getsentry/sentry/3656#-KM2VnWgd3TcWHVoPIHq:-KM2VnWgd3TcWHVoPIHr:-1042553983) ([raw file](https://github.com/getsentry/sentry/blob/920969c9c531ea338d2484b2e2e2da82d63d279a/src/sentry/tsdb/base.py#L58)):*
> ```Python
>     # frequent_organization_rejected_by_system = 401
>     # frequent_organization_blacklisted_by_system = 402
>     # frequent_values_by_issue_tag = 405
> ```

Not sure if there's anything in this key that hasn't already been evicted, but might make sense to make the new key 406 to be safe (or delete this one.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3656)*

**Comment by mitsuhiko** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3656)*

**Comment by tkaemming** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry/3656)*

**Pull request merged**
