### PR TITLE
Better logo in dark mode

### PR DESCRIPTION
**Pull request by mwarkentin**
This uses Github's support for [specifying which theme an image should be shown to](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to).

### Before:

image

### After:

image

### CODE REVIEW

**Review by billyvg — APPROVED** [review]
Oh neat

**Review by dashed — APPROVED** [review]

**Comment by chadwhitacre** [comment]
There was some attempt at this in the SDKs that I think was inconclusive. @bruno-garcia @AbhiPrasad Do you remember? I think it was a third-party contribution.

**Comment by untitaker** [comment]
https://github.com/getsentry/sentry-python/pull/1342

**Comment by mwarkentin** [comment]
@untitaker @chadwhitacre Thanks! Do we render the docs for this repo anywhere else that this would be a concern?

**Comment by mwarkentin** [comment]
Closing until there's better support in other places that these docs are published.

**Pull request closed without merging**
