### PR TITLE
feat: Add the `kafka-options` decorator

### PR DESCRIPTION
**Pull request by lynnagara**
This is intended to replace the `batching_kafka_options` decorator for consumers that don't actually do batching. Eventually, `batching_kafka_options` should be updated to only include those options actually related to batching (i.e. --max-batch-size and --max-batch-time).

This PR also updates the indexer to remove some of the options being passed. There were previously way too many types of batching options being passed in here, and it was very unexpected that --max-batch-size and --max-batch-time had no impact on the actual batch size but only controlled the commit policy. Configuring the commit policy separately to the batch size should not be necessary.

### CODE REVIEW

**Review by untitaker — COMMENTED** [review]
can we make this a bool flag to remove some of the options? We have duplicate CLI options with diverging documentation everywhere, it would be a shame to add more IMO

**Comment by lynnagara** [comment]
Do you mean something like:
```
def kafka_options(group, allow_force_cluster=True, include_batching_options: bool = False, default_max_batch_size: Optional[int] = None, default_max_batch_time: Optional[float] = None):
```

**Comment by lynnagara** [comment]
Btw, the duplication in CLI options is supposed to be temporary. It's only needed because getsentry currently uses `batching_kafka_options`, which needs to be changed first. My eventual plan was to remove all duplication and have only --max-batch-size and --max-batch-time in `batching_kafka_options`

**Comment by untitaker** [comment]
> Do you mean something like:

yes

alternatively, refactor batching_kafka_options to call out to kafka_options?

**Comment by lynnagara** [comment]
> alternatively, refactor batching_kafka_options to call out to kafka_options?

Done

**Review by untitaker — APPROVED** [review]

**Pull request merged**
