### PR TITLE
build(travis): use node 8.9.1 and yarn 1.3.2

### PR DESCRIPTION
**Pull request by billyvg**
This seems to decrease jest run times by > 50%

### CODE REVIEW

**Comment by mattrobenolt** [comment]
I assume we'd want to follow suit and actually use this to build the production artifacts in getsentry, right? If we only change one, it means we're running tests against a different version than we ship.

**Comment by billyvg** [comment]
Yeah definitely, just wanted to confirm performance gains on travis first.

**Comment by getsentry-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Changes to build requirements</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by benvinegar** [comment]
I think we wanted to make sure that people could build Sentry with an "old" (oldest LTS) version of Node. But ... I'm not sure how important that is.

**Review by mattrobenolt — APPROVED** [review]
As long as it works, sounds fantastic. 🥇

**Comment by billyvg** [comment]
getsentry is passing CI, and deployed/works on staging

**Pull request merged**
