### PR TITLE
feat(ui): Use a consistent "active" and "focus" states for form inputs

### PR DESCRIPTION
**Pull request by billyvg**
This change will make `theme.active` and `theme.focus` the aliases to represent an active/selected state and the focus state respectively.

The motivations behind this change are:

- Dark mode
- Consistent design for an "active" or "selected" state
- Consistent design for a "focused" state which differs from an "active" state in that "focus" is temporal.
- To make our designers happy

### CODE REVIEW

**Comment by billyvg** [comment]
Examples:

<details>
<summary>SelectControl</summary>

image

</details>

<details>
<summary>Switch - enabled</summary>

image
image


</details>
<details>
<summary>Switch - disabled</summary>

image
image


</details>

**Comment by EvanPurkhiser** [comment]
Hmm, we definitely want to change all of our colors from green / purple to pink?

**Comment by billyvg** [comment]
Here are my thoughts on this, and I'm sure @doralchan and @robinrendle have some different opinions as well:

- This isn't a hard blocker for dark mode
- I like the pink, but my only concern is that it is a bit similar to our danger/red color
- I would prefer that we have a common "active" and "focus" color for all of these elements, whatever color that may be

**Review by doralchan — APPROVED** [review]
Tied with "Fuck off, I don't care about dark mode"

**Pull request merged**
