### PR TITLE
feat(replay): Change font CSS to match Chrome Dev Tools

### PR DESCRIPTION
**Pull request by billyvg**
* Decrease font size from 12px -> 11px
* Change font family to `Menlo`

Our previous text styling was a bit too big IMO, this brings it to be the same size and font as Chrome dev tools to make it a bit more familiar feeling.

Old:
image

New:
image

### CODE REVIEW

**Review by evanpurkhiser — APPROVED** [review]

**Comment by billyvg** [comment]
> @billyvg @ryan953
> 
> Sounds arbitrary, but I want to avoid a change in font-size because this would mean diverging from the trace view. My goal for from a UI perspective is to keep these tab views as consistent as they can be, and introducing this change would run country, at least, to my goals here. The same goes for the font-family, `Roboto Mono` is our monospaced font unless Vu says otherwise.
> 
> Chrome and Firefox dev tools are a great inspiration for us, but we need to balance this with Sentry's UI style

I agree with this IRT to font family.

Re: trace view and console, they have pretty differing functions where console is *VERY* text driven and the text in traces are more used as labels. I think users would benefit from seeing a couple of more lines in the console. The change is pretty insignificant so I will not die on this hill.

**Comment by billyvg** [comment]
> @billyvg @ryan953
> 
> Sounds arbitrary, but I want to avoid a change in font-size because this would mean diverging from the trace view. My goal for from a UI perspective is to keep these tab views as consistent as they can be, and introducing this change would run country, at least, to my goals here. The same goes for the font-family, `Roboto Mono` is our monospaced font unless Vu says otherwise.
> 
> Chrome and Firefox dev tools are a great inspiration for us, but we need to balance this with Sentry's UI style

I agree with this IRT to font family.

Re: trace view and console, they have pretty differing functions where console is *VERY* text driven and the text in traces are more used as labels. I think users would benefit from seeing a couple of more lines in the console. The change is pretty insignificant so I will not die on this hill.

**Comment by Jesse-Box** [comment]
Even though this is like a two liner change, I don't think it merits the inconsistency right now. Maybe when the network tray will change my mind, but for now, I would keep it how it is.

If we want to take some inspiration from Chrome or Firefox, I would say collapsed console messages (warning as an example) would be very welcome!

**Comment by billyvg** [comment]
@Jesse-Box that is already in progress and what inspired this change: https://github.com/getsentry/sentry/pull/45990

**Pull request closed without merging**
