### PR TITLE
ref: Remove rich metadata for projects from org details

### PR DESCRIPTION
**Pull request by dcramer**

### CODE REVIEW

**Comment by dcramer** [comment]
Havent thoroughly tested this yet, but at a glance these were the only attributes that we needed to keep to have basic functionality. Goal will be to move towards where we're *only* returning projects which you have access to.

**Comment by MaxBittker** [comment]
in getsentry, we had a lot of bugs related to Subscription objects vs SubscriptionDetails objects. it's really hard to keep track of when the data fetching / managing layer in the frontend doesn't have good abstractions for this.

**Comment by dcramer** [comment]
@MaxBittker I agree but thats not a problem for today. We should use ProjectContext (or equiv) everywhere that needs project details.

**Comment by billyvg** [comment]
Wonder if there's a good way to find other tests that should be expecting ProjectSummaries

**Comment by dcramer** [comment]
@billyvg I tried to look for things using '.projects' directly, but its kind of hard to grep since we explode in different ways. Quick QA pass also didnt uncover anything obvious.

**Comment by billyvg** [comment]
What about grepping for `TestStubs.Project()`?

**Comment by dcramer** [comment]
this isnt going to work yet

**Comment by dcramer** [comment]
did some general refactoring to improve test stability here going forward

**Review by billyvg — APPROVED** [review]
wcgw

**Pull request merged**
